### ISSUE TITLE
Exceptions thrown within RequirementsTagProvider and TagTypeReportingTask

### ISSUE THREAD

**Issue by IlyasPatel** [serenity-bdd/serenity-core#1005]
**1.** Clone project https://github.com/serenity-bdd/screenplay-pattern-todomvc

**2.** Updated dependencies to 

<serenity.version>1.6.9</serenity.version> <serenity.cucumber.version>1.5.17</serenity.cucumber.version>

**3.** Run '_mvn clean install -Pcucumber_'

**After the tests are finished, 2 separate errors are thrown:**
---
WARN net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: null
java.lang.NullPointerException
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.stripRootPathFrom(FileSystemRequirementsTagProvider.java:430)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.featureTagRequirementIn(FileSystemRequirementsTagProvider.java:328)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getParentRequirementOf(FileSystemRequirementsTagProvider.java:323)
	at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:27)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:146)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementFor(BaseRequirementsService.java:63)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:170)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:164)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:109)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:230)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:32)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

----

Caused by: net.thucydides.core.reports.templates.TemplateMergeException: Parsing error in template
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.<init>(FreemarkerReportTemplate.java:27)
	at net.thucydides.core.reports.templates.FreeMarkerTemplateManager.getTemplateFrom(FreeMarkerTemplateManager.java:32)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:36)
	... 10 more
Caused by: freemarker.core.ParseException: Syntax error in template "freemarker/results-by-tagtype.ftl" in line 55, column 83:
Encountered "/", but was expecting one of:
    <STRING_LITERAL>
    <RAW_STRING>
    "false"
    "true"
    <INTEGER>
    <DECIMAL>
    "."
    "+"
    "-"
    "!"
    "["
    "("
    "{"
    <ID>
	at freemarker.core.FMParser.generateParseException(FMParser.java:5251)
	at freemarker.core.FMParser.jj_consume_token(FMParser.java:5122)
	at freemarker.core.FMParser.UnaryExpression(FMParser.java:450)
	at freemarker.core.FMParser.MultiplicativeExpression(FMParser.java:559)
	at freemarker.core.FMParser.AdditiveExpression(FMParser.java:512)
	at freemarker.core.FMParser.RangeExpression(FMParser.java:682)
	at freemarker.core.FMParser.RelationalExpression(FMParser.java:662)
	at freemarker.core.FMParser.EqualityExpression(FMParser.java:600)
	at freemarker.core.FMParser.AndExpression(FMParser.java:745)
	at freemarker.core.FMParser.OrExpression(FMParser.java:768)
	at freemarker.core.FMParser.Expression(FMParser.java:348)
	at freemarker.core.FMParser.StringOutput(FMParser.java:1240)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3036)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.Root(FMParser.java:3432)
	at freemarker.template.Template.<init>(Template.java:208)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:495)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:409)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:261)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1786)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1646)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.<init>(FreemarkerReportTemplate.java:25)

The reports are still generated and generally look fine.

**Comment by wakaleo** [comment]
Could you try with versions 1.7.2 and 1.6.4?

**Comment by IlyasPatel** [comment]
It looks like those two errors have stopped but I still get another freemarker error:

Failed to merge template: Parsing error in template

Caused by: freemarker.core.ParseException: Syntax error in template "freemarker/results-by-tagtype.ftl" in line 55, column 83:
Encountered "/", but was expecting one of:
    <STRING_LITERAL>
    <RAW_STRING>
    "false"
    "true"
    <INTEGER>
    <DECIMAL>
    "."
    "+"
    "-"
    "!"
    "["
    "("
    "{"
    <ID>
	at freemarker.core.FMParser.generateParseException(FMParser.java:5251)
	at freemarker.core.FMParser.jj_consume_token(FMParser.java:5122)
	at freemarker.core.FMParser.UnaryExpression(FMParser.java:450)
	at freemarker.core.FMParser.MultiplicativeExpression(FMParser.java:559)
	at freemarker.core.FMParser.AdditiveExpression(FMParser.java:512)
	at freemarker.core.FMParser.RangeExpression(FMParser.java:682)
	at freemarker.core.FMParser.RelationalExpression(FMParser.java:662)
	at freemarker.core.FMParser.EqualityExpression(FMParser.java:600)
	at freemarker.core.FMParser.AndExpression(FMParser.java:745)
	at freemarker.core.FMParser.OrExpression(FMParser.java:768)
	at freemarker.core.FMParser.Expression(FMParser.java:348)
	at freemarker.core.FMParser.StringOutput(FMParser.java:1240)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3036)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.Root(FMParser.java:3432)
	at freemarker.template.Template.<init>(Template.java:208)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:495)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:409)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:261)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1786)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1646)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.<init>(FreemarkerReportTemplate.java:25)
[WARNING] SOME REPORT PAGES COULD NOT BE GENERATED
 * Failed to generate report for net.thucydides.core.reports.html.TagTypeReportingTask@54422189 - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to merge template: Parsing error in template
net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:39)

**Comment by wakaleo** [comment]
I can't reproduce this at all.

**Comment by wakaleo** [comment]
Could you provide a sample project that reproduces this issue? It doesn't seem to be happening on the demo or smoke test projects.
