### ISSUE TITLE
Action moveToElement stop working in serenity after Selenium upgraded to 3.7.0

### ISSUE THREAD

**Issue by AlexChernookov** [serenity-bdd/serenity-core#1012]
I have a method 
```
protected void moveToElement(WebElementFacade e){
         withAction().moveToElement(e).perform();
    }
```
in serenity 1.6.5 this method is working (there is a Selenium v3.5.3 ) fine but when I've updated seretiry to 1.7.0 (Selenium v.3.6.0) it stop working and throw an exception  
I did debug and find that exception is appeared class MouseAction in getActionLocation

```
public abstract class MouseAction extends BaseAction implements IsInteraction {
.........
    protected Coordinates getActionLocation() {
        return this.where == null ? null : this.where.getCoordinates();
    }
}
```
The stacktrace of exception
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.openqa.selenium.internal.Locatable
	at net.serenitybdd.core.pages.WebElementFacadeImpl.getCoordinates(WebElementFacadeImpl.java:1109)
	at org.openqa.selenium.interactions.internal.MouseAction.getActionLocation(MouseAction.java:61)
	at org.openqa.selenium.interactions.MoveMouseAction.perform(MoveMouseAction.java:43)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:36)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:641)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:594)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:425)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:410)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:385)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:133)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:472)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:447)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:252)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitSt

java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.openqa.selenium.internal.Locatable
at com.framework.AjaxPageObject.moveToElement(AjaxPageObject.java:153)

Could you please take a look and fix.
Thanks
BR Alex

**Comment by wakaleo** [comment]
I won't have time to look into this for a while, but it looks like a deprecated Selenium class in the getCoordinates() method of the WelElementFacadeImpl that needs replacing with the non-deprecated equivalent. If you can provide a pull request (with a corresponding test in WhenBrowsingAWebSiteUsingPageObjects would be nice) I will see what I can do.

**Comment by AlexChernookov** [comment]
Thanks guys :)

**Comment by cvarshn-cloud** [comment]
java.lang.ClassCastException: net.serenitybdd.core.pages.WebElementFacadeImpl cannot be cast to org.openqa.selenium.interactions.internal.Locatable

getting this error for serenity version 2.2.1 and 2.2.2

**Comment by wakaleo** [comment]
Do you have a stack trace?
