### ISSUE TITLE
FreeMarker template error

### ISSUE THREAD

**Issue by Linuxic** [serenity-bdd/serenity-core#1036]
Hi! 
This is my code

```
public class AuthenticationTest {
      @Steps
       Actor manager = new Actor("manager");
       @Managed(driver = "iexplorer", uniqueSession = true)
       private WebDriver hisBrowser;
       @Before
       public void before() {
                       manager.can(BrowseTheWeb.with(hisBrowser));
       }
       @Test
       public void shouldBeAbleToLoginAsADMIN() throws IOException {
             givenThat(manager).wasAbleTo(start(conf.URL, ""));
             when(manager).attemptsTo(
                           LogIn.as(conf.loginAdmin, conf.password, conf.standname));
             then(manager).should(
                           seeThat(SuccessResultLogin.displayed(conf.loginAdmin),
                                        is("Success")));
             and(manager).attemptsTo(LogOut.as());
       }
       @After
       public void afterTest() {
             hisBrowser.close();
             hisBrowser.quit();
       }
}
```

This is my pom.xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>ru.ui</groupId>
	<artifactId>ui-tests</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>ui-tests</name>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>1.8.0</serenity.version>
		<serenity.maven.version>1.8.0</serenity.maven.version>
		<restassured.version>2.9.0</restassured.version>
		<jackson-databind.version>2.6.4</jackson-databind.version>
		<jackson-core.version>2.6.4</jackson-core.version>
		<aspectj.version>1.8.9</aspectj.version>
		<maven-surefire-plugin.version>2.19.1</maven-surefire-plugin.version>
		<jetty-maven-plugin>9.2.10.v20150310</jetty-maven-plugin>
		<json-simple.version>1.1.1</json-simple.version>
		<guava.version>19.0</guava.version>
		<gson.version>2.7</gson.version>
		<webdriver.ie.driver>src/test/resources/webdrivers/IEDriverServer.exe</webdriver.ie.driver>
		<maven.build.timestamp.format>yyyy/MM/dd/'${hostname}'-HH-mm</maven.build.timestamp.format>
	</properties>
	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>1.8.0</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay-webdriver</artifactId>
			<version>1.8.0</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay</artifactId>
			<version>1.8.0</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>1.8.0</version>
		</dependency>
		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>2.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>rest-assured-common</artifactId>
			<version>2.9.0</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>json-schema-validator</artifactId>
			<version>2.9.0</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.6.1</version>
		</dependency>
		<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>${restassured.version}</version>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>1.7.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-report-resources</artifactId>
			<version>1.8.0</version>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-core</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.12</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven-surefire-plugin.version}</version>
				<configuration>

					<systemPropertyVariables>
						<environment>${endpoint}</environment>
						<webdriver.ie.driver>src/test/resources/webdrivers/IEDriverServer.exe</webdriver.ie.driver>
						<serenity.take.sckreenshots>disabled</serenity.take.sckreenshots>
					</systemPropertyVariables>
					<testFailureIgnore>true</testFailureIgnore>
					<argLine>-javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"</argLine>
					<properties>
						<property>
							<name>listener</name>
							<value>ru.yandex.qatools.allure.junit.AllureRunListener</value>
							<name>filename</name>
							<value>${filename}</value>
						</property>
					</properties>

				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.aspectj</groupId>
						<artifactId>aspectjweaver</artifactId>
						<version>${aspectj.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.5.1</version>
				<configuration>
					<fork>true</fork>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<systemProperties>
						<webdriver.ie.driver>33</webdriver.ie.driver>
						<surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
					</systemProperties>

				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
							<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>		
		</plugins>
	</build>
</project>

When i see error:
```
31155 [pool-2-thread-1] WARN net.thucydides.core.reports.templates.FreemarkerReportTemplate - Report generation failed
FreeMarker template error:
Java method "net.thucydides.core.reports.html.Formatter.formatWithFields(String)" takes 1 argument, but 2 was given.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${formatter.formatWithFields(step.des...  [in template "freemarker/default.ftl" in macro "step_details" at line 399, column 67]
	- Reached through: @step_details step=step step_number=s...  [in template "freemarker/default.ftl" in macro "write_step" at line 237, column 17]
	- Reached through: @write_step step=step step_number=ste...  [in template "freemarker/default.ftl" at line 451, column 17]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans.SimpleMethod.unwrapArguments(SimpleMethod.java:67)
	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72)
	at freemarker.core.MethodCall._eval(MethodCall.java:62)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Macro$Context.runMacro(Macro.java:184)
	at freemarker.core.Environment.invoke(Environment.java:701)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Macro$Context.runMacro(Macro.java:184)
	at freemarker.core.Environment.invoke(Environment.java:701)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:141)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:127)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:255)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:32)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:186)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
31160 [pool-2-thread-1] ERROR net.thucydides.core.reports.templates.FreemarkerReportTemplate - Syntax error in report template: Java method "net.thucydides.core.reports.html.Formatter.formatWithFields(String)" takes 1 argument, but 2 was given.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${formatter.formatWithFields(step.des...  [in template "freemarker/default.ftl" in macro "step_details" at line 399, column 67]
	- Reached through: @step_details step=step step_number=s...  [in template "freemarker/default.ftl" in macro "write_step" at line 237, column 17]
	- Reached through: @write_step step=step step_number=ste...  [in template "freemarker/default.ftl" at line 451, column 17]
----
	- Failed at: ${formatter.formatWithFields(step.des...  [in template "freemarker/default.ftl" in macro "step_details" at line 399, column 67]
	- Reached through: @step_details step=step step_number=s...  [in template "freemarker/default.ftl" in macro "write_step" at line 237, column 17]
	- Reached through: @write_step step=step step_number=ste...  [in template "freemarker/default.ftl" at line 451, column 17]

net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:219)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:192)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:135)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReportsFor(SerenityRunner.java:410)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReports(SerenityRunner.java:305)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:259)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@2954b5ea
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:216)
	... 11 more
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@2954b5ea
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:257)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:32)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:186)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to merge template: Failed to process FreeMarker template
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:39)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:141)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:127)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:255)
	... 7 more
Caused by: net.thucydides.core.reports.templates.TemplateMergeException: Failed to process FreeMarker template
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:45)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
	... 10 more
Caused by: freemarker.core._TemplateModelException: Java method "net.thucydides.core.reports.html.Formatter.formatWithFields(String)" takes 1 argument, but 2 was given.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${formatter.formatWithFields(step.des...  [in template "freemarker/default.ftl" in macro "step_details" at line 399, column 67]
	- Reached through: @step_details step=step step_number=s...  [in template "freemarker/default.ftl" in macro "write_step" at line 237, column 17]
	- Reached through: @write_step step=step step_number=ste...  [in template "freemarker/default.ftl" at line 451, column 17]
----
	at freemarker.ext.beans.SimpleMethod.unwrapArguments(SimpleMethod.java:67)
	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72)
	at freemarker.core.MethodCall._eval(MethodCall.java:62)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Macro$Context.runMacro(Macro.java:184)
	at freemarker.core.Environment.invoke(Environment.java:701)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Macro$Context.runMacro(Macro.java:184)
	at freemarker.core.Environment.invoke(Environment.java:701)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
	... 11 more
`


```

**Comment by wakaleo** [comment]
Could you provide a sample project?

**Comment by Linuxic** [comment]
@wakaleo, My project https://github.com/Linuxic/ru.ui.git

**Comment by wakaleo** [comment]
Thanks for the demo project. The problem with the demo project is an inconsistent version of the `serenity-report-resource` dependency, which does not match the other serenity dependencies.

**Comment by Linuxic** [comment]
Thanks a lot
