### ISSUE TITLE
JUnit 5 supported SerenityRunner 

### ISSUE THREAD

**Issue by mfgor** [serenity-bdd/serenity-core#1039]
When I try to annotate my tests by Junit 5 @Test annotation they fail with the following error:
`java.lang.Exception: No runnable methods
	at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:191)
	at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at net.serenitybdd.junit.runners.SerenityRunner.<init>(SerenityRunner.java:153)
	at net.serenitybdd.junit.runners.SerenityRunner.<init>(SerenityRunner.java:109)
	at net.serenitybdd.junit.runners.SerenityRunner.<init>(SerenityRunner.java:93)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder.buildRunner(DefensiveAllDefaultPossibilitiesBuilder.java:74)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.vintage.engine.discovery.TestClassRequestResolver.createRunnerTestDescriptor(TestClassRequestResolver.java:54)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.lambda$discover$0(VintageDiscoverer.java:53)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:55)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:65)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:62)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

I assume it happens because SerenityRunner is extended from BlockJUnit4ClassRunner. Is it possible to add support for JUnit 5 library?

**Comment by wakaleo** [comment]
JUnit 5 is currently not supported. Support for JUnit 5 is a substantial change with potentially non-backward compatible changes, so there is no ETA on this at this stage.

**Comment by apodkutin** [comment]
Hi @wakaleo . Do you have any changes in Serenity development roadmap, regarding JUnit 5 support?

**Comment by apodkutin** [comment]
Unfortunately no, at this moment I'm just wondering, because I want to migrate from JUnit4 to JUnit 5 in the project which using Serenity.

**Comment by wakaleo** [comment]
We have started investigating but it’s a massive change (basically a new product) and so writing the junit5 module is a very big job. It’s not just a modification of serenity-JUnit, it’s an entirely new module.

**Comment by apodkutin** [comment]
Yes, I understand, I think it's impossible to make a modification in serenity-JUnit, because there is no backward compatibility and you have to rewrite Runners to Extensions and definitely it will be a new module.

**Comment by fabianlinz** [comment]
In the context of a company internal Hackathon we started to create a Junit5 module. Simple use cases (which actually cover the needs of some of our self-contained-systems) are working (e.g. step injection, page injection, report generation for successful and failing tests). 

To cover the full feature set of the Junit4 runner, there is (as wakaleo already pointed out) quite some work to be done and overlap to Junit5 features would need to be investigated (e.g. parameterized tests). Another open point we only started to look into, is that serenity-core and serenity-model have a dependency to Junit4.  Our current plan is to do some clean-up and then make available what we’ve got.

In case others are interested in this as well, we would be glad to join forces…

Some background on the motivation:
Serenity is used by a couple of our teams. Plain unit tests for Java stuff are nowadays written with Junit5. For the teams using Junit to declare the Serenity scenarios, the difference is sometimes troublesome (e.g. Junit5 does not require public methods and classes; different extension mechanism: Rule vs. Extension). So, we would be happy to see Junit5 support in Serenity.

**Comment by wakaleo** [comment]
@fabianlinz Are you on https://serenity-bdd.rocket.chat? I would love to see how we can get this into the Serenity code base and help expand it.

**Comment by mimatache** [comment]
Hello, if there is a project started for this I would also like to contribute to this if possible :)

**Comment by wakaleo** [comment]
There is a channel on  https://serenity-bdd.rocket.chat on this topic.

**Comment by divisathyan** [comment]
Is Serenity supported in Junit5 now?

**Comment by wakaleo** [comment]
> Is Serenity supported in Junit5 now?

No, but you can run Serenity tests with JUnit 5 in legacy mode.

**Comment by fabianlinz** [comment]
@divisathyan depends on what you are actually looking for... 

Serenity BDD itself allows you to write scenarios in JUnit4 style/syntax. Those can be executed by Junit4 or the Junit5 `junit-vintage-engine` (so Serenity BDD support running tests on the Junit5 platform).

Last year we implemented an initial version for writing Serenity BDD tests in JUnit5 Jupiter style/syntax (see https://github.com/fabianlinz/serenity-junit5#why-junit5-support-for-serenity-bdd for the original motivation) (without any dependency to JUnit4 at compile or runtime). But this is not part of Serenity BDD and does not cover all Serenity BDD features. As there was limited community interest so far and the feature set covers out needs (= we use the library for automated acceptance test in some systems for a year now) there is not much activity.
