### ISSUE TITLE
@Steps annotation not automatically instantiating the class and null pointer exception at getDriver()

### ISSUE THREAD

**Issue by samangipudi** [serenity-bdd/serenity-core#1044]
Steps annotation not instantiating the class automatically instead throwing a null pointer exception. I instantiated the class then it throws NullPointerException at getDriver() method in ScenarioSteps class.

Using Serenity core - 1.8.1
          Serenity Maven - 1.8.1
          Serenity JBehave - 1.18.0

**Comment by wakaleo** [comment]
Have you tried with the most recent version of serenity-jbehave (1.1.34)?

**Comment by samangipudi** [comment]
1.1.34?? If you meant 1.34.0 then yes I tried with that version. With the latest version it throws 
java.lang.NoSuchMethodError: org.jbehave.core.configuration.ParanamerConfiguration.useTableTransformers(Lorg/jbehave/core/model/TableTransformers;)Lorg/jbehave/core/configuration/Configuration;
	at net.serenitybdd.jbehave.SerenityJBehave.defaultConfiguration(SerenityJBehave.java:45)
	at net.serenitybdd.jbehave.SerenityStories.configuration(SerenityStories.java:78)
	at org.jbehave.core.ConfigurableEmbedder.configuredEmbedder(ConfigurableEmbedder.java:118)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.<init>(SerenityReportingRunner.java:74)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.<init>(SerenityReportingRunner.java:68)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by wakaleo** [comment]
What version of JBehave are you using?

**Comment by samangipudi** [comment]
JBehave Core version : 4.0.5

**Comment by wakaleo** [comment]
Try with 4.1.3, or let serenity-jbehave decide the version.

**Comment by samangipudi** [comment]
I changed the JBehave version to 4.1.3 and Serenity JBehave to 1.34.0
Now I get 
Failed to run story stories/payment/payment_page_make_payments.story
java.lang.AbstractMethodError
	at net.thucydides.core.steps.StepEventBus.testStarted(StepEventBus.java:147)
	at net.serenitybdd.jbehave.SerenityReporter.startScenarioCalled(SerenityReporter.java:530)
	at net.serenitybdd.jbehave.SerenityReporter.beforeScenario(SerenityReporter.java:195)
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeScenario(DelegatingStoryReporter.java:58)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeScenario(ConcurrentStoryReporter.java:167)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:892)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by samangipudi** [comment]
Could you please suggest to me the compatible versions of Serenity Core, Serenity JBehave and Serenity Maven? Don't have to be the latest versions but compatible with each other.

**Comment by wakaleo** [comment]
Try with serenity-core 1.8.1, serenity-maven 1.8.1 and serenity-jbehave 1.34.0. Alternatively, use serenity-cucumber, cucumber-jvm is more stable.

**Comment by samangipudi** [comment]
I am using the same set of versions. At present my project is in JBehave with Serenity BDD. So I cannot change it to Cucumber.

Given set of versions are not compatible and throwing RunTimeException.

**Comment by wakaleo** [comment]
It is most likely a dependency conflict. Can you provide a sample project?

**Comment by samangipudi** [comment]
Is runner class looks good?
Runner Class: 

public class AcceptanceTestSuite extends SerenityStories {

	public AcceptanceTestSuite() {
		
	}

	@Override
	public List<String> storyPaths() {
		return Arrays.asList(				
		"stories/payment/payment_page_make_payments.story"
				);
	}

	@Override
	public void run() throws Throwable {
		super.run();
	}

**Comment by samangipudi** [comment]
here is the pom file

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>myaccount-pom</artifactId>
	<packaging>pom</packaging>

	<parent>  
		<groupId>com.pch.payonline</groupId>   
		<artifactId>PayOnlineAutomation</artifactId>
		<version>1.0</version>
		<relativePath>pom.xml</relativePath>
	</parent>

	<modules>
		<module>common</module>
		<module>myaccount</module>
	</modules>
 
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>1.8.1</serenity.version>
		<serenity.maven.version>1.8.5</serenity.maven.version>
		<serenity.jbehave.version>1.34.0</serenity.jbehave.version>
		<serenity.outputDirectory>${report.dir}/serenity-reports</serenity.outputDirectory>
		<serenity.sourceDirectory>target/site/serenity</serenity.sourceDirectory>
	</properties>





	<dependencies>

		<dependency>
			<groupId>com.pch.payonline</groupId>
			<artifactId>common</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jbehave</artifactId>
			<version>${serenity.jbehave.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-report-resources</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.vase4kin</groupId>
			<artifactId>serenity-teamcity-steplistener</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
    		<groupId>com.browserstack</groupId>
    		<artifactId>browserstack-local-java</artifactId>
    		<version>1.0.2</version>
		</dependency>

 	</dependencies>

<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<configuration>
					<skip>true</skip>
					<systemPropertyVariables>
						<environment>${environment}</environment>
					</systemPropertyVariables>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.19</version>
				<configuration>
					<SystemPropertyVariables>
						<environment>${environment}</environment>
					</SystemPropertyVariables>
					<disableXmlReport>true</disableXmlReport>
					<includes>
    	         			<include>**/AcceptanceTestSuite.java</include>                  
					</includes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
	  		<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			

	
		</plugins>
		<pluginManagement>
			<plugins>
				
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>com.github.webdriverextensions</groupId>
										<artifactId>webdriverextensions-maven-plugin</artifactId>
										<versionRange>[1.0,)</versionRange>
										<goals>
											<goal>install-drivers</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<execute>
											<runOnConfiguration>true</runOnConfiguration>
											<runOnIncremental>true</runOnIncremental>
										</execute>
									</action>
								</pluginExecution>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.bsc.maven</groupId>
										<artifactId>maven-processor-plugin</artifactId>
										<versionRange>[2.2.4,)</versionRange>
										<goals>
											<goal>process-test</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<execute>
											<runOnConfiguration>true</runOnConfiguration>
											<runOnIncremental>true</runOnIncremental>
										</execute>
									</action>
								</pluginExecution>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.codehaus.mojo</groupId>
										<artifactId>build-helper-maven-plugin</artifactId>
										<versionRange>[1.9.1,)</versionRange>
										<goals>
											<goal>add-test-source</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>

**Comment by wakaleo** [comment]
I can't do much with a pom.xml file alone, except conclude that this is probably a project-specific issue. Can you reproduce the issue in a sample project?

**Comment by samangipudi** [comment]
I tired creating a sample project with the same pom file which my original project has. It works with no problem. Why is that? what could be the reason for the failure/exception?

**Comment by wakaleo** [comment]
That helps eliminate basic errors, and probably narrows it down to a project-related configuration issue or bug. Try progressively building up the sample project with your real code until you see what breaks it. If you need specific help, I would be happy to take a look at your project, but it would have to be as part of a suppor ticket or support contract (see https://johnfergusonsmart.com/serenity-bdd-mentoring/).

**Comment by samangipudi** [comment]
[ExampleProject.zip](https://github.com/serenity-bdd/serenity-core/files/1511440/ExampleProject.zip)

Here is the sample project having the issue I stated. 
FYI Same Project works with Serenity Core Version: 1.5.11
Serenity Maven Version  : 1.5.11
Serenity JBehave Version : 1.18.0

Hope this helps you in finding the issue.

**Comment by wakaleo** [comment]
I can certainly have a look at this for you, and it appears minor enough to fit in the "Per-Incident Support" model (https://johnfergusonsmart.com/serenity-bdd-mentoring/#support). Could you reach out to me on the email address on the https://johnfergusonsmart.com site with your company details, and I will get a single incident support contract prepared.

**Comment by samangipudi** [comment]
Sure
