### ISSUE TITLE
nullpointer exception while running whole feature file with scenario outline at the end of the feature file

### ISSUE THREAD

**Issue by Prasannajnaeyulu** [serenity-bdd/serenity-core#1067]
Serenity Reporter throwing NPE. This is happening if **Scenario Outline**  was at the last in a feature file. If it's at the beginning then all scenarios are executing without any issues.

Feature File example template:
 **Feature:**
          <some description here...>  
    **Scenario:**
         <some steps here....>
    **Scenario:**
           <some steps here....>
    **Scenario:**
           <some steps here...>
    **Scenario Outline:**
           <some steps here...>

Feature: Areas  Time elapsed: 22.407 sec  <<< ERROR!
java.lang.NullPointerException: null
        at cucumber.runtime.formatter.SerenityReporter.startExample(SerenityReporter.java:575)                                                                                                    at cucumber.runtime.formatter.SerenityReporter.handleTestCaseStarted(SerenityReporter.java:245)                                                                                           at cucumber.runtime.formatter.SerenityReporter.lambda$new$1(SerenityReporter.java:130)
        at cucumber.runner.EventBus.send(EventBus.java:28)
        at cucumber.api.TestCase.run(TestCase.java:55)                                               at cucumber.runner.Runner.runPickle(Runner.java:80)
        at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)                      at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)                      at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)                          at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:99)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)                                    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:108)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)                                 at org.junit.runners.Suite.runChild(Suite.java:127)
        at org.junit.runners.Suite.runChild(Suite.java:26)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)                         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)                           at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:107)                                                                                    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:88)                                                                                             at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:57)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)                                                                                   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)                                                                                                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by Prasannajnaeyulu** [comment]
using serenity core 1.8.1 version

**Comment by wakaleo** [comment]
I'm not seeing this behaviour in the smoketests, could you check with serenity-core 1.8.11 and serenity-cucumber 1.6.7?

**Comment by Prasannajnaeyulu** [comment]
I am using serenity cucumber 1.6.3 and serenity-core 1.8.1. Let me check by changing serenity cucumber to 1.6.7 then.Thanks for your swift repsponse

**Comment by Prasannajnaeyulu** [comment]
no luck same error with serenity-cucumber 1.6.7

**Comment by wakaleo** [comment]
Could you post the stack trace (it will be different for 1.6.7)

**Comment by Prasannajnaeyulu** [comment]
java.lang.NullPointerException: null
        at cucumber.runtime.formatter.SerenityReporter.startExample(SerenityReporter.java:619)
        at cucumber.runtime.formatter.SerenityReporter.handleTestCaseStarted(SerenityReporter.java:253)
        at cucumber.runtime.formatter.SerenityReporter.lambda$new$1(SerenityReporter.java:143)
        at cucumber.runner.EventBus.send(EventBus.java:28)
        at cucumber.api.TestCase.run(TestCase.java:55)
        at cucumber.runner.Runner.runPickle(Runner.java:80)
        at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:99)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:108)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.junit.runners.Suite.runChild(Suite.java:127)
        at org.junit.runners.Suite.runChild(Suite.java:26)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:88)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:57)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by wakaleo** [comment]
Could you provide a sample project that reproduces the issue? I'm not seeing it here.

**Comment by Prasannajnaeyulu** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.sample</groupId>
	<artifactId>sample-auto</artifactId>
	<version>0.0.1</version>
	<packaging>jar</packaging>
	<name>Sample Web Automation</name>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>1.8.1</serenity.version>
		<serenity.maven.version>1.8.1</serenity.maven.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>2.1.0</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>2.1.0</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-jvm</artifactId>
			<version>2.1.0</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.6.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.11</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>1.6.7</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.13</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.13</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18</version>
				<dependencies>
					<dependency>
						<groupId>org.apache.maven.surefire</groupId>
						<artifactId>surefire-junit47</artifactId>
						<version>2.18</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
</build>
<profiles>
		<profile>
			<id>parallel</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<build>
				<plugins>
					
					<plugin>
						<groupId>com.github.temyers</groupId>
						<artifactId>cucumber-jvm-parallel-plugin</artifactId>
						<version>4.2.0</version>
						<executions>
							<execution>
								<id>generateRunners</id>
								<phase>validate</phase>
								<goals>
									<goal>generateRunners</goal>
								</goals>
								<configuration>
									
									
									<glue>
<package>com.sample.test.stepdefinitions</package>
									</glue>
									<featuresDirectory>src/test/resources/features</featuresDirectory>
									<cucumberOutputDir>${project.build.directory}</cucumberOutputDir>
									<customVmTemplate>src/test/resources/cucumber-custom-runner.vm</customVmTemplate>
									<format>json</format>
									
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.7.0</version>
						<configuration>
							<source>1.8</source>
							<target>1.8</target>
						</configuration>
					</plugin>
					<plugin>
						<groupId>net.serenity-bdd.maven.plugins</groupId>
						<artifactId>serenity-maven-plugin</artifactId>
						<version>${serenity.maven.version}</version>
						<dependencies>
							<dependency>
								<groupId>net.serenity-bdd</groupId>
								<artifactId>serenity-core</artifactId>
								<version>${serenity.version}</version>
							</dependency>
						</dependencies>
						
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>2.18</version>
						<dependencies>
							<dependency>
								<groupId>org.apache.maven.surefire</groupId>
								<artifactId>surefire-junit47</artifactId>
								<version>2.18</version>
							</dependency>
						</dependencies>
						<configuration>
							<forkCount>5</forkCount>
							<reuseForks>true</reuseForks>
							<includes>
								<include>**/Parallel*IT.class</include>
							</includes>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>

**Comment by wakaleo** [comment]
I mean a full project, not just the pom.xml file.

**Comment by Prasannajnaeyulu** [comment]
I can't share a code. But, I can give you a context...
I am using cucumber-jvm for parallel execution and using custom vm template to convert junit tests to run with cucumberWithSerenity. Which is generating a runner class as below. The output is written to 1.json file.

import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
strict = true,
features = {"C:/workspace/web-automation/src/test/resources/features/sample.feature"},
plugin = {"json:C:/workspace/web-automation/target/1.json"},
monochrome = false,
tags = {"~@pending"},
glue = {"com.web.auto.stepdefinitions"})
public class Parallel01IT {
}

**Comment by wakaleo** [comment]
I think your best bet in that case is to place a breakpoint in the SerenityReporter class, see what is going on and why the example table is not being populated.

**Comment by Prasannajnaeyulu** [comment]
Yeah. That's a cool idea. I will check that once I get some free time.  Scratched my head since morning with the other reporting issues where cucumber jvm is reporting 18 tests executed. But, serenity aggregate report showing only 16. The issue was just concluded. Its because two other scenarios have got the same name. So, it's aggregating all three into one. I am copy pasting the scenarios and changing the steps but forgetting to change the names :) crazy thing which killed my half day :) Its my bad though :)

**Comment by wakaleo** [comment]
Thanks for the update; effectively, duplicate scenario names are not supported.
