### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/internal/Locatable

### ISSUE THREAD

**Issue by JohannesDorn** [serenity-bdd/serenity-core#1080]
I have tried using Serenity to create Selenium tests in Gherkin files.
When running my tests, I get a NoClassDefFoundError:

Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/internal/Locatable

My POM has dependencies on _net.serenity-bdd:serenity-core:1.8.21_ and _net.serenity-bdd:serenity-junit:1.8.21_ as well as _net.serenity-bdd:serenity-cucumber:1.6.10_.

The problem seems to be that _net.serenitybdd.core.pages.WebElementFacade_ imports _org.openqa.selenium.interactions.internal.Locatable_ but Locatable is actually in _org.openqa.selenium.internal.Locatable_.

**Comment by wakaleo** [comment]
That error would be due to a dependency conflict in your project, most likely an older version of Serenity.

**Comment by wakaleo** [comment]
It looks like a selenium library version conflict

**Comment by JohannesDorn** [comment]
I agree. Do you know which version of Selenium is compatible? I have tried to find a version that has the required _org/openqa/selenium/interactions/internal/Locatable_ but to no avail.

**Comment by wakaleo** [comment]
I think it is 3.8.1, but the simplest is usually just to let Serenity bring it in

**Comment by JohannesDorn** [comment]
That's what I am doing.

I've executed _mvn dependency:tree_ and interestingly, _selenium-api_ is brought in in version 2.53.1 rather than 3.8.1 which explicitly asked for in the serenity-core POM. _selenium-api_ is where Locatable lives. The 3.8.1 version has it at the correct location.
 
I am at a loss why 2.53.1 is brought in. Some dependencies are brought in as 2.53.1, some as 3.8.1.

**Comment by wakaleo** [comment]
There is most likely a dependency in your pom that uses selenium 2.53, which is taking precedence.

**Comment by wakaleo** [comment]
Closing due to lack of activity.

**Comment by imram** [comment]
@wakaleo  I am also getting exact same issue.  Pl find my pom file. Made sure my Local Repo is Completely Deleted to ensure there is not previous version. 

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>aa.ct.fly</groupId>
        <artifactId>merchandising-bff</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>com.sample.me</groupId>
    <artifactId>service-bff-acceptance-test</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.8.21</serenity.version>
        <serenity.cucumber.version>1.6.10</serenity.cucumber.version>
        <webdriver.driver>firefox</webdriver.driver>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity</artifactId>
            <version>1.7</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <includes>
                        <include>**/*.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

Getting Error:
Running features.offers.BagOffers
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.288 sec <<< FAILURE! - in features.offers.BagOffers
initializationError(features.offers.BagOffers)  Time elapsed: 0.005 sec  <<< ERROR!
**java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/internal/Locatable**
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.interactions.internal.Locatable

As you mentioned, it is picking up Selenium selenium-api-2.53.1 instead of 3.8.1 which is dependency for latest serenity core.

Please advise the fix for this conflict

**Comment by imram** [comment]
I explicitly added dependencies for all selenium artifacts wqith version 3.8.1 in my pom, I could see that now the Locatable is referencing the lib 3.8.1 only, but now I am getting following error:
features.eligibility.BagEligibility  Time elapsed: 0.032 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver


Results :

Tests in error: 
  Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver
  Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver
  Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver
  Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver
  Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver
  org/openqa/selenium/internal/Killable
  BagEligibility.features.eligibility.BagEligibility » NoClassDefFound Could not...
  FulfillBagOffers.features.fulfillment.FulfillBagOffers » NoClassDefFound Could...
  BagOffers.features.offers.BagOffers » NoClassDefFound Could not initialize cla...

Tests run: 9, Failures: 0, Errors: 9, Skipped: 0

**Comment by imram** [comment]
Just an FYI, I am testing my microservice using Serenity BDD with Cucumber. If it has nothing to do with Selenium/ Browser based testing, ideally core libs should have been modularized such a way that it should not have even downloaded anything related to Selenium. Just a thought!!

**Comment by wakaleo** [comment]
Do you have a stack trace?

**Comment by imram** [comment]
Hi John,

I was trying to reproduce the Error at home so that I could send you. I am unable to reproduce it and everything seems working fine, not sure but it seems as you had indicated in comments, I was getting version conflicts may be because I was in office and the dependency was not downloading properly(may be corporate firewall/ nexus repo) etc was not letting it download all clean.

For now, things look good, I will retry again in office tomorrow. If it had something to do with connectivity in there.

Thank you again for patiently answering all our questions.

**Comment by Hendrione** [comment]
try to create project using 3 words on groupId. like
com.exercise.automation. I have issue when creating serenity using 2 words
only when using serenity-jbehave-archetype

**Comment by ampie** [comment]
Just a quick comment on this one. I encountered this error because I used Spring Boot's parent pom, which fixes the Selenium version to 2.53.1 in its <dependencyManagement> section. Overriding the <selenium.version> property to be 3.10.0 (or whichever version is compatible with Serenity) in my own pom fixed the problem for me. Hope this helps.

**Comment by hanselcream** [comment]
Having a problem with IntelliJ + Maven, can open chrome or run automation due to Problem occur.

Here is the problem
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/HasTouchScreen
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at TestPlan.<clinit>(TestPlan.java:8)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.interactions.HasTouchScreen
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more

Process finished with exit code 1

**Comment by hanselcream** [comment]
pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>maven-project</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>3.141.59</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.6.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>3.0.0-M5</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>4.4.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.cassandra</groupId>
            <artifactId>cassandra-all</artifactId>
            <version>0.8.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>19</maven.compiler.source>
        <maven.compiler.target>19</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>

**Comment by hanselcream** [comment]
I have 4 Classes

1) PageObject
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.PageFactory;

public class PageObject {
        protected WebDriver driver;

        public PageObject(WebDriver driver){
            this.driver = driver;
            PageFactory.initElements(driver, this);
        }
    }

2) Utils

public class Utils {
    final static String BASE_URL = "https://formy-project.herokuapp.com/form";
    final static String CHROME_DRIVER_LOCATION = "chromedriver.exe";

3) Webform

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

public class WebForm extends PageObject{

    private final String FIRST_NAME = "First Name";
    private final String LAST_NAME = "Last Name";

    @FindBy(id = "first-name")
    private WebElement first_name;

    @FindBy(id = "last-name")
    private WebElement last_name;

    @FindBy(xpath = "//a[contains(text(),'Submit')]")
    private WebElement submit_button;

    public WebForm(WebDriver driver) {
        super(driver);
    }

    public void enterFirstName(){
        this.first_name.sendKeys(FIRST_NAME);
    }

    public void enterLastName(){
        this.last_name.sendKeys(LAST_NAME);
    }

    public void pressSubmitButton(){
        this.submit_button.click();
    }
}

4) TestPlan (where i run my automation)
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

public class TestPlan {
    private static final WebDriver driver = new ChromeDriver();

    @BeforeSuite
    public static void main(String[] args) {
        // ChromeDriver location set up in Utils class
        System.setProperty("webdriver.chrome.driver", Utils.CHROME_DRIVER_LOCATION);
    }

    @Test(testName = "Submit a WebForm")
    public static void submitForm(){
        driver.get(Utils.BASE_URL);
        WebForm webForm = new WebForm(driver);
        webForm.enterFirstName();
        webForm.enterLastName();
        webForm.pressSubmitButton();
    }

    @AfterSuite
    public static void cleanUp(){
        driver.manage().deleteAllCookies();
        driver.close();
    }
}
