### ISSUE TITLE
Overriding storyPaths does not seem to work, if the story file is in a separate jar

### ISSUE THREAD

**Issue by mithuns** [serenity-bdd/serenity-core#1094]
Hi, 

My project structure is in a way, that I have a util project which helps with common tasks, such as creation of some dummy data, and it gets used across several test projects , I have my story file placed inside this jar  
at 
    src/main/resources/stories/my_story.story
location.

Here is the code that I have 

```
package com.Private.service.test.bdd;

import org.jbehave.core.io.CodeLocations;

import net.serenitybdd.jbehave.SerenityStories;

/**
 * The Class AcceptanceTests.
 */
public class AcceptanceTests extends SerenityStories {

    /**
     * {@inheritDoc}
     */
    @Override
    public List<String> storyPaths() {
        final String codeLocation = CodeLocations.codeLocationFromClass(ImportedClassFromAnotherJar.class).toString();
        return Arrays.asList(codeLocation + "!/stories/my_story.story");
    }
}
```

This is the error I get

```
org.jbehave.core.io.StoryResourceNotFound: Story path 'file:/C:/Users/mithuns/.m2/repository/fully-qualified-path-to-jar-1.0-SNAPSHOT/util-jar-1.0-SNAPSHOT.jar!/stories/my_story.story' not found by class loader sun.misc.Launcher$AppClassLoader@3cd1f1c8
	at org.jbehave.core.io.LoadFromClasspath.resourceAsStream(LoadFromClasspath.java:80)
	at net.serenitybdd.jbehave.UTF8StoryLoader.loadResourceAsText(UTF8StoryLoader.java:13)
	at org.jbehave.core.io.LoadFromClasspath.loadStoryAsText(LoadFromClasspath.java:74)
	at org.jbehave.core.embedder.StoryRunner.storyOfPath(StoryRunner.java:194)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.addStories(SerenityReportingRunner.java:285)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.buildDescriptionFromStories(SerenityReportingRunner.java:266)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.getDescriptions(SerenityReportingRunner.java:79)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.getDescription(SerenityReportingRunner.java:126)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:85)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)



```

Can someone please help me , as to if this is not supported or is it a bug ?
I dont want to do the loading stories from a URL, since that url is also absolute since I can have different branches of code trying to run stories or refer to stories, I want to keep it generic, so that if a util dependency is added, I can simply load story files from that common shared jar.

**Comment by wakaleo** [comment]
This is not supported, as JBehave cannot read story files from JAR files.

Actually, this is an example of a common but very bad JBehave anti-pattern - you should **never** use stories as reusable tasks; it takes away from the communication value of the stories, and is harder to maintain. For such reusable tasks, use Serenity step libraries or Screenplay Task objects instead.

**Comment by mithuns** [comment]
I am in a situation where I am supposed to run the same tests , but through two different ways, lets say I have an actual implementation jar, then I create a test jar, which tests my implementation jar, then I package it as a java assembly, then I have another jar which has added capability to test my deployed jar ( it calls the server, do some request-reply translation for me). 
So, these story files are being duplicated at both jars, I want to put them in one place. 

I understand the misuse that can happen if JBehave allowed it. 
Does that mean JBehave should not allow it ? ( capability vs usage, one is what the api should support vs the effective and customary ways of how the community uses it.)

Second, if you can point me to some code samples for Screenplay Task object that does this, that would be great.

**Comment by wakaleo** [comment]
Closing duplicate
