### ISSUE TITLE
Serenity Report generation and display problems

### ISSUE THREAD

**Issue by s1apped** [serenity-bdd/serenity-core#1106]
Hi,

I'm using Serenity With Cucumber. After updating to newest version (1.8.21)and adding serenity-report-resources there are errors in Jenkins Console but report seems to be generating:

FreeMarker template error:
An error has occurred when reading existing sub-variable "overview"; see cause exception! The type of the containing value was: extended_hash+string (net.thucydides.core.requirements.reports.RequirementsOutcomes wrapped into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if (requirements.overview?has_content)  [in template "freemarker/requirements.ftl" at line 299, column 13]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:199)
	at freemarker.core.Dot._eval(Dot.java:40)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.ExistenceBuiltins$ExistenceBuiltIn.evalMaybeNonexistentTarget(ExistenceBuiltins.java:49)
	at freemarker.core.ExistenceBuiltins$has_contentBI._eval(ExistenceBuiltins.java:106)
	at freemarker.core.ExistenceBuiltins$has_contentBI.evalToBoolean(ExistenceBuiltins.java:112)
	at freemarker.core.ParentheticalExpression.evalToBoolean(ParentheticalExpression.java:31)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:46)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
	at net.thucydides.core.reports.html.BaseReportingTask.generateReportPage(BaseReportingTask.java:46)
	at net.thucydides.core.reports.html.RequirementsOverviewReportingTask.generateReports(RequirementsOverviewReportingTask.java:94)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:32)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
	at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:255)
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:159)
	... 21 more
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 20: src/test/resources/D:\Jenkins\workspace\

[WARNING] Report generation failed
FreeMarker template error:
An error has occurred when reading existing sub-variable "overview"; see cause exception! The type of the containing value was: extended_hash+string (net.thucydides.core.requirements.reports.RequirementsOutcomes wrapped into f.e.b.StringModel)

Wondering if it's related to below path current_project.base.dir:
[INFO] --- serenity-maven-plugin:1.8.21:aggregate (serenity-reports) @ smoke-citrus ---
[INFO] current_project.base.dir: **D:\Jenkins\workspace\...**

I have also question. How to not display Related Tags (features, issue, issues) on Report
![image](https://user-images.githubusercontent.com/32245059/35821432-43744614-0aa9-11e8-9c2d-4da79ce41c63.png)
dashboard.excluded.tag.list isn't working

**Comment by s1apped** [comment]
Solved.

**Comment by YiannisDermitzakis** [comment]
I'm also seeing this issue. Could you briefly explain how you solved it?

**Comment by s1apped** [comment]
I made quite a few changes since then but as far as I remember it was related to path to our project.
It was something like folderA\folderB\src. Once src was moved up the issue was gone.
