### ISSUE TITLE
serenity 1.8.21 : Error communicating with the remote browser. It may have died.

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#1115]
Hello @wakaleo , 

Since I updated serenity from 1.8.0 to 1.8.21, all my tests are failing with this kind of error : 
```
Logout STANDARD_ERROR
    fÚvr. 07, 2018 3:21:23 PM org.openqa.selenium.support.ui.ExpectedConditions findElements
    AVERTISSEMENT: WebDriverException thrown by findElements(By.xpath: //div[contains(@class,'tc-notification-error')])
    org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
    Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:26:55.441Z'
    System info: host: 'xxx', ip: 'x.x.x.x', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
    Driver info: driver.version: RemoteWebDriver
    Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 57.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 32220, moz:profile
: C:\Users\xxxx\AppData\Lo..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000
, script: 30000}}
    Session ID: df3e423e-909f-41ea-bb01-e4000474ccfe
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
        at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:398)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:477)
        at org.openqa.selenium.By$ByXPath.findElements(By.java:356)
        at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:359)
        at net.thucydides.core.webdriver.WebDriverFacade.findElements(WebDriverFacade.java:261)
        at org.openqa.selenium.support.ui.ExpectedConditions.findElements(ExpectedConditions.java:914)
        at org.openqa.selenium.support.ui.ExpectedConditions.access$200(ExpectedConditions.java:44)
        at org.openqa.selenium.support.ui.ExpectedConditions$8.apply(ExpectedConditions.java:232)
        at org.openqa.selenium.support.ui.ExpectedConditions$8.apply(ExpectedConditions.java:229)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
        at net.serenitybdd.core.pages.RenderedPageObjectView.waitFor(RenderedPageObjectView.java:100)
        at net.serenitybdd.core.pages.RenderedPageObjectView.elementIsDisplayed(RenderedPageObjectView.java:206)
        at net.serenitybdd.core.pages.PageObject.isElementVisible(PageObject.java:854)
        at pages.BasePage.isErrorNotifPresent(BasePage.java:84)
        at steps.UICommonSteps.checkErrorNotification(UICommonSteps.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jbehave.core.steps.StepCreator$MethodInvoker.invoke(StepCreator.java:958)
        at org.jbehave.core.steps.StepCreator$BeforeOrAfterStep.perform(StepCreator.java:624)
        at org.jbehave.core.steps.StepCreator$BeforeOrAfterStep.doNotPerform(StepCreator.java:641)
        at org.jbehave.core.embedder.PerformableTree$SomethingHappened.run(PerformableTree.java:378)
        at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1090)
        at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:995)
        at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:904)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
        at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
        at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:230)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:97)
        at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:47)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:157)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        ... 36 more
    Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        ... 59 more


runner.Logout STANDARD_OUT
    steps.UICommonSteps.checkErrorNotification() (FAILED)
    (org.jbehave.core.failures.BeforeOrAfterFailed: Method checkErrorNotification (annotated with @AfterScenario in class steps.UICommonSteps) failed: org.openqa.selenium.remote.UnreachableBrow
serException: Error communicating with the remote browser. It may have died.
    Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:26:55.441Z'
    System info: host: 'xxxx', ip: 'x.x.x.x', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
    Driver info: driver.version: RemoteWebDriver
    Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 57.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 32220, moz:profile
: C:\Users\xxxx\AppData\Lo..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000
, script: 30000}}
    Session ID: df3e423e-909f-41ea-bb01-e4000474ccfe)
    15:21:23.606 [pool-3-thread-1] DEBUG n.s.j.e.m.CompositeEmbedderMonitor - storyFailedstories/disconnexion/logout.story
    Failed to run story stories/disconnexion/logout.story
    java.lang.AssertionError: Unexpected end event for null
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestEventAdapter.testFinished(JUnitTestEventAdapter.java:121)
        at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
        at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
        at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
        at com.github.valfirst.jbehave.junit.monitoring.JUnitScenarioReporter.failed(JUnitScenarioReporter.java:270)
        at org.jbehave.core.reporters.DelegatingStoryReporter.failed(DelegatingStoryReporter.java:114)
        at org.jbehave.core.reporters.ConcurrentStoryReporter.failed(ConcurrentStoryReporter.java:307)
        at org.jbehave.core.steps.AbstractStepResult$Failed.describeTo(AbstractStepResult.java:40)
        at org.jbehave.core.embedder.PerformableTree$SomethingHappened.run(PerformableTree.java:380)
        at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1090)
        at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:995)
        at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:904)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
        at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
        at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

    (AfterStories)
```
All browsers and geckodriver remains open too.
Turn back to 1.8.0, and everything is ok.

Any idea ? 

geckodriver 0.19.0 and 0.19.1
firefox 57

**Comment by wakaleo** [comment]
This error message is pretty much always related to an incompatibility between Firefox geckodriver and the selenium version being used. Serenity is just reporting the message.

**Comment by mmanach** [comment]
Ok so there is an issue between selenium 3.7.1 and 3.9.0

**Comment by mmanach** [comment]
for information, seems the issue is known... 
https://github.com/SeleniumHQ/selenium/issues/5445

**Comment by wakaleo** [comment]
Thanks for the update, I’ll close it here then. The best approach is to let Serenity just pull in the dependencies it needs

**Comment by mmanach** [comment]
Yes, but Selenium 3.9.0 is pulled by Serenity :(

**Comment by mmanach** [comment]
@wakaleo , just one question, because I don't understand why selenium 3.9.0 is pulled for serenity 1.8.21, because the seleniumVersion is 3.8.1. Is it caused by gradle ? 
```
|    |    +--- org.seleniumhq.selenium:selenium-server:3.8.1
|    |    |    +--- org.seleniumhq.selenium:selenium-java:3.8.1 -> 3.9.0
|    |    |    |    +--- org.seleniumhq.selenium:selenium-api:3.9.0
```

**Comment by wakaleo** [comment]
Serenity uses 3.8.1, I don’t know of a Selenium version 3.9.0
