### ISSUE TITLE
Report generation failure

### ISSUE THREAD

**Issue by Bredda** [serenity-bdd/serenity-core#1121]
I have a weird issue with Serenity. Build is failing due to Report generation failure while all tests are green. Serenity seems to fail writing the JUnit report

`
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.425 sec <<< FAILURE! - in fr.mypackage.myIT
fr.mypackage.myIT  Time elapsed: 1.321 sec  <<< ERROR!
java.lang.RuntimeException: Report generation failure
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:49)
	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:207)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:191)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:135)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReportsFor(SerenityRunner.java:410)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReports(SerenityRunner.java:305)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:259)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)

Results :

Tests in error: 
  JUnit4Provider.invoke:128->executeTestSet:153->executeWithRerun:173->execute:283 » Runtime

Tests run: 8, Failures: 0, Errors: 1, Skipped: 0
`

The problem occurs only on one of our continuous integration Unix/Jenkins system. We cannot reproduce it on windows machine. Weird part is we used Serenity for ages with Unix CI pipelines and never encountered this problem before.

Started with serenity-core:1.6.9, upgrading to 1.8.21 does'nt change a thing.
No particular dependence outisde Serenity, JUnit 4.12 and AssertJ 1.7

Doesn't seem to be a access file system problem, serenity-maven-plugin is able to write in target/serenity for the aggregate goal (no test in report obviously but index and requirements files are here)

Idon't know if this is really a Serenity related issue but I am stuck here and some help would be greatly appreciated.

Thanks !

**Comment by wakaleo** [comment]
It's not related to Serenity I think (that code has not changed for a long time) - it looks like an OS-related issue. Are there any other log or error messages?

**Comment by wakaleo** [comment]
Closing due to lack of activity.
