### ISSUE TITLE
On using latest version of selenium and serenity getting - Killable cannot be resolved error

### ISSUE THREAD

**Issue by Ashvinijai** [serenity-bdd/serenity-core#1123]
After adding the latest versions of selenium and serenity 
 I am getting an error : net.serenitybdd.core.exceptions.SerenityManagedException: org/openqa/selenium/internal/Killable` 
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.Killable

Could anyone help me with this issue
I have added "selenium-htmlunit-driver" too but still it is showing that error
Is there any alternate jar ?

compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version:'3.6.1'     
	compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version:'3.9.0'
    compile group: 'net.serenity-bdd', name: 'serenity-core', version:'1.8.21'
     compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.8.21'
   compile group: 'org.seleniumhq.selenium', name: 'selenium-api', version: '3.9.0'
   compile group: 'net.serenity-bdd', name: 'serenity-gradle-plugin', version: '1.8.21'
   compile group: 'com.codeborne', name: 'selenide', version: '4.10.01'
  compile group: 'org.seleniumhq.selenium', name: 'lift', version: '3.9.0'
  compile group: 'org.seleniumhq.selenium', name: 'selenium-remote-driver', version: '3.9.0'
  compile group: 'org.seleniumhq.selenium', name: 'selenium-support', version: '3.9.0'
   compile group: 'org.seleniumhq.selenium', name: 'selenium-htmlunit-driver', version: '2.52.0'

**Comment by mmanach** [comment]
Hi, 

Seems your selenium lib versions are not good : your are pulling 'selenium-java', version:'3.6.1', and other selenium libs in version 3.9.0.
By the way selenium-htmlunit-driver 2.52.0 is quite old now.
You can let serenity pulling and managing versions of selenium.

**Comment by wakaleo** [comment]
@mmanach  is right - this is a dependency conflict, not a Serenity issue.

**Comment by Ashvinijai** [comment]
Updated the versions

 compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version:'3.9.0'     
	compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version:'3.9.0'
    compile group: 'net.serenity-bdd', name: 'serenity-core', version:'1.8.21'
     compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.8.21'
   compile group: 'org.seleniumhq.selenium', name: 'selenium-api', version: '3.9.0'
   compile group: 'net.serenity-bdd', name: 'serenity-gradle-plugin', version: '1.8.21'
  compile group: 'org.seleniumhq.selenium', name: 'lift', version: '3.9.0'
  compile group: 'org.seleniumhq.selenium', name: 'selenium-remote-driver', version: '3.9.0'
  compile group: 'org.seleniumhq.selenium', name: 'selenium-support', version: '3.9.0'
   compile group: 'org.seleniumhq.selenium', name: 'selenium-htmlunit-driver', version: '2.52.0'

For 'selenium-htmlunit-driver : 2.52.0' is the latest version

But still I am getting killable issue

**Comment by wakaleo** [comment]
You need to remove or exclude the reference to selenium-htmlunit-driver, which is defined somewhere in your pom.xml or one of its dependencies.

**Comment by mmanach** [comment]
Can you check in your dependencies tree if you have conflicts ? 
By the way, serenity is pulling selenium libs too, so can you just try with this : 
```
compile group: 'net.serenity-bdd', name: 'serenity-core', version:'1.8.21'
compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.8.21'
compile group: 'net.serenity-bdd', name: 'serenity-gradle-plugin', version: '1.8.21'
```

**Comment by Ashvinijai** [comment]
Thank You so much.Its amazing with just these dependencies it worked

compile group: 'net.serenity-bdd', name: 'serenity-core', version:'1.8.21'
compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.8.21'
compile group: 'net.serenity-bdd', name: 'serenity-gradle-plugin', version: '1.8.21'

**Comment by RaishaKhanam** [comment]
Hi,

I am trying to use  below versions in a very old project with Spring boot version(1.5.9.RELEASE)
<serenity.cucumber.version>1.8.21</serenity.cucumber.version>
        <serenity.version>1.8.21</serenity.version>
        <serenity.plugin.version>1.8.21</serenity.plugin.version>
with these I get the below exception :

Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.interactions.Locatable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:766)
        at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:683)
        at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378)
        at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:182)
        at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:661)
        at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:617)
        at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:603)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:932)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852)
        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:291)
        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:222)
        at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:938)
        at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48)
        at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:27)
        at net.serenitybdd.core.di.WebDriverInjectors.getInjector(WebDriverInjectors.java:10)
        at net.thucydides.core.webdriver.WebDriverFactory.<init>(WebDriverFactory.java:62)
        at net.thucydides.core.webdriver.WebDriverFactory.<init>(WebDriverFactory.java:56)
        at net.thucydides.core.webdriver.WebdriverProxyFactory.<init>(WebdriverProxyFactory.java:31)
        at net.thucydides.core.webdriver.WebdriverProxyFactory.getFactory(WebdriverProxyFactory.java:37)
        at net.thucydides.core.steps.BaseStepListener.<init>(BaseStepListener.java:267)
        at net.thucydides.core.steps.BaseStepListener.<init>(BaseStepListener.java:263)
        at net.thucydides.core.steps.Listeners$BaseStepListenerBuilder.withOutputDirectory(Listeners.java:37)
        at net.serenitybdd.core.SerenityListeners.<init>(SerenityListeners.java:30)
        at cucumber.runtime.formatter.SerenityReporter.initialiseListenersFor(SerenityReporter.java:112)
        at cucumber.runtime.formatter.SerenityReporter.lambda$handleTestSourceRead$0(SerenityReporter.java:149)
        at java.util.Optional.ifPresent(Optional.java:159)
        at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:144)
        at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
        at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)
        at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)
        at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:44)
        at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:234)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by RaishaKhanam** [comment]
And when I add selenium dependency the selenium dependencies I can see the cucumber tests run but with the below exception.

Selenium dependencies are:
 <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-api</artifactId>
                <version>3.14.0</version>
                <scope>test</scope>
            </dependency>

 <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-remote-driver</artifactId>
                <version>3.14.0</version>
                <scope>test</scope>
        </dependency>

Exception is:

Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.Killable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)


Can you please help.....

**Comment by wakaleo** [comment]
It's a dependency conflict - you'll need to do a dependency analysis to find a combination that works for you.
