### ISSUE TITLE
1.9.0-rc.1 :     java.lang.NoSuchMethodError: net.thucydides.core.steps.StepEventBus.getForcedResult()Lcom/google/common/base/Optional;

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#1131]
hi @wakaleo , 

I don't know if 1.9.0-rc.1 is stable enough to be tested, I wanted to validate that everything was ok with selenium 3.9.1.
So yes, serenity 1.9.0-rc.1is pulling selenium 3.9.1.

I don't have anymore the error https://github.com/serenity-bdd/serenity-core/issues/1115, because it seems that selenium 3.9.1 solved it (source : https://github.com/SeleniumHQ/selenium/issues/5458#issuecomment-364390143)

But I encounter 2 new issues : 

- in console, for each scenarios : 
```
runner.DeleteAProject STANDARD_OUT
    11:58:36.841 [pool-4-thread-1] DEBUG n.s.j.e.m.CompositeEmbedderMonitor - storyFailedstories/project/delete_a_project.story
    Failed to run story stories/project/delete_a_project.story
    java.lang.NoSuchMethodError: net.thucydides.core.steps.StepEventBus.getForcedResult()Lcom/google/common/base/Optional;
        at net.serenitybdd.jbehave.SerenityReporter.annotatedResultTakesPriority(SerenityReporter.java:743)
        at net.serenitybdd.jbehave.SerenityReporter.successful(SerenityReporter.java:716)
        at org.jbehave.core.reporters.DelegatingStoryReporter.successful(DelegatingStoryReporter.java:177)
        at org.jbehave.core.reporters.ConcurrentStoryReporter.successful(ConcurrentStoryReporter.java:257)
        at org.jbehave.core.steps.AbstractStepResult$Successful.describeTo(AbstractStepResult.java:81)
        at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:348)
        at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1090)
        at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:984)
        at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:904)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
        at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
        at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

- in report after aggregate : 

![image](https://user-images.githubusercontent.com/29480659/36092774-c7609fc4-0fe8-11e8-9bbd-7831ae78929e.png)

Only one scenario is fully played, other stop after one step, and the time duration is not ok.

Thanks,

**Comment by wakaleo** [comment]
Thanks for the update. The APIs have changed, so probably best to wait till there are updates for the Cucumber and jbehave modules as well.

**Comment by wakaleo** [comment]
Could you try with the latest in all versions?

**Comment by mmanach** [comment]
Tried with : 
- serenity 1.9.0-rc.3
- serenity jbehave 1.36.0-rc.1

Seems all is ok

**Comment by wakaleo** [comment]
Thanks for the update.
