### ISSUE TITLE
Chrome headless: Test crashes and the fail result is ignored. Serenity reports success.

### ISSUE THREAD

**Issue by HNygard** [serenity-bdd/serenity-core#1135]
I'm getting exception when trying to enable Chrome "--headless" feature. Unsure what the real error, but this Github issue ticket concerns the problem with Serenity reports. The headless error happens in connecting with open page/get current URL and the driver seems to have died/lost connection. The first problem is that Serenity reports it as all good.

In Gradle's Junit report the test is failing and contains the exception strack trace below. The Serenity report is all success.

My guess is that the exception is thrown in a particular spot that is not covered by error handling.

Serenity version: 1.8.21.

![image](https://user-images.githubusercontent.com/168380/36260048-70f44828-1260-11e8-92f8-9411cbed1eb0.png)
![image](https://user-images.githubusercontent.com/168380/36260208-f58ab720-1260-11e8-8b5b-2dd9ca512952.png)

Stacktrace (from Gradle Junit report):

	net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: Error communicating with the remote browser. It may have died.
	Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
	System info: host: 'my-jenkins-host', ip: '10.10.10.10', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_60'
	Driver info: driver.version: RemoteWebDriver
	Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.35.528161 (5b82f2d2aae0ca..., userDataDir: C:\Users\a~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 64.0.3282.167, webStorageEnabled: true}
	Session ID: 9b8c2dea7b49f1a44634ef282a5c32d1
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
		at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:335)
		at net.thucydides.core.webdriver.WebDriverFacade.currentUrlFor(WebDriverFacade.java:218)
		at net.thucydides.core.webdriver.WebDriverFacade.ignoreUndefinedErrorsIfTheUrlIsCorrectFor(WebDriverFacade.java:202)
		at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:189)
		at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:184)
		at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:840)
		at net.serenitybdd.core.pages.PageObject.open(PageObject.java:704)
		at net.serenitybdd.core.pages.PageObject.open(PageObject.java:688)
		at com.somecode.MyTestSteps.gotToPageWithParam(MyTestSteps.java:28)
		at com.somecode.MyTestSteps$$EnhancerByCGLIB$$81aac860.CGLIB$gotToPageWithParam$3(<generated>)
		at com.somecode.MyTestSteps$$EnhancerByCGLIB$$81aac860$$FastClassByCGLIB$$eda8835a.invoke(<generated>)
		at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
		at net.thucydides.core.steps.BaseMethodRunner.invokeMethod(BaseMethodRunner.java:10)
		at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:20)
		at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:362)
		at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:133)
		at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
		at com.somecode.MyTestSteps$$EnhancerByCGLIB$$81aac860.gotToPageWithParam(<generated>)
		at com.somecode.MyStory.userGoesToPageWith(MyStore.java:42)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
		at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)
		at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1090)
		at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:955)
		at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1029)
		at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:899)
		at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
		at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
		at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
		at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
		at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
		at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.io.InterruptedIOException: thread interrupted
		at okio.Timeout.throwIfReached(Timeout.java:145)
		at okio.Okio$1.write(Okio.java:76)
		at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
		at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
		at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
		at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
		at okhttp3.RealCall.execute(RealCall.java:77)
		at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:104)
		at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:54)
		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:157)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
		... 40 more
		
Notice the following. The exception is thrown from "currentUrlFor(driver)" inside ignoreUndefinedErrorsIfTheUrlIsCorrectFor().

    private void ignoreUndefinedErrorsIfTheUrlIsCorrectFor(WebDriver driver, String url) {
        try {
            driver.get(url);
        } catch (WebDriverException potentiallyIgnorableError) {
            if (!currentUrlFor(driver).equals(urlDeclaredIn(url))) {
                throw potentiallyIgnorableError;
            }
        }
    }

Standard out from Gradle Junit report (end of the output - a few tests is running fine and then Chrome headless crashes for an unknown reason):
	
	2018-02-15 13:24:34,712 [pool-4-thread-1] INFO  org.openqa.selenium.Capabilities - Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()` 
	2018-02-15 13:24:34,716 [pool-4-thread-1] DEBUG n.s.c.w.s.ChromeServicePool - Creating new driver instance with capabilities: Capabilities {browserName: chrome, chrome.switches: --headless, goog:chromeOptions: {args: [test-type, --headless, test-type], extensions: []}, platform: ANY, version: } 
	2018-02-15 13:24:36,038 [Forwarding newSession on session null to remote] INFO  o.o.s.remote.ProtocolHandshake - Detected dialect: OSS 
	Given a logged in normal user (...)
	2018-02-15 13:24:41,631 [pool-4-thread-1] DEBUG n.serenitybdd.core.pages.PageObject - Opening page at url http://localhost:9000/url/?param=123
	Then (...)
	When (...)
	(...)
	2018-02-15 13:24:50,678 [pool-4-thread-1] INFO  org.openqa.selenium.Capabilities - Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()` 
	2018-02-15 13:24:50,683 [pool-4-thread-1] DEBUG n.s.c.w.s.ChromeServicePool - Creating new driver instance with capabilities: Capabilities {browserName: chrome, chrome.switches: --headless, goog:chromeOptions: {args: [test-type, --headless, test-type], extensions: []}, platform: ANY, version: } 
	And (...)
	2018-02-15 13:24:57,140 [pool-4-thread-1] DEBUG n.serenitybdd.core.pages.PageObject - Opening page at url http://localhost:9000/url/#/hashvalue
	When (...)
	Then (...)
	(...)
	2018-02-15 13:30:01,674 [pool-4-thread-1] INFO  org.openqa.selenium.Capabilities - Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()` 
	2018-02-15 13:30:01,678 [pool-4-thread-1] DEBUG n.s.c.w.s.ChromeServicePool - Creating new driver instance with capabilities: Capabilities {browserName: chrome, chrome.switches: --headless, goog:chromeOptions: {args: [test-type, --headless, test-type], extensions: []}, platform: ANY, version: } 
	2018-02-15 13:30:03,015 [Forwarding newSession on session null to remote] INFO  o.o.s.remote.ProtocolHandshake - Detected dialect: OSS 
	Given a logged in normal user on desktop
	2018-02-15 13:30:08,110 [pool-4-thread-1] DEBUG n.serenitybdd.core.pages.PageObject - Opening page at url http://localhost:9000/url/#/hashvalue
	2018-02-15 13:30:34,575 [pool-34-thread-1] WARN  n.s.c.w.s.ChromeServicePool - Remote driver creation failed (unknown error: unable to discover open pages), falling back on default driver creation 
	2018-02-15 13:30:36,454 [Forwarding newSession on session null to remote] INFO  o.o.s.remote.ProtocolHandshake - Detected dialect: OSS 
	Given a logged in mobile user visiting

**Comment by wakaleo** [comment]
The best bet would be to refactor that code to cater for this type of error.

**Comment by HNygard** [comment]
@wakaleo : Could maybe have try-catch around currentUrlFor(). If it throws exception, catch it and throw the first one?

Something like this:

    private void ignoreUndefinedErrorsIfTheUrlIsCorrectFor(WebDriver driver, String url) {
        try {
            driver.get(url);
        } catch (WebDriverException potentiallyIgnorableError) {
            String currentUrl;
            try {
                currentUrl = currentUrlFor(driver);
            } catch (Throwable t) {
                LOGGER.warn("Got an exception while getting [" + url + "].", potentiallyIgnorableError);
                LOGGER.warn("Got an exception while trying to determine if we can ignore the original exception (last log message).", t);
                throw potentiallyIgnorableError;
            }
            if (!currentUrl.equals(urlDeclaredIn(url))) {
                throw potentiallyIgnorableError;
            }
        }
    }

I can submit a pull request for this if you like the solution.

**Comment by wakaleo** [comment]
That looks like an old hack for HTMLUnit idiosyncrasies - I'll see if I can remove it entirely.
