### ISSUE TITLE
Serenity Runner Fails With no informative message when a blank feature file is present

### ISSUE THREAD

**Issue by BlacktoBlue** [serenity-bdd/serenity-core#1158]
HI,

When you have a completely blank feature file the Serenity Runner fails with a null pointer exception. 

```java.lang.NullPointerException
	at cucumber.runtime.formatter.TestSourcesModel.parseGherkinSource(TestSourcesModel.java:161)
	at cucumber.runtime.formatter.TestSourcesModel.getFeature(TestSourcesModel.java:87)
	at cucumber.runtime.formatter.SerenityReporter.featureFrom(SerenityReporter.java:180)
	at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:150)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$0(SerenityReporter.java:111)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:132)
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:315)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:80)
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:38)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)```

Is there a way to handle this better and either ignore blank feature files or throw a more meaningful exception?

**Comment by wakaleo** [comment]
This is the Cucumber parser, not th Serenity code itself, so I would suggest raising an issue with the Cucumber-JVM folk.
