### ISSUE TITLE
com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#1161]
Steps:
1. Trying to run appium scripts on saucelabs
2. Script works properly on local setup
3. pom.xml

```
   <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.9.3</serenity.version>
        <serenity.cucumber.version>1.9.3</serenity.cucumber.version>
        <serenity.maven.version>1.9.3</serenity.maven.version>
    </properties>
```

Actual Result:
1.  [main] ERROR net.serenitybdd.core.Serenity - com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String

```
java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String

	at org.openqa.selenium.remote.RemoteWebElement.getTagName(RemoteWebElement.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.pagefactory.ElementInterceptor.getObject(ElementInterceptor.java:40)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:62)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c.getTagName(<generated>)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.getTagName(WebElementFacadeImpl.java:1113)
	at net.serenitybdd.core.pages.WebElementExpectations.isAFormElement(WebElementExpectations.java:162)
	at net.serenitybdd.core.pages.WebElementExpectations.isDisabledField(WebElementExpectations.java:158)
	at net.serenitybdd.core.pages.WebElementExpectations.access$000(WebElementExpectations.java:10)
	at net.serenitybdd.core.pages.WebElementExpectations$3.apply(WebElementExpectations.java:64)
	at net.serenitybdd.core.pages.WebElementExpectations$3.apply(WebElementExpectations.java:55)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.waitUntilEnabled(WebElementFacadeImpl.java:966)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.waitUntilElementAvailable(WebElementFacadeImpl.java:808)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.click(WebElementFacadeImpl.java:1045)
```

**Comment by wakaleo** [comment]
Looks like a conflict between Selenium (3.10.0 is used in the latest version of Serenity) and Appium.

**Comment by vikramvi** [comment]
Updated `appium java client` version to 
`appiumJavaClientVersion = 6.0.0-BETA4` under `gradle.properties` but still same issue.

Shall I report this issue under appium java client ?

**Comment by wakaleo** [comment]
I think so, it is in the Appium code base

**Comment by vikramvi** [comment]
I checked saucelabs appium server logs and found 
`2018-03-08 06:34:54:559 - [Appium] Welcome to Appium v1.6.4`

Let me find out why saucelabs using old version of appium server and is there any way to configure appium server version

**Comment by vikramvi** [comment]
Got it working with `appium.appiumVersion = 1.7.2` adding to `serenity.properties`.

Closing as issue is not related to serenity.
