### ISSUE TITLE
Custom driver failing

### ISSUE THREAD

**Issue by lnm2** [serenity-bdd/serenity-core#1181]
There is a problem instantiating the custom driver

Here is the output

[main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class net.thucydides.core.webdriver.ProvidedDriver: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (Could not instantiate the custom webdriver provider of type mydriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (Could not instantiate the custom webdriver provider of type mydriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:136)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:135)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:105)
	at net.thucydides.core.webdriver.WebDriverFacade.getDriverClass(WebDriverFacade.java:98)
	at net.thucydides.core.webdriver.WebDriverType.isMobile(WebDriverType.java:9)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:48)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:25)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:21)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:152)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:156)
	at net.serenitybdd.core.pages.PageObject.<init>(PageObject.java:141)
	at testing.pages.PageObjectEnhanced.<init>(PageObjectEnhanced.java:26)
	at testing.pages.AuthenticatePage.<init>(AuthenticatePage.java:11)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.thucydides.core.pages.Pages.createFromConstructorWithWebdriver(Pages.java:247)
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:205)
	at net.thucydides.core.pages.Pages.getPage(Pages.java:89)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:54)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:32)
	at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:141)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:131)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:117)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:82)
	at net.thucydides.core.steps.StepFactory.getStepLibraryFor(StepFactory.java:76)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:52)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:41)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:23)
	at net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:136)
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:102)
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:68)
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:51)
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:41)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.ExamplesRunner.run(ExamplesRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.ScenarioOutlineRunner.run(ScenarioOutlineRunner.java:53)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: java.lang.RuntimeException: Could not instantiate the custom webdriver provider of type mydriver
	at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:28)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:126)
	... 86 more
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:469)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:109)
	at org.openqa.selenium.ie.InternetExplorerDriverService.access$000(InternetExplorerDriverService.java:32)
	at org.openqa.selenium.ie.InternetExplorerDriverService$Builder.findDefaultExecutable(InternetExplorerDriverService.java:167)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
	at org.openqa.selenium.ie.InternetExplorerDriver.setupService(InternetExplorerDriver.java:251)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:172)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:150)
	at com.acme.MyIEDriver.newDriver(MyIEDriver.java:15)
	at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:26)
	... 87 more
[main] WARN net.thucydides.core.pages.Pages - Failed to instantiate page of type class testing.pages.AuthenticatePage (net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class net.thucydides.core.webdriver.ProvidedDriver)

Here is the custom class: 

`package com.acme;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

import net.thucydides.core.webdriver.DriverSource;

public class MyIEDriver implements DriverSource {

    @Override
    public WebDriver newDriver() {
        DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
		// Add
		return new InternetExplorerDriver(capabilities);
    }

        @Override
    public boolean takesScreenshots() {
        return true;
    }
}`

Versions:
Serenity 1.4.0 
Cucumber 1.1.30

**Comment by ricardorlg** [comment]
As the error says, `Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.ie.driver system property;` you have to set the path, also upgrade the serenity version you are using, 1.4.0 is really old.

**Comment by lnm2** [comment]
Also happening on serenity 1.8.1

This is in the serenity properties file:

webdriver.driver=provided
webdriver.provided.type=mydriver
webdriver.provided.mydriver=com.acme.MyIEDriver
thucydides.driver.capabilities=mydriver
webdriver.ie.driver=src/test/resources/grid/IEDriverServer.exe

**Comment by wakaleo** [comment]
Setting the webdriver.ie.driver property should work just fine - why are you using a custom driver?

**Comment by lnm2** [comment]
I would like to set desired capabilities

**Comment by lnm2** [comment]
InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING, true
InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, true
InternetExplorerDriver.UNEXPECTED_ALERT_BEHAVIOR, true
CapabilityType.ACCEPT_SSL_CERTS, true
CapabilityType.PAGE_LOAD_STRATEGY, "eager"
"ignoreZoomSetting", true
setJavascriptEnabled(true)

**Comment by wakaleo** [comment]
I think this sounds like a usage question (better for https://serenity-bdd.rocket.chat) more than an actual defect. If you use a CustomDriver then the code you use to create a new driver is independent of Serenity - you need to code everything yourself, including any processing of the webdriver.ie.driver property. For example, from memory, I don't recall if it needs to be a relative or absolute path.

**Comment by lnm2** [comment]
This is copied from your documentation: http://thucydides.info/docs/serenity-staging/#_custom_webdriver_implementations

**Comment by wakaleo** [comment]
Yes, that is how you write a custom driver. You are responsible for creating a new instance of the driver and ensuring that it can be found.

**Comment by lnm2** [comment]
Specifying the "webdriver.ie.driver" inside the CustomDriver class works, thank you. Would it be possible to add this to the documentation?

**Comment by wakaleo** [comment]
Sure; we are updating the docs on a new platform at the moment, so we will take that point into account.

**Comment by sebasthianc1** [comment]
What is the solution to this problem? Could you share the solution?
