### ISSUE TITLE
Getting exception "element not visible"

### ISSUE THREAD

**Issue by MonaAgrawal** [serenity-bdd/serenity-core#1189]
Hi,
I am getting below exception. Can someone help me to resolve the issue.

net.serenitybdd.core.exceptions.SerenityManagedException: element not visible
(Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 26 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'IT-MLT-10993.local', ip: 'fe80:0:0:0:10:ed5b:760b:499b%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8), userDataDir=/var/folders/6j/bjjyrccn1hnf1dzl_38tfxrwt5f67v/T/.org.chromium.Chromium.NqJYGA}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=65.0.3325.181, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 1db044df9d8433de1e8033c923134faf
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
  at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
  at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
  at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:82)
  at com.serenity.web.matches.desktop.pages.checkout.p2.shipping.ShippingFormPage.selectEmailable(ShippingFormPage.java:122)
  at com.serenity.web.matches.desktop.steps.checkout.ShippingFormSteps.selectEmailable(ShippingFormSteps.java:76)
  at com.serenity.web.matches.desktop.steps.checkout.ShippingFormSteps$$EnhancerByCGLIB$$8e111e61.CGLIB$selectEmailable$21(<generated>)
  at com.serenity.web.matches.desktop.steps.checkout.ShippingFormSteps$$EnhancerByCGLIB$$8e111e61$$FastClassByCGLIB$$bb3f4b0b.invoke(<generated>)
  at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
  at net.thucydides.core.steps.BaseMethodRunner.invokeMethod(BaseMethodRunner.java:10)
  at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:20)
  at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:307)
  at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:125)
  at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
  at com.serenity.web.matches.desktop.steps.checkout.ShippingFormSteps$$EnhancerByCGLIB$$8e111e61.selectEmailable(<generated>)
  at com.cucumber.definitions.checkout.ShippingDefs.iSelectThePromotionalEmailCheckbox(ShippingDefs.java:510)
  at ✽.And I select the promotional email checkbox(/Users/monaa/test-automation/src/test/resources/features/account/ManagePreferences.feature:36)

**Comment by wakaleo** [comment]
This is not a Serenity defect, it is just Selenium telling you that the element you are trying to click on is not visible.

**Comment by MonaAgrawal** [comment]
Thank you for confirmation.
