### ISSUE TITLE
Possible wrong datetime format in JUnitXMLConverter

### ISSUE THREAD

**Issue by daczczcz1** [serenity-bdd/serenity-core#1197]
After test scenario execution an exception is raised:

> java.time.DateTimeException: Field DayOfYear cannot be printed as the value 100 exceeds the maximum print width of 2 	at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2548)	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)	at net.thucydides.core.reports.junit.JUnitXMLConverter.lambda$buildTestSuiteElement$0(JUnitXMLConverter.java:197)	at java.util.Optional.ifPresent(Optional.java:159)	at net.thucydides.core.reports.junit.JUnitXMLConverter.buildTestSuiteElement(JUnitXMLConverter.java:196)	at net.thucydides.core.reports.junit.JUnitXMLConverter.write(JUnitXMLConverter.java:36)	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.lambda$generateReportsFor$0(JUnitXMLOutcomeReporter.java:49)

In file: 

> net.thucydides.core.reports.junit.JUnitXMLConverter:34

the DateTimeFormat is specified as "YYYY-MM-DD hh:mm:ss".

"DD" should be switched to "dd" as this is the correct formatting of day of month. This issue is likely to make report generation fail every time (until the end of the year).

**Comment by daczczcz1** [comment]
This seems to be fixed in 1.9.6.
