### ISSUE TITLE
BUILD FAILURE due to java.time.DateTimeException

### ISSUE THREAD

**Issue by sirgen** [serenity-bdd/serenity-core#1198]
**Env:**
macOS High Sierra 10.13.1
java version "1.8.0_161"
Apache Maven 3.5.2
serenity-core 1.9.4
serenity-cucumber 1.9.4

**Steps to reproduce**
1) git clone https://github.com/sirgen/rp-serenity-bdd.git
2) mvn clean verify

**Actual result:**
BUILD FAILURE
java.time.DateTimeException: Field DayOfYear cannot be printed as the value 100 exceeds the maximum print width of 2
	at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2548)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at net.thucydides.core.reports.junit.JUnitXMLConverter.lambda$buildTestSuiteElement$0(JUnitXMLConverter.java:197)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.thucydides.core.reports.junit.JUnitXMLConverter.buildTestSuiteElement(JUnitXMLConverter.java:196)
	at net.thucydides.core.reports.junit.JUnitXMLConverter.write(JUnitXMLConverter.java:36)
	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.lambda$generateReportsFor$0(JUnitXMLOutcomeReporter.java:49)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:41)
	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:202)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:187)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:135)
	at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:857)
	at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:298)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:117)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Expected result:**
BUILD SUCCESS

**Comment by aysimpson** [comment]
Just seen this ourselves.  It seems to be because today is day 100 and this is a bug with a recent version of Serenity (we are running a branch on an older version which is not failing - 1.8.3)

**Comment by kutzi** [comment]
Already reported as https://github.com/serenity-bdd/serenity-core/issues/1195
and fixed in 1.9.6

**Comment by aysimpson** [comment]
Thanks - I just commented as we saw the post as we were investigating ourselves :)

**Comment by wakaleo** [comment]
Closing as duplicate
