### ISSUE TITLE
Freemarker template error

### ISSUE THREAD

**Issue by kutzi** [serenity-bdd/serenity-core#1199]
After upgrading to serenity-core 1.9.6 serenity-cucumber 1.9.4 (previously: 1.9.1/1.9.3) I get the following errors:

> FreeMarker template error:
> Java method "net.thucydides.core.reports.html.Formatter.renderDescription(String)" threw an exception when invoked on net.thucydides.core.reports.html.Formatter object "net.thucydides.core.reports.html.Formatter@6ffae4ed"; see cause exception in the Java stack trace.
> 
> ----
> FTL stack trace ("~" means nesting-related):
> 	- Failed at: ${formatter.renderDescription(parentR...  [in template "freemarker/screenshots.ftl" at line 122, column 33]
> ----
> 
> Java stack trace (for programmers):
> ----
> freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
> 	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:311)
> 	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:275)
> 	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:80)
> 	at freemarker.core.MethodCall._eval(MethodCall.java:62)
> 	at freemarker.core.Expression.eval(Expression.java:78)
> 	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
> 	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
> 	at freemarker.core.Environment.visit(Environment.java:324)
> 	at freemarker.core.MixedContent.accept(MixedContent.java:54)
> 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
> 	at freemarker.core.IfBlock.accept(IfBlock.java:48)
> 	at freemarker.core.Environment.visit(Environment.java:324)
> 	at freemarker.core.MixedContent.accept(MixedContent.java:54)
> 	at freemarker.core.Environment.visit(Environment.java:324)
> 	at freemarker.core.Environment.process(Environment.java:302)
> 	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
> 	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
> 	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:137)
> 	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:227)
> 	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:108)
> 	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:247)
> 	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:183)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException
> 	at net.thucydides.core.reports.html.Formatter.stripNewLines(Formatter.java:146)
> 	at net.thucydides.core.reports.html.Formatter.renderAsciidoc(Formatter.java:117)
> 	at net.thucydides.core.reports.html.Formatter.renderDescription(Formatter.java:245)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
> 	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:71)
> 	... 24 more
>  [pool-2-thread-4] WARN FreemarkerReportTemplate - Report generation failed

**Comment by kutzi** [comment]
Thanks for the quick fix!
When can I expect a new version with the fix?
