### ISSUE TITLE
1.9.x Returns java.time.DateTimeException: Field DayOfYear cannot be printed as the value 101 exceeds the maximum print width of 2

### ISSUE THREAD

**Issue by tatkom** [serenity-bdd/serenity-core#1204]
Starting from April 10th 2018(100th day of a year) we're getting following error on Serenity report generation step:

> java.time.DateTimeException: Field DayOfYear cannot be printed as the value 100 exceeds the maximum print width of 2

Initial version we used:

```
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>1.9.3</version>
		</dependency>
```
This is also reproducible on 1.9.1
And not reproducible on 1.8.21

Stacktrace:

>  	at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2548)
> 	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
> 	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
> 	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
> 	at net.thucydides.core.reports.junit.JUnitXMLConverter.lambda$buildTestSuiteElement$0(JUnitXMLConverter.java:197)
> 	at java.util.Optional.ifPresent(Optional.java:159)
> 	at net.thucydides.core.reports.junit.JUnitXMLConverter.buildTestSuiteElement(JUnitXMLConverter.java:196)
> 	at net.thucydides.core.reports.junit.JUnitXMLConverter.write(JUnitXMLConverter.java:36)
> 	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.lambda$generateReportsFor$0(JUnitXMLOutcomeReporter.java:49)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
> 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
> 	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
> 	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:41)
> 	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:202)
> 	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:187)
> 	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:135)
> 	at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:822)
> 	at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:316)
> 	at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:148)
> 	at cucumber.runner.EventBus.send(EventBus.java:28)
> 	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
>

**Comment by Hendrione** [comment]
update to 1.9.6

Pada tanggal Rab, 11 Apr 2018 20:00, tatkom <notifications@github.com>
menulis:
