### ISSUE TITLE
FreemarkerReportTemplate - Syntax error in report template

### ISSUE THREAD

**Issue by sergeyfilin** [serenity-bdd/serenity-core#1207]
serenity-core:1.9.6
gradle-4.0-all.zip
`
WARN  n.t.c.r.t.FreemarkerReportTemplate - Report generation failed
    freemarker.core._TemplateModelException: Java method "net.thucydides.core.reports.html.Formatter.renderDescription(String)" threw an exception when invoked on net.thucydides.core.reports.html.Formatter object "net.thucydides.core.reports.html.Formatter@697cf64b"; see cause exception in the Java stack trace.

    ----
    FTL stack trace ("~" means nesting-related):
        - Failed at: ${formatter.renderDescription(feature...  [in template "freemarker/default.ftl" at line 98, column 33]
    ----
        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:311) ~[freemarker-2.3.23.jar:2.3.23]
        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:275) ~[freemarker-2.3.23.jar:2.3.23]
        at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:80) ~[freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.MethodCall._eval(MethodCall.java:62) ~[freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.Expression.eval(Expression.java:78) ~[freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82) ~[freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.DollarVariable.accept(DollarVariable.java:41) ~[freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.Environment.visit(Environment.java:324) [freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.MixedContent.accept(MixedContent.java:54) [freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345) [freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.IfBlock.accept(IfBlock.java:48) [freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.Environment.visit(Environment.java:324) [freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.MixedContent.accept(MixedContent.java:54) [freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.Environment.visit(Environment.java:324) [freemarker-2.3.23.jar:2.3.23]
        at freemarker.core.Environment.process(Environment.java:302) [freemarker-2.3.23.jar:2.3.23]
        at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42) [serenity-core-1.9.6.jar:1.9.6]
        at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37) [serenity-core-1.9.6.jar:1.9.6]
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:137) [serenity-core-1.9.6.jar:1.9.6]
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:123) [serenity-core-1.9.6.jar:1.9.6]
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:247) [serenity-core-1.9.6.jar:1.9.6]
        at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:183) [serenity-core-1.9.6.jar:1.9.6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
    Caused by: java.lang.NullPointerException: null
        at net.thucydides.core.reports.html.Formatter.stripNewLines(Formatter.java:146) ~[serenity-core-1.9.6.jar:1.9.6]
        at net.thucydides.core.reports.html.Formatter.renderAsciidoc(Formatter.java:117) ~[serenity-core-1.9.6.jar:1.9.6]
        at net.thucydides.core.reports.html.Formatter.renderDescription(Formatter.java:245) ~[serenity-core-1.9.6.jar:1.9.6]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458) ~[freemarker-2.3.23.jar:2.3.23]
        at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:71) ~[freemarker-2.3.23.jar:2.3.23]
        ... 23 common frames omitted
    10:26:13.284 [pool-106-thread-1] ERROR n.t.c.r.t.FreemarkerReportTemplate - Syntax error in report template: Java method "net.thucydides.core.reports.html.Formatter.renderDescription(String)" threw an exception when invoked on net.thucydides.core.reports.html.Formatter object "net.thucydides.core.reports.html.Formatter@697cf64b"; see cause exception in the Java stack trace.

    ----
    FTL stack trace ("~" means nesting-related):
        - Failed at: ${formatter.renderDescription(feature...  [in template "freemarker/default.ftl" at line 98, column 33]
    ----
        - Failed at: ${formatter.renderDescription(feature...  [in template "freemarker/default.ftl" at line 98, column 33]

...... > executionError FAILED
    net.thucydides.core.reports.ReportGenerationFailedError
        Caused by: java.util.concurrent.ExecutionException
            Caused by: net.thucydides.core.reports.ReportGenerationFailedError
                Caused by: java.lang.RuntimeException
                    Caused by: net.thucydides.core.reports.templates.TemplateMergeException
                        Caused by: freemarker.core._TemplateModelException
                            Caused by: java.lang.NullPointerException
`

**Comment by wakaleo** [comment]
Fixed in 1.9.7
