### ISSUE TITLE
Epics and Stories not displayed when Jira login and password are passed as system properties

### ISSUE THREAD

**Issue by devtrove** [serenity-bdd/serenity-core#1215]
**Case 1**:  
- Set user credentials in serenity.properties.
- Run `gradle clean test aggregate -Ptags="wip"` for single test
- Open Serenity report. 
**Result:** (works as expected) 
- I see tabs "Overall test results", "Requirements", "Epics", "Stories"
- I see epics and stories from Jira in tabs

**Case 2:**
- Set user credentials as system properties in build.gradle file (currently using plain text values, we'll need to get them from remote service for real project, as plain text passwords are not allowed)
- Run `gradle clean test aggregate -Ptags="wip"` for single test
- Open Serenity report. 
**Result:**  
- I see tabs "Overall test results", "Requirements"
**Problem:**
- I do not see tabs "Epics", "Stories"

**Found via debug:**
When I set logging level to debug and inspect logs, I see:
- System properties are set correctly and passed to test task
- Epics and stories are retrieved from Jira

Start of test task looks like this:
> Starting process 'Gradle Test Executor 1'. Working directory: C:\devel\serenity-template Command: C:\Program Files\Java\jdk1.8\bin\java.exe -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Djira.password=myPassword -Djira.project=XXX -Djira.url=https://mysite.atlassian.net -Djira.username=myUsername -Dorg.gradle.native=false -Dtags=wip -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp C:\Users\myUser\.gradle\caches\4.6\workerMain\gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'

Content of **test** task is identical in both cases.

The differences in log appear for **aggregate** task.

*Aggregate task log output for Case 1 (where serenity.properties are used and epics / stories are displayed):*

> :aggregate (Thread[Task worker for ':' Thread 3,5,main]) started.
Task :aggregate 
Task ':aggregate' is not up-to-date because:
  Task has not declared any outputs.
Generating Serenity Reports for serenity-template to directory C:\devel\serenity-template\target\site\serenity
Generating test results for 1 tests
Running in a non-OSGi environment
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
Task :aggregate 
38 requirements loaded after 8788 ms
38 related requirements found after 8794 ms
Generating test outcome reports: false
Starting generating reports: 8922 ms
Configured report threads: 20
Test results for 1 tests generated in 11788 ms
:aggregate (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 12.092 secs.

*Aggregate task log output for Case 2 (where system properties are used and epics / stories are not displayed):*

> :aggregate (Thread[main,5,main]) started.
 Task :aggregate 
Task ':aggregate' is not up-to-date because:
  Task has not declared any outputs.
Generating Serenity Reports for serenity-template to directory C:\devel\serenity-template\target\site\serenity
Generating test results for 1 tests
Running in a non-OSGi environment
0 requirements loaded after 352 ms
0 related requirements found after 352 ms
Generating test outcome reports: false
Starting generating reports: 430 ms
Configured report threads: 20
Test results for 1 tests generated in 2907 ms
:aggregate (Thread[main,5,main]) completed. Took 3.287 secs.

Using: 
- serenity-core 1.9.8
- serenity-junit 1.9.8
- serenity-jira-requirements-provider 1.9.0
- serenity-jira-plugin 1.9.0
- gradle 4.6
- java 1.8.0_161
- JUnit style tests only

**Comment by wakaleo** [comment]
Could be the gradle build config or the aggregate task. Try digging into the easel plugin to see why the properties are not getting passed through.

**Comment by devtrove** [comment]
Hi again,

Tried researching this with no success. Could you help me identify what I'm missing? To narrow this down I took sample project from serenity-demos/junit-tests-linked-to-issues

**serenity.properties**
```
serenity.use.requirements.directories=false
```

**build.gradle**
```
repositories {
    mavenLocal()
    jcenter()
}

ext{
    serenity_version = "1.9.8"
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.9.8")
        classpath("net.serenity-bdd:serenity-jira-requirements-provider:1.9.0")
    }
}

apply plugin: "java"
apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "net.serenity-bdd.aggregator"

dependencies {
    compile "net.serenity-bdd:serenity-core:$serenity_version"
    compile "net.serenity-bdd:serenity-junit:$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-jira-requirements-provider', version: "1.9.0"

    compile 'org.slf4j:slf4j-simple:1.7.12'
    compile 'junit:junit:4.12'
    compile 'org.assertj:assertj-core:3.1.0'
}

System.setProperty("jira.username", 'myUsername')
System.setProperty("jira.password", 'myPassword')
System.setProperty("jira.project", 'projectCode')
System.setProperty("jira.url", 'https://someCompany.atlassian.net')

test {
    testLogging {
        showStandardStreams = true
    }

    systemProperties System.getProperties()

    println systemProperties
}

gradle.startParameter.continueOnFailure = true

```

If I move Jira credentials to serenity.properties file, epics and stories are displayed in report.

Tried using serenity-gradle-plugin from project buildSrc and printing out some debugging info. Noticed:

**SerentyPlugin->updateProperties**, inspecting `config.getEnvironmentVariables().properties`:
- prints out Jira credentials when they are in serenity.properties file
- contains no Jira credentials when they are passed as system property (using any method I could think of)

**Comment by devtrove** [comment]
More debug. If I understand correctly what I see, JIRARequirementsProvider in aggregate task is reading properties from serenity.properties file only. Is it something I can fix by calling aggregate task in some different way, or should this be fixed in code? 

```
22:25:45.107 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':aggregate'.
22:25:45.107 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Execute doLast {} action for :aggregate' started
22:25:45.108 [LIFECYCLE] [org.gradle.api.Task] Generating Serenity Reports for junit-tests-linked-to-issues to directory C:\devel\serenity-demos\junit-tests-linked-to-issues\target\site\serenity
22:25:45.170 [DEBUG] [net.thucydides.core.util.PropertiesFileLocalPreferences] LOADING LOCAL PROPERTIES FROM C:\devel\serenity-demos\junit-tests-linked-to-issues\serenity.properties 
22:25:45.170 [DEBUG] [net.thucydides.core.util.PropertiesFileLocalPreferences] LOADING LOCAL PROPERTIES FROM C:\devel\serenity-demos\junit-tests-linked-to-issues\serenity.properties 
22:25:45.171 [DEBUG] [net.thucydides.core.util.PropertiesFileLocalPreferences] LOADING LOCAL PROPERTIES FROM C:\devel\serenity-demos\junit-tests-linked-to-issues\serenity.properties 
22:25:45.172 [DEBUG] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider] JIRA URL: null
22:25:45.172 [DEBUG] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider] JIRA project: null
22:25:45.172 [DEBUG] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider] JIRA user: null
22:25:45.222 [DEBUG] [net.thucydides.core.reports.html.HtmlAggregateStoryReporter] Copied screenshots after 1 ms
22:25:45.290 [DEBUG] [net.thucydides.core.reports.html.HtmlAggregateStoryReporter] Loaded test outcomes after 69 ms
22:25:45.290 [INFO] [net.thucydides.core.reports.html.HtmlAggregateStoryReporter] Generating test results for 4 tests
22:25:45.314 [DEBUG] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider] Loading root requirements: issuetype = epic and project=null
22:25:45.346 [INFO] [org.glassfish.jersey.internal.ServiceFinder] Running in a non-OSGi environment
22:25:45.371 [DEBUG] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider] No root requirements found (JQL = issuetype = epic and project=null
net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException: URI template of the newly created target must not be null.
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByJQL(JerseyJiraClient.java:141)
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getRequirements(JIRARequirementsProvider.java:114)
	at net.thucydides.core.requirements.RequirementsProvided.by(RequirementsProvided.java:15)
	at net.thucydides.core.requirements.reports.MultipleSourceRequirmentsOutcomeFactory.buildRequirementsOutcomesFrom(MultipleSourceRequirmentsOutcomeFactory.java:53)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:152)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
	at net.thucydides.core.reports.UserStoryTestReporter$generateReportsForTestResultsFrom.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at net.serenitybdd.plugins.gradle.SerenityPlugin$_apply_closure1$_closure8.doCall(SerenityPlugin.groovy:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:718)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:691)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: URI template of the newly created target must not be null.
	at jersey.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:289)
	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:76)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.buildWebTargetFor(JerseyJiraClient.java:204)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.countByJQL(JerseyJiraClient.java:466)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByJQLBatches(JerseyJiraClient.java:157)
	at net.serenitybdd.plugins.jira.client.FindByJQLLoaderUsingBatches.load(FindByJQLLoaderUsingBatches.java:17)
	at net.serenitybdd.plugins.jira.client.FindByJQLLoaderUsingBatches.load(FindByJQLLoaderUsingBatches.java:8)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3523)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2249)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2132)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4951)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByJQL(JerseyJiraClient.java:137)
	... 61 more
22:25:45.372 [DEBUG] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider] Loading root requirements done: 0
22:25:45.375 [DEBUG] [net.serenitybdd.plugins.jira.requirements.ConcurrentRequirementsLoader] Loading 0 requirements
22:25:45.376 [DEBUG] [net.thucydides.core.requirements.reports.MultipleSourceRequirmentsOutcomeFactory] Merged requirements set:
NO REQUIREMENTS FOUND
22:25:45.380 [INFO] [net.thucydides.core.reports.html.HtmlAggregateStoryReporter] 0 requirements loaded after 90 ms
22:25:45.380 [INFO] [net.thucydides.core.reports.html.HtmlAggregateStoryReporter] 0 related requirements found after 90 ms
22:25:45.380 [INFO] [net.thucydides.core.reports.html.HtmlAggregateStoryReporter] Generating test outcome reports: false
22:25:45.404 [INFO] [net.thucydides.core.reports.html.HtmlAggregateStoryReporter] Starting generating reports: 114 ms
22:25:45.405 [INFO] [net.thucydides.core.reports.NumberOfThreads] Configured report threads: 40
22:25:45.408 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] GENERATE TAG REPORTS FOR TestTag{name='Issues/Sample test', type='story'}
22:25:45.410 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] GENERATE TAG REPORTS FOR TestTag{name='Issues/Sample test', type='story'}
22:25:45.459 [DEBUG] [net.thucydides.core.requirements.RequirementsTagProvider] Requirements found:[]
22:25:45.459 [DEBUG] [net.thucydides.core.requirements.RequirementsTagProvider] Requirements found:[]
22:25:45.459 [DEBUG] [net.thucydides.core.requirements.RequirementsTagProvider] Requirements found:[]
22:25:45.459 [DEBUG] [net.thucydides.core.requirements.RequirementsTagProvider] Requirements found:[]
22:25:45.459 [DEBUG] [net.thucydides.core.requirements.RequirementsTagProvider] Requirements found:[]
22:25:45.459 [DEBUG] [net.thucydides.core.requirements.RequirementsTagProvider] Requirements found:[]
22:25:45.459 [DEBUG] [net.thucydides.core.requirements.RequirementsTagProvider] Requirements found:[]
22:25:45.459 [DEBUG] [net.thucydides.core.requirements.RequirementsTagProvider] Requirements found:[]
22:25:45.516 [DEBUG] [net.thucydides.core.requirements.RequirementsTagProvider] Requirements found:[]
22:25:45.517 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] Generating report in 01f5288b80adbd3af52a8ed68a4a616d3164f750229f80da1ef344382d948835.html
22:25:45.517 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] Generating report in index.html
22:25:45.517 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] Generating report in summary.txt
22:25:45.517 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] Generating report in 3d2871ef9911e9892794a9042e262e6b82ae98dff337dd2d2e4d80be2072e38e.html
22:25:45.517 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] Generating report in 89e5d8ba0ac2da18f0c86d8db78e5a6fe1475023c2967cb64a51dd0811be37ef.html
22:25:45.518 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] Generating report in 7d53ffdc098ba57e5c14dbf49b06f6534b1ff31e9f0ab5f59ef6caf79c3aabd4.html
22:25:45.518 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] Generating report in bd39c26d0977b318da3d10cf730221ddfb1e4418f3e0f13f765c680d3d7a2f7a.html
22:25:45.522 [DEBUG] [net.thucydides.core.reports.html.ReportingTask] Generating report in capabilities.html
```

**Comment by devtrove** [comment]
Have a "quick and dirty" fix. I feel I won't be able to finish it to be nice and create pull request. But in case someone needs a quick fix right now, this is what worked for me:

1. Checkout serenity-core using tag of the version you are using in your tests (in my case - v1.9.8)
2. Update serenity-gradle-plugin:

**SerenityPluginExtension.groovy**
- make `configuration` public
- add `jiraUsername` and `jiraPassword`

Modified version looks like this:
```
class SerenityPluginExtension {
    final def configuration = Injectors.getInjector().getProvider(Configuration.class).get()
    String outputDirectory = configuration.getOutputDirectory()
    String historyDirectory = configuration.getHistoryDirectory()
    String projectKey
    String issueTrackerUrl
    String jiraUrl
    String jiraProject
    String jiraUsername
    String jiraPassword
    String sourceDirectory = outputDirectory
}
```

**SerenityPlugin.groovy**
At the beginning of `aggregate.doLast` add updating environments variables in aggregate task scope:

```
        project.task('aggregate') {
            group = 'Serenity BDD'
            description = 'Generates aggregated Serenity reports'
            doLast {
                def vars = project.serenity.configuration.getEnvironmentVariables()
                if (project.serenity.jiraUsername) {
                    vars.setProperty("jira.username", project.serenity.jiraUsername)
                }
                if (project.serenity.jiraPassword) {
                    vars.setProperty("jira.password", project.serenity.jiraPassword)
                }
                if (project.serenity.jiraProject) {
                    vars.setProperty("jira.project", project.serenity.jiraProject)
                }
                if (project.serenity.jiraUrl) {
                    vars.setProperty("jira.url", project.serenity.jiraUrl)
                }

                updateProperties(project)

[---- everything else unchanged ----]
```

3. Build serenity-gradle-plugin locally (in my case file `serenity-gradle-plugin-1.9.9-SNAPSHOT.jar` was built). 
4. Copy jar to your project and update project config to use it. I used location `src/test/resources/lib`
5. Configure Jira credentials in **two** places in your `build.gradle` -- for test task (can be set globally or for test task only) and for serenity gradle plugin

**build.gradle**

```
repositories {
    mavenLocal()
    jcenter()
    flatDir { dirs "src/test/resources/lib" }
}

ext{
    serenity_version = "1.9.8"
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
        flatDir { dirs "src/test/resources/lib" }

    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.9.9-SNAPSHOT")
        classpath("net.serenity-bdd:serenity-jira-requirements-provider:1.9.0")
    }
}

apply plugin: "java"
apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "net.serenity-bdd.aggregator"

dependencies {
    compile "net.serenity-bdd:serenity-core:$serenity_version"
    compile "net.serenity-bdd:serenity-junit:$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-jira-requirements-provider', version: "1.9.0"

    compile 'org.slf4j:slf4j-simple:1.7.12'
    compile 'junit:junit:4.12'
    compile 'org.assertj:assertj-core:3.1.0'
}

// for test task, can be set using systemProperty("jira.password", "myPassword") as test task configuration
System.setProperty("jira.username", 'myUsername')
System.setProperty("jira.password", 'myPassword')
System.setProperty("jira.project", 'projectCode')
System.setProperty("jira.url", 'https://someCompany.atlassian.net')

// for Serenity aggregate task
serenity {
    jiraUsername = 'myUsername'
    jiraPassword = 'myPassword'
    jiraProject = 'projectCode'
    jiraUrl = 'https://someCompany.atlassian.net'
}

test {
    testLogging {
        showStandardStreams = true
    }

    systemProperties System.getProperties()
}

gradle.startParameter.continueOnFailure = true

``` 

That's all for static config. Create and use additional methods to get Jira credentials from remote credentials storage according to your project needs.
