### ISSUE TITLE
1.9.13 : java.lang.NoSuchMethodError: net.thucydides.core.webdriver.Configuration.getDriverType()Lnet/thucydides/core/webdriver/SupportedWebDriver;

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#1234]
Hello @wakaleo, 

I just updated my serenity deps : 
- core from 1.8.0 to 1.9.13
- gradle plugin to 1.8.0 to 1.9.13
- jbehave to 1.34 to 1.39

Every scenarios are failing with this kind of error message : 
```
15:54:17.574 [pool-4-thread-1] DEBUG n.s.j.e.m.CompositeEmbedderMonitor - runningStory stories/predefinedrole/custom_role_admin.story
Running story stories/predefinedrole/custom_role_admin.story
15:54:17.574 [pool-4-thread-1] INFO  n.s.j.e.m.ReportingEmbedderMonitor - 1019533898story running with path stories/predefinedrole/custom_role_admin.story
15:54:17.574 [pool-4-thread-1] ERROR n.s.j.e.m.ReportingEmbedderMonitor - can not find any story by path stories/predefinedrole/custom_role_admin.story
15:54:17.602 [pool-4-thread-1] DEBUG n.s.j.SerenityReporter - before story custom_role_admin.story
15:54:17.602 [pool-4-thread-1] DEBUG n.s.j.e.m.CompositeEmbedderMonitor - storyFailed stories/predefinedrole/custom_role_admin.story
Failed to run story stories/predefinedrole/custom_role_admin.story
java.lang.NoSuchMethodError: net.thucydides.core.webdriver.Configuration.getDriverType()Lnet/thucydides/core/webdriver/SupportedWebDriver;
	at net.serenitybdd.jbehave.SerenityReporter.getRequestedDriver(SerenityReporter.java:316)
	at net.serenitybdd.jbehave.SerenityReporter.configureDriver(SerenityReporter.java:275)
	at net.serenitybdd.jbehave.SerenityReporter.beforeStory(SerenityReporter.java:129)
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStory(DelegatingStoryReporter.java:78)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStory(ConcurrentStoryReporter.java:123)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:837)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:427)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:398)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Is there any major change about stories or driver declaration / config ? 
I tried to use *drivers.windows.webdriver.firefox.driver*, but with no result :(

Thanks

**Comment by cliviu** [comment]
hi @mmanach , for the moment please use core 1.9.7

**Comment by etsybaev** [comment]
i se the issue for in gradle multimodules project. Last tried with 1.9.19. With version 1.9.7 it works fine. Thanks for suggestion!

**Comment by wakaleo** [comment]
Closed (presumed fixed).
