### ISSUE TITLE
Driver Initialisation error is shown when trying to run serenity tests on Docker

### ISSUE THREAD

**Issue by arunaousula9421** [serenity-bdd/serenity-core#1241]
At the moment, I am trying to setup CI job on Docker and trying to run the Serenity tests. But when trying to run them Jenkins it shows up following error.

```
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
/var/jenkins_home/workspace/Build Automation Pipeline/src/main/resources/drivers/chromedriver: 1: /var/jenkins_home/workspace/Build Automation Pipeline/src/main/resources/drivers/chromedriver: Syntax error: "(" unexpected
May 09, 2018 12:59:28 PM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
[main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.chrome.ChromeDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Timed out waiting for driver server to start.
Build info: version: '3.10.0', revision: '176b4a9', time: '2018-03-02T19:03:16.397Z'
System info: host: '8cc0d80de2bd', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.87-linuxkit-aufs', java.version: '1.8.0_162'
Driver info: driver.version: unknown
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Timed out waiting for driver server to start.
Build info: version: '3.10.0', revision: '176b4a9', time: '2018-03-02T19:03:16.397Z'
System info: host: '8cc0d80de2bd', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.87-linuxkit-aufs', java.version: '1.8.0_162'
Driver info: driver.version: unknown
```

Did anyone had same issue while setting up things on Docker??

**Comment by wakaleo** [comment]
Sound's like a problem with your Docker setup.

**Comment by arunaousula9421** [comment]
Hi @wakaleo, Is there anyway I can resolve this issue??

**Comment by wakaleo** [comment]
The error is simple Selenium reporting that it can't start the chromedriver server. Is the chromedriver binary on the system path in Docker? Is it the correct version? etc.

```
/var/jenkins_home/workspace/Build Automation Pipeline/src/main/resources/drivers/chromedriver: 1: /var/jenkins_home/workspace/Build Automation Pipeline/src/main/resources/drivers/chromedriver: Syntax error: "(" unexpected
```
This looks like an error in the chromedriver binary you appear to be providing in this directory. Is it a linux binary?

**Comment by arunaousula9421** [comment]
@wakaleo It is  MacOSX binary

**Comment by wakaleo** [comment]
The MacOS binary will not run under Linux. You need to ensure that the Linux chromedriver binary is correctly configured (eg by setting it in an OS-related maven profile) or on the path, rather than hard-coding it in your system.properties file.

**Comment by arunaousula9421** [comment]
@wakaleo Can you please provide an example to setup the above??

**Comment by arunaousula9421** [comment]
@wakaleo I have tried the changes as you specified but still getting the same issue.

Project:
https://github.com/arunaousula9421/Automation-BuildPipeline

Here's the logs

```
[0m
09:33:18.901 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
09:33:19.630 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver is 2.38
09:33:19.663 [main] INFO io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
09:33:19.665 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /var/jenkins_home/.m2/repository/webdriver/chromedriver/linux64/2.38/chromedriver
Starting ChromeDriver 2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb) on port 25623
Only local connections are allowed.
09:33:20.391 [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class net.thucydides.core.webdriver.ProvidedDriver: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (Could not instantiate the custom webdriver provider of type mydriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (Could not instantiate the custom webdriver provider of type mydriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:136)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:153)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:114)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:185)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:842)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:743)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:731)
	at pages.HomePage.<init>(HomePage.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.thucydides.core.pages.Pages.createFromConstructorWithWebdriver(Pages.java:266)
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:206)
	at net.thucydides.core.pages.Pages.getPage(Pages.java:90)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:173)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:163)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:146)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:93)
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:75)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:59)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:41)
	at net.serenitybdd.junit.runners.SerenityRunner.injectScenarioStepsInto(SerenityRunner.java:606)
	at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:570)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:473)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:448)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
Caused by: java.lang.RuntimeException: Could not instantiate the custom webdriver provider of type mydriver
	at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:25)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:126)
	... 47 common frames omitted
Caused by: org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.9.87-linuxkit-aufs x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 138 milliseconds
Build info: version: '3.10.0', revision: '176b4a9', time: '2018-03-02T19:03:16.397Z'
System info: host: 'd75831c7e9d1', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.87-linuxkit-aufs', java.version: '1.8.0_162'
Driver info: driver.version: CustomChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at customdrivers.CustomChromeDriver.newDriver(CustomChromeDriver.java:25)
	at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:23)
	... 48 common frames omitted
09:33:20.392 [main] WARN net.thucydides.core.pages.Pages - Failed to instantiate page of type class pages.HomePage ({})
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class net.thucydides.core.webdriver.ProvidedDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:157)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:114)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:185)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:842)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:743)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:731)
	at pages.HomePage.<init>(HomePage.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.thucydides.core.pages.Pages.createFromConstructorWithWebdriver(Pages.java:266)
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:206)
	at net.thucydides.core.pages.Pages.getPage(Pages.java:90)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:173)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:163)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:146)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:93)
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:75)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:59)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:41)
	at net.serenitybdd.junit.runners.SerenityRunner.injectScenarioStepsInto(SerenityRunner.java:606)
	at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:570)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:473)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:448)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
Caused by: net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (Could not instantiate the custom webdriver provider of type mydriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:136)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:153)
	... 46 common frames omitted
Caused by: java.lang.RuntimeException: Could not instantiate the custom webdriver provider of type mydriver
	at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:25)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:126)
	... 47 common frames omitted
Caused by: org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.9.87-linuxkit-aufs x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 138 milliseconds
Build info: version: '3.10.0', revision: '176b4a9', time: '2018-03-02T19:03:16.397Z'
System info: host: 'd75831c7e9d1', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.87-linuxkit-aufs', java.version: '1.8.0_162'
Driver info: driver.version: CustomChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at customdrivers.CustomChromeDriver.newDriver(CustomChromeDriver.java:25)
	at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:23)
	... 48 common frames omitted
09:33:20.396 [main] DEBUG net.thucydides.core.steps.StepEventBus - Test suite started for class ui.SalesSearchUITest
09:33:20.416 [main] INFO net.serenitybdd.core.Serenity - Test Suite Started: Sales search UI test
09:33:20.472 [main] INFO net.serenitybdd.core.Serenity - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: Initialisation
-------------------------------------------------------------------
09:33:20.473 [main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
09:33:20.693 [main] DEBUG net.thucydides.core.reports.ReportService - Reporting formats: [JSON, HTML]
09:33:20.703 [main] DEBUG net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.xml.XMLTestOutcomeReporter@205b132e(format = Optional[XML])
09:33:20.704 [main] DEBUG net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@73044cdf(format = Optional[JSON])
09:33:20.704 [main] DEBUG net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.json.JSONTestOutcomeReporter@73044cdf
09:33:20.796 [main] DEBUG net.thucydides.core.reports.ReportService - Found reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@3bead518(format = Optional[HTML])
09:33:20.797 [main] DEBUG net.thucydides.core.reports.ReportService - Registering reporter: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@3bead518
09:33:20.798 [main] DEBUG net.thucydides.core.reports.ReportService - Reporting formats: [JSON, HTML]
09:33:20.818 [main] DEBUG net.thucydides.core.reports.ReportService - Generating reports for 1 test outcomes using: net.thucydides.core.reports.json.JSONTestOutcomeReporter@73044cdf
09:33:20.820 [main] DEBUG net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
09:33:20.821 [pool-1-thread-1] DEBUG net.thucydides.core.reports.ReportService - Processing test outcome Sales search UI test:Initialisation
09:33:20.822 [pool-1-thread-1] DEBUG net.thucydides.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@73044cdf: Generating report for test outcome: Sales search UI test:Initialisation
09:33:20.854 [pool-1-thread-1] DEBUG net.thucydides.core.reports.json.JSONTestOutcomeReporter - Generating JSON report for Initialisation to file /var/jenkins_home/workspace/Build Automation Pipeline/target/site/serenity/fe1f174e4cd6ce90666183158abe52d0a99984487a360d0d6954a27ee1935846.json (using temp file /var/jenkins_home/workspace/Build Automation Pipeline/target/site/serenity/fe1f174e4cd6ce90666183158abe52d0a99984487a360d0d6954a27ee1935846.json4126bb44-f377-417a-88e7-81d11c68783c)
09:33:21.005 [pool-1-thread-1] DEBUG net.thucydides.core.reports.ReportService - Processing test outcome Sales search UI test:Initialisation done
09:33:21.038 [main] DEBUG net.thucydides.core.reports.ReportService - Shutting down executor service
09:33:21.039 [main] DEBUG net.thucydides.core.reports.ReportService - Reports generated in: 221 ms
09:33:21.040 [main] DEBUG net.thucydides.core.reports.ReportService - Generating reports for 1 test outcomes using: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@3bead518
09:33:21.040 [main] DEBUG net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORTS
09:33:21.041 [pool-2-thread-1] DEBUG net.thucydides.core.reports.ReportService - Processing test outcome Sales search UI test:Initialisation
09:33:21.041 [pool-2-thread-1] DEBUG net.thucydides.core.reports.ReportService - net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@3bead518: Generating report for test outcome: Sales search UI test:Initialisation
09:33:21.042 [pool-2-thread-1] DEBUG net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - GENERATE TEST OUTCOME REPORT FOR Initialisation in fe1f174e4cd6ce90666183158abe52d0a99984487a360d0d6954a27ee1935846
09:33:21.053 [pool-2-thread-1] DEBUG net.thucydides.core.requirements.RequirementsTagProvider - Requirements found:[]
09:33:21.156 [pool-2-thread-1] DEBUG net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - GENERATING HTML REPORT FOR Sales search UI test:Initialisation in fe1f174e4cd6ce90666183158abe52d0a99984487a360d0d6954a27ee1935846.html in directory target/site/serenity  
09:33:21.160 [pool-2-thread-1] DEBUG net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - Generating report in fe1f174e4cd6ce90666183158abe52d0a99984487a360d0d6954a27ee1935846.html
09:33:21.664 [pool-2-thread-1] DEBUG net.thucydides.core.requirements.RequirementsTagProvider - Requirements found:[]
09:33:21.701 [pool-2-thread-1] DEBUG net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - Generated report fe1f174e4cd6ce90666183158abe52d0a99984487a360d0d6954a27ee1935846.html in 541 ms
09:33:21.702 [pool-2-thread-1] DEBUG net.thucydides.core.reports.ReportService - Processing test outcome Sales search UI test:Initialisation done
09:33:21.702 [main] DEBUG net.thucydides.core.reports.ReportService - Shutting down executor service
09:33:21.702 [main] DEBUG net.thucydides.core.reports.ReportService - Reports generated in: 662 ms
09:33:21.719 [main] DEBUG net.thucydides.core.reports.ReportService - Generating report for configuration
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.738 s <<< FAILURE! - in ui.SalesSearchUITest
[ERROR] ui.SalesSearchUITest  Time elapsed: 3.414 s  <<< FAILURE!
net.thucydides.core.pages.WrongPageError: 
The page object class pages.HomePage looks dodgy:
Failed to instantiate page (net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class net.thucydides.core.webdriver.ProvidedDriver)
```

**Comment by wakaleo** [comment]
Looks like you are using a Custom driver which is failing to start under Docker. This is a project configuration issue, not a Serenity defect; could you post the question in https://serenity-bdd.rocket.chat which would be a more appropriate forum. Alternatively, to investigate further, have you considered our support packages?

**Comment by arunaousula9421** [comment]
@wakaleo Do we have any support packages. Where can I view them??

**Comment by wakaleo** [comment]
The Serenity support packages can be found here: https://johnfergusonsmart.com/serenity-bdd-mentoring
