### ISSUE TITLE
Error executing FreeMarker template

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-core#1243]
Hello,

I'm trying to update serenity to the latest sources, but aggregate task throws an error:
`Error executing FreeMarker template
Report generation failed
freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "cardNumberWithLinks"; see cause exception! The type of the containing value was: extended_hash+string (net.thucydides.core.requirements.reports.RequirementOutcome
wrapped into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${requirementOutcome.cardNumberWithLi...  [in template "freemarker/components/requirements-list.ftl" in macro "requirements_results" at line 67, column 63]
        - Reached through: @requirements_results requirements=re...  [in template "freemarker/requirements.ftl" at line 325, column 33]
----
        at freemarker.ext.beans.BeanModel.get(BeanModel.java:199)
        at freemarker.core.Dot._eval(Dot.java:40)
        at freemarker.core.Expression.eval(Expression.java:78)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Macro$Context.runMacro(Macro.java:184)
        at freemarker.core.Environment.invoke(Environment.java:701)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.process(Environment.java:302)
        at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
        at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
        at net.thucydides.core.reports.html.BaseReportingTask.generateReportPage(BaseReportingTask.java:46)
        at net.thucydides.core.reports.html.RequirementsOverviewReportingTask.generateReports(RequirementsOverviewReportingTask.java:92)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:32)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:11)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
        at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:255)
        at freemarker.ext.beans.BeanModel.get(BeanModel.java:159)
        ... 41 more
Caused by: java.lang.NullPointerException
        at net.thucydides.core.requirements.reports.RequirementOutcome.getCardNumberWithLinks(RequirementOutcome.java:222)
        ... 48 more
Syntax error in report template: An error has occurred when reading existing sub-variable "cardNumberWithLinks"; see cause exception! The type of the containing value was: extended_hash+string (net.thucydides.core.requirements.reports.RequirementOutcome wrapped
into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${requirementOutcome.cardNumberWithLi...  [in template "freemarker/components/requirements-list.ftl" in macro "requirements_results" at line 67, column 63]
        - Reached through: @requirements_results requirements=re...  [in template "freemarker/requirements.ftl" at line 325, column 33]
----
        - Failed at: ${requirementOutcome.cardNumberWithLi...  [in template "freemarker/components/requirements-list.ftl" in macro "requirements_results" at line 67, column 63]
        - Reached through: @requirements_results requirements=re...  [in template "freemarker/requirements.ftl" at line 325, column 33]

Error executing FreeMarker template
Report generation failed
freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "cardNumberWithLinks"; see cause exception! The type of the containing value was: extended_hash+string (net.thucydides.core.requirements.reports.RequirementOutcome
wrapped into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${requirementOutcome.cardNumberWithLi...  [in template "freemarker/components/requirements-list.ftl" in macro "requirements_results" at line 67, column 63]
        - Reached through: @requirements_results requirements=re...  [in template "freemarker/requirement-type.ftl" at line 118, column 17]
----
        at freemarker.ext.beans.BeanModel.get(BeanModel.java:199)
        at freemarker.core.Dot._eval(Dot.java:40)
        at freemarker.core.Expression.eval(Expression.java:78)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Macro$Context.runMacro(Macro.java:184)
        at freemarker.core.Environment.invoke(Environment.java:701)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.process(Environment.java:302)
        at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
        at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
        at net.thucydides.core.reports.html.BaseReportingTask.generateReportPage(BaseReportingTask.java:46)
        at net.thucydides.core.reports.html.RequirementsTypeReportingTask.generateReports(RequirementsTypeReportingTask.java:61)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:32)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:11)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
        at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:255)
        at freemarker.ext.beans.BeanModel.get(BeanModel.java:159)
        ... 41 more
Caused by: java.lang.NullPointerException
        at net.thucydides.core.requirements.reports.RequirementOutcome.getCardNumberWithLinks(RequirementOutcome.java:222)
        ... 48 more
Syntax error in report template: An error has occurred when reading existing sub-variable "cardNumberWithLinks"; see cause exception! The type of the containing value was: extended_hash+string (net.thucydides.core.requirements.reports.RequirementOutcome wrapped
into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${requirementOutcome.cardNumberWithLi...  [in template "freemarker/components/requirements-list.ftl" in macro "requirements_results" at line 67, column 63]
        - Reached through: @requirements_results requirements=re...  [in template "freemarker/requirement-type.ftl" at line 118, column 17]
----
        - Failed at: ${requirementOutcome.cardNumberWithLi...  [in template "freemarker/components/requirements-list.ftl" in macro "requirements_results" at line 67, column 63]
        - Reached through: @requirements_results requirements=re...  [in template "freemarker/requirement-type.ftl" at line 118, column 17]
`
Here is some details from my build.gradle:
serenity-core:1.9.16
gradle-4.7-all.zip

**Comment by ilzul** [comment]
@cliviu, thanks a lot for this fix.
Seems like the issue comes from stories with `@issue` tags (at least, I have no errors if I remove those metatags)

@cliviu, How can I get the serenity-core with your corrections ?

**Comment by cliviu** [comment]
@ilzul, I'm not sure when the next release comes but usually it should not take more than a few weeks

**Comment by ilzul** [comment]
Thanks a lot for information. Looking forward for a new package with this fix.

**Comment by wakaleo** [comment]
Should be available in 1.9.17

**Comment by ilzul** [comment]
works like a charm :)
Thanks a lot for your support !
