### ISSUE TITLE
Getting  http.conn.HttpHostConnectException error when i use headless browser.

### ISSUE THREAD

**Issue by muli09** [serenity-bdd/serenity-core#1262]
Getting the below while using headless browser as htmlunit driver and in our application we are using mapquest apis.
org.apache.http.conn.HttpHostConnectException: Connect to api.tiles.mapbox.com:443 [api.tiles.mapbox.com/52.84.88.135] failed: Operation timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:194)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1372)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1291)
	at com.gargoylesoftware.htmlunit.html.HtmlLink.getWebResponse(HtmlLink.java:188)
	at com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet.loadStylesheet(CSSStyleSheet.java:336)
	at com.gargoylesoftware.htmlunit.javascript.host.html.HTMLLinkElement.getSheet(HTMLLinkElement.java:145)
	at com.gargoylesoftware.htmlunit.javascript.host.css.StyleSheetList.item(StyleSheetList.java:182)
	at com.gargoylesoftware.htmlunit.javascript.host.Window.getComputedStyle(Window.java:1611)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by wakaleo** [comment]
This looks like a driver or server issue, rather than a Serenity issue. Is there something that makes you think this might be related to Serenity?
