### ISSUE TITLE
Failed to generate HTML report - Template not found for name freemarker/default.ftl

### ISSUE THREAD

**Issue by jai4july** [serenity-bdd/serenity-core#1275]
Hi ,
       I am facing an issue with generating HTML reports through serenity. Error message I get is "Template not found for name "freemarker/default.ftl". Please find the actual error message below. Can someone please help me on this? Much appreciated . Thanks Jay

**Actual Error message:**
net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
       at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
       at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
       at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
       at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)

Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@ca93621

       at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
       at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
       at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
       at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)

Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@ca93621
Caused by: java.lang.RuntimeException:
Failed to merge template: Template not found for name "freemarker/default.ftl".
The name was interpreted by this TemplateLoader: ClassTemplateLoader(resourceLoaderClass=net.thucydides.core.reports.templates.FreeMarkerTemplateManager, basePackagePath="/").
Caused by: freemarker.template.TemplateNotFoundException:
Template not found for name "freemarker/default.ftl".
The name was interpreted by this TemplateLoader: ClassTemplateLoader(resourceLoaderClass=net.thucydides.core.reports.templates.FreeMarkerTemplateManager, basePackagePath="/").

**Comment by jai4july** [comment]
Additional Notes: The version of serenity core and serenity maven plugin is 1.5.8.   Not sure if the error message is related to this.  The same version works well on my personal laptop. I am facing the issue on my work laptop

**Comment by wakaleo** [comment]
Looks like some sort of maven repository issue. Note that the latest version is 1.9.23, so we can't do much troubleshooting with older versions.

**Comment by wakaleo** [comment]
Closed for lack of activity (presume resolved).
