### ISSUE TITLE
Phantomjs screen shot failure at method call isCurrentlyEnabled( ) 

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#129]
Phantomjs always fails with below error

[main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: WL_LoginStoryTest.VerifySuccessfulLoginToWL - verifyWLisLoadedFully
phantomjs(85353,0x119f11000) malloc: *** error for object 0x10390ac00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: '6wbuildbot.local', ip: '10.40.6.215', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_05'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:784)
	at net.thucydides.core.webdriver.WebDriverFactory.setTimeouts(WebDriverFactory.java:753)
	at net.thucydides.core.webdriver.WebDriverFacade.setImplicitTimeout(WebDriverFacade.java:254)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.findElementImmediately(SmartAjaxElementLocator.java:109)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.findElement(SmartAjaxElementLocator.java:91)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy16.isEnabled(Unknown Source)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.isCurrentlyEnabled(WebElementFacadeImpl.java:337)
	at com.wunderlist.pages.WL_ListFeature.forceWaitPostLogin(WL_ListFeature.java:762)
	at com.wunderlist.steps.WL_ListFeature_EndUserSteps.verifyWLisLoadedFully(WL_ListFeature_EndUserSteps.java:351)

**Comment by cliviu** [comment]
Hi, I've seen a lot of such reports on OS X but no clear solutions. 
Please try first the latest java 7 version if is possible for you.
Which phantomjs version are you using ?

**Comment by vikramvi** [comment]
Hi Cliviu,

I am using latest version of Phantomjs and latest java version as well.

Thanks,
Vikram

**Comment by YamStranger** [comment]
Will close this ticket: 
it is not Serenity BDD issue
