### ISSUE TITLE
ReportGenerationFailedError: java.lang.NullPointerException at net.thucydides.core.tags.BreadcrumbTagFilter.getRequirementBreadcrumbsFrom(BreadcrumbTagFilter.java:50)

### ISSUE THREAD

**Issue by kutzi** [serenity-bdd/serenity-core#1303]
Have seen this once until now:

 [main] ERROR SerenityMain - Exception in Cucumber runtime
net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:203)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:180)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
	at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:855)
	at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:298)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:116)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.runtime.Runtime.run(Runtime.java:107)
	at cucumber.runtime.Runtime$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at SerenityMain.run(SerenityMain.groovy:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at SerenityMain.main(SerenityMain.groovy:26)
Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@632cf7d3
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:200)
	... 23 more
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@632cf7d3
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:241)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at net.thucydides.core.tags.BreadcrumbTagFilter.getRequirementBreadcrumbsFrom(BreadcrumbTagFilter.java:50)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:198)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:186)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:162)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:106)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	... 6 more

**Comment by wakaleo** [comment]
What version are you using?

**Comment by kutzi** [comment]
1.9.17

**Comment by wakaleo** [comment]
Do you get the error with the latest version?

**Comment by kutzi** [comment]
Not yet, but will try.
But since this seems to be some rare concurrency issue, seeing the issue not for some while wouldn't prove that it's fixed ;)

**Comment by wakaleo** [comment]
The actual error is a null pointer exception in the BreadcrumbTagFilter class; the concurrency error is just showing as the reports are generated in parallel.
