### ISSUE TITLE
java.lang.RuntimeException: Unexpected result for screenshot command: null

### ISSUE THREAD

**Issue by kutzi** [serenity-bdd/serenity-core#1333]
Got this once. Non reproducable so far - i.e. usually it works without error

```
 [main] ERROR SerenityMain - Exception in Cucumber runtime
java.lang.RuntimeException: Unexpected result for screenshot command: null
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:303)
	at net.serenitybdd.core.photography.PhotoSession.takeScreenshot(PhotoSession.java:40)
	at net.serenitybdd.core.photography.PhotoSessionBooking.andSaveToDirectory(PhotoSessionBooking.java:37)
	at net.thucydides.core.steps.BaseStepListener.grabScreenshot(BaseStepListener.java:863)
	at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:768)
	at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:762)
	at net.thucydides.core.steps.BaseStepListener.takeInitialScreenshot(BaseStepListener.java:850)
	at net.thucydides.core.steps.BaseStepListener.stepStarted(BaseStepListener.java:520)
	at net.thucydides.core.steps.StepEventBus.stepStarted(StepEventBus.java:354)
	at net.thucydides.core.steps.StepEventBus.stepStarted(StepEventBus.java:343)
	at cucumber.runtime.formatter.SerenityReporter.handleTestStepStarted(SerenityReporter.java:303)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$3(SerenityReporter.java:117)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.api.TestStep.run(TestStep.java:79)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.Runtime.runFeature(Runtime.java:119)
	at cucumber.runtime.Runtime.run(Runtime.java:104)
	at cucumber.runtime.Runtime$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at SerenityMain.run(SerenityMain.groovy:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at SerenityMain.main(SerenityMain.groovy:26)
```

**Comment by kutzi** [comment]
See here: https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/serenitybdd/core/photography/PhotoSession.java#L41

I didn't expect RemoteWebDriver to throw any other exception than WebDriverException, but apparently RuntimeExceptions are also thrown sometimes.

**Comment by wakaleo** [comment]
Looks like the driver failed to take a screenshot for some reason. Did it break the test?

**Comment by kutzi** [comment]
Yes, the test failed because of that and no test result was recorded

**Comment by wakaleo** [comment]
Maybe a PR to get the catch clause to catch RuntimeExceptions as well? (These wouldn't normally be expected I guess).

**Comment by kutzi** [comment]
See https://github.com/serenity-bdd/serenity-core/pull/1334
