### ISSUE TITLE
webdriver.driver property is ignored

### ISSUE THREAD

**Issue by c-mu** [serenity-bdd/serenity-core#136]
I'm running serenity with the gradle plugin (V1.1.13) and serenity cucumber (V1.1.1). No matter how I try to configure which webdriver to use, serenity always uses Firefox. I tried setting it via command line (-Dwebdriver.driver=..., resp. Ddriver=...) as well as in the serenity.properties. I also already tried all supported settings for the driver (chrome, firefox, iexplorer and phantomjs), but the setting is ignored. Am I missing something?

**Comment by cliviu** [comment]
Hi @c-mu ! Please search in your project for the "firefox" text. It may be possible that you have something like this
```java
    @Managed(driver="firefox")                             
    WebDriver driver;
```

**Comment by c-mu** [comment]
Hi @cliviu, I have searched as you advised, but for my source files only got the commented out setting from my serenity.properties in the search results. Anything else I can check/should configure?

**Comment by cliviu** [comment]
try to set the webdriver in the build.gradle :
```java
tasks.withType(Test) {
    systemProperty 'webdriver.driver', System.getProperty('webdriver.driver', 'phantomjs')
}
```

**Comment by c-mu** [comment]
I added that line to the task I have defined to run my tests. Surprisingly I get an _UnsupportedDriverException_ for all drivers (iexplorer, chrome, phantomjs) except firefox. However, I do have all the browsers installed: Edge, IExplorer 11, Chrome 45, Phantomjs 2.0.0, Firefox 41)

**Comment by cliviu** [comment]
can you please post the UnsupportedDriverException stack trace and eventually the error log messages  ? 

can it be that you do not have the dependency to phantomjs? 

'com.github.detro.ghostdriver:phantomjsdriver:1.1.0'

**Comment by c-mu** [comment]
Seems I was missing a lot of configuration settings to make the different drivers work. I'll have a closer look tomorrow and come back in case something is still not working, resp. close the issue.

I assume that this will then also be working when stating the driver in the serenity.properties file along with the driver specific settings?

**Comment by cliviu** [comment]
you can set the driver also in serenity.properties :" webdriver.driver phantomjs" .
The setting in build.gradle overwrites the one in serenity.properties.

**Comment by c-mu** [comment]
ok, still no luck with phantomjs. I have set the PHANTOMJS_BINARY_PATH environment variable, tried adding the binary path via serenity.driver.capabilities, but no success. When I add the webdriver.driver setting in the build.gradle file I get the UnsupportedDriverException, when using the serenity.properties it is ignored (i.e. firefox is used).

Here's the Log output:
```
myPackage.features.theRunner > Scenario: Go home.When I navigate to the home page FAILED
    net.thucydides.core.webdriver.UnsupportedDriverException
        Caused by: net.thucydides.core.webdriver.UnsupportedDriverException
            Caused by: java.lang.IllegalStateException
```
and the stacktrace:
```
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.phantomjs.PhantomJSDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:128)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:100)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:173)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:168)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:836)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:746)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:734)
	at com.intel.i2SubSt.pdmt.features.glue.steps.CommonStepDefinitions.navigate_to_home(CommonStepDefinitions.java:15)
	at ✽.When I navigate to the home page(Theme/Epic/Story.feature:5)
Caused by: net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.phantomjs.PhantomJSDriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:202)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:137)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:128)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:100)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:173)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:168)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:836)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:746)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:734)
	at com.intel.i2SubSt.pdmt.features.glue.steps.CommonStepDefinitions.navigate_to_home(CommonStepDefinitions.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:299)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: The driver executable is a directory: C:\Chocolatey\lib\PhantomJS.2.0.0\tools\phantomjs-2.0.0-windows\bin
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:123)
	at org.openqa.selenium.phantomjs.PhantomJSDriverService.findPhantomJS(PhantomJSDriverService.java:246)
	at org.openqa.selenium.phantomjs.PhantomJSDriverService.createDefaultService(PhantomJSDriverService.java:182)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:99)
	at net.thucydides.core.webdriver.WebdriverInstanceFactory.newPhantomDriver(WebdriverInstanceFactory.java:103)
	at net.thucydides.core.webdriver.WebDriverFactory.phantomJSDriver(WebDriverFactory.java:486)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:182)
	... 67 more
```

**Comment by cliviu** [comment]
please add the executable file name to your setting (phantomjs.exe ) . see java.lang.IllegalStateException: The driver executable is a directory: C:\Chocolatey\lib\PhantomJS.2.0.0\tools\phantomjs-2.0.0-windows\bin

**Comment by Invictum** [comment]
First of all try to check your PhantomJS executable.
Run in cmd
```
phantomjs -v
```
phantomjs version should be returned.

**Comment by cliviu** [comment]
in serenity.properties, set 
phantomjs.binary.path=C:\Chocolatey\lib\PhantomJS.2.0.0\tools\phantomjs-2.0.0-windows\bin\phantomjs.exe

**Comment by c-mu** [comment]
Ha! One down and here's the next:
```
myPackage.features.theRunner > Scenario: Go home.classMethod FAILED
    java.lang.NoClassDefFoundError
        Caused by: java.lang.ClassNotFoundException
```
This is gonna be interesting because: http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/remote/HttpVerb.html

By the way, this only "works" when I add the settings to the build.gradle. When I put the in my serenity.properties, serenity happily ignores them and uses firefox instead. :(

Anyway, here's the stack trace:
```
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/HttpVerb
	at org.openqa.selenium.phantomjs.PhantomJSDriver.getCustomCommands(PhantomJSDriver.java:166)
	at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.<init>(PhantomJSCommandExecutor.java:62)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:110)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:99)
	at net.thucydides.core.webdriver.WebdriverInstanceFactory.newPhantomDriver(WebdriverInstanceFactory.java:103)
	at net.thucydides.core.webdriver.WebDriverFactory.phantomJSDriver(WebDriverFactory.java:486)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:182)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:137)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:128)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:100)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:173)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:168)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:836)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:746)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:734)
	at myPackage.features.glue.steps.CommonStepDefinitions.navigate_to_home(CommonStepDefinitions.java:15)
	at ✽.When I navigate to the home page(Theme/Epic/Story.feature:5)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.HttpVerb
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.getCustomCommands(PhantomJSDriver.java:166)
	at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.<init>(PhantomJSCommandExecutor.java:62)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:110)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:99)
	at net.thucydides.core.webdriver.WebdriverInstanceFactory.newPhantomDriver(WebdriverInstanceFactory.java:103)
	at net.thucydides.core.webdriver.WebDriverFactory.phantomJSDriver(WebDriverFactory.java:486)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:182)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:137)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:128)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:100)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:173)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:168)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:836)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:746)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:734)
	at myPackage.features.glue.steps.CommonStepDefinitions.navigate_to_home(CommonStepDefinitions.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:299)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cliviu** [comment]
Hi, please post you dependencies from your gradle build file

**Comment by c-mu** [comment]
ok, so these are the dependencies I added for serenity:
```
  // Tests (BDD)
  serenityCompile "net.serenity-bdd:serenity-core:1.1.13"
  serenityCompile "net.serenity-bdd:serenity-junit:1.1.13"
  serenityCompile "net.serenity-bdd:serenity-cucumber:1.1.1"
  serenityCompile "org.assertj:assertj-core:1.7.0"
  serenityRuntime "com.github.detro.ghostdriver:phantomjsdriver:1.1.0"
  serenityRuntime "net.serenity-bdd:serenity-jira-plugin:1.0.1"
  serenityRuntime "net.serenity-bdd:serenity-jira-requirements-provider:1.0.1"
 ```
I've had ghostdriver added to serenityCompile as well already, but got the same results.

**Comment by cliviu** [comment]
ok, if you look at the http://mvnrepository.com/artifact/net.serenity-bdd/serenity-jira-plugin/1.0.1
you will see that serenity-jira-plugin uses 'net.serenity-bdd:core:1.0.30'

**Comment by c-mu** [comment]
I know, but JIRA integration works fine and so does cucumber. When I do a gradle dependecyInsight –dependency org.seleniumhq.selenium:selenium-server –configuration serenityRuntime I get

org.seleniumhq.selenium:selenium-server:2.47.1 (conflict resolution)
\--- net.serenity-bdd:serenity-core:1.1.13
     +--- serenityRuntime
     +--- net.serenity-bdd:serenity-junit:1.1.13
     |    +--- serenityRuntime
     |    \--- net.serenity-bdd:serenity-spring:1.1.13
     |         \--- serenityRuntime
     +--- net.serenity-bdd:serenity-spring:1.1.13 (*)
     \--- net.serenity-bdd:serenity-cucumber:1.1.1
          \--- serenityRuntime

org.seleniumhq.selenium:selenium-server:2.44.0 -> 2.47.1
\--- net.serenity-bdd:core:1.0.30
     +--- net.serenity-bdd:serenity-jira-plugin:1.0.1
     |    +--- serenityRuntime
     |    \--- net.serenity-bdd:serenity-jira-requirements-provider:1.0.1
     |         \--- serenityRuntime
     \--- net.serenity-bdd:serenity-jira-requirements-provider:1.0.1 (*)

So thanks to gradle’s  version conflict resolution, both serenity-core versions are using selenium 2.47.1
Or are you suspecting that because of the JIRA integration gradle is somehow using core 1.0.30 and that doesn’t support phantomjs configuration in serenity.properties, resp. at all? :s

**Comment by cliviu** [comment]
I think that the problem comes from mixing "net.serenity-bdd:serenity-core:1.1.13" with "net.serenity-bdd:core:1.0.30". You should stick to the 1.0.30 which is used by the jira plugins but this will not fit with the newer libraries used by the cucumber plugin. I think we need new jira artifacts :-)

**Comment by verhagen** [comment]
@c-mu What is the status of this ?

**Comment by c-mu** [comment]
Unchanged, I guess, unless @cliviu has acted on it. I haven't found the time to look into it, and most likely will not in the near future. (I'm no Java dev, and thus working on Java code takes an excessive amount for time for me).

**Comment by cliviu** [comment]
not fixed yet

**Comment by cliviu** [comment]
serenity-jira-plugin:1.1.1-rc.2 is available at bintray

**Comment by c-mu** [comment]
After updating I'm having problems. I've created [serenity-jira #8](https://github.com/serenity-bdd/serenity-jira/issues/8) to track the issues. Will continue here once they are resolved.

**Comment by c-mu** [comment]
I have successfully included rc.3 of the updated jira plugin, but the behavior is exactly the same as with the old ones (1.0.1):
* When I set the webdriver.driver and phantomjs.binary.path properties in my serenity.properties file to use phantomjs, Serenity happily ignores my setting and uses it's default - firefox
* When applying the same settings in my gradle script as suggested above, phantomjs fails calling the HttpVerb

**Comment by cliviu** [comment]
hi @c-mu. I'm really not sure what happens. Can you please post again you gradle.build file so that I can try to reproduce the problem ?

**Comment by cliviu** [comment]
hi @c-mu , I was able to reproduce your problem, just remove the entry
```xml
 serenityRuntime "com.github.detro.ghostdriver:phantomjsdriver:1.1.0"
```

and you should be fine. Let me know if it works

**Comment by c-mu** [comment]
hi, I just retested. Serentiy uses PhantomJs after removing the reference to the phantomjsdriver dependency. 
Unfortunately it does so only if I set the webdriver.driver and phantomjs.binary.path properties in my gradle script. When passing them via the serentiy.properties, Serenity still falls back to Firefox. :(

**Comment by cliviu** [comment]
ok, thanks for the feedback, I will analyse the problem with the setting also

**Comment by c-mu** [comment]
Hi @cliviu, @YamStranger gave me a tip in #130 regarding accepting systemProperties in a custom task. This fixed the issue of running tests with PhantomJs. Thanks for your help in getting this up and runnig for me.

**Comment by rakeshnambiar** [comment]
Hi .. Is there any way to set the serenity properties run time?

**Comment by wakaleo** [comment]
It depends what you are configuring.

**Comment by rakeshnambiar** [comment]
Hello John,

Thanks for your response. Let me eloborate.

I am using custom chrome browser as I need to set the download folder and it's working fine. But I have few Webservice Test cases which doesn't expect any browser at all and I am using @NoBrowser tag to clasify the tests. Is there any way to specify doesn't open any browser at all for the NoBrowser tag since I have mentioned the custom driver settings on the serenity.property file?

**Comment by rakeshnambiar** [comment]
If I can set the property on run time, probably I can mention not to use the custom driver.

**Comment by wakaleo** [comment]
You can declare a variable of type EnvironmentVariables in your test, e.g.

```
EnvironmentVariables environmentVariables;
```

Then set a property like this:

```
environmentVariables.setProperty("my.property","my value");
```
The problem is that the environment variables are really meant to be read-only, as you don't know at what point in the lifecycle they will be used, and they are shared between all of the tests.

**Comment by rakeshnambiar** [comment]
Thanks John for your quick reply. Let me try this and update you tomorrow.

**Comment by rakeshnambiar** [comment]
Hello John,

Thank you so much. 

It's worked for me. I managed to reset the driver settings same as property file end of the test using @After tag and checked both browsers based and non-browser based scenarios in the same test.

I have still one issue open. It will be great if you could help me on that.

When I click a particular link from the main browser, it opens the PDF content in the new browser. I have changed my browser settings and when I try manually, the auto-download is working. But auto-download not working through the script. So I used Robot key-event and downloaded the file. But the problem is, the new browser doesn't consider the custom download folder and it's downloading to the default user download folder.

**Comment by rakeshnambiar** [comment]
OR 

Could you pls advise how to declare the custom downloads folder in the Serenity.Property file?
I tried the below options and it doesn't work.
serenity.driver.capabilities=ACCEPT_SSL_CERTS:true,SUPPORTS_ALERTS=true,download.default_directory:C:/Downloads/
chrome.switches=--disable-extensions,--test-type,--start-maximized,download.default_directory:C:/Downloads/

**Comment by nobrowser** [comment]
@rakeshnambiar : that was a very poor choice of tag :-P

**Comment by rakeshnambiar** [comment]
@nobrowser ... May I know your 'BEST' solution? :)

**Comment by rakeshnambiar** [comment]
Hi @wakaleo ... Could you pls advise on the below mentioned strange behaviour?

I have created a custom chrome driver and configured the "download.default_directory" and it's working perfectly through my IDE. But not working through command line/Jenkins and chrome downloads the file to the user default download directory.

Am I missing something?
