### ISSUE TITLE
Serenity trying to instantiate wrong driver

### ISSUE THREAD

**Issue by tempuser14** [serenity-bdd/serenity-core#1381]
We run our tests either with Chrome or with Firefox which most of the times works OK. But today while running with Firefox it happened that Serenity tried to instantiate the Chrome driver, at least according to the exeption below.

Command: `mvn clean verify -Pstaging -Dcontext=firefox -Dinjected.tags="browser:firefox" -Dwebdriver.remote.driver=firefox -Dwebdriver.remote.url="http://zalenium.domain.com/wd/hub" -Dserenity.driver.capabilities="build:app.staging"`

Serenity version: 1.9.30

Exception
[pool-3-thread-1] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 11
[pool-3-thread-1] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.chrome.ChromeDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Socket timeout reading Marionette handshake data: Resource temporarily unavailable (os error 11)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: '36166230eafe', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-135-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 10.61 seconds
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Socket timeout reading Marionette handshake data: Resource temporarily unavailable (os error 11)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: '36166230eafe', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-135-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 10.61 seconds	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:137)	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:149)	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:140)	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:110)	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:181)	at pages.LoginPage.navigateToLoginPage(LoginPage.java:21)	at step.LoginSteps.navigateToLoginPage(LoginSteps.java:26)	at step.LoginSteps$$EnhancerByCGLIB$$6646dba4.CGLIB$navigateToLoginPage$1(<generated>)	at step.LoginSteps$$EnhancerByCGLIB$$6646dba4$$FastClassByCGLIB$$5b72f139.invoke(<generated>)	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:449)	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:434)	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:409)	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:150)	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:137)	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:68)	at step.LoginSteps$$EnhancerByCGLIB$$6646dba4.navigateToLoginPage(<generated>)	at step.LoginSteps.logsIn(LoginSteps.java:16)	at step.LoginSteps$$EnhancerByCGLIB$$6646dba4.CGLIB$logsIn$0(<generated>)	at step.LoginSteps$$EnhancerByCGLIB$$6646dba4$$FastClassByCGLIB$$5b72f139.invoke(<generated>)	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:449)	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:434)	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:409)	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:150)	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:137)	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:68)	at step.LoginSteps$$EnhancerByCGLIB$$6646dba4.logsIn(<generated>)	at test.ProductManagementTest.addsNewProductAndModifiesIt(ProductManagementTest.java:38)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)	at org.junit.rules.RunRules.evaluate(RunRules.java:20)	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:435)	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:42)	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:346)	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:239)	at org.junit.runners.Suite.runChild(Suite.java:128)	at org.junit.runners.Suite.runChild(Suite.java:27)	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)	at java.util.concurrent.FutureTask.run(FutureTask.java:266)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	at java.lang.Thread.run(Thread.java:748)Caused by: org.openqa.selenium.WebDriverException: Socket timeout reading Marionette handshake data: Resource temporarily unavailable (os error 11)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: '36166230eafe', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-135-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 10.61 seconds	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)	at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverBuilder.newRemoteDriver(RemoteDriverBuilder.java:55)	at net.serenitybdd.core.webdriver.driverproviders.DefaultRemoteDriver.buildWithOptions(DefaultRemoteDriver.java:24)	at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider.newInstance(RemoteDriverProvider.java:53)	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:127)	... 62 moreCaused by: org.openqa.selenium.WebDriverException: Socket timeout reading Marionette handshake data: Resource temporarily unavailable (os error 11)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: '36166230eafe', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-135-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
remote stacktrace: 
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 's00098.booklan.de', ip: '10.202.10.98', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.9.1.el7.x86_64', java.version: '1.8.0_171'
Driver info: driver.version: unknown	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)	at org.openqa.selenium.remote.server.RemoteSession$Factory.performHandshake(RemoteSession.java:145)	at org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:160)	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:177)	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)	at org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:180)	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:65)	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)	at java.util.Collections$2.tryAdvance(Collections.java:4717)	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:68)	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)	at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405)	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:71)	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$3(WebDriverServlet.java:250)	... 5 more[pool-3-thread-1] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.chrome.ChromeDriver: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (The appium.platformName needs to be specified (either IOS or ANDROID)
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (The appium.platformName needs to be specified (either IOS or ANDROID)	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:137)	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:149)	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:140)	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:110)	at test.core.ZaleniumTestWatcher.failed(ZaleniumTestWatcher.java:51)	at org.junit.rules.TestWatcher.failedQuietly(TestWatcher.java:84)	at org.junit.rules.TestWatcher.access$300(TestWatcher.java:46)	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:62)	at org.junit.rules.RunRules.evaluate(RunRules.java:20)	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:435)	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:42)	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:346)	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:239)	at org.junit.runners.Suite.runChild(Suite.java:128)	at org.junit.runners.Suite.runChild(Suite.java:27)	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)	at java.util.concurrent.FutureTask.run(FutureTask.java:266)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	at java.lang.Thread.run(Thread.java:748)Caused by: net.thucydides.core.webdriver.ThucydidesConfigurationException: The appium.platformName needs to be specified (either IOS or ANDROID)	at net.thucydides.core.webdriver.appium.AppiumConfiguration.lambda$getTargetPlatform$1(AppiumConfiguration.java:38)	at java.util.Optional.orElseThrow(Optional.java:290)	at net.thucydides.core.webdriver.appium.AppiumConfiguration.getTargetPlatform(AppiumConfiguration.java:38)	at net.serenitybdd.core.webdriver.driverproviders.RemoteWebdriverStub.from(RemoteWebdriverStub.java:13)	at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider.newInstance(RemoteDriverProvider.java:50)	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:127)	... 31 more[pool-3-thread-1] ERROR test.core.ZaleniumTestWatcher - Exception while setting cookie
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:153)	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:140)	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:110)	at test.core.ZaleniumTestWatcher.failed(ZaleniumTestWatcher.java:51)	at org.junit.rules.TestWatcher.failedQuietly(TestWatcher.java:84)	at org.junit.rules.TestWatcher.access$300(TestWatcher.java:46)	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:62)	at org.junit.rules.RunRules.evaluate(RunRules.java:20)	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:435)	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:42)	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:346)	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:239)	at org.junit.runners.Suite.runChild(Suite.java:128)	at org.junit.runners.Suite.runChild(Suite.java:27)	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)	at java.util.concurrent.FutureTask.run(FutureTask.java:266)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	at java.lang.Thread.run(Thread.java:748)Caused by: net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (The appium.platformName needs to be specified (either IOS or ANDROID)	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:137)	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:149)	... 30 moreCaused by: net.thucydides.core.webdriver.ThucydidesConfigurationException: The appium.platformName needs to be specified (either IOS or ANDROID)	at net.thucydides.core.webdriver.appium.AppiumConfiguration.lambda$getTargetPlatform$1(AppiumConfiguration.java:38)	at java.util.Optional.orElseThrow(Optional.java:290)	at net.thucydides.core.webdriver.appium.AppiumConfiguration.getTargetPlatform(AppiumConfiguration.java:38)	at net.serenitybdd.core.webdriver.driverproviders.RemoteWebdriverStub.from(RemoteWebdriverStub.java:13)	at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider.newInstance(RemoteDriverProvider.java:50)	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:127)	... 31 moreTests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 120.168 sec <<< FAILURE! - in test.ProductManagementTest
addsNewProductAndModifiesIt(test.ProductManagementTest)  Time elapsed: 10.693 sec  <<< ERROR!
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Socket timeout reading Marionette handshake data: Resource temporarily unavailable (os error 11)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: '36166230eafe', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-135-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 10.61 seconds
	at pages.LoginPage.navigateToLoginPage(LoginPage.java:21)
	at step.LoginSteps.navigateToLoginPage(LoginSteps.java:26)
	at step.LoginSteps.logsIn(LoginSteps.java:16)
	at test.ProductManagementTest.addsNewProductAndModifiesIt(ProductManagementTest.java:38)

**Comment by wakaleo** [comment]
The driver choice is deterministic - try checking for code or environment changes since the last test runs.
