### ISSUE TITLE
IE 11 Browser Load Issue on Serenity Core Version 1.9.36

### ISSUE THREAD

**Issue by raju1986** [serenity-bdd/serenity-core#1386]
Issue while running bdd testcases in IE browser using Serenity

**Description :**
We are trying run our bdd testcases in IE browser by providing the required configuration in serenity.properties.

- If a feature file contains a scenario with multiple examples, then only for first example IE Browser is launched and URL is added and executed but for next example it just launches the IE Browser but URL is not passed.

- Also for all the other scenarios it just launches browser and URL is not passed.

We tried all the below options to resolve it but no luck and are still in same state :

**https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration
https://github.com/serenity-bdd/serenity-core/issues/1360
https://groups.google.com/forum/#!msg/thucydides-users/GyhZ84m7Z_4/WZqhNJg0CwAJ**

**We are getting below exception in logs :**
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for By.xpath: //*[contains(@id,'pm-navigation-modality-container')]/div/div/span[contains(., 'XR')] to be displayed (tried for 30 second(s) with 100 milliseconds interval)
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'G7HQ03H2E', ip: '172.27.112.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_162'
Driver info: driver.version: unknown
        at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:303)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
        at net.serenitybdd.core.pages.WebElementFacadeImpl.checkPresenceOfWebElement(WebElementFacadeImpl.java:855)
        ... 34 more

**Note : Please don't go by "Element Not Found" issue as it is working fine for First Scenario and only for subsequent scenarios we are getting this exception and also in older version of Serenity**

IE tests were running fine on older version of Serenity (1.1.36) and Serenity JBehave Version (1.13.0) but only after migrating to latest version we are seeing this issue.

Below are the configuration details on which we are facing this issue 👍 
Serenity Version : 1.9.36
Serenity JBehave Version : 1.42.0
Selenium Version : 3.13.0
IE Version : 11.0
webdriver.ie.driver=src/test/resources/pm/drivers/IEDriverServer.exe
webdriver.driver=iexplorer

**Comment by wakaleo** [comment]
The only relevant difference is the Selenium  version

**Comment by raju1986** [comment]
Yes. We are using the default Selenium Version 3.13.0 which gets downloaded as part of Serenity Core.
Do you suggest to try with latest Selenium Version 3.14.0 version ?

**Comment by wakaleo** [comment]
Yes.

**Comment by wakaleo** [comment]
Closing for lack of activity.
