### ISSUE TITLE
grid timing issue - net.thucydides.core.webdriver.WebDriverFacade.findElements(WebDriverFacade.java:218)

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#139]
There is bug at line 
at net.thucydides.core.webdriver.WebDriverFacade.findElements(WebDriverFacade.java:218)

remotewebdriver doesn't comply to timeout values mentioned in serenity.properties

complete output from maven run as below

--------

org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash

from tab crashed

  (Session info: chrome=45.0.2454.101)

  (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 4.0.9-boot2docker x86_64) (WARNING: The server did not provide any stacktrace information)

Command duration or timeout: 54 milliseconds

Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'

System info: host: '0d486fa379ca', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.0.9-boot2docker', java.version: '1.8.0_45-internal'

Driver info: org.openqa.selenium.chrome.ChromeDriver

Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.s9atpE}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=45.0.2454.101, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]

Session ID: 69852c4d124eb0b4d571cb4eb6bab1e6

*** Element info: {Using=xpath, value=//text[@rel='smart_list_inbox']}

Command duration or timeout: 190 milliseconds

Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'

System info: host: '6wbuildbot.local', ip: '10.40.6.48', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_05'

Driver info: org.openqa.selenium.remote.RemoteWebDriver

Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.s9atpE}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=45.0.2454.101, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=630cdb26-e7af-42c5-80a1-daf76b0af851, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]

Session ID: 630cdb26-e7af-42c5-80a1-daf76b0af851

*** Element info: {Using=xpath, value=//text[@rel='smart_list_inbox']}

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:408)

at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)

at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)

at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)

at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:373)

at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:449)

at org.openqa.selenium.By$ByXPath.findElements(By.java:353)

at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:336)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:483)

at org.openqa.selenium.remote.Augmenter$CompoundHandler.intercept(Augmenter.java:191)

at org.openqa.selenium.remote.RemoteWebDriver$$EnhancerByCGLIB$$8c77a11d.findElements(<generated>)

at net.thucydides.core.webdriver.WebDriverFacade.findElements(WebDriverFacade.java:218)

---------

I tried Docket setup with another repo https://github.com/Ardesco/Selenium-Maven-Template and it worked well.

Can you please look into this bug ?

**Comment by vikramvi** [comment]
Because of this scenarios like gmail log-in , fails as after entering id and pwd , clicking enter driver doesn't wait for required time and instead finishes action with few milliseconds.

**Comment by wakaleo** [comment]
FindElements is designed to not wait, as it is often used to check for the presence of elements that can legitimately be missing. This is the historical behaviour of Selenium, though they changed it in a recent version and broke many tests. There are many ways to control the timeouts beyond the default values. Can you share a sample project on GitHub?
