### ISSUE TITLE
Error running feature from Intellij Runner

### ISSUE THREAD

**Issue by jdmesalosada** [serenity-bdd/serenity-core#1405]
Hi everybody, I'm getting the following error running the feautures using intellij. 
Serenity version: 2.0.3
Plugin: Cucuumber for java

java.lang.NullPointerException
	at net.thucydides.core.steps.StepEventBus.updateOverallResults(StepEventBus.java:706)
	at net.serenitybdd.screenplay.EventBusInterface.updateOverallResult(EventBusInterface.java:34)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:170)

Thanks.

**Comment by jdmesalosada** [comment]
In your runner in Main class you have to put: net.serenitybdd.cucumber.cli.Main
<img width="352" alt="mainclass" src="https://user-images.githubusercontent.com/5983195/46875029-418ece80-ce00-11e8-90f3-c95a30464e49.png">
