### ISSUE TITLE
Get NPE On ScenarioFilter class

### ISSUE THREAD

**Issue by Hendrione** [serenity-bdd/serenity-core#1424]
I got error when tried to use parallel testing in my automation. the error shows that I got `NullPointerException` on `ScenarioFilter` class. Looks like method geMethodName() is returning null.

        `String methodName = description.getMethodName();
        boolean shouldRun = scenarios.stream().anyMatch(methodName::equals) || displayName.startsWith("Examples") || displayName.contains("|");`
Did I miss something? Here is the log:

`17:51:51.818 [main] ERROR net.serenitybdd.cucumber.CucumberWithSerenity - Test failed to start
java.lang.NullPointerException: null
        at net.serenitybdd.cucumber.suiteslicing.ScenarioFilter.shouldRun(ScenarioFilter.java:36)
        at org.junit.runners.ParentRunner.shouldRun(ParentRunner.java:434)
        at org.junit.runners.ParentRunner.filter(ParentRunner.java:382)
        at net.serenitybdd.cucumber.CucumberWithSerenity.lambda$toPossibleFeatureRunner$3(CucumberWithSerenity.java:161)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at net.serenitybdd.cucumber.CucumberWithSerenity.getChildren(CucumberWithSerenity.java:136)
        at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
        at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
`

**Comment by wakaleo** [comment]
Try not using forks.

**Comment by Hendrione** [comment]
still happening. already tried use:
`mvn clean verify -Dserenity.batch.count=3 -Dserenity.batch.number=2 -Dserenity.test.statistics.dir=/statistics`

**Comment by Hendrione** [comment]
Here is my maven failsafe plugin in pom.xml 
`          <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin}</version>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <includes>
                        <include>**/CucumberRunner*.java</include>
                    </includes>
                    <systemPropertyVariables>
                        <cucumber.options>--junit,--step-notifications</cucumber.options>
                        <spring.config.location>classpath:/application-UATA.properties</spring.config.location>
                        
                        
                    </systemPropertyVariables>
                </configuration>
            </plugin>`

**Comment by Hendrione** [comment]
Note: I didn't add configuration for parallel testing on systemPropertiesVariables and in serenity.properties

**Comment by wakaleo** [comment]
Are you trying to do parallel testing or batch testing (they are very different things)?

**Comment by Hendrione** [comment]
Oh sorry, I tried this command. I want to run in parallel actually.
```
mvn clean verify -Dserenity.batch.count=3 -Dserenity.batch.number=2 -Dserenity.fork.number=1 -Dserenity.fork.count=2 -Dserenity.test.statisti
cs.dir=/statistics
```

**Comment by wakaleo** [comment]
Try https://johnfergusonsmart.com/running-parallel-tests-serenity-bdd-cucumber/

**Comment by Hendrione** [comment]
I tried this actually:
[](https://serenity-bdd.github.io/theserenitybook/latest/serenity-parallel.html)

**Comment by Hendrione** [comment]
I just following the steps and got error. already implemented the sample code here also
[https://github.com/serenity-bdd/serenity-cucumber](https://github.com/serenity-bdd/serenity-cucumber)
IDK why it is still getting NPE. Already using latest version of Serenity 2.0.10

**Comment by Hendrione** [comment]
Ok will try

**Comment by Hendrione** [comment]
Hi @wakaleo, I already found the problem. IDK when I add cucumber options `--junit,--step-notifications`, the methodname data is getting null. that's why it is getting error. but IDK how to solve this since it is in Junit library.

**Comment by wakaleo** [comment]
Maybe @nbarrett could help (he wrote the sliding code)

**Comment by nbarrett** [comment]
Hi @Hendrione - It looks like you've fixed it now by removing those cucumber options (which I have to admit I have no knowledge of). In all cases when I've developed and tested the batching, `description.getMethodName()` always returns the scenario name. For instance I just put a breakpoint inside that filter and ran a feature and you can see that is is populated with the scenario name (scenario preview in background):

![image](https://user-images.githubusercontent.com/626941/47586178-641ffc00-d957-11e8-8541-e558b98852e2.png)

Do you need those cucumber options or can you live without them?

**Comment by Hendrione** [comment]
Actually those cucumber options is used for displaying the detail step in my IDE (Intellij IDEA) whe I run using JUnit. if I am not use the options, it will show the output like this:
<img width="960" alt="withoutstepnotifications" src="https://user-images.githubusercontent.com/6661010/47597127-269e8b80-d9b6-11e8-9df8-5af41b3308ee.png">

If I use those cucumber Options, it will show more detailed steps and it will make us easier to debug and check the error.
<img width="960" alt="witstepnotifications" src="https://user-images.githubusercontent.com/6661010/47597142-459d1d80-d9b6-11e8-96e1-6a9f9f54a0f3.png">

**Comment by wakaleo** [comment]
If Cucumber is not populating those fields when certain options are used, it sounds like a Cucumber defect not a Serenity one.

**Comment by nbarrett** [comment]
To me, the need to run in parallel batches is a separate concern to the need to debug and see real-time output and in practice you'd be doing those things at separate points in your story development lifecycle. In my experience, It's only really worth trying to get test suites running in parallel when you've completed the development of the test and it's reliable. Hope this helps?

**Comment by Hendrione** [comment]
@nbarrett yah I agree with you. So we can create different profile just like in the tutorial to run. One for parallel and one for not parallel.

@wakaleo ok. should be cucucumber defect.
