### ISSUE TITLE
ERROR: org.openqa.selenium.remote.ProtocolHandshake createSession

### ISSUE THREAD

**Issue by rakeshnambiar** [serenity-bdd/serenity-core#1429]
Log 
------------------------------------------------------------------------------------------------------------
Oct 29, 2018 12:33:28 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Starting ChromeDriver 2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a) on port 2453
Only local connections are allowed.
Oct 29, 2018 12:33:31 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
      java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
-------------------------------------------------------------------------------------------------------------
OS - Win10
<serenity.version>2.0.11</serenity.version>
<serenity.maven.version>2.0.11</serenity.maven.version>
<serenity.cucumber.version>1.9.20</serenity.cucumber.version>

I am not sure, this issue is related to Selenium core.

**Comment by wakaleo** [comment]
Could you post the full stack trace?

**Comment by rakeshnambiar** [comment]
@wakaleo 

Oct 29, 2018 12:33:28 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Starting ChromeDriver 2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a) on port 2453
Only local connections are allowed.
Oct 29, 2018 12:33:31 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
      java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at net.thucydides.core.webdriver.WebdriverInstances.registeredDriverNameFor(WebdriverInstances.java:157)
	at net.thucydides.core.webdriver.WebdriverInstances.setCurrentDriverTo(WebdriverInstances.java:148)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.setCurrentDriver(SerenityWebdriverManager.java:128)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:115)
	at net.thucydides.core.webdriver.WebDriverFacade.getDriverClass(WebDriverFacade.java:99)
	at net.thucydides.core.webdriver.WebDriverType.isMobile(WebDriverType.java:9)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:48)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:19)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:158)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:162)
	at net.thucydides.core.pages.Pages.createFromSimpleConstructor(Pages.java:236)
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:204)
	at net.thucydides.core.pages.Pages.getPage(Pages.java:90)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)

**Comment by wakaleo** [comment]
Do you have any page objects that contain other page objects as fields?

**Comment by rakeshnambiar** [comment]
I think Yes. It was working fine with the older version and I tried to use the latest 😊

**Comment by wakaleo** [comment]
What was the previous version?

**Comment by rakeshnambiar** [comment]
<serenity.version>1.6.0</serenity.version>
        <serenity.maven.version>1.5.11</serenity.maven.version>
        <serenity.cucumber.version>1.5.9</serenity.cucumber.version>

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces the issue?

**Comment by rakeshnambiar** [comment]
@wakaleo Thanks for your response. Please find the attached sample project.
[sample_project.zip](https://github.com/serenity-bdd/serenity-core/files/2525713/sample_project.zip)

**Comment by wakaleo** [comment]
Not sure if it's the only thing, but the circular dependency in the EuropePmcHomePage class will cause problems - try removing the field and calling the method directly.

**Comment by rakeshnambiar** [comment]
@wakaleo thanks again for checking the sample project. I just removed all the unused fields and methods from both the classes and now the test is PASS. Now let me figure out which field/method is causing the real problem.

**Comment by wakaleo** [comment]
I'm pretty sure it's the EuropePmcHomePage field nested in the EuropePmcHomePage class - if you remove this field, and replace the code that uses this field with a simple method call, it appears to work.
