### ISSUE TITLE
Exception - Failed to generate configuration report

### ISSUE THREAD

**Issue by ariksher-nex** [serenity-bdd/serenity-core#1442]
I'm running Serenity-Core version 2.0.11
and serenity-gradle-plugin version 2.0.11
and Serenity-Cucumber 1.9.19

and I get (inconsistently) the following exception:

> com.ebs.direct.acceptance.MdNormalizerAcceptanceTests > classMethod FAILED
> net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
>     Caused by:
>     java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@25935d7b
>         Caused by:
>         net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@25935d7b
>             Caused by:
>             java.util.NoSuchElementException: No value present

**Comment by wakaleo** [comment]
We can't do much with this error in it's present state - can you provide a sample project that reproduces the issue?

**Comment by ariksher-nex** [comment]
- parent file **build.gradle** relevant content:

```
buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath 'net.serenity-bdd:serenity-gradle-plugin:2.0.11'
    }
}

allprojects {
    repositories {
        mavenLocal()
    }

    dependencyManagement {
       dependencies {
            dependency 'junit:junit:4.12'
            dependency 'net.serenity-bdd:serenity-core:2.0.11'
            dependency 'net.serenity-bdd:serenity-cucumber:1.9.19'
       }
    }
}
```

- failing module , file **build.gradle** content:

```
defaultTasks 'clean', 'jar', 'aggregate'

apply plugin: 'net.serenity-bdd.aggregator'

dependencies {
    testCompile 'net.serenity-bdd:serenity-core'
    testCompile 'net.serenity-bdd:serenity-cucumber'
}

```

- the test class that runs the Cucumber:

package com.ebs.direct.acceptance;

import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
    tags = {"not @limitation", "not @known_issue"},
    plugin = {"pretty"},
    features = "src/test/resources/features/md-normalizer"
)
public class **MdNormalizerAcceptanceTests** {

}

**Comment by ariksher-nex** [comment]
is it enough?

**Comment by ariksher-nex** [comment]
> We can't do much with this error in its present state - can you provide a sample project that reproduces the issue?

is it enough?

**Comment by wakaleo** [comment]
No, we would need a full project that reproduces the issue. The issue is most likely related to the tests themselves.

**Comment by ariksher-nex** [comment]
Not sure I can upload the entire project.
Still, up until recently we used version 1.9.45,
and only after upgrading to 2.0.11 we started seeing it.
we did **not** touch the tests themselves.

**Comment by wakaleo** [comment]
Do you have at least a full stack trace?

**Comment by ariksher-nex** [comment]
the stack I got is in the description. 
isn't it the full one?
if not how should i dump one?

**Comment by ariksher-nex** [comment]
trying to run gradle test with --full-stacktrace 
because its inconsistent, need to run X times.... 
:-|
trying...

**Comment by wakaleo** [comment]
There should be line numbers, in the report (which is a summary version) or in the Gradle test reports.

**Comment by ariksher-nex** [comment]
OK found it. I have stack trace for each line seperatley. loading them.

**Comment by ariksher-nex** [comment]
**net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report**
at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:203)
at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:180)
at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:892)
at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:325)
at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:121)
at cucumber.runner.EventBus.send(EventBus.java:28)
at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:128)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:564)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:564)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
at java.lang.Thread.run(Thread.java:844)

**Comment by ariksher-nex** [comment]
**Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@e08d1e3**

at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:191)
at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:200)
at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:180)
at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:892)
at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:325)
at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:121)
at cucumber.runner.EventBus.send(EventBus.java:28)
at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:128)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:564)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:564)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
at java.lang.Thread.run(Thread.java:844)

**Comment by ariksher-nex** [comment]
**Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@e08d1e3**

at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:241)
at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:844)

**Comment by ariksher-nex** [comment]
**Caused by: java.util.NoSuchElementException: No value present**

at java.util.Optional.get(Optional.java:151)
at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:95)
at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:198)
at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:186)
at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:162)
at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:106)
at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:844)

**Comment by wakaleo** [comment]
Based on this I will need to see your whole project.

**Comment by wakaleo** [comment]
Then try to create a sample project that reproduces the issue. Specific files won't help very much, as I don't know where the problem is.

**Comment by ariksher-nex** [comment]
I think I know whats causing the problem.
At class **BaseRequirementsService**, method **getAncestorRequirementsFor**
```
if (matchingAncestorFor(requirement.get()).isPresent()) {
   Requirement matchingAncestor = matchingAncestorFor(requirement.get()).get();
```
looks like **matchingAncestorFor(requirement.get())** returns different output on the if part (.isPresent) and on the line below (.get).

I will create a PR for it.

**Comment by ariksher-nex** [comment]
looks like the problem is solved in 2.0.13.
could it be?

**Comment by dileepguntamadugu** [comment]
This issues seems to be happening with 2.0.42. Below is the exception stack trace.

net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:203)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:180)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
	at net.serenitybdd.junit.runners.SerenityParameterizedRunner.generateReportsFor(SerenityParameterizedRunner.java:216)
	at net.serenitybdd.junit.runners.SerenityParameterizedRunner.generateReports(SerenityParameterizedRunner.java:212)
	at net.serenitybdd.junit.runners.SerenityParameterizedRunner.run(SerenityParameterizedRunner.java:207)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:346)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:346)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC$1.run(ParallelComputerBuilder.java:535)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.json.JSONTestOutcomeReporter@767e20cf
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:200)
	... 35 more
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.json.JSONTestOutcomeReporter@767e20cf
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:240)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.InvalidPathException: **Illegal char <:> at index 2: /C:/Users/dileep/eclipse-workspace/serenitytestautomation/target/test-classes/features**
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at net.thucydides.core.requirements.model.RequirementsConfiguration.<init>(RequirementsConfiguration.java:34)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.<init>(FileSystemRequirementsTagProvider.java:117)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.<init>(FileSystemRequirementsTagProvider.java:75)
	at net.serenitybdd.cucumber.service.CucumberTagProviderStrategy.getTagProviders(CucumberTagProviderStrategy.java:36)
	at net.thucydides.core.statistics.service.ClasspathTagProviderService.allKnownTagProviders(ClasspathTagProviderService.java:90)
	at net.thucydides.core.statistics.service.ClasspathTagProviderService.loadTagProvidersFromPath(ClasspathTagProviderService.java:54)
	at net.thucydides.core.statistics.service.ClasspathTagProviderService.tagProvidersFor(ClasspathTagProviderService.java:36)
	at net.thucydides.core.statistics.service.ClasspathTagProviderService.getTagProviders(ClasspathTagProviderService.java:28)
	at net.thucydides.core.model.TestOutcome.getTags(TestOutcome.java:1736)
	at net.thucydides.core.model.TestOutcome.addVersionsDefinedInTagsTo(TestOutcome.java:1616)
	at net.thucydides.core.model.TestOutcome.getVersions(TestOutcome.java:1611)
	at net.thucydides.core.model.TestOutcome.calculateDynamicFieldValues(TestOutcome.java:338)
	at net.thucydides.core.reports.json.gson.GsonJSONConverter.toJson(GsonJSONConverter.java:81)
	at net.thucydides.core.reports.json.JSONTestOutcomeReporter.generateReportFor(JSONTestOutcomeReporter.java:60)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:238)
	... 6 more

**Comment by RobertoPegoraro** [comment]
I'm facing the same problem when running remotely

`P166RunCucumber > executionError FAILED
502715 [Thread-3] INFO  c.c.s.d.CloseDriverCommand - Close webdriver: 43 -> RemoteWebDriver: chrome on Windows XP (0a233cb8f6e4ae2228a494837ad2b464)...
    net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
        at app//net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:211)
        at app//net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:188)
        at app//net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:134)
        at app//io.cucumber.core.plugin.SerenityReporter.generateReports(SerenityReporter.java:993)
        at app//io.cucumber.core.plugin.SerenityReporter.handleTestRunFinished(SerenityReporter.java:377)
        at app//io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at app//io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at app//io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
        at app//io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:111)
        at app//io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:98)
        at app//io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:291)
        at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at app//org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at app//org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at app//org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
        at java.base@11/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base@11/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base@11/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base@11/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base@11/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base@11/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base@11/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base@11/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base@11/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@11/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at app//org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
        at app//org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at java.base@11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base@11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@11/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

        Caused by:
        java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.json.JSONTestOutcomeReporter@1fc3d3ec
            at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
            at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
            at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:208)
            ... 56 more

            Caused by:
            net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.json.JSONTestOutcomeReporter@1fc3d3ec
                at app//net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:248)
                at app//net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:184)
                at java.base@11/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base@11/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base@11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base@11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base@11/java.lang.Thread.run(Thread.java:834)

                Caused by:
                java.nio.file.NoSuchFileException: target/site/serenity/0f5667a375e739bac2b387d32961b2edba7e2ced691a58f68aa0071588f778f2.json6bcbed46-9c45-4fe1-af2f-e7eab05f92fb -> target/site/serenity/0f5667a375e739bac2b387d32961b2edba7e2ced691a58f68aa0071588f778f2.json
                    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
                    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
                    at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:417)
                    at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:263)
                    at java.base/java.nio.file.Files.move(Files.java:1421)
                    at net.thucydides.core.reports.io.SafelyMoveFiles.to(SafelyMoveFiles.java:30)
                    at net.thucydides.core.reports.io.SafelyMoveFiles.to(SafelyMoveFiles.java:39)
                    at net.thucydides.core.reports.io.SafelyMoveFiles.to(SafelyMoveFiles.java:39)
                    at net.thucydides.core.reports.io.SafelyMoveFiles.to(SafelyMoveFiles.java:39)
                    at net.thucydides.core.reports.json.JSONTestOutcomeReporter.generateReportFor(JSONTestOutcomeReporter.java:64)
                    at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:246)
                    ... 6 more
`
