### ISSUE TITLE
Issue with uploading file to remote machine

### ISSUE THREAD

**Issue by vzakharchuk** [serenity-bdd/serenity-core#1450]
Hey, 

could you please take a look at my config?
can't figure out what I'm missing here. 

from serenity.properties 

```
webdriver.base.url=http://localhost:8081
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = driver.ExtendedDriver
webdriver.remote.url = http://hub_adress:4444/wd/hub
```

from ExtendedDriver class

```
        String remoteAdress = getProperty("webdriver.remote.url", getSerenityProperty(BASE_REMOTE_URL));
        if(remoteAdress != null){
                capabilities.setCapability("enableVNC", true);
                remoteWebDriver =  new RemoteWebDriver(create(remoteAdress).toURL(), capabilities);
                remoteWebDriver.setFileDetector(new LocalFileDetector());
                return remoteWebDriver;
```
from test code 
```
        File file = new ArtifactoryService().downloadFile(fileName);
        upload(file.getAbsolutePath()).to(element(UPLOAD_FILE_LOCATOR));
```
The file is successfully dowloaded to the local machine 
The issue is with upload() method which I'm using to upload the file to the remote machine.
but constantly getting 

```
17:37:41     org.openqa.selenium.WebDriverException: invalid argument: File not found : /tmp/9cc5bdc59dbb6b155b37f5824dc79b95/D1.dash
17:37:41       (Session info: chrome=70.0.3538.67)
17:37:41       (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.4.0-135-generic x86_64) (WARNING: The server did not provide any stacktrace information)
17:37:41     Command duration or timeout: 0 milliseconds
17:37:41     Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
17:37:41     System info: host: '77c8e34051f1', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_181'
17:37:41     Driver info: org.openqa.selenium.remote.RemoteWebDriver
17:37:41     Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.43.600233 (523efee95e3d68..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:38771}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 70.0.3538.67, webStorageEnabled: true}
17:37:41     Session ID: 9cc5bdc59dbb6b155b37f5824dc79b95
17:37:41     	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
17:37:41     	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
17:37:41     	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
17:37:41     	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
17:37:41     	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
17:37:41     	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
17:37:41     	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
17:37:41     	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
17:37:41     	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
17:37:41     	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
17:37:41     	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
17:37:41     	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
17:37:41     	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:100)
17:37:41     	at net.serenitybdd.core.pages.WebElementFacadeImpl.sendKeys(WebElementFacadeImpl.java:1101)
17:37:41     	at net.thucydides.core.pages.components.FileToUpload.to(FileToUpload.java:87)
17:37:41     	at pages.AbstractPage.uploadDashboardFile(AbstractPage.java:181)
17:37:41     	at step_definitions.AnalyticsSteps.importDashboard(AnalyticsSteps.java:68)
17:37:41     	at ✽.Import "D1.dash" dashboard(src/test/resources/features/Analytics/Navver/Folders.feature:49)
```

**Comment by wakaleo** [comment]
Looks like a (Selenium) usage question rather than a bug - could you post it on https://serenity-bdd.rocket.chat?

**Comment by vzakharchuk** [comment]
thanks for the reply! already did. 
I just wanted to specify if I'm using correctly Serenity upload() method?

**Comment by vzakharchuk** [comment]
it was fixed by Selenoid configuration change.
