### ISSUE TITLE
Not able to run Serenity & jBehave tests on firefox

### ISSUE THREAD

**Issue by kailaygurdeep** [serenity-bdd/serenity-core#1461]
Trying to run a maven project in Eclipse IDE with jBehave serenity and when I run my story, it does not open Firefox or any browser and shows below mentioned error.
Versions, I am using :
Firefox : 63.0.3(64 bit)
<serenity.version>2.0.15</serenity.version>
<serenity.jbehave.version>1.44.0</serenity.jbehave.version>
geckodriver : v0.23.0

net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:154)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:142)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:112)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:182)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:861)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:762)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:750)
	at com.sentaca.serenity.steps.LoginPageSteps.open(LoginPageSteps.java:17)

**Comment by wakaleo** [comment]
Most likely a Firefox/WebDriver version compatibility issue. Do you have any reason to suspect that the issue comes from the Serenity code?

**Comment by kailaygurdeep** [comment]
As I am unable to resolve this issue so wanted to try any solution or advise you could provide.
Do you know how to fix this if it is Firefox/WebDriver compatibility issue?
Thanks in Advance!

**Comment by wakaleo** [comment]
Is there any other log message. The one you have listed is just a wrapper for the Selenium error.

**Comment by wakaleo** [comment]
Closing for lack of activity - I presume this is a driver compatibility issue with Firefox.
