### ISSUE TITLE
Cannot find Chrome binary

### ISSUE THREAD

**Issue by parshk** [serenity-bdd/serenity-core#1508]
In Linux, I'm trying to run a serenity test using the Chrome driver, the following exception is thrown:

**The error:**

> 19:19:38.140 [DEBUG] [TestEventLogger]         Caused by:
> 19:19:38.140 [DEBUG] [TestEventLogger]         net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (unknown error: cannot find Chrome binary
> 19:19:38.140 [DEBUG] [TestEventLogger]           (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 2.6.32-696.18.7.el6.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
> 

Chrome driver seems to be installed properly, since chromedriver -v and whereis chromedriver returns **ChromeDriver 2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634)** and **/usr/local/bin/chromedriver** respectively. The path of the chromedriver added to PATH variable and I'm running my code as root.

**serenity.properties:**
```
serenity.issue.tracker.url = http://10.249.233.146:8080/browse/{0}
serenity.reports.show.step.details=true
serenity.restart.browser.for.each=Story
webdriver.driver=chrome
webdriver.chrome.driver=/usr/local/bin/chromedriver
chrome.switches=--headless
webdriver.timeouts.implicitlywait=2000
webdriver.wait.for.timeout = 20000
serenity.take.screenshots=FOR_FAILURES
thucycides.step.delay=100ms
serenity.timeout=2000
serenity.browser.height=1080
serenity.browser.width=1600
```

Thanks in advance for your help.

**Comment by wakaleo** [comment]
"cannot find Chrome binary" is WebDriver telling you that it can't find the chrome driver binary. I can't see anything wrong with the config, but the error message is pretty unambiguous. What happens when you run `/usr/local/bin/chromedriver -v`?

As an aside, running any code as root is probably not a great idea.

**Comment by parshk** [comment]
Thanks @wakaleo for your help. Actually /usr/local/bin/chromdriver -v returns **ChromeDriver 2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634)**.
I ran the code without root privilege, but still the same error.
This is the error track: 

```
12:07:31.281 [DEBUG] [TestEventLogger]     net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:157)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:144)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:114)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:189)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:184)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:828)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.serenitybdd.core.pages.PageObject.open(PageObject.java:738)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.serenitybdd.core.pages.PageObject.open(PageObject.java:726)
12:07:31.281 [DEBUG] [TestEventLogger]         at com.jira.serenity.users.JiraUser.loginIfNotAlreadyLoggedIn(JiraUser.java:20)
12:07:31.281 [DEBUG] [TestEventLogger]         at com.jira.serenity.users.JiraUser$$EnhancerByCGLIB$$17bb07a1.CGLIB$loginIfNotAlreadyLoggedIn$0(<generated>)
12:07:31.281 [DEBUG] [TestEventLogger]         at com.jira.serenity.users.JiraUser$$EnhancerByCGLIB$$17bb07a1$$FastClassByCGLIB$$b0a4b1cc.invoke(<generated>)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:395)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:380)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:355)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:132)
12:07:31.281 [DEBUG] [TestEventLogger]         at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
12:07:31.281 [DEBUG] [TestEventLogger]         at com.jira.serenity.users.JiraUser$$EnhancerByCGLIB$$17bb07a1.loginIfNotAlreadyLoggedIn(<generated>)
12:07:31.281 [DEBUG] [TestEventLogger]         at com.jira.serenity.features.behaviours._Steps.before(_Steps.java:14)
12:07:31.281 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:07:31.281 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:07:31.281 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:07:31.281 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
12:07:31.281 [DEBUG] [TestEventLogger]         at cucumber.runtime.Utils$1.call(Utils.java:40)
12:07:31.281 [DEBUG] [TestEventLogger]         at cucumber.runtime.Timeout.timeout(Timeout.java:16)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.Utils.invoke(Utils.java:34)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.Suite.runChild(Suite.java:128)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.Suite.runChild(Suite.java:27)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.junit.ExamplesRunner.run(ExamplesRunner.java:59)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.Suite.runChild(Suite.java:128)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.Suite.runChild(Suite.java:27)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.junit.ScenarioOutlineRunner.run(ScenarioOutlineRunner.java:53)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
12:07:31.282 [DEBUG] [TestEventLogger]         at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
12:07:31.282 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:07:31.282 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:07:31.282 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:07:31.282 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
12:07:31.282 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
12:07:31.283 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
12:07:31.283 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:07:31.283 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:07:31.283 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:07:31.283 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
12:07:31.283 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:07:31.283 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:07:31.283 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
12:07:31.283 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:748)
12:07:31.283 [DEBUG] [TestEventLogger]
12:07:31.283 [DEBUG] [TestEventLogger]         Caused by:
12:07:31.283 [DEBUG] [TestEventLogger]         net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (unknown error: cannot find Chrome binary
12:07:31.283 [DEBUG] [TestEventLogger]           (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 2.6.32-696.18.7.el6.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
12:07:31.283 [DEBUG] [TestEventLogger]         Command duration or timeout: 13 milliseconds
12:07:31.283 [DEBUG] [TestEventLogger]         Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
12:07:31.283 [DEBUG] [TestEventLogger]         System info: host: 'ip-10-249-233-146.ec2.internal', ip: '10.249.233.146', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-696.18.7.el6.x86_64', java.version: '1.8.0_161'
12:07:31.283 [DEBUG] [TestEventLogger]         Driver info: driver.version: ChromeDriver
12:07:31.283 [DEBUG] [TestEventLogger]             at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:135)
12:07:31.283 [DEBUG] [TestEventLogger]             at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:153)
12:07:31.283 [DEBUG] [TestEventLogger]             ... 97 more
12:07:31.283 [DEBUG] [TestEventLogger]
12:07:31.283 [DEBUG] [TestEventLogger]             Caused by:
12:07:31.283 [DEBUG] [TestEventLogger]             org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary

```

**Comment by wakaleo** [comment]
Hmmm, Serenity is just reporting the error that ChromeDriver is reporting ("cannot find Chrome binary") which could be that the file is not on the path, or not in the place defined by the webdriver.chrome.driver property, or not executable for some reason. To say more than that I would need to look at your environment. It doesn't appear to be a Serenity issue.

**Comment by parshk** [comment]
Not sure if this additional info could help.
I tried to run my code on Windows through command line. When we don't set webdriver.chrome.driver in the serenity.properties, it works properly, but once I add webdriver.chrome.driver to serenity.properties it throws the same error "cannot find chrome binary"! (Variable environment was set correctly and the path to chrome driver is correct).
But in Linux, for both cases (either we set webdriver.chrome.driver or not), we have the same error.

**Comment by wakaleo** [comment]
Sound's like an environment-specific issue. I can only suppose that Selenium is not happy with the binary specified in the `webdriver.chrome.driver` variable. If you raise a support ticket (https://johnfergusonsmart.com/serenity-bdd-mentoring#support) we can take a closer look.

**Comment by parshk** [comment]
Thanks @wakaleo for your help. Resolved.

**Comment by rpasive** [comment]
may we know how this was resolved? i'm having the same issue

**Comment by parshk** [comment]
Finally we added following line to serenity.properties and our issue was resolved.
**chrome.switches=--headless;--disable-dev-shm-usage**

**Comment by mcocosila** [comment]
For me the real cause was that the Chrome browser was not installed in the Linux machine (Linux docker image). Error message reported by ChromeDriver "cannot find **Chrome binary**" is confusing.

See https://stackoverflow.com/a/43306178

**Comment by rpasive** [comment]
@mcocosila exactly my issue too. had to ask the admins to install chrome on the ubuntu server. thanks guys
