### ISSUE TITLE
Broken Report and FreeMarker Exceptions

### ISSUE THREAD

**Issue by Shreya1417** [serenity-bdd/serenity-core#1544]
I've been battling with an issue for a few days now.
I'm using the latest version of serenity to run tests with JUnit. The tests complete and passes, but the report generation fails due to freemarker.core.NonHashException.
The reports generated show the overall tests results but the individual tests reports are not being generated. 

Any Ideas on how I can resolve the issue and generate reports?

The following is the error encountered:

TEST PASSED: Verify the login at the Airbnb portal
----------------------------------------------------------------------------
Jan 29, 2019 3:26:03 PM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
For "." left-hand operand: Expected a hash, but this has evaluated to a string (wrapper: f.t.SimpleScalar):
==> featureOrStory.get().type  [in template "freemarker/screenshots.ftl" at line 175, column 69]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign parentType = inflection.of(fe...  [in template "freemarker/screenshots.ftl" at line 175, column 33]
----

Java stack trace (for programmers):
----
freemarker.core.NonHashException: [... Exception message was already printed; see it above ...]
	at freemarker.core.Dot._eval(Dot.java:48)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.MethodCall._eval(MethodCall.java:58)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.ListLiteral.getModelList(ListLiteral.java:93)
	at freemarker.core.MethodCall._eval(MethodCall.java:63)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.MethodCall._eval(MethodCall.java:58)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.Assignment.accept(Assignment.java:134)
	at freemarker.core.Environment.visit(Environment.java:330)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.process(Environment.java:309)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:138)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:231)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:109)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

36156 [pool-2-thread-1] WARN net.thucydides.core.reports.templates.FreemarkerReportTemplate - Report generation failed
FreeMarker template error:
For "." left-hand operand: Expected a hash, but this has evaluated to a string (wrapper: f.t.SimpleScalar):
==> featureOrStory.get().type  [in template "freemarker/screenshots.ftl" at line 175, column 69]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign parentType = inflection.of(fe...  [in template "freemarker/screenshots.ftl" at line 175, column 33]
----

Java stack trace (for programmers):
----
freemarker.core.NonHashException: [... Exception message was already printed; see it above ...]
	at freemarker.core.Dot._eval(Dot.java:48)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.MethodCall._eval(MethodCall.java:58)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.ListLiteral.getModelList(ListLiteral.java:93)
	at freemarker.core.MethodCall._eval(MethodCall.java:63)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.MethodCall._eval(MethodCall.java:58)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.Assignment.accept(Assignment.java:134)
	at freemarker.core.Environment.visit(Environment.java:330)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.process(Environment.java:309)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:138)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:231)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:109)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
36159 [pool-2-thread-1] ERROR net.thucydides.core.reports.templates.FreemarkerReportTemplate - Syntax error in report template: For "." left-hand operand: Expected a hash, but this has evaluated to a string (wrapper: f.t.SimpleScalar):
==> featureOrStory.get().type  [in template "freemarker/screenshots.ftl" at line 175, column 69]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign parentType = inflection.of(fe...  [in template "freemarker/screenshots.ftl" at line 175, column 33]
----
	- Failed at: #assign parentType = inflection.of(fe...  [in template "freemarker/screenshots.ftl" at line 175, column 33]

net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:203)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:180)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReportsFor(SerenityRunner.java:400)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReports(SerenityRunner.java:295)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:248)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@23af9455
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:200)
	... 11 more
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@23af9455
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:241)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to merge template: Failed to process FreeMarker template
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:39)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:138)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:231)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:109)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	... 6 more
Caused by: net.thucydides.core.reports.templates.TemplateMergeException: Failed to process FreeMarker template
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:45)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
	... 10 more
Caused by: freemarker.core.NonHashException: For "." left-hand operand: Expected a hash, but this has evaluated to a string (wrapper: f.t.SimpleScalar):
==> featureOrStory.get().type  [in template "freemarker/screenshots.ftl" at line 175, column 69]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign parentType = inflection.of(fe...  [in template "freemarker/screenshots.ftl" at line 175, column 33]
----
	at freemarker.core.Dot._eval(Dot.java:48)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.MethodCall._eval(MethodCall.java:58)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.ListLiteral.getModelList(ListLiteral.java:93)
	at freemarker.core.MethodCall._eval(MethodCall.java:63)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.MethodCall._eval(MethodCall.java:58)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.Assignment.accept(Assignment.java:134)
	at freemarker.core.Environment.visit(Environment.java:330)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.process(Environment.java:309)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
	... 11 more
Please find the attachement of reports. 
![screenshot 221](https://user-images.githubusercontent.com/39733665/51900586-bd2a8080-23db-11e9-9cd1-326515142741.png)
![screenshot 222](https://user-images.githubusercontent.com/39733665/51900588-be5bad80-23db-11e9-98aa-95c3eeee21e3.png)
![screenshot 223](https://user-images.githubusercontent.com/39733665/51900589-be5bad80-23db-11e9-81bf-deb6e40c77fa.png)

**Comment by wakaleo** [comment]
It would be related to the specific tests and test data - can you share a project that reproduces the issue?

**Comment by Shreya1417** [comment]
[https://github.com/Shreya1417/WebApplicationAutomationUsingSerenity](url)

I have uploaded the project to my Git repository.
Please clone it from there and execute maven update to set up the project.

**Comment by wakaleo** [comment]
Your `pom.xml` file contains a reference to serenity-resources with a different version to the main serenity version:
```
<dependency>
    <groupId>net.serenity-bdd</groupId>
    <artifactId>serenity-report-resources</artifactId>
    <version>1.0.28</version>
</dependency>
```
Remove this dependency and your project will work.

**Comment by Shreya1417** [comment]
Thanks a lot..! This worked for me. I am getting expected reports now.
