### ISSUE TITLE
Using serenity 2.0.39 seeing a ClassCastException when interacting with a widget based element in a page object

### ISSUE THREAD

**Issue by dbirch-cognitoiq** [serenity-bdd/serenity-core#1555]
I am seeing the following exception using Serenity 2.0.39 when trying use a PageObject containing a Widget-based implementation.

The test is a hybrid android app, running in the web view context, so the driver wrapped by the WebDriverFacade is an AndroidDriver, provided by a custom DriverSource.

When first trying to interact with the widget based element in the page (which is initially instantiated fine), the following exception is thrown:
```
Failed to instantiate page (java.lang.ClassCastException: net.thucydides.core.webdriver.WebDriverFacade cannot be cast to org.openqa.selenium.remote.RemoteWebDriver)
```

The full stace trace is:
```
04/02 15:31:49.550 WARN  [Test worker] n.t.c.p.Pages: Failed to instantiate page of type class com.cognitoiq.test.helios.mobile.page.startup.SubscriberKeyEntryPage ({})
java.lang.ClassCastException: net.thucydides.core.webdriver.WebDriverFacade cannot be cast to org.openqa.selenium.remote.RemoteWebDriver
	at net.thucydides.core.webdriver.appium.AppiumConfiguration.getTargetPlatform(AppiumConfiguration.java:42) ~[serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:51) ~[serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41) ~[serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31) ~[serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21) ~[serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:19) ~[serenity-core-2.0.39.jar:2.0.39]
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:161) ~[serenity-core-2.0.39.jar:2.0.39]
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:165) ~[serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.pages.Pages.createFromSimpleConstructor(Pages.java:237) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:204) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.pages.Pages.getPage(Pages.java:90) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55) [serenity-core-2.0.39.jar:2.0.39]
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:166) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:156) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:139) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:86) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:76) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60) [serenity-core-2.0.39.jar:2.0.39]
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:42) [serenity-core-2.0.39.jar:2.0.39]
	at net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:135) [serenity-core-2.0.39.jar:2.0.39]
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:101) [serenity-core-2.0.39.jar:2.0.39]
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:68) [serenity-cucumber-1.9.30.jar:na]
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:51) [serenity-cucumber-1.9.30.jar:na]
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:41) [serenity-cucumber-1.9.30.jar:na]
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60) [cucumber-java-2.4.0.jar:na]
	at cucumber.runtime.HookDefinitionMatch.runStep(HookDefinitionMatch.java:17) [cucumber-core-2.4.0.jar:na]
	at cucumber.runner.UnskipableStep.executeStep(UnskipableStep.java:22) [cucumber-core-2.4.0.jar:na]
	at cucumber.api.TestStep.run(TestStep.java:83) [cucumber-core-2.4.0.jar:na]
	at cucumber.api.TestCase.run(TestCase.java:58) [cucumber-core-2.4.0.jar:na]
	at cucumber.runner.Runner.runPickle(Runner.java:80) [cucumber-core-2.4.0.jar:na]
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140) [cucumber-junit-2.4.0.jar:na]
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68) [cucumber-junit-2.4.0.jar:na]
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23) [cucumber-junit-2.4.0.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73) [cucumber-junit-2.4.0.jar:na]
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118) [cucumber-junit-2.4.0.jar:na]
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56) [cucumber-junit-2.4.0.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127) [cucumber-junit-2.4.0.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114) [gradle-testing-jvm-4.5.1.jar:4.5.1]
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57) [gradle-testing-jvm-4.5.1.jar:4.5.1]
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66) [gradle-testing-jvm-4.5.1.jar:4.5.1]
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51) [gradle-testing-base-4.5.1.jar:4.5.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-4.5.1.jar:4.5.1]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-4.5.1.jar:4.5.1]
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32) [gradle-messaging-4.5.1.jar:4.5.1]
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93) [gradle-messaging-4.5.1.jar:4.5.1]
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source) [na:na]
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108) [gradle-testing-base-4.5.1.jar:4.5.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-4.5.1.jar:4.5.1]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-4.5.1.jar:4.5.1]
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146) [gradle-messaging-4.5.1.jar:4.5.1]
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128) [gradle-messaging-4.5.1.jar:4.5.1]
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404) [gradle-messaging-4.5.1.jar:4.5.1]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) [gradle-base-services-4.5.1.jar:4.5.1]
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) [gradle-base-services-4.5.1.jar:4.5.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) [gradle-base-services-4.5.1.jar:4.5.1]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
      net.thucydides.core.pages.WrongPageError: The page object class com.cognitoiq.test.helios.mobile.page.startup.SubscriberKeyEntryPage looks dodgy:
Failed to instantiate page (java.lang.ClassCastException: net.thucydides.core.webdriver.WebDriverFacade cannot be cast to org.openqa.selenium.remote.RemoteWebDriver)
	at net.thucydides.core.pages.Pages.thisPageObjectLooksDodgy(Pages.java:295)
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:223)
	at net.thucydides.core.pages.Pages.getPage(Pages.java:90)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:166)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:156)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:139)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:86)
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:76)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:42)
	at net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:135)
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:101)
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:68)
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:51)
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:41)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.HookDefinitionMatch.runStep(HookDefinitionMatch.java:17)
	at cucumber.runner.UnskipableStep.executeStep(UnskipableStep.java:22)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wakaleo** [comment]
Have a look in the getCurrentPageOfType() method in the Pages class. This method was modified to add support for non-public constructors, but may have broken some of the community-provided Appium code.

**Comment by dbirch-cognitoiq** [comment]
Seems ok in 2.0.32, will look into that in a sec and let you know - just trying to narrow down the exact version it broke in :)

**Comment by wakaleo** [comment]
Probably #2c0aeee823662cc504aceea9de921d2c741c82e8

**Comment by miles-mason** [comment]
This is to do with the work around different ways of specifying the Appium platform. I'll put in a PR to catch the ClassCastException.

**Comment by dbirch-cognitoiq** [comment]
Many thanks, need to get setup to build serenity locally and I will give this a test :)

**Comment by dbirch-cognitoiq** [comment]
Confirmed working with 2.0.40-SNAPSHOT serenity built from current master, just going to finish a test run and make sure there's no more issues.

**Comment by dbirch-cognitoiq** [comment]
Actually, quick question any idea when 2.0.40 is going to be released? I'd rather not have to publish this locally to get the latest changes.

**Comment by wakaleo** [comment]
Probably over the weekend

**Comment by dbirch-cognitoiq** [comment]
Thanks, I will hold off for 2.0.40 then.
