### ISSUE TITLE
Tests passed but console displays errors.

### ISSUE THREAD

**Issue by sebastianciocan** [serenity-bdd/serenity-core#1559]
Hi,
I have a project with Serenity and Appium for Android.
My tests pass but there are errors displayed in the console.
Example:
[main] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: Appium.features
[main] ERROR net.thucydides.core.model.TestOutcome - Tag provider net.thucydides.core.requirements.PackageRequirementsTagProvider@765df79d failure
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:934)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at net.thucydides.core.requirements.FileSystemRequirementsStore.read(FileSystemRequirementsStore.java:42)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.reloadedRequirements(PackageRequirementsTagProvider.java:106)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.fetchRequirements(PackageRequirementsTagProvider.java:100)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirements(PackageRequirementsTagProvider.java:91)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirementFor(PackageRequirementsTagProvider.java:246)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getTagsFor(PackageRequirementsTagProvider.java:266)
	at net.thucydides.core.model.TestOutcome.getTagsUsingTagProviders(TestOutcome.java:1751)
	at net.thucydides.core.model.TestOutcome.getTags(TestOutcome.java:1736)
	at net.thucydides.core.model.TestOutcome.addTags(TestOutcome.java:1781)
	at net.thucydides.core.steps.BaseStepListener.testFinished(BaseStepListener.java:466)
	at net.thucydides.core.steps.StepEventBus.testFinished(StepEventBus.java:302)
	at net.thucydides.junit.listeners.JUnitStepListener.testFinished(JUnitStepListener.java:98)
	at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
	at org.junit.internal.runners.model.EachTestNotifier.fireTestFinished(EachTestNotifier.java:38)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:331)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:461)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:436)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:44)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:241)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:63)
	at com.google.gson.Gson.fromJson(Gson.java:922)
	... 35 more
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 

What causes this and how can I fix it?

**Comment by wakaleo** [comment]
Have you tried doing a clean build?
