### ISSUE TITLE
FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE: Jenkins + Browserstack

### ISSUE THREAD

**Issue by egurinovich** [serenity-bdd/serenity-core#158]
Hi,
I tried to run my tests on Jenkins using BrowserStack. 
Occasionally I recieve next error:
2175 [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.remote.RemoteWebDriver: Could not instantiate class org.openqa.selenium.remote.RemoteWebDriver

It happens NOT ALWAYS, but every second or third time.
When error occurred all tests will be failed with this error.

When I run tests on local machine with RemoteDriver it works fine every time.

This command I'm using to run tests on Jenkins:
clean verify -Dsurefire.useFile=false -Dwebdriver.remote.driver=firefox -Dwebdriver.driver=remote -Dserenity.driver.capabilities=resolution:1280x1024;browserstack.debug:true;os:WINDOWS;os_version:7;browser:firefox;browser_version:41;build:FirefoxSmoke;project:tribalWarsProject -Dmaven.test.failure.ignore=true -Dtags="level:smoke"

Logs from Jenkins:
http://screencast.com/t/gnIg1cEh

Serenity.properties file: http://screencast.com/t/OvWxgOtfYIF5

Also, I can attach pom file if it requred
Help, please.

**Comment by AlinaRot** [comment]
Hi, i am also experiencing the same problem. 
When starting the build on Jenkins either is failing and then the next try is connecting to Browserstack running the tests; either is working and then the  next run is failing. This is happening for almost 2 weeks now.
Plus on different Jenkins build depending on a maven configuration  the build is running or not.

clean
integration-test
serenity:aggregate
-Dsurefire.useFile=false
-Dwebdriver.driver=firefox
-Dmaven.test.failure.ignore=true
-Dtags="level3:weekly"

For example, i have 3 identical builds, only the -Dtags="level3:weekly" is different for each. For "level:deployment" the build is not run returning in the same error as above.

2175 [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.remote.RemoteWebDriver: Could not instantiate class org.openqa.selenium.remote.RemoteWebDriver

Please help.

**Comment by onio** [comment]
The same :(

270236 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: clicksMarketSelectionButton
11069755 [main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class net.thucydides.core.webdriver.ProvidedDriver: Could not instantiate class net.thucydides.core.webdriver.ProvidedDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class net.thucydides.core.webdriver.ProvidedDriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:190)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:84)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:78)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:50)
	at net.thucydides.core.webdriver.WebDriverFacade.findElement(WebDriverFacade.java:166)
	at net.thucydides.core.annotations.locators.SmartElementLocator.findElement(SmartElementLocator.java:36)

**Comment by YamStranger** [comment]
Hello @egurinovich!
Thanks for this issue. 

Can you check if this issue can be reproduced on last version of serenity? And it will be great, if you attach your pom file and may some example of code what you use (also for this purpose we can use serenity-demos)

Thanks!

**Comment by JetFree** [comment]
Hey, finally I got last version and I'm glad to say that it doesn't reproduced on version 1.1.17. Thanks!

**Comment by YamStranger** [comment]
@JetFree Its great!

Please share your experience with @egurinovich  - as opener of this issue. Only he can close this issue :)

Thanks a lot!

**Comment by JetFree** [comment]
Sorry, It is my second account))) Now close)

**Comment by ganeshabelavadi** [comment]
Faced same issue in version 1.1.25-rc.4

at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:221)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
	at net.thucydides.core.webdriver.WebdriverInstanceFactory.newFirefoxDriver(WebdriverInstanceFactory.java:59)
	at net.thucydides.core.webdriver.WebDriverFactory.firefoxDriver(WebDriverFactory.java:492)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:176)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:139)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:130)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:175)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:170)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:829)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:739)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:727)
	at com.ge.hc.webminPages.ConfigurationPage.steps.StaticPersistentRoutesSteps.logintoWebmin(StaticPersistentRoutesSteps.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:566)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:546)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:510)
	at org.jbehave.core.embedder.StoryRunner.runStepsWithLifecycle(StoryRunner.java:476)
	at org.jbehave.core.embedder.StoryRunner.runScenariosParametrisedByExamples(StoryRunner.java:465)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:334)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:239)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:182)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:233)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[pool-1-thread-1] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:201)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:139)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:130)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:175)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:170)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:829)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:739)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:727)
	at com.ge.hc.webminPages.ConfigurationPage.steps.StaticPersistentRoutesSteps.logintoWebmin(StaticPersistentRoutesSteps.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:566)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:546)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:510)
	at org.jbehave.core.embedder.StoryRunner.runStepsWithLifecycle(StoryRunner.java:476)
	at org.jbehave.core.embedder.StoryRunner.runScenariosParametrisedByExamples(StoryRunner.java:465)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:334)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:239)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:182)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:233)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wakaleo** [comment]
Have you checked the versions of Firefox you are using?

**Comment by s8sachin** [comment]
same issue here. it was not working on firefox 51, and i downgraded to 39 and 35, yet same issue. however i am able to run on my pc, but when i try on jenkins, i am getting this error. (same as above)

**Comment by wakaleo** [comment]
selenium 2.53.1 supports firefox 45 and 46, nothing higher.

**Comment by kuldeep-surendra** [comment]
same issue @s8sachin, 

> ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.firefox.FirefoxDriver: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

,
on jenkins server . but working fine in my local

**Comment by wakaleo** [comment]
This is a Selenium/Firefox compatibility issue - make sure the version of Firefox running on Jenkins is compatible with Selenium 2.53.1
