### ISSUE TITLE
Error "Too many open files" with property serenity.take.screenshots=AFTER_EACH_STEP

### ISSUE THREAD

**Issue by dip56** [serenity-bdd/serenity-core#160]
Error reproduce only in serenity version 1.1.17. If we use serenity.take.screenshots=FOR_FAILURES everything is good.

linux settings:
```
user@linux:~# sysctl fs.file-max
fs.file-max = 100000
user@linux:~# ulimit -n
100000
```

error stack traces:
```
INFO ReportService - net.thucydides.core.reports.xml.XMLTestOutcomeReporter@35640898: Generating report for test outcome: 
java.lang.RuntimeException: Report generation failure
	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:133)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:120)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:98)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReportsFor(SerenityRunner.java:384)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReports(SerenityRunner.java:268)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:246)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: target/site/serenity/SERENITY-JUNIT-557eb6a0d0c1f93865f78cca2d548222e3880625e4d5ce72ce1e73cb897f3d12.xml (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:46)
	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:131)
	... 21 more
```

```
WARN ResizableImage - Could not resize screenshot, so leaving original version: target/site/serenity/11049164337ac0fcd2dae74b0a66f1d8.png
javax.imageio.IIOException: Can't create an ImageInputStream!
	at javax.imageio.ImageIO.read(ImageIO.java:1306)
	at net.thucydides.core.images.ResizableImage.rescaleCanvas(ResizableImage.java:105)
	at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.resizedImage(ScreenshotFormatter.java:64)
	at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight(ScreenshotFormatter.java:47)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:208)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:195)
	at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
	at ch.lambdaj.Lambda.convert(Lambda.java:986)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.expandScreenshots(HtmlAcceptanceTestReporter.java:192)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:178)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:88)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:178)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:23)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by wakaleo** [comment]
Could you provide a sample project that reproduces this issue?

On 30 October 2015 at 09:01, dip <notifications@github.com> wrote:

> Error reproduce only in serenity version 1.1.17. If we use
> serenity.take.screenshots=FOR_FAILURES everything is good.
>
> linux settings:
>
> user@linux:~# sysctl fs.file-max
> fs.file-max = 100000
> user@linux:~# ulimit -n
> 100000
>
> error stack traces:
>
> INFO ReportService - net.thucydides.core.reports.xml.XMLTestOutcomeReporter@35640898: Generating report for test outcome:
> java.lang.RuntimeException: Report generation failure
>     at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:133)
>     at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:120)
>     at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:98)
>     at net.serenitybdd.junit.runners.SerenityRunner.generateReportsFor(SerenityRunner.java:384)
>     at net.serenitybdd.junit.runners.SerenityRunner.generateReports(SerenityRunner.java:268)
>     at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:246)
>     at org.junit.runners.Suite.runChild(Suite.java:128)
>     at org.junit.runners.Suite.runChild(Suite.java:27)
>     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>     at org.junit.runners.Suite.runChild(Suite.java:128)
>     at org.junit.runners.Suite.runChild(Suite.java:27)
>     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: java.io.FileNotFoundException: target/site/serenity/SERENITY-JUNIT-557eb6a0d0c1f93865f78cca2d548222e3880625e4d5ce72ce1e73cb897f3d12.xml (Too many open files)
>     at java.io.FileOutputStream.open0(Native Method)
>     at java.io.FileOutputStream.open(FileOutputStream.java:270)
>     at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
>     at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
>     at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:46)
>     at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:131)
>     ... 21 more
>
> WARN ResizableImage - Could not resize screenshot, so leaving original version: target/site/serenity/11049164337ac0fcd2dae74b0a66f1d8.png
> javax.imageio.IIOException: Can't create an ImageInputStream!
>     at javax.imageio.ImageIO.read(ImageIO.java:1306)
>     at net.thucydides.core.images.ResizableImage.rescaleCanvas(ResizableImage.java:105)
>     at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.resizedImage(ScreenshotFormatter.java:64)
>     at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight(ScreenshotFormatter.java:47)
>     at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:208)
>     at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:195)
>     at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
>     at ch.lambdaj.Lambda.convert(Lambda.java:986)
>     at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.expandScreenshots(HtmlAcceptanceTestReporter.java:192)
>     at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:178)
>     at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:88)
>     at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:178)
>     at net.thucydides.core.reports.ReportService.access$100(ReportService.java:23)
>     at net.thucydides.core.reports.ReportService$1.run(ReportService.java:114)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/160>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by wakaleo** [comment]
Could you also try with 1.1.18-rc.1 (on Bintray)?

**Comment by dip56** [comment]
Error still reproduce in version 1.1.18-rc.1. I think the problems were begun after start DDT tests with big test data. We use DDT tests with SerenityParameterizedRunner and @Concurrent annotation.

Maybe "net.serenitybdd.core.photography.DarkroomProcessingLine" leave streams open while resize images?

after DDT test runs I see too many warnings like this:
```
WARN ResizableImage - Could not find the dimensions of the screenshot for target/site/serenity/f7f5cd7979305e4c2b807e6e59ac2881.png
```

**Comment by YamStranger** [comment]
Hi @dip56!

We can not reproduce this problem, but you are right - some streams was not closed correctly during resizing (image processing lib feature), so it should be fixed [here](https://github.com/serenity-bdd/serenity-core/blob/e20b95e3c009f3dd5dda8fa16ceb0a15cf24bbc9/serenity-core/src/main/java/net/thucydides/core/images/ResizableImage.java#L78). 

Please check, if your issue reproduced in [1.1.22-rc.10](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.22-rc.10) - it should be fixed now. 

if issue will be not reproduced, please close this issue, otherwise please provide some example - it will help us to provide fix.

Thanks a lot!!!

**Comment by dip56** [comment]
Hello @YamStranger,

I can't reproduce this bug with version 1.1.22-rc.10. I think everything is fine. Thank you for fix =)

**Comment by YamStranger** [comment]
@dip56 you are welcome )
