### ISSUE TITLE
Work with Custom Driver is broken since version 1.1.17

### ISSUE THREAD

**Issue by dip56** [serenity-bdd/serenity-core#162]
Hello John,

something wrong with Custom Driver since version 1.1.17 (also reproduced in 1.1.18-rc.1).

sample project to reproduce this bug:
https://github.com/dip56/serenity-custom-driver

run only one test with custom driver:
```
mvn -Dit.test=net.thucydides.showcase.junit.features.cart.AddItemsToCartTest -Dwebdriver.driver=provided -Dwebdriver.provided.type=remote -Dwebdriver.provided.remote=qa.ChromeRemoteDriver clean integration-test serenity:aggregate
```

stack trace for custom driver:
```
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1329)
	at qa.ChromeRemoteDriver.newDriver(ChromeRemoteDriver.java:27)
	at net.thucydides.core.webdriver.WebDriverFactory.providedDriver(WebDriverFactory.java:247)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:189)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:139)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:130)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.getDriverClass(WebDriverFacade.java:95)
	at net.thucydides.core.webdriver.WebDriverFacade.getDriverName(WebDriverFacade.java:379)
	at net.thucydides.core.webdriver.WebdriverInstances.getCurrentDriverName(WebdriverInstances.java:43)
	at net.thucydides.core.webdriver.ThucydidesWebdriverManager.getWebdriver(ThucydidesWebdriverManager.java:101)
	at net.thucydides.core.webdriver.ThucydidesWebdriverManager.getWebdriver(ThucydidesWebdriverManager.java:139)
	at net.serenitybdd.junit.runners.SerenityRunner.getDriver(SerenityRunner.java:596)
	at net.serenitybdd.junit.runners.SerenityRunner.resetBroswerFromTimeToTime(SerenityRunner.java:527)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:424)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:52)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

log:
```
[main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class org.openqa.selenium.remote.RemoteWebDriver: Could not instantiate class org.openqa.selenium.remote.RemoteWebDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.remote.RemoteWebDriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:201)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:139)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:130)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:175)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:170)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:830)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:740)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:728)
	at net.thucydides.showcase.junit.steps.serenity.BuyerSteps.opens_home_page(BuyerSteps.java:24)
	at net.thucydides.showcase.junit.steps.serenity.BuyerSteps$$EnhancerByCGLIB$$1bcd0e4b.CGLIB$opens_home_page$5(<generated>)
	at net.thucydides.showcase.junit.steps.serenity.BuyerSteps$$EnhancerByCGLIB$$1bcd0e4b$$FastClassByCGLIB$$a40737ff.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:339)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:324)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:299)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:129)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:56)
	at net.thucydides.showcase.junit.steps.serenity.BuyerSteps$$EnhancerByCGLIB$$1bcd0e4b.opens_home_page(<generated>)
	at net.thucydides.showcase.junit.features.cart.AddItemsToCartTest.add_item_to_cart(AddItemsToCartTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:428)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:52)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:620)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at net.thucydides.core.webdriver.WebDriverFactory.buildRemoteDriver(WebDriverFactory.java:286)
	at net.thucydides.core.webdriver.WebDriverFactory.newRemoteDriver(WebDriverFactory.java:278)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:172)
	... 46 more
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:525)
	... 51 more
```

**Comment by dip56** [comment]
not reproduced on version 1.1.22-rc.4
