### ISSUE TITLE
Anonymous Interaction throws net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null

### ISSUE THREAD

**Issue by dmalecki001** [serenity-bdd/serenity-core#1620]
I have come across a certain issue. For a static Performable that has an anonymous Interaction implementation, serenity throws net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null. However, should the same method have arguments that are passed into the Interaction then the code works. The following is some sample code with the issue and the whole exception stacktrace is at the bottom. Serenity version used -> 2.0.41.
```sh
@RunWith(SerenityRunner.class)
public class Main {
    public static Performable passingMethod(String value) {
        return new Interaction() {
            @Override
            public <T extends Actor> void performAs(T t) {
                System.out.println(value);
            }
        };
    }
    public static Performable failingMethod() {
        return new Interaction() {
            @Override
            public <T extends Actor> void performAs(T t) {
                System.out.println("failingMethod");
            }
        };
    }
    @Test
    public void run() {
        Actor actor = new Actor("Damian");
        actor.attemptsTo(Main.passingMethod("passingMethod"));
        actor.attemptsTo(Main.failingMethod());
    }
}
```
Exception
```sh
net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null

	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:345)
	at net.sf.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:305)
	at net.thucydides.core.steps.StepFactory.createProxyStepLibrary(StepFactory.java:207)
	at net.thucydides.core.steps.StepFactory.instantiateUniqueStepLibraryFor(StepFactory.java:179)
	at net.thucydides.core.steps.StepFactory.getUniqueStepLibraryFor(StepFactory.java:115)
	at net.serenitybdd.core.steps.Instrumented$InstrumentedBuilder.newInstance(Instrumented.java:30)
	at net.serenitybdd.screenplay.InstrumentedTask.instrumentedCopyOf(InstrumentedTask.java:61)
	at net.serenitybdd.screenplay.InstrumentedTask.of(InstrumentedTask.java:24)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:161)
	at com.test.sample.runners.Main.run(Main.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:461)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:436)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:44)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:241)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:459)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
	... 45 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	... 50 more
```

**Comment by wakaleo** [comment]
That looks like a dependency conflict - check your project dependencies, particularly related to cglib.

**Comment by dmalecki001** [comment]
Even if then this is not directly caused by us as we never called that library directly.
I created a sample project with only Serenity dependencies in pom and the result was the same.
Code:
public class TestRunner {

    public static Performable runner(){
        return new Interaction() {
            @Override
            public <T extends Actor> void performAs(T t) {
                System.out.println("Test");
            }
        };
    }

    @Test
    public void run(){
        Actor actor = new Actor("Damian");
        actor.attemptsTo(TestRunner.runner());
    }
}

Pom:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.test</groupId>
    <artifactId>test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.version>3.8.0</maven.compiler.version>
        <java.version>1.8</java.version>
        <serenity.version>2.0.41</serenity.version>
        <serenity.cucumber.version>1.9.31</serenity.cucumber.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay-webdriver</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay-rest</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

Exception:
net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null

	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:345)
	at net.sf.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:305)
	at net.thucydides.core.steps.StepFactory.createProxyStepLibrary(StepFactory.java:207)
	at net.thucydides.core.steps.StepFactory.instantiateUniqueStepLibraryFor(StepFactory.java:179)
	at net.thucydides.core.steps.StepFactory.getUniqueStepLibraryFor(StepFactory.java:115)
	at net.serenitybdd.core.steps.Instrumented$InstrumentedBuilder.newInstance(Instrumented.java:30)
	at net.serenitybdd.screenplay.InstrumentedTask.instrumentedCopyOf(InstrumentedTask.java:61)
	at net.serenitybdd.screenplay.InstrumentedTask.of(InstrumentedTask.java:24)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:161)
	at com.test.TestRunner.run(TestRunner.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:459)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
	... 41 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	... 46 more

**Comment by wakaleo** [comment]
Can you provide a sample project with this test?

**Comment by dmalecki001** [comment]
Sure,
here it is: https://github.com/dmalecki001/Serenity-Issue1620

**Comment by wakaleo** [comment]
What version of Java and Maven? I can't reproduce the issue with your project.

**Comment by dmalecki001** [comment]
```sh
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
```sh
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\Apache\apache-maven-3.6.0\bin\..
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: C:\Java\jdk1.8.0_181\jre
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by wakaleo** [comment]
It seems to be related to Java 8 (it doesn't happen with Java 11). I will investigate further.

**Comment by wakaleo** [comment]
Anonymous classes cannot be instrumented by CGLib. The only workaround (to avoid the error message) is to not try to instrument the anonymous classes, which means they will not take part in reporting etc. Is this your intent?

**Comment by dmalecki001** [comment]
My original intent was rather to simply have an anonymous implementation inside the static performable instead of a whole separate class impleneting Interaction. As far as I understand:
```sh
public static performable doSomething(){
return new Interaction {
  public <T extends Actor> void performAs(T actor){
      System.out.println("Test");  
    }
  }
}
```
is the same as:
```sh
public static performable doSomething(){
return Tasks.instrumented(Sample.class);
}

class Sample implements Interaction {
  @Override
  public <T extends Actor> void performAs(T actor){
      System.out.println("Test");  
    }
}
```

**Comment by wakaleo** [comment]
It isn't the same for CGLib, since CGLib cannot instrument anonymous classes. I can add a fix so it doesn't throw an exception and it executes the code, but your milage may vary as the task will not appear in the reports or be instrumented (i.e. page objects or step libraries won't be initialised)

**Comment by dmalecki001** [comment]
Ok, but should I have a task that is not related to serenity code in any way like update on the database, testdata generation etc. then I presume it would work just fine. If so, then the fix would be greatly appreciated as I, and probably many others, deal with tasks like that, which often are silent.
Thus, such anonymous Interaction would from now on be executed however will be treated as though it was silent, is that correct?
