### ISSUE TITLE
 java.lang.NoClassDefFoundError: Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver

### ISSUE THREAD

**Issue by Yiao** [serenity-bdd/serenity-core#1641]
I use serenity-bdd with cucumber4 to generate the cucumber report and I can't run it ... maybe is a problem of version, I didn't found any solution with google ...

I add my errors messages :
```
java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)

java.lang.NoClassDefFoundError: Could not initialize class net.thucydides.core.webdriver.SupportedWebDriver

	at net.thucydides.core.configuration.WebDriverConfiguration.lookupSupportedDriverTypeFor(WebDriverConfiguration.java:45)
	at net.thucydides.core.configuration.WebDriverConfiguration.getDriverType(WebDriverConfiguration.java:33)
```

And my maven file :

```
	<properties>
		<cucumber.version>4.2.0</cucumber.version>
                <serenity.version>2.0.41</serenity.version>
                <serenity.cucumber.version>1.0.6</serenity.cucumber.version>
	</properties>

       <dependencies>
                <dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
                </dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>
                 <dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-screenplay-webdriver</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber4</artifactId>
			<version>${serenity.cucumber.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

        <build>
		<plugins>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<configuration>
					<tags>${tags}</tags>
				</configuration>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```

**Comment by Yiao** [comment]
Maybe I must add maven-failsafe-plugin ?

**Comment by wakaleo** [comment]
Are you starting with the serenity-cucumber4-starter project?

**Comment by Yiao** [comment]
I'm so happy you repose me ;) Thank you . I try with my pc in home with  serenity-cucumber4-starter it works well, but when I try to run it in the enterprise  I got :

```
org.openqa.selenium.NoSuchElementException: 
no such element: Unable to locate element: {"method":"css selector","selector":".js-search-input"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds

```

In our enterprise we have a proxy, maybe our proxy blocked something?

**Comment by Yiao** [comment]
And when I run cucumber test in our project 
I got 

```
cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)
cucumber.runner.TestStep.executeStep(TestStep.java:63)
cucumber.runner.TestStep.run(TestStep.java:49)
cucumber.runner.TestCase.run(TestCase.java:40)
cucumber.runner.Runner.runPickle(Runner.java:40)
```

**Comment by wakaleo** [comment]
The WebDriver exception looks like a genuine test failure, so yes, the proxy could be blocking access. In which case, the project is working correctly. Try to add a test that accesses one of your internal sites.

**Comment by Yiao** [comment]
But in our project, we don't have any test to a site, we have just test cucumber with mocks. I don't know why I need the WebDriver, I run our test with cucumber 4 before, it works. And I just follow the serenity-cucumber4-starter to add dependencies and replace @Runwith(Cucumber.class) by using @Runwith(CucumberWithSerenity) and I just can't run it anymore.

```
 @Given("^le reporting process XXX est :")
    public void a_reporting_process_XXX_with_code_exists(DataTable dataTable) {
        reportingProcessXXX = dataTable.asMaps(String.class, String.class);
    }

    @And("^template est (Template_XXXX_XXXXX)")
    public void a_template_for_reporting_process_XXX(String templateName) {
        templateNameXXX= templateName;
    }

```

**Comment by wakaleo** [comment]
Then there is most likely a dependency conflict. Do a Maven dependency analysis to figure out what the conflict is. In particular, make sure your cucumber dependencies are aligned.

**Comment by Yiao** [comment]
You are right, I got conflict.

```
[INFO] \- net.serenity-bdd:serenity-core:jar:2.0.41:test
[INFO]    +- net.serenity-bdd:serenity-model:jar:2.0.41:test
[INFO]    |  \- (commons-collections:commons-collections:jar:3.2.2:test - omitted for duplicate)
[INFO]    +- io.appium:java-client:jar:6.1.0:test
[INFO]    |  \- commons-validator:commons-validator:jar:1.6:test
[INFO]    |     +- commons-beanutils:commons-beanutils:jar:1.9.2:test
[INFO]    |     |  \- (commons-collections:commons-collections:jar:3.2.1:test - omitted for conflict with 3.2.2)
[INFO]    |     \- (commons-collections:commons-collections:jar:3.2.2:test - omitted for duplicate)
[INFO]    \- commons-collections:commons-collections:jar:3.2.2:test

```

**Comment by Yiao** [comment]
I add my rapport serenity : 

`org/openqa/selenium/internal/Killable`
```
java.lang.NoClassDefFoundError
cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)
cucumber.runner.TestStep.executeStep(TestStep.java:63)
cucumber.runner.TestStep.run(TestStep.java:49)
cucumber.runner.TestCase.run(TestCase.java:40)
cucumber.runner.Runner.runPickle(Runner.java:40)
Caused by: java.lang.ClassNotFoundException
org.openqa.selenium.internal.Killable
cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java :16)
cucumber.runner.TestStep.executeStep(TestStep.java :63)
cucumber.runner.TestStep.run(TestStep.java :49)
cucumber.runner.TestCase.run(TestCase.java :40)
cucumber.runner.Runner.runPickle(Runner.java :40)
```

**Comment by Yiao** [comment]
Hello john, you can close this, it's Ok, is our proxy blocked somethings ...

**Comment by hangbti** [comment]
> Hello john, you can close this, it's Ok, is our proxy blocked somethings ...

Hi @Yiao Yiao 
Please help me to set proxy for this issue, I got the same error. Thanks in advance

**Comment by Yiao** [comment]
We just stop use the proxy of our clients, they don't care ...
