### ISSUE TITLE
Illegal char <:> at index 2:.....InvalidPath Illegal char <:> at index...

### ISSUE THREAD

**Issue by shreyasarjun** [serenity-bdd/serenity-core#1644]
I am getting below error 
Illegal char <:> at index 2: /C:/MyApplication/testing/target/test-classes/features
  h.com.myapp.cucumber.runner.h » InvalidPath Illegal char <:> at index..

With Serenity core version: 2.0.42 only.

If I changed serenity core version to 2.0.25 then its working fine.

Issue with latest serenity version 2.0.42 .

Could you please look into this.

**Comment by wakaleo** [comment]
Do you have a stack dump? This is a Windows-specific issue so I can't reproduce it.

**Comment by scormaq** [comment]
@wakaleo I got this same issue when tried to update my project from serenity 2.0.40 to 2.0.42 and serenity-cucumber from 1.0.6 to 1.0.7 (Maven 3.6.0, Windows 10)
There no big stack trace in output except one mentioned in OP. I debugged a bit, next line causes this exception:
https://github.com/serenity-bdd/serenity-core/blob/f3d2cdf1ddfd8549d154b1302319a0375be92936/serenity-model/src/main/java/net/thucydides/core/requirements/model/RequirementsConfiguration.java#L34

Here is related issue on SO: https://stackoverflow.com/questions/43972777/exception-in-thread-main-java-nio-file-invalidpathexception-illegal-char

**Comment by wakaleo** [comment]
Can you propose a PR?

**Comment by scormaq** [comment]
@wakaleo here you go 🙂 
https://github.com/serenity-bdd/serenity-core/pull/1646

**Comment by drkstr101** [comment]
> 
> 
> Do you have a stack dump? This is a Windows-specific issue so I can't reproduce it.

Here is full stacktrace. It doesn't seem to like the `C:/` at the beginning of absolute paths in Windows.

        java.nio.file.InvalidPathException: Illegal char &lt;:&gt; at index 2: /C:/Users/aarmiller/Workspace/aarmiller/serenity-cucumber-starter/build/resources/test/features" type="java.nio.file.InvalidPathException">java.nio.file.InvalidPathException: Illegal char &lt;:&gt; at index 2: /C:/Users/aarmiller/Workspace/aarmiller/serenity-cucumber-starter/build/resources/test/features
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at net.thucydides.core.requirements.model.RequirementsConfiguration.&lt;init&gt;(RequirementsConfiguration.java:34)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.&lt;init&gt;(FileSystemRequirementsTagProvider.java:117)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.&lt;init&gt;(FileSystemRequirementsTagProvider.java:75)
        at net.serenitybdd.cucumber.service.CucumberTagProviderStrategy.getTagProviders(CucumberTagProviderStrategy.java:36)
        at net.thucydides.core.statistics.service.ClasspathTagProviderService.tagProvidersThatCanProcess(ClasspathTagProviderService.java:80)
        at net.thucydides.core.statistics.service.ClasspathTagProviderService.loadTagProvidersFromPath(ClasspathTagProviderService.java:56)
        at net.thucydides.core.statistics.service.ClasspathTagProviderService.tagProvidersFor(ClasspathTagProviderService.java:36)
        at net.thucydides.core.statistics.service.ClasspathTagProviderService.getTagProviders(ClasspathTagProviderService.java:28)
        at net.thucydides.core.model.TestOutcome.getTags(TestOutcome.java:1736)
        at net.thucydides.core.reports.junit.JUnitXMLConverter.getFlakyTestDescription(JUnitXMLConverter.java:82)
        at net.thucydides.core.reports.junit.JUnitXMLConverter.buildTestCaseElement(JUnitXMLConverter.java:72)
        at net.thucydides.core.reports.junit.JUnitXMLConverter.write(JUnitXMLConverter.java:39)
        at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.lambda$generateReportsFor$0(JUnitXMLOutcomeReporter.java:47)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:39)
        at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:194)
        at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:179)
        at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
        at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:902)
        at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:329)
        at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:130)
        at cucumber.runner.EventBus.send(EventBus.java:28)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:128)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

**Comment by drkstr101** [comment]
FYI This is bug is not present in `net.serenity-bdd:serenity-core:2.0.41` and `net.serenity-bdd:serenity-cucumber:1.9.31`. Bump either of those deps to latest version and the issue presents itself on Windows.

**Comment by wakaleo** [comment]
Fixed in 2.0.43

**Comment by ZaziroZ** [comment]
Same bug present again in v. 2.0.81

**Comment by wakaleo** [comment]
Probably not the same bug I think,l. Can you reproduce in the latest version?

**Comment by ZaziroZ** [comment]
The latest version is quarantined in my organization (because of the serenity-report-resources-2.2.1.jar that has some vulnerabilities)

Meanwhile, v. 2.0.81 produces the following:
`WARN  n.t.c.r.RequirementsTagProvider - Failed to load requirements: Illegal char <:> at index 9: classpath:features/status/temp.feature
java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:features/status/temp.feature
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.lambda$requirementWithMatchingPath$7(FileSystemRequirementsTagProvider.java:402)`

**Comment by wakaleo** [comment]
Could you point out these vulnerabilities so we can update the corresponding libraries? As an open source project, it is very hard to support older versions.

**Comment by ZaziroZ** [comment]
I'll ask around to get more details.

Meanwhile, I tried using v. 2.1.2 for serenity-core and v. 2.0.81 only for serenity-report-resources and serenity-maven-plugin via execution mechanism.

I does work fine! So the bug looks gone in newer versions.

**Comment by Krwasch** [comment]
I've updated to 2.2.0 and get following error since then (Win10):
For some reason 2 paths are sent now

`Failed to load requirements: Illegal char <:> at index 33: C:\Users\abc\def\Project-Folder\C:\Users\abc\def\Project-Folder\src\test\resources\features\feature
java.nio.file.InvalidPathException: Illegal char <:> at index 33: :\Users\abc\def\Project-Folder\C:\Users\abc\def\Project-Folder\src\test\resources\features\feature
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at net.thucydides.core.requirements.RootDirectory.toAbsolute(RootDirectory.java:118)
	at net.thucydides.core.requirements.RootDirectory.lambda$getRootDirectoryPaths$0(RootDirectory.java:110)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.thucydides.core.requirements.RootDirectory.getRootDirectoryPaths(RootDirectory.java:110)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.rootDirectories(FileSystemRequirementsTagProvider.java:153)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.<init>(FileSystemRequirementsTagProvider.java:146)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.readChildrenFrom(FileSystemRequirementsTagProvider.java:741)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.requirementFromDirectoryName(FileSystemRequirementsTagProvider.java:648)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.readRequirementFrom(FileSystemRequirementsTagProvider.java:560)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.capabilitiesAndStoriesIn(FileSystemRequirementsTagProvider.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getRequirements(FileSystemRequirementsTagProvider.java:179)
	at net.thucydides.core.requirements.RequirementsProvided.by(RequirementsProvided.java:15)
	at net.thucydides.core.requirements.MultiSourceRequirementsService.getRequirements(MultiSourceRequirementsService.java:40)
	at net.thucydides.core.requirements.BaseRequirementsService.getRequirementTypes(BaseRequirementsService.java:197)
	at net.thucydides.core.reports.html.FreemarkerContext.getBuildContext(FreemarkerContext.java:103)
	at net.thucydides.core.reports.html.TextSummaryReportTask.generateReports(TextSummaryReportTask.java:31)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:33)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`
