### ISSUE TITLE
@Steps with interface does not work

### ISSUE THREAD

**Issue by centu81** [serenity-bdd/serenity-core#1690]
I have a case when depending on the situation I would like to use different step libraries for the same actions. 

I have stpedef library that is used by diffrent projects. 
`
@Steps
public IWebApp webapp;
`

Each projects has implementation of that interface.
With autowired it works correctly. But using Steps I'm getting exception (I need to use steps as in the interface implementation I'm using other step libraries and with autowired fields are not instantiated)
net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for WebApp:null
        at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:92)
        at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
        at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:76)
        at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
        at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:42)
        at net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:135)
        at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:101)
        at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:68)
        at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:51)
        at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:41)
        at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:49)
        at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
        at cucumber.runner.TestStep.executeStep(TestStep.java:63)

**Comment by wakaleo** [comment]
The @Steps annotation needs a class to implement, so this cannot work. Using Screenplay Performables would make this approach easier.

**Comment by centu81** [comment]
Is there any workaround?

**Comment by wakaleo** [comment]
As I said, using Screenplay would be a good workaround.

**Comment by centu81** [comment]
is there equivalent to @Scope("cucumber-glue") in Serenity for spring integration. I would like to remove after each scenario.

**Comment by centu81** [comment]
The workaround I apply. Just needed to put the class I would like to use in properties.
'
    @PostConstruct
    private void initWebApp() throws ClassNotFoundException {
        object = (Interface) StepFactory.getFactory().getSharedStepLibraryFor(Class.forName(generalConfig.getClass()));
    }
'

**Comment by Ragul-Dhandapani** [comment]
@centu81 - I am trying to do the Spring Integration using CucumberWithSerenity and I'm also facing the same issue?, Do you have any sample gitHub project which i can refer how you had integrated the Spring using CucumberWithSerenity. Because I have gone through many blogs but nothing helped out much. 

Ex: https://stackoverflow.com/questions/63394861/spring-boot-serenity-cucumber-for-rest-api-integration-test

**Comment by pabloleal1** [comment]
Hi all, after my class using @Steps, I'm getting the error described as below: Im Using appium driver as Driver. 


net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for VerificationCode_SerenitySteps:net.thucydides.core.webdriver.WebDriverFacade cannot be cast to org.openqa.selenium.remote.RemoteWebDriver


Any help will be very welcome!

**Comment by wakaleo** [comment]
@pabloleal1 do you have a stack trace?

**Comment by pabloleal1** [comment]
sorry @wakaleo but I Can't get a stack trace from serenity report cause It's not possible for me add steps on the report unfortunally

**Comment by pabloleal1** [comment]
As I typed you before, once I try to instance a class using @Steps, the intellij log show me the next error. 

net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for VerificationCode_SerenitySteps:net.thucydides.core.webdriver.WebDriverFacade cannot be cast to org.openqa.selenium.remote.RemoteWebDriver
