### ISSUE TITLE
Can't use @Shared annotation to use a model class to execute a post transaction

### ISSUE THREAD

**Issue by LucasGrc** [serenity-bdd/serenity-core#1697]
I want to to use the `@Shared` annotation to set up a model class in a task and then use the model class in other task to execute a post transaction on a API end point but I get the error
`java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: net.serenitybdd.tutorials.model.facility.PaymentTransaction. Forgot to register a type adapter?`

Feature:
``` 
givenThat(john).wasAbleTo(CreatesTheModel.forTheClinic());

        when(john).attemptsTo(
                CallTheAuthToken.usingPost("/auth-token")
        );

        then(john).should(
                seeThat(TheApiResponse.code(), is(200))
        );
```
Model classes
```
public class CustomerTransactionInfo {

    private int amount;

    public CustomerTransactionInfo(int amount) {
        this.amount = amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public int getAmount() {
        return amount;
    }
}

public class Organization {

    private String externalId;
    private String type;

    public Organization(String externalId, String type) {
        this.externalId = externalId;
        this.type = type;
    }

    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getExternalId() {
        return externalId;
    }

    public String getType() {
        return type;
    }
}
public class PaymentTransaction {

    private CustomerTransactionInfo customerTransactionInfo;
    private Organization organization;

    public void setCustomerTransactionInfo(CustomerTransactionInfo customerTransactionInfo) {
        this.customerTransactionInfo = customerTransactionInfo;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    public Organization getOrganization() {
        return organization;
    }

    public CustomerTransactionInfo getCustomerTransactionInfo() {
        return customerTransactionInfo;
    }
}
```
Task that creates the model
```
public class CreatesTheModel implements Task {
    @Shared
    PaymentTransaction paymentTransaction;

    @Override
    public <T extends Actor> void performAs(T actor) {
        CustomerTransactionInfo customerTransactionInfo;
        Organization organization;

        customerTransactionInfo = new CustomerTransactionInfo(0);
        organization = new Organization("14840", "PaymentTransaction");

        paymentTransaction.setCustomerTransactionInfo(customerTransactionInfo);
        paymentTransaction.setOrganization(organization);
    }

    public static Performable forTheClinic() {
        return instrumented(CreatesTheModel.class);
    }
}
```
Task the executes the post
```
public class CallTheAuthToken implements Task {
    @Shared
    PaymentTransaction paymentTransaction;

    private String endPoint;

    public CallTheAuthToken(String endPoint) {
        this.endPoint = endPoint;
    }

    @Override
    @Step("{0} call the Api #endPoint endPoint")
    public <T extends Actor> void performAs(T actor) {
        actor.attemptsTo(
                Post.to(endPoint).with(request -> request
                        .header("Content-Type","application/json")
                        .body(paymentTransaction)
                )
        );
    }

    public static CallTheAuthToken usingPost(String endPoint) {
        return instrumented(CallTheAuthToken.class, endPoint);
    }
}
```

When I try to executes this code I get the error `java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: net.serenitybdd.tutorials.model.facility.PaymentTransaction. Forgot to register a type adapter?`

But when I remove the annotation `@Shared` and I set the model in the task that executes the post it works just fine:

```
public class CallTheAuthToken implements Task {
    PaymentTransaction paymentTransaction;

    private String endPoint;

    public CallTheAuthToken(String endPoint) {
        this.endPoint = endPoint;
    }

    @Override
    @Step("{0} call the Api #endPoint endPoint")
    public <T extends Actor> void performAs(T actor) {
        CustomerTransactionInfo customerTransactionInfo;
        Organization organization;

        customerTransactionInfo = new CustomerTransactionInfo(0);
        organization = new Organization("14840", "PaymentTransaction");

        paymentTransaction = new PaymentTransaction();
        paymentTransaction.setCustomerTransactionInfo(customerTransactionInfo);
        paymentTransaction.setOrganization(organization);

        actor.attemptsTo(
                Post.to(endPoint).with(request -> request
                        .header("Content-Type","application/json")
                        .body(paymentTransaction)
                )
        );
    }

    public static CallTheAuthToken usingPost(String endPoint) {
        return instrumented(CallTheAuthToken.class, endPoint);
    }
}
```

Please can you help me with this issue and tell me what I'm doing wrong, thanks in advance.

**Comment by wakaleo** [comment]
Can you post the full stack trace?

**Comment by LucasGrc** [comment]
Sorry for the delay in the answer, this is the full stack trace:

```
java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: net.serenitybdd.tutorials.model.facility.PaymentTransaction. Forgot to register a type adapter?

	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.Gson.toJson(Gson.java:703)
	at com.google.gson.Gson.toJson(Gson.java:682)
	at com.google.gson.Gson.toJson(Gson.java:637)
	at com.google.gson.Gson.toJson(Gson.java:617)
	at io.restassured.internal.mapping.GsonMapper.serialize(GsonMapper.groovy:45)
	at io.restassured.internal.mapping.ObjectMapping.serializeWithGson(ObjectMapping.groovy:175)
	at io.restassured.internal.mapping.ObjectMapping.serialize(ObjectMapping.groovy:136)
	at io.restassured.internal.RequestSpecificationImpl.body(RequestSpecificationImpl.groovy:832)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationBodyConfigurations.body(RequestSpecificationBodyConfigurations.java:29)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.body(RequestSpecificationDecorated.java:28)
	at net.serenitybdd.tutorials.tasks.auth_token.CallTheAuthToken.lambda$performAs$0(CallTheAuthToken.java:29)
	at net.serenitybdd.tutorials.tasks.auth_token.CallTheAuthToken.performAs(CallTheAuthToken.java:26)
	at net.serenitybdd.tutorials.features.authToken.AuthTokenStory.verify_the_token_provider(AuthTokenStory.java:38)

[main] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: net.serenitybdd.tutorials.features
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 
```

**Comment by wakaleo** [comment]
Using the @Shared annotation will cause CGLib instrument the PaymentTransaction class, which appears to confuse GSON's serialisation. A safer approach would be to have the actor remember/recall the PaymentTransaction object.

**Comment by LucasGrc** [comment]
Thanks a lot for your help and time, what I did was create the model class I need in a function and send it to the task that executes the post as a parameter.
