### ISSUE TITLE
serenity.maintain.session=true doesn't work in serenity.conf

### ISSUE THREAD

**Issue by DjerohN** [serenity-bdd/serenity-core#1744]
Hi! I have problem configuring serenity.maintain.session = "true" through serenity.conf file, it doesn't work for me. But it works when I set it through serenity.properties file.

In serenity.conf it looks like:
```
environments {
  all {
    serenity.maintain.session = "true"
  }
}

```
My versions:
```
<dependency>
	<groupId>net.serenity-bdd</groupId>
	<artifactId>serenity-core</artifactId>
	<version>2.0.60</version>
	<exclusions>
		<exclusion>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>io.cucumber</groupId>
	<artifactId>cucumber-java</artifactId>
	<version>4.2.0</version>
</dependency>
<dependency>
	<groupId>io.cucumber</groupId>
	<artifactId>cucumber-junit</artifactId>
	<version>4.2.0</version>
</dependency>
<dependency>
	<groupId>net.serenity-bdd</groupId>
	<artifactId>serenity-junit</artifactId>
	<version>2.0.60</version>
</dependency>
<dependency>
	<groupId>net.serenity-bdd</groupId>
	<artifactId>serenity-rest-assured</artifactId>
	<version>2.0.60</version>
</dependency>
<dependency>
	<groupId>net.serenity-bdd</groupId>
	<artifactId>serenity-cucumber4</artifactId>
	<version>1.0.17</version>
</dependency>
```

**Comment by wakaleo** [comment]
Can you share your full serenity.conf file?

**Comment by DjerohN** [comment]
Of course:
```
environments {
	default {
		base.host = "http://localhost"
		base.port = "8080"
	}
	all {
		serenity.data.dir = "testdata"
		feature.file.encoding = "UTF-8"
		serenity.report.encoding = "UTF-8"
		serenity.project.name = "Default Application"
		serenity.maintain.session = "true"
		report.timeout = "60"
	}
	local {
		base.host = "http://localhost"
		base.port = "8881"
		kafka.host = "localhost"
		kafka.port = "9092"
	}
	qa {
		base.host = "http://ci-host"
		base.port = ""
	}
}
```

**Comment by wakaleo** [comment]
Fixed in 2.0.61

**Comment by DjerohN** [comment]
Thank you!

**Comment by DjerohN** [comment]
@wakaleo, after updating serenity version to 2.0.62, I'm getting error trying to launch test with Junit.
Error:
```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, net.serenitybdd.core.environment.UnknownEnvironmentException: No environment configuration found for environment 'local'
  at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
  at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
  while locating net.thucydides.core.util.EnvironmentVariables

1 error

	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at net.serenitybdd.cucumber.CucumberWithSerenity.environmentSpecifiedTags(CucumberWithSerenity.java:131)
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:87)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: net.serenitybdd.core.environment.UnknownEnvironmentException: No environment configuration found for environment 'local'
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.ensureSpecifiedEnvironmentConfigurationExistsFor(EnvironmentSpecificConfiguration.java:157)
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.environmentStrategyDefinedIn(EnvironmentSpecificConfiguration.java:130)
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.<init>(EnvironmentSpecificConfiguration.java:63)
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.from(EnvironmentSpecificConfiguration.java:122)
	at net.thucydides.core.ThucydidesSystemProperty.optionalPropertyValueDefinedIn(ThucydidesSystemProperty.java:1539)
	at net.thucydides.core.ThucydidesSystemProperty.from(ThucydidesSystemProperty.java:1489)
	at net.thucydides.core.util.PropertiesFileLocalPreferences.defaultPropertiesFileName(PropertiesFileLocalPreferences.java:181)
	at net.thucydides.core.util.PropertiesFileLocalPreferences.preferencesFileWithAbsolutePath(PropertiesFileLocalPreferences.java:173)
	at net.thucydides.core.util.PropertiesFileLocalPreferences.loadPreferences(PropertiesFileLocalPreferences.java:55)
	at net.thucydides.core.util.SystemEnvironmentVariables.createEnvironmentVariables(SystemEnvironmentVariables.java:186)
	at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
	at net.thucydides.core.guice.ThucydidesModule$$FastClassByGuice$$a52485fb.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 18 more
```
Options:
```
-Denvironment=local "-Dcucumber.options= --tags @tag"
```
serenity.conf is the same.

**Comment by wakaleo** [comment]
What does your serenity.conf file look like?

**Comment by DjerohN** [comment]
Here it is:
```
environments {
	default {
		base.host = "http://localhost"
		base.port = "8080"
	}
	all {
		serenity.data.dir = "testdata"
		feature.file.encoding = "UTF-8"
		serenity.report.encoding = "UTF-8"
		serenity.project.name = "Default Application"
		serenity.maintain.session = "true"
		report.timeout = "60"
	}
	local {
		base.host = "http://localhost"
		base.port = "8881"
		kafka.host = "localhost"
		kafka.port = "9092"
	}
	ci {
		base.host = "http://ci-host"
		base.port = ""
	}
}
```

**Comment by wakaleo** [comment]
Thanks; should work in 2.0.63

**Comment by DjerohN** [comment]
@wakaleo, I'm sorry to tell, but it still doesn't work after updating to 2.0.64 serenity.

Error:
```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, net.serenitybdd.core.environment.UnknownEnvironmentException: No environment configuration found for environment 'local'
  at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
  at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
  while locating net.thucydides.core.util.EnvironmentVariables

1 error

	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at net.serenitybdd.cucumber.CucumberWithSerenity.environmentSpecifiedTags(CucumberWithSerenity.java:131)
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:87)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: net.serenitybdd.core.environment.UnknownEnvironmentException: No environment configuration found for environment 'local'
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.ensureSpecifiedEnvironmentConfigurationExistsFor(EnvironmentSpecificConfiguration.java:157)
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.environmentStrategyDefinedIn(EnvironmentSpecificConfiguration.java:130)
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.<init>(EnvironmentSpecificConfiguration.java:63)
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.from(EnvironmentSpecificConfiguration.java:122)
	at net.thucydides.core.ThucydidesSystemProperty.optionalPropertyValueDefinedIn(ThucydidesSystemProperty.java:1539)
	at net.thucydides.core.ThucydidesSystemProperty.from(ThucydidesSystemProperty.java:1489)
	at net.thucydides.core.util.PropertiesFileLocalPreferences.defaultPropertiesFileName(PropertiesFileLocalPreferences.java:181)
	at net.thucydides.core.util.PropertiesFileLocalPreferences.preferencesFileWithAbsolutePath(PropertiesFileLocalPreferences.java:173)
	at net.thucydides.core.util.PropertiesFileLocalPreferences.loadPreferences(PropertiesFileLocalPreferences.java:55)
	at net.thucydides.core.util.SystemEnvironmentVariables.createEnvironmentVariables(SystemEnvironmentVariables.java:186)
	at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
	at net.thucydides.core.guice.ThucydidesModule$$FastClassByGuice$$a52485fb.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 18 more
```
Junit command line:
```
-Denvironment=local "-Dcucumber.options= --tags @some-tag"
```
Serenity.conf file:
```
environments {
	default {
		base.host = "http://localhost"
		base.port = "8080"
	}
	all {
		serenity.data.dir = "testdata"
		feature.file.encoding = "UTF-8"
		serenity.report.encoding = "UTF-8"
		serenity.project.name = "Default Application"
		serenity.maintain.session = "true"
		report.timeout = "60"
	}
	local {
		base.host = "http://localhost"
		base.port = "8881"
		kafka.host = "localhost"
		kafka.port = "9092"
	}
	qa {
		base.host = "http://qa"
		base.port = ""
	}
}
```
Want to mention that I use JRE 12 for running Junit (Liberica JDK distr).

**Comment by wakaleo** [comment]
Did you update the serenity-cucumber version?

**Comment by DjerohN** [comment]
Upgrading serenity-cucumber4 to version 1.0.18 has no effect, still getting the error.

**Comment by DjerohN** [comment]
Works fine with serenity 2.0.66 and serenity-cucumber4 1.0.19. Thank you!
