### ISSUE TITLE
Test cases are not running with Chromium

### ISSUE THREAD

**Issue by franciscoguemes** [serenity-bdd/serenity-core#1755]
According with the question: https://github.com/serenity-bdd/serenity-core/issues/604 it is possible to run the test cases in Chromium.

I am using Ubuntu linux:
`$ uname -a
Linux francisco-XPS-13-9370 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

I have Chromium installed: Version 76.0.3809.87 (Official Build) snap (64-bit)

I have generated the Serenity project from a maven archetype with the following command: 
`mvn` archetype:generate -Dfilter=net.serenity-bdd:serenity-cucumber-archetype

I updated the pom.xml file to have the latest versions of serenity and serenity cucumber:
```
<serenity.version>2.0.64</serenity.version>
<serenity.cucumber.version>1.9.44</serenity.cucumber.version>
```
I placed the webdriver binaries inside src/test/resources/webdriver the following way:
```
          ├── linux
          │   ├── chromedriver-v75.0.3770.140-linux64
          │   └── geckodriver-v0.24.0-linux64
          ├── mac
          │   ├── chromedriver-v75.0.3770.140-mac64
          │   └── geckodriver-v0.24.0-macos
          └── README.txt
```
And each binary has execution permissions

My serenity.properties file has the following content:
```
# Define the default driver
#webdriver.driver=phantomjs
webdriver.driver=chrome
#webdriver.driver=firefox

# Appears at the top of the reports
serenity.project.name = Demo Project using Serenity and Cucumber

# Root package for any JUnit acceptance tests
#serenity.test.root=net.thucydides.showcase.junit.features

# Customise your riequirements hierarchy
#serenity.requirement.types=feature, story

# Run the tests without calling webdriver - useful to check your Cucumber wireing
#serenity.dry.run=true

# Customise browser size
#serenity.browser.height = 1200
#serenity.browser.width = 1200

#webdriver.gecko.driver=src/test/resources/webdriver/linux/geckodriver-v0.24.0-linux64
#webdriver.chrome.driver = src/test/resources/webdriver/linux/chromedriver-v75.0.3770.140-linux64

# https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html#_configuring_the_driver
# https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html
drivers.linux.webdriver.chrome.driver = src/test/resources/webdriver/linux/chromedriver-v75.0.3770.140-linux64
#drivers.linux.webdriver.gecko.driver = src/test/resources/webdriver/linux/geckodriver-v0.24.0-linux64

drivers.mac.webdriver.chrome.driver = src/test/resources/webdriver/mac/chromedriver-v75.0.3770.140-mac64
#drivers.mac.webdriver.gecko.driver = src/test/resources/webdriver/mac/geckodriver-v0.24.0-macos
```
Note that I have commented any mention to Firefox or gecko.

And still the error message that I am getting is the following:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running scs.DefinitionTestSuite
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
                                                                                     
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat      
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
 Learn Serenity BDD online at http://serenity-dojo.com                               
-------------------------------------------------------------------------------------

[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Lookup a definition
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: Looking up the definition of 'apple'
-------------------------------------------------------------------(lookup-a-definition;looking-up-the-definition-of--apple-)
Aug 01, 2019 3:43:44 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Aug 01, 2019 3:43:44 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: true, browserName: firefox, firefox_profile: org.openqa.selenium.firefox..., headless: false, loggingPrefs: org.openqa.selenium.logging..., marionette: true, moz:firefoxOptions: {}, platform: ANY, version: }
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED WITH ERROR: Looking up the definition of 'apple'
---------------------------------------------------------------------
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Is the home page
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases). See below for more details.
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: Looking up the definition of 'pear'
-------------------------------------------------------------------(lookup-a-definition;looking-up-the-definition-of--pear-)
Aug 01, 2019 3:43:45 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Aug 01, 2019 3:43:45 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: true, browserName: firefox, firefox_profile: org.openqa.selenium.firefox..., headless: false, loggingPrefs: org.openqa.selenium.logging..., marionette: true, moz:firefoxOptions: {}, platform: ANY, version: }
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED WITH ERROR: Looking up the definition of 'pear'
---------------------------------------------------------------------
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Is the home page
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases). See below for more details.

Failed scenarios:
src/test/resources/features/consult_dictionary/LookupADefinition.feature:6 # Looking up the definition of 'apple'
src/test/resources/features/consult_dictionary/LookupADefinition.feature:11 # Looking up the definition of 'pear'

2 Scenarios (2 failed)
6 Steps (2 failed, 4 skipped)
0m1.284s

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:172)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:902)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:803)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:791)
	at scs.steps.serenity.EndUserSteps.is_the_home_page(EndUserSteps.java:32)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c.CGLIB$is_the_home_page$3(<generated>)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c$$FastClassByCGLIB$$63ddb45b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c.is_the_home_page(<generated>)
	at scs.steps.DefinitionSteps.givenTheUserIsOnTheWikionaryHomePage(DefinitionSteps.java:17)
	at ✽.the user is on the Wikionary home page(src/test/resources/features/consult_dictionary/LookupADefinition.feature:7)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases). See below for more details.
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:158)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:172)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:902)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:803)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:791)
	at scs.steps.serenity.EndUserSteps.is_the_home_page(EndUserSteps.java:32)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c.CGLIB$is_the_home_page$3(<generated>)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c$$FastClassByCGLIB$$63ddb45b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c.is_the_home_page(<generated>)
	at scs.steps.DefinitionSteps.givenTheUserIsOnTheWikionaryHomePage(DefinitionSteps.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:31)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:25)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
	at com.google.common.base.Preconditions.checkState(Preconditions.java:842)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:134)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:44)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:167)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:190)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider.lambda$newMarionetteDriver$0(FirefoxDriverProvider.java:70)
	at net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver.withConfiguration(ProvideNewDriver.java:40)
	at net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider.newMarionetteDriver(FirefoxDriverProvider.java:66)
	at net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:52)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:169)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:150)
	... 58 more

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:172)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:902)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:803)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:791)
	at scs.steps.serenity.EndUserSteps.is_the_home_page(EndUserSteps.java:32)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c.CGLIB$is_the_home_page$3(<generated>)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c$$FastClassByCGLIB$$63ddb45b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c.is_the_home_page(<generated>)
	at scs.steps.DefinitionSteps.givenTheUserIsOnTheWikionaryHomePage(DefinitionSteps.java:17)
	at ✽.the user is on the Wikionary home page(src/test/resources/features/consult_dictionary/LookupADefinition.feature:12)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases). See below for more details.
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:158)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:172)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:902)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:803)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:791)
	at scs.steps.serenity.EndUserSteps.is_the_home_page(EndUserSteps.java:32)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c.CGLIB$is_the_home_page$3(<generated>)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c$$FastClassByCGLIB$$63ddb45b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:461)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:446)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:421)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:176)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:163)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:69)
	at scs.steps.serenity.EndUserSteps$$EnhancerByCGLIB$$6ac4376c.is_the_home_page(<generated>)
	at scs.steps.DefinitionSteps.givenTheUserIsOnTheWikionaryHomePage(DefinitionSteps.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:31)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:25)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
	at com.google.common.base.Preconditions.checkState(Preconditions.java:842)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:134)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:44)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:167)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:190)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider.lambda$newMarionetteDriver$0(FirefoxDriverProvider.java:70)
	at net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver.withConfiguration(ProvideNewDriver.java:40)
	at net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider.newMarionetteDriver(FirefoxDriverProvider.java:66)
	at net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:52)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:169)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:150)
	... 58 more

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.494 sec <<< FAILURE! - in scs.DefinitionTestSuite
Looking up the definition of 'apple'(Lookup a definition)  Time elapsed: 0.786 sec  <<< ERROR!
net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases). See below for more details.
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases

Looking up the definition of 'pear'(Lookup a definition)  Time elapsed: 0.23 sec  <<< ERROR!
net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases). See below for more details.
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases


Results :

Tests in error: 
  Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
  Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
```
Any idea why is it not working?
To me looks like it is ignoring the option _webdriver.driver=chrome_ and tries to run the webdriver for firefox...

Thanks in advance.

**Comment by wakaleo** [comment]
Better to start with the https://github.com/serenity-bdd/serenity-cucumber-starter/ project, which runs with chrome by default.

**Comment by wakaleo** [comment]
The projects generated via an archetype should work with the latest archetypes.

**Comment by franciscoguemes** [comment]
I have found the issue. In the pom.xml file there is the following property in the properties section:
`<webdriver.driver>firefox</webdriver.driver>`
which you need to delete/comment and then in the build section there is the definition of the plugin maven-failsafe-plugin on which you need to delete/comment the usage of the property:
```
<plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <includes>
                        <include>**/*.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
<!--                         <webdriver.driver>${webdriver.driver}</webdriver.driver> -->
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                        	<!-- https://maven.apache.org/surefire/maven-failsafe-plugin/examples/skipping-tests.html -->
                        	<skipITs>${skipTests}</skipITs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
Once you do these changes, then serenity takes into account the command line option and the the configuration in serenity.conf

**Comment by franciscoguemes** [comment]
I have found the issue. In the pom.xml file there is the following property in the properties section:
`<webdriver.driver>firefox</webdriver.driver>`
which you need to delete/comment and then in the build section there is the definition of the plugin maven-failsafe-plugin:
```
<plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <includes>
                        <include>**/*.java</include>
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
<!--                         <webdriver.driver>${webdriver.driver}</webdriver.driver> -->
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                        	<!-- https://maven.apache.org/surefire/maven-failsafe-plugin/examples/skipping-tests.html -->
                        	<skipITs>${skipTests}</skipITs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by wakaleo** [comment]
Thanks for the update Francisco.
