### ISSUE TITLE
Getting java.lang.NoClassDefFoundError after adding Serenity Zalenium dependency in gradle

### ISSUE THREAD

**Issue by cspriya** [serenity-bdd/serenity-core#1773]
```
My Dependencies
dependencies {
compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.9'
compile group: 'net.serenity-bdd', name: 'serenity-core', version:"$serenity_version"
compile group: 'net.serenity-bdd', name: 'serenity-junit', version:"$serenity_version"
compile group: 'net.serenity-bdd', name: 'serenity-cucumber', version:'1.9.14'
compile group: 'net.serenity-bdd', name: 'serenity-screenplay', version:"$serenity_version"
compile group: 'net.serenity-bdd', name: 'serenity-screenplay-rest', version:"$serenity_version"
compile group: 'net.serenity-bdd', name: 'serenity-screenplay-webdriver', version:"$serenity_version"
compile group: 'net.serenity-bdd', name: 'serenity-zalenium', version: '2.0.51'
testCompile group: 'io.cucumber', name: 'cucumber-java', version:'2.3.1'
testCompile group: 'io.cucumber', name: 'cucumber-junit', version:'2.3.1'
testCompile group: 'junit', name: 'junit', version:'4.12'
testCompile group: 'org.slf4j', name: 'slf4j-simple', version:'1.7.25'
}
LOGS
java.lang.NoClassDefFoundError: org/newsclub/net/unix/AFUNIXSocketAddress
at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3192)
at java.base/java.lang.Class.getMethods(Class.java:1905)
at cucumber.runtime.java.MethodScanner.scan(MethodScanner.java:38)
at cucumber.runtime.java.JavaBackend.loadGlue(JavaBackend.java:79)
at cucumber.runner.Runner.(Runner.java:45)
at cucumber.runtime.Runtime.(Runtime.java:65)
at cucumber.runtime.Runtime.(Runtime.java:45)
at cucumber.runtime.Runtime.(Runtime.java:41)
at net.serenitybdd.cucumber.CucumberWithSerenityRuntime.createSerenityEnabledRuntime(CucumberWithSerenityRuntime.java:38)
at net.serenitybdd.cucumber.CucumberWithSerenityRuntime.using(CucumberWithSerenityRuntime.java:28)
at net.serenitybdd.cucumber.CucumberWithSerenity.createRuntime(CucumberWithSerenity.java:54)
at cucumber.api.junit.Cucumber.(Cucumber.java:78)
at net.serenitybdd.cucumber.CucumberWithSerenity.(CucumberWithSerenity.java:38)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
```

**Comment by wakaleo** [comment]
This is a dependency conflict - you will need to resolve it using the usual Maven dependency analysis tools.

**Comment by cspriya** [comment]
@wakaleo  I am not sure how to check with the mentioned tool.

If you know please help with the zalenium compatibility with serenity_version = "1.9.36"

**Comment by wakaleo** [comment]
The recommended versions are shown here: https://github.com/serenity-bdd/serenity-core#what-is-the-latest-stable-version-i-should-use

**Comment by wakaleo** [comment]
Presuming resolved.

**Comment by qaswapnesh** [comment]
@wakaleo  you were right - I put serenity and restassured version same then problem was resolved
