### ISSUE TITLE
Junit will run two same story on eclipse.

### ISSUE THREAD

**Issue by ChrisD1990** [serenity-bdd/serenity-core#1794]
when i run my test story with Junit on ecilpse, but i don't know why will get two same story, 
one story path is  **src/test/resources/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story** , 
one story path is **target/test-classes/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story for compiled .** 
so when run story finished ,then the junit will automation to run story under  /target/target-classes.

below is run log

Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=true,ignoreFailureInView=true,verboseFailures=false,verboseFiltering=false,storyTimeouts=5000000,threads=1,failOnStoryTimeout=false]
16276 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - [36m

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
                                                                                     
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat      
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
 Learn Serenity BDD online at http://serenity-dojo.com                               
-------------------------------------------------------------------------------------
[0m

(BeforeStories)

Running story src/test/resources/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story
Using timeout for story DemoUISingleTest.story of 5000000 secs.
16752 [pool-1-thread-1] INFO net.serenitybdd.jbehave.embedders.monitors.ReportingEmbedderMonitor - 246826139story running with path src/test/resources/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story
16752 [pool-1-thread-1] ERROR net.serenitybdd.jbehave.embedders.monitors.ReportingEmbedderMonitor - can not find any story by path src/test/resources/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story
16795 [pool-1-thread-1] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Demo UI single change add remove

(src/test/resources/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story)
Meta:
@feature DemoUISingleChange

17242 [pool-1-thread-1] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: DemoUISingleChange demo suite
-------------------------------------------------------------------(src/test/resources/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story;DemoUISingleChange demo suite)
Scenario: DemoUISingleChange demo suite
Aug 30, 2019 2:04:15 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Aug 30, 2019 2:04:23 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Given mngPortal is running and end user can access with Browser for simpleChange
When login on the MngPortal for simpleChange
And open suite management page for simpleChange (FAILED)
(org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.xpath: //td[text()='2018.08.001'] (tried for 100 second(s) with 500 milliseconds interval))
And get action list for simpleChange (NOT PERFORMED)
252591 [pool-1-thread-1] ERROR net.thucydides.core.steps.ConsoleLoggingListener - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED WITH ERROR: DemoUISingleChange demo suite
---------------------------------------------------------------------
252987 [pool-1-thread-1] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Open suite management page
252988 [pool-1-thread-1] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Expected condition failed: waiting for element to be clickable: By.xpath: //td[text()='2018.08.001'] (tried for 100 second(s) with 500 milliseconds interval)

org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.xpath: //td[text()='2018.08.001'] (tried for 100 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.mf.tf.mngportal.ui.pages.MngportalManagementpPage.checkDemoInstalled(MngportalManagementpPage.java:748)
	at com.mf.tf.suites.demo.upgrade.simple.DemoUIChangeSteps.openSuiteManagementPage(DemoUIChangeSteps.java:44)
	at com.mf.tf.suites.demo.upgrade.simple.DemoUIChangeSteps$$EnhancerByCGLIB$$28160370.CGLIB$openSuiteManagementPage$29(<generated>)
	at com.mf.tf.suites.demo.upgrade.simple.DemoUIChangeSteps$$EnhancerByCGLIB$$28160370$$FastClassByCGLIB$$fade73a9.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:464)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:449)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:424)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:165)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:152)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:70)
	at com.mf.tf.suites.demo.upgrade.simple.DemoUIChangeSteps$$EnhancerByCGLIB$$28160370.openSuiteManagementPage(<generated>)
	at com.mf.tf.suites.demo.upgrade.DemoUISimpleChangeTest.openSuiteManagementPage(DemoUISimpleChangeTest.java:30)
	(reflection-invoke)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:782)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:350)
...

Running story target/test-classes/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story
Using timeout for story DemoUISingleTest.story of 5000000 secs.

(target/test-classes/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story)
Meta:
@feature DemoUISingleChange

Scenario: DemoUISingleChange demo suite
253155 [pool-1-thread-1] INFO net.serenitybdd.jbehave.embedders.monitors.ReportingEmbedderMonitor - 246826139story running with path target/test-classes/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story
253155 [pool-1-thread-1] ERROR net.serenitybdd.jbehave.embedders.monitors.ReportingEmbedderMonitor - can not find any story by path target/test-classes/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story
253180 [pool-1-thread-1] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Demo UI single change add remove
253184 [pool-1-thread-1] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: DemoUISingleChange demo suite
-------------------------------------------------------------------(target/test-classes/com/mf/tf/suites/demo/upgrade/ui/DemoUISingleTest.story;DemoUISingleChange demo suite)
Aug 30, 2019 2:08:09 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Aug 30, 2019 2:08:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

**Comment by wakaleo** [comment]
I'm not sure what problem you are describing. Maven copies resources from src to target before running the tests - that's how it works.
