### ISSUE TITLE
Serenity gradle aggregate task fails on Win10 

### ISSUE THREAD

**Issue by pmmdre** [serenity-bdd/serenity-core#1806]
*Environment:*
* Windows 10
* Java 8
* Gradle 5.6
* Serenity versions:
    * net.serenity-bdd:serenity-core:2.0.67
    * net.serenity-bdd:serenity-cucumber4:1.0.5
    * net.serenity-bdd:serenity-junit:2.0.67
    
*Problem:*
Gradle aggregate task runs into Exception on Windows machine. 
The requirements, capabilities, features etc. tabs of the Serenity report are not shown.
```
SOME REPORT PAGES COULD NOT BE GENERATED
 * Failed to generate report for net.thucydides.core.reports.html.HtmlAggregateStoryReporter$CopyResourcesTask@40beba50 - java.util.concurrent.ExecutionException: java.nio.file.NoSuchFileException: src\test\resources\assets
sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
```
* The src\test\resources\assets directory exists
* **We found out that the problem does not occur before Serenity version 2.0.49.**
* **The same code works fine on our CI Environment (Jenkins/Linux)**

Call stack:
``` 
Caused by: java.nio.file.NoSuchFileException: src\test\resources\assets
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.Files.list(Files.java:3451)
	at net.thucydides.core.reports.html.CopyProjectSpecificResourcesTask.generateReports(CopyProjectSpecificResourcesTask.java:28)
	at net.thucydides.core.reports.html.HtmlReporter.copyProjectSpecificResources(HtmlReporter.java:84)
	at net.thucydides.core.reports.html.HtmlReporter.copyResourcesToOutputDirectory(HtmlReporter.java:76)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter$CopyResourcesTask.generateReports(HtmlAggregateStoryReporter.java:318)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:32)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by wakaleo** [comment]
Is this reproducible?

**Comment by pmmdre** [comment]
Yes, we had this issue on 3 different Win10 machines since a few weeks. Happens on every execution of aggregate task.

**Comment by wakaleo** [comment]
You might have to put a breakpoint in the CopyProjectSpecificResourcesTask class to see why Java is not finding that path - maybe something to do with the working directory? I don’t recall anything changing in that feature for a while.

**Comment by pmmdre** [comment]
Thanks for the hint! This indeed seems to have to do with the gradle working directory. 
`CopyProjectSpecificResourcesTask.generateReports()` calls `Files.list(assetSourcePath())` with `assetSourcePath()` returning "src\test\resources\assets".

Inside of `Files.list(assetSourcePath())`, `Files.newDirectoryStream(dir)` uses the Gradle deamon directory `C:\Users\<user>\.gradle\daemon\5.6\.` as the working dir.

I will try to fix this via gradle somehow. I will post the solution as soon as I have it.

So long, thanks for pushing me in the right direction, @wakaleo

**Comment by zzoubian** [comment]
@pmmdre  - Did you ever resolve this issue?  I am seeing this on my windows machine as well.  Using serenity 2.1.5.

**Comment by zzoubian** [comment]
I was able to workaround this issue by setting it in the serenity.properties file:
report.assets.directory = ${user.dir}/src/test/resources/assets

**Comment by pmmdre** [comment]
@zzoubian in our case, disabling gradle deamon for local executions did the trick. Thanks for the idea concerning the properties file!
