### ISSUE TITLE
Incorrect stack trace when chain methods are used

### ISSUE THREAD

**Issue by JetFree** [serenity-bdd/serenity-core#1814]
For example, I have a test that checks some info:
```
staffSteps.atAccountSchoolAdministrationPage().verifyLicenseInfoForSchool(secondCreatedSchool, 41, secondSchoolStCount, true);

staffSteps.atAccountSchoolAdministrationPage().selectSchoolByName(createdSchool.getSchoolName())
   .verifyLicenseInfoReserved(reservedFirstSchool, LICENSE_AMOUNT - reservedForSecondSchool, firstSchoolStCount)
                .cancel();
```

This code will be failed on method `staffSteps.atAccountSchoolAdministrationPage().verifyLicenseInfoForSchool` because this method contains assert. 

In this case serenity will provide NPE with stack trace on line `.cancel();` but have to provide assertion error with stack trace on line `staffSteps.atAccountSchoolAdministrationPage().verifyLicenseInfoForSchool`.

Example of how I use chain methods:
```
@Step
    public AtSchoolDetailsPage verifyLicenseInfoReserved(int reserved, int available, int assigned) {
        Assert.assertTrue("School has incorrect license type. Expected Reserved, but found Any available",
                    doesSchoolHaveReservedLicenses());
        Assert.assertEquals(reserved, getReservedLicensesNumber());
        Assert.assertEquals(available, getAvailableLicensesNumber());
        Assert.assertEquals(assigned, getAssignedLicensesNumber());
        return this;
    }
```

Example of stack trace I get:
```
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - STEP FAILURE: org.junit.ComparisonFailure: expected:<4[1] reserved> but was:<4[0] reserved>
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - STARTING STEP Select school by name: UsM3uJyUAutomation
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - IGNORING STEP



java.lang.NullPointerException
	at com.readnaturally.qa.tests.ui.staff.accountschool.changeallocationtype.LicensingAllocationReservedTypeTest.bothSchoolsChangedToReservedWithStudents(LicensingAllocationReservedTypeTest.java:330)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.readnaturally.qa.framework.runner.RniSerenityRunner$FrameworkMethodWithParameters.invokeExplosively(RniSerenityRunner.java:122)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)
	at com.readnaturally.qa.framework.runner.RniSerenityRunner$RunBeforeWithUser.evaluate(RniSerenityRunner.java:150)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:435)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:239)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by wakaleo** [comment]
Chaining methods in this way is not compatible with Serenity instrumentation.

**Comment by JetFree** [comment]
Is anything planned to do with it in future?

**Comment by wakaleo** [comment]
Not really.

**Comment by JetFree** [comment]
It's sad
