### ISSUE TITLE
Serenity initialization error

### ISSUE THREAD

**Issue by vedshankar14** [serenity-bdd/serenity-core#1819]
Hi, 

I am using serenity with cucumber using gradle.
have following dependencies:
    compile group: 'net.serenity-bdd', name: 'serenity-core', version: '2.0.49'
    compile group: 'net.serenity-bdd', name: 'serenity-spring', version: '2.0.49'
    compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '2.0.49'
    compile group: 'net.serenity-bdd', name: 'serenity-cucumber', version: '1.9.38'
    compile group: 'io.cucumber', name: 'cucumber-java', version: '4.4.0'
    compile group: 'io.cucumber', name: 'cucumber-core', version: '4.4.0'
    compile group: 'io.cucumber', name: 'cucumber-junit', version: '4.4.0'

if I am changing cucumber version 4.4.0 to 2.4.0 then it is working fine but with 4.4.0 giving below error.

I have tried with force resolution strategy with 2.4.0. Version is not getting updated.

Serenity initializationError

java.lang.NullPointerException
	at net.serenitybdd.cucumber.CucumberWithSerenity.getChildren(CucumberWithSerenity.java:94)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:359)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Comment by hariharanravichandran** [comment]
Try this https://github.com/serenity-bdd/serenity-cucumber4/issues/8#issuecomment-496666562

**Comment by wakaleo** [comment]
Make sure you respect the Serenity and Cucumber library versions: see https://github.com/serenity-bdd/serenity-core/blob/master/README.md#serenity-with-junit. Serenity does not support Cucumber 4.4.0

**Comment by wakaleo** [comment]
Also, make sure your dependencies are defined as described in https://github.com/serenity-bdd/serenity-cucumber4#adding-the-cucumber-4-dependency

**Comment by vedshankar14** [comment]
Tried with serenity-cucumber-4 also.. getting some other issue.
is there any possibility to provide support for higher version of cucumber with serenity-cucumber?
I am asking because I am not using serenity-cucumber4.

**Comment by wakaleo** [comment]
No. Cucumber 4 is not backward compatible.

**Comment by wakaleo** [comment]
Closing for lack of activity.
