### ISSUE TITLE
Appium pages have null web driver in some step libraries

### ISSUE THREAD

**Issue by justinhinze** [serenity-bdd/serenity-core#1828]
The web driver and elements are null in page objects in some step libraries but not others. 

- Only when tests are run with CucumberWithSerenity.class
- Only when using Appium driver
- Same with `serenity-cucumber` and `serenity-cucumber4`

_Stack Trace_
`java.lang.NullPointerException
	at suite.pages.SomePage.tapLocationStatus(SomePage.java:16)
	at suite.steps.SomeSteps.tapLocationStatus(SomeSteps.java:13)
	at suite.steps.SomeSteps$$EnhancerByCGLIB$$dbfafe36.CGLIB$tapLocationStatus$0(<generated>)
	at suite.steps.SomeSteps$$EnhancerByCGLIB$$dbfafe36$$FastClassByCGLIB$$4d4dfb2b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:460)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:445)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:420)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:175)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:162)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:68)
	at suite.steps.SomeSteps$$EnhancerByCGLIB$$dbfafe36.tapLocationStatus(<generated>)
	at step_definitions.MyStepdefs.doItAgain(MyStepdefs.java:23)
	at ✽.I should be able to do the same in another(src/test/resources/features/AFeature.feature:6)`

_App under test_
https://github.com/appium/ios-test-app

_Sample project_
[serenitycucumberfourappiumseven.zip](https://github.com/serenity-bdd/serenity-core/files/3673850/serenitycucumberfourappiumseven.zip)

**Comment by wakaleo** [comment]
Maybe one of the Appium users can check this out?
