### ISSUE TITLE
Random failure with 'IllegalStateException: Cannot retrieve Junit4 test start event'

### ISSUE THREAD

**Issue by nu75h311** [serenity-bdd/serenity-core#1829]
This is happening ~1 out of 20 runs on Bamboo in Linux. All tests pass but the build fails because of the below dump.
Locally it runs fine.

Any ideas?

Versions:
```
<serenity.version>2.0.9</serenity.version>
<serenity.maven.version>2.0.9</serenity.maven.version>
<serenity.cucumber.version>1.9.19</serenity.cucumber.version>
<cucumber.version>2.4.0</cucumber.version>
<xml.apis.version>1.4.01</xml.apis.version>
```

Stack trace:
```
build	28-Sep-2019 12:20:05	Tests run: 95, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3,054.465 sec <<< FAILURE! - in com.etc.etc.etc.TestRunnerIT
build	28-Sep-2019 12:20:05	Feature: Perform ETC calculation  Time elapsed: 45.272 sec  <<< ERROR!
build	28-Sep-2019 12:20:05	net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:203)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:180)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
build	28-Sep-2019 12:20:05		at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:892)
build	28-Sep-2019 12:20:05		at cucumber.runtime.formatter.SerenityReporter.finishExample(SerenityReporter.java:704)
build	28-Sep-2019 12:20:05		at cucumber.runtime.formatter.SerenityReporter.handleTestCaseFinished(SerenityReporter.java:272)
build	28-Sep-2019 12:20:05		at cucumber.runtime.formatter.SerenityReporter.lambda$new$2(SerenityReporter.java:117)
build	28-Sep-2019 12:20:05		at cucumber.runner.EventBus.send(EventBus.java:28)
build	28-Sep-2019 12:20:05		at cucumber.api.TestCase.run(TestCase.java:65)
build	28-Sep-2019 12:20:05		at cucumber.runner.Runner.runPickle(Runner.java:80)
build	28-Sep-2019 12:20:05		at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
build	28-Sep-2019 12:20:05		at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
build	28-Sep-2019 12:20:05		at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
build	28-Sep-2019 12:20:05		at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
build	28-Sep-2019 12:20:05		at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
build	28-Sep-2019 12:20:05		at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
build	28-Sep-2019 12:20:05		at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
build	28-Sep-2019 12:20:05		at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
build	28-Sep-2019 12:20:05		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
build	28-Sep-2019 12:20:05	Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@22712bd1
build	28-Sep-2019 12:20:05		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
build	28-Sep-2019 12:20:05		at java.util.concurrent.FutureTask.get(FutureTask.java:192)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:200)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:180)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
build	28-Sep-2019 12:20:05		at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:892)
build	28-Sep-2019 12:20:05		at cucumber.runtime.formatter.SerenityReporter.finishExample(SerenityReporter.java:704)
build	28-Sep-2019 12:20:05		at cucumber.runtime.formatter.SerenityReporter.handleTestCaseFinished(SerenityReporter.java:272)
build	28-Sep-2019 12:20:05		at cucumber.runtime.formatter.SerenityReporter.lambda$new$2(SerenityReporter.java:117)
build	28-Sep-2019 12:20:05		at cucumber.runner.EventBus.send(EventBus.java:28)
build	28-Sep-2019 12:20:05		at cucumber.api.TestCase.run(TestCase.java:65)
build	28-Sep-2019 12:20:05		at cucumber.runner.Runner.runPickle(Runner.java:80)
build	28-Sep-2019 12:20:05		at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
build	28-Sep-2019 12:20:05		at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
build	28-Sep-2019 12:20:05		at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
build	28-Sep-2019 12:20:05		at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
build	28-Sep-2019 12:20:05		at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
build	28-Sep-2019 12:20:05		at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
build	28-Sep-2019 12:20:05		at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
build	28-Sep-2019 12:20:05		at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
build	28-Sep-2019 12:20:05		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
build	28-Sep-2019 12:20:05	Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@22712bd1
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:241)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
build	28-Sep-2019 12:20:05		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
build	28-Sep-2019 12:20:05		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
build	28-Sep-2019 12:20:05		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
build	28-Sep-2019 12:20:05		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
build	28-Sep-2019 12:20:05		at java.lang.Thread.run(Thread.java:748)
build	28-Sep-2019 12:20:05	Caused by: java.util.NoSuchElementException: No value present
build	28-Sep-2019 12:20:05		at java.util.Optional.get(Optional.java:135)
build	28-Sep-2019 12:20:05		at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:95)
build	28-Sep-2019 12:20:05		at net.thucydides.core.tags.BreadcrumbTagFilter.getRequirementBreadcrumbsFrom(BreadcrumbTagFilter.java:51)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:199)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:186)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:162)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:106)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
build	28-Sep-2019 12:20:05		at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
build	28-Sep-2019 12:20:05		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
build	28-Sep-2019 12:20:05		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
build	28-Sep-2019 12:20:05		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
build	28-Sep-2019 12:20:05		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
build	28-Sep-2019 12:20:05		at java.lang.Thread.run(Thread.java:748)
build	28-Sep-2019 12:20:05	
build	28-Sep-2019 12:20:05	Test mechanism  Time elapsed: 45.272 sec  <<< ERROR!
build	28-Sep-2019 12:20:05	java.lang.IllegalStateException: Cannot retrieve Junit4 test start event from finished description 'Feature: Perform ETC calculation'.
build	28-Sep-2019 12:20:05		at com.gradle.maven.scan.extension.test.listener.junit4.Junit4TestListener.a(SourceFile:127)
build	28-Sep-2019 12:20:05		at com.gradle.maven.scan.extension.test.listener.junit4.Junit4TestListener.a(SourceFile:95)
build	28-Sep-2019 12:20:05		at com.gradle.maven.scan.extension.test.listener.junit4.Junit4TestListener.testFailure(SourceFile:82)
build	28-Sep-2019 12:20:05		at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:142)
build	28-Sep-2019 12:20:05		at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
build	28-Sep-2019 12:20:05		at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:138)
build	28-Sep-2019 12:20:05		at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:132)
build	28-Sep-2019 12:20:05		at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.run(ParentRunner.java:369)
build	28-Sep-2019 12:20:05		at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
build	28-Sep-2019 12:20:05		at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
build	28-Sep-2019 12:20:05		at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
build	28-Sep-2019 12:20:05		at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
build	28-Sep-2019 12:20:05		at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
build	28-Sep-2019 12:20:05		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
build	28-Sep-2019 12:20:05		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
build	28-Sep-2019 12:20:05		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
build	28-Sep-2019 12:20:05	
build	28-Sep-2019 12:20:05	
build	28-Sep-2019 12:20:05	Results :
build	28-Sep-2019 12:20:05	
build	28-Sep-2019 12:20:05	Tests in error: 
build	28-Sep-2019 12:20:05	  Failed to generate configuration report
build	28-Sep-2019 12:20:05	  Cannot retrieve Junit4 test start event from finished description 'Feature: Perform ETC calculation'.
build	28-Sep-2019 12:20:05	
build	28-Sep-2019 12:20:05	Tests run: 95, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by wakaleo** [comment]
Could be an IO issue. Have you tried with more recent versions?

**Comment by nu75h311** [comment]
You mean io.cucumber? I have the same version running on another module with no issues.
I will try to upgrade serenity versions, but it's hard to reproduce.
