### ISSUE TITLE
SerenityBDD Chrome unable to download files in headless and unable to redirect download path

### ISSUE THREAD

**Issue by gheeno** [serenity-bdd/serenity-core#1849]
As a Serenity User, I would like to download a file ( via clicking a button ) in headless mode, also - have this file saved in a folder of my choosing. 

Scenario :
Given A User Downloads a file
Then the User sees the file in the folder.

POM Settings
```
        <java.version>1.8</java.version>
        <serenity.version>1.8.20</serenity.version>
        <serenity.jbehave.version>1.35.0</serenity.jbehave.version>
        <chromedriver-dep.version>77.0.3865.40</chromedriver-dep.version>
```
Serenity Property File
```
# Test run
driver=chrome
serenity.maintain.session=true
step.creation.strategy=legacy
serenity.browser.width=1920
serenity.browser.height=1080
serenity.keep.unscaled.screenshots=true
        
# Chrome Preferences
chrome_preferences.download.default_directory=System.getProperty("user.dir")
chrome_preferences.downloadPath=System.getProperty("user.dir")
chrome_preferences.download.directory_upgrade=true
chrome_preferences.profile.default_content_settings.popups=0
chrome_preferences.download.prompt_for_download=false
chrome_preferences.safebrowsing.enabled=false
chrome_preferences.safebrowsing.disable_download_protection=true
chrome_preferences.behavior=allow


chrome.capabilities.acceptSslCerts = true
chrome.capabilities.handlesAlerts = true

#Chrome Switches
chrome.switches=--allow-running-insecure-content;--no-sandbox;--disable-web-security;--disable-extension;--disable-dev-shm-usage;--headless;
```

Observations : 
1. The download works properly on NON-HEADLESS mode BUT the file goes to MyDocuments despite the setting.
2. Headless mode - does not download the file at all.
3. Even writing an Absolute `Path` doesn't do anything. It doesn't change the default download folder.

Any help would be awesome.
Thanks

P.S I did ask the query in Rocket, no avail.

**Comment by AshirovaK** [comment]
Hi. As i understand there was a problem in Chrome WebDriver, but in 77.0.3865.10 version solution was be done. 
(https://chromedriver.chromium.org/downloads see point "Support to save file downloads in headless mode" [Issue 2454](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2454))
And now to download files in headless we should use something like this:
```
browser.driver.sendChromiumCommand('Page.setDownloadBehavior', {
    'behavior': 'allow',
    'downloadPath': DOWNLOAD_DIR
});
```
But I dont understand how to use this solution with Serenity :(

**Comment by wakaleo** [comment]
Where is that solution documented? The question is rather, how to do this with the Java ChromeDriver API.

**Comment by wakaleo** [comment]
```
chrome_preferences.download.default_directory=System.getProperty("user.dir")
chrome_preferences.downloadPath=System.getProperty("user.dir")
```
This won't work; properties files can't have Java code in them. However the following might work:
```
chrome_preferences.download.default_directory=${user.dir}
chrome_preferences.downloadPath=${user.dir}
```

**Comment by wakaleo** [comment]
You can configure Chrome as suggested in https://github.com/TheBrainFamily/chimpy/issues/108 like this:

```
chrome.preferences {
    download: "{prompt_for_download: false,directory_upgrade: true,default_directory:'${user.dir}/downloads'}"
}
```

However it doesn't fix the issue - chromedriver still doesn't download in headless mode. I suspect this might be a chromedriver issue.

**Comment by lilyhoang** [comment]
> ```
> chrome_preferences.download.default_directory=System.getProperty("user.dir")
> chrome_preferences.downloadPath=System.getProperty("user.dir")
> ```
> 
> This won't work; properties files can't have Java code in them. However the following might work:
> 
> ```
> chrome_preferences.download.default_directory=${user.dir}
> chrome_preferences.downloadPath=${user.dir}
> ```

Hi wakaleo

how can I add this property for  window with specific folder 
I use as " chrome_preferences.download.default_directory=${user.dir}\download " but it's not help

**Comment by wakaleo** [comment]
See above: I think this is a chromedriver issue; does it work if you are not running chrome in headless mode?

**Comment by anna-yordanova** [comment]
Hello,

I have tried with **chrome_preferences.download.default_directory**=${user.dir}/downloads
but the result path contains backslash and  forward slash (e.g C:\projects\my_project/downloads). Thus the path is invalid.

**Comment by wakaleo** [comment]
> Hello,
> 
> I have tried with **chrome_preferences.download.default_directory**="${user.dir}/downloads"
> but the result path contains backslash and forward slash (e.g C:\projects\my_project/downloads). Thus the path is invalid.

Does it work with forward slash? Java isn't usually fussy about the order of the slashes in paths. But the underlying problem is the chromedriver issue I think, regardless of the accuracy of the path.

**Comment by anna-yordanova** [comment]
The problem seems to be that for Chrome the path has to contain only backslashes (I'm on windows). The same path but with forward slashes is invalid and in result the download fails.

**Comment by wakaleo** [comment]
Can you use `chrome_preferences.download.default_directory=${user.dir}\downloads`?

**Comment by anna-yordanova** [comment]
If it is set in serenity.conf then I have to escape the backslash but the path becomes invalid.

**Comment by wakaleo** [comment]
What if you put it in quotes? Are you using the serenity.conf or serenity.properties file?

**Comment by anna-yordanova** [comment]
I use serenity.conf and the value is in quotes. If it is not escaped the error is:

`1) Error in custom provider, com.typesafe.config.ConfigException$Parse: src\test\resources\serenity.conf: 12: Expecting a value but got wrong token: 'd' (backslash followed by 'd', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) (if you intended 'd' (backslash followed by 'd', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
  at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
  while locating net.thucydides.core.util.EnvironmentVariables`

**Comment by wakaleo** [comment]
Is there another stack trace?

**Comment by anna-yordanova** [comment]
`com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.typesafe.config.ConfigException$Parse: src\test\resources\serenity.conf: 12: Expecting a value but got wrong token: 's' (backslash followed by 's', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) (if you intended 's' (backslash followed by 's', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
  at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
  while locating net.thucydides.core.util.EnvironmentVariables

1 error

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
	at io.cucumber.junit.CucumberSerenityRunner.environmentSpecifiedTags(CucumberSerenityRunner.java:158)
	at io.cucumber.junit.CucumberSerenityRunner.<init>(CucumberSerenityRunner.java:105)
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:9)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: com.typesafe.config.ConfigException$Parse: src\test\resources\serenity.conf: 12: Expecting a value but got wrong token: 's' (backslash followed by 's', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) (if you intended 's' (backslash followed by 's', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:473)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:646)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:688)
	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:702)
	at net.thucydides.core.util.PropertiesFileLocalPreferences.typesafeConfigPreferencesInCustomDefinedConfigFile(PropertiesFileLocalPreferences.java:95)
	at net.thucydides.core.util.PropertiesFileLocalPreferences.loadPreferences(PropertiesFileLocalPreferences.java:58)
	at net.thucydides.core.util.SystemEnvironmentVariables.createEnvironmentVariables(SystemEnvironmentVariables.java:186)
	at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
	at net.thucydides.core.guice.ThucydidesModule$$FastClassByGuice$$a52485fb.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 18 more`

**Comment by AshirovaK** [comment]
> 
> 
> ```
> chrome_preferences.download.default_directory=System.getProperty("user.dir")
> chrome_preferences.downloadPath=System.getProperty("user.dir")
> ```
> 
> This won't work; properties files can't have Java code in them. However the following might work:
> 
> ```
> chrome_preferences.download.default_directory=${user.dir}
> chrome_preferences.downloadPath=${user.dir}
> ```

Now i read, that this way is not working for headless mode. 
[Comment 11](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2454#c11)

> Downloads in headless work a little differently. There's the Page.setDownloadBehavior devtools >command to set a download folder. See also crbug.com/696481.

To resolve this issue we need to be able  to send command to driver? Do I understand the comment 11 by eseckler@chromium.org correctly?

**Comment by AshirovaK** [comment]
This way work in headless mode :) 
```
chrome.preferences.download.default_directory={path}
chrome.preferences.profile.default_content_settings.popupsy=0
```

**Comment by joellis13** [comment]
Not sure if people are still struggling with this, but I was so I'll post my solution here. In serenity.conf, in quotes, the compiler wants to escape what comes after the '\', but if you double them, you get '\\' instead of '\'. The solution was to pull it in as a variable from serenity.properties. The curve ball when bringing a variable into serenity.conf, it double-double escapes the slashes, so you only get 1 '\' for every 4 typed. So if your location is \\\\dev.drive.name\is\qa\downloads, you need to enter \\\\\\\\\\\\\\\\dev.drive.name\\\\\\\\is\\\\\\\\qa\\\\\\\\downloads to make it read correctly. In the example below, note how I default to `user.dir` in `.prop` as the single-slashed path string won't interpret correctly in `.conf`, and also the `#{}` string interpolation syntax instead of `${}`:

`serenity.properties`
```
chrome_preferences.download.default_directory=${user.dir}\\downloads
dev.download.default_directory=\\\\\\\\dev.drive.name\\\\is\\\\qa\\\\downloads
qa.download.default_directory=\\\\\\\\qa.drive.name\\\\is\\\\qa\\\\downloads
```

`serenity.conf`
```
environments {
    local {}
    dev {
        chrome_preferences.download.default_directory="#{dev.download.default_directory}"
    }
    qa {
        chrome_preferences.download.default_directory="#{qa.download.default_directory}"
    }
}
```

**Comment by farfanium** [comment]
I had the same issue to escape backslash, I tried each and every possible solution posted here but none of those worked for me. After scratching my head for several hours, I found myself with the simplest solution:

Let's say, I have my own my_downloads folder at project root level and my suite runs on windows for local executions and on Linux for uat environment, so I did this:

`serenity.conf`

`environments {
    local {
        webdriver {
            prefs {
                download.default_directory = ${user.dir}"\\my_downloads"
            }
        {
    }
    uat {
        webdriver {
            prefs {
                download.default_directory = ${user.dir}/my_downloads
            }
        {
    }
}`

So, to escape backslash in serenity.conf file and make it work on Windows, just put it inside double quotes. no need to do dark tricks

**Comment by nilimamoh** [comment]
I am trying to set the download path in serenity.properties  file with the below options suggested but those are not working in theserenity version (  <version>3.6.17</version>)

chrome_preferences.download.default_directory=${user.dir}\\src/test/resources/testdata/downloads
chrome_preferences.profile.default_content_setting_values.automatic_downloads = 1

**Comment by joellis13** [comment]
> I am trying to set the download path in serenity.properties file with the below options suggested but those are not working in theserenity version ( 3.6.17)
> 
> chrome_preferences.download.default_directory=${user.dir}\src/test/resources/testdata/downloads chrome_preferences.profile.default_content_setting_values.automatic_downloads = 1

@nilimamoh I'm still stuck using v2.x but I think I see 2 problems in your code:
1. You're using both forward and back slashes (will always confuse - just use backslash)
2. I've always had to escape backslashes to have them read, so try doubling each. This will result in your path looking like:
```
chrome_preferences.download.default_directory=${user.dir}\\src\\test\\resources\\testdata\\downloads
```
Not sure it'll apply in your situation, but I've also had to "re-escape" the backslashes if I wanted to reference the property in `serenity.conf` (change the doubles to quadruples just to make a single backslash). See [my comment](https://github.com/serenity-bdd/serenity-core/issues/1849#issuecomment-997020830) above.
