### ISSUE TITLE
Zalenium Integration failing build after successfully executing tests

### ISSUE THREAD

**Issue by lgermani** [serenity-bdd/serenity-core#1857]
1. In order to execute a small test suite using Zalenium, I'm following this documentation: https://serenity-bdd.github.io/theserenitybook/latest/serenity-grid.html

After putting `<dependency>
    <groupId>net.serenity-bdd</groupId>
    <artifactId>serenity-zalenium</artifactId>
    <version>${serenity.version}</version>
    <scope>test</scope>
</dependency>`
on my dependencies the build is failing, even tests run being successful.

```[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.238 s - in slots.admin.specs.auth.BasicAuthenticationTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- serenity-maven-plugin:2.0.81:aggregate (serenity-reports) @ slots-functional-tests ---
[INFO] current_project.base.dir: C:\code\slots-admin\aut
[INFO] Generating test results for 3 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.FileSystemRequirementsTagProvider@7c5fbde4, net.thucydides.core.requirements.PackageRequirementsTagProvider@702e21c]
[INFO] Loading requirements from package requirements at: slots.admin.specs
[INFO] LOADED REQUIREMENTS:
REQUIREMENTS:
    - feature : Auth {id: Auth, displayName: 'Auth', path: , parent: 'null'}
        - story : Basic authentication test {id: Basic authentication test, displayName: 'Basic authentication test', path: auth, parent: 'Auth'}

[INFO] 2 requirements loaded after 456 ms
[INFO] 2 related requirements found after 459 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 533 ms
[INFO] Configured report threads: 40
[INFO] Test results for 3 tests generated in 1.6 secs
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.1:verify (default) @ slots-functional-tests ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.103 s
[INFO] Finished at: 2019-10-25T15:44:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.1:verify (default) on project slots-functional-tests: There are test failures.
[ERROR]
[ERROR] Please refer to C:\code\slots-admin\aut\target\failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException There was an error in the forked process
[ERROR] Test mechanism :: Document is cookie-averse
[ERROR] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
[ERROR] System info: host: 'DESKTOP-UC8GF4M', ip: '192.168.92.143', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11'
[ERROR] Driver info: org.openqa.selenium.remote.RemoteWebDriver
[ERROR] Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0.3, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20191009172106, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 420, moz:profile: /tmp/rust_mozprofilefJwp6r, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.9.184-linuxkit, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: 102908f1-25a9-48f3-95f5-980..., zal:name: Basic authentication test -...}
[ERROR] Session ID: 102908f1-25a9-48f3-95f5-98088d1f15e2
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:510)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:382)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:297)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Test mechanism :: Document is cookie-averse
[ERROR] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
[ERROR] System info: host: 'DESKTOP-UC8GF4M', ip: '192.168.92.143', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11'
[ERROR] Driver info: org.openqa.selenium.remote.RemoteWebDriver
[ERROR] Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0.3, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20191009172106, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 420, moz:profile: /tmp/rust_mozprofilefJwp6r, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.9.184-linuxkit, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: 102908f1-25a9-48f3-95f5-980..., zal:name: Basic authentication test -...}
[ERROR] Session ID: 102908f1-25a9-48f3-95f5-98088d1f15e2
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:371)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:347)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

To reproduce I'm simply using `mvn clean verify -Dwebdriver.remote.url=http://localhost:4444/wd/hub -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.os=LINUX -Denvironment=dev`

2. Also, even when I specify `-Dwebdriver.remote.driver=chrome` and have

```
webdriver {
  driver = remote
  remote {
    url="http://localhost:4444/wd/hub"
    driver=chrome
  }
}
``` 

on my serenity.conf, the test it's running on firefox AND chrome.

```
Oct 25, 2019 3:43:44 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Oct 25, 2019 3:43:48 PM org.openqa.selenium.remote.ProtocolHandshake createSession
```

Here is the full log: https://gist.github.com/lgermani/239642223f7d0a9b0ad3b72632b1388f

3. It seems that test metadata being passed to Zalenium Dashboard it's kinda buggy:
![image](https://user-images.githubusercontent.com/1315828/67577297-7ab28c00-f740-11e9-9528-f90b39400bd1.png)

In order to run my containers I'm executing the command suggested on the documentation:

```
docker run --rm -ti --name zalenium -p 4444:4444 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/videos:/home/seluser/videos -e WAIT_FOR_AVAILABLE_NODES=false \
  --privileged dosel/zalenium start --desiredContainers 4
```

Am I doing something wrong in the zalenium configuration / serenity?

**Comment by lgermani** [comment]
Please check the following code:
https://gist.github.com/lgermani/2833f9b21df6255a7e7e99191030157a

When I move "slotsAdminHomePage.open();" from "SlotsAdminTestSetup" class and put inside BasicAuthenticationTest.shouldBeAbleToLogInAsAdminWithBasicAuth it works normally.

So it seems that the iteration I'm making with the browser by opening the default system page 
on the @Before it's generating some kind of bug that is trying to create a second browser without capabilities (then trying to open firefox since it's the default).

Any clue how can I solve this?

**Comment by lgermani** [comment]
Found that the problem was calling driver.getCurrentUrl() on BasicAuthenticationTest.slotsAdminFunctionalSetup, aparently the way I'm getting the driver instance from FunctionalTestAutomationSetup it's not working correctly.

Whats the correct way to get Webdriver Instance from serenity?

**Comment by wakaleo** [comment]
It's probably something to do with the order of instantiation of the driver; I would need to study the code more closely to understand more. `getDriver().getCurrentUrl()` is the usual way.

**Comment by lgermani** [comment]
@wakaleo you're right, `getDriver().getCurrentUrl()` works when you're inside an object that extends `PageObject`, for the other ones, what I found it works is `Serenity.getWebdriverManager().getCurrentDriver()`.

So for now, issues 1. and 2. are solved.

Number 3. Test meta-data passed to zalenium dashboard it's kinda buggy, instead of showing the test tittle is showing a hash.

**Comment by wakaleo** [comment]
If you are having issues with the specific Zalenium integration have a look at https://github.com/serenity-bdd/serenity-core/tree/master/serenity-zalenium and see if you can propose some PRs.
