### ISSUE TITLE
serenity-core 2.0.46 (and newer) + BrowserStack throws net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

### ISSUE THREAD

**Issue by johannes-namics** [serenity-bdd/serenity-core#1859]
Hello there,

I've setup a small project to run tests on BrowserStack.
Up to ``serenity-core`` v2.0.45 it's been working fine. But once I update to v2.0.46 or higher I get: ``net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver`` 

Here's the stacktrace:
```
-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   /
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|

 News and tutorials at http://www.serenity-bdd.info
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport
 Learn Serenity BDD online at http://serenity-dojo.com
-------------------------------------------------------------------------------------

900 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Acceptance test
971 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener -
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/


TEST STARTED: should_see_a_list_of_search_results_after_searching_for_a_valid_search_term
-------------------------------------------------------------------
971 [main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
Oct 28, 2019 1:31:12 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
1650 [main] ERROR net.thucydides.core.steps.ConsoleLoggingListener -
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/
          \_\

TEST FAILED WITH ERROR: Should see a list of search results after searching for a valid search term
---------------------------------------------------------------------
1738 [main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Opens etsy home page
1738 [main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.232 s <<< FAILURE! - in com.namics.nta.demo.etsy.testcases.AcceptanceTest
[ERROR] should_see_a_list_of_search_results_after_searching_for_a_valid_search_term(com.namics.nta.demo.etsy.testcases.AcceptanceTest)  Time elapsed: 0.627 s  <<< ERROR!
net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (null). See below for more details.
        at com.namics.nta.demo.etsy.testcases.AcceptanceTest.should_see_a_list_of_search_results_after_searching_for_a_valid_search_term(AcceptanceTest.java:18)
```

I've added a minimal version of our project for you to reproduce the error.
[minimal-BS-project.zip](https://github.com/serenity-bdd/serenity-core/files/3778720/minimal-BS-project.zip)

Once unpacked you'll need to add valid BrowserStack credentials to ``src/test/resources/serenity.properties``. Afterwards you should be able to run the ``AcceptanceTest`` with ``mvn verify``. But when you change ``<serenity.maven.version>`` in the pom.xml from 2.0.45 to 2.0.46 (or higher) it's going to fail with the error I've mentioned.

Any help will be very much appreciated. :-)

Cheers,
Johannes

**Comment by wakaleo** [comment]
You need to make sure you are using the appropriate version of Firefox and geckodriver for whatever version of Selenium Serenity is using.

**Comment by johannes-namics** [comment]
Hi John,

thank you for the fast response.

To be honest I'm unsure how to make sure I'm using the correct versions of Firefox and Geckodriver.

I can run the tests fine on a local Selenium Standalone Server v3.141.59 with Geckodriver v0.24.0 and Firefox v.70 by changing ``serenity.properties`` to:

```
webdriver.remote.url=http://localhost:4444/wd/hub
webdriver.remote.os=WINDOWS
webdriver.remote.driver=firefox
serenity.browser.maximized=true
```
I'm on Windows 10 Enterprise v10.0.18362 Build 18362.

But when I try to run them on BrowserStack they always fail. I've tried all combinations of: 
``browserstack.browser_version=67.0`` to ``70.0``
``browserstack.geckodriver=0.23.0`` to ``0.25.0``
(and also ``browserstack.firefox.driver=0.23.0`` to ``0.25.0``; I'm not sure which one is correct)
with
``browserstack.selenium_version=3.141.59``

According to BrowserStack's [Capabilities Generator](https://www.browserstack.com/automate/capabilities) Firefox 70 and Geckodriver 24 should be compatible with Selenium 3.141.59. And they are on my machine.

As I said, it also works with ``erenity-core`` v2.0.45 but breaks when I update to v2.0.46 (or higher). So I strongly suspect there is some change in [2.0.46](https://github.com/serenity-bdd/serenity-core/commit/70cca75e14962ce04611aedee0ca55c9d08bb6c9) that BrowserStack has a problem with.

Please also note I can reproduce the same behaviour when running the tests with Chrome.
I use:
```
browserstack.browser=Chrome
browserstack.browser_version=77.0
```
With ``serenity-core`` v2.0.46 I get the same error referring to FirefoxDriver. Whereas it works with v2.0.45.

**Comment by wakaleo** [comment]
If you suspect it is a change then it would be worth investigating the git changes for that version. I won’t have time to look into this for a while but I’m happy to point you in the right direction if you see anything odd. 

Those versions are relatively old now - have you tried with more recent versions?

**Comment by johannes-namics** [comment]
I've just tried setting ``serenity-core``'s version to 2.0.87 in the sources I uploaded in the first post. (minimal-BS-project.zip)
I get the very same error.

**Comment by wakaleo** [comment]
If it runs locally but not on BrowserStack, I suspect there is some property you need to provide to BrowserStack. Have a look at the changes in git between those versions of you think it is related. I doubt I can reproduce the issue or take a look any time soon though.

**Comment by amaliaburulea** [comment]
Hi, I have the exact same issue.  It seems that 2.0.46 was a major update and since then properties like 
`browserstack.browser=Chrome
browserstack.browser_version=77.0` are not working anymore.

**Comment by wakaleo** [comment]
See above. If you can tell me the properties needed for recent chrome versions, it should be easy to pass them to browserstack.

**Comment by dezignedqa** [comment]
Did anyone find a solution? walk around?

**Comment by amaliaburulea** [comment]
> 
> 
> Did anyone find a solution? walk around?
> 2.0.46 is working fine for me.
> 
> 2.0.47 says:
> [main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - net.thucydides.core.webdriver.DriverConfigurationError-->Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
> 
> 2.2.9 has the same error as in issue description

Hi, yes, I updated to the latest serenity version and I used the model provided here: https://github.com/browserstack/serenity-browserstack/blob/master/src/test/java/com/browserstack/BrowserStackSerenityDriver.java
You can check also the serenity.property file in that repo to see how to specify the properties.
I hope it helps.

**Comment by dezignedqa** [comment]
It's working. Thank you so much!

I added https://github.com/browserstack/serenity-browserstack/blob/master/src/test/java/com/browserstack/BrowserStackSerenityDriver.java class to my projects and set serenity properties like:
browserstack.user=cleared
browserstack.key=cleared
browserstack.server=hub-cloud.browserstack.com

webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.browserstack.BrowserStackSerenityDriver
serenity.driver.capabilities = mydriver

webdriver.timeouts.implicitlywait = 5000
serenity.use.unique.browser = false
serenity.dry.run=false

environment.single.browser=chrome

**Comment by dezignedqa** [comment]
Amalia, another question: did you manage to launch tests in any other browser except Chrome?)

**Comment by amaliaburulea** [comment]
Yes, It works on other browsers as well, I do not use cross-browsing on a daily basis but I was able to start the tests on various browsers and devices.
To do so you have to specify something like this in serenity.properties :
bstack_browser = Firefox
bstack_os = Windows
bstack_os_version = 10
bstack_browser_version = 77.0

**Comment by dezignedqa** [comment]
bstack_browser = Firefox
It's working. 
I wish you all the best! You helped me so much!

**Comment by amaliaburulea** [comment]
Hello again. I just updated to Serenity 2.2.9 and retried with remote driver and it seems to work.
What I provided in the properties file is this:
```
webdriver.remote.url=http://{browserstack.user}:{browserstack.key}@{browserstack.server}
browserstack.browser = Chrome
browserstack.os = Windows
browserstack.os_version = 10
browserstack.resolution = 1920x1080
browserstack.browser_version = 77.0
browserstack.local=true
browserstack.localIdentifier=YourLocalIdentifier
bstack.acceptSslCert = false
bstack.forceLocal=true
```
Notice that some properties must be specified as `bstack.` and not `browserstack.` and this is a bit confusing. For example, `browserstack.acceptSslCert = false` would return an error.
But at least now the error is clear :` net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (The property '#/firstMatch/0/bstack:options' contains additional properties ["forceLocal"] outside of the schema when none are allowed in the payload. 
`
In this case there is no need to add BrowserStackSerenityDriver.java  class as mentioned above

**Comment by vishalweb** [comment]
I am facing similar error when trying to launch tests on appium on bitbar. Would anyone have a solution on how to set capabilities for bitbar in serenity.properties for mobile app

Error:
Failed to instantiate page (net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class io.appium.java_client.AppiumDriver)

I have provided the following in the serenity.properties (have removed the values here but am passing the correct values)
webdriver.driver= appium
appium.hub = https://appium.bitbar.com/wd/hub/
appium.platformName=
appium.deviceName=
appium.automationName=Appium
appium.bitbar_apiKey=
appium.bitbar_device=
appium.bitbar_app=
appium.app=
appium.bitbar_target=android
appium.appPackage=
appium.appActivity=

**Comment by tejaldud** [comment]
I am facing issue with Firefox driver initialisation


Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:34012
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Tejals-MBP', ip: 'fe80:0:0:0:14a1:eff5:72b1:c4fe%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_241'
Driver info: driver.version: ProvideNewDriver). See below for more details.
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:159)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:172)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:913)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:814)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:802)
	at hotelbooking.BookingStefDefs.iAmOnTheBookingPage(BookingStefDefs.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:64)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:104)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:73)
	at io.cucumber.core.runtime.Runtime.lambda$execute$5(Runtime.java:110)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
	at io.cucumber.core.runtime.Runtime.lambda$execute$6(Runtime.java:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:233)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:86)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:87)
	at io.cucumber.core.cli.Main.run(Main.java:92)
	at io.cucumber.core.cli.Main.main(Main.java:34)
Caused by: org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:34012
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Tejals-MBP', ip: 'fe80:0:0:0:14a1:eff5:72b1:c4fe%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_241'
Driver info: driver.version: ProvideNewDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	

Below is the version i am using for serenity 
    <serenity.version>3.0.5</serenity.version>
        <serenity.maven.version>2.4.24</serenity.maven.version>
        <serenity.cucumber.version>2.4.34</serenity.cucumber.version>
        <logback.version>1.2.3</logback.version>
