### ISSUE TITLE
Ensure not working with Serenity 2.0.84 

### ISSUE THREAD

**Issue by ssmuthukumaran** [serenity-bdd/serenity-core#1875]
Am using serenity cucumber, in one of the tasks am using ensure for asserting.
Was using 2.0.72 and had no issues, upgraded serenity core to 2.0.84 and got following exception
`   java.lang.IllegalStateException: Invisible parameter type of kotlin.jvm.internal.DefaultConstructorMarker arg6 for public net.serenitybdd.screenplay.ensure.PerformableExpectation$ByteBuddy$lbmLYhHQ(java.lang.Object,net.serenitybdd.screenplay.ensure.Expectation,java.lang.Object,boolean,java.lang.String,int,kotlin.jvm.internal.DefaultConstructorMarker)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:1396)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:519)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:207)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:198)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3404)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3600)
	at net.thucydides.core.steps.StepFactory.createProxyStepLibrary(StepFactory.java:210)
	at net.thucydides.core.steps.StepFactory.instantiateUniqueStepLibraryFor(StepFactory.java:193)
	at net.thucydides.core.steps.StepFactory.getUniqueStepLibraryFor(StepFactory.java:129)
	at net.serenitybdd.core.steps.Instrumented$InstrumentedBuilder.newInstance(Instrumented.java:30)
	at net.serenitybdd.screenplay.InstrumentedTask.instrumentedCopyOf(InstrumentedTask.java:64)
	at net.serenitybdd.screenplay.InstrumentedTask.of(InstrumentedTask.java:23)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:171)
	at serenity.tasks.common.CreateTask.performAs(CreateTask.java:54)`

Am using SerenityCucumber 1.9.48

**Comment by wakaleo** [comment]
Could be a library issue, though the serenity-ensure library hasn’t changed recently. Could you provide a sample project?

**Comment by wakaleo** [comment]
It could be related to Kotlin and ByteBuddy (see https://github.com/raphw/byte-buddy/issues/350), which has been updated in recent versions. What version are you using exactly?
