### ISSUE TITLE
RestAssured scenarios are falied with SerenityManagedException.

### ISSUE THREAD

**Issue by biatcha** [serenity-bdd/serenity-core#1897]
All RestAssured related test starts failing from today, all was set on Friday. No changes in project was made.
 
net.serenitybdd.core.exceptions.SerenityManagedException: null
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3067)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.http.impl.client.DefaultRedirectStrategy.createLocationURI(DefaultRedirectStrategy.java:189)
	at org.apache.http.impl.client.DefaultRedirectStrategy.getLocationURI(DefaultRedirectStrategy.java:148)
	at org.apache.http.impl.client.DefaultRedirectStrategy.getRedirect(DefaultRedirectStrategy.java:221)
	at org.apache.http.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:1083)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:514)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:2128)
	at io.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:494)
	at io.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:451)
	at io.restassured.internal.http.HTTPBuilder$request$2.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at io.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1531)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
	at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)
	at io.restassured.filter.Filter$filter$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at io.restassured.filter.Filter$filter.call(Unknown Source)
	at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
	at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)
	at io.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
	at io.restassured.filter.FilterContext$next.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1731)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
	at com.buydomains.steps.BDUserStepsApiCalls.systemCallGetContactAuth(BDUserStepsApiCalls.java:1670)
	at com.buydomains.steps.BDUserStepsApiCalls$$EnhancerByCGLIB$$92a79e76.CGLIB$systemCallGetContactAuth$64(<generated>)
	at com.buydomains.steps.BDUserStepsApiCalls$$EnhancerByCGLIB$$92a79e76$$FastClassByCGLIB$$7877f24a.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:449)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:434)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:409)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:150)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:137)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:68)
	at com.buydomains.steps.BDUserStepsApiCalls$$EnhancerByCGLIB$$92a79e76.systemCallGetContactAuth(<generated>)
	at com.buydomains.jbehave.BDStepsApiCalls.whenSystemCallGetContactAuth(BDStepsApiCalls.java:637)
[pom.txt](https://github.com/serenity-bdd/serenity-core/files/3968167/pom.txt)

**Comment by wakaleo** [comment]
SerenityManagedExceptoion is just a wrapper for an underlying issue. Have a look at the reports to see the actual issue. If no changes were made to the code, something must have changed with the app under test.

**Comment by biatcha** [comment]
sorry, thats from report

org.apache.http.client.ClientProtocolException | org.apache.http.client.ClientProtocolException

org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:839)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)io.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:494)io.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:451)io.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1531)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1290)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1731)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:-1)com.buydomains.steps.BDUserStepsApiCalls.systemCallGetContactAuth(BDUserStepsApiCalls.java:1670)com.buydomains.jbehave.BDStepsApiCalls.whenSystemCallGetContactAuth(BDStepsApiCalls.java:637) | org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:839)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)io.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:494)io.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:451)io.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1531)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1290)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1731)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:-1)com.buydomains.steps.BDUserStepsApiCalls.systemCallGetContactAuth(BDUserStepsApiCalls.java:1670)com.buydomains.jbehave.BDStepsApiCalls.whenSystemCallGetContactAuth(BDStepsApiCalls.java:637)
-- | --
org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:839)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)io.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:494)io.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:451)io.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1531)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1290)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1731)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy:-1)io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:-1)com.buydomains.steps.BDUserStepsApiCalls.systemCallGetContactAuth(BDUserStepsApiCalls.java:1670)com.buydomains.jbehave.BDStepsApiCalls.whenSystemCallGetContactAuth(BDStepsApiCalls.java:637)

**Comment by biatcha** [comment]
![exc](https://user-images.githubusercontent.com/37931802/70910477-7441e180-2018-11ea-9636-e78e2d3ecb87.jpg)

**Comment by wakaleo** [comment]
That sounds like either a  server issue or a problem with the URL you are requesting

**Comment by biatcha** [comment]
my apologies, found the issue with application auth. Thank you
