### ISSUE TITLE
[Serenity Rest] - Get request in a After hook is throwing NullPointerException

### ISSUE THREAD

**Issue by ralves20** [serenity-bdd/serenity-core#1907]
Hello,

In my test suite I need to perform a Get request in a After (cucumber hook), and when I perform this request using the default screenplay way, I'm getting nullpointer exception. Apparently serenity is losing the reference to the task object, when executed on the after hook.

**Request:**
`        actor.attemptsTo(
                Check.whether(name != null)
                        .andIfSo(
                                Get.resource(endpointForSearchParametrizationWithName)
                                        .with(requestSpecification -> requestSpecification
                                                .pathParam("name", name)
                                                .headers(headerContent)))
                        .otherwise(
                                Get.resource(endpointForSearchAllParametrization)
                                        .with(requestSpecification -> requestSpecification
                                                .headers(headerContent))));`

**Exception stacktrace:**
`java.lang.NullPointerException
	at 
	at 
	at net.serenitybdd.screenplay.Actor.performTask(Actor.java:233)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:214)
	at net.serenitybdd.screenplay.Actor.performWithoutReporting(Actor.java:198)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:169)
	at br.com.fastshop.carrinhomultiplo.cucumber.steps_definition.CommonSteps.after_scenario(CommonSteps.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)
	at cucumber.runner.TestStep.executeStep(TestStep.java:63)
	at cucumber.runner.TestStep.run(TestStep.java:49)
	at cucumber.runner.TestCase.run(TestCase.java:48)
	at cucumber.runner.Runner.runPickle(Runner.java:40)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at net.serenitybdd.cucumber.CucumberWithSerenity.runChild(CucumberWithSerenity.java:193)
	at net.serenitybdd.cucumber.CucumberWithSerenity.runChild(CucumberWithSerenity.java:64)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at net.serenitybdd.cucumber.CucumberWithSerenity$1.evaluate(CucumberWithSerenity.java:202)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

However when I use the SerenityRest.get(), the request just works well.
**example:**
`SerenityRest.given().headers(headerContent).when().get(endpoint);`

So, I just created a Performable to performs the request on the way described.

**Serenity version: 2.0.80**
**Cucumber version: 4.2.0**

It seems to be a bug... is it?

**Comment by wakaleo** [comment]
Can you provide a sample project for this?
