### ISSUE TITLE
Serenity reports are not generated (ReportGenerationFailedError: Failed to generate configuration report)

### ISSUE THREAD

**Issue by amirduran** [serenity-bdd/serenity-core#1915]
When I run my tests then tests are completed but the reports are not generated and I have no idea what the problem might be. 

Here are some parts of my `pom.xml ` file (some other project related dependencies which are not important are not included):

```
<properties>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	<java.version>1.8</java.version>
	<maven.compiler.source>1.8</maven.compiler.source>
	<maven.compiler.target>1.8</maven.compiler.target>
	<spring.version>1.4.2.RELEASE</spring.version>
	<serenity.version>2.0.91</serenity.version>
	<serenity.maven.version>2.0.91</serenity.maven.version>
	<selenium.version>3.141.59</selenium.version>
</properties>

<plugin>
	<groupId>net.serenity-bdd.maven.plugins</groupId>
	<artifactId>serenity-maven-plugin</artifactId>
	<version>${serenity.maven.version}</version>
	<executions>
		<execution>
			<id>serenity-reports</id>
			<phase>post-integration-test</phase>
			<goals>
				<goal>aggregate</goal>
			</goals>
		</execution>
	</executions>
</plugin>
<dependencies>
	
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-spring</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/io.rest-assured/spring-mock-mvc -->
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>spring-mock-mvc</artifactId>
			<version>4.1.2</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>${selenium.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-api</artifactId>
			<version>${selenium.version}</version>
			<scope>test</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-remote-driver -->
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-driver</artifactId>
			<version>${selenium.version}</version>
		</dependency>

</dependencies>
```

```
-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----'|  |__   |  |_)  |    |  |__   |   \|  | |  | '---|  |----' \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . '  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| '._____||_______||__| \__| |__|     |__|         |__|    
                                                                                     
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat      
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
 Learn Serenity BDD online at http://serenity-dojo.com                               
-------------------------------------------------------------------------------------

09:26:55.777 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: User api test
09:26:55.858 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____  
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \ 
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/ 
                                                                  

TEST STARTED: testUserLogin
-------------------------------------------------------------------
09:26:55.858 [main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
09:26:56.359 [main] DEBUG net.thucydides.core.steps.StepInterceptor - STARTING STEP: UserApiTest.testUserLogin - Login user
09:26:58.643 [main] DEBUG org.apache.http.impl.conn.BasicClientConnectionManager - Get connection for route {}->http://localhost:9080
09:26:58.659 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnectionOperator - Connecting to localhost:9080
09:26:58.686 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: ignoreCookies
09:26:58.687 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
09:26:58.687 [main] DEBUG org.apache.http.client.protocol.RequestTargetAuthentication - Target auth state: UNCHALLENGED
09:26:58.688 [main] DEBUG org.apache.http.client.protocol.RequestProxyAuthentication - Proxy auth state: UNCHALLENGED
09:26:58.688 [main] DEBUG org.apache.http.impl.client.DefaultHttpClient - Attempt 1 to execute request
09:26:58.688 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Sending request: POST /api/auth/login HTTP/1.1
09:26:58.689 [main] DEBUG org.apache.http.wire -  >> "POST /api/auth/login HTTP/1.1[\r][\n]"
09:26:58.690 [main] DEBUG org.apache.http.wire -  >> "Accept: */*[\r][\n]"
09:26:58.690 [main] DEBUG org.apache.http.wire -  >> "Content-Type: text/plain; charset=ISO-8859-1[\r][\n]"
09:26:58.690 [main] DEBUG org.apache.http.wire -  >> "Content-Length: 60[\r][\n]"
09:26:58.690 [main] DEBUG org.apache.http.wire -  >> "Host: localhost:9080[\r][\n]"
09:26:58.690 [main] DEBUG org.apache.http.wire -  >> "Connection: Keep-Alive[\r][\n]"
09:26:58.690 [main] DEBUG org.apache.http.wire -  >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_201)[\r][\n]"
09:26:58.690 [main] DEBUG org.apache.http.wire -  >> "Accept-Encoding: gzip,deflate[\r][\n]"
09:26:58.690 [main] DEBUG org.apache.http.wire -  >> "[\r][\n]"
09:26:58.690 [main] DEBUG org.apache.http.headers - >> POST /api/auth/login HTTP/1.1
09:26:58.691 [main] DEBUG org.apache.http.headers - >> Accept: */*
09:26:58.691 [main] DEBUG org.apache.http.headers - >> Content-Type: text/plain; charset=ISO-8859-1
09:26:58.691 [main] DEBUG org.apache.http.headers - >> Content-Length: 60
09:26:58.691 [main] DEBUG org.apache.http.headers - >> Host: localhost:9080
09:26:58.691 [main] DEBUG org.apache.http.headers - >> Connection: Keep-Alive
09:26:58.691 [main] DEBUG org.apache.http.headers - >> User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_201)
09:26:58.691 [main] DEBUG org.apache.http.headers - >> Accept-Encoding: gzip,deflate
09:26:58.691 [main] DEBUG org.apache.http.wire -  >> "{"password":"Password123","username":"test@test.io"}"
09:26:58.900 [main] DEBUG org.apache.http.wire -  << "HTTP/1.1 200 [\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "Set-Cookie: accessKey=eyJeyJhbGciOiJIUzhbGciOieyJhbGciOiJIUzJIUzUxMeyJhbGciOiJIUziJ9.eyJzdWIiOiJMDQxODg5NyIsInNjbhbnNlbG1AYmlubmluZG1AYmlubmluZ2VyLm;Max-Age=899;path=/;HttpOnly[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "Set-Cookie: accessToken=eUzUxMinNeyJhbGciOiJIUzjbhbnNlbG1AYmlubmliOiJMDQxODg5NyIsInNjbhbnIUzUxMiJ9.ey;Max-Age=899;path=/[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "Access-Control-Allow-Credentials: true[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "X-Content-Type-Options: nosniff[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "X-XSS-Protection: 1; mode=block[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "Pragma: no-cache[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "Expires: 0[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "X-Frame-Options: DENY[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "Content-Length: 57[\r][\n]"
09:26:58.902 [main] DEBUG org.apache.http.wire -  << "Date: Tue, 14 Jan 2020 08:26:58 GMT[\r][\n]"
09:26:58.903 [main] DEBUG org.apache.http.wire -  << "[\r][\n]"
09:26:58.903 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Receiving response: HTTP/1.1 200 
09:26:58.903 [main] DEBUG org.apache.http.headers - << HTTP/1.1 200 
09:26:58.903 [main] DEBUG org.apache.http.headers - << Set-Cookie: accessKey=EC6D5DC71B7FA3B5814AE13E804F8518A37D44DF6F5EAE45EFE6C4A051A9;Max-Age=899;path=/;HttpOnly
09:26:58.903 [main] DEBUG org.apache.http.headers - << Set-Cookie: accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbnNlbG1AYmlubmluZ2VyLmlvIiwianRpIjoiMTU3ODk5MDQxODg5NyIsInNjb3BlcyI6WyJST0xFX0tVTkRFIl0sImt1bmRlbm5yIjoiMTAwMTgzMjk3IiwidXNlcklkIjoiNCIsInVzZXJuYW1lIjoiYW5zZWxtQGJpbm5pbmdlci5pbyIsInZvcm5hbWUiOiJMb3JlbnoiLCJuYWNobmFtZSI6IkRlbW1lbCIsImFjY2Vzc0tleSI6Ijk3OTczNTdBRUU0QkNDOEQ3Q0RBNDQzMDZCMDhGNUI5NEVEMkJBRkVFQ0VBM0ExMzM4M0JGOEYzRjEyNEQ4NEYiLCJsYXN0TG9nZ2VkSW5BdCI6MTU3ODk5MDIwNDAwMCwiaXNzIjoiZGllYmF5ZXJpc2NoZSIsImlhdCI6MTU3ODk5MDQxOCwiZXhwIjoxNTc4OTkxMzE4fQ.P5IpBqhkbd3vPaY7Ao_200irJMlz9LdgUYue7diyK60JdK24P-5W9KaBjfZwtoh10MRA0FYJjgsxkbpXGqHFdQ;Max-Age=899;path=/
09:26:58.903 [main] DEBUG org.apache.http.headers - << Access-Control-Allow-Credentials: true
09:26:58.903 [main] DEBUG org.apache.http.headers - << X-Content-Type-Options: nosniff
09:26:58.903 [main] DEBUG org.apache.http.headers - << X-XSS-Protection: 1; mode=block
09:26:58.903 [main] DEBUG org.apache.http.headers - << Cache-Control: no-cache, no-store, max-age=0, must-revalidate
09:26:58.903 [main] DEBUG org.apache.http.headers - << Pragma: no-cache
09:26:58.903 [main] DEBUG org.apache.http.headers - << Expires: 0
09:26:58.903 [main] DEBUG org.apache.http.headers - << X-Frame-Options: DENY
09:26:58.904 [main] DEBUG org.apache.http.headers - << Content-Length: 57
09:26:58.904 [main] DEBUG org.apache.http.headers - << Date: Tue, 14 Jan 2020 08:26:58 GMT
09:26:58.908 [main] DEBUG org.apache.http.impl.client.DefaultHttpClient - Connection can be kept alive indefinitely
09:26:58.947 [main] DEBUG io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder - Parsing response as: application/octet-stream
09:26:58.947 [main] DEBUG io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder - Parsed data to instance of: class org.apache.http.conn.EofSensorInputStream
09:26:59.139 [main] DEBUG org.apache.http.wire -  << "{"success":true}"
09:26:59.139 [main] DEBUG org.apache.http.impl.conn.BasicClientConnectionManager - Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@2bc426f0
09:26:59.139 [main] DEBUG org.apache.http.impl.conn.BasicClientConnectionManager - Connection can be kept alive indefinitely
09:26:59.556 [main] DEBUG net.thucydides.core.steps.StepInterceptor - STEP DONE: Login user
09:26:59.624 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - 
        __    _____ _____ ____ _____   ____   _    ____  ____  _____ ____  
  _     \ \  |_   _| ____/ ___|_   _| |  _ \ / \  / ___|/ ___|| ____|  _ \ 
 (_)_____| |   | | |  _| \___ \ | |   | |_) / _ \ \___ \\___ \|  _| | | | |
  _|_____| |   | | | |___ ___) || |   |  __/ ___ \ ___) |___) | |___| |_| |
 (_)     | |   |_| |_____|____/ |_|   |_| /_/   \_\____/|____/|_____|____/ 
        /_/                                                                

TEST PASSED: Test user login
----------------------------------------------------------------------------
09:26:59.632 [main] DEBUG net.thucydides.core.reports.ReportService - Reporting formats: [JSON, HTML]
09:26:59.717 [main] DEBUG net.thucydides.core.reports.ReportService - Reporting formats: [JSON, HTML]
09:26:59.729 [main] DEBUG net.thucydides.core.reports.ReportService - Generating reports for 1 test outcomes using: net.thucydides.core.reports.json.JSONTestOutcomeReporter@28757abd
09:26:59.731 [pool-1-thread-1] DEBUG net.thucydides.core.reports.ReportService - Processing test outcome User api test:testUserLogin
09:26:59.731 [pool-1-thread-1] DEBUG net.thucydides.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@28757abd: Generating report for test outcome: User api test:testUserLogin
09:26:59.740 [pool-1-thread-1] DEBUG net.thucydides.core.reports.json.JSONTestOutcomeReporter - Generating JSON report for Test user login to file C:\Users\user\Desktop\bapp\backend\target\site\serenity\d03f3a40f0a744a170ab803f3710fff3ca140bd3f114e3205f873c1ed69717b7.json (using temp file C:\Users\user\Desktop\bapp\\-backend\target\site\serenity\d03f3a40f0a744a170ab803f3710fff3ca140bd3f114e3205f873c1ed69717b7.json9cf44bf3-dda7-4f89-9cff-07d5b5841f4c)
09:26:59.780 [pool-1-thread-1] DEBUG net.thucydides.core.reports.ReportService - Processing test outcome User api test:testUserLogin done
09:26:59.780 [main] DEBUG net.thucydides.core.reports.ReportService - Shutting down executor service
09:26:59.780 [main] DEBUG net.thucydides.core.reports.ReportService - Reports generated in: 51 ms
09:26:59.780 [main] DEBUG net.thucydides.core.reports.ReportService - Generating reports for 1 test outcomes using: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@3d0cac1f
09:26:59.781 [pool-2-thread-1] DEBUG net.thucydides.core.reports.ReportService - Processing test outcome User api test:testUserLogin
09:26:59.781 [pool-2-thread-1] DEBUG net.thucydides.core.reports.ReportService - net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@3d0cac1f: Generating report for test outcome: User api test:testUserLogin
09:26:59.781 [pool-2-thread-1] DEBUG net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - GENERATE TEST OUTCOME REPORT FOR testUserLogin in d03f3a40f0a744a170ab803f3710fff3ca140bd3f114e3205f873c1ed69717b7
09:26:59.792 [pool-2-thread-1] DEBUG net.thucydides.core.requirements.RequirementsTagProvider -  found:[]
09:26:59.800 [pool-2-thread-1] DEBUG net.thucydides.core.requirements.RequirementsTagProvider -  found:[]
09:26:59.901 [pool-2-thread-1] DEBUG net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - GENERATING HTML REPORT FOR User api test:testUserLogin in d03f3a40f0a744a170ab803f3710fff3ca140bd3f114e3205f873c1ed69717b7.html in directory target\site\serenity  
09:26:59.906 [pool-2-thread-1] DEBUG net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - Generating report in d03f3a40f0a744a170ab803f3710fff3ca140bd3f114e3205f873c1ed69717b7.html
09:26:59.913 [pool-2-thread-1] DEBUG freemarker.cache - Couldn't find template in cache for "freemarker/default.ftl"("en_GB", UTF-8, parsed); will try to load it.
09:26:59.914 [pool-2-thread-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("freemarker/default_en_GB.ftl"): Not found
09:26:59.916 [pool-2-thread-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("freemarker/default_en.ftl"): Not found
09:26:59.917 [pool-2-thread-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("freemarker/default.ftl"): Found
09:26:59.917 [pool-2-thread-1] DEBUG freemarker.cache - Loading template for "freemarker/default.ftl"("en_GB", UTF-8, parsed) from "jar:file:/C:/Users/user/.m2/repository/net/serenity-bdd/serenity-report-resources/2.0.91/serenity-report-resources-2.0.91.jar!/freemarker/default.ftl"
09:27:00.081 [main] DEBUG net.thucydides.core.reports.ReportService - Shutting down executor service
net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:204)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:181)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReportsFor(SerenityRunner.java:401)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReports(SerenityRunner.java:296)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:249)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@3d0cac1f
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:201)
	... 10 more
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@3d0cac1f
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:241)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to merge template: Parsing error in template
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:39)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:139)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:125)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	... 6 more
Caused by: net.thucydides.core.reports.templates.TemplateMergeException: Parsing error in template
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.<init>(FreemarkerReportTemplate.java:27)
	at net.thucydides.core.reports.templates.FreeMarkerTemplateManager.getTemplateFrom(FreeMarkerTemplateManager.java:32)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:36)
	... 9 more
Caused by: freemarker.core.ParseException: Syntax error in template "freemarker/default.ftl" in line 509, column 98:
The left hand operand of ?index must be a loop variable, but there's no loop variable in scope with this name: recordedData
	at freemarker.core.FMParser.checkLoopVariableBuiltInLHO(FMParser.java:513)
	at freemarker.core.FMParser.BuiltIn(FMParser.java:1183)
	at freemarker.core.FMParser.AddSubExpression(FMParser.java:1101)
	at freemarker.core.FMParser.PrimaryExpression(FMParser.java:593)
	at freemarker.core.FMParser.UnaryExpression(FMParser.java:639)
	at freemarker.core.FMParser.MultiplicativeExpression(FMParser.java:754)
	at freemarker.core.FMParser.AdditiveExpression(FMParser.java:706)
	at freemarker.core.FMParser.RangeExpression(FMParser.java:886)
	at freemarker.core.FMParser.RelationalExpression(FMParser.java:834)
	at freemarker.core.FMParser.EqualityExpression(FMParser.java:797)
	at freemarker.core.FMParser.AndExpression(FMParser.java:953)
	at freemarker.core.FMParser.OrExpression(FMParser.java:975)
	at freemarker.core.FMParser.Expression(FMParser.java:534)
	at freemarker.core.FMParser.StringOutput(FMParser.java:1508)
	at freemarker.core.FMParser.StaticTextAndInterpolations(FMParser.java:4242)
	at freemarker.core.StringLiteral.parseValue(StringLiteral.java:70)
	at freemarker.core.FMParser.StringLiteral(FMParser.java:1388)
	at freemarker.core.FMParser.PrimaryExpression(FMParser.java:557)
	at freemarker.core.FMParser.UnaryExpression(FMParser.java:639)
	at freemarker.core.FMParser.MultiplicativeExpression(FMParser.java:754)
	at freemarker.core.FMParser.AdditiveExpression(FMParser.java:706)
	at freemarker.core.FMParser.RangeExpression(FMParser.java:886)
	at freemarker.core.FMParser.RelationalExpression(FMParser.java:834)
	at freemarker.core.FMParser.EqualityExpression(FMParser.java:797)
	at freemarker.core.FMParser.AndExpression(FMParser.java:953)
	at freemarker.core.FMParser.OrExpression(FMParser.java:975)
	at freemarker.core.FMParser.Expression(FMParser.java:534)
	at freemarker.core.FMParser.Assign(FMParser.java:2212)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:3339)
	at freemarker.core.FMParser.MixedContentElements(FMParser.java:3697)
	at freemarker.core.FMParser.List(FMParser.java:1731)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:3329)
	at freemarker.core.FMParser.MixedContentElements(FMParser.java:3697)
	at freemarker.core.FMParser.If(FMParser.java:1611)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:3325)
	at freemarker.core.FMParser.MixedContentElements(FMParser.java:3697)
	at freemarker.core.FMParser.Macro(FMParser.java:2630)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:3352)
	at freemarker.core.FMParser.MixedContentElements(FMParser.java:3697)
	at freemarker.core.FMParser.Root(FMParser.java:4280)
	at freemarker.template.Template.<init>(Template.java:254)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:548)
	at freemarker.cache.TemplateCache.getTemplateInternal(TemplateCache.java:438)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:291)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2438)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2287)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.<init>(FreemarkerReportTemplate.java:25)
	... 11 more

Process finished with exit code -2

```

**Comment by amirduran** [comment]
@wakaleo any idea what is wrong here?

**Comment by wakaleo** [comment]
Not really, it's weird; the Freemarker code at that line seems fine. Can you provide a sample project that reproduces the issue?

**Comment by amirduran** [comment]
The problem was in spring dependency that messed up all dependencies in my project.

**Comment by krishnapemmaraju** [comment]
5:46:16.496 [pool-1-thread-1] DEBUG n.t.core.reports.ReportService - Processing test outcome Invoke Met Office DataPoint API For forecast data feeds:Get forecast feeds for hourly and daily from the 'sitelist' endpoint
15:46:16.496 [pool-1-thread-1] DEBUG n.t.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@25ea068e: Generating report for test outcome: Invoke Met Office DataPoint API For forecast data feeds:Get forecast feeds for hourly and daily from the 'sitelist' endpoint
15:46:16.496 [pool-1-thread-2] DEBUG n.t.core.reports.ReportService - Processing test outcome Invoke Met Office DataPoint API For forecast data feeds:Get Forecast feeds for specific LocationID
15:46:16.496 [pool-1-thread-2] DEBUG n.t.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@25ea068e: Generating report for test outcome: Invoke Met Office DataPoint API For forecast data feeds:Get Forecast feeds for specific LocationID
15:46:16.513 [pool-1-thread-1] DEBUG n.t.c.r.json.JSONTestOu

@wakaleo  - is there any way to disable this log
