### ISSUE TITLE
Selenium test can't be started

### ISSUE THREAD

**Issue by amirduran** [serenity-bdd/serenity-core#1918]
In my project I want to run selenium tests. 
Here is a simple selenium test that I wrote: 

```
@RunWith(SerenityRunner.class)
public class GoogleUITest{
    @Managed
    WebDriver driver;

    @Test
    public void testGoogle() {
        driver.get("http://www.google.com");
        driver.findElement(By.name("q")).sendKeys("firefly", Keys.ENTER);
        new WebDriverWait(driver,5).until(titleContains("firefly - Google"));
        assertThat(driver.getTitle()).contains("firefly - Google");
    }
}
```

When I start this test, then I get the following error: 
```
java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/internal/Locatable

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:766)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:683)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:181)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:661)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:617)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:603)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:932)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:291)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:222)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:938)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:47)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:24)
	at net.serenitybdd.junit.runners.SerenityRunner.<init>(SerenityRunner.java:89)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:36)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.interactions.internal.Locatable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 63 more

```

I found similar error in internet and this seems to be a version conflict. Here is my `pom.xml` :

```
<properties>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	<java.version>1.8</java.version>
	<maven.compiler.source>1.8</maven.compiler.source>
	<maven.compiler.target>1.8</maven.compiler.target>
	<spring.version>1.4.2.RELEASE</spring.version>
	<serenity.version>2.0.91</serenity.version>
	<serenity.maven.version>2.0.91</serenity.maven.version>
</properties>

.....

<dependency>
	<groupId>net.serenity-bdd</groupId>
	<artifactId>serenity-core</artifactId>
	<version>${serenity.version}</version>
	<scope>test</scope>
</dependency>

<dependency>
	<groupId>net.serenity-bdd</groupId>
	<artifactId>serenity-spring</artifactId>
	<version>${serenity.version}</version>
	<scope>test</scope>
</dependency>

<dependency>
	<groupId>io.rest-assured</groupId>
	<artifactId>spring-mock-mvc</artifactId>
	<version>4.1.2</version>
	<scope>test</scope>
</dependency>
```
So current version of `serenity-core` is `2.0.91` which uses  version `3.141.59` of `selenium-java` and `selenium-api` and everything should be working fine but I get error above. 

Here is my dependency tree when I search for selenium where is obviously visible that only serenity uses selenium as dependency. What is problem here?

![image](https://user-images.githubusercontent.com/6552083/72434038-f568d180-379a-11ea-9fbd-21a04ba7c447.png)

**Comment by wakaleo** [comment]
It looks like there are some odd things going on in your dependencies - you have a mix of Selenium 3 and Selenium 2 jars. Do a dependency analysis and make sure you are only pulling in Selenium 3.141.59 libraries.

**Comment by amirduran** [comment]
@wakaleo I have no idea why version 2.53.1 is mixed with version 3. In any case, after manual import of every dependency it worked.

**Comment by wakaleo** [comment]
See https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html - importing the dependencies manually will work but will be hard to maintain.

**Comment by amirduran** [comment]
For records: 
`Spring Boot Starter Parent` was making problems. The version I have is: `1.4.2.RELEASE` which requires selenium version: `2.53.1`
