### ISSUE TITLE
not able to read serenity.conf

### ISSUE THREAD

**Issue by sunnysachdeva99** [serenity-bdd/serenity-core#1936]
I am getting null value while reading a property from serenity.conf which is placed under src/test/resources

 mvn clean  -Dtags=SMOKE -Denvironment=dev verify serenity:aggregate
Hooks.java
```
private EnvironmentVariables env;
@Before
    public void beforeScenario() {
        
        env= SystemEnvironmentVariables.createEnvironmentVariables();
        String baseUri= EnvironmentSpecificConfiguration.from(env).getProperty("scangun.uri");
        System.out.println(baseUri);
}
```

serenity.conf
```
environments {
      dev {
            scangun.uri="http://scangun-dev.com"
            scangun.path="/api/v2/stores"
      }
      qa {
            scangun.uri="http://scangun-qa.com"
            scangun.path="/api/v2/stores"
      }
      prod {
            scangun.uri="http://scangun-prod.com"
            scangun.path="/api/v2/stores"
      }
}
```
pom.xml

```
<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>2.0.91</serenity.version>
		<serenity.maven.version>2.0.91</serenity.maven.version>
		<serenity.cucumber.version>1.0.30</serenity.cucumber.version>
		<cucumber.version>4.8.0</cucumber.version>
		<encoding>UTF-8</encoding>
	</properties>

	<!-- <repositories> -->
	<!-- <repository> -->
	<!-- <snapshots> -->
	<!-- <enabled>false</enabled> -->
	<!-- </snapshots> -->
	<!-- <id>central</id> -->
	<!-- <name>bintray</name> -->
	<!-- <url>http://jcenter.bintray.com</url> -->
	<!-- </repository> -->
	<!-- </repositories> -->
	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray-plugins</name>
			<url>https://jcenter.bintray.com</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.0.13</version>
		</dependency>
		<!-- - To use Cucumber 4, exclude the old Cucumber 2 cucumber-core dependency
			from the serenity-core dependency - and include the Cucumber 4 cucumber-java
			and cucumber-junit dependencies. -->
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber4</artifactId>
			<version>${serenity.cucumber.version}</version>
			<scope>test</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/net.serenity-bdd/serenity-rest-assured -->
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>org.assertj</groupId>-->
<!--			<artifactId>assertj-core</artifactId>-->
<!--			<version>3.6.2</version>-->
<!--			<scope>test</scope>-->
<!--		</dependency>-->
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
			<scope>test</scope>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.10</version>
			<scope>provided</scope>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all -->
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>2.5.8</version>
			<type>pom</type>
		</dependency>

		<!-- https://mvnrepository.com/artifact/io.rest-assured/json-path -->
		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>2.4.0</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.6</version>
		</dependency>

	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.1</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.22.1</version>
				<configuration>
					<includes>
						<include>**/automation/**/*.java</include>
						<include>**/automation/*.java</include>
					</includes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<configuration>
					<tags>${tags}</tags>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

error

TEST STARTED: User check health and version of store
-------------------------------------------------------------------(store-health-feature;user-check-health-and-version-of-store)
16:51:35.996 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM /Users/admin/Documents/_Work/Sephora/code/automation-scangunAPI/serenity.properties 
16:51:36.003 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM /Users/admin/Documents/_Work/Sephora/code/automation-scangunAPI/serenity.properties 
16:51:36.004 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - LOADING LOCAL PROPERTIES FROM /Users/admin/Documents/_Work/Sephora/code/automation-scangunAPI/serenity.properties 
16:51:36.004 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - serenity.project.name=ScangunAPIAutomation
16:51:36.005 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - environments.dev.scangun.uri=http://scangun-dev.com
16:51:36.005 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - environments.qa.scangun.path=/api/v2/stores
16:51:36.005 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - environments.dev.scangun.path=/api/v2/stores
16:51:36.005 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - environments.qa.scangun.uri=http://scangun-prod.com
16:51:36.006 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - environments.prod.scangun.uri=http://scangun-qa.com
16:51:36.006 [main] DEBUG n.t.c.u.PropertiesFileLocalPreferences - environments.prod.scangun.path=/api/v2/stores
      net.serenitybdd.core.environment.UndefinedEnvironmentVariableException: Environment 'scangun.uri' property undefined for environment 'null'
        at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.lambda$getProperty$6(EnvironmentSpecificConfiguration.java:118)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.getProperty(EnvironmentSpecificConfiguration.java:114)
        at com.automation.scangun.bdd.steps.Hooks.beforeScenario(Hooks.java:22)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cucumber.runtime.Utils$1.call(Utils.java:26)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:20)
        at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:65)
        at cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)
        at cucumber.runner.TestStep.executeStep(TestStep.java:65)
        at cucumber.runner.TestStep.run(TestStep.java:50)
        at cucumber.runner.TestCase.run(TestCase.java:42)
        at cucumber.runner.Runner.runPickle(Runner.java:50)
        at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
        at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:68)
        at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:23)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:221)
        at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:66)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:251)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:82)
        at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:70)
        at org.testng.TestRunner$1.run(TestRunner.java:570)
        at org.testng.TestRunner.runJUnitWorkers(TestRunner.java:717)
        at org.testng.TestRunner.privateRunJUnit(TestRunner.java:601)
        at org.testng.TestRunner.run(TestRunner.java:502)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
        at org.testng.TestNG.runSuites(TestNG.java:1028)
        at org.testng.TestNG.run(TestNG.java:996)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:198)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

**Comment by wakaleo** [comment]
I can't reproduce this with the code you have posted. The code is fine, though you don't need `env= SystemEnvironmentVariables.createEnvironmentVariables()`. Are you sure you correctly typed "environment" on the command line?

**Comment by sunnysachdeva99** [comment]
it worked after I commented
env= SystemEnvironmentVariables.createEnvironmentVariables();

one question, is it possible to set env parameter somewhere in Junit config, this help in debugging code
