### ISSUE TITLE
Unable to intergrate Jira with Serenity BDD

### ISSUE THREAD

**Issue by quyennt44** [serenity-bdd/serenity-core#1974]
Hi,
Could you have a look at my issue. I'm trying to update status of my issue on Jira but nothing happen. I've search for similar issue but no luck.
- This is the content in pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>auto.teko</groupId>
	<artifactId>auto-teko</artifactId>
	<version>1.0-SNAPSHOT</version>
	<!-- <packaging>jar</packaging> -->

	<name>Teko Automation Framework</name>

	<properties>
		<maven.test.skip>false</maven.test.skip>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<serenity.version>2.0.82</serenity.version>
		<serenity.cucumber.version>1.9.45</serenity.cucumber.version>
		<selenium.version>3.141.59</selenium.version>
		<log4j.version>1.2.17</log4j.version>
		<webdriver.driver>firefox</webdriver.driver>
		<surefire.maven.plugin.version>3.0.0-M3</surefire.maven.plugin.version>
		<thread.number>4</thread.number>
	</properties>

	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>https://jcenter.bintray.com</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray-plugins</name>
			<url>https://jcenter.bintray.com</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>22.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/io.appium/java-client -->
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>7.2.0</version>
			<exclusions>
				<exclusion>
					<groupId>cglib</groupId>
					<artifactId>cglib</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>cglib</groupId>
			<artifactId>cglib</artifactId>
			<version>3.2.5</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/ru.yandex.qatools.ashot/ashot -->
		<dependency>
			<groupId>ru.yandex.qatools.ashot</groupId>
			<artifactId>ashot</artifactId>
			<version>1.5.4</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.5</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.hamcrest/hamcrest-all -->
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>${selenium.version}</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>${selenium.version}</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-driver</artifactId>
			<version>${selenium.version}</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-support</artifactId>
			<version>${selenium.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.7</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>1.7.0</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.8-dmr</version>
		</dependency>
		<!-- read write file -->
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
		</dependency>
		<!-- testlink java api -->
		<dependency>
			<groupId>br.eti.kinoshita</groupId>
			<artifactId>testlink-java-api</artifactId>
			<version>1.9.13-0</version>
		</dependency>
		<dependency>
			<groupId>com.github.mkolisnyk</groupId>
			<artifactId>cucumber-reports</artifactId>
			<version>1.0.6</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/net.serenity-bdd/serenity-junit -->
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>1.0.23</version>
		</dependency>
		<dependency>
			<groupId>commons-httpclient</groupId>
			<artifactId>commons-httpclient</artifactId>
			<version>3.1</version>
		</dependency>
		<!-- log4j -->
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>

		<dependency>
			<groupId>com.ullink.slack</groupId>
			<artifactId>simpleslackapi</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.tyrus.bundles</groupId>
			<artifactId>tyrus-standalone-client</artifactId>
			<version>1.8.3</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.threeten/threetenbp -->
		<dependency>
			<groupId>org.threeten</groupId>
			<artifactId>threetenbp</artifactId>
			<version>1.3.6</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.poi/poi -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.17</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.17</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.apache.poi/poi-scratchpad -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-scratchpad</artifactId>
			<version>3.17</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml-schemas -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml-schemas</artifactId>
			<version>3.17</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.apache.poi/ooxml-schemas -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>ooxml-schemas</artifactId>
			<version>1.3</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.apache.poi/poi-examples -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-examples</artifactId>
			<version>3.17</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.apache.poi/poi-excelant -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-excelant</artifactId>
			<version>3.17</version>
		</dependency>
		
		<!-- Added by QuyenNT Start-->
		<!-- This plugin supports to intergrate with Jira -->
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-plugin</artifactId>
            <version>1.11.0</version>
        </dependency>
               <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jira-requirements-provider</artifactId>
            <version>1.11.0</version>
        </dependency>	
        <!-- Added by QuyenNT End-->
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>${surefire.maven.plugin.version}</version>
				<configuration>
					<argLine>-Xmx512m</argLine>
					<systemPropertyVariables>
						<webdriver.driver>${webdriver.driver}</webdriver.driver>
						<runOrder>alphabetical</runOrder>
					</systemPropertyVariables>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.apache.maven.surefire</groupId>
						<artifactId>surefire-junit47</artifactId>
						<version>${surefire.maven.plugin.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<executions>
					<execution>
						<phase>verify</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
				
				<!-- Added by QuyenNT Start-->
				<!-- This plugin supports to intergrate with Jira -->
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-jira-requirements-provider</artifactId>
                        <version>1.11.0</version>
                    </dependency>
                </dependencies>
                <!-- Added by QuyenNT End-->
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${surefire.maven.plugin.version}</version>
				<configuration>
					<forkCount>${thread.number}</forkCount>
					<reuseForks>false</reuseForks>
					<useFile>false</useFile>
					<includes>
						<include>**/TestRunner*.class</include>
					</includes>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

- This is configuration in serenity.properties file:
![serenity properties](https://user-images.githubusercontent.com/43987470/75437653-2a1a9c00-5989-11ea-8ac5-370b5ce0599e.PNG)
-This is issue mapping in feature file:
![Feature](https://user-images.githubusercontent.com/43987470/75437841-782f9f80-5989-11ea-9cf4-fc6fc3496777.PNG)
- This is content in workflow file:
![workflowGroovy](https://user-images.githubusercontent.com/43987470/75437773-5afad100-5989-11ea-943e-a9820228e938.PNG)
- This is workflow in Jira:
![JiraWorkflow](https://user-images.githubusercontent.com/43987470/75437799-6817c000-5989-11ea-99d7-e0f04ccf4921.PNG)
- This is the issue on Jira:
![JiraIssue](https://user-images.githubusercontent.com/43987470/75437896-8d0c3300-5989-11ea-8625-4d688f92362f.PNG)
- And this is the console log when I run my testcase:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< auto.teko:auto-teko >-------------------------
[INFO] Building Teko Automation Framework 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ auto-teko ---
[INFO] Deleting D:\workspace\java\att\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ auto-teko ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 11 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ auto-teko ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 43 source files to D:\workspace\java\att\target\classes
[INFO] /D:/workspace/java/att/src/main/java/auto/teko/coreactions/CoreActionForm.java: Some input files use unchecked or unsafe operations.
[INFO] /D:/workspace/java/att/src/main/java/auto/teko/coreactions/CoreActionForm.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ auto-teko ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 67 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ auto-teko ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 32 source files to D:\workspace\java\att\target\test-classes
[INFO] /D:/workspace/java/att/src/test/java/auto/teko/catalog/object/Test.java: D:\workspace\java\att\src\test\java\auto\teko\catalog\object\Test.java uses unchecked or unsafe operations.
[INFO] /D:/workspace/java/att/src/test/java/auto/teko/catalog/object/Test.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ auto-teko ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running auto.teko.runner.TestRunner
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Teko/.m2/repository/org/slf4j/slf4j-simple/1.7.7/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Teko/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   /
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|

 News and tutorials at http://www.serenity-bdd.info
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport
 Learn Serenity BDD online at http://serenity-dojo.com
-------------------------------------------------------------------------------------

[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Adding new attribute set
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Adding new brands
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Updating existing brands
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Create new test case for adding master category
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Adding new product
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Create variants of product
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Adding new sale channel
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/


TEST STARTED: TC01 Create A Master Category With Valid Input
-------------------------------------------------------------------(create-new-test-case-for-adding-master-category;tc01-create-a-master-category-with-valid-input)
log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.BasicClientConnectionManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
27/02/2020 17:35:53 INFO [ApiBaseSteps][get_response_status_code] Actual result: 200
27/02/2020 17:35:53 INFO [ApiBaseSteps][get_response_status_code] Expected result: 200
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener -
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/
          \_\

TEST FAILED: TC01 Create A Master Category With Valid Input
--------------------------------------------------------------------------
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP And The value ignore case of response status node 'code' should be 'SUCCESS2'
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener -

Failed scenarios:
src/test/resources/catalog/api/master_category/MasterCategoryCreation.feature:7 # TC01 Create A Master Category With Valid Input

1 Scenarios (1 failed)
9 Steps (1 failed, 3 skipped, 5 passed)
0m7.101s

java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at auto.teko.api.ApiUtils.responseNodeValueShouldBe(ApiUtils.java:193)
        at auto.teko.scenariosteps.ApiSteps.check_response_content(ApiSteps.java:163)
        at ?.The value ignore case of response status node 'code' should be 'SUCCESS2'(src/test/resources/catalog/api/master_category/MasterCategoryCreation.feature:13)

[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.708 s - in auto.teko.runner.TestRunner
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ auto-teko ---
[INFO] Building jar: D:\workspace\java\att\target\auto-teko-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M3:integration-test (default) @ auto-teko ---
[INFO]
[INFO] --- serenity-maven-plugin:2.0.82:aggregate (serenity-reports) @ auto-teko ---
[INFO] current_project.base.dir: D:\workspace\java\att
[INFO] Generating test results for 1 tests
[INFO] Loading requirements from tag providers :[net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider@61bd6c16]
[INFO] LOADED REQUIREMENTS:
NO REQUIREMENTS FOUND
[INFO] 0 requirements loaded after 1.4 secs
[INFO] 0 related requirements found after 1.4 secs
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 1.6 secs
[INFO] Configured report threads: 20
[INFO] Test results for 1 tests generated in 3.1 secs
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M3:verify (default) @ auto-teko ---
[INFO]
[INFO] --- serenity-maven-plugin:2.0.82:check (default) @ auto-teko ---
[INFO] Checking Serenity test results
[INFO] ----------------------
[INFO] SERENITY TEST OUTCOMES
[INFO] ----------------------
[INFO]   - Tests executed: 1
[INFO]   - Tests passed: 0
[INFO]   - Tests failed: 1
[INFO]   - Tests with errors: 0
[INFO]   - Tests pending: 0
[INFO]   - Tests compromised: 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.835 s
[INFO] Finished at: 2020-02-27T17:36:06+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.0.82:check (default) on project auto-teko: A failure occurred in the Serenity tests -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
Plz have a look. Thx.

**Comment by pindukuri** [comment]
The same output iam also getting. one way integration working but 2 way is not working please do the needful.

Pom: <?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.ostk.serenity.demo</groupId>
  <artifactId>com.ostk.serenity.demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>


 

  <properties>
  <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>
<dependencies>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jbehave</artifactId>
            <version>1.20.0</version>
            <scope>test</scope>
        </dependency>

 <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>2.1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jbehave</groupId>
            <artifactId>jbehave-core</artifactId>
            <version>4.1</version>
            <scope>test</scope>
        </dependency>
   
        

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.8</version>
            <scope>test</scope>
        </dependency>
  
 
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>




  
  
   <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.0</version>

                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>1.2.2</version>

                <executions>
                    <execution>
                        <id>serenity-reports</id>

                        <phase>post-integration-test</phase>

                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            <dependencies>
                   <dependency>
    <groupId>net.serenity-bdd</groupId>
    <artifactId>serenity-jira-plugin</artifactId>
    <version>1.1.2-rc.1</version>
</dependency>

   

</dependencies> 
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.19.1</version>

                <configuration>
                    <includes>
                        <include>**/MySampleSerenityStories.java</include>
                    </includes>
                </configuration>

                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

Console output:


[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ com.ostk.serenity.demo ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /Users/pindukuri/eclipse-workspace1/com.ostk.serenity.demo/target/com.ostk.serenity.demo-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (default) @ com.ostk.serenity.demo ---
[INFO] 
[INFO] --- serenity-maven-plugin:1.2.2:aggregate (serenity-reports) @ com.ostk.serenity.demo ---

[INFO] current_project.base.dir: /Users/pindukuri/eclipse-workspace1/com.ostk.serenity.demo
Generating HTML Story Reports from /Users/pindukuri/eclipse-workspace1/com.ostk.serenity.demo/target/site/serenity
Generating HTML Story Reports to /Users/pindukuri/eclipse-workspace1/com.ostk.serenity.demo/target/site/serenity
Generating HTML Outcome Reports: false
[INFO] Generating test results for 2 tests
[INFO] 0 requirements loaded after 20 ms
[INFO] 0 related requirements found after 20 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 71 ms
[INFO] Finished generating test results for 2 tests after 878 ms
GENERATE CUSTOM REPORTS
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ com.ostk.serenity.demo ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ com.ostk.serenity.demo ---
[INFO] Installing /Users/pindukuri/eclipse-workspace1/com.ostk.serenity.demo/target/com.ostk.serenity.demo-0.0.1-SNAPSHOT.jar to /Users/pindukuri/.m2/repository/com/ostk/serenity/demo/com.ostk.serenity.demo/0.0.1-SNAPSHOT/com.ostk.serenity.demo-0.0.1-SNAPSHOT.jar
[INFO] Installing /Users/pindukuri/eclipse-workspace1/com.ostk.serenity.demo/pom.xml to /Users/pindukuri/.m2/repository/com/ostk/serenity/demo/com.ostk.serenity.demo/0.0.1-SNAPSHOT/com.ostk.serenity.demo-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.244 s
[INFO] Finished at: 2020-03-01T19:55:30-07:00
[INFO] ------------------------------------------------------------------------

serenity.properties:

jira.url=
#jira.project=
jira.username=
jira.password=
serenity.public.url=
serenity.jira.workflow.active=true
serenity.jira.workflow=jira-workflow.groovy

workflow.groovy:

when 'In Progress', {
    'success' should: 'Bug Found'
    
}




Please have a look and update thanks.
