### ISSUE TITLE
Failed to generate configuration report

### ISSUE THREAD

**Issue by shrikish** [serenity-bdd/serenity-core#1978]
Report isn't generating properly. 
I cant figure out if there is something wrong with different version being used for serenity libraries? or some other issue?

Below jar's are being used -
serenity-jbehave-1.46.0.jar, serenity-core-2.0.48.jar, serenity-report-resources-2.0.48.jar, serenity-model-2.0.48.jar, serenity-reports-2.0.48.jar, serenity-stats-2.0.48.jar,
freemarker-2.3.23.jar

<groupId>net.serenity-bdd.maven.plugins</groupId>
 <artifactId>serenity-maven-plugin</artifactId>
<version>2.0.48</version>

**Getting below exception** -

net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:203)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:180)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
	at net.serenitybdd.jbehave.SerenityReporter.generateReports(SerenityReporter.java:514)
	at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:499)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:51)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:136)
	at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:452)
	at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:130)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)
	at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:94)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at org.jbehave.core.junit.JUnitStories.run(JUnitStories.java:21)
	at org.jbehave.core.embedder.Embedder.runAsEmbeddables(Embedder.java:131)
	at org.jbehave.mojo.RunStoriesAsEmbeddables.execute(RunStoriesAsEmbeddables.java:18)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@33dfad1b
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:200)
	... 36 more
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@33dfad1b
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:240)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to merge template: Parsing error in template
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:39)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:138)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:124)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:238)
	... 6 more
Caused by: net.thucydides.core.reports.templates.TemplateMergeException: Parsing error in template
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.<init>(FreemarkerReportTemplate.java:27)
	at net.thucydides.core.reports.templates.FreeMarkerTemplateManager.getTemplateFrom(FreeMarkerTemplateManager.java:32)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:36)
	... 9 more
Caused by: freemarker.core.ParseException: Syntax error in template "freemarker/default.ftl" in line 464, column 94:
The left hand operand of ?index must be a loop variable, but there's no loop variable in scope with this name: recordedData
	at freemarker.core.FMParser.checkLoopVariableBuiltInLHO(FMParser.java:326)
	at freemarker.core.FMParser.BuiltIn(FMParser.java:961)
	at freemarker.core.FMParser.AddSubExpression(FMParser.java:881)
	at freemarker.core.FMParser.PrimaryExpression(FMParser.java:400)
	at freemarker.core.FMParser.UnaryExpression(FMParser.java:446)
	at freemarker.core.FMParser.MultiplicativeExpression(FMParser.java:559)
	at freemarker.core.FMParser.AdditiveExpression(FMParser.java:512)
	at freemarker.core.FMParser.RangeExpression(FMParser.java:682)
	at freemarker.core.FMParser.RelationalExpression(FMParser.java:635)
	at freemarker.core.FMParser.EqualityExpression(FMParser.java:600)
	at freemarker.core.FMParser.AndExpression(FMParser.java:745)
	at freemarker.core.FMParser.OrExpression(FMParser.java:768)
	at freemarker.core.FMParser.Expression(FMParser.java:348)
	at freemarker.core.FMParser.StringOutput(FMParser.java:1240)
	at freemarker.core.FMParser.FreeMarkerText(FMParser.java:3167)
	at freemarker.core.StringLiteral.parseValue(StringLiteral.java:58)
	at freemarker.core.FMParser.StringLiteral(FMParser.java:1125)
	at freemarker.core.FMParser.PrimaryExpression(FMParser.java:370)
	at freemarker.core.FMParser.UnaryExpression(FMParser.java:446)
	at freemarker.core.FMParser.MultiplicativeExpression(FMParser.java:559)
	at freemarker.core.FMParser.AdditiveExpression(FMParser.java:512)
	at freemarker.core.FMParser.RangeExpression(FMParser.java:682)
	at freemarker.core.FMParser.RelationalExpression(FMParser.java:635)
	at freemarker.core.FMParser.EqualityExpression(FMParser.java:600)
	at freemarker.core.FMParser.AndExpression(FMParser.java:745)
	at freemarker.core.FMParser.OrExpression(FMParser.java:768)
	at freemarker.core.FMParser.Expression(FMParser.java:348)
	at freemarker.core.FMParser.Assign(FMParser.java:1882)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2835)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3081)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.List(FMParser.java:1437)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2827)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3081)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.If(FMParser.java:1338)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2824)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3081)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.Macro(FMParser.java:2269)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2845)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3081)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.Root(FMParser.java:3432)
	at freemarker.template.Template.<init>(Template.java:208)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:495)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:409)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:261)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1786)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1646)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.<init>(FreemarkerReportTemplate.java:25)
	... 11 more
[INFO] 

[INFO] --- serenity-maven-plugin:2.0.48:aggregate (serenity-reports) @ SPEA ---

**Comment by wakaleo** [comment]
Have you tried with the latest versions?

**Comment by shrikish** [comment]
After using latest version's i.e.

serenity-jbehave-1.46.0.jar

serenity-core-2.0.52.jar, serenity-report-resources-2.0.52.jar, serenity-model-2.0.52.jar, serenity-reports-2.0.52.jar, serenity-stats-2.0.52.jar, serenity-junit-2.0.52.jar, serenity-screenplay-2.0.52.jar, cloning-1.9.10.jar, serenity-screenplay-webdriver-2.0.52.jar

I'm still getting same exception

net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:203)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:180)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:127)
	at net.serenitybdd.jbehave.SerenityReporter.generateReports(SerenityReporter.java:514)
	at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:499)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:51)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:136)
	at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:452)
	at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:130)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)
	at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:94)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at org.jbehave.core.junit.JUnitStories.run(JUnitStories.java:21)
	at org.jbehave.core.embedder.Embedder.runAsEmbeddables(Embedder.java:131)
	at org.jbehave.mojo.RunStoriesAsEmbeddables.execute(RunStoriesAsEmbeddables.java:18)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@1355e378
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:200)
	... 36 more
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@1355e378
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:240)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to merge template: Parsing error in template
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:39)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:138)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:124)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:238)
	... 6 more
Caused by: net.thucydides.core.reports.templates.TemplateMergeException: Parsing error in template
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.<init>(FreemarkerReportTemplate.java:27)
	at net.thucydides.core.reports.templates.FreeMarkerTemplateManager.getTemplateFrom(FreeMarkerTemplateManager.java:32)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:36)
	... 9 more
Caused by: freemarker.core.ParseException: Syntax error in template "freemarker/default.ftl" in line 469, column 94:
The left hand operand of ?index must be a loop variable, but there's no loop variable in scope with this name: recordedData
	at freemarker.core.FMParser.checkLoopVariableBuiltInLHO(FMParser.java:326)
	at freemarker.core.FMParser.BuiltIn(FMParser.java:961)
	at freemarker.core.FMParser.AddSubExpression(FMParser.java:881)
	at freemarker.core.FMParser.PrimaryExpression(FMParser.java:400)
	at freemarker.core.FMParser.UnaryExpression(FMParser.java:446)
	at freemarker.core.FMParser.MultiplicativeExpression(FMParser.java:559)
	at freemarker.core.FMParser.AdditiveExpression(FMParser.java:512)
	at freemarker.core.FMParser.RangeExpression(FMParser.java:682)
	at freemarker.core.FMParser.RelationalExpression(FMParser.java:635)
	at freemarker.core.FMParser.EqualityExpression(FMParser.java:600)
	at freemarker.core.FMParser.AndExpression(FMParser.java:745)
	at freemarker.core.FMParser.OrExpression(FMParser.java:768)
	at freemarker.core.FMParser.Expression(FMParser.java:348)
	at freemarker.core.FMParser.StringOutput(FMParser.java:1240)
	at freemarker.core.FMParser.FreeMarkerText(FMParser.java:3167)
	at freemarker.core.StringLiteral.parseValue(StringLiteral.java:58)
	at freemarker.core.FMParser.StringLiteral(FMParser.java:1125)
	at freemarker.core.FMParser.PrimaryExpression(FMParser.java:370)
	at freemarker.core.FMParser.UnaryExpression(FMParser.java:446)
	at freemarker.core.FMParser.MultiplicativeExpression(FMParser.java:559)
	at freemarker.core.FMParser.AdditiveExpression(FMParser.java:512)
	at freemarker.core.FMParser.RangeExpression(FMParser.java:682)
	at freemarker.core.FMParser.RelationalExpression(FMParser.java:635)
	at freemarker.core.FMParser.EqualityExpression(FMParser.java:600)
	at freemarker.core.FMParser.AndExpression(FMParser.java:745)
	at freemarker.core.FMParser.OrExpression(FMParser.java:768)
	at freemarker.core.FMParser.Expression(FMParser.java:348)
	at freemarker.core.FMParser.Assign(FMParser.java:1882)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2835)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3081)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.List(FMParser.java:1437)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2827)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3081)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.If(FMParser.java:1338)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2824)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3081)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.Macro(FMParser.java:2269)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2845)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3081)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.Root(FMParser.java:3432)
	at freemarker.template.Template.<init>(Template.java:208)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:495)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:409)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:261)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1786)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1646)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.<init>(FreemarkerReportTemplate.java:25)
	... 11 more
[INFO] 
[INFO] --- serenity-maven-plugin:2.0.52:aggregate (serenity-reports) @ SPEA ---

**Comment by wakaleo** [comment]
The latest version of serenity-core etc  lots 2.1.8

**Comment by shrikish** [comment]
It worked like charm. Thanks a lot for quick response.
