### ISSUE TITLE
The page object class com.myUse.Pages.LoginPage looks dodgy: Failed to instantiate page

### ISSUE THREAD

**Issue by mansiKulkarni39** [serenity-bdd/serenity-core#1986]
@wakaleo 
I am using appium(version 1.16.0) to automate my native apk. But after execution, it is starting appium server and launching my apk and then without clicking any locators it is forcing to stop application and server will get stop.  
Please find below details which I am providing in my project

**Serenity.Properties**

webdriver.driver= appium
appium.automationName=uiautomator2
appium.platformName=Android
appium.platformVersion=10.0
appium.deviceName=emulator-5554
appium.app=/Users/mansi/Downloads/development-testing-release.apk
appium.appPackage=#### (Correct package providing)
appium.appActivity=#### (Correct activity providing)
appium.newCommandTimeout=1000

**POM.xml**
       <serenity.version>2.0.91</serenity.version>
        <serenity.maven.version>2.0.91</serenity.maven.version>
        <serenity.cucumber.version>1.9.50</serenity.cucumber.version>

**LoginPage class**
public class LoginPage extends MobilePageObject {

    public LoginPage(WebDriver driver) {
        super(driver);
    }

    @AndroidFindBy(id = "dev:id/bSignIn")
    public WebElementFacade signinButton;

**MobilePageObject class**
public class MobilePageObject extends PageObject {
    public MobilePageObject(final WebDriver driver) {
        super(driver, new Predicate<PageObject>() {
            public boolean apply(PageObject page) {
                PageFactory
                        .initElements(new AppiumFieldDecorator(((WebDriverFacade) page.getDriver()).getProxiedDriver(),
                                page.getImplicitWaitTimeout()), page);
                return true;
            }
        });
    }
}

**step definition class**
public class SubmitLeaveScenarios {
    LoginPage loginPage;

    @Managed(driver="Appium")
    WebDriver driver;

    @Given("^I am login to DWP Mobile APP$")
    public void i_am_login_to_DWP_Mobile_APP() {
       loginPage.signinButton.click();
       loginPage.loginApplication();
    }

**Error getting**
net.thucydides.core.pages.WrongPageError: The page object class com.myUse.Pages.LoginPage looks dodgy:
Failed to instantiate page (java.lang.IllegalArgumentException: Can not set net.serenitybdd.core.pages.WebElementFacade field com.myUse.Pages.LoginPage.signinButton to io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c)
	at net.thucydides.core.pages.Pages.thisPageObjectLooksDodgy(Pages.java:296)
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:220)
	at net.thucydides.core.pages.Pages.getPage(Pages.java:91)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.serenitybdd.core.Serenity.injectDependenciesInto(Serenity.java:63)
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:104)
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:68)
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:51)
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:41)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	at ✽.I am login to DWP Mobile APP(src/test/resources/features/SubmitLeave.feature:5)

**Comment by wakaleo** [comment]
Have you asked on Gitter if anyone has any thoughts on this?

**Comment by mansiKulkarni39** [comment]
Haven't I will check it then.

**Comment by mansiKulkarni39** [comment]
I am waiting for quick response, actually it is quite urgent. Can you please help me on that?

**Comment by wakaleo** [comment]
Try using a WebElement instead of a WebElementFacade

**Comment by mansiKulkarni39** [comment]
Thank you, it is working now. Changed WebElementFacade to WebElement. Also I have removed MobilePageObject and just extended to PageObject. (which was fixed in 1.9.0) as per https://github.com/serenity-bdd/serenity-core/issues/1152.
