### ISSUE TITLE
Manual test reporting as PENDING status

### ISSUE THREAD

**Issue by ibrahimkhaleel** [serenity-bdd/serenity-core#2013]
My feature file is declared as below scenarios with manual tags, Both test tags are reporting as a PENDING status. 

As you can see, one should report PASS and another should be FAIL per each respective manual tag. Please assist, if I have missed anything

Feature File:

  @manual
  @manual-result:passed
  Scenario: Unregistered user attempts to login

  @manual
  @manual-result:failed
  Scenario: Unregistered user prompted to register

Attached below screenshot:
![image](https://user-images.githubusercontent.com/25445287/77868317-b3e0b200-7232-11ea-94b2-e129df59fdc3.png)

**Comment by wakaleo** [comment]
Unable to reproduce this with 2.2.0:

```

  @color:green
  @salads
  @snacks
  @manual
  Scenario: Grow Granny Smith apples
    Given I have a field
    When I plant some Granny Smith apples trees
    Then some apples should grow
    And the apples should be green

  @color:red
  @snacks
  @Manual
  @manual-result:failed
  Scenario: Grow Red Delicious apples
    Given I have a field
    When I plant some Red Delicious apples trees
    Then some apples should grow
    And the apples should be red

  @color:red
  @snacks
  @Manual
  @manual-result:passed
  Scenario: Grow Juicy Red Delicious apples
    Given I have a field
    When I plant some Red Delicious apples trees
    Then some apples should grow
    And the apples should be red
```

![image](https://user-images.githubusercontent.com/55986/77888541-56655900-7264-11ea-886c-63c146d895ba.png)

![image](https://user-images.githubusercontent.com/55986/77888568-611fee00-7264-11ea-88d3-be569669c633.png)

**Comment by ibrahimkhaleel** [comment]
I think I am using an older version. Please check below screen from pom.xml
![image](https://user-images.githubusercontent.com/25445287/77967333-d0d1bf80-72dc-11ea-99d0-809c9d1a3875.png)
Could you please assist me how to upgrade all these versions to latest?
Thank you

**Comment by wakaleo** [comment]
Copy the dependency setup from serenity-cucumber-starter

**Comment by ibrahimkhaleel** [comment]
@wakaleo Hi, my current project set up is base on serenity-cucumber4-starter. As you suggested I have tried upgrading the new versions from serenity-cucumber-starter's dependencies, but it is throwing errors. One Sample below:


 at io.cucumber.core.runner.PickleStepDefinitionMatch.arityMismatch(PickleStepDefinitionMatch.java:134)
        at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:42)
        at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
        at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
        at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:46)
        at io.cucumber.core.runner.TestCase.run(TestCase.java:51)
        at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
        at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
        at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
        at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:227)
        at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:54)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
        at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
        at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:362)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:254)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by wakaleo** [comment]
Copy the dependency setup *exactly* from https://github.com/serenity-bdd/serenity-cucumber-starter

**Comment by ibrahimkhaleel** [comment]
@wakaleo I think I have found the issue with my reported issue. The reason my below manual scenarios were reported as Pending because they did not have the steps. 

@Manual
@manual-result:passed
Scenario: Unregistered user attempts to login

@Manual
@manual-result:failed
Scenario: Unregistered user prompted to register

After adding your gherkins to my feature I have noticed the difference. Please confirm if my assumption with the solution is correct.

Further to follow up I have two questions if you could provide any solution.
Q1. For all manual test scenarios, I have following unidentified steps errors with recommended snippets. Please suggest if this can be suppressed when scenario is tagged as a Manual.

![image](https://user-images.githubusercontent.com/25445287/78172987-e7982380-744e-11ea-8448-f5287e3a1fac.png)
![image](https://user-images.githubusercontent.com/25445287/78173225-48bff700-744f-11ea-91e7-3f4ca4ce503f.png)

Q2. My serenity.properties has an entry like - serenity.logging=QUIET
But I am still getting logs at the console (Please check below screenshot)
![image](https://user-images.githubusercontent.com/25445287/78173598-de5b8680-744f-11ea-90f2-53cc841b7915.png)

Thank you.

**Comment by wakaleo** [comment]
This is related to Cucumber, not Serenity - how is your runner class configured? If you have the "strict" attribute set to true, missing steps will be treated as errors, otherwise they are not. 

The `serenity.logging` property is for test logging, not for the banner text. You can control the banner using the `serenity.console.banner` property (set to "normal" for a smaller title)

**Comment by ibrahimkhaleel** [comment]
Hi @wakaleo, I have changed the Cucumber options to strict = false. It is not failing for undefined steps. Could you please help me with these issues - 

Issue1: I could not exclude Manual tests from the report when I set the property serenity.report.show.manual.tests=false 


Issue2: Could you please let me know the property set up if I wan to completely omit below banner text and Serenity Link Sources:
![image](https://user-images.githubusercontent.com/25445287/78178658-e5869280-7457-11ea-9027-da760424d45d.png)

Following are my current entries from serenity.property file:
serenity.logging=QUIET
serenity.console.headings=NORMAL
serenity.console.banner=NORMAL

**Comment by wakaleo** [comment]
`serenity.report.show.manual.tests` just excludes the manual test count from the summary reports; if you want to exclude manual tests, you should use Cucumber filters for this. But that kind of defeats the purpose of including them in your feature files (why include them if you don't want them to appear in the reports?)

Regarding issue 2, this is not supported.

**Comment by ibrahimkhaleel** [comment]
Thank you @wakaleo , that makes sense.
