### ISSUE TITLE
JIRA comments update - not for all JIRA Issue Types

### ISSUE THREAD

**Issue by coumarine** [serenity-bdd/serenity-core#2031]
Below are the issues, when tried to update comment for a JIRA ticket using Serenity:
1. Update comments for, Issue Types ‘Epic’ or ‘Testing Task’ only. Other types E.g. Story, Bug Story etc., does not work
2. For  ‘Epic’ or ‘Testing Task’, once comment is updated 1st time, does not update on next attempts i.e. it neither overwrites not appends the comment

Note: I have tried with different JIRA credentials, include one with JIRA Admin access

During both these issues, getting below error:
--------------------------------------------------------------------------------------------------
09:04:45.148 [pool-3-thread-1] WARN  n.t.c.r.RequirementsTagProvider - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
    java.lang.IllegalArgumentException: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:266)
        at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
        at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
        at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementFor(BaseRequirementsService.java:48)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:171)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:107)
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
        at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:239)
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:255)
        ... 13 common frames omitted
    Caused by: java.lang.NullPointerException: null
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToComment(JerseyJiraClient.java:301)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.commentsIn(JerseyJiraClient.java:291)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToIssueSummary(JerseyJiraClient.java:280)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByKey(JerseyJiraClient.java:248)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:17)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:8)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:235)
        ... 14 common frames omitted
    09:04:45.877 [pool-3-thread-1] WARN  n.t.c.r.RequirementsTagProvider - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
    java.lang.IllegalArgumentException: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:266)
        at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
        at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
        at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:78)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:201)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:189)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:107)
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
        at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:239)
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:255)
        ... 14 common frames omitted
    Caused by: java.lang.NullPointerException: null
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToComment(JerseyJiraClient.java:301)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.commentsIn(JerseyJiraClient.java:291)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToIssueSummary(JerseyJiraClient.java:280)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByKey(JerseyJiraClient.java:248)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:17)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:8)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:235)
        ... 15 common frames omitted
    09:04:46.611 [pool-3-thread-1] WARN  n.t.c.r.RequirementsTagProvider - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
    java.lang.IllegalArgumentException: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:266)
        at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
        at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
        at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:78)
        at net.thucydides.core.tags.BreadcrumbTagFilter.getRequirementBreadcrumbsFrom(BreadcrumbTagFilter.java:51)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:202)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:189)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:107)
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
        at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:239)
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:255)
        ... 15 common frames omitted
    Caused by: java.lang.NullPointerException: null
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToComment(JerseyJiraClient.java:301)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.commentsIn(JerseyJiraClient.java:291)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToIssueSummary(JerseyJiraClient.java:280)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByKey(JerseyJiraClient.java:248)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:17)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:8)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:235)
        ... 16 common frames omitted
    09:04:47.654 [pool-3-thread-1] WARN  n.t.c.r.RequirementsTagProvider - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
    java.lang.IllegalArgumentException: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:266)
        at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
        at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
        at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementFor(BaseRequirementsService.java:48)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:171)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:229)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:110)
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
        at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:239)
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:255)
        ... 14 common frames omitted
    Caused by: java.lang.NullPointerException: null
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToComment(JerseyJiraClient.java:301)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.commentsIn(JerseyJiraClient.java:291)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToIssueSummary(JerseyJiraClient.java:280)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByKey(JerseyJiraClient.java:248)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:17)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:8)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:235)
        ... 15 common frames omitted
    09:04:48.271 [pool-3-thread-1] WARN  n.t.c.r.RequirementsTagProvider - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
    java.lang.IllegalArgumentException: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:266)
        at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
        at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
        at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:78)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:201)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:189)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:229)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:110)
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
        at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:239)
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:255)
        ... 15 common frames omitted
    Caused by: java.lang.NullPointerException: null
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToComment(JerseyJiraClient.java:301)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.commentsIn(JerseyJiraClient.java:291)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToIssueSummary(JerseyJiraClient.java:280)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByKey(JerseyJiraClient.java:248)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:17)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:8)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:235)
        ... 16 common frames omitted
    09:04:48.901 [pool-3-thread-1] WARN  n.t.c.r.RequirementsTagProvider - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
    java.lang.IllegalArgumentException: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:266)
        at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
        at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
        at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:78)
        at net.thucydides.core.tags.BreadcrumbTagFilter.getRequirementBreadcrumbsFrom(BreadcrumbTagFilter.java:51)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:202)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:189)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:229)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:110)
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
        at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:239)
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:255)
        ... 16 common frames omitted
    Caused by: java.lang.NullPointerException: null
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToComment(JerseyJiraClient.java:301)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.commentsIn(JerseyJiraClient.java:291)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToIssueSummary(JerseyJiraClient.java:280)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByKey(JerseyJiraClient.java:248)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:17)
        at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:8)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:235)
        ... 17 common frames omitted
    09:04:49.766 [Test worker] INFO  n.s.plugins.jira.JiraUpdater - Updating comments for issue PRJ-5322
    09:04:49.767 [Test worker] INFO  n.s.plugins.jira.JiraUpdater - WIKI Rendering activated: true

com.automation.DynamicTestSuite0 > classMethod FAILED
    java.lang.NullPointerException
        at net.serenitybdd.plugins.jira.domain.Author.fromJsonString(Author.java:29)
        at net.serenitybdd.plugins.jira.domain.IssueComment.fromJsonString(IssueComment.java:214)
        at net.serenitybdd.plugins.jira.client.JerseyJiraClient.getComments(JerseyJiraClient.java:783)
        at net.serenitybdd.plugins.jira.service.JiraIssueTracker.getCommentsFor(JiraIssueTracker.java:93)
        at net.serenitybdd.plugins.jira.JiraUpdater.newOrUpdatedCommentFor(JiraUpdater.java:128)
        at net.serenitybdd.plugins.jira.JiraUpdater.updateIssue(JiraUpdater.java:93)
        at net.serenitybdd.plugins.jira.JiraUpdater.lambda$updateIssueStatus$0(JiraUpdater.java:75)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at net.serenitybdd.plugins.jira.JiraUpdater.updateIssueStatus(JiraUpdater.java:74)
        at net.serenitybdd.plugins.jira.JiraStepListener.testSuiteFinished(JiraStepListener.java:89)
        at net.thucydides.core.steps.StepEventBus.testSuiteFinished(StepEventBus.java:612)
        at cucumber.runtime.formatter.SerenityReporter.lambda$assureTestSuiteFinished$16(SerenityReporter.java:772)
        at java.util.Optional.ifPresent(Optional.java:159)
        at cucumber.runtime.formatter.SerenityReporter.assureTestSuiteFinished(SerenityReporter.java:770)
        at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:357)
        at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:150)
        at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
        at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)
        at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)
        at net.serenitybdd.cucumber.CucumberWithSerenity$1.evaluate(CucumberWithSerenity.java:203)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ricardorlg** [comment]
This error is related to new Jira versions where the Author entity is different, It Is a bug in Serenity Jira. It happens because before serenity makes the comment he fetches the comments in the Jira issue and gets the authors, in new versions The Author has a different structure.

**Comment by ricardorlg** [comment]
I will upload a fix to the plugin in the next days.

**Comment by coumarine** [comment]
> I will upload a fix to the plugin in the next days.
Sure, thanks

**Comment by coumarine** [comment]
> This error is related to new Jira versions where the Author entity is different, It Is a bug in Serenity Jira. It happens because before serenity makes the comment he fetches the comments in the Jira issue and gets the authors, in new versions The Author has a different structure.

@ricardorlg Meanwhile, please advice which version of JIRA would work without this issue.

**Comment by coumarine** [comment]
@ricardorlg Meanwhile, please advice which version of JIRA would work without this issue.

**Comment by coumarine** [comment]
Team, please can anybody help me. If I can get the version of JIRA, which would work without this issue, we shall revert to that JIRA version. Thanks!

**Comment by ricardorlg-aval** [comment]
The PR with the fix was merged yesterday.

**Comment by coumarine** [comment]
Thanks much. However I am experiencing same error. This time, I am not able to update the comments even first time.

JIRA ticket's issue type is - Testing Task

JIRA Plugins used:
 jira: "net.serenity-bdd:serenity-jira-plugin:1.12.0"
 jirarequirements: 'net.serenity-bdd:serenity-jira-requirements-provider:1.12.0'

**Comment by ricardorlg-aval** [comment]
could you provide the stack trace.

**Comment by wakaleo** [comment]
The JIRA APIs have changed so the JIRA module is undergoing some updates. This is not related to serenity core though

**Comment by ricardorlg-aval** [comment]
@coumarine open this issue in serenity Jira module, so I can track it a nd review.

**Comment by coumarine** [comment]
> @coumarine open this issue in serenity Jira module, so I can track it a nd review.

What is the link please @ricardorlg-aval

**Comment by ricardorlg-aval** [comment]
https://github.com/serenity-bdd/serenity-jira

**Comment by coumarine** [comment]
> https://github.com/serenity-bdd/serenity-jira

@ricardorlg-aval created new issue https://github.com/serenity-bdd/serenity-jira/issues/105

**Comment by ricardorlg-aval** [comment]
https://github.com/serenity-bdd/serenity-jira/pull/106 will fix this.
