### ISSUE TITLE
Issue with mvn dependency of "serenity-core" and "serenity-cucumber4"

### ISSUE THREAD

**Issue by sfarhan25** [serenity-bdd/serenity-core#2042]
Hi,

I am trying to use **serenity-cucumber4** with Serenity Core in my project.
Following is the mvn dependency I have added for the same.

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>2.2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-context</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber4</artifactId>
            <version>2.1.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>2.2.1</version>
        </dependency>

Have updated the required code for the same as the class packages had changes from Cucumber 2 --> Cucumber 4.
And the maven build was successful with no compilation errors.

But at runtime, I get the following error:

`java.lang.NoClassDefFoundError: cucumber/runtime/io/ResourceLoader
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: cucumber.runtime.io.ResourceLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more`

`mvn dependency:tree` too was successful.

Could you please help with the mvn dependencies and the usage of serenity-cucumber4 with the latest serenity-core ?
Is there something I am doing incorrectly ? Please help me with the same.

**Comment by wakaleo** [comment]
Serenity 2.2.x only supports Cucumber 5 - see https://github.com/serenity-bdd/serenity-cucumber-starter

**Comment by sfarhan25** [comment]
@wakaleo Thank you very much for your prompt response. 
Works like a charm for Cucumber 5 👍 

Also, if I want to use Cucumber 4, is the serenity-core **2.1.10** the latest version I can use ?
As, the further version of Serenity looks to have cucumber 5.

Please provide your inputs.

**Comment by wakaleo** [comment]
I think 2.1.1 is probably the latest one compatible with Cucumber 4. I would recommend moving to the latest versions

**Comment by sfarhan25** [comment]
Thanks @wakaleo. That helps 👍
