### ISSUE TITLE
When executing test cases with more test data (above 10 )in scenario outline facing below exception.

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#2071]
When executing test cases with more test data (above 10 )in scenario outline facing below exception.
Using serenity-rest-assured-2.0.83 , io.rest.assured:rest-assured-3.3.0
java.lang.RuntimeException: Some exception during recording fields
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:52)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
 at io.restassured.filter.Filter$filter$0.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.FilterContext$next.call(Unknown Source)
 at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1749)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
 at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
 at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
 at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
 at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1755)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
 at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
 at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
 at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
 at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:175)
 at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.executeCall(RequestSpecificationDecorated.java:293)
 at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.execute(RequestSpecificationDecorated.java:253)
 at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:105)
 at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:28)
 at apis.RetrieveDepositInfoAPI.getVerificationType(RetrieveDepositInfoAPI.java:40)
 at apis.RetrieveDepositInfoAPI$ByteBuddy$vVKCuBv4.getVerificationType$accessor$gtCSuXDf(Unknown Source)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at net.thucydides.core.steps.BaseMethodRunner.invokeMethod(BaseMethodRunner.java:18)
 at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:18)
 at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:377)
 at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:162)
 at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:74)
 at apis.RetrieveDepositInfoAPI$ByteBuddy$vVKCuBv4.getVerificationType(Unknown Source)
 at steps.ControlTableSteps.user_tries_to_get_the_verification_types(ControlTableSteps.java:21)
 at ?.user tries to get the verification types(src/serenity/resources/features/control_table/control_table.feature:28)
Caused by: java.net.SocketException: Connection reset
 at java.net.SocketInputStream.read(SocketInputStream.java:210)
 at java.net.SocketInputStream.read(SocketInputStream.java:141)
 at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)
 at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
 at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:276)
 at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
 at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
 at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
 at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:294)
 at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)
 at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:207)
 at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
 at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
 at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:679)
 at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:481)
 at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
 at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
 at io.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:2146)
 at io.restassured.internal.http.HTTPBuilder.post(HTTPBuilder.java:349)
 at io.restassured.internal.http.HTTPBuilder$post$2.call(Unknown Source)
 at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1274)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
 at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
 at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:151)
 at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)
 at io.restassured.filter.Filter$filter$0.call(Unknown Source)
 at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:122)
 at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
 at io.restassured.filter.Filter$filter.call(Unknown Source)
 at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
 at io.restassured.filter.Filter$filter$0.call(Unknown Source)
 at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
 at io.restassured.filter.FilterContext$next.call(Unknown Source)
 at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1749)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
 at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
 at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
 at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
 at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1755)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
 at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
 at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:47)
 at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
 at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:175)
 at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.executeCall(RequestSpecificationDecorated.java:293)
 at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.execute(RequestSpecificationDecorated.java:253)
 at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:105)
 at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:28)
 at apis.RetrieveDepositInfoAPI.getVerificationType(RetrieveDepositInfoAPI.java:40)
 at apis.RetrieveDepositInfoAPI$ByteBuddy$vVKCuBv4.getVerificationType$accessor$gtCSuXDf(Unknown Source)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at net.thucydides.core.steps.BaseMethodRunner.invokeMethod(BaseMethodRunner.java:18)
 at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:18)
 at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:377)
 at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:162)
 at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:74)
 at apis.RetrieveDepositInfoAPI$ByteBuddy$vVKCuBv4.getVerificationType(Unknown Source)
 at steps.ControlTableSteps.user_tries_to_get_the_verification_types(ControlTableSteps.java:21)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at cucumber.runtime.Utils$1.call(Utils.java:26)
 at cucumber.runtime.Timeout.timeout(Timeout.java:16)
 at cucumber.runtime.Utils.invoke(Utils.java:20)
 at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:49)
 at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
 at cucumber.runner.TestStep.executeStep(TestStep.java:63)
 at cucumber.runner.TestStep.run(TestStep.java:49)
 at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
 at cucumber.runner.TestCase.run(TestCase.java:44)
 at cucumber.runner.Runner.runPickle(Runner.java:40)
 at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
 at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
 at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
 at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
 at net.serenitybdd.cucumber.CucumberWithSerenity.runChild(CucumberWithSerenity.java:193)
 at net.serenitybdd.cucumber.CucumberWithSerenity.runChild(CucumberWithSerenity.java:64)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
 at net.serenitybdd.cucumber.CucumberWithSerenity$1.evaluate(CucumberWithSerenity.java:202)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
 at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
 at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)

**Comment by wakaleo** [comment]
I can't reproduce this, but it looks like an issue with the application under test: `Caused by: java.net.SocketException: Connection reset`
