### ISSUE TITLE
[pool-2-thread-1] WARN net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: Illegal char <:> at index 9: classpath

### ISSUE THREAD

**Issue by bharatrajs** [serenity-bdd/serenity-core#2121]
hi,

can you please check below error and i am using  
<serenity.version>2.2.7</serenity.version>		
 <serenity.maven.version>2.2.7</serenity.maven.version>	  
<serenity.cucumber.version>2.2.2</serenity.cucumber.version>       

ERROR:
[pool-2-thread-1] WARN net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: Illegal char <:> at index 9: classpath:com\projectps\project1\ui\view\dummyaddresssearch\dummyAddressSearch.feature
java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:com\projectps\project1\ui\view\dummyaddresssearch\dummyAddressSearch.feature
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2234)
	at net.thucydides.core.requirements.RootDirectory.getRelativePathOf(RootDirectory.java:360)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.requirementWithMatchingPath(FileSystemRequirementsTagProvider.java:378)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getParentRequirementOf(FileSystemRequirementsTagProvider.java:341)
	at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementFor(BaseRequirementsService.java:48)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:171)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:107)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[pool-2-thread-1] WARN net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: Illegal char <:> at index 9: classpath:com\projectps\project1\ui\view\dummyaddresssearch\dummyAddressSearch.feature
java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:com\projectps\project1\ui\view\dummyaddresssearch\dummyAddressSearch.feature
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2234)
	at net.thucydides.core.requirements.RootDirectory.getRelativePathOf(RootDirectory.java:360)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.requirementWithMatchingPath(FileSystemRequirementsTagProvider.java:378)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getParentRequirementOf(FileSystemRequirementsTagProvider.java:341)
	at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
	at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:78)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:201)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:189)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:107)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[pool-2-thread-1] WARN net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: Illegal char <:> at index 9: classpath:com\projectps\project1\ui\view\dummyaddresssearch\dummyAddressSearch.feature
java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:com\projectps\project1\ui\view\dummyaddresssearch\dummyAddressSearch.feature
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2234)
	at net.thucydides.core.requirements.RootDirectory.getRelativePathOf(RootDirectory.java:360)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.requirementWithMatchingPath(FileSystemRequirementsTagProvider.java:378)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getParentRequirementOf(FileSystemRequirementsTagProvider.java:341)
	at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
	at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:78)
	at net.thucydides.core.tags.BreadcrumbTagFilter.getRequirementBreadcrumbsFrom(BreadcrumbTagFilter.java:51)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:202)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:189)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:107)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cliviu** [comment]
hi @bharatrajs  , can you provide a small project to help us to reproduce your problem ?

**Comment by bharatrajs** [comment]
hi,
please check below dummy project
https://github.com/bharatrajs/cucumbertest

MyTest Run as junit test

**Comment by cliviu** [comment]
How are you running your project ?

**Comment by bharatrajs** [comment]
right click on  runner file MyTest and Run as junit test 
In case i need the serenity reports
clean test -Dtest=MyTest serenity:aggregate

**Comment by cliviu** [comment]
does the Exception come in both cases  ?

**Comment by cliviu** [comment]
And another question: which IDE are you using ?  I cannot reproduce it with IntelliJ on Windows ...

**Comment by wakaleo** [comment]
You should be putting the feature file in a sub directory under src/test/resources/features in order to represent your requirements hierarchy. Serenity cannot report on requirements correctly if if doesn’t know where the requirements root directory is.

**Comment by bharatrajs** [comment]
yes the exception comes in both cases
i am using eclipse
the feature file is under
src\test\resources\com\cucumbertest\ui\test\VerifyLayout.feature
is this path incorrect?

**Comment by wakaleo** [comment]
Feature files should be under src/test/resources/features in a directory structure that represents your requirements hierarchy.

**Comment by bharatrajs** [comment]
i have updated the feature directory structure

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features = "src/test/resources/features/", 
glue = {"com.cucumbertest.ui.test"})
public class MyTest {

}

the error has gone but now in the report i see same feature twice
please advice
[generated-test-sources.zip](https://github.com/serenity-bdd/serenity-core/files/4744589/generated-test-sources.zip)

**Comment by wakaleo** [comment]
Put your feature file in a sub directory underneath src/test/features

**Comment by bharatrajs** [comment]
it works but i need to add the features location path in every runner class
(i have a separate runner class for every module with same sub folder structure for feature file (under src/test/resources) and step definitions (under src/test/java) )
time being i will ignore the error as the reports are anyhow generated
thanks for the support
