### ISSUE TITLE
Disable w3c option of chromedriver V83 in Serenity

### ISSUE THREAD

**Issue by w2a** [serenity-bdd/serenity-core#2124]
While launching Android browser test with Appium in Java we give below in capabilites
capabilities.setCapability("appium:chromeOptions", ImmutableMap.of("w3c", false));

Just wanted to check how to provide the same in serenity.properties file

Tried this in serenity.conf but not working:

chrome {
    capabilities {
        chromeOptions {
            "w3c" = false
        }
    }

Any workaround to add in properties file.

Getting below exception:

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class io.appium.java_client.AppiumDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.serenitybdd.core.webdriver.RemoteDriver.of(RemoteDriver.java:13)
	at net.thucydides.core.webdriver.appium.AppiumConfiguration.getTargetPlatform(AppiumConfiguration.java:57)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:51)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:19)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:166)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:170)
	at net.thucydides.core.steps.PageObjectDependencyInjector.updatePageObject(PageObjectDependencyInjector.java:69)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:31)
	at net.serenitybdd.junit.runners.SerenityRunner.injectDriverInto(SerenityRunner.java:618)
	at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:593)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:463)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:438)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:45)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:242)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new **WebDriver instance of type class io.appium.java_client.AppiumDriver (unknown command: Cannot call non W3C standard command while in W3C mode**
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-1BDQC6B', ip: '192.168.137.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.google.android.apps.chr..., appPackage: com.android.chrome, browserName: Chrome, databaseEnabled: false, desired: {browserName: Chrome, deviceName: andriod, hub: http://127.0.0.1:4723/wd/hub, loggingPrefs: {}, platformName: android, platformVersion: 9.0}, deviceApiLevel: 28, deviceManufacturer: vivo, deviceModel: vivo 1818, deviceName: 8e006adb, deviceScreenDensity: 480, deviceScreenSize: 1080x2340, deviceUDID: 8e006adb, hub: http://127.0.0.1:4723/wd/hub, javascriptEnabled: true, locationContextEnabled: false, loggingPrefs: org.openqa.selenium.logging..., networkConnectionEnabled: true, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 9, statBarHeight: 84, takesScreenshot: true, viewportRect: {height: 2130, left: 0, top: 84, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 02985531-c547-4062-9cf2-37fa77d8cfae). See below for more details.
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:158)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	... 33 more
Caused by: org.openqa.selenium.UnsupportedCommandException: unknown command: Cannot call non W3C standard command while in W3C mode
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-1BDQC6B', ip: '192.168.137.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.google.android.apps.chr..., appPackage: com.android.chrome, browserName: Chrome, databaseEnabled: false, desired: {browserName: Chrome, deviceName: andriod, hub: http://127.0.0.1:4723/wd/hub, loggingPrefs: {}, platformName: android, platformVersion: 9.0}, deviceApiLevel: 28, deviceManufacturer: vivo, deviceModel: vivo 1818, deviceName: 8e006adb, deviceScreenDensity: 480, deviceScreenSize: 1080x2340, deviceUDID: 8e006adb, hub: http://127.0.0.1:4723/wd/hub, javascriptEnabled: true, locationContextEnabled: false, loggingPrefs: org.openqa.selenium.logging..., networkConnectionEnabled: true, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 9, statBarHeight: 84, takesScreenshot: true, viewportRect: {height: 2130, left: 0, top: 84, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 02985531-c547-4062-9cf2-37fa77d8cfae
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:45)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:42)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:59)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:68)
	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:49)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:91)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
	at net.serenitybdd.core.webdriver.driverproviders.AppiumDriverProvider.newDriverUsingExternalServer(AppiumDriverProvider.java:59)
	at net.serenitybdd.core.webdriver.driverproviders.AppiumDriverProvider.newInstance(AppiumDriverProvider.java:47)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:169)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:150)
	... 34 more

**Comment by ricardorlg-aval** [comment]
You can set the W3C property using https://serenity-bdd.github.io/theserenitybook/latest/extending-webdriver.html

**Comment by w2a** [comment]
That solves my issue, Thank you so much !!!

**Comment by lhuyz87** [comment]
> That solves my issue, Thank you so much !!!

Hello, how are you, sorry. I have the same problem, do you have an example of how you solved the problem?
