### ISSUE TITLE
Any solution from serenity to solve issue "The forked VM terminated without properly saying goodbye. VM crash or System.exit called?"?

### ISSUE THREAD

**Issue by kzokv** [serenity-bdd/serenity-core#2159]
Hello, it seems that serenity-bdd has some difficulties with using maven failsafe plugin as the following issues occur `The forked VM terminated without properly saying goodbye. VM crash or System.exit called?` and `Error occurred in starting fork, check output in log`  when the Jenkins job tries to run the test cases in parallel. 

See the details below:

From the failsafe-summary.xml, I got below error messages
```
<?xml version="1.0" encoding="UTF-8"?>
<failsafe-summary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/failsafe-summary.xsd" result="254" timeout="false">
    <completed>0</completed>
    <errors>0</errors>
    <failures>0</failures>
    <skipped>0</skipped>
    <failureMessage>org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /var/jenkins/workspace/OMS_Staging_Test/qa-auto &amp;&amp; /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /var/jenkins/workspace/OMS_Staging_Test/qa-auto/target/surefire/surefirebooter1239733677911095875.jar /var/jenkins/workspace/OMS_Staging_Test/qa-auto/target/surefire 2020-07-07T08-28-29_303-jvmRun4 surefire8852969510139337299tmp surefire_2883007098309838464tmp
Error occurred in starting fork, check output in log
Process Exit Code: 143
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:510)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:382)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:297)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /var/jenkins/workspace/OMS_Staging_Test/qa-auto &amp;&amp; /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /var/jenkins/workspace/OMS_Staging_Test/qa-auto/target/surefire/surefirebooter1239733677911095875.jar /var/jenkins/workspace/OMS_Staging_Test/qa-auto/target/surefire 2020-07-07T08-28-29_303-jvmRun4 surefire8852969510139337299tmp surefire_2883007098309838464tmp
Error occurred in starting fork, check output in log
Process Exit Code: 143
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:371)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:347)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
</failureMessage>
</failsafe-summary>

```

and below is my POM file
```
<project>
   <properties>
      <maven.failsafe.version>3.0.0-M3</maven.failsafe.version>
      <maven.surefire.version>3.0.0-M3</maven.surefire.version>
   </properties>
   <profiles>
      <profile>
         <id>remote_mt_forks</id>
         <build>
            <plugins>
               <plugin>
                  <artifactId>maven-failsafe-plugin</artifactId>
                  <configuration>
                     <systemPropertyVariables>
                        <serenity.fork.count>0${parallel.tests}</serenity.fork.count>
                        <serenity.fork.number>0${surefire.forkNumber}</serenity.fork.number>
                     </systemPropertyVariables>
                     <includes>
                        <include>${include.classes.multi.threads.useforks}</include>
                     </includes>
                     <threadCount>${parallel.tests}</threadCount>
                     <forkCount>${parallel.tests}</forkCount>
                  </configuration>
               </plugin>
            </plugins>
         </build>
      </profile>
      <profile>
         <id>remote_mt_noforks</id>
         <build>
            <plugins>
               <plugin>
                  <artifactId>maven-failsafe-plugin</artifactId>
                  <configuration>
                     <includes>
                        <include>${include.classes.multi.threads}</include>
                        <include>${include.claases.multi.threads.noforks}</include>
                     </includes>
                     <parallel>classes</parallel>
                     <threadCount>${parallel.tests}</threadCount>
                     <forkCount>${parallel.tests}</forkCount>
                  </configuration>
               </plugin>
            </plugins>
         </build>
      </profile>
      <profile>
         <id>aggregate_report</id>
         <build>
            <plugins>
               <plugin>
                  <groupId>net.serenity-bdd.maven.plugins</groupId>
                  <artifactId>serenity-maven-plugin</artifactId>
                  <version>${serenity.maven.version}</version>
                  <configuration>
                     <reports>single-page-html</reports>
                     <outputDirectory>${project.build.directory}/serenity-reports</outputDirectory>
                  </configuration>
                  <dependencies>
                     <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                     </dependency>
                  </dependencies>
                  <executions>
                     <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                           <goal>aggregate</goal>
                        </goals>
                     </execution>
                  </executions>
               </plugin>
            </plugins>
         </build>
      </profile>
   </profiles>
   <build>
      <plugins>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>${maven.surefire.version}</version>
            <configuration>
               <skip>true</skip>
            </configuration>
         </plugin>
         <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>${maven.failsafe.version}</version>
            <configuration>
               <!--VM crash-->
               <!--https://stackoverflow.com/a/33757854-->
               <!--see: https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class -->
               <argLine>-Xmx1024m -Xms1024m -XX:MaxPermSize=512m -Djdk.net.URLClassPath.disableClassPathURLCheck=true</argLine>
               <argLine>-Dfile.encoding=UTF-8</argLine>
               <systemPropertyVariables>
                  <webdriver.base.url>${webdriver.base.url}</webdriver.base.url>
               </systemPropertyVariables>
               <parallel>classes</parallel>
            </configuration>
            <executions>
               <execution>
                  <goals>
                     <goal>integration-test</goal>
                     <goal>verify</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.0</version>
            <configuration>
               <source>1.8</source>
               <target>1.8</target>
            </configuration>
         </plugin>
      </plugins>
   </build>
</project>
```
Note: I was referencing https://github.com/serenity-bdd/serenity-cucumber5-starter/blob/master/pom.xml to create my own.

After googling the error messages, I found below stackoverflow posts
https://stackoverflow.com/a/33757854, 
https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class and 
https://stackoverflow.com/questions/9320620/maven-surefire-plugin-error-occured-in-starting-fork-check-output-in-log

The folks suggested following solutions:

1. Add argLine `-Xmx1024m`, `-XX:MaxPermSize=512m` and `-Djdk.net.URLClassPath.disableClassPathURLCheck=true` in build node of `maven-surefire-plugin` :
  
> None of them worked

2. Use configuration `<useSystemClassLoader>false</useSystemClassLoader>` for `maven-surefire-plugin`:
 
> It didn't solve my issue either and I found out that the the same test got run x times for where  x is equal to the value of parallel.tests

3. Use `forkCount=0`:

> As far as I understand, we shouldn't specify forkCount=0 if serenity needs to run tests in parallel, it should always be the same as the value of parallel.tests

4. Use different failsafe versions:

> I tried `2.22.0`, `2.22.1`, `2.22.2`, `3.0.0-M3`, `3.0.0-M4` and `3.0.0-M5` but none of them worked...

Thus, I'm wondering if there's any solution to get my issue resolved?

**Comment by wakaleo** [comment]
I don't think this is related to the Serenity code.

**Comment by kzokv** [comment]
You are right. Sorry for bringing up this dumb question.
