### ISSUE TITLE
Failed to resolve a serialised class during report generation

### ISSUE THREAD

**Issue by vsrd13** [serenity-bdd/serenity-core#2169]
@wakaleo 

I am seeing the below issue while executing "mvn -X clean install -DskipITs" command on my "Serenity BDD Cucumber project. 

**Issue:** Failed to resolve a serialised class during report generation

<snip>
**[DEBUG] Failed to resolve a serialised class during report generation:** **C:\Users\****\git\*******\target\site\serenity\browserconfig.xml**
com.thoughtworks.xstream.mapper.CannotResolveClassException: browserconfig**
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:81)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
	at net.thucydides.core.reports.xml.XMLTestOutcomeReporter.loadReportFrom(XMLTestOutcomeReporter.java:121)
	at net.thucydides.core.reports.TestOutcomeLoader$TestOutcomeLoaderCallable.call(TestOutcomeLoader.java:102)
	at net.thucydides.core.reports.TestOutcomeLoader$TestOutcomeLoaderCallable.call(TestOutcomeLoader.java:90)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
<snip/>

**_Below are dependency versions which are using in my project._**

<serenity.version>2.2.9</serenity.version>
<serenity.maven.version>2.2.9</serenity.maven.version>
<serenity.cucumber.version>2.2.5</serenity.cucumber.version>

Could you please help me how to resolve the above issue. Thank you.

**Comment by wakaleo** [comment]
Could you post your serenity.properties or serenity.conf file?

**Comment by vsrd13** [comment]
HI John,

Here goes the serenity.properties and serenity.conf file. 

**<serenity.properties - File>**
serenity.project.name=Flex Force Portal Automation Suite

**<serenity.conf- File>**
#Parameter for browser specification
webdriver {
  driver = chrome
}

#test parameter

#Parameter for executing browser in headless mode
headless.mode = false

serenity {
  #  take.screenshots = FOR_FAILURES
}
#
# Chrome options can be defined using the chrome.switches property
#
chrome.switches = """--start-maximized;--test-type;--no-sandbox;--ignore-certificate-errors;
                   --disable-popup-blocking;--disable-default-apps;--disable-extensions-file-access-check;
                   --incognito;--disable-infobars,--disable-gpu"""
#
# Define drivers for different platforms. 
#Serenity will automatically pick the correct driver for the current platform
#
drivers {
  windows {
    webdriver.chrome.driver = "src/test/resources/webdriver/windows/chromedriver.exe"
    webdriver.gecko.driver = "src/test/resources/webdriver/windows/geckodriver.exe"
    webdriver.ie.driver = "src/test/resources/webdriver/windows/IEDriverServer.exe"
  }
  mac {
    webdriver.chrome.driver = "src/test/resources/webdriver/mac/chromedriver"
    webdriver.gecko.driver = "src/test/resources/webdriver/mac/geckodriver"
  }
  linux {
    webdriver.chrome.driver = "src/test/resources/webdriver/linux/chromedriver"
    webdriver.gecko.driver = "src/test/resources/webdriver/linux/geckodriver"
  }
}


#
# This section defines environment-specific configuration for different environments.
# You can define normal Serenity properties, such as webdriver.base.url, or custom ones
#

environments {
  default {
    webdriver.base.url = "https://<My_URL>"
   
  }
  dev {
    webdriver.base.url = ""
  }
  staging {
    webdriver.base.url = ""
  }
  prod {
    webdriver.base.url = ""
  }
}

**Comment by wakaleo** [comment]
Can you provide a project that reproduces the issue?

**Comment by vsrd13** [comment]
Automation.zip
<https://drive.google.com/file/d/1ze8NW-1hTsBidZD5vLhSw7P4tT7mWj7j/view?usp=drive_web>
Hi Serenity-Bdd/Serenity-Core,

Please find attached source code repository where I am seeing the error.

Regards,
Venkat.
