### ISSUE TITLE
Error executing FreeMarker template

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2181]
Hello,

I'm using the following libraries:
```
ext {
    junitVersion = '4.13'
    slf4jVersion = '1.7.30'
    assertJVersion = '3.16.1'
    serenityVersion = '2.2.10'
}

dependencies {
    testImplementation "junit:junit:${junitVersion}"
    testImplementation "org.slf4j:slf4j-simple:$slf4jVersion"
    testImplementation "org.assertj:assertj-core:${assertJVersion}"
    testImplementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-junit:${serenityVersion}"
}
```
When running serenity tests lots of errors are reported by the FreeMarker template as below:
```
error	24-Jul-2020 11:52:25	Error executing FreeMarker template
build	24-Jul-2020 11:52:25	Report generation failed
build	24-Jul-2020 11:52:25	freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
build	24-Jul-2020 11:52:25	==> formatter.renderHeader  [in template "freemarker/home.ftl" at line 137, column 58]
build	24-Jul-2020 11:52:25	
build	24-Jul-2020 11:52:25	----
build	24-Jul-2020 11:52:25	Tip: It's the step after the last dot that caused this error, not those before it.
build	24-Jul-2020 11:52:25	----
build	24-Jul-2020 11:52:25	Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
build	24-Jul-2020 11:52:25	----
build	24-Jul-2020 11:52:25	
build	24-Jul-2020 11:52:25	----
build	24-Jul-2020 11:52:25	FTL stack trace ("~" means nesting-related):
build	24-Jul-2020 11:52:25		- Failed at: ${formatter.htmlCompatibleStoryTitle(...  [in template "freemarker/home.ftl" at line 137, column 21]
build	24-Jul-2020 11:52:25	----
build	24-Jul-2020 11:52:25		at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
build	24-Jul-2020 11:52:25		at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85)
build	24-Jul-2020 11:52:25		at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:63)
build	24-Jul-2020 11:52:25		at freemarker.core.NonMethodException.<init>(NonMethodException.java:74)
build	24-Jul-2020 11:52:25		at freemarker.core.MethodCall._eval(MethodCall.java:67)
build	24-Jul-2020 11:52:25		at freemarker.core.Expression.eval(Expression.java:101)
build	24-Jul-2020 11:52:25		at freemarker.core.ListLiteral.getModelList(ListLiteral.java:93)
build	24-Jul-2020 11:52:25		at freemarker.core.MethodCall._eval(MethodCall.java:60)
build	24-Jul-2020 11:52:25		at freemarker.core.Expression.eval(Expression.java:101)
build	24-Jul-2020 11:52:25		at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
build	24-Jul-2020 11:52:25		at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
build	24-Jul-2020 11:52:25		at freemarker.core.Environment.visit(Environment.java:331)
build	24-Jul-2020 11:52:25		at freemarker.core.Environment.visit(Environment.java:337)
build	24-Jul-2020 11:52:25		at freemarker.core.Environment.visit(Environment.java:337)
build	24-Jul-2020 11:52:25		at freemarker.core.Environment.process(Environment.java:310)
build	24-Jul-2020 11:52:25		at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:39)
build	24-Jul-2020 11:52:25		at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
build	24-Jul-2020 11:52:25		at net.thucydides.core.reports.html.BaseReportingTask.generateReportPage(BaseReportingTask.java:45)
build	24-Jul-2020 11:52:25		at net.thucydides.core.reports.html.TagReportingTask.generateTagReport(TagReportingTask.java:83)
build	24-Jul-2020 11:52:25		at net.thucydides.core.reports.html.TagReportingTask.generateReports(TagReportingTask.java:64)
build	24-Jul-2020 11:52:25		at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:33)
build	24-Jul-2020 11:52:25		at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:12)
build	24-Jul-2020 11:52:25		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
build	24-Jul-2020 11:52:25		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
build	24-Jul-2020 11:52:25		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
build	24-Jul-2020 11:52:25		at java.base/java.lang.Thread.run(Thread.java:834)
build	24-Jul-2020 11:52:25	Report generation failed
error	24-Jul-2020 11:52:25	Error executing FreeMarker template
error	24-Jul-2020 11:52:25	Error executing FreeMarker template
error	24-Jul-2020 11:52:25	Error executing FreeMarker template
error	24-Jul-2020 11:52:25	Syntax error in report template: The following has evaluated to null or missing:
error	24-Jul-2020 11:52:25	==> formatter.renderHeader  [in template "freemarker/home.ftl" at line 137, column 58]
error	24-Jul-2020 11:52:25	
error	24-Jul-2020 11:52:25	----
error	24-Jul-2020 11:52:25	Tip: It's the step after the last dot that caused this error, not those before it.
error	24-Jul-2020 11:52:25	----
error	24-Jul-2020 11:52:25	Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
error	24-Jul-2020 11:52:25	----
```
I have no clue what went wrong here. At least all tests are passing and the serenity report is available finally.

Please, advice some work around or a solution.
Thanks and best regards, André

**Comment by cliviu** [comment]
hi, please try serenityVersion = '2.2.12'

**Comment by aybartsch** [comment]
Thanks, the new Serenity version has solved this issue. Closing the issue...
