### ISSUE TITLE
Spring Boot Maven Project JIRA Integration Issue

### ISSUE THREAD

**Issue by nandkv** [serenity-bdd/serenity-core#2256]
Following the guide here for two way JIRA integration: http://www.thucydides.info/docs/serenity/#_two_way_integration_with_jira

- Demo Project: Spring Boot with Rest Assured
- Default Reporting works well with no issues reported.
- Created a standard Scrum Project in JIRA with 1 Epic and 4 Stories.
- Added default properties to serenity.properties file 

```
serenity.project.name=Test
jira.url=https://myinstance.atlassian.net
jira.project=BDD
jira.username=user@gmail.com
jira.password=test
jira.root.issue.type=Epic
jira.custom.narrative.field=Story
jira.custom.field.1=Acceptance Criteria
serenity.release.types=milestone, release, version
```

- Added the meta data to the feature file 
```
@issues:BDD-1
Feature: Customer API Deployed
```

- Once I add the JIRA integration as defined in the guide the capabilities and features no longer works and the JIRA integration fails with the following error.

```
21:26:32.786 Æpool-7-thread-7Å WARN  n.t.c.r.RequirementsTagProvider - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: java.lang.IllegalStateException: InjectionManagerFactory not found.
java.lang.IllegalArgumentException: net.serenitybdd.plugins.jira.model.JQLException: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:266)
	at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:138)
	at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:78)
	at net.thucydides.core.tags.BreadcrumbTagFilter.getRequirementBreadcrumbsFrom(BreadcrumbTagFilter.java:51)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:202)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:189)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:165)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:107)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.serenitybdd.plugins.jira.model.JQLException: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:239)
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:255)
	... 15 common frames omitted
Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:74)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:74)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:412)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:807)
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:219)
	at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:610)
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:364)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:192)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:36)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.readFieldValues(JerseyJiraClient.java:480)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByKey(JerseyJiraClient.java:245)
	at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:17)
	at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:8)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:235)

```

Dependencies:
```
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jira-requirements-provider</artifactId>
			<version>1.12.0</version>
		</dependency>

			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<configuration>
					<tags>${tags}</tags>
				</configuration>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-jira-requirements-provider</artifactId>
						<version>1.12.0</version>
					</dependency>				
				</dependencies>
			</plugin>
```

**Comment by nandkv** [comment]
``

**Comment by nandkv** [comment]
Reviewed the code for the serenity plugin and this was due to the jersey dependencies that was not able to inject one of the dependencies.
```
		<dependency>
		  <groupId>org.glassfish.jersey.ext</groupId>
		  <artifactId>jersey-spring4</artifactId>
		</dependency>
```
Also the instructions for JIRA integration are incorrect. Seems like we need to include the dependencies only in the dependencies section and not the build section.
