### ISSUE TITLE
Can't run test by tags array  -Dtags="DynamicLists, Login"

### ISSUE THREAD

**Issue by upaul23** [serenity-bdd/serenity-core#2273]
In result I got this stecktrace. I didn't use cucumber in my project.

My current versions:

"<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>2.3.4</serenity.version>
        <serenity.maven.version>2.3.4</serenity.maven.version>        
        <maven.failsafe.version>3.0.0-M4</maven.failsafe.version>
    </properties>"

Tags expressions worked for version 2.0.82

io.cucumber.tagexpressions.TagExpressionException: Tag expression 'dynamiclists, login' could not be parsed because of syntax error: expected operator
        at io.cucumber.tagexpressions.TagExpressionParser.check(TagExpressionParser.java:136)
        at io.cucumber.tagexpressions.TagExpressionParser.parse(TagExpressionParser.java:74)
        at io.cucumber.tagexpressions.TagExpressionParser.parse(TagExpressionParser.java:27)
        at net.thucydides.core.reports.html.CucumberCompatibleFilter.cucumberTagExpressionUsing(CucumberCompatibleFilter.java:29)
        at net.thucydides.core.reports.html.CucumberCompatibleFilter.matchesTags(CucumberCompatibleFilter.java:56)
        at net.thucydides.core.tags.TagScanner.shouldRunMethod(TagScanner.java:51)
        at net.serenitybdd.junit.runners.SerenityRunner.shouldSkipTest(SerenityRunner.java:522)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:432)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by wakaleo** [comment]
You need to use the Cucumber notation for tags, e.g. -Dtags="DynamicLists or Login"

**Comment by upaul23** [comment]
Thx a lot! All works!
![image](https://user-images.githubusercontent.com/23288298/96227878-6ee95680-0f9d-11eb-995f-00aa1fa69db8.png)
