### ISSUE TITLE
On using latest version of selenium and serenity getting - java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable

### ISSUE THREAD

**Issue by Pushpanjali1993** [serenity-bdd/serenity-core#2302]
After updating to the latest version of serenity and selenium I am getting an error as - java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable  could anyone please help me out here.

Below are the dependencies which i am using.

`dependencies {

    compile "net.logstash.logback:logstash-logback-encoder"
    compile "org.springframework.boot:spring-boot-starter-test"

    compile ("com.cybg.ta:cybg-verification-services-int3:+"){
        exclude group: 'io.cucumber', module: 'cucumber-core'
        exclude group: 'io.cucumber', module: 'cucumber-java'
    }

    compile("com.bank.test:common-serenity:3.0.9") {
        exclude group: 'io.cucumber', module: 'cucumber-core'
        exclude group: 'io.cucumber', module: 'cucumber-java'
        exclude group: 'io.qameta.allure', module: 'allure-java-commons'
        exclude group: 'io.qameta.allure', module: 'allure-model'
        exclude group: 'javax.resource', module: 'connector'
    }

    compile 'io.cucumber:cucumber-java:5.6.0'
    //Serenity With Spring Boot
    compile "net.serenity-bdd:serenity-spring:2.2.9"

    //Allure Report Dependencies
    compile "io.qameta.allure:allure-cucumber5-jvm:$allurePluginVersion"
    compile "org.aspectj:aspectjweaver:1.9.5"

    //selenium dependencies
    compile group: 'net.serenity-bdd', name: 'serenity-core', version:'2.2.9'
    compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '2.2.9'
    compile group: 'net.serenity-bdd', name: 'serenity-gradle-plugin', version: '2.2.9'
    compile "org.seleniumhq.selenium:selenium-api:3.141.59"
    compile "org.seleniumhq.selenium:selenium-remote-driver:3.14.0"

}`

Many Thanks

**Comment by wakaleo** [comment]
That's a dependency conflict. Looks like the version of selenium-remote-driver is wrong.

**Comment by Pushpanjali1993** [comment]
Thanks for your quick response @wakaleo . I tried changing the dependency for selenium-remote-driver to 3.141.59 but still facing the same issue. Below is the snippet of error message, can you please have a look?


`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/r906755/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.25/8dacf9514f0c707cbbcdd6fd699e8940d42fb54e/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/r906755/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.11/ccedfbacef4a6515d2983e3f89ed753d5d4fb665/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[main] WARN io.cucumber.junit.CucumberSerenityRunner - By default Cucumber is running in --non-strict mode.
This default will change to --strict and --non-strict will be removed.
You can use --strict or @CucumberOptions(strict = true) to suppress this warning
org.junit.runner.notification.StoppedByUserException
	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:116)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:81)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:227)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:254)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.thucydides.core.webdriver.SupportedWebDriver.<clinit>(SupportedWebDriver.java:31)
	at net.thucydides.core.configuration.WebDriverConfiguration.lookupSupportedDriverTypeFor(WebDriverConfiguration.java:49)
	at net.thucydides.core.configuration.WebDriverConfiguration.getDriverType(WebDriverConfiguration.java:33)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.getDefaultDriverType(SerenityWebdriverManager.java:178)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.getWebdriver(SerenityWebdriverManager.java:116)
	at net.thucydides.core.webdriver.ThucydidesWebDriverSupport.getDriver(ThucydidesWebDriverSupport.java:147)
	at net.thucydides.core.webdriver.ThucydidesWebDriverSupport.getPages(ThucydidesWebDriverSupport.java:208)
	at net.serenitybdd.core.Serenity.getPages(Serenity.java:188)
	at net.serenitybdd.core.Serenity.getDefaultDependencyInjectors(Serenity.java:84)
	at net.serenitybdd.core.Serenity.getDependencyInjectors(Serenity.java:74)
	at net.serenitybdd.core.Serenity.resetDependencyInjectors(Serenity.java:67)
	at net.serenitybdd.core.Serenity.done(Serenity.java:167)
	at cucumber.runtime.SerenityObjectFactory.stop(SerenityObjectFactory.java:31)
	at io.cucumber.core.runner.Runner.disposeBackendWorlds(Runner.java:175)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:70)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:227)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:254)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.Killable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 50 more
`

Thanks.

**Comment by wakaleo** [comment]
NoClassDefFound is a dependency conflict. You need to do a dependency analysis on your pom file.
