### ISSUE TITLE
Serenity reports - no tests results are shown

### ISSUE THREAD

**Issue by tziviskou** [serenity-bdd/serenity-core#2309]
I imported the code (two classes) and configuration (pom.xml ans erenity.properties) of the serenity-junit-starter project into my project built with maven.

When I tun the tests I get:

[DEBUG] 2 requirements loaded after 7 ms
[DEBUG] 2 related requirements found after 7 ms
[DEBUG] Generating test outcome reports: false
[DEBUG] Aggregate reports generated in 210 ms 
[DEBUG] Test outcome reports generated in 225 ms
[INFO] Test results for 0 tests generated in 235 ms in directory: file:/D:/git3/easylake-service/target/site/serenity/
[DEBUG] Generated reports after 238 ms

Failed to resolve a serialised class during report generation: D:\git3\easylake-service\target\site\serenity\browserconfig.xml
com.thoughtworks.xstream.mapper.CannotResolveClassException: browserconfig
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:81)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
	at net.thucydides.core.reports.xml.XMLTestOutcomeReporter.loadReportFrom(XMLTestOutcomeReporter.java:121)
	at net.thucydides.core.reports.TestOutcomeLoader$TestOutcomeLoaderCallable.call(TestOutcomeLoader.java:99)
	at net.thucydides.core.reports.TestOutcomeLoader$TestOutcomeLoaderCallable.call(TestOutcomeLoader.java:87)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

As a result I do not see any test results in the serenity index.html. I see the Story but no scenario.

Thank you

**Comment by wakaleo** [comment]
What version are you using? XML reports have been deprecated for a while now...

**Comment by tziviskou** [comment]
<serenity.version>2.2.8</serenity.version>
<serenity.maven.version>2.2.8</serenity.maven.version>
        
as in the serenity-junit-starter project.
What version should I use?

**Comment by wakaleo** [comment]
That should be fine, but there shouldn't be any XML reports. Could you post your serenity.properties file?

**Comment by tziviskou** [comment]
serenity.properties contains:

serenity.project.name=Serenity and JUnit Quick Start Project
serenity.test.root=starter
