### ISSUE TITLE
Error executing FreeMarker template

### ISSUE THREAD

**Issue by Unbr8kbal** [serenity-bdd/serenity-core#231]
I'm getting an error executing gradle aggregate, it looks like this:

```
Syntax error in report template: Java method "net.thucydides.core.model.OutcomeCounter.withResult(String)" threw an exception when invoked on net.thucydides.core.model.OutcomeCounter object "net.thucydides.core.model.OutcomeCounter@43e7fbb1"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #assign successfulManualTests = (test...  [in template "freemarker/home.ftl" at line 23, column 1]
----
        - Failed at: #assign successfulManualTests = (test...  [in template "freemarker/home.ftl" at line 23, column 1]
```

Thanks

**Comment by YamStranger** [comment]
Hello @Unbr8kbal Thanks for this issue. 

Please some more examples to reproduce your issue. 

I can't reproduce your issue with our [demo](https://github.com/serenity-bdd/serenity-demos) projects

Thanks a lot!

**Comment by Unbr8kbal** [comment]
Hard for me to do that since it's IP..

However here is the full stacktrace:

```15:33:46.482 [ERROR] [freemarker.runtime] Error executing FreeMarker template
15:33:46.486 [ERROR] [net.thucydides.core.reports.templates.FreemarkerReportTemplate] Syntax error in report template: Java method "net.thucydides.core.model.OutcomeCounter.withResult(String)" threw an exception when invoked on net.thucydides.core.model.OutcomeCounter object "net.thucydides.core.model.OutcomeCounter@301c3892"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #assign successfulManualTests = (test...  [in template "freemarker/home.ftl" at line 23, column 1]
----
        - Failed at: #assign successfulManualTests = (test...  [in template "freemarker/home.ftl" at line 23, column 1]

15:33:46.486 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':integration-test:aggregate'
15:33:46.486 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :integration-test:aggregate FAILED
15:33:46.492 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :integration-test:aggregate (Thread[main,5,main]) completed. Took 1.423 secs.
15:33:46.492 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 1.423 secs, idle: 0.001 secs
15:33:46.496 [ERROR] [org.gradle.BuildExceptionReporter] 
15:33:46.497 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:33:46.497 [ERROR] [org.gradle.BuildExceptionReporter] 
15:33:46.497 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:33:46.497 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':integration-test:aggregate'.
15:33:46.497 [ERROR] [org.gradle.BuildExceptionReporter] > Failed to merge template: Failed to process FreeMarker template
15:33:46.498 [ERROR] [org.gradle.BuildExceptionReporter] 
15:33:46.498 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:33:46.498 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':integration-test:aggregate'.
15:33:46.498 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
15:33:46.499 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
15:33:46.499 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
15:33:46.499 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
15:33:46.499 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
15:33:46.499 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
15:33:46.499 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
15:33:46.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
15:33:46.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
15:33:46.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
15:33:46.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
15:33:46.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
15:33:46.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
15:33:46.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
15:33:46.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
15:33:46.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
15:33:46.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
15:33:46.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
15:33:46.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
15:33:46.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
15:33:46.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
15:33:46.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
15:33:46.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
15:33:46.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
15:33:46.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
15:33:46.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
15:33:46.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
15:33:46.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
15:33:46.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
15:33:46.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
15:33:46.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
15:33:46.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
15:33:46.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
15:33:46.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
15:33:46.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
15:33:46.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.RuntimeException: Failed to merge template: Failed to process FreeMarker template
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.reports.html.HtmlReporter$Merger.usingContext(HtmlReporter.java:158)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportPage(HtmlAggregateStoryReporter.java:504)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateAggregateReportFor(HtmlAggregateStoryReporter.java:258)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:160)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:130)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.reports.UserStoryTestReporter$generateReportsForTestResultsFrom.call(Unknown Source)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at net.serenitybdd.plugins.gradle.SerenityPlugin$_apply_closure1_closure6.doCall(SerenityPlugin.groovy:37)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
15:33:46.506 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter]        ... 57 more
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: net.thucydides.core.reports.templates.TemplateMergeException: Failed to process FreeMarker template
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:42)
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.reports.html.HtmlReporter$Merger.usingContext(HtmlReporter.java:155)
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter]        ... 67 more
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: freemarker.core._TemplateModelException: Java method "net.thucydides.core.model.OutcomeCounter.withResult(String)" threw an exception when invoked on net.thucydides.core.model.OutcomeCounter object "net.thucydides.core.model.OutcomeCounter@301c3892"; see cause exception in the Java stack trace.
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter] 
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter] ----
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter] FTL stack trace ("~" means nesting-related):
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter]        - Failed at: #assign successfulManualTests = (test...  [in template "freemarker/home.ftl" at line 23, column 1]
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter] ----
15:33:46.507 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:307)
15:33:46.508 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:280)
15:33:46.508 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:68)
15:33:46.508 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.MethodCall._eval(MethodCall.java:62)
15:33:46.508 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.Expression.eval(Expression.java:76)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.EvalUtil.compare(EvalUtil.java:110)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.ComparisonExpression.evalToBoolean(ComparisonExpression.java:65)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.BooleanExpression._eval(BooleanExpression.java:27)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.Expression.eval(Expression.java:76)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.ParentheticalExpression._eval(ParentheticalExpression.java:44)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.Expression.eval(Expression.java:76)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.Assignment.accept(Assignment.java:71)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.Environment.visit(Environment.java:257)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.MixedContent.accept(MixedContent.java:57)
15:33:46.514 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.Environment.visit(Environment.java:257)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.core.Environment.process(Environment.java:235)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.template.Template.process(Template.java:262)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:33)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        ... 68 more
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IncompatibleClassChangeError: class net.sf.cglib.core.DebuggingClassWriter has interface org.objectweb.asm.ClassVisitor as super class
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
15:33:46.515 [ERROR] [org.gradle.BuildExceptionReporter]        at ch.lambdaj.proxy.ProxyUtil.createEnhancer(ProxyUtil.java:89)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at ch.lambdaj.proxy.ProxyUtil.createProxy(ProxyUtil.java:49)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at ch.lambdaj.function.argument.ArgumentsFactory.createPlaceholder(ArgumentsFactory.java:52)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at ch.lambdaj.function.argument.ArgumentsFactory.registerNewArgument(ArgumentsFactory.java:45)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at ch.lambdaj.function.argument.ArgumentsFactory.createArgument(ArgumentsFactory.java:39)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at ch.lambdaj.function.argument.ArgumentsFactory.createArgument(ArgumentsFactory.java:31)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at ch.lambdaj.Lambda.on(Lambda.java:44)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.model.OutcomeCounter.withResult(OutcomeCounter.java:23)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at net.thucydides.core.model.OutcomeCounter.withResult(OutcomeCounter.java:19)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1385)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:52)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:48)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:62)
15:33:46.516 [ERROR] [org.gradle.BuildExceptionReporter]        ... 83 more
15:33:46.517 [ERROR] [org.gradle.BuildExceptionReporter] 
15:33:46.517 [LIFECYCLE] [org.gradle.BuildResultLogger] 
15:33:46.517 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
15:33:46.517 [LIFECYCLE] [org.gradle.BuildResultLogger] 
15:33:46.517 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 15.783 secs
```

It looks related to this: https://github.com/serenity-bdd/serenity-core/pull/206

Not really sure what else i could do.

**Comment by Unbr8kbal** [comment]
Was very related to #206 , had another asm on the classpath.
