### ISSUE TITLE
Exceptions while run test on JDK15 with Serenity (using Rest Assured) 2.2.0/2.3.5

### ISSUE THREAD

**Issue by DmitriyKapeliukh** [serenity-bdd/serenity-core#2310]
Pre-Conditions:
Java version "15.0.1" 2020-10-20
Maven Apache Maven 3.5.4
OS: macOS Catalina 10.15.7

**When I running tests with Serenity 2.2.0, I've got:**

```
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at net.thucydides.core.steps.StepFactory.createProxyStepLibrary(StepFactory.java:227)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:163)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:154)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:101)
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:76)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:42)
	at net.serenitybdd.junit.runners.SerenityRunner.injectScenarioStepsInto(SerenityRunner.java:646)
	at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:609)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:464)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:438)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:45)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:367)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:242)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.restassured.RestAssured
	at io.restassured.builder.ResponseSpecBuilder.<init>(ResponseSpecBuilder.java:66)
	at <..my project code stacktrace..>
	... 38 common frames omitted
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "steps" is null
	at net.thucydides.core.steps.StepsAnnotatedField.actorFieldIn(StepsAnnotatedField.java:159)
	at net.thucydides.core.steps.StepsAnnotatedField.assignActorNameIn(StepsAnnotatedField.java:135)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:79)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:42)
	at net.serenitybdd.junit.runners.SerenityRunner.injectScenarioStepsInto(SerenityRunner.java:646)
	at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:609)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:464)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:438)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:45)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:367)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:242)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**And when I running tests with Serenity 2.3.5, I've got:**

```
java.lang.AbstractMethodError: Receiver class net.serenitybdd.rest.decorators.ResponseSpecificationDecorated$ByteBuddy$KHRByodA does not define or inherit an implementation of the resolved method 'abstract io.restassured.specification.ResponseLogSpecification log()' of interface io.restassured.specification.ResponseSpecification.
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1634)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1259)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1026)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
	at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1661)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1259)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1026)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
	at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
	at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:175)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.executeCall(RequestSpecificationDecorated.java:303)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.execute(RequestSpecificationDecorated.java:263)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:115)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:38)
	at <..my project code stacktrace..>
```

**Comment by wakaleo** [comment]
java.lang.NoClassDefFoundError is a version conflict. Your project is probably using a version of RestAssured that is not compatible with the version of Serenity you are using.

**Comment by DmitriyKapeliukh** [comment]
> java.lang.NoClassDefFoundError is a version conflict. Your project is probably using a version of RestAssured that is not compatible with the version of Serenity you are using.

But when I use Serenity 2.3.5 (Rest Assured 4.3.1 included) I've got "java.lang.AbstractMethodError..." Please see the end of first message.

**Comment by wakaleo** [comment]
It's still a version conflict of some kind, either directly with RestAssured, or indirectly (possibly with Groovy). Try doing a dependency analysis on your project.

**Comment by ricardorlg-aval** [comment]
for the last exception message, are u using SerenityRest.enableLoggingOfRequestAndResponseIfValidationFails() in your code?

**Comment by DmitriyKapeliukh** [comment]
> for the last exception message, are u using SerenityRest.enableLoggingOfRequestAndResponseIfValidationFails() in your code?

Yes!

**Comment by DmitriyKapeliukh** [comment]
> > for the last exception message, are u using SerenityRest.enableLoggingOfRequestAndResponseIfValidationFails() in your code?
> 
> Yes! Used inside the method with Before annotation.
> 
> ```
>     @Before
>     public void run() {
>         RestAssured.baseURI = "https://nyApiHost/";
>         SerenityRest.useRelaxedHTTPSValidation();
>         SerenityRest.enableLoggingOfRequestAndResponseIfValidationFails();
>         SerenityRest.setDefaultRequestSpecification(
>                 new RequestSpecBuilder()
>                         .setContentType(ContentType.JSON)
>                         .build());
>         SerenityRest.setDefaultRootPath("data");
>     }
> ```

@ricardorlg-aval did you have a suggestion to avoid/fix this issue?

**Comment by ricardorlg-aval** [comment]
remove that call, and try again.

**Comment by ferranmarcfg** [comment]
Hi, I have the same error as you in version 2.3.5 but in version 2.3.8.

**Comment by wakaleo** [comment]
Also, do a dependency analysis and make sure Groovy 3.0.x is being used.

**Comment by DmitriyKapeliukh** [comment]
> Also, do a dependency analysis and make sure Groovy 3.0.x is being used.

[INFO] |  +- org.codehaus.groovy:groovy:jar:3.0.5:compile
[INFO] |  +- org.codehaus.groovy:groovy-xml:jar:3.0.5:compile
[INFO] |  \- org.codehaus.groovy:groovy-json:jar:3.0.5:compile

**Comment by DmitriyKapeliukh** [comment]
> remove that call, and try again.

When I'm running test without a call `SerenityRest.enableLoggingOfRequestAndResponseIfValidationFails()` exception described above did not happen. But I need this static method to log in console request/response when my test fails on status code verification.

**Comment by ricardorlg-aval** [comment]
this is fixed now, just wait for the new release, @wakaleo can tell u when is going to be the release.

**Comment by DmitriyKapeliukh** [comment]
@ricardorlg-aval works fine with Serenity 2.3.9. I'll close this issue.

**Comment by mohamed-abdulkadar-mpf** [comment]
Hi, 
I have used Task  and CanBeSilent, but still i see **Rest Query** in the Report. Can you provide me example by using Task to hide Rest Query in the Report.

**Sample Code**
`public class LoginTask implements Task , CanBeSilent {
    
   @Steps
    HelperUtility helperUtility;

    private final Login userLoginInput;
    private final String nickname;


    UserInformationUtilities userInfoUtilities = new UserInformationUtilities();
    
    public LoginTask(UserProfile profile) {

        userInfoUtilities.loadUserInformationFromSecretFile();
        this.userLoginInput = new Login(userInfoUtilities.userInfoUtilities(profile.nickname),
                userInfoUtilities.getApiUserPassword(profile.nickname));
        this.nickname = profile.nickname;

    }

    

    public static Performable getUserToken(UserProfile profile) {
        return instrumented(LoginTask.class, profile);
    }

    
    @Override
    @Step("{0} Get Auth  Token for user #nickname")
    public <T extends Actor> void performAs(T actor) {

    

        //Build Requests header based on external or internal user
        Map<String,String> headerList = helperUtility.getHeaders();

        actor.attemptsTo(
                Post.to(EndPoints.Token.path())
                        .with(request -> request
                                .headers(headerList)
                                .body(userLoginInput)

                        )

        );

        actor.should(
                seeThatResponse("Http StatusCode for call "+ EndPoints.Token.path(),
                        response -> response.statusCode(200)
                )
        );

        if (SerenityRest.lastResponse().statusCode() == 200) {
                String token = SerenityRest.lastResponse().jsonPath().get("token");
                actor.remember(nickname, token);
            
        }

    }


    @Override
    public boolean isSilent() {
        return true;
    }
}
`

**Comment by globalworming** [comment]
check #2029, this should be possible. If not, please create a new issue

**Comment by ricardorlg-aval** [comment]
You have to add to the post a call to withNoReporting() method.

Something like 
``` java
actor.attemptsTo(
            Post.to(EndPoints.Token.path())
                   .withNoReporting()
                    .with(request -> request
                            .headers(headerList)
                            .body(userLoginInput)

                    )

    ); 
```
