### ISSUE TITLE
Null pointer execption while running cucumber feature file with Serenity pageObject , it is failing create the Steps for an class 

### ISSUE THREAD

**Issue by trinadhdn** [serenity-bdd/serenity-core#2331]
Failing while calling below step and respective object has steps implemented .

![image](https://user-images.githubusercontent.com/25567280/101311416-5e57ad00-3877-11eb-809d-e9421203de33.png)

Error :- 

java.lang.NullPointerException
	at net.thucydides.core.steps.StepsAnnotatedField.actorFieldIn(StepsAnnotatedField.java:159)
	at net.thucydides.core.steps.StepsAnnotatedField.assignActorNameIn(StepsAnnotatedField.java:135)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:79)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:42)
	at net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:137)
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:103)
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:71)
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:54)
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:44)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:27)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:46)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:51)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:227)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:254)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by wakaleo** [comment]
You cannot run a Serenity test directly from a feature file - this is not supported by the IDEs.

**Comment by trinadhdn** [comment]
No , i am running from the runner file .


@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
		features = "src/test/resources/web/features", 
		glue = "com.cbre.steps.web",
        plugin = {"pretty","json:target/site/reports/web/chrome.json" }, 
		tags = {  "@democasen321"},
        dryRun = false)

public class ChromeRunner {

**Comment by wakaleo** [comment]
Is ObjectTypes a step library or a page object?

**Comment by trinadhdn** [comment]
This is how i defined in ObjectType.

	package com.cbre.objectManager;

import java.io.IOException;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.xml.datatype.DatatypeConfigurationException;

import com.cbre.webui.commons.PropertiesHandler;
import com.google.gson.JsonArray;

import net.thucydides.core.annotations.Step;

/**
 * @author Trinadh Kumar Nakka Date: 03/09/2020
 * 
 */
public class ObjectTypes extends BaseObject{

	PropertiesHandler page = new PropertiesHandler();

	public ObjectTypes(String propertyFileName) throws IOException {
		page.baseName = propertyFileName;
		waitForPageLoad();
		waitForGridSpinnerToComplete();


	}

	@Step("WebTextBox")
	public WebTextBox WebTextBox(String objectName) throws IOException {
		waitForGridSpinnerToComplete();
		String selector = page.getSelectorFromPropertyFile("WebTextBox." + objectName);
		BaseObject.m_objectName = objectName;

		if (!selector.isEmpty()) {
			WebTextBox object = new WebTextBox(selector);
			return object;
		} else {
			return null;
		}
	}
	
	@Step("WebTextBox")
	public WebTextBox WebTextBox(String objectName, String childobjectName) throws IOException {
		waitForGridSpinnerToComplete();

		String selector = page.getSelectorFromPropertyFile("WebTextBox." + objectName);
		String childSelector = page.getSelectorFromPropertyFile("WebTextBox." + childobjectName);
		BaseObject.m_objectName = objectName;

		if (!selector.isEmpty() && !childSelector.isEmpty()) {
			WebTextBox object = new WebTextBox(selector, childSelector);
			return object;
		} else {
			return null;
		}
	}

	@Step("WebButton")
	public WebButton WebButton(String objectName) throws IOException {
		waitForGridSpinnerToComplete();
		String selector = page.getSelectorFromPropertyFile("WebButton." + objectName);
		BaseObject.m_objectName = objectName;
		if (!selector.isEmpty()) {
			WebButton object = new WebButton(selector);
			return object;
		} else {
			return null;
		}
	}

	@Step("WebCheckBox")
	public WebCheckBox WebCheckBox(String objectName) throws IOException {
		waitForGridSpinnerToComplete();

		String selector = page.getSelectorFromPropertyFile("WebCheckBox." + objectName);
		BaseObject.m_objectName = objectName;

		if (!selector.isEmpty()) {
			WebCheckBox object = new WebCheckBox(selector);
			return object;
		} else {
			return null;
		}
	}

	@Step("WebComboBox")
	public WebComboBox WebComboBox(String objectName) throws IOException {
		waitForGridSpinnerToComplete();

		String selector = page.getSelectorFromPropertyFile("WebComboBox." + objectName);
		BaseObject.m_objectName = objectName;

		if (!selector.isEmpty()) {
			WebComboBox object = new WebComboBox(selector);
			return object;
		} else {
			return null;
		}
	}

	@Step("WebToggleButton")
	public WebToggleButton WebToggleButton(String objectName) throws IOException {
		waitForGridSpinnerToComplete();

		String selector = page.getSelectorFromPropertyFile("WebToggleButton." + objectName);
		BaseObject.m_objectName = objectName;

		if (!selector.isEmpty()) {
			WebToggleButton object = new WebToggleButton(selector);
			return object;
		} else {
			return null;
		}
	}

	@Step("WebComboBox")
	public WebComboBox WebComboBox(String objectName, String childobjectName) throws IOException {
		waitForGridSpinnerToComplete();

		String selector = page.getSelectorFromPropertyFile("WebComboBox." + objectName);
		String childSelector = page.getSelectorFromPropertyFile("WebComboBox." + childobjectName);
		BaseObject.m_objectName = objectName;

		if (!selector.isEmpty() && !childSelector.isEmpty()) {
			WebComboBox object = new WebComboBox(selector, childSelector);
			return object;
		} else {
			return null;
		}
	}
	@Step("WebObject")
	public static WebObject WebObject(String objectName) throws IOException {
		waitForGridSpinnerToComplete();

		String selector = page.getSelectorFromPropertyFile("WebObject." + objectName);
		BaseObject.m_objectName = objectName;

		if (!selector.isEmpty()) {
			WebObject object = new WebObject(selector);
			return object;
		} else {
			return null;
		}
	}

	@Step("WebTable")
	public WebTable WebTable(String objectName) throws IOException, DatatypeConfigurationException {
		String selector = page.getSelectorFromPropertyFile("WebTable." + objectName);
		BaseObject.m_objectName = objectName;

		if (!selector.isEmpty()) {
			WebTable object = new WebTable(selector);
			return object;
		} else {
			return null;
		}
	}
}

**Comment by wakaleo** [comment]
It looks like you are mixing page objects and step libraries, which may cause problems.

**Comment by trinadhdn** [comment]
any suggestion to create objects ?

**Comment by trinadhdn** [comment]
I updated the code to below and i am getting below error

public class ObjectTypes extends BaseObject {

	PropertiesHandler page = new PropertiesHandler();

	@Steps
	WebTextBox webtextbox;
	@Steps
	WebObject webObject;

	public ObjectTypes(String propertyFileName) throws IOException {
		page.baseName = propertyFileName;
		waitForPageLoad();
		waitForGridSpinnerToComplete();

	}





Error :- 
[31mThen [0m[31mVerify Objects on Pulse Landing Page[0m                              [90m# com.cbre.steps.web.PulseLandingPageStepDefinition.Verify_Objects_on_PulseLanding_ObjectTypes(io.cucumber.datatable.DataTable)[0m
      [31mnet.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for ObjectTypes:null
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:132)
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:76)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:42)
	at net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:137)
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:103)
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:71)
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:54)
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:44)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:27)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:46)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:51)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:227)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:254)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NullPointerException
	at net.thucydides.core.steps.StepsAnnotatedField.actorFieldIn(StepsAnnotatedField.java:159)
	at net.thucydides.core.steps.StepsAnnotatedField.assignActorNameIn(StepsAnnotatedField.java:135)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:79)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
	at net.thucydides.core.steps.StepAnnotations.injectNestedScenarioStepsInto(StepAnnotations.java:52)
	at net.thucydides.core.steps.StepFactory.instantiateAnyNestedStepLibrariesIn(StepFactory.java:403)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:194)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:179)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:126)
	... 40 more
[0m
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
  [36mThen [0m[36mEnter data on RightSideBar Page[0m                                   [90m# com.cbre.steps.web.RightSideBarPageStepDefinition.Enter_data_on_Contacts_page(io.cucumber.datatable.DataTable)[0m
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
  [36mThen [0m[36mEnter data on CriticalDates Page[0m                                  [90m# com.cbre.steps.web.CriticalDatesPageStepDefinition.Enter_data_on_CriticalDates_page(io.cucumber.datatable.DataTable)[0m
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
  [36mThen [0m[36mVerify Alert Message Text[0m                                         [90m# com.cbre.steps.web.BaseObjectStepDefinition.Verify_Alert_Message(io.cucumber.datatable.DataTable)[0m
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
  [36mThen [0m[36mEnter data on Pulse Landing Page[0m                                  [90m# com.cbre.steps.web.PulseLandingPageStepDefinition.Enter_data_on_Pulse_Landing_ObjectTypes(io.cucumber.datatable.DataTable)[0m
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
  [36mThen [0m[36mEnter data on CriticalDates Table Page[0m                            [90m# com.cbre.steps.web.CriticalDatesPageStepDefinition.Enter_data_on_CriticalDates_Table_pageS(io.cucumber.datatable.DataTable)[0m
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
  [36mThen [0m[36mVerify data on CriticalDates Page[0m                                 [90m# com.cbre.steps.web.CriticalDatesPageStepDefinition.Verify_data_on_CriticalDates_page(io.cucumber.datatable.DataTable)[0m
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
  [36mThen [0m[36mEnter data on CriticalDates Page[0m                                  [90m# com.cbre.steps.web.CriticalDatesPageStepDefinition.Enter_data_on_CriticalDates_page(io.cucumber.datatable.DataTable)[0m
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
  [36mThen [0m[36mEnter data on CriticalDates Table Page[0m                            [90m# com.cbre.steps.web.CriticalDatesPageStepDefinition.Enter_data_on_CriticalDates_Table_pageS(io.cucumber.datatable.DataTable)[0m
Step argument class io.cucumber.core.gherkin.vintage.GherkinVintageDataTableArgument
  [36mThen [0m[36mEnter Data on Popup[0m                                               [90m# com.cbre.steps.web.BaseObjectStepDefinition.Enter_Obn_Popup(io.cucumber.datatable.DataTable)[0m

[31mFailed scenarios:[0m
[31mfile:///C:/GIT_Repo/Pulse_Automation/Pulse_QE_Automation/src/test/resources/web/features/CriticalDates_AllCases.feature:7[0m# Create CriticalDate with all valid details

1 Scenarios ([31m1 failed[0m)
11 Steps ([31m1 failed[0m, [36m9 skipped[0m, [32m1 passed[0m)
1m21.286s


net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for ObjectTypes:null
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:132)
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:76)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:42)
	at net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:137)
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:103)
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:71)
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:54)
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:44)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:27)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:46)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:51)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:227)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:254)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NullPointerException
	at net.thucydides.core.steps.StepsAnnotatedField.actorFieldIn(StepsAnnotatedField.java:159)
	at net.thucydides.core.steps.StepsAnnotatedField.assignActorNameIn(StepsAnnotatedField.java:135)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:79)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
	at net.thucydides.core.steps.StepAnnotations.injectNestedScenarioStepsInto(StepAnnotations.java:52)
	at net.thucydides.core.steps.StepFactory.instantiateAnyNestedStepLibrariesIn(StepFactory.java:403)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:194)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:179)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:126)
	... 40 more

**Comment by trinadhdn** [comment]
@wakaleo , Any suggestion please

**Comment by trinadhdn** [comment]
i was able to fix with workaround .

1. Removed @Steps annotation 
2. Just created an object with name like "ClassNAme name;"
3. Created a constructor with driver as a parameter 

public ObjectTypes(WebDriver driver) throws IOException {
		driver = super.getDriver();

	}

it started working .

Sample Code:- 

StepDefintion :- 
public class PulseLandingPageStepDefinition {

	ObjectTypes page;

	@Then("^Enter data on Pulse Landing Page$")
	public void Enter_data_on_Pulse_Landing_ObjectTypes(DataTable dt) throws Throwable {
		List<Map<String, String>> list = dt.asMaps(String.class, String.class);

		page.setObjectTypesParams(this.getClass().getSimpleName());

		for (Map<String, String> map : list) {
			//page.waitForPageLoad();
			page.WebObject("OverviewTab").click(map.get("buttonToClick"));
			page.WebObject("CriticalDatesTab").click(map.get("buttonToClick"));
			page.WebObject("DocumentsTab").click(map.get("buttonToClick"));
			page.WebObject("ContactsTab").click(map.get("buttonToClick"));
			page.WebObject("PropertyDropdownLink").click(map.get("buttonToClick"));
			page.WebTextBox("PropertyDropdownSearch", "ListOptions")
					.setandSelectDataFromDropDown(map.get("PropertyDropdownSearch"));
			page.WebButton("GlobalFilter").click(map.get("buttonToClick"));
			page.WebButton("TopBeforeObjectTypes").click(map.get("buttonToClick"));
			page.WebButton("TopNextObjectTypes").click(map.get("buttonToClick"));
			//page.waitForPageLoad();
		}
	}


Object class :- 

public class ObjectTypes extends BaseObject {


	public ObjectTypes(String propertyFileName) throws IOException {
		page.baseName = propertyFileName;
		waitForPageLoad();
		waitForGridSpinnerToComplete();

	}

	public ObjectTypes(WebDriver driver) throws IOException {
		driver = super.getDriver();

	}
