### ISSUE TITLE
serenity-gradle-plugin aggregate task OutOfMemoryError

### ISSUE THREAD

**Issue by hertzsprung** [serenity-bdd/serenity-core#2369]
I can [workaround this with `export _JAVA_OPTIONS=-Xmx4g`](https://stackoverflow.com/a/59852045/150884), but setting `org.gradle.jvmargs=-Xmx4g` in `gradle.properties` doesn't help (does the aggregate task run in a JVM separate from the gradle daemon?)

Is there a way of increasing the aggregate task's heap size from build.gradle?  If not, can it be added?

````
14:04:24.823 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :featureTest
14:04:49.381 [DEBUG] [TestEventLogger]     2021-01-18 14:04:49,372  WARN [pool-125-thread-1] (RequirementsProvided.java:17) - Failed to load requirements: GC overhead limit exceeded
14:04:49.381 [DEBUG] [TestEventLogger]     java.lang.OutOfMemoryError: GC overhead limit exceeded
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.Arrays.copyOfRange(Arrays.java:3664)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.lang.String.<init>(String.java:207)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.zip.ZipCoder.toString(ZipCoder.java:59)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.zip.ZipFile.getZipEntry(ZipFile.java:583)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.zip.ZipFile.access$900(ZipFile.java:60)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:539)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.jar.JarFile$JarEntryIterator.next(JarFile.java:257)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:266)
14:04:49.381 [DEBUG] [TestEventLogger]          at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:247)
14:04:49.381 [DEBUG] [TestEventLogger]          at com.google.common.reflect.ClassPath$DefaultScanner.scanJarFile(ClassPath.java:522)
14:04:49.381 [DEBUG] [TestEventLogger]          at com.google.common.reflect.ClassPath$Scanner.scanJar(ClassPath.java:400)
14:04:49.381 [DEBUG] [TestEventLogger]          at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:384)
14:04:49.381 [DEBUG] [TestEventLogger]          at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:361)
14:04:49.381 [DEBUG] [TestEventLogger]          at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:354)
14:04:49.381 [DEBUG] [TestEventLogger]          at com.google.common.reflect.ClassPath.from(ClassPath.java:119)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsFromClassesInPackage(PackageRequirementsTagProvider.java:171)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsStartingFrom(PackageRequirementsTagProvider.java:161)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementsReadFromClasspath(PackageRequirementsTagProvider.java:120)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.requirements.PackageRequirementsTagProvider.fetchRequirements(PackageRequirementsTagProvider.java:103)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirements(PackageRequirementsTagProvider.java:94)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.requirements.RequirementsProvided.by(RequirementsProvided.java:15)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.requirements.MultiSourceRequirementsService.getRequirements(MultiSourceRequirementsService.java:40)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.requirements.BaseRequirementsService.getRequirementTypes(BaseRequirementsService.java:197)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:163)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:107)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:246)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:184)
14:04:49.382 [DEBUG] [TestEventLogger]          at net.thucydides.core.reports.ReportService$$Lambda$1700/452100653.run(Unknown Source)
14:04:49.382 [DEBUG] [TestEventLogger]          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
14:04:49.382 [DEBUG] [TestEventLogger]          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:04:49.976 [LIFECYCLE] [org.gradle.launcher.daemon.server.Daemon] 
14:04:49.976 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
14:04:49.976 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
14:04:49.976 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
14:04:49.976 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
14:04:49.977 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
14:04:49.977 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
14:04:49.977 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
14:04:51.271 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 16273854464, Free: 4919574528}
14:04:51.271 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 16273854464, Free: 4919574528}
14:04:51.271 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 3817865216, Committed: 560463872}

````

**Comment by wakaleo** [comment]
this is a gradle question I think?

**Comment by hertzsprung** [comment]
I'm not sure whether changes are needed in the serenity-gradle-plugin itself, but I've failed to work out how to change the heap size of serenity's `aggregate` task.  I'll keep looking.

**Comment by wakaleo** [comment]
There isn't any task-specific option in the aggregate task for that - I think it's normally something that would be done in the gradle script, not in the task source code.

**Comment by hertzsprung** [comment]
Found it!  I had to [set the heap size for `JavaForkOptions` tasks](https://stackoverflow.com/questions/21906736/how-do-i-set-jvm-options-for-gradleworkermain):
````
tasks.withType(JavaForkOptions) {
    maxHeapSize = '1024m'
}
````
1024m was enough for me (the [default `maxHeapSize` for gradle is 512m](https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory)).
