### ISSUE TITLE
@RunWith(SerenityParameterizedRunner.class) not execute the test

### ISSUE THREAD

**Issue by Deniss22605** [serenity-bdd/serenity-core#2381]
When I'm trying to run the automated test, by using @RunWith(SerenityParameterizedRunner.class), I'm retrieving the following error: 
**java.lang.Exception: No tests found matching Method ... from org.junit.internal.requests.ClassRequest**

Project configuration: 

1. Serenity BDD Version: 2.3.12
2. Serenity JUnit Version: 2.3.12
3. JUnit Version: 4.12

Note: When I use @RunWith(SerenityRunner.class) no error happens.

**Comment by SiKing** [comment]
Did you define `@TestData` and a constructor that consumes it?
https://serenity-bdd.github.io/theserenitybook/latest/junit-data-driven.html

**Comment by Jacobvu84** [comment]
@Deniss22605 
Can you give your test name ?

**Comment by vinhtrangithub** [comment]
same issue

java.lang.Exception: No tests found matching Method findCarNameandPriceTest(testcases.CarPriceTest) from org.junit.internal.requests.ClassRequest@38aa816f



at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)

at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)

at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)

at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)

at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
