### ISSUE TITLE
Call to Serenity.takeScreenshot() fail with NullPointerException

### ISSUE THREAD

**Issue by Jiri72** [serenity-bdd/serenity-core#2398]
When calling Serenity.takeScreenshot from step it sometime fail with NullPointerException.
```
 java.lang.NullPointerException
	at net.thucydides.core.steps.BaseStepListener.shouldTakeScreenshots(BaseStepListener.java:875)
	at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:858)
	at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:854)
	at net.thucydides.core.steps.BaseStepListener.takeScreenshot(BaseStepListener.java:1118)
	at net.thucydides.core.steps.StepEventBus.takeScreenshot(StepEventBus.java:711)
	at net.serenitybdd.core.Serenity.takeScreenshot(Serenity.java:249)
```
Solution is to use method screenshots() instead of member variable directly in net.thucydides.core.steps.BaseStepListener.shouldTakeScreenshots method
```
if (screenshots.areDisabledForThisAction())
```
to 
```
if (screenshots().areDisabledForThisAction())
```

I think that it was introduced in commit 7a639e2801710aa6cd60e5f9210945a8911ebcd7

**Comment by wakaleo** [comment]
Well spotted. Could you propose a PR?
