### ISSUE TITLE
Error org.junit.runner.notification.StoppedByUserException

### ISSUE THREAD

**Issue by billyjulius** [serenity-bdd/serenity-core#2427]
Hello

I found this error `org.junit.runner.notification.StoppedByUserException` when running serenity cucumber. I try investigate it, and it seems this error appear when there is cucumber feature with no feature description on it (As a... I want to... So that.....).
Which is weird because previous serenity version is working well even there is no feature description.

Version used
```
serenity-core v2.3.12
serenity-cucumber6 v2.3.12
```

Error stacktrace
```
org.junit.runner.notification.StoppedByUserException
	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:116)
	at org.apache.maven.surefire.common.junit4.Notifier.fireTestStarted(Notifier.java:100)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:133)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:234)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wakaleo** [comment]
I can't reproduce this - features without scenario descriptions seem to work just fine.

**Comment by billyjulius** [comment]
So I found this error is cause by another package `serenity-reportportal-integration` which is weird because in previous version it is worked well. If I disable that package, serenity worked normal and that error is gone. So I think something in that package that break the proccess, not the Serenity itself. I will look into that package repo.
Thank you for the response though and I'm sorry for the inconvenience.
