### ISSUE TITLE
The Step class is null PointerException

### ISSUE THREAD

**Issue by vinhtrangithub** [serenity-bdd/serenity-core#2457]
``Hi all,
I got this error

19:39:41.027 [main] INFO  n.s.c.w.d.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [], extensions: []}, loggingPrefs: org.openqa.selenium.logging...}
Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 21382
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
May 13, 2021 7:39:43 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

java.lang.NullPointerException
	at starter.math.WhenAddingNumbers.addingSums(WhenAddingNumbers.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:467)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:441)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:57)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:250)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

and here is my running code
`package starter.math;

import net.serenitybdd.junit.runners.SerenityRunner;
import net.thucydides.core.annotations.Managed;
import net.thucydides.core.annotations.Narrative;
import net.thucydides.core.annotations.Pending;
import net.thucydides.core.annotations.Steps;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import starter.steps.MathWizSteps;
import steps.CellPhoneSteps;
import steps.TGDDSteps;

@RunWith(SerenityRunner.class)
public class WhenAddingNumbers {

    private String cellPhoneURL = "https://cellphones.com.vn/";
    private String searchName = "iPhone 11";

    @Managed
    WebDriver driver;

    @Steps
    public CellPhoneSteps cellPhoneSteps;
    public TGDDSteps tgddSteps;

    @Test
    public void addingSums() {
        driver.get("https://www.google.com/");
        tgddSteps.searchItem(searchName); //<~~~ error is this step

        //new WebDriverWait(driver,5).until(ExpectedConditions.titleContains("firefly - Google"));

        //assertThat(driver.getTitle()).contains("firefly - Google");
        /*// Given
        michael.startsWith(1);

        // When
        michael.adds(2);

        // Then
        michael.shouldHave(3);*/
    }
}
`

**Comment by wakaleo** [comment]
`tgddSteps` needs to be annotated with the `@Steps` annotation.

**Comment by vinhtrangithub** [comment]
Yes, thanks, it resolved now.
