### ISSUE TITLE
Serenity aggregate report issue

### ISSUE THREAD

**Issue by suadhika** [serenity-bdd/serenity-core#2461]
All the report htmls  are created but its not generating aggregated report. Below is the stack trace and my configuration details:

gradle version: 7.0.2
serenity version: "2.4.4
java version: 1.8.0_271

build.gradle

`apply plugin: 'java'
apply plugin: 'maven'
apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: 'net.serenity-bdd.aggregator'

repositories {
    mavenLocal()
    jcenter()
}

ext{
    serenity_version = "2.4.4"
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:2.4.4")
        classpath ("net.serenity-bdd:serenity-single-page-report:2.4.4")
    }
}

group = 'serenity-cucumber-bdd-screenplay'
version = '1.0.0-SNAPSHOT'

description = """"""

sourceCompatibility = 8
targetCompatibility = 8
tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.8'
    annotationProcessor 'org.projectlombok:lombok:1.18.8'
    compile group: 'net.serenity-bdd', name: 'serenity-core', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-junit', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-cucumber6', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-screenplay', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-screenplay-rest', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-screenplay-webdriver', version:"$serenity_version"
    testCompile group: 'io.cucumber', name: 'cucumber-java', version:'6.10.0'
    testCompile group: 'io.cucumber', name: 'cucumber-junit', version:'6.10.0'
    testCompile group: 'junit', name: 'junit', version:'4.13'
    testCompile group: 'org.slf4j', name: 'slf4j-simple', version:'1.7.30'
}

test {
    testLogging {
        showStandardStreams = true
    }
    // Set maxParallelForks using project property
    // testMaxParallelForks if set otherwise use 1.
    maxParallelForks = project.findProperty('testMaxParallelForks') ?: 1
    /* Pass all system properties*/
    systemProperties System.getProperties()
}

task copyDeps(type: Copy){
    from configurations.runtime
    into project.projectDir.path+"/lib"
}

gradle.startParameter.continueOnFailure = true`

Stack trace:
 `        at net.thucydides.core.reports.html.RequirementsOverviewReportingTask.generateReports(RequirementsOverviewReportingTask.java:103)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:33)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:12)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Failed to generate report for net.thucydides.core.reports.html.ErrorTypeReportingTask@8d17f92 - java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: kotlin.collections.CollectionsKt.minOrNull(Ljava/lang/Iterable;)Ljava/lang/Comparable;
net.serenitybdd.reports.model.DurationsKt.startToFinishTimeIn(Durations.kt:45)
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: kotlin.collections.CollectionsKt.minOrNull(Ljava/lang/Iterable;)Ljava/lang/Comparable;
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at net.thucydides.core.reports.html.Reporter.generateReports(Reporter.java:56)
        at net.thucydides.core.reports.html.Reporter.generateReportsFor(Reporter.java:32)
        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:211)
        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:136)
        at net.thucydides.core.reports.UserStoryTestReporter$generateReportsForTestResultsFrom.call(Unknown Source)
        at net.serenitybdd.plugins.gradle.SerenityPlugin$_apply_closure1$_closure9.doCall(SerenityPlugin.groovy:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:724)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:697)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:273)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:258)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: kotlin.collections.CollectionsKt.minOrNull(Ljava/lang/Iterable;)Ljava/lang/Comparable;
        at net.serenitybdd.reports.model.DurationsKt.startToFinishTimeIn(Durations.kt:45)
        at net.serenitybdd.reports.model.DurationsKt.clockDurationOf(Durations.kt:38)
        at net.thucydides.core.reports.html.FreemarkerContext.getBuildContext(FreemarkerContext.java:108)
        at net.thucydides.core.reports.html.ErrorTypeReportingTask.generateReports(ErrorTypeReportingTask.java:42)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:33)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:12)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
SOME REPORT PAGES COULD NOT BE GENERATED
 * Failed to generate report for Test Summary Report - java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: kotlin.collections.CollectionsKt.minOrNull(Ljava/lang/Iterable;)Ljava/lang/Comparable;
net.serenitybdd.reports.model.DurationsKt.startToFinishTimeIn(Durations.kt:45)

 * Failed to generate report for net.thucydides.core.reports.html.AggregateReportingTask@7a72418e - java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: kotlin.collections.CollectionsKt.minOrNull(Ljava/lang/Iterable;)Ljava/lang/Comparable;
net.serenitybdd.reports.model.DurationsKt.startToFinishTimeIn(Durations.kt:45)`

**Comment by suadhika** [comment]
Changed the build.gradle as below and the issue is resolved.
`apply plugin: 'java'
apply plugin: "idea"
apply plugin: 'net.serenity-bdd.aggregator'

repositories {
    mavenLocal()
    jcenter()
}

ext{
    serenity_version = "2.4.4"
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:2.4.4")
        classpath ("net.serenity-bdd:serenity-single-page-report:2.4.4")
    }
}

group = 'serenity-cucumber-bdd-screenplay'
version = '1.0.0-SNAPSHOT'

description = """"""

sourceCompatibility = 8
targetCompatibility = 8
tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}


dependencies {
    implementation 'org.projectlombok:lombok:1.18.8'
    annotationProcessor 'org.projectlombok:lombok:1.18.8'
    implementation group: 'net.serenity-bdd', name: 'serenity-core', version:"$serenity_version"
    implementation group: 'net.serenity-bdd', name: 'serenity-junit', version:"$serenity_version"
    implementation group: 'net.serenity-bdd', name: 'serenity-cucumber6', version:"$serenity_version"
    implementation group: 'net.serenity-bdd', name: 'serenity-screenplay', version:"$serenity_version"
    implementation group: 'net.serenity-bdd', name: 'serenity-screenplay-rest', version:"$serenity_version"
    implementation group: 'net.serenity-bdd', name: 'serenity-screenplay-webdriver', version:"$serenity_version"
    implementation group: 'io.cucumber', name: 'cucumber-java', version:'6.10.0'
    implementation group: 'io.cucumber', name: 'cucumber-junit', version:'6.10.0'
    implementation group: 'junit', name: 'junit', version:'4.13'
    implementation group: 'org.slf4j', name: 'slf4j-simple', version:'1.7.30'
}

test {
    testLogging {
        showStandardStreams = true
    }
    // Set maxParallelForks using project property
    // testMaxParallelForks if set otherwise use 1.
    maxParallelForks = project.findProperty('testMaxParallelForks') ?: 1
    /* Pass all system properties*/
    systemProperties System.getProperties()
}


task copyDeps(type: Copy){
    from configurations.runtimeOnly
    into project.projectDir.path+"/lib"
}

gradle.startParameter.continueOnFailure = true`
