### ISSUE TITLE
Serenity 2.4.x report doesn't display screenshot after upgrading

### ISSUE THREAD

**Issue by antuking** [serenity-bdd/serenity-core#2464]
Hello everybody,

I'm facing the issue can't take screenshot for Serenity's version 2.4.5 which have ever been upgraded from 2.0.71.1. After I try to run specific scenario successfully, I see that the issue relates to `SerenityParameterizedRunner` at the console log as below:

>      WARN net.serenitybdd.core.photography.PhotoSession - Failed to take screenshot
        at AppiumDriver.execuorg.openqa.selenium.UnsupportedCommandException: Method is not implemented
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:467)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:441)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:57)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:250)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at net.serenitybdd.junit.runners.SerenityParameterizedRunner.run(SerenityParameterizedRunner.java:217)

Please help me give more suggestions to resolve this one. Btw, I tried to add `junit-vintage-engine` into `maven-surefire-plugin`. But this one still occur then

**Comment by wakaleo** [comment]
It's an issue with your appium version: "AppiumDriver.execuorg.openqa.selenium.UnsupportedCommandException: Method is not implemented". Make sure you are using a version of Appium that corresponds to the version of Serenity you are using (see https://github.com/serenity-bdd/serenity-core#what-is-the-latest-stable-version-i-should-use)

**Comment by antuking** [comment]
Thanks for your inform @wakaleo . Let me try this one.
