### ISSUE TITLE
MicrosoftEdge browser not supported (Selenoid)

### ISSUE THREAD

**Issue by mlarrea** [serenity-bdd/serenity-core#2468]
Recently aerokube has added Edge to the available browser containers in Selenoid, but Selenoid requires referring to them as "MicrosoftEdge". Then serenity throws an error because this browser name is not on the list of supported browsers. Could this be fixed from serenity's side?

**Comment by wakaleo** [comment]
Can you provide a PR?

**Comment by mlarrea** [comment]
I'm afraid I don't have that knowledge about your project

**Comment by wakaleo** [comment]
Do you have a stack trace or some more details about the issue you are seeing?

**Comment by mlarrea** [comment]
If we use "MicrosoftEdge":
      java.lang.AssertionError: Unsupported driver for webdriver.driver or webdriver.remote.driver: MicrosoftEdge. Did you mean remote?
	at net.serenitybdd.core.webdriver.driverproviders.DriverCapabilities.driverTypeFor(DriverCapabilities.java:60)
	at net.serenitybdd.core.webdriver.driverproviders.DriverCapabilities.forDriver(DriverCapabilities.java:39)
	at net.serenitybdd.core.webdriver.driverproviders.DefaultRemoteDriver.buildRemoteCapabilities(DefaultRemoteDriver.java:32)
	at net.serenitybdd.core.webdriver.driverproviders.DefaultRemoteDriver.buildWithOptions(DefaultRemoteDriver.java:23)
	at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider.newInstance(RemoteDriverProvider.java:54)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:170)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:151)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.executeScript(WebDriverFacade.java:373)
	at com.adidas.pe.te.serenitybdd.seed.fe.web.page_objects.WiktionaryPage.openAndMaximize(WiktionaryPage.java:55)
	at com.adidas.pe.te.serenitybdd.seed.fe.web.cucumber_steps.WiktionarySteps.isTheHomePage(WiktionarySteps.java:31)
	at com.adidas.pe.te.serenitybdd.seed.fe.web.cucumber_steps.WiktionarySteps$ByteBuddy$pwPN9PE2.isTheHomePage$accessor$tjCktxPI(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:492)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:472)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:445)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:201)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:188)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:76)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	.......

**Comment by mlarrea** [comment]
When using "edge" the error is thrown from Selenoid

**Comment by priyathambiran** [comment]
Hi Team, Any idea when does an edge issue on selenoid will be fixed? Thanks

**Comment by wakaleo** [comment]
Try with 2.4.48, or dig into t code and propose a PR
