### ISSUE TITLE
Serenity with restAssured execution error Preconditions.checkArgument

### ISSUE THREAD

**Issue by sudheerah** [serenity-bdd/serenity-core#2478]
Hi,

I am using serenity-cucumber6 with RestAssured for my API testing. I am using below dependencies. 

```
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>2.3.12</serenity.version>
        <serenity.maven.version>2.3.12</serenity.maven.version>
        <serenity.cucumber.version>2.3.12</serenity.cucumber.version>
        <logback.version>1.2.3</logback.version>
        <encoding>UTF-8</encoding>
    </properties>

<dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>4.3.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-path</artifactId>
            <version>4.3.2</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber6</artifactId>
            <version>${serenity.cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.6.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>

    </dependencies>
```

But when run the feature file I am getting below error which seems to selenium, related. However, **I DO NOT want to do any UI testing here**. So looks like dependency related issue. Further I could see **org.seleniumhq.selenium....** packages under External Libraries as well. Not sure why they have been downloaded as I don't have anything relating to selenium in my POM.

**Error:**

```
Step failed
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.google.inject.Key.ensureRetainedAtRuntime(Key.java:341)
	at com.google.inject.Key.strategyFor(Key.java:335)
	at com.google.inject.Key.get(Key.java:250)
	at com.google.inject.internal.AbstractBindingBuilder.annotatedWithInternal(AbstractBindingBuilder.java:77)
	at com.google.inject.internal.BindingBuilder.annotatedWith(BindingBuilder.java:51)
	at com.google.inject.internal.BindingBuilder.annotatedWith(BindingBuilder.java:42)
	at net.thucydides.core.guice.ThucydidesModule.configure(ThucydidesModule.java:62)
	at net.thucydides.core.guice.webdriver.WebDriverModule.configure(WebDriverModule.java:17)
```

**Comment by wakaleo** [comment]
"java.lang.NoSuchMethodError" is pretty much always a version conflict. I'm not sure what it is in this particular case though - you would need to do a dependency analysis. The selenium dependencies come with serenity-code, you can't exclude them.

**Comment by sudheerah** [comment]
@wakaleo I basically got the same dependencies as this https://github.com/serenity-bdd/serenity-rest-starter.git. 
When you say "The selenium dependencies come with **serenity-code**," Did you mean to say **serenity-core**?

Since I have mentioned the versions I am using what more details you reckon to help identify the root-cause?

**Comment by wakaleo** [comment]
Yes, I meant serenity-core. Just run a maven dependency analysis and look for conflicts.

**Comment by sudheerah** [comment]
@wakaleo 
I can see below conflicts

```
   +- (io.rest-assured:rest-assured:jar:3.0.2:test - version managed from 4.3.2; omitted for conflict with 4.3.2)
|  +- (io.cucumber:cucumber-java:jar:6.9.1:test - omitted for conflict with 6.6.0)
|  +- io.cucumber:cucumber-junit:jar:6.9.1:test
|  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
|  |  \- (io.cucumber:cucumber-core:jar:6.9.1:test - omitted for conflict with 6.6.0)
|  +- io.cucumber:datatable-matchers:jar:3.4.0:test
|  |  +- (org.apiguardian:apiguardian-api:jar:1.1.0:test - omitted for duplicate)
|  |  +- (io.cucumber:datatable:jar:3.4.0:test - omitted for duplicate)
|  |  \- (org.hamcrest:hamcrest:jar:2.2:test - omitted for conflict with 2.1)
```

**Comment by wakaleo** [comment]
Have you tried with serenity 2.4.24?

**Comment by sudheerah** [comment]
I've got below with 2.4.24

```
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>2.4.24</serenity.version>
        <serenity.maven.version>2.4.24</serenity.maven.version>
        <serenity.cucumber.version>2.4.24</serenity.cucumber.version>
```

Conflicts

```
|  +- net.serenity-bdd:serenity-model:jar:2.4.24:test
|  |  +- (net.serenity-bdd:serenity-report-resources:jar:2.4.24:test - omitted for duplicate)
|  |  +- (org.hamcrest:hamcrest:jar:2.2:test - omitted for conflict with 2.1)
|  |  +- io.cucumber:cucumber-core:jar:6.10.2:test
|  |  |  +- io.cucumber:cucumber-gherkin:jar:6.10.2:test
|  |  |  |  \- (io.cucumber:cucumber-plugin:jar:6.10.2:test - omitted for duplicate)
|  |  |  +- io.cucumber:cucumber-gherkin-messages:jar:6.10.2:test
|  |  |  |  \- (io.cucumber:cucumber-gherkin:jar:6.10.2:test - omitted for duplicate)
|  |  |  +- io.cucumber:messages:jar:14.0.1:test
|  |  |  +- io.cucumber:tag-expressions:jar:3.0.0:test
|  |  |  +- io.cucumber:cucumber-expressions:jar:10.3.0:test
|  |  |  +- (io.cucumber:datatable:jar:3.5.0:test - omitted for conflict with 3.4.0)

|  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:2.53.1:test
|  |  +- (org.seleniumhq.selenium:selenium-remote-driver:jar:2.53.1:test - version managed from 3.141.59; omitted for duplicate)
|  |  +- (commons-io:commons-io:jar:2.4:test - omitted for conflict with 2.8.0)

|  +- io.github.bonigarcia:webdrivermanager:jar:4.4.1:test
|  |  +- (org.slf4j:slf4j-api:jar:1.7.25:test - version managed from 1.7.30; omitted for duplicate)
|  |  +- (commons-io:commons-io:jar:2.8.0:test - omitted for duplicate)
|  |  +- (com.google.code.gson:gson:jar:2.8.2:test - version managed from 2.8.6; omitted for duplicate)
|  |  +- (org.apache.commons:commons-lang3:jar:3.12.0:test - omitted for conflict with 3.11)

|  |  +- (org.seleniumhq.selenium:selenium-java:jar:2.53.1:test - version managed from 3.141.59; omitted for duplicate)
|  |  +- (commons-io:commons-io:jar:2.6:test - omitted for conflict with 2.8.0)

+- net.serenity-bdd:serenity-rest-assured:jar:2.4.24:test
|  +- (net.serenity-bdd:serenity-core:jar:2.4.24:test - omitted for duplicate)
|  +- (io.rest-assured:rest-assured:jar:3.0.2:test - version managed from 4.3.3; omitted for conflict with 4.3.2)

|  +- io.cucumber:datatable-matchers:jar:3.4.0:test
|  |  +- (org.apiguardian:apiguardian-api:jar:1.1.0:test - omitted for conflict with 1.1.1)
|  |  +- io.cucumber:datatable:jar:3.4.0:test
|  |  |  \- (org.apiguardian:apiguardian-api:jar:1.1.0:test - omitted for conflict with 1.1.1)
|  |  \- (org.hamcrest:hamcrest:jar:2.2:test - omitted for conflict with 2.1)
```

**Comment by wakaleo** [comment]
And does it work?

**Comment by sudheerah** [comment]
As mentioned same error.

**Comment by wakaleo** [comment]
`java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument` is a conflict with the guava version. That's what you need to look for and fix.

**Comment by sudheerah** [comment]
I added guava dependency which was missing before

```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>30.1-jre</version>
        </dependency>
```

Then get different error:

```
Step failed
java.lang.NoClassDefFoundError: org/openqa/selenium/WrapsElement
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
```

**Comment by wakaleo** [comment]
java.lang.NoClassDefFoundError does not mean the class or library is missing, it means that the wrong version is being used. Try starting with a known working set of dependencies, e.g. in https://github.com/serenity-bdd/serenity-rest-starter.

**Comment by sudheerah** [comment]
@wakaleo I am using exactly the same versions and combinations as  https://github.com/serenity-bdd/serenity-rest-starter.
Only thing is I don't have below since I got one parent POM already.

```
        <parent>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-parent</artifactId>
            <version>2.4.2</version>
        </parent>
```
Is there an option to add above parent in addition to my existing one?

**Comment by sudheerah** [comment]
@wakaleo If I use cucumber-java, should I exclude cucumber-core from serenity-core?
