### ISSUE TITLE
Cannot run Serevity cucumber tests with tags

### ISSUE THREAD

**Issue by sudheerah** [serenity-bdd/serenity-core#2489]
Hello,

I am using below versions with `serenity-cucumber6`

```
        <serenity.plugin.version>2.4.34</serenity.plugin.version>
        <serenity.version>2.4.34</serenity.version>
        <serenity.cucumber.version>2.4.34</serenity.cucumber.version>
        <cucumber.version>6.10.4</cucumber.version>
        <maven-plugin.version>3.0.0-M5</maven-plugin.version>
        <java.version>1.8</java.version>
```

Main class

```
import org.junit.runner.RunWith;

import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
    plugin = {"pretty", "html:target/reports/cucumber-html-report"},
    glue = {"my.stepdefinitions"},
    tags = "not @skip",
    features = "src/it/resources/features/"
)

public class MyCucumberTests {
}
```

I was trying to run identified test with tags as below config in IntelliJ

![image](https://user-images.githubusercontent.com/6559722/122483583-43c87280-d016-11eb-97a7-ccda14d9c7a0.png)

Then I got below error

```
Step failed
java.lang.NoSuchMethodError: io.restassured.config.LogConfig.blacklistedHeaders()Ljava/util/Set;
	at net.serenitybdd.rest.utils.RestReportingHelper.registerCall(RestReportingHelper.java:69)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.reportQuery(RequestSpecificationDecorated.java:292)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.execute(RequestSpecificationDecorated.java:284)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.get(RequestSpecificationDecorated.java:67)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.get(RequestSpecificationDecorated.java:38)
	at my.specs.RequestSpecs.getRequest(RequestSpecs.java:29)
	at my.stepdefinitions.CommonStepDefs.iCallEndPoint(CommonStepDefs.java:70)
```

But When I change the Main class to :` io.cucumber.core.cli.Main`, I was able to run tests. But runs all the test NOT just with specified tags as specify in the VM Options in the above IDE edit config. (e.g. `-Dcucumber.options="--tags @Demo"`)

**Comment by sudheerah** [comment]
I tried command line as well,  with `mvn clean verify -Drun.jvmArguments="-Dspring.profiles.active=it"` it also gives the same above error

**Comment by wakaleo** [comment]
Run it as a plain JUnit test.

**Comment by sudheerah** [comment]
@wakaleo Can you please explain bit further like If use intelliJ, what are the edot config settings Or command to run from command line

**Comment by BeanSDET** [comment]
if you're using cucumber 6 then you need to pass this flag to run by tags `-Dcucumber.filter.tags="@Demo"`

**Comment by wakaleo** [comment]
Closing presumed answered.
