### ISSUE TITLE
Serenity browserstack integration throwing error-Failed to generate configuration report

### ISSUE THREAD

**Issue by srilakshmishankar** [serenity-bdd/serenity-core#2509]
I am using serenity-core: 2.4.48
net.serenity-bdd:serenity-gradle-plugin:2.4.34
net.serenity-bdd:serenity-single-page-report:2.4.48
net.serenity-bdd:serenity-browserstack:2.4.48
net.serenity-bdd:serenity-reports:2.4.48
net.serenity-bdd:serenity-cucumber6:2.4.48
Also I have serenity-rest-assure and serenity-spring latest

I dont get error if I remove net.serenity-bdd:serenity-browserstack:2.4.48
I tried with previous versions til 2.3.33 and still same error

The target folder is generated as well but I always get below error, this makes the pipeline/job fail even though tests have passed. I html report I cannot see BDD steps and screenshots in report. 

More info:
This is multi gradle project. I have buildSrc and main gradle project and gradle command is like this
gradle clean test aggregate reports

Stack-trace:

`Failed to generate configuration report
net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:211)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:188)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:134)
	at io.cucumber.core.plugin.SerenityReporter.generateReports(SerenityReporter.java:945)
	at io.cucumber.core.plugin.SerenityReporter.handleTestRunFinished(SerenityReporter.java:370)
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
	at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:93)
	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:74)
	at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:288)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@733fd07a
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:208)
	... 41 more
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@733fd07a
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:248)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:184)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
Caused by: java.lang.RuntimeException: Failed to merge template: Failed to process FreeMarker template
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:39)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:164)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:134)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:246)
	... 6 more
Caused by: net.thucydides.core.reports.templates.TemplateMergeException: Failed to process FreeMarker template
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:41)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:37)
	... 9 more
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> testOutcome.externalLink.url  [in template "freemarker/default.ftl" at line 202, column 44]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${testOutcome.externalLink.url}  [in template "freemarker/default.ftl" at line 202, column 42]
----
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:479)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:331)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.process(Environment.java:310)
	at net.thucydides.core.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:38)
	... 10 more`

**Comment by wakaleo** [comment]
Try with serenity-gradle-plugin:2.4.48

**Comment by srilakshmishankar** [comment]
Still same error with serenity-gradle-plugin:2.4.48

Also here latest version was 2.4.34: https://mvnrepository.com/artifact/net.serenity-bdd/serenity-gradle-plugin/2.4.34
hence was using 2.4.34.

Now all versions at 2.4.48. If I remove implementation "net.serenity-bdd:serenity-browserstack:2.4.48" I will not get this error.

**Comment by srilakshmishankar** [comment]
@wakaleo I am blocked with BS integration because of this. Any other suggestions. Earlier I was not using dependency and just ran on BS by:
-Denvironment=staging -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.url=http://<user.token>@hub-cloud.browserstack.com/wd/hub 
This solution works but I cannot set resolution, os, os_version etc on browser. Default versions are selected in this case and I have failing tests. hence I want to go for serenity BS dependency.

**Comment by srilakshmishankar** [comment]
May be related? https://github.com/serenity-bdd/serenity-core/issues/1442

**Comment by srilakshmishankar** [comment]
I have tried the solution mentioned here with all serenity related versions 2.4.48 and 2.4.34

**Comment by wakaleo** [comment]
2.4.48 and 2.4.34 are not compatible - all versions need to be 2.4.48.

The Serenity Gradle Plugin is now deployed directly to the Gradle plugins repo: https://plugins.gradle.org/plugin/net.serenity-bdd.serenity-gradle-plugin

Can you post your browserstack config here?

**Comment by srilakshmishankar** [comment]
In serenity.conf I have below:
browserstack.os = windows
browserstack.os_version = 10
browserstack.browser_version = 91
browserstack.resolution = 1280x1024

gradle command:
./gradlew clean test aggregate reports
-Denvironment=staging -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.url=http://<mybscredentials>@hub-cloud.browserstack.com/wd/hub -DCUCUMBER_FILTER_TAGS="@test"

**Comment by srilakshmishankar** [comment]
My main build.gradle

`import com.github.spotbugs.snom.SpotBugsTask

import java.util.stream.Collectors

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath "net.serenity-bdd:serenity-gradle-plugin:2.4.48"
        classpath "net.serenity-bdd:serenity-single-page-report:2.4.48"
    }
}

plugins {
    id 'com.github.spotbugs' version '4.7.1'
    id 'com.diffplug.spotless' version '5.14.1'
    id 'java'
    id 'pmd'
    id "io.freefair.lombok" version "5.3.3.3"
}

apply plugin: 'net.serenity-bdd.aggregator'
apply plugin: "net.serenity-bdd.serenity-gradle-plugin"

group 'com.platform'
version '1.0-SNAPSHOT'
sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
}

ext {
    assertJVersion = '3.20.2'
    cucumberVersion = '6.10.4'
    jacksonVersion = '2.12.3'
    junitVersion = '5.7.2'
    serenityCoreVersion = '2.4.48'
    serenityCucumberVersion = '2.4.48'
    springBootVersion = '2.5.2'
}

dependencies {
    implementation "net.serenity-bdd:serenity-rest-assured:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-browserstack:2.4.48"
    implementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-reports:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-spring:${serenityCoreVersion}"
    implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
    implementation "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    testImplementation "io.cucumber:cucumber-junit:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-java8:${cucumberVersion}"
    testImplementation "net.serenity-bdd:serenity-cucumber6:${serenityCucumberVersion}"
    testImplementation "net.serenity-bdd:serenity-junit:${serenityCoreVersion}"
    testImplementation "org.assertj:assertj-core:${assertJVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
    testImplementation "org.junit.vintage:junit-vintage-engine:${junitVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testImplementation "io.github.bonigarcia:webdrivermanager:4.4.3"
}
`

And build.gradle from buildSrc:

`import com.github.spotbugs.snom.SpotBugsTask

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:4.7.1"
        classpath "com.diffplug.spotless:spotless-plugin-gradle:5.14.1"
    }
}

plugins {
    id 'java-library'
    id 'pmd'
}

apply plugin: "com.github.spotbugs"
apply plugin: "com.diffplug.spotless"

repositories {
    mavenCentral()
}
ext {
    serenityCoreVersion = '2.4.48'
    junitVersion = '5.7.2'
}

dependencies {
    implementation "com.slack.api:slack-api-client:1.8.1"
    implementation "io.prometheus:simpleclient:0.11.0"
    implementation "io.prometheus:simpleclient_pushgateway:0.11.0"
    implementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-reports:${serenityCoreVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
}`

**Comment by srilakshmishankar** [comment]
> Your error is due to a version conflict in the Serenity libraries. 2.4.48 and 2.4.34 are not compatible - all versions need to be 2.4.48.
> 
> The Serenity Gradle Plugin is now deployed directly to the Gradle plugins repo: https://plugins.gradle.org/plugin/net.serenity-bdd.serenity-gradle-plugin
> 
> Can you post your browserstack config here?

@wakaleo 
I have 2.4.48 with all even then same error. I have listed all dependencies above.

**Comment by srilakshmishankar** [comment]
This one below you see anything?

`Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> testOutcome.externalLink.url  [in template "freemarker/default.ftl" at line 202, column 44]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
`

**Comment by wakaleo** [comment]
Have you looked into the code? Have a look at the AfterABrowserStackScenario class, and see what it is producing.

**Comment by srilakshmishankar** [comment]
This was fixed with below serenity.conf properties:
browserstack.server = hub-cloud.browserstack.com/wd/hub
browserstack.os = windows
browserstack.os_version = 10
browserstack.browser_version = 93
browserstack.resolution = 1920x1200
