### ISSUE TITLE
error with  net.serenity-bdd:serenity-core version 2.5.8

### ISSUE THREAD

**Issue by ccrj1105** [serenity-bdd/serenity-core#2531]
after update dependency` net.serenity-bdd:serenity-core:2.5.8 `and `net.serenity-bdd:serenity-screenplay-rest:2.5.8`  i run my  test and show this error

```
`java.lang.NoClassDefFoundError: io/cucumber/core/options/FeatureOptions

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.ClassNotFoundException: io.cucumber.core.options.FeatureOptions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more`
```

**Comment by ccrj1105** [comment]
my build.gradle file

```
ext{
    serenity_core_version = "2.5.8"
    serenity_cucumber_version = "6.11.0"
    serenity_cucumber4_version = "2.1.2"
}
dependencies {
//    compile localGroovy()
    compile "net.serenity-bdd:serenity-core:$serenity_core_version"
    compile "net.serenity-bdd:serenity-junit:$serenity_core_version"
    compile "io.cucumber:cucumber-java:$serenity_cucumber_version"
    compile "io.cucumber:cucumber-junit:$serenity_cucumber_version"
    compile "net.serenity-bdd:serenity-screenplay:$serenity_core_version"
    compile "net.serenity-bdd:serenity-screenplay-webdriver:$serenity_core_version"
    compile "net.serenity-bdd:serenity-emailer:2.1.0"
    compile "net.serenity-bdd:serenity-screenplay-rest:$serenity_core_version"
    compile "net.serenity-bdd:serenity-cucumber4:$serenity_cucumber4_version"
    compile "net.serenity-bdd:serenity-junit:$serenity_core_version"

    /*Persistence*/
    compile "org.hibernate:hibernate-core:5.4.10.Final"
    compile "javax.persistence:javax.persistence-api:2.2"
    implementation      "mysql:mysql-connector-java:8.0.19"
    compile "com.zaxxer:HikariCP:3.4.2"

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.10.0'
    implementation 'com.fasterxml.jackson.module:jackson-module-parameter-names:2.10.0'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.10.0'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.10.0'
    implementation 'com.github.javafaker:javafaker:1.0.1'
    implementation 'redis.clients:jedis:3.1.0'
    implementation 'biz.paluch.redis:lettuce:3.2.Final'

    /* Lombok */
    compileOnly 'org.projectlombok:lombok:1.18.10'
    annotationProcessor 'org.projectlombok:lombok:1.18.10'
    testCompile 'org.slf4j:slf4j-simple:1.7.7'
    testCompile 'junit:junit:4.13.2'
    testCompile 'org.assertj:assertj-core:1.7.0'

    /* testrail */
    compile "com.codepine.api:testrail-api-java-client:2.0.1"

}
```

**Comment by wakaleo** [comment]
Use the recommended version combinations (https://github.com/serenity-bdd/serenity-core/blob/master/README.md#serenity-with-cucumber) - Serenity 2.5.8 is not compatible with Cucumber 4 (see https://github.com/serenity-bdd/serenity-core/blob/master/README.md#cucumber-4)

**Comment by wakaleo** [comment]
Closing presumed answered.
