### ISSUE TITLE
Cucumber step definition no longer linked to feature files

### ISSUE THREAD

**Issue by tquality** [serenity-bdd/serenity-core#2550]
I upgraded to cucumber 6 en serenity core 2.6.0. But since the upgrade the steps and the feature files are no longe r linked. I have following glue setup:

```
import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(features = {"src/test/resources/features"},
        glue = {"be.nbb.hive.cucumber.steps"})
public class CucumberRunner {
```

But when I run my tests in the feature file I get following message

`Exception in thread "main" io.cucumber.core.exception.CucumberException: java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 15
^I click on (?:?:the )?\?(?:.*)?(?:?:.*)? \((name|id|css|xpath\): \?(?:.+)?\\)$
               ^
	at io.cucumber.core.runtime.CucumberExecutionContext.getException(CucumberExecutionContext.java:82)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:103)
	at net.serenitybdd.cucumber.cli.Main.run(Main.java:27)
	at net.serenitybdd.cucumber.cli.Main.main(Main.java:18)
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 15
^I click on (?:?:the )?\?(?:.*)?(?:?:.*)? \((name|id|css|xpath\): \?(?:.+)?\\)$
               ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.sequence(Pattern.java:2123)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.group0(Pattern.java:2821)
	at java.util.regex.Pattern.sequence(Pattern.java:2051)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1054)
	at io.cucumber.cucumberexpressions.DefaultPatternCompiler.compile(DefaultPatternCompiler.java:12)
	at io.cucumber.cucumberexpressions.TreeRegexp.<init>(TreeRegexp.java:22)
	at io.cucumber.cucumberexpressions.CucumberExpression.<init>(CucumberExpression.java:37)
	at io.cucumber.cucumberexpressions.ExpressionFactory.createExpression(ExpressionFactory.java:34)
	at io.cucumber.core.stepexpression.StepExpressionFactory.crateExpression(StepExpressionFactory.java:88)
	at io.cucumber.core.stepexpression.StepExpressionFactory.createExpression(StepExpressionFactory.java:61)
	at io.cucumber.core.stepexpression.StepExpressionFactory.createExpression(StepExpressionFactory.java:49)
	at io.cucumber.core.runner.CachingGlue.lambda$prepareGlue$3(CachingGlue.java:244)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.cucumber.core.runner.CachingGlue.prepareGlue(CachingGlue.java:243)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:70)
	at io.cucumber.core.runtime.Runtime.lambda$execute$5(Runtime.java:110)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
	at io.cucumber.core.runtime.Runtime.lambda$execute$6(Runtime.java:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:233)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:86)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:87)
	... 2 more`

Is something going wrong or am I doing something wrong?

**Comment by wakaleo** [comment]
The Cucumber APIs changed a lot in Cucumber 6, so your step definitions will no longer all work. See https://cucumber.io/docs/cucumber/step-definitions/.

**Comment by tquality** [comment]
But the linking should be the same no? I'm not really seeing a major difference from what I have at the moment

**Comment by wakaleo** [comment]
No, the step definitions are quite different and many things that work in Cucumber 4 and 5 need to be rewritten for Cucumber 6.

**Comment by tquality** [comment]
So it's better to go from cucumber to cucumber4? As we try to fix following issue 

`Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Error forwarding the new session new session request for webdriver should contain a location header or an 'application/json;charset=UTF-8' response body with the session ID.`

I found in another post that we should upgrade we had at that time following versions:
`<serenity.version>2.1.5</serenity.version>
        <serenity.cucumber.version>1.9.50</serenity.cucumber.version>`

**Comment by wakaleo** [comment]
No, Cucumber 4 is no longer supported

**Comment by wakaleo** [comment]
Closing as related to IntelliJ, not Serenity.
