### ISSUE TITLE
JUnit 5: Parallel execution -> NullPointerException: No BaseStepListener has been registered

### ISSUE THREAD

**Issue by Dvoreth** [serenity-bdd/serenity-core#2563]
I'm using the following versions:

<serenity.version>2.6.0</serenity.version>
<junit.version>5.8.0</junit.version>

Tests work fine when executed sequentially, but if I use JUnit 5's parallelization, it looks like there's an issue involving the SerenityTestExecutionListener when starting and finishing tests:

`[ERROR] WARNING: TestExecutionListener [net.serenitybdd.junit5.SerenityTestExecutionListener] threw exception for method: executionFinished(TestIdentifier [uniqueId = '[engine:junit-
jupiter]/[class:redacted.class.name]/[method:redacted()]', parentId = '[engine:junit-jupi
ter]/[class:redacted.class.name]', displayName = 'redacted()', legacyReportingName = 'redacted()', source = MethodSource [className = 'redacted.class.name', methodName = 'redacted', methodParameterTypes = ''], tags = [], type = TEST], TestExecutionResult [status = SUCCESSFUL, throwable = null])
[ERROR] java.lang.NullPointerException: No BaseStepListener has been registered - are you running your test using the Serenity runners?
[ERROR]         at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
[ERROR]         at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:153)
[ERROR]         at net.thucydides.core.steps.StepEventBus.testFinished(StepEventBus.java:336)
[ERROR]         at net.thucydides.core.steps.StepEventBus.testFinished(StepEventBus.java:355)
[ERROR]         at net.serenitybdd.junit5.SerenityTestExecutionListener.testFinished(SerenityTestExecutionListener.java:329)
[ERROR]         at net.serenitybdd.junit5.SerenityTestExecutionListener.executionFinished(SerenityTestExecutionListener.java:270)
[ERROR]         at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionFinished$10(TestExecutionListenerRegistry.java:109)
[ERROR]         at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67)
[ERROR]         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[ERROR]         at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyEach(TestExecutionListenerRegistry.java:65)
[ERROR]         at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$200(TestExecutionListenerRegistry.java:32)
[ERROR]         at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.executionFinished(TestExecutionListenerRegistry.java:108)
[ERROR]         at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56)
[ERROR]         at org.junit.platform.launcher.core.DelegatingEngineExecutionListener.executionFinished(DelegatingEngineExecutionListener.java:46)
[ERROR]         at org.junit.platform.launcher.core.OutcomeDelayingEngineExecutionListener.executionFinished(OutcomeDelayingEngineExecutionListener.java:63)
[ERROR]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.reportCompletion(NodeTestTask.java:183)
[ERROR]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:89)
[ERROR]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:1
85)
[ERROR]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.ja
va:155)
[ERROR]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)
[ERROR]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
[ERROR]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[ERROR]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
[ERROR]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[ERROR]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
[ERROR]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[ERROR]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
[ERROR]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
[ERROR]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:1
85)
[ERROR]         at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[ERROR]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[ERROR]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[ERROR]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[ERROR]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[ERROR]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
`

I'm using the following configuration for the junit-platform.properties file:

`junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default = same_thread
junit.jupiter.execution.parallel.mode.classes.default = concurrent`

Tests run fine if junit.jupiter.execution.parallel.enabled is set to false.

(My goal is to execute my test classes in parallel but all tests in one test class within the same thread.)

I was able to provoke this behaviour for the example project https://github.com/serenity-dojo/serenity-web-training/tree/junit5-solution as well.

Any advice? Or is this simply an open TODO in Serenity's JUnit5 support?

**Comment by wakaleo** [comment]
I'm not sure if parallel execution in JUnit 5 is supported yet - @cliviu ?
