### ISSUE TITLE
Serenity-bdd run throws java.lang.IllegalStateException 

### ISSUE THREAD

**Issue by nshagin** [serenity-bdd/serenity-core#2568]
Running my scripts and at the end 'serenity-bdd run --features ./features' throwing Unable to load cache item error messages.
Can anyone help me with this?

I am using Java version: 16.0.1

Logs:

[report] INFO: An exception was caught and reported. Message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineCla
ss(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4d405ef7
[report] java.lang.IllegalStateException: Unable to load cache item
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
[report]        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
[report]        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
[report]        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
[report]        at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:69)
[report]        at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:327)
[report]        at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:135)
[report]        at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:105)
[report]        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
[report]        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:356)
[report]        at com.google.inject.spi.Elements.getElements(Elements.java:104)
[report]        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
[report]        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
[report]        at com.google.inject.Guice.createInjector(Guice.java:87)
[report]        at com.google.inject.Guice.createInjector(Guice.java:69)
[report]        at com.google.inject.Guice.createInjector(Guice.java:59)
[report]        at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:27)
[report]        at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:20)
[report]        at net.thucydides.core.requirements.FileSystemRequirementsService.<init>(FileSystemRequirementsService.java:20)
[report]        at net.thucydides.core.requirements.FileSystemRequirements.<init>(FileSystemRequirements.java:24)
[report]        at net.serenitybdd.cli.reporters.RequirementsStrategy.forDirectory(RequirementsStrategy.java:11)
[report]        at net.serenitybdd.cli.reporters.CLIAggregateReportGenerator.generateReportsFrom(CLIAggregateReportGenerator.java:50)
[report]        at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:56)
[report]        at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
[report]        at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
[report] Caused by: java.lang.ExceptionInInitializerError
[report]        at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:104)
[report]        at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
[report]        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
[report]        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
[report]        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
[report]        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
[report]        ... 27 more
[report] Caused by: com.google.inject.internal.cglib.core.$CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lan
g.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unna
med module @4d405ef7
[report]        at com.google.inject.internal.cglib.core.$ReflectUtils.defineClass(ReflectUtils.java:464)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:339)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
[report]        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory$Generator.create(KeyFactory.java:221)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:174)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:157)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:149)
[report]        at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:145)
[report]        at com.google.inject.internal.cglib.core.$MethodWrapper.<clinit>(MethodWrapper.java:23)
[report]        ... 38 more
[report] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.se
curity.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4d405ef7
[report]        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[report]        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[report]        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[report]        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[report]        at com.google.inject.internal.cglib.core.$ReflectUtils$1.run(ReflectUtils.java:61)
[report]        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
[report]        at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:52)
[report]        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
[report]        ... 35 more
[report]
[report] Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
[report]        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
[report]        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[report]        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
[report]        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
[report]        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
[report]        at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
[report]        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
[report]        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
[report]        at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:606)
[report]        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:943)
[report]        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863)
[report]        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:300)
[report]        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:231)
[report]        at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:949)
[report]        at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48)
[report]        at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60)
[report]        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:135)
[report]        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
[report]        at com.google.inject.Guice.createInjector(Guice.java:87)
[report]        at com.google.inject.Guice.createInjector(Guice.java:69)
[report]        at com.google.inject.Guice.createInjector(Guice.java:59)
[report]        at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:27)
[report]        at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:20)
[report]        at net.thucydides.core.requirements.FileSystemRequirementsService.<init>(FileSystemRequirementsService.java:20)
[report]        at net.thucydides.core.requirements.FileSystemRequirements.<init>(FileSystemRequirements.java:24)
[report]        at net.serenitybdd.cli.reporters.RequirementsStrategy.forDirectory(RequirementsStrategy.java:11)
[report]        at net.serenitybdd.cli.reporters.CLIAggregateReportGenerator.generateReportsFrom(CLIAggregateReportGenerator.java:50)
[report]        at net.serenitybdd.cli.SerenityCLIReportCoordinator.execute(SerenityCLIReportCoordinator.java:56)
[report]        at net.serenitybdd.cli.Serenity.executeWith(Serenity.java:116)
[report]        at net.serenitybdd.cli.Serenity.main(Serenity.java:80)
[report] Caused by: java.lang.IllegalStateException: Unable to load cache item
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
[report]        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
[report]        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
[report]        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
[report]        at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:49)
[report]        at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:156)
[report]        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:94)
[report]        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
[report]        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
[report]        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
[report]        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
[report]        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
[report]        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
[report]        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
[report]        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
[report]        ... 29 more
[report] Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
[report]        at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:104)
[report]        at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
[report]        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
[report]        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
[report]        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
[report]        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
[report]        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[report]        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
[report]        ... 46 more

**Comment by globalworming** [comment]
Did it ever work before? Are you sure about your feature path? Do you have any weird files in your features directory?

**Comment by nshagin** [comment]
It worked before in another system, but not in this laptop, I checked my feature files, I cant find anything weird in all feature directory/files. 
As I am new to serenity-bdd, could you please advise the steps to do so that I can check?
Thanks in advance

**Comment by globalworming** [comment]
If it worked before, then compare both systems and find the difference.
Or create a simple example project to reproduce the error.

**Comment by nshagin** [comment]
I downloaded a project _serenity-js-cucumber-protractor-template-master_ from github and executed it, getting the same errors as mine.
[test:report] Oct 05, 2021 12:18:48 PM com.google.inject.internal.MessageProcessor visit
[test:report] INFO: An exception was caught and reported. Message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.d
efineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @
4d405ef7
[test:report] java.lang.IllegalStateException: Unable to load cache item

Please advise on this issue.

**Comment by nshagin** [comment]
Hi team, I downgraded my JAVA version from 16.0.1 to 15.0.1, and the report is generated successfully. So serenity bdd report is not supporting the JAVA version 16.0.1. Thanks.

**Comment by wakaleo** [comment]
What version of Serenity are you using? Are you using Serenity BDD or Serenity/JS?

**Comment by beyond-danube** [comment]
OK so long story short on the topic:
* serenity-maven-plugin 2.2.0 with Java 11 - does NOT throw exception
* serenity-maven-plugin 2.2.0 with Java 16 - does throw exception
* serenity-maven-plugin 2.5.10 with both Java 11 and Java 16 - does NOT throw exception

**Comment by wakaleo** [comment]
This is an old issue due to a version of Guice which is not compatible with recent versions of Java. Make sure you are using the latest version of serenity-cli and serenity/js.

**Comment by gigamac** [comment]
I know this is closed, but had same issue with these dependencies (bad outcome java 16, good outcome java 15):
` "devDependencies": {
    "@serenity-js/console-reporter": "^2.32.3",
    "@serenity-js/core": "^2.32.3",
    "@serenity-js/mocha": "^2.32.3",
    "@types/mocha": "^9.0.0",
    "@types/node": "^16.11.7",
    "mocha": "^9.1.3",
    "ts-node": "^10.4.0",
    "typescript": "^4.4.4"`

**Comment by sumit12071988** [comment]
Encountered the same issue. 
Resolution: as John Ferguson Smart mentioned, ensure all the maven dependencies are the latest ones. The script works fine with the JDK 17 as well.

**Comment by BenDuong1386** [comment]
Hi All,

I'm new to Serenity BDD and just followed the tutorial1 and I encountered this same error. I'm using IntelliJ, Maven, OpenJDK. The pom.xml file was generated by following the Maven archetype step (mvn archetype:generate -Dfilter=serenity) and then selecting the latest (net.serenity-bdd:serenity-junit-screenplay-archetype).

**Maven 3.8.5**
**OpenJDK  "1.8.0_302"**
**Serenity Version: 2.3.2**

What should I be checking, or what I can tweak to fix this error, please could someone help me? Below is the complete stack trace.

Aug 03, 2022 11:07:42 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @17d99928
java.lang.IllegalStateException: Unable to load cache item
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
	at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
	at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
	at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:69)
	at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:272)
	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:116)
	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:100)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:353)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:27)
	at net.serenitybdd.junit.runners.SerenityRunner.<init>(SerenityRunner.java:102)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.ExceptionInInitializerError
	at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:104)
	at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
	at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
	... 37 more
Caused by: com.google.inject.internal.cglib.core.$CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @17d99928
	at com.google.inject.internal.cglib.core.$ReflectUtils.defineClass(ReflectUtils.java:464)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at com.google.inject.internal.cglib.core.$KeyFactory$Generator.create(KeyFactory.java:221)
	at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:174)
	at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:157)
	at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:149)
	at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:145)
	at com.google.inject.internal.cglib.core.$MethodWrapper.<clinit>(MethodWrapper.java:23)
	... 48 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @17d99928
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.google.inject.internal.cglib.core.$ReflectUtils$1.run(ReflectUtils.java:61)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:52)
	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
	... 45 more


com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2052)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:51)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:48)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:595)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:932)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:291)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:222)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:938)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:27)
	at net.serenitybdd.junit.runners.SerenityRunner.<init>(SerenityRunner.java:102)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalStateException: Unable to load cache item
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
	at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
	at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
	at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:49)
	at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:156)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:92)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
	at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:104)
	at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
	at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
	... 56 more
