### ISSUE TITLE
JUnit 5: Nullpointer when accessing Steps with JUnit Jupiter

### ISSUE THREAD

**Issue by fabian-froehlich** [serenity-bdd/serenity-core#2573]
Steps to reproduce:
1. Clone serenity-core repository
2. Execute `SamplePassingNonWebScenario` (net.thucydides.samples) with IntelliJ
3. Nullpointer when accessing `steps`

```
java.lang.NullPointerException
	at net.thucydides.samples.SamplePassingNonWebScenario.edge_case_1(SamplePassingNonWebScenario.java:22)

java.lang.NullPointerException
	at net.thucydides.samples.SamplePassingNonWebScenario.edge_case_2(SamplePassingNonWebScenario.java:29)

java.lang.NullPointerException
	at net.thucydides.samples.SamplePassingNonWebScenario.happy_day_scenario(SamplePassingNonWebScenario.java:14)

```

I also could reproduce this behaviour with my own project when I tried to migrate to JUnit Jupiter.

Is there a working example that show how to write JUnit5 Tests with Serenity-BDD?

This is my pom.xml
POM:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.corp</groupId>
    <artifactId>test</artifactId>
    <name>test</name>
    <version>0.0.1-SNAPSHOT</version>
    <properties>
        <parallel.tests>1</parallel.tests>

        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <serenity.version>2.6.0</serenity.version>
        <junit5.version>5.8.1</junit5.version>
        <assertj-core.version>3.21.0</assertj-core.version>
        <logback-classic.version>1.2.6</logback-classic.version>
        <lombok.version>1.18.22</lombok.version>
        <mockserver-netty.version>5.11.2</mockserver-netty.version>
        <json.version>20210307</json.version>
        <guava.version>31.0.1-jre</guava.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-model</artifactId>
            <version>${serenity.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit5</artifactId>
            <version>${serenity.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback-classic.version}</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj-core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${json.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-netty</artifactId>
            <version>${mockserver-netty.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>


        <!-- TEST DEPENDENCIES -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit5.version}</version>
            <scope>compile</scope>
            <optional>true</optional>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit5.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>${junit5.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>${junit5.version}</version>
            <scope>compile</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.platform/junit-platform-launcher -->
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>1.7.1</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/Test*.java</include>
                        <include>**/*TestSuite.java</include>
                        <include>**/When*.java</include>
                    </includes>
                    <parallel>classes</parallel>
                    <threadCount>${parallel.tests}</threadCount>
                    <forkCount>${parallel.tests}</forkCount>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- Prettier Formatter -->
            <plugin>
                <groupId>com.hubspot.maven.plugins</groupId>
                <artifactId>prettier-maven-plugin</artifactId>
                <version>0.14</version>
                <configuration>
                    <ignoreEditorConfig>true</ignoreEditorConfig>
                    <nodeVersion>12.13.0</nodeVersion>
                    <prettierJavaVersion>0.8.3</prettierJavaVersion>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <skipIfEmpty>true</skipIfEmpty>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.0.0-M1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.0.0-M1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```

**Comment by fabian-froehlich** [comment]
Thanks for your quick reply. I guess we should wait a little further until migrating our testsuites to JUnit5. But we are looking forward to it since every other testsuite ist already running JUnit5.

Your Fork worked for me as well. It seems that the following lines inside the maven-failsafe-plugin was missing
```
                    <systemPropertyVariables>
                        <junit.jupiter.extensions.autodetection.enabled>true</junit.jupiter.extensions.autodetection.enabled>
                    </systemPropertyVariables>
```
Adding that makes the test start but fail at a Step where we create a Mockserver (org.mock-server:mockserver-netty). I will give it another shot when this feature becomes stable.

**Comment by fabian-froehlich** [comment]
In addition to the Property that I had to use there is now an annotation that makes the tests work.
```
@ExtendWith(SerenityJUnit5Extension.class)
public class MyTest {
...
}
```
The output running tests with `mvn verify` seem a bit verbose and less colourful. But this might be streamlined with a future release (we are usung 3.0.5 right now).
But it was somehow confusing reading the JUnit 5 Support in the latest release and recognizing that it was not completly implemented yet.
