### ISSUE TITLE
Question - Where I could check, whether Serenity is working with the latest Java LTS release - Java 17?

### ISSUE THREAD

**Issue by kedziorm** [serenity-bdd/serenity-core#2600]
In the table https://github.com/serenity-bdd/serenity-core#what-is-the-latest-stable-version-i-should-use I cannot find information about Java versions that should work with the Serenity BDD.
How could I find this information?

**Comment by wakaleo** [comment]
Any recent version should work fine with JDK 17

**Comment by kedziorm** [comment]
Thank you for response. I am considering migration to the latest, stable Java and Selenium (4.0.0) versions. Thus, I want to ensure, whether it is good to even start testing the possibility of migration.

**Comment by wakaleo** [comment]
You'll need to wait a bit for the Selenium 4 integration.

**Comment by dev-ducu** [comment]
Any idea how to pass this error, though?

`net.serenitybdd.core.exceptions.SerenityManagedException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @43517800
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
`

Using amazon coreoto 17, and serenity-core 3.0.5 + serenity-jbehave 1.46.0

**Comment by ChandanSDET** [comment]
I am also getting the same problem
Using Playwright + Serenity + Jbehave
Time elapsed: 1.201 s  <<< ERROR!
net.serenitybdd.core.exceptions.SerenityManagedException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @539c53b5
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)

**Comment by ChandanSDET** [comment]
@dev-ducu Have you got any resolution to the problem?

**Comment by wakaleo** [comment]
serenity-jbehave is no longer supported - I don't know if it works with recent Java versions.
