### ISSUE TITLE
TestFramework can't load test strategies from serenity-model lib in jenkins

### ISSUE THREAD

**Issue by CimaCha** [serenity-bdd/serenity-core#2603]
I'm working with serenity + cucumber6 + junit-vintage + gradle
For some reason I need to update my TAF from 1.8 to 1.11 java version
For this we have special node with jdk11, however in every build I saw problem like this 

`Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
2021-11-09 17:25:59      	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
2021-11-09 17:25:59      	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
2021-11-09 17:25:59      	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
2021-11-09 17:25:59      	at java.base/java.util.Objects.checkIndex(Objects.java:372)
2021-11-09 17:25:59      	at java.base/java.util.ArrayList.get(ArrayList.java:459)
2021-11-09 17:25:59      	at net.thucydides.core.adapters.TestFramework.<clinit>(TestFramework.java:31)
2021-11-09 17:25:59      	at net.thucydides.core.annotations.TestAnnotations.isIgnored(TestAnnotations.java:49)
2021-11-09 17:25:59      	at net.thucydides.core.steps.BaseStepListener.setDefaultResultFromAnnotations(BaseStepListener.java:747)
2021-11-09 17:25:59      	at net.thucydides.core.steps.BaseStepListener.recordStep(BaseStepListener.java:732)
2021-11-09 17:25:59      	at net.thucydides.core.steps.BaseStepListener.stepStarted(BaseStepListener.java:685)
2021-11-09 17:25:59      	at net.thucydides.core.steps.BaseStepListener.recordRestQuery(BaseStepListener.java:1313)
2021-11-09 17:25:59      	at net.serenitybdd.rest.utils.RestReportingHelper.registerCall(RestReportingHelper.java:82)
2021-11-09 17:25:59      	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.reportQuery(RequestSpecificationDecorated.java:292)
2021-11-09 17:25:59      	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.execute(RequestSpecificationDecorated.java:284)
2021-11-09 17:25:59      	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:120)
2021-11-09 17:25:59      	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:38)`

After some investigation I understood that this list contains of test adapters and I don't know why it's empty
Localy everything works fine. Could you help me to understand what's the reason of this behavior?

**Comment by wakaleo** [comment]
What version is this?

**Comment by CimaCha** [comment]
The version is 2.6.0 and I tried to update to 3.0.5 and have the same problem

**Comment by CimaCha** [comment]
Dependencies

ext {
    serenityVersion = '2.6.0'
    cucumberVersion = '6.11.0'
    jsonVersion = '20210307'
    jsonpathVersion = '2.6.0'
    springVersion = '5.3.10'
    jacksonVersion = '2.13.0'
    slf4jVersion = '1.7.32'
    asserJVersion = '3.21.0'
    webdriverManagerVersion = '5.0.3'
    jUnitVersion = '5.8.1'
    opencsvVersion = '5.5.2'
}

configurations {
    cucumberRuntime {
        extendsFrom implementation
    }
}

dependencies {
    implementation("net.serenity-bdd:serenity-rest-assured:${serenityVersion}")
    implementation("net.serenity-bdd:serenity-core:${serenityVersion}")
    implementation("net.serenity-bdd:serenity-spring:${serenityVersion}")
    implementation("net.serenity-bdd:serenity-cucumber6:${serenityVersion}")
    implementation("net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}")
    implementation("net.serenity-bdd:serenity-screenplay:${serenityVersion}")
    implementation("net.serenity-bdd:serenity-ensure:${serenityVersion}")
    implementation("com.jayway.jsonpath:json-path:${jsonpathVersion}")
    implementation("org.json:json:${jsonVersion}")
    implementation("org.springframework:spring-core:${springVersion}")
    implementation("org.springframework:spring-test:${springVersion}")
    implementation("org.springframework:spring-tx:${springVersion}")
    implementation("org.springframework:spring-aop:${springVersion}")
    implementation("com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}")
    implementation("com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}")
    implementation("com.fasterxml.jackson.core:jackson-core:${jacksonVersion}")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVersion}")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:${jacksonVersion}")
    implementation("io.cucumber:cucumber-core:${cucumberVersion}")
    implementation("io.cucumber:cucumber-java:${cucumberVersion}")
    implementation("io.cucumber:cucumber-junit:${cucumberVersion}")
    implementation("io.cucumber:cucumber-junit-platform-engine:${cucumberVersion}")
    implementation("org.assertj:assertj-core:${asserJVersion}")
    implementation("io.github.bonigarcia:webdrivermanager:${webdriverManagerVersion}")
    implementation("org.junit.vintage:junit-vintage-engine:${jUnitVersion}")
    implementation("org.junit.jupiter:junit-jupiter:${jUnitVersion}")
    implementation("com.opencsv:opencsv:${opencsvVersion}")
    implementation("ch.qos.logback:logback-classic:1.2.6")

**Comment by wakaleo** [comment]
Looks like you don't have serenity-junit or serenity-junit5 in your direct dependencies - could be a Gradle dependency management issue.

**Comment by CimaCha** [comment]
Same problem with this dependency too

**Comment by wakaleo** [comment]
I'm not sure what to suggest - maybe ask on http://gitter.im/serenity-bdd/serenity-core. Serenity is failing to find the JUnit 5 adaptor on the class path, which is generally a build script or dependency issue.

**Comment by wakaleo** [comment]
Closing for lack of activity
