### ISSUE TITLE
JUnit 5: Parallel execution ->  java.lang.NullPointerException: No BaseStepListener has been registered

### ISSUE THREAD

**Issue by bachhavdipak** [serenity-bdd/serenity-core#2607]
Getting below issue while executing test in a parallel mode:

```
 java.lang.NullPointerException: No BaseStepListener has been registered
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
        at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:139)
        at net.thucydides.core.steps.StepEventBus.testFailed(StepEventBus.java:531)
        at net.serenitybdd.junit5.extension.SerenityJUnitLifecycleAdapterExtension.testFailed(SerenityJUnitLifecycleAdapterExtension.java:70)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$nodeFinished$14(TestMethodTestDescriptor.java:299)
        at org.junit.jupiter.engine.descriptor.MethodBasedTestDescriptor.lambda$invokeTestWatchers$3(MethodBasedTestDescriptor.java:134)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.junit.jupiter.engine.descriptor.MethodBasedTestDescriptor.invokeTestWatchers(MethodBasedTestDescriptor.java:132)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.nodeFinished(TestMethodTestDescriptor.java:290)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.nodeFinished(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.reportCompletion(NodeTestTask.java:176)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:89)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecut
orService.java:185)
```

I'm using the following configuration for the junit-platform.properties file:

```
junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.default = same_thread
junit.jupiter.execution.parallel.mode.classes.default = same_thread
junit.jupiter.execution.parallel.config.strategy = dynamic
```
Tests run fine if junit.jupiter.execution.parallel.enabled is set to false.

(My goal is to execute my test classes in parallel but all tests in one test class within the same thread.)

**Comment by wakaleo** [comment]
I don't think that's supported yet, but feel free to take a look and propose a PR if it's useful for you
