### ISSUE TITLE
org.openqa.selenium.JavascriptException: javascript error: Cannot read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by sumit-global** [serenity-bdd/serenity-core#2609]
Hi John,

I am using serenity "2.3.10", I am trying to open url using `openUrl(url)` method, I am getting below exception 

`org.openqa.selenium.JavascriptException: javascript error: Cannot read properties of null (reading 'contains')`

Below is full stacktarce.

`org.openqa.selenium.JavascriptException: javascript error: Cannot read properties of null (reading 'contains')
  (Session info: chrome=96.0.4664.45)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LHTU05CG034579V', ip: '10.21.204.169', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 96.0.4664.45, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: C:\Users\sbhardw9\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:58024}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c7926af25cd9164e62426491f6bfaafd
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
	at net.thucydides.core.webdriver.javascript.JavascriptExecutorFacade.executeScript(JavascriptExecutorFacade.java:64)
	at net.thucydides.core.pages.jquery.JQueryEnabledPage.executeScriptFrom(JQueryEnabledPage.java:68)
	at net.thucydides.core.pages.jquery.JQueryEnabledPage.injectJQuery(JQueryEnabledPage.java:60)
	at net.thucydides.core.pages.jquery.JQueryEnabledPage.activateJQuery(JQueryEnabledPage.java:96)
	at net.serenitybdd.core.pages.PageObject.addJQuerySupport(PageObject.java:1214)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:915)
	at net.serenitybdd.core.pages.PageObject.openUrl(PageObject.java:862)`

**Comment by wakaleo** [comment]
Have you tried a more recent version?

**Comment by sumit-global** [comment]
Could you please suggest which version I should use as I want cucumber 5 not 6 at a moment.

**Comment by wakaleo** [comment]
Cucumber 5 isn't supported in the latest versions - you'll need to check the versions table on the project homepage

**Comment by sumit-global** [comment]
let me check and get back to you.

**Comment by sumit-global** [comment]
I tested same with "2.5.8" version and observed same behavior.

**Comment by wakaleo** [comment]
Try setting `serenity.jquery.integration` to false.

**Comment by sumit-global** [comment]
Just want to confirm do I need to add same in serenity.properties file?

**Comment by wakaleo** [comment]
Yes, or in serenity.conf

**Comment by sumit-global** [comment]
Thanks John let me try and get back to you

**Comment by sumit-global** [comment]
Thanks John it's working like champ, thanks for quick response, closing this thread.
