### ISSUE TITLE
[Serenity Rest] - Get or Post request in a @After in hook is throwing NullPointerException

### ISSUE THREAD

**Issue by JonathanOrtegon-L** [serenity-bdd/serenity-core#2627]
In my test suite I need to make a post and get request on a @After (cucumber hook), and when I make this request using the default script form (with the same iterations used in steps) if the scenario fails before hook I get null pointer exception.

Request:
`actor.attemptsTo(
                Post.to(AuthenticationServiceEndpoints.LOGIN.getUrlPath())
                        .with(requestSpecification -> baseLuloInternalRequestWithBearerToken()
                                .header(FIREBASE_ID.toString(), firebaseId)
                                .body(this.loginModel))
        );`
Exception stacktrace:
`    java.lang.NullPointerException
	at net.serenitybdd.screenplay.rest.interactions.Post.performAs(Post.java:24)
	at net.serenitybdd.screenplay.rest.interactions.Post$ByteBuddy$dRBKVmX5.performAs$accessor$WVijUH9P(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:492)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:472)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:445)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:201)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:188)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:76)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at net.serenitybdd.screenplay.rest.interactions.Post$ByteBuddy$dRBKVmX5.performAs(Unknown Source)
	at net.serenitybdd.screenplay.Actor.performTask(Actor.java:252)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:233)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:178)
	at lulobank.automation.api.lulo.services.internal.interactions.authentication.PostLogin.performAs(PostLogin.java:28)
	at lulobank.automation.api.lulo.services.internal.interactions.authentication.PostLogin$ByteBuddy$vTSpyAGV.performAs$accessor$OULfTORU(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:492)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:472)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:445)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:201)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:188)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:76)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at lulobank.automation.api.lulo.services.internal.interactions.authentication.PostLogin$ByteBuddy$vTSpyAGV.performAs(Unknown Source)
	at net.serenitybdd.screenplay.Actor.performTask(Actor.java:252)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:233)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:178)
	at lulobank.automation.tasks.be.request.Login.performAs(Login.java:40)
	at lulobank.automation.tasks.be.request.Login$ByteBuddy$ak8Nr4bj.performAs$accessor$MyHr4ezM(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:492)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:472)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:445)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:201)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:188)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:76)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at lulobank.automation.tasks.be.request.Login$ByteBuddy$ak8Nr4bj.performAs(Unknown Source)
	at net.serenitybdd.screenplay.Actor.performTask(Actor.java:252)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:233)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:178)
	at lulobank.automation.commons.tasks.testusers.AccountValidation.answeredBy(AccountValidation.java:40)
	at lulobank.automation.commons.tasks.testusers.AccountValidation.answeredBy(AccountValidation.java:26)
	at net.serenitybdd.screenplay.Actor.asksFor(Actor.java:206)
	at lulobank.automation.stepsdefinitions.Hooks.lambda$afterScenario$1(Hooks.java:72)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at lulobank.automation.stepsdefinitions.Hooks.afterScenario(Hooks.java:71)`

However when I use SerenityRest.get () to get evidence from the device farm the request just works fine.
example:
```
RestAssured.given ()
                .baseUri (BROWSERSTACK_API_BASE_URL)
                .auth ()
                .basic (BROWSERSTACK_USER, BROWSERSTACK_PASSWORD)
                .pathParams (pathParams)
                .when ()
                .get (endpoint.getUrlPath ())
                .then ()
                .and ()
                .extract ()
                .response ();
```

Versions POM:
```
<project.build.sourceEncoding> UTF-8 </project.build.sourceEncoding>
    <serenity.version> 2.3.33 </serenity.version>
    <serenity.maven.version> 2.3.33 </serenity.maven.version>
    <serenity.cucumber.version> 2.3.33 </serenity.cucumber.version>
    <cucumber.version> 6.9.1 </cucumber.version>
    <lombok.version> 1.18.10 </lombok.version>
    <junit.version> 4.13.1 </junit.version>
    <slf4j.version> 1.7.7 </slf4j.version>
    <jackson.version> 2.10.3 </jackson.version>
    <javafaker.version> 1.0.1 </javafaker.version>
    <univocity.version> 2.8.4 </univocity.version>
    <encoding> UTF-8 </encoding>
```

It seems to be a bug ... right?

**Comment by wakaleo** [comment]
Possibly, I would debug and have a look at what it is doing under the hood.

**Comment by JonathanOrtegon-L** [comment]
Hooks @before
scenario
1.POST Login
2. Steps
3. Failure Step
Hook @after
	POST Login (same in step 1)
```
actor.attemptsTo(
        Post.to(AuthenticationServiceEndpoints.LOGIN.getUrlPath())
                .with(requestSpecification -> baseLuloInternalRequestWithBearerToken()
                        .header(FIREBASE_ID.toString(), firebaseId)
                        .body(this.loginModel))
);
```

```
public static RequestSpecification baseLuloInternalRequestWithBearerToken() {
    return rootLuloInternalRequest()
            .header(AUTH_HEADER_KEY, String.format("%s %s", BEARER_KEY, getBearerToken()));
}

```
Fail in
```
package net.serenitybdd.screenplay.rest.interactions;
@Step("{0} executes a POST on the resource #resource")
@Override
public <T extends Actor> void performAs(T actor) {
    rest().post(as(actor).resolve(resource));
}
```

from this point it won't let me debug any more and throws the nullPointerException

the variable resoruce contains the correct url

**Comment by wakaleo** [comment]
RestAssured is full of Groovy which makes it hard to debug. I'd put a breakpoint in the performAs() and try to evaluate each part of the expression - e.g. is it the rest() method throwing the exception, or when it resolves the resource. It may not have the session context it needs anymore in the @After method.

**Comment by JonathanOrtegon-L** [comment]
the rest() method is throwing the exception

**Comment by wakaleo** [comment]
Dig into that method and see what it is doing. I'm not too familiar with that module so I'm not sure how it works, but by stepping through the code you might see something.

**Comment by ricardorlg-aval** [comment]
You can add the property SERENITY_DISABLE_REST_CALLS_AFTER_FAILURES to false and it will allow to execute rest calls on hooks after failures

**Comment by JonathanOrtegon-L** [comment]
```
 @Override
    public Response post(String path, Object... pathParams) {
        return execute(POST, path, pathParams);
    }

protected Response execute(final RestMethod method, final String path, final Object... pathParams) {
        Response response = null;
        RuntimeException exception = null;
        try {
            response = executeCall(method, path, pathParams);
            if (RestExecutionHelper.restCallsAreDisabled()) {
                response = stubbed();
            }
        } catch (RuntimeException e) {
            exception = e;
        }
        if (exception != null) {
            reportError(method, path, exception, pathParams);
            if (Serenity.shouldThrowErrorsImmediately()) {
                throw exception;
            } else {
                response = stubbed();
            }
        } else {
            if (withReporting)
                reportQuery(method, path, response, pathParams);
        }
        this.lastResponse = response;
        return response;
    }
```


> Dig into that method and see what it is doing. I'm not too familiar with that module so I'm not sure how it works, but by stepping through the code you might see something.

**Comment by JonathanOrtegon-L** [comment]
> You can add the property SERENITY_DISABLE_REST_CALLS_AFTER_FAILURES to false and it will allow to execute rest calls on hooks after failures

Use SERENITY_DISABLE_REST_CALLS_AFTER_FAILURES in serenity.properties and environmentVariables with false value, and not working

**Comment by wakaleo** [comment]
Did you try `serenity.disable.rest.calls.after.failures=false'?

**Comment by JonathanOrtegon-L** [comment]
> serenity.disable.rest.calls.after.failures=false

Hello, what a pity the delay answering
I already tried your suggestion and it didn't work

**Comment by wakaleo** [comment]
The best would be to dig into the code and see what it is doing. I'm not sure what the lifecycle is doing, but the @after might be being called after the tests have wrapped up, so the Screenplay code might no longer have everything it needs to operate.

**Comment by JonathanOrtegon-L** [comment]
> The best would be to dig into the code and see what it is doing. I'm not sure what the lifecycle is doing, but the @after might be being called after the tests have wrapped up, so the Screenplay code might no longer have everything it needs to operate.

I have tried several things:
1. create a new actor and give him the skills and parameters that are needed.
2. consume directly in the @after the post:
```
actor.attemptsTo (
                 Post.to (AuthenticationServiceEndpoints.LOGIN.getUrlPath ())
                         .with (requestSpecification -> BearerToken ()
                                 .header (FIREBASE_ID.toString (), firebaseId)
                                 .body (this.loginModel))
         );
```

All this verifying that the parameters and the model are correct, all this without success.

Note: we did a test using RestAssured and the consumption works correctly, the problem only happens with SerenityRest. Making the change to RestAssured is not possible since it will cost us a lot since the amount of tests is very large and SerenityRest facilitates the report without complications.

**Comment by wakaleo** [comment]
Why not just do that step with RestAssured? I only use the Serenity wrappers when I want to document an interaction, not for setup and tear down

**Comment by JonathanOrtegon-L** [comment]
> Why not just do that step with RestAssured? I only use the Serenity wrappers when I want to document an interaction, not for setup and tear down

Because all the tests are with serenity rest and the whole process that is done in @after reuses the interactions with serenity rest, making the change to rest assured would be very expensive in time and effort, since our framework is already very large and it already has a lot of api consumptions.

**Comment by wakaleo** [comment]
Can you reproduce the issue in a sample project?

**Comment by JonathanOrtegon-L** [comment]
> Can you reproduce the issue in a sample project?

This is a sample project in which when it fails in the @after there is a consumption of a microservice and it presents the error.
sorry for the delay, I had not done it for work issues

https://github.com/JonathanOrtegon-L/SerenityRestTest

**Comment by ricardorlg** [comment]
@JonathanOrtegon-L  thanks for the sample project, I was able to reproduce the error and found the cause.

@wakaleo the problem is that when running Screenplay rest actions, the rest() function is called, but if a previous step fails then a DryRunMethodRunner is used to execute the method instead of NormalMethodRunner. 

We should add to the shouldRunInDryRunMode method and extra check to verify if the method to be called comes from a cleanup method, which also will imply adding a CleanupMethodAnnotationProvider implementation for Cucumber. 

let me know what u think.

**Comment by wakaleo** [comment]
@ricardorlg That makes sense. Do you want to have a go at it?

**Comment by ricardorlg** [comment]
Sure, assigne this to me.

**Comment by JonathanOrtegon-L** [comment]
Hello, in order not to have this problem, do I have to use the latest version of serenity core or does it also apply to version 2.3.33, which was where it was presented?

> > Hello, I see that the solution has already been merged, but how do I implement it in my projects? try to update the versions and dependencies in the POM but it didn't work @wakaleo @ricardorlg
> 
> This is on master but hasn't been released yet.

**Comment by ricardorlg-yml** [comment]
You have to use the latest version or the one on which the fix was released.

**Comment by JonathanOrtegon-L** [comment]
> You have to use the latest version or the one on which the fix was released.
Is there a way or a guide to migrate only the serenity core without updating Selenium version, RestAssured version, Appium client version?, or are the versions of the aforementioned versions closely dependent? If it is necessary to update or migrate from 2.33 to 3.2.3 in a way that does not impact a project so much.

**Comment by wakaleo** [comment]
> > You have to use the latest version or the one on which the fix was released.
> 
> Is there a way or a guide to migrate only the serenity core without updating Selenium version, RestAssured version, Appium client version?, or are the versions of the aforementioned versions closely dependent? If it is necessary to update or migrate from 2.33 to 3.2.3 in a way that does not impact a project so much. @ricardorlg-yml @wakaleo @ricardorlg

You really don't want to do that - the versions are fairly tightly coupled.
