### ISSUE TITLE
iOS tests are throwing error, but android scripts worked fine using Saucelabs

### ISSUE THREAD

**Issue by madhusudhan-patha** [serenity-bdd/serenity-core#2634]
**Note: The same script is working fine using selenium+appium code on saucelabs**

**Description:**
 

Versions:
```
<serenity.version>3.1.1</serenity.version>
<serenity.maven.version>3.1.1</serenity.maven.version>
<serenity.cucumber.version>3.1.1</serenity.cucumber.version>
```

**Serenity.properties**
```
appium.browserName=safari
webdriver.driver = remote
webdriver.remote.driver = appium
webdriver.remote.url = https://oauth-<USER>:<ACCESS_KEY>@ondemand.eu-central-1.saucelabs.com:443/wd/hub
appium.automationName = XCUITest
appium.platformName = iOS
appium.deviceName = iPhone Simulator
appium.platformVersion = 13
```

Test Script

```
**This script extends the class net.serenitybdd.core.pages.PageObject class**
 @FindBy(xpath="//XCUIElementTypeButton[@label='3']")
 protected WebElement eleDIVmyElement;
    
getDriver().get("http://saucelabs.com/test/guinea-pig");
String divText=eleDIVmyElement.getText();
org.junit.Assert.assertEquals(divText,"I am a divs");
```

Error Stack trace:

```
net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for SauceWebPagePanel:Could not instantiate class org.openqa.selenium.remote.RemoteWebDriver
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:130)
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:89)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:70)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:52)
	at net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:145)
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:109)
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:76)
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:59)
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:49)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:64)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:104)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:73)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:151)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:135)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:259)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:58)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:287)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.remote.RemoteWebDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.serenitybdd.core.webdriver.RemoteDriver.of(RemoteDriver.java:18)
	at net.thucydides.core.webdriver.appium.AppiumConfiguration.getTargetPlatform(AppiumConfiguration.java:59)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:52)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:42)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:19)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:164)
	at com.myorg.pagepanel.mobile.SauceWebPagePanel$ByteBuddy$3lH3SGU7.setDriver$accessor$Wvko1inB(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:504)
	at net.thucydides.core.steps.StepInterceptor.runBaseObjectMethod(StepInterceptor.java:398)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:83)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at com.myorg.pagepanel.mobile.SauceWebPagePanel$ByteBuddy$3lH3SGU7.setDriver(Unknown Source)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:168)
	at com.myorg.pagepanel.mobile.SauceWebPagePanel$ByteBuddy$3lH3SGU7.setDriver$accessor$Wvko1inB(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:504)
	at net.thucydides.core.steps.StepInterceptor.runBaseObjectMethod(StepInterceptor.java:398)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:83)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at com.myorg.pagepanel.mobile.SauceWebPagePanel$ByteBuddy$3lH3SGU7.setDriver(Unknown Source)
	at net.thucydides.core.steps.PageObjectDependencyInjector.updatePageObject(PageObjectDependencyInjector.java:100)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:48)
	at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:206)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:196)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:177)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:124)
	... 43 more
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.remote.RemoteWebDriver (Could not start a new session. Unable to parse remote response: ). See below for more details.
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:146)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	... 80 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: 
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:126)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:146)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:225)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:79)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:87)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:105)
	at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverBuilder.newRemoteDriver(RemoteDriverBuilder.java:50)
	at net.serenitybdd.core.webdriver.driverproviders.DefaultRemoteDriver.buildWithOptions(DefaultRemoteDriver.java:28)
	at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider.newInstance(RemoteDriverProvider.java:32)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:157)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:136)
	... 81 more
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: 
	at org.openqa.selenium.json.Json.toType(Json.java:57)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:109)
	... 100 more
Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'IN-L-C165GY0', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_302'
Driver info: driver.version: RemoteDriver
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:307)
	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:229)
	at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.Json.toType(Json.java:71)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	... 102 more
```

**Comment by wakaleo** [comment]
"Expected to read a START_MAP but instead have: END. Last 0 characters read: " - Saucelabs is sending an error of some kind in the JSON response, which is causing Selenium to crash. Without being able to run the actual tests it's difficult to say more.

**Comment by madhusudhan-patha** [comment]
Actually the errors mentioned in description were displayed  even before the job is finished and the job on saucelabs continued to run till timeout. Please find the log files from saucelabs. I don't see any errors sent by saucelabs. Can you please help?

[saucelabs_appium_logs.txt](https://github.com/serenity-bdd/serenity-core/files/7688098/saucelabs_appium_logs.txt)
[command_output.txt](https://github.com/serenity-bdd/serenity-core/files/7688100/command_output.txt)

**Comment by wakaleo** [comment]
Closing as this appears to be a Saucelabs configuration question, not a Serenity defect.

**Comment by madhusudhan-patha** [comment]
Hi @wakaleo, There is a new release for selenium. Any possibility to include selenium 4.1.1 as part of serenity?

**Comment by wakaleo** [comment]
We will include it in the next release if it passes our tests (4.1.0 had quite a few issues)
