### ISSUE TITLE
I am not able to use proxy servers with Chrome

### ISSUE THREAD

**Issue by escor888** [serenity-bdd/serenity-core#2697]
I have tried a lot of things and nothing is working.

1) Add proxy to maven global settings.xml
2) Add serenity.proxy.http= www-proxy.us.xxx.com and serenity.proxy.http_port = 80 in serenity.properties
3) Create my custom webdriver with chromeoptions.
4) Implements BeforeAWebdriverScenario class.
5) Add proxy in chrome.switches in serenity.properties

btw there is not much information about my own web driver implementation as well as the try 4.

**Comment by escor888** [comment]
Error shown: ERR_TUNNEL_CONNECTION_FAILED

**Comment by wakaleo** [comment]
Can you make it work with plain Selenium?

**Comment by escor888** [comment]
I need to check it, 
don't we have documentation about proxy in chrome? I think should be a common scenario.
btw in some places I am seeing serenity.proxy.http is only supported by Firefox, is it?

**Comment by escor888** [comment]
is this a good try?
public class MyCapabilityEnhancer implements BeforeAWebdriverScenario {

    @Override
    public DesiredCapabilities apply(EnvironmentVariables environmentVariables,
                                     SupportedWebDriver driver,
                                     TestOutcome testOutcome,
                                     DesiredCapabilities capabilities) {
        
        if (driver == SupportedWebDriver.CHROME) {
            System.out.println("enhancing chrome capabilities");
            System.out.println(capabilities);
            Proxy proxy = new Proxy();
            proxy.setHttpProxy("http://www-proxy.us.xxx.com:80");
            capabilities.setCapability("proxy", proxy); 
            System.out.println(capabilities);
        }
        return capabilities;
    }
}

**Comment by wakaleo** [comment]
That could work. If that is the only configuration you need to do, then `serenity.proxy.http` should work.  See https://github.com/serenity-bdd/serenity-core/blob/a4fca1c8da8b23060480c1fee92b64e62e34f0f4/serenity-model/src/main/java/net/thucydides/core/ThucydidesSystemProperty.java#L604 for documentation on the proxy settings - they should work for all browsers.

**Comment by muthu5151** [comment]
Hi Team,

Even I am facing the same issue when I try to configure http proxy settings for chrome. I have provided the below configuration in serenity.properties file,

serenity.proxy.http = localhost
serenity.proxy.http_port = 8181

Error message:

Caused by: java.lang.NullPointerException
	at net.serenitybdd.core.webdriver.driverproviders.ConfiguredProxy.definedIn(ConfiguredProxy.java:64)
	at net.serenitybdd.core.webdriver.driverproviders.ChromeDriverCapabilities.addProxyConfigurationTo(ChromeDriverCapabilities.java:104)
	at net.serenitybdd.core.webdriver.driverproviders.ChromeDriverCapabilities.configuredOptions(ChromeDriverCapabilities.java:74)
	at net.serenitybdd.core.webdriver.driverproviders.ChromeDriverCapabilities.getCapabilities(ChromeDriverCapabilities.java:42)
	at net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider.enhancedCapabilitiesConfiguredIn(ChromeDriverProvider.java:73)
	at net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider.newInstance(ChromeDriverProvider.java:50)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:157)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:136)
