### ISSUE TITLE
Getting ClassDef found error

### ISSUE THREAD

**Issue by anshubhatt09** [serenity-bdd/serenity-core#2735]
I am getting below error when i am running it. 

java.lang.NoClassDefFoundError: serenityswag/inventory/WhenViewingHighlightedProducts (wrong name: serenityswag/Inventory/WhenViewingHighlightedProducts)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.google.common.reflect.ClassPath$ClassInfo.load(ClassPath.java:360)
	at net.thucydides.core.requirements.annotations.ClassInfoAnnotations.hasAnAnnotation(ClassInfoAnnotations.java:26)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.classRepresentsARequirementIn(PackageRequirementsTagProvider.java:184)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.lambda$requirementPathsFromClassesInPackage$1(PackageRequirementsTagProvider.java:174)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

**Comment by anshubhatt09** [comment]
no i am writing step by step as given in the video.  how should i debug this issue now. please guide.

**Comment by wakaleo** [comment]
Which repository are you using?
