### ISSUE TITLE
Click on a link is not waiting for default time

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#281]
This is broken again in 1.1.25-rc.2

Please let me know how to add acceptance test case for this kind of scenario in framework , so that such regressions can be caught easily.

As per below error instead of waiting for next page to load ( which is non AJAX ) for default time , it simply returns false in 12 milliseconds

----------
[main] INFO net.serenitybdd.core.pages.WebElementFacadeImpl - link 'Forgot your password?':click
org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=48.0.2564.97)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 12 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'Vikrams-MBP.fritz.box', ip: '192.168.178.33', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/94/3dpydv3j2t7__4736h1pl0vr0000gn/T/.org.chromium.Chromium.DmPA4I}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=48.0.2564.97, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: f0b3ec0ebd312c87a36b2218feef1dd1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:367)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.isElementUsable(SmartAjaxElementLocator.java:129)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator$SlowLoadingElement.isLoaded(SmartAjaxElementLocator.java:217)
	at org.openqa.selenium.support.ui.SlowLoadableComponent.get(SlowLoadableComponent.java:59)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.ajaxFindElement(SmartAjaxElementLocator.java:138)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.findElement(SmartAjaxElementLocator.java:93)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy17.getTagName(Unknown Source)
	at net.serenitybdd.core.pages.HtmlTag.tagFrom(HtmlTag.java:27)
	at net.serenitybdd.core.pages.HtmlTag$ButtonTag.canHandleThis(HtmlTag.java:64)
	at net.serenitybdd.core.pages.HtmlTag.from(HtmlTag.java:15)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.humanizedTabfNameFor(WebElementFacadeImpl.java:992)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.logIfVerbose(WebElementFacadeImpl.java:978)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.type(WebElementFacadeImpl.java:557)

**Comment by wakaleo** [comment]
Hi Vikram,

Could you provide some more details about what you are doing to get this error? The error is a StaleElementReferenceException, which means that Selenium is trying to access an element that has been changed since it was last referenced. The timeout is just the time it took for Selenium to realise that the element was different, so is not (directly at least) related to any Serenity timeouts.

The integration tests for timeouts and such are in the WhenManagingWebdriverTimeouts and WhenBrowsingAWebSiteUsingPageObjects classes.

**Comment by wakaleo** [comment]
This is actually a completely different issue. It is due to the verbose logger trying to access the element to find out what type it is, and failing. This should be fixed in the next release.

**Comment by vikramvi** [comment]
Thanks John for quick reply , will check this in new release and close later.

**Comment by wakaleo** [comment]
This should be working in 1.1.25-rc.4

**Comment by vikramvi** [comment]
@wakaleo  I would like to add unit test case for verbose logger , any examples I can refer to submit PR for this scenario ?

Thanks,
Vikram

**Comment by wakaleo** [comment]
Sure, but I'm thinking of deprecating this feature as I'm not sure it is
very useful and it is implemented better with the Journey pattern anyway.

On 4 February 2016 at 12:15, vikramvi <notifications@github.com> wrote:

> @wakaleo <https://github.com/wakaleo> I would like to add unit test case
> for verbose logger , any examples I can refer to submit PR for this
> scenario ?
>
> Thanks,
> Vikram
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/281#issuecomment-179796183>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7497151337
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by vikramvi** [comment]
http://www.slideshare.net/wakaleo/serenity-and-the-journey-pattern 

pasting link here just for reference of "Journey Pattern"

**Comment by vikramvi** [comment]
verified fixed with latest version from JCenter 1.1.26-rc.1
