### ISSUE TITLE
java.lang.NullPointerException: No BaseStepListener has been registered - are you running your test using the Serenity runners?

### ISSUE THREAD

**Issue by softwaredev999** [serenity-bdd/serenity-core#2830]
Hello,

Setting up a serenity project for the first time using maven and cucumber in Eclipse IDE. When I run the feature file, I get an error

"java.lang.NullPointerException: No BaseStepListener has been registered - are you running your test using the Serenity runners?"

**POM.xml:**
```

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>serenity_project</groupId>
	<artifactId>Serenity_Project</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<dependencies>

		<!-- https://mvnrepository.com/artifact/net.serenity-bdd/serenity-core -->
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>3.2.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/net.serenity-bdd/serenity-cucumber -->
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>3.2.5</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-java -->
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>7.3.4</version>
		</dependency>


		<!-- https://mvnrepository.com/artifact/net.serenity-bdd/serenity-junit -->
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>3.2.5</version>
		</dependency>


	</dependencies>


</project>
```

**Feature file:**

```
Feature: Search by keyword

  Scenario: Searching for a term
    Given launch home page
```

**Step definition**

```
    @Given("launch home page")
    public void launch() {
        navigateTo.launchHome();
    }
```

I am getting the error at step definition:
```

java.lang.NullPointerException: No BaseStepListener has been registered - are you running your test using the Serenity runners?
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
	at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:153)
	at net.thucydides.core.steps.StepEventBus.wrapUpCurrentCucumberStep(StepEventBus.java:932)
	at net.thucydides.core.steps.StepInterceptor.finishAnyCucumberSteps(StepInterceptor.java:560)
	at net.thucydides.core.steps.StepInterceptor.notifyOfStepFailure(StepInterceptor.java:554)
	at net.thucydides.core.steps.StepInterceptor.logStepFailure(StepInterceptor.java:476)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:468)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:209)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:196)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:84)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at **navigateTo.launchHome()** 
```

Thank you in advance!

**Comment by wakaleo** [comment]
You need to run Serenity scenarios from the Serenity runner class, not from the feature file itself.

**Comment by zakaz** [comment]
If you use intellij Idea, you just have to go to "Edit Configurations", then click "Edit configuration templates...", choose "Cucumber Java" and set "Main class:" as "net.serenitybdd.cucumber.cli.Main"
![image](https://user-images.githubusercontent.com/13405597/191553880-b24216f7-1ea9-4ecf-b1ea-52c2e9f75dd9.png)

**Comment by Bhala1987** [comment]
If we are using GWT of Cucumber, then we also need to add the Glue (ki.stepDefinitions) in the above Cucumber for Java Edit Configurations dialog box of IntelliJ along with 'net.serenitybdd.cucumber.cli.Main' Main class.
