### ISSUE TITLE
Replacement of named URL not working

### ISSUE THREAD

**Issue by aybartsch** [serenity-bdd/serenity-core#2836]
Hi there,
I have to deal with two different base url for the same environment. I tried the below solution:

Excerpt from serenity.conf:
```
        webdriver {
            base.url = "http://localhost:4200/tenants"
            support.base.url = "http://localhost:4210/tenants"
        }
```
Excerpt from step class:
```
supportTenantListPage.open("support", withParameters(EnvironmentVariablesHelper.getProperty("webdriver.support.base.url")));
```
Excerpt from page class:
```
@NamedUrls(value = {@NamedUrl(name = "support", url = "{1}")})
```
I was thinking that I could inject a different base url this way but I'm facing an assertion error instead:
```
java.lang.AssertionError: Invalid URL: {1}

	at net.serenitybdd.core.pages.PageUrls.updatedFullUrl(PageUrls.java:222)
	at net.serenitybdd.core.pages.PageUrls.addBaseUrlTo(PageUrls.java:206)
	at net.serenitybdd.core.pages.PageUrls.urlWithParametersSubstituted(PageUrls.java:180)
	at net.serenitybdd.core.pages.PageUrls.getNamedUrl(PageUrls.java:174)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:768)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:755)
```
Could you please tell me what is wrong and how I should do it correctly?
Thanks, André
PS: We are using serenity version 2.4.34 with cucumber runner at present.

**Comment by wakaleo** [comment]
That's a pretty old version. In general, the base url should be the hostname and port, with no paths (e.g. http://localhost:4200).
