### ISSUE TITLE
NPE when trying to call Environment Variables

### ISSUE THREAD

**Issue by ntthaibk** [serenity-bdd/serenity-core#2837]
Hi, I have a question related to EnvironmentVariables, currently I put it in a BaseService class that look like this

```
public class BaseService{
    private final Logger LOGGER = LoggerFactory.getLogger(BaseService.class);

    public EnvironmentVariables environmentVariables;

    protected String getEnvironmentProperty(String propertyName){
        return EnvironmentSpecificConfiguration.from(environmentVariables)
                .getProperty(propertyName);
    }
```
and when I try to call it in my test code

```
public class Debug extend BaseService{

@Test
    public void checkBaseService(){
        System.out.println(getEnvironmentProperty("base.url"));
    }
}
```
then it return NPE and EnvironmentVariables is null
```
at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.environmentStrategyDefinedIn(EnvironmentSpecificConfiguration.java:277)
at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.<init>(EnvironmentSpecificConfiguration.java:130)
at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.from(EnvironmentSpecificConfiguration.java:271)
at com.mdaq.testing.services.BaseService.getEnvironmentProperty(BaseService.java:24)
```

I think the reason might be because how we inject the Environment Variables. Could someone please feedback, thanks 👍

**Comment by wakaleo** [comment]
The EnvironmentVariables field will be injected for fields annotated with @Steps or for Screenplay tasks.
