### ISSUE TITLE
Getting StepInitializationException:Failed to create step library error while running a test in serenity in intellij

### ISSUE THREAD

**Issue by johnysv** [serenity-bdd/serenity-core#2848]
Getting the below error in intellij while trying to run a test

10:43:55.195 [main] ERROR n.thucydides.core.steps.StepFactory - Cannot create StepFactory for  class com.allianz.frp.steps.LoginSteps
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at net.thucydides.core.steps.StepFactory.createProxyStepLibrary(StepFactory.java:255)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:186)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:177)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:124)
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:80)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:61)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:43)
	at net.serenitybdd.junit.runners.SerenityRunner.injectScenarioStepsInto(SerenityRunner.java:641)
	at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:604)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:467)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:441)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:250)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: Missing parameters
Usage:
mvn clean verify -DtestStage=<test_stage> -DjwtToken=<token> -DraiApiKey=<key> -DoeConnectApiKeyGroupManager=<key> -browserLocale=<[us|de]> 

	at com.allianz.frp.steps.StepsCommons.<init>(StepsCommons.java:19)
	at com.allianz.frp.steps.LoginSteps.<init>(LoginSteps.java:45)
	at com.allianz.frp.steps.LoginSteps$ByteBuddy$t8tUGpB1.<init>(Unknown Source)
	... 33 common frames omitted

Test ignored.

net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for LoginSteps:null

	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:130)
	at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:80)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:61)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:43)
	at net.serenitybdd.junit.runners.SerenityRunner.injectScenarioStepsInto(SerenityRunner.java:641)
	at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:604)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:467)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:441)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:250)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.NullPointerException
	at net.serenitybdd.core.di.SpringDependencyInjector.annotatedWithSpringContext(SpringDependencyInjector.java:32)
	at net.serenitybdd.core.di.SpringDependencyInjector.injectDependenciesInto(SpringDependencyInjector.java:17)
	at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:206)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:196)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:177)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:124)
	... 25 more

10:43:55.230 [main] INFO   - Test Suite Started: UJ
10:43:55.585 [pool-1-thread-1] INFO  n.t.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@3cd9aa64: Generating report for test outcome: UJ:Initialisation
10:43:55.978 [pool-2-thread-1] INFO  n.t.core.reports.ReportService - net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@671c4166: Generating report for test outcome: UJ:Initialisation

Process finished with exit code -1

java.lang.NullPointerException
	at net.serenitybdd.core.lifecycle.LifecycleRegister.hasAnnotatedMethod(LifecycleRegister.java:50)
	at net.serenitybdd.core.lifecycle.LifecycleRegister.lambda$invokeMethodsAnnotatedBy$0(LifecycleRegister.java:40)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1620)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at net.serenitybdd.core.lifecycle.LifecycleRegister.invokeMethodsAnnotatedBy(LifecycleRegister.java:41)
	at net.thucydides.core.steps.BaseStepListener.testStarted(BaseStepListener.java:447)
	at net.thucydides.core.steps.StepEventBus.testStarted(StepEventBus.java:146)
	at net.thucydides.core.steps.StepEventBus.testStarted(StepEventBus.java:175)
	at net.thucydides.junit.listeners.JUnitStepListener.testStarted(JUnitStepListener.java:82)
	at net.thucydides.junit.listeners.JUnitStepListener.startTestIfNotYetStarted(JUnitStepListener.java:138)
	at net.thucydides.junit.listeners.JUnitStepListener.testFailure(JUnitStepListener.java:119)
	at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:63)
	at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:142)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:138)
	at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:132)
	at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:369)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:250)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

**Comment by johnysv** [comment]
Its there already, Below is my code

package com.allianz.frp.tests.e2elarge;

import xxx.xxx.xxx.steps.LoginSteps;
import xxx.xxx.xxx.TestConfiguration;

import lombok.extern.slf4j.Slf4j;
import net.serenitybdd.junit.runners.SerenityRunner;
import net.serenitybdd.junit.spring.integration.SpringIntegrationMethodRule;
import net.thucydides.core.annotations.*;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestWatcher;
import org.junit.runner.Description;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.springframework.retry.annotation.EnableRetry;
import org.springframework.test.context.ContextConfiguration;
import net.serenitybdd.core.annotations.findby.FindBy;
import net.serenitybdd.core.pages.WebElementFacade;
import java.util.Properties;

@Slf4j
@Narrative(
        title = "Psample title",
        text = { "In order to do a replication",
                "as a user",
                "sample" }
)

@RunWith(SerenityRunner.class)
@ContextConfiguration(classes = TestConfiguration.class)
@EnableRetry
@FixMethodOrder(MethodSorters.NAME_ASCENDING)

public class Sample {
    @Steps
    public LoginSteps loginSteps;

    @Rule
    public SpringIntegrationMethodRule springIntegrationMethodRule = new SpringIntegrationMethodRule();

    private static Boolean previousTestPassed = true;
    @Rule
    public TestWatcher watchman = new TestWatcher() {
        @Override
        protected void failed(Throwable e, Description description) {
            LOG.info(description.toString());
            previousTestPassed = false;
        }
    };

    @Managed(clearCookies = ClearCookiesPolicy.Never)
    public WebDriver webdriver;
    public Properties properties;

    @Test
    @WithTagValuesOf({"good case", "e2eLarge"})
    @Title("Initialisation")
    public void UserJourneyPart1() throws Exception {
       System.out.println("test executing..");
        loginSteps.loginAsAdmin();

    }

}
