### ISSUE TITLE
unable to launch tests in MS Edge browser

### ISSUE THREAD

**Issue by sudhirpogaku** [serenity-bdd/serenity-core#2852]
I am trying to run my tests in MS Edge (Version 102.0.1245.44) but failing due to below error:
Note: webdriver path is set correctly in serenity.conf file and version of browser and driver file is matching.

webdriver {
  driver = edge
}
drivers {
   windows {
   webdriver.edge.driver = "src/test/resources/webdriver/windows/msedgedriver.exe"
   }
}
--------
Jun 21, 2022 7:21:49 PM org.openqa.selenium.remote.DesiredCapabilities edge
INFO: Using `new EdgeOptions()` is preferred to `DesiredCapabilities.edge()`
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {browserName: MicrosoftEdge, loggingPrefs: org.openqa.selenium.logging..., platform: WINDOWS, version: }

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.edge.EdgeDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:172)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:902)
	at net.serenitybdd.core.pages.PageObject.openUrl(PageObject.java:851)
.
.
.
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.edge.EdgeDriver (The path to the driver executable must be set by the webdriver.edge.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/MicrosoftWebDriver. The latest version can be downloaded from http://go.microsoft.com/fwlink/?LinkId=619687). See below for more details.
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:158)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:172)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:902)
	at net.serenitybdd.core.pages.PageObject.openUrl(PageObject.java:851)

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/docs/guide/driver_config#condiguring-microsoft-edge

**Comment by tpazz** [comment]
I found a workaround if you are using gradle build: 

https://stackoverflow.com/questions/78237673/could-not-instantiate-class-org-openqa-selenium-edge-edgedriver-serenity/78237839#78237839)
