### ISSUE TITLE
Can we delegate healenium driver to serenity ..pls suggest 

### ISSUE THREAD

**Issue by botlasai** [serenity-bdd/serenity-core#2908]

**Comment by wakaleo** [comment]
You might be able to use a custom driver for this, but I am not familiar with healinium so couldn't really say.

**Comment by botlasai** [comment]
Can you help me with a sample implementation of the custom driver  .

**Comment by TheGlovner** [comment]
Hoping someone had already sorted this.

The usual healenium process seems to be to pass the instantiated driver to the healenium method like:

//declare delegate
WebDriver delegate = new ChromeDriver();
//create Self-healing driver
SelfHealingDriver driver = SelfHealingDriver.create(delegate);

But this is obviously being done when the driver is being created at runtime rather than during the initialisation. I'll keep digging to see if anyone else has come up with a solution.

**Comment by globalworming** [comment]
that doesn't look right, should be like:

```
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.test.utilities.HealeniumDriverWrapper
thucydides.driver.capabilities = mydriver
```

**Comment by globalworming** [comment]
just tried with serenity v3.3.7 and it still works...
serenity.conf like 
```
webdriver {
  driver = provided
  provided {
    type = mydriver
    mydriver = com.example.MyCustomDriver
  }
}

thucydides.driver.capabilities = mydriver
```

and using an `OnlineCast` or the `@Managed` annotation.. and it will invoke the driver 

```
09:00:29.555 [main] DEBUG n.serenitybdd.core.pages.PageObject - Opening page at url https://example.com/issues/test
new driver call
```

```
package com.example;

import net.thucydides.core.webdriver.DriverSource;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class MyCustomDriver implements DriverSource {

  @Override
  public WebDriver newDriver() {
    System.out.println("new driver call");
    return new ChromeDriver();
  }

  @Override
  public boolean takesScreenshots() {
    return true;
  }
}
```

https://github.com/globalworming/serenity-junit-screenplay-starter/commit/fbe6ea054544a6037dceb37e2812771c91856fe6

**Comment by TheGlovner** [comment]
Schoolboy error on my part, I though the "mydriver" value was a placeholder for the Class name of the driver I was trying to bring in.

Okay so I've fixed the properties and have my custom driver class set up, put a debug step in and it's certainly going there but chrome not firing up or hitting the provided page. 

Assume I'm now missing the part around the @Managed annotation you suggested.

Where does this annotation actually go?

**Comment by globalworming** [comment]
no, you don't need it. if the debug reaches your custom driver, then you are good. you may get errors now because of  missing chrome options and capabilities you have to configure. 
what error message do you get?

**Comment by TheGlovner** [comment]
Hmmm, my mistake it seems, I swear it hit the breakpoint in there previously before I made some changes, god knows what was in there to make it happen though:

```
Message:Page not loaded in the given time, page title:
Could not instantiate the custom webdriver provider of type com.test.utilities.HealeniumDriverWrapper
java.lang.AssertionError: Message:Page not loaded in the given time, page title:
Could not instantiate the custom webdriver provider of type com.test.utilities.HealeniumDriverWrapper
	at org.junit.Assert.fail(Assert.java:89)
	at gov.scot.utilities.common.BasePageObject.waitForCondition(BasePageObject.java:1190)
	at gov.scot.utilities.common.BasePageObject.waitForCondition(BasePageObject.java:1224)
	at gov.scot.utilities.common.BasePageObject.waitForPageLoading(BasePageObject.java:1154)
	at gov.scot.utilities.common.BasePageObject.containsElements(BasePageObject.java:1252)
	at gov.scot.pages.spm.common.LoginPage.lambda$setSpmLoginUsername$0(LoginPage.java:15)
	at gov.scot.utilities.common.BasePageObject.lambda$waitForCondition$23(BasePageObject.java:1175)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at gov.scot.utilities.common.BasePageObject.waitForCondition(BasePageObject.java:1173)
	at gov.scot.pages.spm.common.LoginPage.setSpmLoginUsername(LoginPage.java:15)
	at gov.scot.steps.spm.common.LoginPageSteps.i_login_to_spm(LoginPageSteps.java:266)
```

**Comment by TheGlovner** [comment]
Hmmm, my mistake it seems, I swear it hit the breakpoint in there previously before I made some changes, god knows what was in there to make it happen though:
```
Message:Page not loaded in the given time, page title:
Could not instantiate the custom webdriver provider of type com.test.utilities.HealeniumDriverWrapper
java.lang.AssertionError: Message:Page not loaded in the given time, page title:
Could not instantiate the custom webdriver provider of type com.test.utilities.HealeniumDriverWrapper
	at org.junit.Assert.fail(Assert.java:89)
	at com.test.utilities.common.BasePageObject.waitForCondition(BasePageObject.java:1190)
	at com.test.utilities.common.BasePageObject.waitForCondition(BasePageObject.java:1224)
	at com.test.utilities.common.BasePageObject.waitForPageLoading(BasePageObject.java:1154)
	at com.test.utilities.common.BasePageObject.containsElements(BasePageObject.java:1252)
	at com.test.pages.spm.common.LoginPage.lambda$setSpmLoginUsername$0(LoginPage.java:15)
	at com.test.utilities.common.BasePageObject.lambda$waitForCondition$23(BasePageObject.java:1175)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at com.test.utilities.common.BasePageObject.waitForCondition(BasePageObject.java:1173)
	at com.test.pages.spm.common.LoginPage.setSpmLoginUsername(LoginPage.java:15)
	at com.test.steps.spm.common.LoginPageSteps.i_login_to_spm(LoginPageSteps.java:266)
```

**Comment by TheGlovner** [comment]
God, I'm an idiot. I needed to alter the package name back (sensitive data and all that).

So altered the package name back to the internal path I have. Ran it in debug with a breakpoint on:

```
WebDriver chromeDelegate = new ChromeDriver();
```

And it is hitting it now, Set it off running and it's just getting into a loop creating multiple instances of chrome. I suspect this is where the chrome options will come into play since it doesn't seem to know what URL to try and hit:

```
May 17, 2023 12:06:26 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Invalid Status code=403 text=Forbidden
java.io.IOException: Invalid Status code=403 text=Forbidden
	at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
	at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Is there a way to supply the chrome options that already exist in serenity.conf to the instantiation of the chromedriver? Or do they all have to be configured explictly again in the method of this implementation of the DriverSource interface?

**Comment by globalworming** [comment]
the error is solved by adding this option https://stackoverflow.com/a/75679117/1359903

> Is there a way to supply the chrome options that already exist in serenity.conf 
you should be able to access properties from there with `SystemEnvironmentVariables.currentEnvironmentVariables().getProperty("webdriver.provided.options")`

**Comment by TheGlovner** [comment]
Thanks for all your help this far, greatly appreciated. All previous work hasn't needed this level of interaction with these areas just the actual functional test code (I'm mostly coming from the manual test background into the automation sphere), I'll get to work on this and see where it goes next.
