### ISSUE TITLE
starting version 3.3.4 - getCurrentWindowHandle {} errors for device application

### ISSUE THREAD

**Issue by gsevtlana** [serenity-bdd/serenity-core#2984]
see the difference in screenshot
starting 3.3.4 - getting error on getCurrentWindowHandle, when running test on device application, tests not run -  Appium does not support getCurrentWindowHandle.
is there a workaround? 

------------
an unknown error has occurred
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: '5CG2212G3R', ip: '192.168.0.21', [os.name](http://os.name/): 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_25'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [c5fc0d78-7abc-4791-b5ba-c5397be721a3, getCurrentWindowHandle {}]
Capabilities {appium:CFBundleIdentifier: com.ed***.dcx.interna..., appium:accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI..., appium:appID: com.ed***.dcx.interna..., appium:assert_javascript_enabled: true, appium:audioStreamInfo: {"audioStreamingServerUrl":..., appium:authenticationTenant: operator, appium:autoLaunch: true, appium:bundleId: com.ed***.dcx.interna..., appium:cloud: ed***.[perfectomobile.com](http://perfectomobile.com/), appium:device: iphone, appium:deviceName: 00008110-00140CA61139801E, appium:deviceSessionId: c5fc0d78-7abc-4791-b5ba-c53..., appium:engineExternalExecId: c5fc0d78-7abc-4791-b5ba-c53..., appium:entityType: appium_driver, appium:executionId: c5fc0d78-7abc-4791-b5ba-c53..., appium:executionTenantId: ed***-perfectomobile-com, appium:host: ed***.[perfectomobile.com](http://perfectomobile.com/), appium:hub: [https://ed***.perfect](https://ed%2A%2A%2A.perfect/)..., appium:liveStreamEnabled: false, appium:mcmExecutionId: ********..., appium:password: , appium:pixelRatio: 3, appium:platformVersion: 16.0, appium:reportPdfUrl: [https://ed***.app.per](https://ed%2A%2A%2A.app.per/)..., appium:scriptName: RemoteWebDriver, appium:sdkVersion: 16.0, appium:securityToken: , appium:serverConnector: , appium:serverHost: [100.86.76.130:11604](http://100.86.76.130:11604/), appium:simpleIsVisibleCheck: true, appium:statBarHeight: 47, appium:stopUrl: [https://ed***.perfect](https://ed%2A%2A%2A.perfect/)..., appium:streamInfo: {"url":"https://ed/***..., appium:testGridReportUrl: [https://ed***.app.per](https://ed%2A%2A%2A.app.per/)..., appium:testRunWithPureAppiumFlow: false, appium:udid: 00008110-00140CA61139801E, appium:user: , appium:viewportRect: {height: 2391, left: 0, top: 141, width: 1170}, appium:webdriver.remote.sessionid: c5fc0d78-7abc-4791-b5ba-c53..., appium:xcuitestFindOptimizations: true, platformName: IOS}
Session ID: c5fc0d78-7abc-4791-b5ba-c5397be721a3
org.openqa.selenium.WebDriverException: An unknown error has occurred
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: '5CG2212G3R', ip: '192.168.0.21', [os.name](http://os.name/): 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_25'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [c5fc0d78-7abc-4791-b5ba-c5397be721a3, getCurrentWindowHandle {}]
Capabilities {appium:CFBundleIdentifier: com.ed***.dcx.interna..., appium:accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI..., appium:appID: com.ed***.dcx.interna..., appium:assert_javascript_enabled: true, appium:audioStreamInfo: {"audioStreamingServerUrl":..., appium:authenticationTenant: operator, appium:autoLaunch: true, appium:bundleId: com.ed***.dcx.interna..., appium:cloud: ed***.[perfectomobile.com](http://perfectomobile.com/), appium:device: iphone, appium:deviceName: 00008110-00140CA61139801E, appium:deviceSessionId: c5fc0d78-7abc-4791-b5ba-c53..., appium:engineExternalExecId: c5fc0d78-7abc-4791-b5ba-c53..., appium:entityType: appium_driver, appium:executionId: c5fc0d78-7abc-4791-b5ba-c53..., appium:executionTenantId: ed***-perfectomobile-com, appium:host: ed***.[perfectomobile.com](http://perfectomobile.com/), appium:hub: [https://ed***.perfect](https://ed%2A%2A%2A.perfect/)..., appium:liveStreamEnabled: false, appium:mcmExecutionId: *********..., appium:password: , appium:pixelRatio: 3, appium:platformVersion: 16.0, appium:reportPdfUrl: [https://ed***.app.per](https://ed%2A%2A%2A.app.per/)..., appium:scriptName: RemoteWebDriver, appium:sdkVersion: 16.0, appium:securityToken: , appium:serverConnector: , appium:serverHost: [100.86.76.130:11604](http://100.86.76.130:11604/), appium:simpleIsVisibleCheck: true, appium:statBarHeight: 47, appium:stopUrl: [https://ed***.perfect](https://ed%2A%2A%2A.perfect/)..., appium:streamInfo: {"url":"https://ed/***..., appium:testGridReportUrl: [https://ed***.app.per](https://ed%2A%2A%2A.app.per/)..., appium:testRunWithPureAppiumFlow: false, appium:udid: 00008110-00140CA61139801E, appium:user: , appium:viewportRect: {height: 2391, left: 0, top: 141, width: 1170}, appium:webdriver.remote.sessionid: c5fc0d78-7abc-4791-b5ba-c53..., appium:xcuitestFindOptimizations: true, platformName: IOS}
Session ID: c5fc0d78-7abc-4791-b5ba-c5397be721a3
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:267)
        at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:465)
        at net.thucydides.core.webdriver.WebDriverFacade.getWindowHandle(WebDriverFacade.java:333)
        **at net.serenitybdd.core.photography.WebDriverPhotoLens.alertIsDisplayedFor(WebDriverPhotoLens.java:43)**
        at net.serenitybdd.core.photography.WebDriverPhotoLens.canTakeScreenshot(WebDriverPhotoLens.java:34)
        at net.serenitybdd.core.photography.PhotoSession.takeScreenshot(PhotoSession.java:47)
        at net.serenitybdd.core.photography.PhotoSessionBooking.takeScreenshot(PhotoSessionBooking.java:36)
        at net.thucydides.core.steps.BaseStepListener.screenshotFrom(BaseStepListener.java:1104)
        at net.thucydides.core.steps.BaseStepListener.lambda$grabScreenshots$9(BaseStepListener.java:1094)
        at net.thucydides.core.steps.BaseStepListener$$Lambda$489/27571193.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at net.thucydides.core.steps.BaseStepListener.grabScreenshots(BaseStepListener.java:1096)
        at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:991)
        at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:985)
        at net.thucydides.core.steps.BaseStepListener.takeInitialScreenshot(BaseStepListener.java:1078)
        at net.thucydides.core.steps.BaseStepListener.stepStarted(BaseStepListener.java:704)
        at net.thucydides.core.steps.StepEventBus.stepStarted(StepEventBus.java:455)
        at net.thucydides.core.steps.StepEventBus.stepStarted(StepEventBus.java:444)
        at net.thucydides.core.steps.StepInterceptor.notifyStepStarted(StepInterceptor.java:570)
        at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:208)
        at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:196)
        at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:84)
        at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
        at com.ed***.test.steps.DirectoryLoginSteps$ByteBuddy$Vzz0Kujt.verifyApplicationIsLaunched(Unknown Source)
        at com.ed***.test.testcases.MobileTest.configTest(MobileTest.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:472)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:446)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:61)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:255)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

![Serenity 3 4_PerfectoFailure](https://user-images.githubusercontent.com/22656279/205561099-1efd6e87-45e4-448c-9d79-dbf43e36aa40.JPG)

**Comment by ricardorlg** [comment]
use latest version

**Comment by gsevtlana** [comment]
all versions after 3.3.0 till 3.4.3 (latest on maven central) have same errors

**Comment by ricardorlg-yml** [comment]
weird I'm using the latest version with Appium, it runs without problem. I get the error messages on Appium server but it doesn't stop the execution.

**Comment by gsevtlana** [comment]
as a workaround, disabling screenshots helps

**Comment by wakaleo** [comment]
Possible fix/workaround in 3.5.1

**Comment by Ramesh1103** [comment]
Hi @ricardorlg-yml ,
may i know how you are passing android properties from serenity.conf with latest serenity version ?
With latest version I am unable to run Appium tests .
