### ISSUE TITLE
Cucumber junit 5 parallel execution No basse StepListerner when using remoteDriver

### ISSUE THREAD

**Issue by GianniGiglio** [serenity-bdd/serenity-core#3037]
Running cucumber junit 5 test in parallel is work when using a local driver but fails when using a remote driver.

The reason is probably because the wrong eventBus is used in the class RemoteDriverProvider.

Current implementation:

https://github.com/serenity-bdd/serenity-core/blob/main/serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/RemoteDriverProvider.java#L75

` TestOutcome testOutcome = StepEventBus.getEventBus().getBaseStepListener().getCurrentTestOutcome();`

In this case the baseStepListener will be null and throw the stacktrace below.

I might have a fix but am unable to test it since I don't seem to be able to build the master branch using gradle.

Possible solution:

        TestOutcome testOutcome =null;
            if (StepEventBus.getParallelEventBus().isBaseStepListenerRegistered()){
                testOutcome =StepEventBus.getParallelEventBus().getBaseStepListener().getCurrentTestOutcome();
            }else {

             testOutcome = StepEventBus.getEventBus().getBaseStepListener().getCurrentTestOutcome();

}

java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1383)
	at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:194)
	at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider.newInstance(RemoteDriverProvider.java:75)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:162)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:140)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:158)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:149)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:119)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:189)

**Comment by GianniGiglio** [comment]
@cliviu Sorry to ping you but since you did some fixes for parellel execution perhaps you can have a look.

**Comment by cliviu** [comment]
Yes, is in my backlog. I will have a look over the weekend.

**Comment by GianniGiglio** [comment]
Already opened a Pr since I was able to build using maven 
https://github.com/serenity-bdd/serenity-core/pull/3040

**Comment by wakaleo** [comment]
Should be fixed in 3.6.12
