### ISSUE TITLE
Adding "headless" arg to goog:chromeOptions causes driver configuration error

### ISSUE THREAD

**Issue by Angelthree95** [serenity-bdd/serenity-core#3054]
Hi,
I have a problem with running tests in headless mode with default driver configuration in serenity.conf.
I'm running tests with JUnitRunner and maven on my Windows PC.
My current webdriver config in serenity.conf (based on https://github.com/serenity-bdd/serenity-core/issues/2964 and https://serenity-bdd.github.io/docs/guide/driver_config ):
```
webdriver {
	driver = "chrome"
	autodownload = true

	timeouts {
		script = 30000
		pageLoad = 300000
		implicit = 15000
	}

	capabilities {
		browserName = "chrome"
		acceptInsecureCerts = true
		"goog:chromeOptions" {
			args = ["incognito", "no-sandbox", "ignore-certificate-errors", "disable-popup-blocking", "disable-default-apps", "disable-extensions-file-access-check", "disable-infobars", "window-size=1920,1080", "headless"]
		}
	}
}
```

First of all (what is weird to me) Serenity reports doubled chrome args in test run log:
`
11:51:06.712 [main] INFO  n.s.c.w.d.ChromeDriverProvider - Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, --headless], extensions: []}}
`
Also starting from Serenity version 3.6 "--headless" arg is included when adding "headless" arg.

Disabling the "headless" arg in goog:chromeOptions results in tests running fine, but I need headless driver for remote test execution.
I went back as far as Serenity version 3.3.6 but found no improvement.

Here is the eroor message I get when running headless: 
```
net.thucydides.core.webdriver.DriverConfigurationError: 
WebDriver was unable to create a new instance of type class org.openqa.selenium.chrome.ChromeDriver
WebDriver reported the following message: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-JM326OV', ip: '10.251.1.9'
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, --headless], extensions: []}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, --headless], extensions: []}}}]
See below for more details.
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:150)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:161)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:152)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:122)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:192)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:982)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:880)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:868)
	at pl.org.bn.qa.polona2.login_page.LoginPageSteps.givenImLoggedIn(LoginPageSteps.java:72)
	at pl.org.bn.qa.polona2.login_page.LoginPageSteps$ByteBuddy$iSM5C9Km.givenImLoggedIn$accessor$uZqapBe9(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:518)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:498)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:472)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:211)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:198)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:86)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at pl.org.bn.qa.polona2.login_page.LoginPageSteps$ByteBuddy$iSM5C9Km.givenImLoggedIn(Unknown Source)
	at pl.org.bn.qa.polona2.pdn.scientific_project.CreateScientificProjectTestSuite.createScientificProjectMinimalData(CreateScientificProjectTestSuite.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:234)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:228)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:131)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-JM326OV', ip: '10.251.1.9'
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, --headless], extensions: []}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, incognito, no-sandbox, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-extensions-file-acc..., disable-infobars, window-size=1920,1080, headless, --headless], extensions: []}}}]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:71)
	at net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider.newInstance(ChromeDriverProvider.java:73)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:162)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:140)
	... 95 more
Caused by: java.lang.RuntimeException: NettyHttpHandler request execution error
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:124)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 103 more
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:11045 after 180000 ms
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 116 more
Caused by: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:11045 after 180000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Any help would be greatly appreciated.

**Comment by zzoubian** [comment]
hello, have you tried changing headless to:
headless=chrome, or headless=new
see blog post here:
https://serenity-bdd.github.io/blog/2023/02/02/index

**Comment by Angelthree95** [comment]
Thanks! That fixed it

**Comment by madduci** [comment]
I am still experiencing this issue, as also the #2743. Locally on my machine, it works without problems with all the browsers I've configured (Firefox, Edge, Chrome). On a remote Virtual VM with Windows Core 2022 or a Windows Docker Container (Core 2022) i get the error that it crashes.

It seems like it has to do with the parsing/passing of parameters to drivers from the `serenity.conf`, because instrumenting the Driver programmatically in java (e.g. with the `driver.addArguments("--headless"))` works fine and the driver works as intended.

It looks like the arguments get parsed twice, from logs:

```
Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [headless, incognito, disable-gpu, disable-default-apps, disable-popup-blocking, window-size=1920,1080, headless, incognito, disable-gpu, disable-default-apps, disable-popup-blocking, window-size=1920,1080, remote-allow-origins=*]
```

but in my `serenity.conf` I have the following configurations:

```
"goog:chromeOptions" {
            args = ["headless", "incognito", "disable-gpu", "disable-default-apps", "disable-popup-blocking", "window-size=1920,1080"]
}
```

**Comment by Angelthree95** [comment]
> I am still experiencing this issue, as also the #2743. Locally on my machine, it works without problems with all the browsers I've configured (Firefox, Edge, Chrome). On a remote Virtual VM with Windows Core 2022 or a Windows Docker Container (Core 2022) i get the error that it crashes.
> 
> My current Serenity Version is the `4.1.0` and i'm using the Selenium `4.17.0` to support CDP 121.
> 
> It seems like it has to do with the parsing/passing of parameters to drivers from the `serenity.conf`, because instrumenting the Driver programmatically in java (e.g. with the `driver.addArguments("--headless"))` works fine and the driver works as intended.
> 
> It looks like the arguments get parsed twice, from logs:
> 
> ```
> Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [headless, incognito, disable-gpu, disable-default-apps, disable-popup-blocking, window-size=1920,1080, headless, incognito, disable-gpu, disable-default-apps, disable-popup-blocking, window-size=1920,1080, remote-allow-origins=*]
> ```
> 
> but in my `serenity.conf` I have the following configurations:
> 
> ```
> "goog:chromeOptions" {
>    args = ["headless", "incognito", "disable-gpu", "disable-default-apps", "disable-popup-blocking", "window-size=1920,1080"]
> }
> ```

I did it with serenity.conf only. You don't have to pass any other arguments again.
```
"goog:chromeOptions" {
			args = [
				"incognito",
				"no-sandbox",
				"ignore-certificate-errors",
				"remote-allow-origins=*",
				"disable-popup-blocking",
				"disable-default-apps",
				"disable-extensions-file-access-check",
				"disable-infobars",
				"window-size=1920,1080",
				"disable-dev-shm-usage",
				"disable-gpu",
				"headless=new"
			]
		}
```

**Comment by madduci** [comment]
> I did it with serenity.conf only. You don't have to pass any other arguments again.
> 
> ```
> "goog:chromeOptions" {
> 			args = [
> 				"incognito",
> 				"no-sandbox",
> 				"ignore-certificate-errors",
> 				"remote-allow-origins=*",
> 				"disable-popup-blocking",
> 				"disable-default-apps",
> 				"disable-extensions-file-access-check",
> 				"disable-infobars",
> 				"window-size=1920,1080",
> 				"disable-dev-shm-usage",
> 				"disable-gpu",
> 				"headless=new"
> 			]
> 		}
> ```

yes, i apply only once in the `serenity.conf` these settings and it gets logged twice in the targeted machine and the driver doesn't start.

If i put these arguments programmatically, instead of using the `serenity.conf` properties, it works
