### ISSUE TITLE
Multiple browser capabilities configuration.

### ISSUE THREAD

**Issue by lRaulMN7** [serenity-bdd/serenity-core#3077]
Hello! I can see in the documentation that I can give capabilities configuration in the serenity.conf file. https://serenity-bdd.github.io/docs/guide/driver_config

This works for my edge execution.

webdriver {
      capabilities{
        browserName = "MicrosoftEdge"
        "ms:edgeOptions" {
              args = ["test-type", "ignore-certificate-errors", "headless", "--start-maximized"
                "incognito", "disable-infobars", "disable-gpu", "disable-default-apps", "disable-popup-blocking"]
            }
      }
}

This works for my Chrome execution

webdriver {
  capabilities {
    browserName = "Chrome"
    "goog:chromeOptions" {
      args = [ "start-maximized", "headless"]
    }
  }
}

However, I want my test to run in multiple browsers + each browser will have different capabilities. I can not afford to change the serenity.conf every time I need to run the tests in a different browser.

I've seen somebody in another ticket to configure the webdriver object within the environments object, but I want to keep this for URL settings. For me, having different "environments" for each browser doesn't make sense. I want to have different environments **and** different browsers, so call my tests using -Denvironment and something like -Dbrowser. 

I've also seen a workaround using Java calls and a provided driver browser, but this adds a lot of overhead and kills the beauty of tools like serenity and webdrivermanager. 

Is there any way to do this in the latest version? If not, would this be an accepted feature for a PR?
Thanks in advance.

**Comment by lRaulMN7** [comment]
I forgot to mention, I've tried the following conf:

capabilities{
        "ms:edgeOptions" {
              args = ["test-type", "ignore-certificate-errors", "headless", "--start-maximized"
                "incognito", "disable-infobars", "disable-gpu", "disable-default-apps", "disable-popup-blocking"]
        }
        "goog:chromeOptions" {
            args = [ "start-maximized", "headless"]
        }
}

which results in the edge driver not picking up any of the capabilities.

**Comment by wakaleo** [comment]
This isn't currently supported but may be in a future version.

**Comment by lRaulMN7** [comment]
Thanks @wakaleo !

I've been reading the code for the first time and I believe this change should be implemented in the SerenityWebdriverManager class. The way I see it, user should be able to define a single capability 

```
webdriver {
  capabilities {
    browserName = "Chrome"
    "goog:chromeOptions" {
    args = [ "start-maximized", "headless"]
    }
  }
}
```

but also, several ones

```
webdrivers {
  webdriver-edge {
    capabilities {
      browserName = "MicrosoftEdge"
      "ms:edgeOptions" {
        args = ["test-type", "ignore-certificate-errors", "headless", "--start-maximized", "incognito", "disable-infobars", "disable-gpu", "disable-default-apps", "disable-popup-blocking"]
      }
    }
  }

  webdriver-chrome {
    capabilities {
      browserName = "chrome"
      chromeOptions {
        args = ["--disable-extensions", "--disable-infobars", "--headless", "--disable-gpu", "--start-maximized", "--incognito", "--no-sandbox", "--disable-popup-blocking"]
      }
    }
  }
}
```

And define the one he wants to use with webdriver.driver or from the Thudecities class (serenity.properties). If no one defined, default to either the first webdriver defined in the list, or default to Chrome. 

It shouldn't be a breaking change if made backwards compatible. Also, we have multiple tests regarding wrong/incomplete .conf files so this can help us implement the change.

**Comment by wakaleo** [comment]
Hi @lRaulMN7, I'd definitely like to explore this option - that would make it easier to configure different tests with different browsers. I (also) intend to set up a way to run the same test through multiple browsers, but that involves intervening in the JUnit and Cucumber runners, which is a much bigger change. Your idea would be a great addition and would not involve as big a change to the code base.

**Comment by dkoudrin** [comment]
Would love to see this change implemented. As I'm in the same boat - I don't see a way to test on multiple different browsers using serenity (on an individual test/feature basis) currently.

**Comment by rehmanuet** [comment]
Can we please have multiple browser support?

Multiple Driver + Custom Driver (could be anything, Appium, Browsertack, Custom Chrome Implemetation)
for example

serenity.conf

`
environments {
  provided {
      webdriver {
      webdriver.driver = provided
      webdriver.provided.type = mydriver
      webdriver.provided.mydriver = runner.CustomWebDriverProvider
      browser=chrome
      thucydides.driver.capabilities = mydriver
      }
    }
  edge {
    webdriver {
      capabilities {
        browserName = "MicrosoftEdge"
        "ms:edgeOptions" {
          args = ["test-type", "ignore-certificate-errors", "headless",
            "incognito", "disable-infobars", "disable-gpu", "disable-default-apps", "disable-popup-blocking"]
        }
      }
    }
  }
  firefox {
    webdriver {
      capabilities {
        browserName = "firefox"
        pageLoadStrategy = "normal"
        acceptInsecureCerts = true
        unhandledPromptBehavior = "dismiss"
        strictFileInteractability = true

        "moz:firefoxOptions" {
          args = ["-headless"],
          prefs {
            "javascript.options.showInConsole": false
          },
          log {"level": "info"},
        }
      }
    }
  }
}
`

**Comment by wakaleo** [comment]
You can do this already - that's what the environments section is for.

**Comment by rehmanuet** [comment]
@wakaleo , Thanks for the reply, regarding above comment

I'm getting  following error when I'm using it from serenity conf, otherwise  CustomWebDriverProvider works fine

Error: Environment 'browser' property undefined for environment '[custom]'

My serenity.conf file:

```
# serenity {
#     take.screenshots = FOR_FAILURES
# }

headless.mode = false

environments {
  custom {
      webdriver {
      driver = provided
     provided {
     type = mydriver
     mydriver = runner.CustomWebDriverProvider
         }
      browser=firefox
      thucydides.driver.capabilities = mydriver
      }
    }
  edge {
    webdriver {
      capabilities {
        browserName = "MicrosoftEdge"
        "ms:edgeOptions" {
          args = ["test-type", "ignore-certificate-errors", "headless",
            "incognito", "disable-infobars", "disable-gpu", "disable-default-apps", "disable-popup-blocking"]
        }
      }
    }
  }
  firefox {
    webdriver {
      capabilities {
        browserName = "firefox"
        pageLoadStrategy = "normal"
        acceptInsecureCerts = true
        unhandledPromptBehavior = "dismiss"
        strictFileInteractability = true

        "moz:firefoxOptions" {
          args = ["-headless"],
          prefs {
            "javascript.options.showInConsole": false
          },
          log {"level": "info"},
        }
      }
    }
  }
}
```


my custom webdriver file looks lke
```java
package runner;

import com.liita.tas.drivermanager.Browser;
import com.liita.tas.drivermanager.DriverFactory;
import net.serenitybdd.model.environment.EnvironmentSpecificConfiguration;
import net.thucydides.core.webdriver.DriverSource;
import net.thucydides.model.environment.SystemEnvironmentVariables;
import org.openqa.selenium.WebDriver;

import java.net.MalformedURLException;


public class CustomWebDriverProvider implements DriverSource {

    @Override
    public WebDriver newDriver() {
        try {
            return initBrowser().getDriver();
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
    }

    public static Browser initBrowser() throws MalformedURLException {
        EnvironmentSpecificConfiguration value = EnvironmentSpecificConfiguration.from(SystemEnvironmentVariables.createEnvironmentVariables());
        WebDriver driver = DriverFactory.init(value.getProperty("browser"), "locale");
        return new Browser(driver, Integer.parseInt(value.getProperty("element.timeout")), Integer.parseInt(value.getProperty("page.timeout")));
    }

    @Override
    public boolean takesScreenshots() {
        return true; // Set it to true if you want Serenity to take screenshots
    }
}
```


Error
``` bash
10:41:36.577 [ForkJoinPool-2-worker-1] ERROR  -     Test failed at step: Given "ES US Basic" is logged into the dashboard
10:41:36.577 [ForkJoinPool-2-worker-1] ERROR  -     WebDriver was unable to create a new instance of type class net.thucydides.core.webdriver.ProvidedDriver
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.764 s <<< FAILURE! -- in runner.Junit5CucumberRunnerDEV
[ERROR] Login Page.User able to have Smile/Message buttons throughout Match profile Screen -- Time elapsed: 3.585 s <<< ERROR!
net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class net.thucydides.core.webdriver.ProvidedDriver
        at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:181)
        at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:169)
        at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:120)
        at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:209)
        at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:982)
        at net.serenitybdd.core.pages.PageObject.openUrl(PageObject.java:928)
        at com.liita.tas.stepdefinitions.LoginSteps.isLoggedIntoTheDashboard(LoginSteps.java:43)
        at ✽."ES US Basic" is logged into the dashboard(classpath:features/Login.feature:6)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class net.thucydides.core.webdriver.ProvidedDriver
WebDriver reported the following message: Could not instantiate the custom webdriver provider of type mydriver
See below for more details.
        at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:152)
        at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:178)
        at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:169)
        at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:120)
        at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:209)
        at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:982)
        at net.serenitybdd.core.pages.PageObject.openUrl(PageObject.java:928)
        at com.liita.tas.stepdefinitions.LoginSteps.isLoggedIntoTheDashboard(LoginSteps.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
        at io.cucumber.java.Invoker.invoke(Invoker.java:24)
        at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
        at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
        at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
        at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
        at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
        at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:84)
        at io.cucumber.core.runner.TestStep.run(TestStep.java:56)
        at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
        at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
        at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
        at io.cucumber.junit.platform.engine.CucumberEngineExecutionContext.lambda$runTestCase$4(CucumberEngineExecutionContext.java:112)
        at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:137)
        at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
        at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:137)
        at io.cucumber.junit.platform.engine.CucumberEngineExecutionContext.runTestCase(CucumberEngineExecutionContext.java:109)
        at io.cucumber.junit.platform.engine.NodeDescriptor$PickleDescriptor.execute(NodeDescriptor.java:168)
        at io.cucumber.junit.platform.engine.NodeDescriptor$PickleDescriptor.execute(NodeDescriptor.java:90)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.RuntimeException: Could not instantiate the custom webdriver provider of type mydriver
        at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:24)
        at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:164)
        at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:142)
        ... 33 more
Caused by: net.serenitybdd.model.environment.UndefinedEnvironmentVariableException: Environment 'browser' property undefined for environment '[custom]'
        at net.serenitybdd.model.environment.EnvironmentSpecificConfiguration.lambda$getProperty$11(EnvironmentSpecificConfiguration.java:196)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at net.serenitybdd.model.environment.EnvironmentSpecificConfiguration.getProperty(EnvironmentSpecificConfiguration.java:192)
        at runner.CustomWebDriverProvider.initBrowser(CustomWebDriverProvider.java:27)
        at runner.CustomWebDriverProvider.newDriver(CustomWebDriverProvider.java:18)
        at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:22)
        ... 35 more

```

**Comment by rehmanuet** [comment]
Thanks, I found out my mistake, and its working fine.

**Comment by juanfelipe28** [comment]
@wakaleo Is there any possibility of running a parallel crossbrowser in serenity?
