### ISSUE TITLE
Unable to launch new chrome instance after updating chrome from version 110 to 111

### ISSUE THREAD

**Issue by cb-rajeshkumar** [serenity-bdd/serenity-core#3081]
@wakaleo After updating the chrome am getting below error while trying to launch new driver. Am using latest version 3.6.12

net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
	at app//net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:164)
	at app//net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:152)
	at app//net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:122)
	at app//net.serenitybdd.core.pages.PageObject.hasDevTools(PageObject.java:300)
	at app//net.serenitybdd.core.pages.PageObject.getDevTools(PageObject.java:311)
	at app//net.serenitybdd.screenplay.actions.WithDevTools.performAs(WithDevTools.java:48)
	at app//net.serenitybdd.screenplay.Actor.performTask(Actor.java:296)
	at app//net.serenitybdd.screenplay.Actor.perform(Actor.java:275)
	at app//net.serenitybdd.screenplay.Actor.performWithoutReporting(Actor.java:258)
	at app//net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:213)
	at app//net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:222)
	at app//cb.stepdefinitions.Merchant.ActionStepDefinition.actorIsTheMerchant(ActionStepDefinition.java:47)
	at ✽.truecaller is the merchant(./src/test/resources/features/rebranding/cb_rebranding.feature:6)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class org.openqa.selenium.chrome.ChromeDriver
WebDriver reported the following message: Unable to establish websocket connection to http://localhost:64430/devtools/browser/32bc8ef7-022b-43d6-8c01-aecb8ecd182f
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.5.1', java.version: '11.0.17'
Driver info: driver.version: ChromeDriver
See below for more details.
	at app//net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:150)
	at app//net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:161)
	at app//net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:152)
	at app//net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:122)
	at app//net.serenitybdd.core.pages.PageObject.hasDevTools(PageObject.java:300)
	at app//net.serenitybdd.core.pages.PageObject.getDevTools(PageObject.java:311)
	at app//net.serenitybdd.screenplay.actions.WithDevTools.performAs(WithDevTools.java:48)
	at app//net.serenitybdd.screenplay.Actor.performTask(Actor.java:296)
	at app//net.serenitybdd.screenplay.Actor.perform(Actor.java:275)
	at app//net.serenitybdd.screenplay.Actor.performWithoutReporting(Actor.java:258)
	at app//net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:213)
	at app//net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:222)
	at app//cb.stepdefinitions.Merchant.ActionStepDefinition.actorIsTheMerchant(ActionStepDefinition.java:47)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:566)
	at app//io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at app//io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at app//io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at app//io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at app//io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at app//io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at app//io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at app//io.cucumber.core.runner.TestStep.executeStep(TestStep.java:84)
	at app//io.cucumber.core.runner.TestStep.run(TestStep.java:56)
	at app//io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at app//io.cucumber.core.runner.TestCase.run(TestCase.java:84)
	at app//io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at app//io.cucumber.junit.PickleRunners$NoStepDescriptions.lambda$run$0(PickleRunners.java:151)
	at app//io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:130)
	at app//io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at app//io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:130)
	at app//io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:148)
	at app//io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144)
	at app//io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at app//io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137)
	at app//io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:259)
	at app//io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:59)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:288)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:64430/devtools/browser/32bc8ef7-022b-43d6-8c01-aecb8ecd182f
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.5.1', java.version: '11.0.17'
Driver info: driver.version: ChromeDriver
	at app//org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
	at app//org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
	at app//org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:107)
	at app//org.openqa.selenium.devtools.Connection.<init>(Connection.java:78)
	at app//org.openqa.selenium.chromium.ChromiumDriver.lambda$new$2(ChromiumDriver.java:116)
	at java.base@11.0.17/java.util.Optional.map(Optional.java:265)
	at app//org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
	at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:71)
	at app//net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider.newInstance(ChromeDriverProvider.java:73)
	at app//net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:162)
	at app//net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:140)
	... 76 more

**Comment by globalworming** [comment]
that's a bug in chromedriver, see https://groups.google.com/g/chromedriver-users/c/xL5-13_qGaA

**Comment by globalworming** [comment]
there is a workaround

```
Actually, I have it figured out after enabling verbose logging of chromedriver:

[32332:259:0214/190812.204658:ERROR:devtools_http_handler.cc(766)] Rejected an incoming WebSocket connection from the http://localhost:58642/ origin. Use the command line flag --remote-allow-origins=http://localhost:58642/ to allow connections from this origin or --remote-allow-origins=* to allow all origins.

So I added the --remote-allow-origin=* to the ChromeOptions and I can successfully connect:

ChromeOptions ops = new ChromeOptions();
ops.addArguments("--remote-allow-origins=*");
```

**Comment by cb-rajeshkumar** [comment]
Thanks @globalworming Its working!!

**Comment by jerrin89** [comment]
> there is a workaround
> 
> ```
> Actually, I have it figured out after enabling verbose logging of chromedriver:
> 
> [32332:259:0214/190812.204658:ERROR:devtools_http_handler.cc(766)] Rejected an incoming WebSocket connection from the http://localhost:58642/ origin. Use the command line flag --remote-allow-origins=http://localhost:58642/ to allow connections from this origin or --remote-allow-origins=* to allow all origins.
> 
> So I added the --remote-allow-origin=* to the ChromeOptions and I can successfully connect:
> 
> ChromeOptions ops = new ChromeOptions();
> ops.addArguments("--remote-allow-origins=*");
> ```

Where to find the Chromeoption??

**Comment by globalworming** [comment]
usually you'd add it to the serenity.conf https://github.com/serenity-bdd/serenity-core/issues/3083#issuecomment-1463548553
