### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by bachhavdipak** [serenity-bdd/serenity-core#3093]
Gettong below exception while running test in parallel mode.

```
junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.default = same_thread
junit.jupiter.execution.parallel.mode.classes.default = same_thread
junit.jupiter.execution.parallel.config.strategy = dynamic

```

Error log:
```

                    java.lang.OutOfMemoryError: Java heap space
                        at java.base/java.util.regex.Pattern$BnM.optimize(Pattern.java:5543)
                        at java.base/java.util.regex.Pattern.compile(Pattern.java:1796)
                        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1429)
                        at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
                        at java.base/java.lang.String.replaceAll(String.java:2126)
                        at net.thucydides.core.ThucydidesSystemProperty.withSerenityPrefix(ThucydidesSystemProperty.java:1721)
                        at net.thucydides.core.ThucydidesSystemProperty.optionalPropertyValueDefinedIn(ThucydidesSystemProperty.java:1796)
                        at net.thucydides.core.ThucydidesSystemProperty.from(ThucydidesSystemProperty.java:1735)
                        at net.thucydides.core.webdriver.appium.AppiumConfiguration.definedTargetPlatform(AppiumConfiguration.java:105)
                        at net.thucydides.core.webdriver.appium.AppiumConfiguration.currentlyConfiguredTargetPlatform(AppiumConfiguration.java:81)
                        at net.thucydides.core.webdriver.appium.AppiumConfiguration.isDefined(AppiumConfiguration.java:223)
                        at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:40)
                        at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:30)
                        at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
                        at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:20)
                        at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:167)
                        at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:171)
                        at net.thucydides.core.pages.PageFactory.createFromSimpleConstructor(PageFactory.java:68)
                        at net.thucydides.core.pages.PageFactory.createPageOfType(PageFactory.java:38)
                        at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:83)
                        at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:50)
                        at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:84)
                        at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:50)
                        at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:206)
                        at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:196)
                        at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:177)
                        at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:124)
                        at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
                        at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:89)
                        at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:70)
                        at net.thucydides.core.steps.StepAnnotations.injectNestedScenarioStepsInto(StepAnnotations.java:62)
                        at net.thucydides.core.steps.StepFactory.instantiateAnyNestedStepLibrariesIn(StepFactory.java:405)

```

**Comment by wakaleo** [comment]
Could you try with 3.6.21? But I suspect the problem is JUnit 5 generating a very large number of parallel threads - try limiting the number of threads.

**Comment by bachhavdipak** [comment]
@wakaleo : I have tried with the latest core version 3.6.21 but still facing same issue but intrestingly when I downgrade serenity core version to  **3.5.1** its working as expected so I think issue is related to serenity core latest version

**Comment by cliviu** [comment]
Hi @bachhavdipak. How many tests do you have and how much heap are you allowing for your process? Maybe you can try by allowing more memory (-Xmx), see if it helps and if the limit is acceptable.

**Comment by bachhavdipak** [comment]
@wakaleo : Yes Iam getting stack trace with 3.6.21. Currently I am trying to execute 200+ test cases .

I am using **not any thread count** with my configuration and using **-Xmx5120M** memory.

**Comment by bachhavdipak** [comment]
@wakaleo : Please find below  stack trace for 3.6.21.

```
Caused by:
        org.junit.platform.commons.JUnitException: Error executing tests for engine junit-jupiter
            at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
            at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
            ... 30 more

            Caused by:
            java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
                at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
                at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
                ... 31 more

                Caused by:
                java.lang.OutOfMemoryError
                    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                    at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
                    ... 33 more

```

**Comment by wakaleo** [comment]
I haven't come across this before. If you have a commercial support package we could take a look at the project directly - otherwise it looks difficult to troubleshoot without a sample project.

**Comment by bachhavdipak** [comment]
No I dont , actually I am curious because its working without any issue with 3.5.1 version.

**Comment by bachhavdipak** [comment]
@wakaleo : How its working without any error with 3.5.1 version ?
