### ISSUE TITLE
EmptyStackException while running tests in parallel

### ISSUE THREAD

**Issue by vsitari** [serenity-bdd/serenity-core#3096]
Hello, 
I have such issue while running tests in parallel. I found here https://serenity-bdd.github.io/docs/guide/cucumber how to configure serenity for running parallel tests. If I run tests in more than two threads I encounter such error: 
java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:102)
	at net.thucydides.core.steps.BaseStepListener.getCurrentStep(BaseStepListener.java:769)
	at net.thucydides.core.steps.BaseStepListener.currentStepHasMoreThanOneScreenshot(BaseStepListener.java:1084)
	at net.thucydides.core.steps.BaseStepListener.removeDuplicatedInitialScreenshotsIfPresent(BaseStepListener.java:1070)
	at net.thucydides.core.steps.BaseStepListener.take(BaseStepListener.java:1001)
	at net.thucydides.core.steps.BaseStepListener.takeEndOfStepScreenshotFor(BaseStepListener.java:966)
	at net.thucydides.core.steps.BaseStepListener.stepFinished(BaseStepListener.java:797)
	at net.thucydides.core.steps.StepEventBus.stepFinished(StepEventBus.java:520)
	at io.cucumber.core.plugin.SerenityReporter.recordStepResult(SerenityReporter.java:834)
	at io.cucumber.core.plugin.SerenityReporter.handleResult(SerenityReporter.java:823)
	at io.cucumber.core.plugin.SerenityReporter.handleTestStepFinished(SerenityReporter.java:370)
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
	at io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
	at io.cucumber.core.runtime.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:62)
	at io.cucumber.core.runner.TestStep.emitTestStepFinished(TestStep.java:116)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:67)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)......
Sometimes for two threads I could face the same problem. 
What could be the cause? Thank you

**Comment by wakaleo** [comment]
Try with 3.6.22
