### ISSUE TITLE
Unable to download the chrome webdriver from company VPN while using the managedWebDriver of serenity

### ISSUE THREAD

**Issue by poojaBjAcharya** [serenity-bdd/serenity-core#3137]
Hi John,

It is a privilege for me to write an email. What a tool this serenity is!! Hats of to you guys.
In our organization people are very happy.

Coming back to the issue. 
Currently with the latest serenity I see that we are not able to download the chrome driver in the VPN. once I come out of the VPN I am able to download.
Is there any way to add the proxy and go over it to download the proxy.

**Below is the log for the same:**

Searching for a term(search-by-keyword;searching-for-a-term)
--------------------------------------------------------------------------------
May 19, 2023 9:57:41 AM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Unsuccessful command executed: [C:\Users\nishiveg\AppData\Local\Temp\selenium-manager864406660971009152018627625866544\selenium-manager.exe, --driver, chromedriver]
ERROR  error sending request for url (https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_win32.zip): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)

Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_332'
Driver info: driver.version: ChromeDriver
09:57:19.846 [main] INFO  n.s.c.w.d.ChromeDriverProvider - Starting Chrome driver instance with capabilities:
09:57:19.849 [main] INFO  n.s.c.w.d.ChromeDriverProvider - Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [remote-allow-origins=*, test-type, no-sandbox, ignore-certificate-errors, --window-size=1000,800, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, remote-allow-origins=*, test-type, no-sandbox, ignore-certificate-errors, --window-size=1000,800, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, remote-allow-origins=*], extensions: []}}
  [31mGiven [0m[31mUser navigates to SA url[0m                                                         [90m# com.fireflink.automation.stepdefinitions.LoginScreen.user_navigates_to_sa_url()[0m
      [31mnet.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
              at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:164)
              at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:152)
              at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:122)
              at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:192)
              at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:982)
              at net.serenitybdd.core.pages.PageObject.open(PageObject.java:880)
              at net.serenitybdd.core.pages.PageObject.open(PageObject.java:868)
              at com.fireflink.automation.navigation.BaseFile.navigateToSaUrl(BaseFile.java:24)
              at com.fireflink.automation.stepdefinitions.LoginScreen.user_navigates_to_sa_url(LoginScreen.java:22)
              at âœ½.User navigates to SA url(file:///C:/Pooja_Data/workspace/serenity-cucumber-starter/src/test/resources/features/search/search_by_keyword.feature:4)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class org.openqa.selenium.chrome.ChromeDriver
WebDriver reported the following message: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
See below for more details.

**Comment by onlybiju** [comment]
Try using proxy for auto download, pass the below command from run config. 
-Dwdm.proxy=proxyServer -Dwdm.proxyUser=companyUserName -Dwdm.proxyPass=password

**Comment by poojaBjAcharya** [comment]
With the above also I am facing the same issue. Any help please?

**Comment by onlybiju** [comment]
Can you paste here what you have tried you can mask userId and Password

**Comment by poojaBjAcharya** [comment]
Hi Sir,
thanks for the reply.

I have provided like this 

-Dwdm.proxy=10.158.100.6:8080 clean install

our proxy doesn't need username and password.

**Comment by poojaBjAcharya** [comment]
Hi Sir,

Thanks for providing a quick check.

I have provided like below now
-Dwdm.proxy=https://10.158.100.6:8080 clean install

But still no luck. I tried with http also, but unfortunately it is not working.

Any thing else I missing sir?
