### ISSUE TITLE
[Serenity Version 3.9.0] java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by bachhavdipak** [serenity-bdd/serenity-core#3184]
I am facing below OutOfMemoryError issue with the latest serenity 3.9.0 version while running my code same code is working with serenity 3.7.1 version without any issue. 

I have tried to increase heap space. Also tried to update junit-platform.properties but nothing is working.

```
023-07-12T18:41:35.2805682Z Gradle Test Executor 1 STANDARD_ERROR
2023-07-12T18:41:35.2806455Z     [ForkJoinPool-1-worker-3] INFO  - 
2023-07-12T18:41:35.2807100Z 
2023-07-12T18:41:35.2807577Z     -------------------------------------------------------------------------------------
2023-07-12T18:41:35.2808192Z          _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
2023-07-12T18:41:35.2906966Z         /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
2023-07-12T18:41:35.2907363Z        |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
2023-07-12T18:41:35.2907490Z         \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
2023-07-12T18:41:35.2907748Z     .----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
2023-07-12T18:41:35.2907892Z     |_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
2023-07-12T18:41:35.2908035Z                                                                                      
2023-07-12T18:41:35.2908370Z      News and tutorials at http://www.serenity-bdd.info                                  
2023-07-12T18:41:35.2908648Z      Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
2023-07-12T18:41:35.2908938Z      Join the Serenity Community on Gitter: https://gitter.im/serenity-bdd/serenity-core 
2023-07-12T18:41:35.2909223Z      Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
2023-07-12T18:41:35.2909530Z     -------------------------------------------------------------------------------------
2023-07-12T18:41:35.2909625Z 
2023-07-12T18:41:35.2909883Z     [ForkJoinPool-1-worker-3] INFO  - Test Suite Started: General master journey test
2023-07-12T18:41:35.2910164Z     [ForkJoinPool-1-worker-3] INFO  - Test Suite Started: General master journey test
2023-07-12T18:41:48.8810320Z 
2023-07-12T18:41:48.8829114Z UnknownClass.JUnit Jupiter > UnknownClass.executionError FAILED
2023-07-12T18:41:48.8829816Z     org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to execute tests
2023-07-12T18:41:48.8875179Z         at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:153)
2023-07-12T18:41:48.8875728Z         at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
2023-07-12T18:41:48.8876011Z         at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
2023-07-12T18:41:48.8876303Z         at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
2023-07-12T18:41:48.8876625Z         at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
2023-07-12T18:41:48.8876926Z         at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
2023-07-12T18:41:48.8877177Z         at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
2023-07-12T18:41:48.8877425Z         at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
2023-07-12T18:41:48.8878023Z         at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
2023-07-12T18:41:48.8878313Z         at app//org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
2023-07-12T18:41:48.8878799Z         at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
2023-07-12T18:41:48.8879360Z         at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
2023-07-12T18:41:48.8879739Z         at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
2023-07-12T18:41:48.8880040Z         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
2023-07-12T18:41:48.8880295Z         at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-07-12T18:41:48.8880532Z         at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-07-12T18:41:48.8880819Z         at java.base@11.0.19/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-07-12T18:41:48.8881062Z         at java.base@11.0.19/java.lang.reflect.Method.invoke(Method.java:566)
2023-07-12T18:41:48.8881295Z         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2023-07-12T18:41:48.8881542Z         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2023-07-12T18:41:48.8881802Z         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
2023-07-12T18:41:48.8882106Z         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2023-07-12T18:41:48.8882332Z         at com.sun.proxy.$Proxy2.stop(Unknown Source)
2023-07-12T18:41:48.8882539Z         at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
2023-07-12T18:41:48.8882802Z         at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
2023-07-12T18:41:48.8883083Z         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
2023-07-12T18:41:48.8883327Z         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
2023-07-12T18:41:48.8883601Z         at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
2023-07-12T18:41:48.8883900Z         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
2023-07-12T18:41:48.8884375Z         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
2023-07-12T18:41:48.8884676Z         at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
2023-07-12T18:41:48.8884946Z         at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
2023-07-12T18:41:48.8885120Z 
2023-07-12T18:41:48.8885229Z         Caused by:
2023-07-12T18:41:48.8885686Z         org.junit.platform.commons.JUnitException: Error executing tests for engine junit-jupiter
2023-07-12T18:41:48.8885947Z             at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:57)
2023-07-12T18:41:48.8886247Z             at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
2023-07-12T18:41:48.8886440Z             ... 31 more
2023-07-12T18:41:48.8886602Z 
2023-07-12T18:41:48.8886723Z             Caused by:
2023-07-12T18:41:48.8886869Z             java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
2023-07-12T18:41:48.8887092Z                 at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
2023-07-12T18:41:48.8887362Z                 at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
2023-07-12T18:41:48.8887582Z                 ... 32 more
2023-07-12T18:41:48.8887704Z 
2023-07-12T18:41:48.8887914Z                 Caused by:
2023-07-12T18:41:48.8888037Z                 java.lang.OutOfMemoryError
2023-07-12T18:41:48.8888202Z                     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-07-12T18:41:48.8888462Z                     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2023-07-12T18:41:48.8888753Z                     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-07-12T18:41:48.8889024Z                     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2023-07-12T18:41:48.8889252Z                     at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
2023-07-12T18:41:48.8889430Z                     ... 34 more
2023-07-12T18:41:48.8889473Z 
2023-07-12T18:41:48.8889565Z                     Caused by:
2023-07-12T18:41:48.8889696Z                     java.lang.OutOfMemoryError: Java heap space
2023-07-12T18:41:48.8889857Z                         at java.base/java.util.HashMap.newNode(HashMap.java:1815)
2023-07-12T18:41:48.8890036Z                         at java.base/java.util.HashMap.putVal(HashMap.java:638)
2023-07-12T18:41:48.8890232Z                         at java.base/java.util.HashMap.putMapEntries(HashMap.java:511)
2023-07-12T18:41:48.8890414Z                         at java.base/java.util.HashMap.<init>(HashMap.java:486)
2023-07-12T18:41:48.8890658Z                         at net.thucydides.core.environment.SystemEnvironmentVariables.copy(SystemEnvironmentVariables.java:45)
2023-07-12T18:41:48.8890956Z                         at net.thucydides.core.environment.SystemEnvironmentVariables.currentEnvironmentVariables(SystemEnvironmentVariables.java:62)
2023-07-12T18:41:48.8891279Z                         at net.serenitybdd.core.environment.ConfiguredEnvironment.getEnvironmentVariables(ConfiguredEnvironment.java:12)
2023-07-12T18:41:48.8891573Z                         at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.<init>(SmartAjaxElementLocator.java:87)
2023-07-12T18:41:48.8891870Z                         at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.<init>(SmartAjaxElementLocator.java:49)
2023-07-12T18:41:48.8892167Z                         at net.thucydides.core.annotations.locators.SmartElementLocatorFactory.createLocator(SmartElementLocatorFactory.java:21)
2023-07-12T18:41:48.8892477Z                         at net.thucydides.core.annotations.locators.SmartFieldDecorator.decorate(SmartFieldDecorator.java:53)
2023-07-12T18:41:48.8892729Z                         at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:109)
2023-07-12T18:41:48.8892973Z                         at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:101)
2023-07-12T18:41:48.8893242Z                         at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:22)
2023-07-12T18:41:48.8893551Z                         at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:20)
2023-07-12T18:41:48.8893802Z                         at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:167)
2023-07-12T18:41:48.8894036Z                         at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:171)
2023-07-12T18:41:48.8894368Z                         at net.thucydides.core.pages.PageFactory.createFromSimpleConstructor(PageFactory.java:68)
2023-07-12T18:41:48.8894627Z                         at net.thucydides.core.pages.PageFactory.createPageOfType(PageFactory.java:38)
2023-07-12T18:41:48.8894911Z                         at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:83)
2023-07-12T18:41:48.8895343Z                         at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:50)
2023-07-12T18:41:48.8895626Z                         at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:206)
2023-07-12T18:41:48.8895895Z                         at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:196)
2023-07-12T18:41:48.8896154Z                         at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:177)
2023-07-12T18:41:48.8896420Z                         at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:124)
2023-07-12T18:41:48.8896729Z                         at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
2023-07-12T18:41:48.8897067Z                         at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:89)
2023-07-12T18:41:48.8897347Z                         at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:70)
2023-07-12T18:41:48.8897631Z                         at net.thucydides.core.steps.StepAnnotations.injectNestedScenarioStepsInto(StepAnnotations.java:62)
2023-07-12T18:41:48.8897903Z                         at net.thucydides.core.steps.StepFactory.instantiateAnyNestedStepLibrariesIn(StepFactory.java:405)
2023-07-12T18:41:48.8898178Z                         at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:194)
2023-07-12T18:41:48.8898439Z                         at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:177)
2023-07-12T18:41:48.8898561Z 
2023-07-12T18:41:48.8898677Z UnknownClass.JUnit Jupiter FAILED
2023-07-12T18:41:48.8898735Z 
```

**Comment by wakaleo** [comment]
Do you get this error with version 3.9.7?

**Comment by bachhavdipak** [comment]
Yes but Its resolved after increasing heap space

**Comment by bachhavdipak** [comment]
@wakaleo : no its not fixed ,even after increasing heap space to 4GB with version 3.9.7. As I mentioned earlierfunctionality is working as expected with 3.7.1 version so not sure what changes are integrated between this two releases.

**Comment by wakaleo** [comment]
I can't reproduce it (I have a test project with 87000 tests which runs with 1m of heapspace) - can you provide a sample project to reproduce the issue, or investigate the code on your side and raise a PR?

**Comment by bachhavdipak** [comment]
I cant provide you project and its really difficult to debug code as well becuase issue is occuring while executing jobs in a parallel environment. Cant we just check above stracktrace and compare it with the latest release to fix above issue.

**Comment by wakaleo** [comment]
The latest release is a complete rewrite of the reporting engine, so that might be tricky, but you can certainly checkout different versions locally to see if you can isolate the issue.

**Comment by bachhavdipak** [comment]
If I am not wrong then its exactly same issue https://github.com/serenity-bdd/serenity-core/issues/3093. Which is somehow working with 3.7.1 release
![image](https://github.com/serenity-bdd/serenity-core/assets/77110618/4d13774b-1a07-424e-8943-a34d07782aa0)

**Comment by wakaleo** [comment]
So maybe start looking at the commits after that release. If you need someone to investigate in depth more quickly, it could be done as part of a commercial support contract.

**Comment by bachhavdipak** [comment]
Is it possible to create another relase 3.7.X with console logging enabled ?

**Comment by wakaleo** [comment]
No, but you can check out that version in git, make the changes you want, and build with mvn clean install -DskipTests

**Comment by bachhavdipak** [comment]
But I am unable to use those changes out of serenity core project until and unless its publish with the maven

**Comment by wakaleo** [comment]
The command above will deploy a snapshot version to your local maven repository.

**Comment by cliviu** [comment]
@bachhavdipak , can you provide a heap dump?

**Comment by KroneckerDeIta** [comment]
When upgrading from 3.2.4 to 4.2.22 I am getting Java heap space errors as well, but I think it is caused by something different to the people above. For me I think I have narrowed it down to memory issues with SerenityRest. When running with the profiler in Intellij at the point in the tests where I need to upload a file:

    val spec = SerenityRest.given()
    ...
    spec.multiPart("file", file)
    ...
    spec.post(url)

in 4.2.22 the memory usage is 1.93GB to upload a 31MB file! For 3.2.4 it only uses 68.68MB and if I swap SerenityRest for just RestAssured the memory usage is 16MB. 

Is it the decorators that are using so much memory?

**Comment by KroneckerDeIta** [comment]
I don't think we need a new project, I think this behaviour is very easy to replicate.

In the serenity-core test class ExperimentalWhenInstantiatingARestAssuredRequest add the following main method:

    public static void main(String[] args)
    {
      try
      {
        Thread.sleep(5000);
      }
      catch (InterruptedException e)
      {
        throw new RuntimeException(e);
      }
      RequestSpecification given = SerenityRest.given();
      File file = new File("/var/tmp/file.txt");
      given.multiPart("file", file);
      given.post("http://localhost:12345/not/a/path");
    }

Generate the file that is read using the following command (if on Ubuntu):

    fallocate -l 100M /var/tmp/file.txt

Then run with the profiler on. The memory required when calling the post method will be about 1.08GB. If the file size is increased to 500MB:

    fallocate -l 500M /var/tmp/file.txt

then memory required goes up to 4.82GB.

If SerenityRest is changed for RestAssured the memory usage for the 500MB file is 73MB.

And if I checkout the old 3.2.4 tag then the memory usage for the 500MB file is 59MB.

**Comment by wakaleo** [comment]
Can you try with version 4.2.26?

**Comment by KroneckerDeIta** [comment]
I have just copied my code to both the very latest version of the main branch and the 4.2.26 tag and I am getting the same result (the post method is using 4.82GB of memory for the 500MB file above).

**Comment by wakaleo** [comment]
> I have just copied my code to both the very latest version of the main branch and the 4.2.26 tag and I am getting the same result (the post method is using 4.82GB of memory for the 500MB file above).

Thanks for checking. The best would be to dig into the code to see what the Serenity RestAssured code is doing when it runs this code (I'm not too familiar with that part of the code base). I made a change to prevent it from storing binary payloads but that would not seem to be enough.
