### ISSUE TITLE
Bitbar integration failing on Jenkins

### ISSUE THREAD

**Issue by WorldofAzeem** [serenity-bdd/serenity-core#3194]
Hello,
We have integrated serenity with Bitbar by having serenity.config file  "src\serenity\resources"  .. 
Tests works fine perfectly connects to the birbar and executes from local machines (windows) 

Now when trying to run same test from Jenkins it throws error like below. 

runners.BrowserLaunchRunner > Simple test to launch browser with given "appUrl".To validate browser is launching and going to appUrl STANDARD_ERROR
    Jul 17, 2023 2:49:57 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
    INFO: Using OpenTelemetry for tracing

runners.BrowserLaunchRunner > Simple test to launch browser with given "appUrl".To validate browser is launching and going to appUrl FAILED
    net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.remote.RemoteWebDriver
        at app//net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:164)
        at app//net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:152)
        at app//net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:122)
        at app//net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:192)
        at app//net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:982)
        at app//net.serenitybdd.core.pages.PageObject.openUrl(PageObject.java:928)
        at app//pages.DiscoverHomePage.goToUrl(DiscoverHomePage.java:75)
        at app//pages.DiscoverHomePage.go(DiscoverHomePage.java:33)
        at app//steps.BrowserLaunchStepDefinition.goToAppUrl(BrowserLaunchStepDefinition.java:12)
        at ?.user navigates to the appUrl(file:///opt/app/workspace/esqm-org/Automation/FrameworkAndUtils/QEP_TA/Smoke%20Test/Linux-Chrome-Headless/1-ui-with-serenity/src/serenity/resources/features/browser_launch/validate_browser_launch.feature:4)

        Caused by:
        net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class org.openqa.selenium.remote.RemoteWebDriver
        WebDriver reported the following message: Could not start a new session. Response code 400. Message: com.testdroid.api.APIException 
        Host info: host: 'vclp025872.na.discoverfinancial.com', ip: '10.15.166.197'
        Build info: version: '4.8.0', revision: '267030adea'
        System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.80.1.el7.x86_64', java.version: '11.0.18'
        Driver info: org.openqa.selenium.remote.RemoteWebDriver
        Command: [null, newSession {capabilities=[**Capabilities {bitbar:options: {}, browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {bitbar:options: {}, browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}}]**

Capabilities are showing as blank even though we have data in serenity.config file.  We are not able to find what the issue is why its failing only on Jenkins environment. 

please let us know if there are any recommendations.

**Comment by WorldofAzeem** [comment]
serenity.config file  is below 
webdriver {
  driver = "remote"
  capabilities {
    platformName = "Windows"
    browserName = "firefox"
    browserVersion = "113"
    "bitbar:options" {
      osVersion = "10"
      screenResolution = "1920x1080"
    }
  }
}
bitbar {
  active = true
  apiKey = "OUR KEY"
  hub = "eu-desktop-hub"
  cloudUrl = "https://cloud.bitbar.com"
}
