### ISSUE TITLE
Selenium 4 Support for remote webdriver

### ISSUE THREAD

**Issue by toshavyas** [serenity-bdd/serenity-core#3201]
While calling remote webdriver/saucelabs if we pass selenium 4 capabilities its giving error.

Caused by: java.io.UncheckedIOException: java.net.ConnectException: connection timed out: ondemand.us-west-1.saucelabs.com/66.85.52.224:443
                  at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
                  at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
                  at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
                  at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
                  at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
 
{
  "capabilities": {
    "firstMatch": [
      {
        "acceptInsecureCerts": true,
        "browserName": "chrome",
        "browserVersion": "latest",
        "goog:chromeOptions": {
          "args": [
            "test-type",
            "ignore-certificate-errors",
            "--window-size=1000,800",
            "--no-sandbox",
            "--disable-dev-shm-usage",
            "incognito",
            "disable-infobars",
            "disable-gpu",
            "disable-default-apps",
            "disable-popup-blocking",
            "test-type",
            "ignore-certificate-errors",
            "--window-size=1000,800",
            "--no-sandbox",
            "--disable-dev-shm-usage",
            "incognito",
            "disable-infobars",
            "disable-gpu",
            "disable-default-apps",
            "disable-popup-blocking",
            "remote-allow-origins=*"
          ],
          "extensions": [
          ],
          "sauce:options": {
            "accessKey": "",
            "build": "Serenity-Saucelabs-build",
            "extendedDebugging": true,
            "maxDuration": 10800,
            "name": "Serenity-Saucelabs-Integration",
            "parent-tunnel": "",
            "tags": "Serenity-Saucelabs",
            "tunnel-identifier": "",
            "username": ""
          }
        },
        "platformName": "Windows 10"
      }
    ]
  }
}

**Comment by wakaleo** [comment]
Have you asked Saucelabs?

**Comment by toshavyas** [comment]
Yes we did and they asked to open a bug with Serenity.

**Comment by wakaleo** [comment]
I don't think it's related to the Serenity code - it looks like something to do with the way Saucelabs handles the capabilities it is sent. If you can get the equivalent code working in plain Selenium and compare the capabilities being sent that might help understand where the issue is coming from.
