### ISSUE TITLE
Upgrading serenity framework with version 3.6.23 and getting below error while launching the framework. Setup serenity.conf for chrome broswer

### ISSUE THREAD

**Issue by Kuldeepgupta72** [serenity-bdd/serenity-core#3208]
net.serenitybdd.core.exceptions.SerenityManagedException: org/openqa/selenium/AcceptedW3CCapabilityKeys
	at net.thucydides.core.steps.ErrorConvertor.convertToAssertion(ErrorConvertor.java:13)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:483)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:211)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:198)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:86)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at com.dbs.bpds.steps.LoginPage_Steps$ByteBuddy$959OYUNN.launchApplication(Unknown Source)
	at tests.AutoCashCreditTest.givenAdminUserIsAbleToLoginToApplicationSuccessfullyForAccess(AutoCashCreditTest.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:790)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:349)

**Comment by Kuldeepgupta72** [comment]
@wakaleo Please help me on this

**Comment by wakaleo** [comment]
That looks like a chromedriver issue. Make sure you use a recent version (3.9.8 or 4.0.x). 

Incidently, JBehave hasn't been supported for a while now, so there is no guarantee of compatibility with new versions.
