### ISSUE TITLE
Serenity 4.0.0-beta2 doesn't generates html report in case the test is ran locally with JUnit Cucumber Runner

### ISSUE THREAD

**Issue by vayaszsolt** [serenity-bdd/serenity-core#3232]
Hi,

After I moved to use the 4.0.0-beta2 version the html report wasn't generated after I ran a single Scenario tagged with a special name. 
I needed to add this property to the serenity.conf property in order the report to get generated:

`output.formats=html`

After I added this property I am receiving this stacktrace:

```
16:59:02.787 [pool-1-thread-1] ERROR n.t.m.r.BaseRequirementsService - Tag provider failure
net.thucydides.model.reports.ReportLoadingFailedError: Can not load reports for some reason
	at net.thucydides.model.reports.TestOutcomeLoader.loadFrom(TestOutcomeLoader.java:88)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.loadRequirements(TestOutcomeRequirementsTagProvider.java:97)
	at net.thucydides.model.domain.RequirementCache.getRequirements(RequirementCache.java:41)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.getRequirements(TestOutcomeRequirementsTagProvider.java:86)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.getFlattenedRequirements(TestOutcomeRequirementsTagProvider.java:363)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.findRequirementByTag(TestOutcomeRequirementsTagProvider.java:336)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at net.thucydides.model.domain.RequirementCache.getRequirementsByTag(RequirementCache.java:59)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.getRequirementFor(TestOutcomeRequirementsTagProvider.java:331)
	at net.thucydides.model.requirements.BaseRequirementsService.getRequirementFor(BaseRequirementsService.java:71)
	at net.thucydides.model.reports.html.ReportNameProvider.forRequirement(ReportNameProvider.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1552)
	at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:56)
	at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:51)
	at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:62)
	at freemarker.core.MethodCall._eval(MethodCall.java:62)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Assignment.accept(Assignment.java:134)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at net.thucydides.model.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:38)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:36)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:164)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:128)
	at net.thucydides.model.reports.ReportService.generateReportFor(ReportService.java:245)
	at net.thucydides.model.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IllegalArgumentException: Unsupported report format: HTML
	at net.thucydides.model.reports.TestOutcomeLoader.getOutcomeReporter(TestOutcomeLoader.java:190)
	at net.thucydides.model.reports.TestOutcomeLoader.loadFrom(TestOutcomeLoader.java:62)
	... 42 common frames omitted
16:59:02.809 [pool-1-thread-1] ERROR n.t.m.r.BaseRequirementsService - Tag provider failure
net.thucydides.model.reports.ReportLoadingFailedError: Can not load reports for some reason
	at net.thucydides.model.reports.TestOutcomeLoader.loadFrom(TestOutcomeLoader.java:88)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.loadRequirements(TestOutcomeRequirementsTagProvider.java:97)
	at net.thucydides.model.domain.RequirementCache.getRequirements(RequirementCache.java:41)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.getRequirements(TestOutcomeRequirementsTagProvider.java:86)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.getFlattenedRequirements(TestOutcomeRequirementsTagProvider.java:363)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.findRequirementByTag(TestOutcomeRequirementsTagProvider.java:336)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at net.thucydides.model.domain.RequirementCache.getRequirementsByTag(RequirementCache.java:59)
	at net.thucydides.model.requirements.TestOutcomeRequirementsTagProvider.getRequirementFor(TestOutcomeRequirementsTagProvider.java:331)
	at net.thucydides.model.requirements.BaseRequirementsService.getRequirementFor(BaseRequirementsService.java:71)
	at net.thucydides.model.reports.html.ReportNameProvider.forRequirement(ReportNameProvider.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1552)
	at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:56)
	at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:51)
	at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:62)
	at freemarker.core.MethodCall._eval(MethodCall.java:62)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Assignment.accept(Assignment.java:134)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at net.thucydides.model.reports.templates.FreemarkerReportTemplate.merge(FreemarkerReportTemplate.java:38)
	at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:36)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:164)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:128)
	at net.thucydides.model.reports.ReportService.generateReportFor(ReportService.java:245)
	at net.thucydides.model.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IllegalArgumentException: Unsupported report format: HTML
	at net.thucydides.model.reports.TestOutcomeLoader.getOutcomeReporter(TestOutcomeLoader.java:190)
	at net.thucydides.model.reports.TestOutcomeLoader.loadFrom(TestOutcomeLoader.java:62)
	... 42 common frames omitted
```

Somebody knows why is needed to specify the default output format? Also why am I receiving this error?

**Comment by vayaszsolt** [comment]
Is there any way to see the report in case a single scenario is run using a runner else than maven?

In my case I am using IntelJidea to develop new automation tests. The Cucumber JUnit runner is starting much faster compare to run a full maven lifecycle to trigger a single test to be run. Is their a way to support this scenario with a html report to be generated at the end?

**Comment by wakaleo** [comment]
Serenity generates the HTML reports from the JSON output of the test runs during the aggregate phase. You can run mvn serenity:aggregate at any stage and generate the HTML reports from the tests that have been executed.
