### ISSUE TITLE
net.serenitybdd.model.buildinfo.PropertyBasedDriverCapabilityRecord

### ISSUE THREAD

**Issue by akhabarovIT** [serenity-bdd/serenity-core#3260]
Hello!
Please help me understand why I am getting a warning. 

**Warn**:
`[pool-3-thread-1] WARN net.serenitybdd.model.buildinfo.PropertyBasedDriverCapabilityRecord - Failed to store browser configuration for {moz:debuggerAddress=true, acceptInsecureCerts=true, browserName=firefox, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, strictFileInteractability=true, moz:firefoxOptions={args=[-test-type, -ignore-certificate-errors, --window-size=1920,1080, -no-sandbox, -enable-automation, -disable-dev-shm-usage, -disable-browser-side-navigation, -disable-gpu, -disable-popup-blocking], log={level=error}, prefs={javascript.options.showInConsole=false}}}`

**Serenity version**: 4.0.4

**serenity.conf**: 
```
webdriver {
    autodownload = true
}

serenity {
    project.name = "Web Desktop Autotests"
    tag.failures = "true"
    linked.tags = "issue"
    use.unique.browser = false
    restart.browser.each.scenario = true
    take.screenshots = FOR_EACH_ACTION
    reports.show.step.details = false
    report.show.manual.tests = false
    browser.height = 1080
    browser.width = 1920
    keep.unscaled.screenshots = true
    enable_java = true
}

simplified.stack.traces = false
cucumber.publish.quiet = true

environments {
    run_with_chrome {
        chrome {
            switches = "--remote-allow-origins=*"
        }
        customproperty = chrome
        context = chrome
        webdriver {
            capabilities {
                browserName = "chrome"
                "goog:chromeOptions" {
                    args = ["test-type", "ignore-certificate-errors", "--window-size=1920,1080", "no-sandbox",
                        "enable-automation", "disable-dev-shm-usage", "disable-browser-side-navigation", "disable-gpu",
                        "headless=new", "disable-popup-blocking"
                    ]
                }
            }
        }
    }
    run_with_firefox {
        webdriver {
            capabilities {
                browserName = "firefox"

                pageLoadStrategy = "normal"
                acceptInsecureCerts = true
                unhandledPromptBehavior = "dismiss"
                strictFileInteractability = true

                "moz:firefoxOptions" {
                    args = ["-test-type", "-ignore-certificate-errors", "--window-size=1920,1080", "-no-sandbox",
                            "-enable-automation", "-disable-dev-shm-usage", "-disable-browser-side-navigation", "-disable-gpu",
                            "-disable-popup-blocking"
                        ],
                        prefs {
                            "javascript.options.showInConsole": false
                        },
                        log {
                            "level": "info"
                        },
                }
            }
        }
    }
}
```

I tried to configure serenity.conf as in the example here https://github.com/serenity-bdd/serenity-core/issues/3225#issuecomment-1684876071

**Comment by akhabarovIT** [comment]
Why my question is ignored?

**Comment by wakaleo** [comment]
There is no SLA on open source projects. If you would like to investigate this warning is logged here: https://github.com/serenity-bdd/serenity-core/blob/577a7c5f78a313c6dfb95da1d358f285ea3c455e/serenity-model/src/main/java/net/serenitybdd/model/buildinfo/PropertyBasedDriverCapabilityRecord.java#L40

**Comment by DanielFran** [comment]
Same issue, migrating from 3.8.1 to 4.0.14, using java 17:
````txt
11:45:02.235 [main] WARN  n.s.m.b.PropertyBasedDriverCapabilityRecord - Failed to store browser configuration for {goog:chromeOptions={args=[start-maximized, window-size=1920,1080, incognito, test-type, no-sandbox, headless=new, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-infobars, disable-extensions-file-access-check, disable-gpu, start-maximized, window-size=1920,1080, incognito, test-type, no-sandbox, headless=new, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-infobars, disable-extensions-file-access-check, disable-gpu, remote-allow-origins=*], extensions=[]}, acceptInsecureCerts=false, browserName=chrome}
java.io.FileNotFoundException: C:\Users\DFranco\IdeaProjects\test\target\site\serenity\browser-chrome.properties (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at net.serenitybdd.model.buildinfo.PropertyBasedDriverCapabilityRecord.registerCapabilities(PropertyBasedDriverCapabilityRecord.java:36)
	at net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider.newInstance(ChromeDriverProvider.java:68)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:164)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:142)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:178)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:169)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:120)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:209)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:982)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:880)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:868)
	at net.colt.sdwan.qa.ui.portal.stepImplemented.ImplementationOfLoginPage.openApplication(ImplementationOfLoginPage.java:17)
	at net.colt.sdwan.qa.ui.portal.stepImplemented.ImplementationOfLoginPage$ByteBuddy$FIAmf5Lx.openApplication$accessor$O0zB8rBW(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:519)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:499)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:471)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:213)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:200)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:92)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at net.colt.sdwan.qa.ui.portal.stepImplemented.ImplementationOfLoginPage$ByteBuddy$FIAmf5Lx.openApplication(Unknown Source)
	at net.colt.sdwan.qa.ui.portal.stepsdefinitions.DefinitionsOfLogin.iNavigateToColtSdWANUI(DefinitionsOfLogin.java:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:84)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:56)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.junit.platform.engine.CucumberEngineExecutionContext.lambda$runTestCase$4(CucumberEngineExecutionContext.java:112)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:137)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:137)
	at io.cucumber.junit.platform.engine.CucumberEngineExecutionContext.runTestCase(CucumberEngineExecutionContext.java:109)
	at io.cucumber.junit.platform.engine.NodeDescriptor$PickleDescriptor.execute(NodeDescriptor.java:168)
	at io.cucumber.junit.platform.engine.NodeDescriptor$PickleDescriptor.execute(NodeDescriptor.java:90)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:76)
	at org.junit.platform.suite.engine.SuiteLauncher.execute(SuiteLauncher.java:63)
	at org.junit.platform.suite.engine.SuiteTestDescriptor.execute(SuiteTestDescriptor.java:128)
	at org.junit.platform.suite.engine.SuiteTestEngine.lambda$execute$0(SuiteTestEngine.java:73)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.junit.platform.suite.engine.SuiteTestEngine.execute(SuiteTestEngine.java:73)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
11:45:02.239 [main] INFO  n.s.c.w.d.ChromeDriverProvider - Starting Chrome driver instance with capabilities:
11:45:02.240 [main] INFO  n.s.c.w.d.ChromeDriverProvider - Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [start-maximized, window-size=1920,1080, incognito, test-type, no-sandbox, headless=new, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-infobars, disable-extensions-file-acc..., disable-gpu, start-maximized, window-size=1920,1080, incognito, test-type, no-sandbox, headless=new, ignore-certificate-errors, disable-popup-blocking, disable-default-apps, disable-infobars, disable-extensions-file-acc..., disable-gpu, remote-allow-origins=*], extensions: []}}
````
