### ISSUE TITLE
java.lang.IllegalArgumentException: http://:-1/json/version could not be parsed into a proper Uri, missing host

### ISSUE THREAD

**Issue by johnago** [serenity-bdd/serenity-core#3273]
java.lang.IllegalArgumentException: http://:-1/json/version could not be parsed into a proper Uri, missing host
	at org.asynchttpclient.uri.Uri.create(Uri.java:73) ~[async-http-client-2.12.3.jar:na]
	at org.asynchttpclient.uri.Uri.create(Uri.java:62) ~[async-http-client-2.12.3.jar:na]
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:147) ~[async-http-client-2.12.3.jar:na]
	at org.asynchttpclient.Dsl.request(Dsl.java:73) ~[async-http-client-2.12.3.jar:na]
	at org.openqa.selenium.remote.http.netty.NettyMessages.toNettyRequest(NettyMessages.java:59) ~[selenium-remote-driver-4.1.4.jar:na]
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:56) ~[selenium-remote-driver-4.1.4.jar:na]
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42) ~[selenium-http-4.1.4.jar:na]
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56) ~[selenium-http-4.1.4.jar:na]
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49) ~[selenium-remote-driver-4.1.4.jar:na]
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42) ~[selenium-http-4.1.4.jar:na]
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56) ~[selenium-http-4.1.4.jar:na]
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:97) ~[selenium-remote-driver-4.1.4.jar:na]
	at org.openqa.selenium.devtools.CdpEndpointFinder.getCdpEndPoint(CdpEndpointFinder.java:54) ~[selenium-remote-driver-4.1.4.jar:na]
	at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$1(ChromiumDriver.java:120) ~[selenium-chromium-driver-4.1.4.jar:na]
	at java.base/java.util.Optional.flatMap(Optional.java:289) ~[na:na]
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:120) ~[selenium-chromium-driver-4.1.4.jar:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106) ~[selenium-chrome-driver-4.1.4.jar:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72) ~[selenium-chrome-driver-4.1.4.jar:na]
	at com.my.mynewwebsite.controller.WebDriverPool.configure(WebDriverPool.java:149) ~[classes/:na]
	at com.my.mynewwebsite.controller.WebDriverPool.get(WebDriverPool.java:208) ~[classes/:na]
	at com.my.mynewwebsite.controller.SeleniumDownloader.download(SeleniumDownloader.java:77) ~[classes/:na]
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:419) ~[webmagic-core-0.7.5.jar:na]
	at us.codecraft.webmagic.Spider.access$000(Spider.java:61) ~[webmagic-core-0.7.5.jar:na]
	at us.codecraft.webmagic.Spider$1.run(Spider.java:322) ~[webmagic-core-0.7.5.jar:na]
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74) ~[webmagic-core-0.7.5.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by johnago** [comment]
Why this happen?

**Comment by wakaleo** [comment]
Closing because insufficient information. Please complete the full defect form.
