### ISSUE TITLE
Compatibility issues with serenity 4.0.15 & appium java-client 9.0.0

### ISSUE THREAD

**Issue by DipanGarg** [serenity-bdd/serenity-core#3290]
### What happened?

I am using latest serenity version 4.0.15(at the time of writing) and  have updated Appium java-client library to 9.0.0(latest version), but i am getting following error when trying to execute any script on my mobile devices

java.lang.NoClassDefFoundError: io/appium/java_client/remote/MobileCapabilityType
	at net.thucydides.core.webdriver.appium.AppiumConfiguration.collectAppiumCapabilities(AppiumConfiguration.java:227)
	at net.thucydides.core.webdriver.appium.AppiumConfiguration.<clinit>(AppiumConfiguration.java:37)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.<init>(ElementLocatorFactorySelector.java:27)
	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.<init>(ElementLocatorFactorySelector.java:21)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.locatorFactories(SmartElementProxyCreator.java:27)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:20)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:167)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:171)
	at net.serenitybdd.core.pages.PageObject.<init>(PageObject.java:156)

**I believe it is happening because previously deprecated AndroidMobileCapabilityType interface has been removed as part of Appium java-client 9.0.0**

### What did you expect to happen?

Execution should be successful. Also Serenity should provide out of the box support to latest Java-client library(9.0.x)

### Serenity BDD version

4.0.15

### JDK version

11

### Execution environment

Android/iOS real Devices + Browserstack

### How to reproduce the bug.

Serenity-core dependency 4.0.15
Appium Java-client dependency 9.0.0

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by Moncada25** [comment]
Hello, I am having the same issue using this environment.

Mac OS Sonoma 14.0
Java 17
Gradle 7.6
serenity-gradle-plugin 4.0.15
Serenity Suite 4.0.15
Appium java-client 9.0.0

**Comment by wakaleo** [comment]
Serenity 4.0.16 is build with Appium 9.0.0

**Comment by DipanGarg** [comment]
Thanks @wakaleo. Its working now. Will close this issue.
cc: @Moncada25
