### ISSUE TITLE
Report generation failure

### ISSUE THREAD

**Issue by awallat** [serenity-bdd/serenity-core#334]
With the version 1.1.28 there's for each test an error when generating the report. So the report is empty after test execution. The versions before didn't have this problem. Here's the stack trace:

```
java.lang.RuntimeException: Report generation failure
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:59)
	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:164)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:153)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:103)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReportsFor(SerenityRunner.java:407)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReports(SerenityRunner.java:291)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:253)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
```

Seems like files could not be moved here. Is it necessary to define an output directory now? 
```
181 [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.build.directory : null
181 [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.reporting.OutputDirectory : null
182 [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - OutputDirectory : C:\Projects\selenium\ingrid-serenity-tests\target\site\serenity
```

**System:**
- Windows 10
- jUnit 4.12

**Comment by YamStranger** [comment]
@awallat Thanks for this issue. 

It seems that moving files on Windows when some process writing to it (or stream is opened) produce exceptions. (On Linux all works fine)

Will push update soon.

**Comment by YamStranger** [comment]
@awallat new release published - please try it.

**Comment by sergrosh** [comment]
Also have the same problem:
`[main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.build.directory : null
[main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.reporting.OutputDirectory : null`

**Comment by YamStranger** [comment]
@sergrosh did you try latest version of serenity core -> 1.1.29-rc.1
And if you execute 
`gradle test aggregate`  - you receive empty report?  

_________________________________

>[main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.build.directory : null [main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.reporting.OutputDirectory : null

These fields will be null only during gradle/mvn plugin executing. During test those properties will be empty.

**Comment by awallat** [comment]
With version 1.1.29-rc.1 the report generation works again under Windows. Thanks for the quick fix!
