### ISSUE TITLE
Report failes to generate when using SoftAssertions and Cucumber Examples

### ISSUE THREAD

**Issue by dpascalau** [serenity-bdd/serenity-core#3376]
### What happened?

When using Cucumber Scenario Outline with Examples and if the `io.cucumber.core.plugin.SerenityReporterParallel` plugin is set in the Cucumber Suite runner, if the SoftAssertions are used and at least 1 example fails, the Serenity report fails to generate and throws the following stacktrace:
``` java
Failed to generate report - java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/opentest4j/MultipleFailuresError
org.opentest4j.MultipleFailuresError
java.base/java.lang.ClassLoader.defineClass1(Native Method)
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/opentest4j/MultipleFailuresError
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at net.thucydides.core.reports.html.Reporter.lambda$generateReportsFor$0(Reporter.java:51)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoClassDefFoundError: org/opentest4j/MultipleFailuresError
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader.findClass(VisitableURLClassLoader.java:186)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.thucydides.model.domain.TestOutcome.testResultFromFailureClassname(TestOutcome.java:1489)
	at net.thucydides.model.domain.TestOutcome.getResult(TestOutcome.java:1477)
	at net.serenitybdd.reports.model.ScenarioSummary$Companion.ofFailingScenariosIn(ScenarioSummary.kt:30)
	at net.serenitybdd.reports.model.FrequentFailuresBuilder.withMaxOf(FrequentFailures.kt:22)
	at net.thucydides.core.reports.html.FreemarkerContext.getBuildContext(FreemarkerContext.java:176)
	at net.thucydides.core.reports.html.TagReportingTask.generateTagReport(TagReportingTask.java:75)
	at net.thucydides.core.reports.html.TagReportingTask.generateReports(TagReportingTask.java:69)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:33)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:12)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.opentest4j.MultipleFailuresError
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader.findClass(VisitableURLClassLoader.java:186)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 26 more
```

The class is available and I've even tried to force add it. 
If none of the examples fail, the report is correctly generated.
If the `io.cucumber.core.plugin.SerenityReporterParallel` Cucumber plugin is not used, the report is correctly generated.

### What did you expect to happen?

I expected the report to generate correctly and I'm able to see the failures.

### Serenity BDD version

4.0.27

### JDK version

17

### How to reproduce the bug.

Steps to reproduce:

The CucumberTestSuite runner in the Serenity Cucumber Starter repo can be used:

```java
package starter;

import org.junit.platform.suite.api.ConfigurationParameter;
import org.junit.platform.suite.api.IncludeEngines;
import org.junit.platform.suite.api.SelectClasspathResource;
import org.junit.platform.suite.api.Suite;

import static io.cucumber.junit.platform.engine.Constants.PLUGIN_PROPERTY_NAME;

@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("/features")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "io.cucumber.core.plugin.SerenityReporterParallel,pretty,timeline:build/test-results/timeline")
public class CucumberTestSuite {
}
```

Along with the following Feature file and Step Definitions:

```java
package starter.stepdefinitions;

import io.cucumber.java.en.Then;
import org.assertj.core.api.SoftAssertions;

public class ExampleStepDefinitions {

    @Then("^value of ([^\"]*) should be ([^\"]*)$")
    public void outputShouldBeInput(String output, String input) {
        SoftAssertions softly = new SoftAssertions();
        softly.assertThat(input).isEqualTo(output);
        softly.assertAll();
    }
}
```

```cucumber
Feature: random feature

  @example
  Scenario Outline: Example for failed report
    Then value of <output> should be <input>

    Examples:
      | output | input |
      | test   | test  |
      | fail   | test  |
```

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
java.lang.NoClassDefFoundError is pretty much _always_ due to dependency conflicts, so the first thing to do would be to look for a dependency conflict in your project.

**Comment by dpascalau** [comment]
Hi @wakaleo, thanks for getting back on this. I've checked for dependency conflicts and I've updated the version of AssertJ Core to `3.24.2` as it showing a version conflict, but the error still occurs. I've tried forcing the specific version of the both AssertJ and Opentest4j with no success.

**Comment by dpascalau** [comment]
We managed to fix the issue by adding the `Opentest4j` dependency to the classpath by doing this:

In `build.gradle` file under the `buildscript` section we added:
``` gradle
    dependencies {
        classpath("org.opentest4j:opentest4j:1.3.0")
    } 
```

This has fixed the issue and now the report is generated correctly. 
Leaving this here in case anyone else has the same issue.
