### ISSUE TITLE
not able to include or exclude tags while doing parallel execution using serenity

### ISSUE THREAD

**Issue by geetha051993** [serenity-bdd/serenity-core#3431]
i have tried giving @tags in testrunner class, also in serenity.properties file  and in cucmber.properties file none of these works for me.
irrespective of tags all scenarios were executing parallelly.

can anyone help me on this issue, how to run specific scenarios parallelly .

**testrunner:**
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("com.health.bdd")
@SelectClasspathResource("/features/parallel1")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.health.bdd")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "io.cucumber.core.plugin.SerenityReporterParallel,pretty,json:target/cucumber.json,"
		+ "timeline:target/test-results/timeline")
@CucumberOptions(tags = "@parw")

**cucumber.properties**

cucumber.execution.order = fixed
cucumber.plugin=pretty,json:target/cucumber.json,timeline:target/test-results/timeline
cucumber.snippet-type=camelcase
cucumber.filter.tags= @parw
cucumber.options=--tags @parw

**serenity.properties**

serenity.tag.ignore=parw

Thanks in Advance

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/docs/reporting/filtering_reports#using-tags-with-cucumber-and-junit-5

**Comment by geetha051993** [comment]
Hi @wakaleo , i have tried but still no luck
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("com.health.bdd")
@SelectClasspathResource("/features/Workflow")
//@SelectClasspathResource("/features/parallel")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.health.bdd")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "io.cucumber.core.plugin.SerenityReporterParallel,pretty,json:target/cucumber.json,"
		+ "timeline:target/test-results/timeline")
@ConfigurationParameter(key = FILTER_TAGS_PROPERTY_NAME, value = "@parallel and @parallel4")
public class CucumberTestSuite {



getting below error else it won't execute anything:

org.junit.platform.commons.JUnitException: TestEngine with ID 'cucumber' failed to execute tests
Caused by: org.junit.platform.commons.JUnitException: Error executing tests for engine cucumber
Caused by: java.lang.IllegalArgumentException: No enum constant org.junit.platform.engine.support.hierarchical.DefaultParallelExecutionConfigurationStrategy.RANDOM
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at io.cucumber.junit.platform.engine.CucumberTestEngine.createExecutorService(CucumberTestEngine.java:68)

**Comment by geetha051993** [comment]
Hi, did anyone have solution for this

Thanks in advance

**Comment by geetha051993** [comment]
@wakaleo  Thank you , it's working

**Comment by wakaleo** [comment]
That looks like a Cucumber or JUnit dependency issue of some kind.
