### ISSUE TITLE
Serenity Execute on multiple environment with gradle tool

### ISSUE THREAD

**Issue by PreethiJeevi** [serenity-bdd/serenity-core#3474]
Attached is serenity.conf and serenity.properties file.

[serenity.conf.txt](https://github.com/serenity-bdd/serenity-core/files/15421464/serenity.conf.txt)
[serenity.properties.txt](https://github.com/serenity-bdd/serenity-core/files/15421465/serenity.properties.txt)

Below error is displayed.

Step failed
net.serenitybdd.core.environment.UndefinedEnvironmentVariableException: Environment 'env' property undefined for environment '[]'
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.lambda$getProperty$7(EnvironmentSpecificConfiguration.java:141)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.serenitybdd.core.environment.EnvironmentSpecificConfiguration.getProperty(EnvironmentSpecificConfiguration.java:137)
	at com.essentracomponenet.serenity.util.PropertyHelper.getEnvironment(PropertyHelper.java:53)
	at com.essentracomponenet.serenity.config.LaHook.preProdAuthHandler(LaHook.java:606)

**Comment by wakaleo** [comment]
You are trying to refer to a variable ("env") for an environment that is not defined. Try defining all your property values in serenity.conf rather than splitting them between serenity.conf and serenity.properties.

**Comment by PreethiJeevi** [comment]
Thank you wakaleo.
