### ISSUE TITLE
WebElementFacade not getting initialized when using PageFactory @FindBy

### ISSUE THREAD

**Issue by anshuman-sdet** [serenity-bdd/serenity-core#3498]
### What happened?

I am trying to upgrade to serenity version 3.9.8 so that I can make use of parallel execution using Junit 5. The application is being launched fine which means that the getDriver() object is working fine. However, when interacting with an element, it throws below error: 
java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.isDisplayed()" because "this.element" is null
	at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:304)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:290)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:287)
	at org.openqa.selenium.support.ui.ExpectedConditions$23.apply(ExpectedConditions.java:656)
	at org.openqa.selenium.support.ui.ExpectedConditions$23.apply(ExpectedConditions.java:652)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:203)
	at net.serenitybdd.core.pages.RenderedPageObjectView.waitFor(RenderedPageObjectView.java:110)
	at net.serenitybdd.core.pages.PageObject.waitFor(PageObject.java:417)

Also tried to update to latest Serenity version 4.1.20 but the result is exactly the same. Everything works fine when using the earlier version 3.6.22.
When using getDriver().findElement, it's working perfectly fine on both 3.9.8 and 4.1.20. The issue is only when using @FindBy annotation.

### What did you expect to happen?

The WebElementFacade should not be null when using @FindBy and interactions with the elements should happen.

### Serenity BDD version

serenity-core, serenity-junit, serenity-cucumber, serenity-rest-assured, serenity-single-page-report - 3.9.8 & 4.1.20

### JDK version

17

### Execution environment

Win 11

### How to reproduce the bug.

Upgrade to latest version of Serenity 4.1.20 from 3.6.22. Have the PageFactory to find the elements using @FindBy annotation.

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by skarindra** [comment]
I encountered the same issue, the difference is just on the version, for me everything work well with version 4.1.6 and nothing works with the newer version (> 4.1.6). Seems like there's an issue with @FindBy initialization.

cc: @wakaleo

**Comment by Snailpower** [comment]
Also encountering this issue. Downgrade to 4.1.6 fixes the issue. Thanks @skarindra!

Using Java 21 here. Hopefully a fix can be made for 4.2.x

**Comment by wakaleo** [comment]
This is related to the selenium or Appium dependencies so there most likely won't be any change in Serenity to address this. I would advise consulting the release notes for Selenium and Appium and making sure you are using the latest dependencies

**Comment by wakaleo** [comment]
If you need this fix quickly the best thing would be to propose a PR or request a fix as part of a commercial support contract.

**Comment by JuanpaBoadaOkt** [comment]
I am having the same issue with `net.serenity-bdd  >  serenity-core  >  4.1.14`

**Comment by bachhavdipak** [comment]
@wakaleo : Any update on this ?

**Comment by wakaleo** [comment]
I have not seen any PRs related to this, and no one has requested it as
part of a commercial support package, so…no

*John Ferguson Smart*

Wakaleo Consulting

Mobile: +44739 883 2273

***@***.***


https://johnfergusonsmart.com/ <http://www.serenity-dojo.com/>

[image: Facebook icon]
<https://www.facebook.com/John-Ferguson-Smart-Serenity-Dojo-110131163912759/>
  [image: LinkedIn icon]
<https://uk.linkedin.com/in/john-ferguson-smart-7442907>  [image: Twitter
icon] <https://twitter.com/wakaleo>

**Comment by bachhavdipak** [comment]
@wakaleo  : Intrestingly its not failing for all elements ; also I observed we can sort out this issue if we not use @Step annotation to avoid this error for the pages where its throwing this error.

**Comment by bachhavdipak** [comment]
@wakaleo  : This seems to happen intermittently, not for all elements, and it doesn’t appear to be related to the @FindBy annotations. The issue might stem from null references being injected into the step library class, leading to this error.

Could you kindly provide more insights or suggestions on how to troubleshoot or resolve this issue?  **java.lang.NullPointerException: Cannot invoke "net.serenitybdd.core.pages.WebElementFacade.waitUntilVisible()" because "this.Button" is null** 
at net.thucydides.core.steps.BaseMethodRunner.invokeMethod(BaseMethodRunner.java:18)
	at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:18)
	at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:425)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:200)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:93)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)

**Comment by bachhavdipak** [comment]
@wakaleo  : PR has been raised for you : https://github.com/serenity-bdd/serenity-core/pull/3575

**Comment by bachhavdipak** [comment]
@wakaleo  : Can you please do needful ?

**Comment by bachhavdipak** [comment]
@General: Could someone please share a reproducible example of the above issue?

**Comment by Abhishek468** [comment]
> If you need this fix quickly the best thing would be to propose a PR or request a fix as part of a commercial support contract.

@wakaleo I don't think this is needed. I have found the issue and the fix.

**Comment by Abhishek468** [comment]
created PR @bachhavdipak @skarindra @Snailpower @wakaleo @JuanpaBoadaOkt @anshuman-sdet 
https://github.com/serenity-bdd/serenity-core/pull/3625
