### ISSUE TITLE
SerenityReporterParallel plug-in when used in conjunction with EventFiringDecorator throws net.serenitybdd.core.webdriver.UnexpectedDriverExpected: Expected a remote web driver instance but found class net.bytebuddy.renamed.java.lang.Object$ByteBuddy$FiH6ft9h

### ISSUE THREAD

**Issue by maheshdaniin** [serenity-bdd/serenity-core#3554]
### What happened?

Driver class uses EventFiringDecorator to associate BrowserListener which handles events.
Then it returns driver as 
return eventFiringWebDriver.decorate(driver);

serenity ui runner is configured as 
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("/features/ui/searching.feature")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "uk.domain.component.ui.steps,uk.domain.component.api.steps,uk.domain.hooks")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "io.cucumber.core.plugin.SerenityReporterParallel,pretty,timeline:build/test-results/timeline")
@IncludeTags({"single-ui"})
public class TestSuiteUi {

}

when executed this via mvn, 
ui test runs fine till following error stack is thrown
net.serenitybdd.core.webdriver.UnexpectedDriverExpected: Expected a remote web driver instance but found class net.bytebuddy.renamed.java.lang.Object$ByteBuddy$FiH6ft9h
	at net.serenitybdd.core.webdriver.RemoteDriver.of(RemoteDriver.java:20)
	at net.serenitybdd.core.webdriver.RemoteDriver.of(RemoteDriver.java:18)
	at net.thucydides.core.steps.events.TestFinishedEvent.saveCurrentWebDriverContext(TestFinishedEvent.java:38)
	at net.thucydides.core.steps.events.TestFinishedEvent.<init>(TestFinishedEvent.java:31)
	at io.cucumber.core.plugin.SerenityReporterParallel.handleTestCaseFinished(SerenityReporterParallel.java:367)
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
	at io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
	at io.cucumber.core.runtime.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:62)
	at io.cucumber.core.runner.TestCase.emitTestCaseFinished(TestCase.java:219)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:98)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.junit.platform.engine.CucumberEngineExecutionContext.lambda$runTestCase$4(CucumberEngineExecutionContext.java:112)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:137)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:137)
	at io.cucumber.junit.platform.engine.CucumberEngineExecutionContext.runTestCase(CucumberEngineExecutionContext.java:109)
	at io.cucumber.junit.platform.engine.NodeDescriptor$PickleDescriptor.execute(NodeDescriptor.java:168)
	at io.cucumber.junit.platform.engine.NodeDescriptor$PickleDescriptor.execute(NodeDescriptor.java:90)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:670)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:670)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

and serenity aggregate does not report this in it's report

tried running same without  io.cucumber.core.plugin.SerenityReporterParallel,
test runs fine without any exception thrown, but serenity aggregate still does not show this test result in aggregate report

then tried running with 
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "io.cucumber.core.plugin.SerenityReporter,pretty,timeline:build/test-results/timeline")
no error thrown as well as this result is reported in aggregate report

Please can you suggested why we are seeing this error? driver class is returning correct WebDriver object as test is running fine and executing full scenario till end.

it just that following lines are causing the problem :

	at net.thucydides.core.steps.events.TestFinishedEvent.saveCurrentWebDriverContext(TestFinishedEvent.java:38)
	at net.thucydides.core.steps.events.TestFinishedEvent.<init>(TestFinishedEvent.java:31)
	at io.cucumber.core.plugin.SerenityReporterParallel.handleTestCaseFinished(SerenityReporterParallel.java:367)

Also tested with serenity 4.2.3 version getting same error.

### What did you expect to happen?

with parallel plug-in used, test to run fine as well as reported in serenity aggregate report.

### Serenity BDD version

4.1.3

### JDK version

openjdk 17.0.5 2022-10-18 LTS

### Execution environment

Mac Os
Chrome Browser
All required dependencies pull by Serenity
With Junit 5.11.0
Cucumber 7.15.0

### How to reproduce the bug.

pom file to use versions mentioned above
create test ui runner class as specified in error report
create associated feature, step and actions
run mvn command that will pick up this runner class and execute feature file scenario
observe mvn log for error
also observe serenity aggregate post integration test did not show this test in report.

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment]
I can't reproduce this, can you provide a sample project.

**Comment by maheshdaniin** [comment]
@wakaleo added sample project here 
https://github.com/maheshdaniin/sample-project/tree/develop
please clone this and run 
mvn clean install -DskipCheckstyle
from function directory, you should see above error reported

**Comment by wakaleo** [comment]
> @wakaleo added sample project here https://github.com/maheshdaniin/sample-project/tree/develop please clone this and run mvn clean install -DskipCheckstyle from function directory, you should see above error reported

I can't run this project, but it looks like you are using very old library versions. Make sure you are using the latest versions of Serenity, Lombok, Mockito etc. If you need further help, we can look into a commercial support option so we can look at your project directly.

**Comment by maheshdaniin** [comment]
@wakaleo are you using develop branch of the sample-project repo?
I am using all latest version in that branch. Main branch is still at much older versions

**Comment by wakaleo** [comment]
It's because of your decorated custom driver. I've added a workaround but you may lose functionality if you don't let Serenity manage the drivers itself.

**Comment by maheshdaniin** [comment]
@wakaleo when you say you have added  a workaround? is that in sample project or is serenity version?

**Comment by wakaleo** [comment]
In the Serenity code.
