### ISSUE TITLE
Appium + Serenity: Not yet implemented is shown.

### ISSUE THREAD

**Issue by selvavaithi** [serenity-bdd/serenity-core#359]
Hi,
I am using Appium + Serenity (JAVA) when every im running a story im getting the following even though the entire story has run successfully. Can you guys look into this. My Environment is as below
Serenity-core: 1.1.29-rc.1
Serenity-jbehave: 1.8.0
Win: 8.1 pro
Eclipse: Version: Mars.2 Release (4.5.2)
Appium:Java-Client: 3.4.0
Appium version: 1.4.16.1 (Ophiuchus)

Failed to run story stories/readbucktest.story
org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4 milliseconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'SCI-DT-161', ip: '192.168.129.195', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_31'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.liquid.realbucks, app=D:/WorkSpace/MobileWorkSpace/RealBucksAutomation/src/test/resource/RealBucks.apk, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=emulator-5554, platform=LINUX, appActivity=com.liquid.realbucks.DashboardActivity, desired={appPackage=com.liquid.realbucks, appActivity=com.liquid.realbucks.DashboardActivity, app=D:/WorkSpace/MobileWorkSpace/RealBucksAutomation/src/test/resource/RealBucks.apk, platformVersion=5.1, platformName=Android, deviceName=emulator-5554}, platformVersion=6.0, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, platformName=Android}]
Session ID: b9fe890a-145f-444d-b66b-8a114ec2eb7e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:206)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandles(RemoteWebDriver.java:539)
	at net.thucydides.core.webdriver.WebDriverFacade.close(WebDriverFacade.java:275)
	at net.serenitybdd.jbehave.SerenityReporter.closeBrowsersForThisStory(SerenityReporter.java:492)
	at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:478)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:122)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:792)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:416)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:387)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by YamStranger** [comment]
Hello @selvavaithi 

Thanks for this issue, it seems that [Window handles](https://groups.google.com/forum/#!topic/appium-discuss/pEPo-NsCj5Y) are not yet implemented for Android. 

Thanks!

**Comment by YamStranger** [comment]
@selvavaithi Please add used version of appium to keep log.

**Comment by selvavaithi** [comment]
Hi @YamStranger ,
Updated, Thanks for reply :+1:

**Comment by YamStranger** [comment]
@selvavaithi please check fix of this issue in latest serenity core (1.1.29-rc.3)

Thanks!

**Comment by selvavaithi** [comment]
@YamStranger .. ok yam

**Comment by selvavaithi** [comment]
Hi @YamStranger 

Still im getting the same error. The following is the log for it

org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'SCI-DT-161', ip: '192.168.56.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_31'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.liquid.realbucks, app=D:/WorkSpace/MyAppName.apk, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=4d00af03525c80a1, platform=LINUX, appActivity=com.liquid.myappname.DashboardActivity, desired={appPackage=com.liquid.myappname, appActivity=com.liquid.myappname.DashboardActivity, app=D:/WorkSpace/MyAppName.apk, platformVersion=4.0.4, platformName=Android, deviceName=4d00af03525c80a1}, platformVersion=5.0.2, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, platformName=Android}]
Session ID: 9b0ced39-70ed-44c5-bb44-44bab4ae5556
	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:206)
	at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:521)
	at net.thucydides.core.webdriver.WebDriverFacade.close(WebDriverFacade.java:280)
	at net.serenitybdd.jbehave.SerenityReporter.closeBrowsersForThisStory(SerenityReporter.java:492)
	at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:478)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:122)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:792)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:416)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:387)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


And the following is my gradle.build file

import junit.framework.TestListener;

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'

def serenityver = "1.1.29-rc.3"
def serenityJbehaveVer = "1.8.0"
def junitver = "4.12"

repositories {
	mavenLocal()
	jcenter()
}

buildscript{

	repositories{
		mavenLocal()
		jcenter()
	}

	dependencies {
		classpath("net.serenity-bdd:serenity-gradle-plugin:1.1.29-rc.3")
	}
}

dependencies {
	compile 'org.slf4j:slf4j-api:1.7.19'
	testCompile "net.serenity-bdd:serenity-core:$serenityver"
	testCompile "net.serenity-bdd:serenity-junit:$serenityver"
	testCompile "net.serenity-bdd:serenity-jbehave:$serenityJbehaveVer"
	testCompile "junit:junit:$junitver"
	testCompile('org.assertj:assertj-core:1.7.0')
	testCompile('org.slf4j:slf4j-simple:1.7.19')
}


test {

	// show standard out and standard error of the test JVM(s) on the console
	testLogging.showStandardStreams = true

}

gradle.startParameter.continueOnFailure = true


When i used maven pom xml im getting "Missing artifact net.serenity-bdd:serenity-core:jar:1.1.29-rc.3"

**Comment by wakaleo** [comment]
Appium has been updated in the latest release (version 1.1.32-rc.2), could you see if you are having the same issue with this version?

**Comment by selvavaithi** [comment]
Hi @wakaleo 

I have updated yet getting the following error.

    Failed to run story Stories/SampleAppStories/simpleapp.story
    org.openqa.selenium.WebDriverException: Not yet implemented. Please help us:
 http://appium.io/get-involved.html (WARNING: The server did not provide any sta
cktrace information)
    Command duration or timeout: 4 milliseconds
    Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e18749
0ca824', time: '2016-03-15 10:43:46'
    System info: host: 'SCI-DT-161', ip: '192.168.56.1', os.name: 'Windows 8', o
s.arch: 'amd64', os.version: '6.2', java.version: '1.8.0-ea'
    Session ID: 98c0586b-504c-4ab6-9eeb-b2a2f44684ab
    Driver info: io.appium.java_client.android.AndroidDriver
    Capabilities [{platform=LINUX, app=D:/WorkSpace/Driver/selendroid-test-app-0
.17.0.apk, javascriptEnabled=true, appActivity=io.selendroid.testapp.HomeScreenA
ctivity, browserName=Android, networkConnectionEnabled=true, desired={app=D:/Wor
kSpace/Driver/selendroid-test-app-0.17.0.apk, deviceName=192.168.56.101:5555, pl
atformName=Android, appActivity=io.selendroid.testapp.HomeScreenActivity, appPac
kage=io.selendroid.testapp}, locationContextEnabled=false, appPackage=io.selendr
oid.testapp, platformVersion=6.0, databaseEnabled=false, platformName=Android, d
eviceName=192.168.56.101:5555, webStorageEnabled=false, warnings={}, takesScreen
shot=true}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:414)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.
java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHa
ndler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.ja
va:678)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGener
icMobileDriver.java:43)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:216)
        at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java
:521)
        at net.thucydides.core.webdriver.WebDriverFacade.close(WebDriverFacade.j
ava:280)
        at net.serenitybdd.jbehave.SerenityReporter.closeBrowsersForThisStory(Se
renityReporter.java:511)
        at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.
java:497)
        at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(Delegat
ingStoryReporter.java:49)
        at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(Concurr
entStoryReporter.java:122)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(Pe
rformableTree.java:792)
        at org.jbehave.core.embedder.PerformableTree.performCancellable(Performa
bleTree.java:416)
        at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.jav
a:387)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManage
r.java:291)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManage
r.java:265)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:724)

com.sampleapp.test.SampleAppTest > java.lang.Object.AfterStories STANDARD_OUT

**Comment by wakaleo** [comment]
That's when Serenity is calling WebDriver.close(), is there any reason that you know of that that would not be supported by Appium?

**Comment by hypery2k** [comment]
maybe it's related to #235

**Comment by wakaleo** [comment]
Could you try with 1.1.34?

**Comment by hypery2k** [comment]
can confirm that it's working with appium with 1.1.34 on iOS.

**Comment by selvavaithi** [comment]
Hi tried in windows 8 on Android and still getting that same error.

    org.openqa.selenium.WebDriverException: Not yet implemented. Please help us:
 http://appium.io/get-involved.html (WARNING: The server did not provide any sta
cktrace information)
    Command duration or timeout: 7 milliseconds
    Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e18749
0ca824', time: '2016-03-15 10:43:46'
    System info: host: 'SCI-DT-161', ip: '192.168.56.1', os.name: 'Windows 8', o
s.arch: 'amd64', os.version: '6.2', java.version: '1.8.0-ea'
    Session ID: 4cf37fe9-c832-4c6a-8f98-7999b0848a97
    Driver info: io.appium.java_client.android.AndroidDriver
    Capabilities [{platform=LINUX, app=D:/WorkSpace/Driver/selendroid-test-app-0
.17.0.apk, javascriptEnabled=true, appActivity=io.selendroid.testapp.HomeScreenA
ctivity, browserName=Android, networkConnectionEnabled=true, desired={app=D:/Wor
kSpace/Driver/selendroid-test-app-0.17.0.apk, deviceName=192.168.56.101:5555, pl
atformName=Android, appActivity=io.selendroid.testapp.HomeScreenActivity, appPac
kage=io.selendroid.testapp}, locationContextEnabled=false, appPackage=io.selendr
oid.testapp, platformVersion=6.0, databaseEnabled=false, platformName=Android, d
eviceName=192.168.56.101:5555, webStorageEnabled=false, warnings={}, takesScreen
shot=true}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:414)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.
java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHa
ndler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.ja
va:678)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGener
icMobileDriver.java:43)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:216)
        at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java
:521)
        at net.thucydides.core.webdriver.WebDriverFacade.close(WebDriverFacade.j
ava:280)
        at net.serenitybdd.jbehave.SerenityReporter.closeBrowsersForThisStory(Se
renityReporter.java:511)
        at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.
java:497)
        at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(Delegat
ingStoryReporter.java:49)
        at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(Concurr
entStoryReporter.java:122)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(Pe
rformableTree.java:792)
        at org.jbehave.core.embedder.PerformableTree.performCancellable(Performa
bleTree.java:416)
        at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.jav
a:387)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManage
r.java:291)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManage
r.java:265)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:724)

    (AfterStories)

**Comment by wakaleo** [comment]
This could be an issue with the Appium driver; I'm not seeing it here. If you can isolate the issue and provide a pull request, we'd be happy to see if we can integrate it into the code base.

**Comment by hypery2k** [comment]
tested it with android,too. It's working. But you need to install appium with ` npm install -g appium --chromedriver_version="2.16"`to get it working, see my [PR](https://github.com/serenity-bdd/serenity-documentation/pull/80/files)

**Comment by selvavaithi** [comment]
I have used Appium directly downloading it from Appium site. I'll it by installing it though npm @hypery2k ..

**Comment by selvavaithi** [comment]
Hi @wakaleo , Yeah sure let me try my best.

**Comment by gurutaku** [comment]
hi, I encounter exactly the same issue when i integrated Appium with Serenity/JBehave. Everything works except getting an error when SerenityReporter is trying to close the Appium driver (android driver to be more specific) using close(). I tried driver.quit() and it worked, but strangely driver.close() doesn't close the AndroidDriver. Please kindly help.

**Comment by hypery2k** [comment]
There should be no need to manually close the driver

**Comment by gurutaku** [comment]
driver.quit() is just something that i tried on the side without having SerenityReporter calling close() and it works. Since I'm using SerenityReportingRunner, I am kind of stuck with SerenityReporter calling close() and throwing this error...

**Comment by gurutaku** [comment]
i'm using 
        <dependency>
    		<groupId>org.jbehave</groupId>
    		<artifactId>jbehave-core</artifactId>
    		<version>4.0.5</version>
		</dependency>
        <dependency>
    		<groupId>net.serenity-bdd</groupId>
    		<artifactId>serenity-jbehave</artifactId>
    		<version>1.8.0</version>
		</dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>1.1.36</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>1.1.36</version>
        </dependency>
