### ISSUE TITLE
executeAsyncScript throwing error asynchronous script timeout

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#381]
1.1.26-rc.1

trying to do HTML5 drag and drop per example http://stackoverflow.com/questions/33849040/drag-and-drop-testing-in-selenium-on-html5-using-java?lq=1

getting below error

`
net.serenitybdd.core.exceptions.SerenityManagedException: asynchronous script timeout: result was not received in 10 seconds
  (Session info: chrome=49.0.2623.112)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.61 seconds
Build info: version: '2.50.1', revision: 'd7fc91b29de65b790abb01f3ac5f7ea2191c88a7', time: '2016-01-29 11:11:26'
System info: host: 'vikrams-mbp.guest.corp.microsoft.com', ip: '10.85.22.17', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=/var/folders/94/3dpydv3j2t7__4736h1pl0vr0000gn/T/.org.chromium.Chromium.bR4dgY}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.112, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: ef827b1b3820d1ae5e86d1dc11e4b70d
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:598)
	at net.thucydides.core.webdriver.WebDriverFacade.executeAsyncScript(WebDriverFacade.java:370)`

**Comment by wakaleo** [comment]
I'm not sure this is related to Serenity - it looks like a Selenium/WebDriver/Javascript issue. Do you get a different behaviour with raw Selenium?

**Comment by YamStranger** [comment]
@vikramvi 
Will close this issue - source of it not Serenity but Selenium. 

Thanks!
