### ISSUE TITLE
Webdriver not initializing from @BeforeStories

### ISSUE THREAD

**Issue by bvpadmanaban** [serenity-bdd/serenity-core#472]
**Scenario**: Invoke the browser and maximize it in the @BeforeStories

**Problem 1:**

serenity.version - 1.1.36
serenity.jbehave.version - 1.8.0

In this configuration, null pointer exception occurs for the above specified scenario because Webdriver not initializing by Serenity.

**Problem 2**:

serenity.version - 1.1.36
serenity.jbehave.version - 1.13.0

In this configuration, before going to browser invoking in the @BeforeStories below exception occurs

java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
    at net.thucydides.core.steps.BaseStepListener.getCurrentTestOutcome(BaseStepListener.java:240)
    at net.thucydides.core.steps.BaseStepListener.stepFailed(BaseStepListener.java:528)
    at net.thucydides.core.steps.StepEventBus.stepFailed(StepEventBus.java:314)
    at net.serenitybdd.jbehave.SerenityReporter.failed(SerenityReporter.java:749)
    at org.jbehave.core.reporters.DelegatingStoryReporter.failed(DelegatingStoryReporter.java:103)
    at org.jbehave.core.reporters.ConcurrentStoryReporter.failed(ConcurrentStoryReporter.java:272)
    at org.jbehave.core.steps.AbstractStepResult$Failed.describeTo(AbstractStepResult.java:57)
    at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:536)
    at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:515)
    at org.jbehave.core.embedder.StoryRunner.runBeforeOrAfterStorySteps(StoryRunner.java:460)
    at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:268)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

In the below configuration all working fine for me for the above specified scenario.

serenity.version - 1.1.21
serenity.jbehave.version - 1.5.0

Thanks,
Padmanaban

**Comment by YamStranger** [comment]
@bvpadmanaban please move this issue to JBehave, I will take a look on it. 

Thanks!!

**Comment by wakaleo** [comment]
Should be fixed.
