### ISSUE TITLE
Receiving javax.net.ssl.SSLHandshakeException error while running test using Thucydides Browsermob plugin

### ISSUE THREAD

**Issue by Joshli2017** [serenity-bdd/serenity-core#479]
Hi,
After adding dependency for the serenity-browsermob-plugin into framework and implementing it as described in ticket #100 , I am getting following error. The issue is it loads the page correctly but its unable to open the video on the page.

INFO 07/15 02:48:57 o.b.p.h.BrowserMobH~ - javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure when requesting https://tiles-cloudfront.cdn.mozilla.net/desktop/STAR/en-US.9db09f5ea732868fd4aabadc64932fd246a45afd.ag.json

INFO 07/15 02:48:59 o.b.p.j.h.SocketLis~ - Started SocketListener on 0.0.0.0:57267
WARN 07/15 02:48:59 o.b.p.j.h.HttpConne~ - POST https://shavar.services.mozilla.com:443/downloads?client=navclient-auto-ffox&appver=47.0.1&pver=2.2 HTTP/1.1
java.lang.NoSuchMethodError: org.eclipse.jetty.util.UrlEncoded.decodeTo(Ljava/lang/String;Lorg/eclipse/jetty/util/MultiMap;Ljava/lang/String;)V
	at org.browsermob.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:504)
	at org.browsermob.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:372)
	at org.browsermob.proxy.http.BrowserMobHttpRequest.execute(BrowserMobHttpRequest.java:157)
	at org.browsermob.proxy.BrowserMobProxyHandler.proxyPlainTextRequest(BrowserMobProxyHandler.java:270)
	at org.browsermob.proxy.selenium.SeleniumProxyHandler.handle(SeleniumProxyHandler.java:185)
	at org.browsermob.proxy.jetty.http.HttpContext.handle(HttpContext.java:1509)
	at org.browsermob.proxy.jetty.http.HttpContext.handle(HttpContext.java:1461)
	at org.browsermob.proxy.jetty.http.HttpServer.service(HttpServer.java:892)
	at org.browsermob.proxy.jetty.http.HttpConnection.service(HttpConnection.java:815)
	at org.browsermob.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:981)
	at org.browsermob.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:832)
	at org.browsermob.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:245)
	at org.browsermob.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
	at org.browsermob.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
INFO 07/15 02:48:59 o.b.p.h.BrowserMobH~ - javax.net.ssl.SSLException: Received fatal alert: unexpected_message when requesting https://search.services.mozilla.com/1/firefox/47.0.1/release/en-US/AU/default/default
 org.eclipse.jetty.util.UrlEncoded.decodeTo(Ljava/lang/String;Lorg/eclipse/jetty/util/MultiMap;Ljava/lang/String;)V
	at org.browsermob.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:504)
	at org.browsermob.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:372)
	at org.browsermob.proxy.http.BrowserMobHttpRequest.execute(BrowserMobHttpRequest.java:157)
	at org.browsermob.proxy.BrowserMobProxyHandler.proxyPlainTextRequest(BrowserMobProxyHandler.java:270)
	at org.browsermob.proxy.selenium.SeleniumProxyHandler.handle(SeleniumProxyHandler.java:185)
	at org.browsermob.proxy.jetty.http.HttpContext.handle(HttpContext.java:1509)
	at org.browsermob.proxy.jetty.http.HttpContext.handle(HttpContext.java:1461)
	at org.browsermob.proxy.jetty.http.HttpServer.service(HttpServer.java:892)
	at org.browsermob.proxy.jetty.http.HttpConnection.service(HttpConnection.java:815)
	at org.browsermob.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:981)
	at org.browsermob.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:832)
	at org.browsermob.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:245)
	at org.browsermob.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
	at org.browsermob.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)

I get same error when I run test on chrome browser.

**Comment by wakaleo** [comment]
This appears to be a BrowserMob issue rather than a Serenity issue.

**Comment by Joshli2017** [comment]
Thanks John. It was a BMP issue.
