### ISSUE TITLE
findBy isn't support CSS selectors

### ISSUE THREAD

**Issue by Invictum** [serenity-bdd/serenity-core#488]
In accordance to http://thucydides.info/docs/serenity-staging/#_writing_serenity_page_objects
findBy method of PageObject supports Xpath and CSS selector locators, but looks like it isn't true.

serenity.version - 1.1.36, serenity.jbehave.version - 1.13.0

```
findBy("//a[@class = 'js-password-forgotten']); //element find
findBy("a.js-password-forgotten"); //element not found
```
Log
```
net.serenitybdd.core.exceptions.SerenityManagedException: Unable to locate element: {"method":"xpath","selector":"a.js-password-forgotten"}
Command duration or timeout: 30.03 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'host', ip: '8.8.8.8', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.7.0_79'
*** Element info: {Using=xpath, value=a.js-password-forgotten}
Session ID: 6f602b50-1931-a44d-b704-0ca6bfe26238
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=45.0.1}]

	at net.serenitybdd.core.exceptions.SerenityManagedException.detachedCopyOf(SerenityManagedException.java:20)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:338)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
```

**Comment by wakaleo** [comment]
In this case the expression "a.js-password-forgotten" is ambiguous - it could be either CSS or Path. In these cases, an explicit selector is required.
