### ISSUE TITLE
 RuntimeException>> executing runnable net.serenitybdd.plugins.jira.JiraListener >>ConnectException: Connection timed ou

### ISSUE THREAD

**Issue by lovetemple** [serenity-bdd/serenity-core#497]
Wondering if the jira plugin actually work for cloud jira ( ondemand Jira) ?
. I have tried installing jira locally and it worked. But trying on cloud jira account with out any proxy and firewall etc..throws connection time out error. No fancy addon's etc..but just simple cloud account and integration jira fails.
 I have tried different version of below plugins with comibations of serenity core and none of them could connect to cloud jira :(

(   serenity-jira-requirements-provider :1.1.2-rc.1 & serenity-jira-plugin 1.1.2-rc.1.. )

 Updating JIRA issue: JiraSampleProject-xxx-170
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - JIRA server: Connection to JIRA instance at https://JiraSampleProject.atlassian.net/ with user AdminUser
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - Updating comments for issue JiraSampleProject-xxx-170
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - WIKI Rendering activated: true
Jul 29, 2016 3:10:40 PM com.google.common.util.concurrent.AbstractFuture executeListener
SEVERE: RuntimeException while executing runnable net.serenitybdd.plugins.jira.JiraListener$2@1a635172 with executor com.google.common.util.concurrent.MoreExecutors$DirectExecutorService@8dba1aa
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection timed out: connect
    at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:205)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:217)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:655)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:652)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:422)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:652)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:387)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:291)
    at net.serenitybdd.plugins.jira.client.JerseyJiraClient.getComments(JerseyJiraClient.java:736)
    at net.serenitybdd.plugins.jira.service.JiraIssueTracker.getCommentsFor(JiraIssueTracker.java:89)

**Comment by cliviu** [comment]
Hmm, It may have something to do with the proxy/firewall ?

**Comment by lovetemple** [comment]
HMM NO FIREWALL , NO PROXY SIMPLE CONFIG ON A LOCAL PC WITH ADMIN RIGHTS AND STRAIGHT CONNECTION TO NET. 
So the jira-plugin takes care of refresh token and oauth set up and adding the application link on jira and other activities?  Because you need to activate the application link of incoming calls to jira cloud and hope the jira plugin is taking care of it.?

**Comment by cliviu** [comment]
hi, 
Yes, cloud jira is supported as well. 
There is no **oauth** support in jira plugin. All you need is the user/password. 
jira.username=jirauser
jira.password=t0psecret
I'm really not sure why do you get the TimeoutException. It may be some network configuration issue.
Do you really have a project named **JiraSampleProject** in your JIRA environment ?
