### ISSUE TITLE
FF 48.0 + 1.1.37-rc.7 issue : net.thucydides.core.webdriver.UnsupportedDriverException

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#502]
FF 48.0 + 1.1.37-rc.7 throwing below error.

net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:146)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:133)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:103)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:178)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:173)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:831)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:741)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:729)

Question ??

Where to see version of FF supported by current version of Serenity ?

Thanks,
Vikram

**Comment by wakaleo** [comment]
These issues are usually related to incompatibilities between Selenium and Firefox. The latest version of Serenity uses Selenium 2.53.1, which is the latest 2.x version. As of Firefox 48.0, you need to have the Marionette driver (see http://www.theautomatedtester.co.uk/blog/2016/selenium-webdriver-and-firefox-47.html).

**Comment by vikramvi** [comment]
Thanks for clarification.

**Comment by rrussell39** [comment]
@wakaleo Is there any ETA on a serenity version that will include Selenium 3.x?  I guess we cannot at this point test >=Firefox 48  using Serenity since I see that the latest release candidate 1.2.1-rc.6 still uses Selenium 2.53.1?  We use Sauce Labs for our testing VM farm so I'm not sure if/how they use the Marionette driver.  Something to go investigate.

**Comment by wakaleo** [comment]
It depends on when the geckodriver is finished - it is not yet feature complete, and fails the Serenity smoke tests, so I don't believe it is ready for prime time yet.

**Comment by rrussell39** [comment]
@wakaleo Ok thanks for the quick reply!

**Comment by wakaleo** [comment]
Once the geckodriver is feature-complete, we will switch it over. Note that this has other implications as well (i.e. no longer supporting Java 7) which need to be considered.
