### ISSUE TITLE
x.isDisplayed fails after x.isPresent passes

### ISSUE THREAD

**Issue by Martin-Spamer** [serenity-bdd/serenity-core#503]
Given a page containing the following
`<input type="hidden" id="storyEditorCoreContentPublishDatePicker" value="" data-reactid="75">`

And the following fragment of ActualPageObject .
```
	@FindBy(id="publishDate")
	private WebElementFacade publishDate ;
...
	Assert.assertNotNull(this.publishDate); // 1) Passes : WebElement is initialised
	Assert.assertTrue(this.publishDate.isPresent()); // 2) Passes : WebElement exists
	Assert.assertTrue(this.publishDate.isDisplayed()); // 3) Fails : Element not available
```

**Expected Behaviour**
The the call to element.isDisplayed, passes because the element exists, as proven by preceeding assertion at 2  but is hidden therefore return should return false at step 3.

**Actual Behaviour**
The element exists and is initialised by the ActualPageObject. at 1
The isPresent passes with expected return of true, at 2
element.isDisplayed throws an exception of Element not found, at 3

**Comment by hazmeister** [comment]
Hidden inputs typically should not be displayed on screen and the element has a different ID. Did you copy the correct element?

**Comment by wakaleo** [comment]
What version of Serenity are you using? Could you post the stack trace?

**Comment by Martin-Spamer** [comment]
The ID miss-match is a red herring, it was me simplifying/sanitising the FindBy but failing to do the same to the page fragment.  They are the equal and correct in the real code.

I consider this to be unexpected behaviour because **isDisplayed** fails with an exception, while in ubiquitous language semantics and reenforced from the boolean return implies the purpose is flow control based on visibility and should therefore return false not throw an Assertion Exception.

The full call stack, (with minor redact to hide my client.)

org.openqa.selenium.ElementNotVisibleException: Timed out after 2 seconds. Element not available
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-27-generic', java.version: '1.8.0_101'
Driver info: driver.version: unknown
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.ajaxFindElement(SmartAjaxElementLocator.java:142)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.findElement(SmartAjaxElementLocator.java:93)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.getElement(WebElementFacadeImpl.java:144)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.isDisplayed(WebElementFacadeImpl.java:1064)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.thucydides.core.annotations.locators.AbstractSingleItemHandler.invoke(AbstractSingleItemHandler.java:45)
	at com.sun.proxy.$Proxy16.isDisplayed(Unknown Source)
	at com.(sanitised).automation.cms.common.article.StoryEditorPage.bug(StoryEditorPage.java:556)
	at com.(sanitised).automation.cms.CMSSmokeTestAT.serenityBugTest(CMSSmokeTestAT.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:430)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:52)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:241)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by wakaleo** [comment]
What version of Serenity are you using?

**Comment by Martin-Spamer** [comment]
Full version above 1.1.36, will try it with the 37rc version and post follow up in a few mins.

**Comment by wakaleo** [comment]
The `isPresent()` will return true if the element is present but not visible. `isDisplayed()` respects the semantics of the WebDriver function, so will fail if the method is present but not visible. And indeed, `isVisible()` simply returns true if the element is present and visible, and false otherwise.
