### ISSUE TITLE
Serenity is not able to generate the reports.

### ISSUE THREAD

**Issue by mandardjoshi** [serenity-bdd/serenity-core#522]
@wakaleo 
After running the tests in maven serenity getting an exception below for reports and execution stopped.

Exception in thread "pool-1-thread-3" net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@4444b7
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:183)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:23)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unsupported image type
	at net.thucydides.core.images.SimpleImageInfo.processStream(SimpleImageInfo.java:63)
	at net.thucydides.core.images.SimpleImageInfo.<init>(SimpleImageInfo.java:44)
	at net.thucydides.core.images.ResizableImage.<init>(ResizableImage.java:33)
	at net.thucydides.core.images.ResizableImage.loadFrom(ResizableImage.java:37)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.maxHeightOf(HtmlAcceptanceTestReporter.java:233)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.maxScreenshotHeightIn(HtmlAcceptanceTestReporter.java:226)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.expandScreenshots(HtmlAcceptanceTestReporter.java:193)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:178)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:88)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:181)

**Comment by wakaleo** [comment]
What version of Serenity are you using?

**Comment by mandardjoshi** [comment]
@wakaleo I am using Serenity 1.1.3

**Comment by wakaleo** [comment]
Could you try with the latest version (1.1.37)?

**Comment by mandardjoshi** [comment]
@wakaleo Tried with the latest jar version of serenity and it is working fine now.Thanks and closing the Issue.
