### ISSUE TITLE
Failed to generate report for whilst running mvn clean verify for serenity-screenplay  [mvn archetype:generate -Dfilter=serenity]

### ISSUE THREAD

**Issue by sudheerpujar** [serenity-bdd/serenity-core#549]
Hi 
I created a maven app using command `mvn archetype:generate -Dfilter=serenity`
with options 
`4: remote -> net.serenity-bdd:serenity-junit-screenplay-archetype (Serenity automated acceptance testing project using Screenplay, Selenium 2 and JUnit)`
and
`5: 1.1.38`

After successful  creation of maven project, I ran the following command
`mvn clean verify` 

The tests passed with following error to fail to generate the report,

net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:181)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:162)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:111)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReportsFor(SerenityRunner.java:396)
	at net.serenitybdd.junit.runners.SerenityRunner.generateReports(SerenityRunner.java:284)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:249)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@6050462a
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:222)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:34)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:156)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replaceAll(String.java:2223)
	at net.thucydides.core.requirements.classpath.NarrativeText.definedIn(NarrativeText.java:16)
	at net.thucydides.core.requirements.classpath.NonLeafRequirementsAdder.to(NonLeafRequirementsAdder.java:61)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.addRequirementsDefinedIn(PackageRequirementsTagProvider.java:199)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementsReadFromClasspath(PackageRequirementsTagProvider.java:113)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.fetchRequirements(PackageRequirementsTagProvider.java:91)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirements(PackageRequirementsTagProvider.java:83)
	at net.thucydides.core.requirements.MultiSourceRequirementsService.getRequirements(MultiSourceRequirementsService.java:45)
	at net.thucydides.core.requirements.BaseRequirementsService.getRequirementTypes(BaseRequirementsService.java:195)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:130)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:96)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:220)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:34)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:156)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Results :

Tests in error: 
  JUnit4Provider.invoke:128->executeTestSet:153->executeWithRerun:173->execute:283 » ReportGenerationFailed

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.

**Comment by sudheerpujar** [comment]
Same issue is there for archetype option 
`3: remote -> net.serenity-bdd:serenity-junit-archetype (Serenity automated acceptance testing project using Selenium 2 and JUnit)`
and
`5: 1.1.38`

**Comment by wakaleo** [comment]
What version of Firefox are you using?

**Comment by sudheerpujar** [comment]
40.0 @ office
might be higher @ home.

**Comment by sudheerpujar** [comment]
47.0.1 @ home

**Comment by wakaleo** [comment]
This will be fixed in the next release

**Comment by sudheerpujar** [comment]
Thanks John

**Comment by sudheerpujar** [comment]
Hi John, 
Thanks for resolving this issue. 
Its working fine with version 1.1.42
```
<dependency>
    <groupId>net.serenity-bdd</groupId>
    <artifactId>serenity-core</artifactId>
    <version>1.1.42</version>
</dependency>

```
