### ISSUE TITLE
IllegalArgumentException after upgrade to 1.1.41

### ISSUE THREAD

**Issue by nickm12345** [serenity-bdd/serenity-core#555]
Hi,

I upgrade from 1.1.37rc-6 to 1.1.41 today and I'm seeing the following Error in my output for each test.   Additionally the tests are taking much longer to run including tests marked with the @Ignore annotation which also have the same error.

Thanks for any help,

[main] INFO net.serenitybdd.core.Serenity - 
        __    _____ _____ ____ _____   ____   _    ____  ____  _____ ____  
  _     \ \  |_   _| ____/ ___|_   _| |  _ \ / \  / ___|/ ___|| ____|  _ \ 
 (_)_____| |   | | |  _| \___ \ | |   | |_) / _ \ \___ \\___ \|  _| | | | |
  _|_____| |   | | | |___ ___) || |   |  __/ ___ \ ___) |___) | |___| |_| |
 (_)     | |   |_| |_____|____/ |_|   |_| /_/   \_\____/|____/|_____|____/ 
        /_/                                                                

TEST PASSED: Acceptance Criteria 3 - Start date/time can not be updated to a date/time less than today and current time. 
----------------------------------------------------------------------------
[main] ERROR net.thucydides.core.model.TestOutcome - Tag provider net.thucydides.core.requirements.PackageRequirementsTagProvider@5f5effb0 failure
java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replaceAll(String.java:2210)
	at net.thucydides.core.requirements.classpath.NarrativeText.definedIn(NarrativeText.java:16)
	at net.thucydides.core.requirements.classpath.NonLeafRequirementsAdder.to(NonLeafRequirementsAdder.java:61)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.addRequirementsDefinedIn(PackageRequirementsTagProvider.java:208)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementsReadFromClasspath(PackageRequirementsTagProvider.java:122)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.fetchRequirements(PackageRequirementsTagProvider.java:100)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirements(PackageRequirementsTagProvider.java:92)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getRequirementFor(PackageRequirementsTagProvider.java:229)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getTagsFor(PackageRequirementsTagProvider.java:249)
	at net.thucydides.core.model.TestOutcome.getTagsUsingTagProviders(TestOutcome.java:1492)
	at net.thucydides.core.model.TestOutcome.getTags(TestOutcome.java:1473)
	at net.thucydides.core.model.TestOutcome.addTags(TestOutcome.java:1522)
	at net.thucydides.core.steps.BaseStepListener.testFinished(BaseStepListener.java:371)
	at net.thucydides.core.steps.StepEventBus.testFinished(StepEventBus.java:247)
	at net.thucydides.junit.listeners.JUnitStepListener.testFinished(JUnitStepListener.java:92)
	at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
	at org.junit.internal.runners.model.EachTestNotifier.fireTestFinished(EachTestNotifier.java:38)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:331)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:427)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:52)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:241)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

**Comment by nbarrett** [comment]
Yes, I got that on windows as well. I have a fix for this on my machine and I'll create a PR for it tomorrow....

**Comment by wakaleo** [comment]
This has been fixed in the current code base, it should be available in the next release

**Comment by wakaleo** [comment]
Fixed in 1.1.42
