### ISSUE TITLE
Serenity & JBehave: HTML report does not have test results when story file has 2 same scenarios

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#569]
**PRECONDITIONS**
**Serenity**: 1.1.42
**Serenity-JBehave**: 1.1.3

**SUMMARY**
When JBehave story file contains 2 or more scenarios with same title, Serenity HTML report may not contain results at all - following error logged:

```
(AfterStories)
Generating reports view to 'd:\Work\projects\serenity_sample\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 2 stories (of which 0 pending) containing 6 scenarios (of which 0 pending)
Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.56 sec <<< FAILURE! - in com.foobar.jbehave.AcceptanceTests
com.foobar.jbehave.AcceptanceTests  Time elapsed: 1.056 sec  <<< ERROR!
java.lang.RuntimeException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:181)
        at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:162)
        at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:111)
        at net.serenitybdd.jbehave.SerenityReporter.generateReports(SerenityReporter.java:525)
        at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:502)
        at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
        at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:122)
        at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:435)
        at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:130)
        at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)
        at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:86)
        at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
        at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)
        at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:175)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.xml.XMLTestOutcomeReporter@22ef9844
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:222)
        at net.thucydides.core.reports.ReportService.access$100(ReportService.java:34)
        at net.thucydides.core.reports.ReportService$1.run(ReportService.java:156)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.AccessDeniedException: target\site\serenity\a1ab0d7ada04f2ffb359f4234721331f.xml11971ace-998f-400c-9e5b-97b47054990a -> target\site\serenity\a1ab0d7ada04f2ffb359f4234721331f.xml
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
        at java.nio.file.Files.move(Files.java:1395)
        at net.thucydides.core.reports.xml.XMLTestOutcomeReporter.generateReportFor(XMLTestOutcomeReporter.java:98)
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:220)
        at net.thucydides.core.reports.ReportService.access$100(ReportService.java:34)
        at net.thucydides.core.reports.ReportService$1.run(ReportService.java:156)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


Results :

Tests in error:
  JUnit4Provider.invoke:128->executeTestSet:153->executeWithRerun:173->execute:283 ? Runtime
```

Generated HTML report is empty (although all tests have been run):
![empty_serenity_report](https://cloud.githubusercontent.com/assets/6312221/19346483/35df73e8-914c-11e6-84fe-e6fa4413e3b9.png)

I have set up a simple maven-based project that can help to reproduce this issue: 
[serenity_sample.zip](https://github.com/serenity-bdd/serenity-core/files/526890/serenity_sample.zip)
(You need to unzip it and run `mvn clean verify`). You may need to run tests a few times until issue reproduced. Also please note that archive already contains `target` folder with reproduced failure - you can investigate it on your own as well.
_N.B. In case when issue not reproduced and report generated - only 1 scenario among all same-named is appeared in HTML report, I think this can be reason for another bug._
_N.B. 2 This issue also reproduced on previous Serenity versions_

**Comment by cliviu** [comment]
Hi @scormaq,  the java.nio.file.AccessDeniedException looks strange . I will take a look at your issue, thanks !

**Comment by jyotimittal01** [comment]
I am getting the exactly same error. @scormaq - Please let me know if you were able to find a solution. Thanks!

**Comment by wakaleo** [comment]
Are you running on Windows?

**Comment by jyotimittal01** [comment]
yes, Windows 8.1.

**Comment by jyotimittal01** [comment]
I got the issue resolved by adding a unique identifier(S1, S2, etc) to each scenario in the story file-
Example-
Scenario: S1
Given the user on the site
When I view the utility navigation
Then I will be able to access the  site 

Scenario: S2
Given the user on the  site
When I view the utility navigation
Then the menu item that corresponds with my current section is displayed in the active state

**Comment by wakaleo** [comment]
So you had two scenarios in the same story file, both with the same name?

**Comment by scormaq** [comment]
Hi @wakaleo ,
> So you had two scenarios in the same story file, both with the same name?
Yes, the issue is reproduced when same story file has 2 scenarios with same name. Attached archive in the 1st post has project sample.
> I got the issue resolved by adding a unique identifier(S1, S2, etc) to each scenario in the story file
I ended up with same solution :) In my project I have a convention to set unique id in each scenario title, so it was a simple solution to rename repeated titles within story file to like next ones: `Scenario: 123 setup` and `Scenario: 123 tear down` along with regular 'Scenario: 123 test foobar business feature'

**Comment by weichou1229** [comment]
yes , i got the same problem on win10,
when one story have same name scenarios .
but i think that are
* userstory has wrong format .
* sometime happen access denied ,otherwise it will not generate report right  

this is one , 
```
使用登入功能來驗證權限

Narrative:
  (In order to) 為了可以獲得操作系統的權限
  (As a)        作為一個系統使用者
  (I want to )  我想要能夠使用登入功能來驗證權限

Meta:
@issue #30, #58
@wip                       <====================== wrong tag
Scenario: 未登入,被導向登入頁
Given 我是一個系統管理員,帳號密碼是'admin'和'123'
When 還未登入就開啟首頁
Then 我應該會看到登入按鈕
```
[error_log.txt](https://github.com/serenity-bdd/serenity-core/files/571842/error_log.txt)
  
------------------
another one  
```
!--Scenario: 填新增信息                 <=================   wrong comment format
!--Given 新增报销项目的编号和名称是'<number>'和'<projectName>'
!--When 点击"取消"按钮
!--Then 并关闭弹窗

Examples:
|number  |projectName|result|
|test001 |test001Name|新增数据成功|
|""|test002Name|新增失败|
```

[erroe_log2.txt](https://github.com/serenity-bdd/serenity-core/files/571852/erroe_log2.txt)

**Comment by wakaleo** [comment]
Serenity will allow scenarios with the same name in _different_ stories in 1.2.2-x.
