### ISSUE TITLE
Getting Error SerenityManagedException when using Rest Assured 

### ISSUE THREAD

**Issue by Hendrione** [serenity-bdd/serenity-core#593]
#Hi I am getting Error when try to using rest assured on serenity : 

Here is my code : 

`expect().that().statusCode(200)
            .and().body("success",equalTo("true"))
            .when()
            .delete("www.example.com?param1={param1}&param2={param2}&param3={param3}&param4={param4}&param5={param5}&cartId={cartid}&requestParams={params}",
    "10001","123","web","123","123",cartid,"{}");`

I am always getting error everytime when I try using rest Assured. here is the printstracktrace :  

```
`When the user delete pending cart using cart API with cart id 'hendri.antomy@test.com' (FAILED)
(net.serenitybdd.core.exceptions.SerenityManagedException: net.serenitybdd.core.rest.RestQuery.withRequestCookies(Ljava/lang/String;)Lnet/serenitybdd/core/rest/RestQuery;)

net.serenitybdd.core.exceptions.SerenityManagedException: net.serenitybdd.core.rest.RestQuery.withRequestCookies(Ljava/lang/String;)Lnet/serenitybdd/core/rest/RestQuery;
at net.thucydides.core.steps.ErrorConvertor.convertToAssertion(ErrorConvertor.java:23)
at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:318)
at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:130)
at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:57)
at com.gdn.steps.serenity.EndUserStepsHomePage$$EnhancerByCGLIB$$5bf229bb.deletePendingCartAPI(<generated>)
at com.gdn.steps.HomePageSteps.theUserDeletePendingCartUsingCartAPIWithCartId(HomePageSteps.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:566)
at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:546)
at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:510)
at org.jbehave.core.embedder.StoryRunner.runStepsWithLifecycle(StoryRunner.java:476)
at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:336)
at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:239)
at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:182)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:233)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)`
```

I am using rest-assured version 1.1.39 and serenity-jbehave-archetype version 1.1.19

**Comment by wakaleo** [comment]
Could you provide a sample project that reproduces this issue?

**Comment by Hendrione** [comment]
@wakaleo , now it is working. I just change the version on serenity-core and serenity-jbehave-version.
