### ISSUE TITLE
Serenity With JIRA Integration fails with Error: JIRA query failed: error 500

### ISSUE THREAD

**Issue by Gurunathan5029** [serenity-bdd/serenity-core#605]
Hi Cliviu,
I am configuring my features to the new JIRA Project which has the Project name as "XXX QA Automation" and Key as "QAAUTO".

It was previously working fine with my local JIRA. 

Serenity Test fails at the end on JIRA process , please see the below error message.
TEST PASSED: Report Generation With Inputs
----------------------------------------------------------------------------
[main] INFO net.serenitybdd.plugins.jira.JiraListener - Updating JIRA issue: TMW QA Automation-QAAUTO-13
[main] INFO net.serenitybdd.plugins.jira.JiraListener - JIRA server: Connection to JIRA instance at http://corp-jira.tmwsystems.com:8080/secure/Dashboard.jspa with user ggunaseelan
[main] INFO net.serenitybdd.plugins.jira.JiraListener - Updating comments for issue TMW QA Automation-QAAUTO-13
[main] INFO net.serenitybdd.plugins.jira.JiraListener - WIKI Rendering activated: true
Nov 22, 2016 2:33:00 AM com.google.common.util.concurrent.AbstractFuture executeListener
SEVERE: RuntimeException while executing runnable net.serenitybdd.plugins.jira.JiraListener$2@3f3c8b60 with executor com.google.common.util.concurrent.MoreExecutors$DirectExecutorService@16bbaab3
net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 500
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.checkValid(JerseyJiraClient.java:552)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.getComments(JerseyJiraClient.java:737)
	at net.serenitybdd.plugins.jira.service.JiraIssueTracker.getCommentsFor(JiraIssueTracker.java:89)
	at net.serenitybdd.plugins.jira.JiraListener.newOrUpdatedCommentFor(JiraListener.java:229)
	at net.serenitybdd.plugins.jira.JiraListener.updateIssue(JiraListener.java:202)
	at net.serenitybdd.plugins.jira.JiraListener.access$300(JiraListener.java:39)
	at net.serenitybdd.plugins.jira.JiraListener$2.run(JiraListener.java:170)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:595)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:96)
	at net.serenitybdd.plugins.jira.JiraListener.updateIssueStatus(JiraListener.java:166)
	at net.serenitybdd.plugins.jira.JiraListener.testSuiteFinished(JiraListener.java:150)
	at net.thucydides.core.steps.StepEventBus.testSuiteFinished(StepEventBus.java:507)
	at net.serenitybdd.cucumber.SerenityReporter.assureTestSuiteFinished(SerenityReporter.java:537)
	at net.serenitybdd.cucumber.SerenityReporter.done(SerenityReporter.java:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy21.done(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.done(JUnitReporter.java:208)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:99)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

[pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - Updating JIRA issue: TMW QA Automation-QAAUTO-13
[pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - JIRA server: Connection to JIRA instance at http://corp-jira.tmwsystems.com:8080/secure/Dashboard.jspa with user ggunaseelan
[pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - Updating comments for issue TMW QA Automation-QAAUTO-13
[pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - WIKI Rendering activated: true
Nov 22, 2016 2:33:00 AM com.google.common.util.concurrent.AbstractFuture executeListener
SEVERE: RuntimeException while executing runnable net.serenitybdd.plugins.jira.JiraListener$2@2a3c186c with executor com.google.common.util.concurrent.MoreExecutors$DirectExecutorService@1c8008cc
net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 500
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.checkValid(JerseyJiraClient.java:552)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.getComments(JerseyJiraClient.java:737)
	at net.serenitybdd.plugins.jira.service.JiraIssueTracker.getCommentsFor(JiraIssueTracker.java:89)
	at net.serenitybdd.plugins.jira.JiraListener.newOrUpdatedCommentFor(JiraListener.java:229)
	at net.serenitybdd.plugins.jira.JiraListener.updateIssue(JiraListener.java:202)
	at net.serenitybdd.plugins.jira.JiraListener.access$300(JiraListener.java:39)
	at net.serenitybdd.plugins.jira.JiraListener$2.run(JiraListener.java:170)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:613)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**POM File :** 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>net.serenity-bdd.demos</groupId>
	<artifactId>cucumber-webtests</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>AMS Automation</name>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>1.1.42</serenity.version>
		<serenity.cucumber.version>1.1.9</serenity.cucumber.version>
		<serenity.maven.version>1.1.7</serenity.maven.version>
		<webdriver.driver>chrome</webdriver.driver>
	</properties>
	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>http://jcenter.bintray.com</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray-plugins</name>
			<url>http://jcenter.bintray.com</url>
		</pluginRepository>
	</pluginRepositories>
	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.cucumber.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.7</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>1.7.0</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jira-plugin</artifactId>
			<version>1.1.2-rc.1</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>1.8.6</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jira-requirements-provider</artifactId>
			<version>1.1.3-rc.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.12</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.9</version>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.directory.studio</groupId>
			<artifactId>org.dom4j.dom4j</artifactId>
			<version>1.6.1</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
		<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18</version>
		 <configuration>
          <parallel>methods</parallel>
          <threadCount>10</threadCount>
        </configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.18</version>
				<configuration>
					<includes>
						<include>**/cucumber/junit/**/*.java</include>
						<include>**/cucumber/*.java</include>
					</includes>
					<reuseForks>true</reuseForks>
					
					<argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
					<systemPropertyVariables>
						<webdriver.driver>chrome</webdriver.driver>
						<maven.test.ignore.failure>true</maven.test.ignore.failure>
						<thucydides.estimated.tests.per.requirement>2</thucydides.estimated.tests.per.requirement>
					</systemPropertyVariables>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-jira-requirements-provider</artifactId>
						<version>1.1.3-rc.1</version>
					</dependency>
				</dependencies>
			</plugin>			
		</plugins>
	</build>
</project>

**Cucumber Feature file:** 
@UniqueBrowser 
@issue:QAAUTO-13 
Feature: Smoke Test 

Scenario: Login 
	Given I Login to Application 
		|Username|Password|
		|adminXXt|XXdmin   |

**Serenity Properties:**
webdriver.driver = chrome
webdriver.chrome.driver = C:\\chromedriver.exe
serenity.project.name = TMW QA Automation
serenity.use.unique.browser = false
serenity.browser,height = 1200
serenity.browser,width = 1200
serenity.dry.run=false
serenity.test.root=net.thucydides.showcase.cucumber.junit
jira.url=http://corp-jira.tmwsystems.com:8080/secure/Dashboard.jspa
jira.project=TMW QA Automation
serenity.project.key=QAAUTO
jira.username=ggunaseelan
jira.password=sample
serenity.public.url =http://localhost:8080/job/JCS-AMS/HTML_Report/
serenity.jira.workflow.active=true
serenity.jira.workflow=jira-workflow.groovy
serenity.release.types=milestone, release, version
webdriver.timeouts.implicitlywait = 10000
serenity.take.screenshots=AFTER_EACH_STEP

**Please help me in configuring my project with this new JIRA**

**Comment by wakaleo** [comment]
As this appears to be an issue with the JIRA plugin, could you raise the same issue on https://github.com/serenity-bdd/serenity-jira?

**Comment by Gurunathan5029** [comment]
I have created a new issue #59. 

When I have tried with the shortened URL :
 jira.url=http://corp-jira.tmwsystems.com:8080/

I am getting following error ,
TEST PASSED: Report Generation With Inputs
----------------------------------------------------------------------------
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - Updating JIRA issue: TMW QA Automation-QAAUTO-13
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - JIRA server: Connection to JIRA instance at http://corp-jira.tmwsystems.com:8080/ with user ggunaseelan
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - Updating comments for issue TMW QA Automation-QAAUTO-13
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - WIKI Rendering activated: true
Nov 22, 2016 3:00:49 AM com.google.common.util.concurrent.AbstractFuture executeListener
SEVERE: RuntimeException while executing runnable net.serenitybdd.plugins.jira.JiraListener$2@12570b13 with executor com.google.common.util.concurrent.MoreExecutors$DirectExecutorService@12c7fc98
net.serenitybdd.plugins.jira.client.JIRAConfigurationError: Service not found (404) - try checking the JIRA URL?
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.handleConfigurationError(JerseyJiraClient.java:562)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.checkValid(JerseyJiraClient.java:549)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.getComments(JerseyJiraClient.java:737)
	at net.serenitybdd.plugins.jira.service.JiraIssueTracker.getCommentsFor(JiraIssueTracker.java:89)
	at net.serenitybdd.plugins.jira.JiraListener.newOrUpdatedCommentFor(JiraListener.java:229)
	at net.serenitybdd.plugins.jira.JiraListener.updateIssue(JiraListener.java:202)
	at net.serenitybdd.plugins.jira.JiraListener.access$300(JiraListener.java:39)
	at net.serenitybdd.plugins.jira.JiraListener$2.run(JiraListener.java:170)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:613)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - Updating JIRA issue: TMW QA Automation-QAAUTO-13
[pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - JIRA server: Connection to JIRA instance at http://corp-jira.tmwsystems.com:8080/ with user ggunaseelan
[pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - Updating comments for issue TMW QA Automation-QAAUTO-13
[pool-1-thread-3] INFO net.serenitybdd.plugins.jira.JiraListener - WIKI Rendering activated: true
Nov 22, 2016 3:00:50 AM com.google.common.util.concurrent.AbstractFuture executeListener
SEVERE: RuntimeException while executing runnable net.serenitybdd.plugins.jira.JiraListener$2@1ada6d87 with executor com.google.common.util.concurrent.MoreExecutors$DirectExecutorService@594a1f67
net.serenitybdd.plugins.jira.client.JIRAConfigurationError: Service not found (404) - try checking the JIRA URL?
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.handleConfigurationError(JerseyJiraClient.java:562)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.checkValid(JerseyJiraClient.java:549)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.getComments(JerseyJiraClient.java:737)
	at net.serenitybdd.plugins.jira.service.JiraIssueTracker.getCommentsFor(JiraIssueTracker.java:89)
	at net.serenitybdd.plugins.jira.JiraListener.newOrUpdatedCommentFor(JiraListener.java:229)
	at net.serenitybdd.plugins.jira.JiraListener.updateIssue(JiraListener.java:202)
	at net.serenitybdd.plugins.jira.JiraListener.access$300(JiraListener.java:39)
	at net.serenitybdd.plugins.jira.JiraListener$2.run(JiraListener.java:170)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:613)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

My Project in JIRA:
![capture](https://cloud.githubusercontent.com/assets/19922204/20515742/22bf6b56-b0b9-11e6-8a3c-31f759726d48.PNG)

**Comment by wakaleo** [comment]
Thanks. See https://github.com/serenity-bdd/serenity-jira/issues/59.
