### ISSUE TITLE
net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - NOTE: I couldn't convert scaled screenshot for *.png 

### ISSUE THREAD

**Issue by huanleapp** [serenity-bdd/serenity-core#632]
Hi
I am using  serenity BDD test
Test case is passed. but there are exception throwed:
```
[pool-1-thread-4] INFO net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - NOTE: I couldn't convert scaled screenshot for 560ced5b9421c1cad0de4d59a300b5bf.png: target\site\serenity\560ced5b9421c1cad0de4d59a300b5bf.png -> target\site\serenity\scaled_560ced5b9421c1cad0de4d59a300b5bf.png: The process cannot access the file because it is being used by another process.

java.nio.file.FileSystemException: target\site\serenity\560ced5b9421c1cad0de4d59a300b5bf.png -> target\site\serenity\scaled_560ced5b9421c1cad0de4d59a300b5bf.png: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:205)
	at sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:278)
	at java.nio.file.Files.copy(Files.java:1274)
	at net.thucydides.core.images.ResizableImage.saveTo(ResizableImage.java:144)
	at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.resizedImage(ScreenshotFormatter.java:65)
	at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight(ScreenshotFormatter.java:47)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:223)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:208)
	at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
	at ch.lambdaj.Lambda.convert(Lambda.java:986)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.expandScreenshots(HtmlAcceptanceTestReporter.java:202)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:188)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:99)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:221)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:35)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Please help

**Comment by wakaleo** [comment]
This usually means that the screenshot file was locked by another process (such as an antivirus). If the tests are running successfully the message can be safely ignored.
