### ISSUE TITLE
Aggregate report problems after upgrade to 1.2.1-rc.7

### ISSUE THREAD

**Issue by tbbstny** [serenity-bdd/serenity-core#634]
I updated from serenity cucumber 1.1.10 to 1.1.14, and serenity-core from 1.1.40 to 1.2.1-rc.7 in order to get the benefit of Serenity better handling features and tests tagged with @ignore or @ignored.  There are some really big side effects to the upgrade:

- My features are organized like as serenity.requirement.types=theme, epic, feature.  After the upgrade, no epics are being reported in the "Epics" tab in the aggregate report unless the feature file name and the internal feature description text are the same.  
- Perhaps related to the epic issue, but for all epics that do not get reported, the associated features do not show under the "Features" tab in the aggregate report.  The features DO show on home page of the report in the "Tests" grid.
- My epic folders have multiple feature files in them.  As the feature files are process, if a feature is encountered that includes an @pending tag (was at the feature level in my specific case), all features that are process after that point are reported as also PENDING.

**Comment by wakaleo** [comment]
Could you try with 1.2.2-rc.2 and provide a sample project reproducing the issues?

**Comment by tbbstny** [comment]
I've updated to 1.2.2-rc.2 and updated my test app here: https://github.com/tbbstny/SerenityCucumberStudy

Can run these maven commands to generate reports against either version for comparison:
mvn clean install -PSerenity 
mvn clean install -PSerenity1.1.40

zPending Theme has the issue with Subsequent features being marked as PENDING when they should not be.

Otherwise, clicking between reports and comparing the differences between the Theme, Epic and Feature tabs in each report you'll see several issues:
- Something changed with Epics and/or Features that have dashes in their names
- Features that have a file name and a Feature: name inside the file that don't match have been dropped from the report

Also, a long standing issue, but if you know how I can get tabs to show in hierarchical order (Themes, Epics, Features) instead of Epics, Themes, Features order, I'd appreciate that too.

Thanks!

**Comment by tbbstny** [comment]
Refined project and updated README to detail these issue:
https://github.com/tbbstny/SerenityCucumberStudy

**Comment by wakaleo** [comment]
Thanks for the sample project. Could you try with 1.2.2-rc.5?

**Comment by wakaleo** [comment]
Fixed in 1.2.2-rc.5

**Comment by tbbstny** [comment]
Thanks for looking into this, and my apologies for the delay - I was out last week.  I've tried with 1.2.2-rc.5 and am now getting the following error with the aggregate plugin - so not getting a report at all.  Don't know if it matters, but was configured to use 1.1.14 for serenity-cucumber, so I tried 1.1.18 just to see if the latest of that would help, but get error in both cases.

`[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.2.2-rc.5:aggregate (serenity-reports) on project SerenityStudy: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.2.2-rc.5:aggregate failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.2.2-rc.5:aggregate (serenity-reports) on project SerenityStudy: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.2.2-rc.5:aggregate failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.2.2-rc.5:aggregate failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:166)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:237)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:177)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
`

**Comment by wakaleo** [comment]
Please try with 1.1.2-rc.6 and 1.1.20

**Comment by tbbstny** [comment]
With 1.2.2-rc.6 and 1.1.20, every issue reported, including the bonus of having the theme, epic and features shown in hierarchical order, are all working as expected.  Thanks!
