### ISSUE TITLE
Detailed report for steps not generated

### ISSUE THREAD

**Issue by ziyueyinsha** [serenity-bdd/serenity-core#647]
I use serenity + cucumber as my automation framework. The test can be ran success, however, there is no detailed step info in test report. The target html link in test can not be found when I click on the test scenario name.

I have set 'serenity.reports.show.step.details=true' in serenity.properties file. Can someone help on this?

<img width="775" alt="screen shot 2017-01-06 at 8 12 13 pm" src="https://cloud.githubusercontent.com/assets/24954940/21713414/07cbbd78-d44e-11e6-8f75-d04711452e08.png">
<img width="1233" alt="screen shot 2017-01-06 at 8 12 53 pm" src="https://cloud.githubusercontent.com/assets/24954940/21713421/0ec9de70-d44e-11e6-8891-3eba84603fd9.png">
<img width="1413" alt="screen shot 2017-01-06 at 8 21 26 pm" src="https://cloud.githubusercontent.com/assets/24954940/21713424/1588c604-d44e-11e6-8680-eb97892d92b4.png">

**Comment by wakaleo** [comment]
Could you specify what version you are using, and if possible provide a sample project that illustrates the problem?

**Comment by wakaleo** [comment]
This is usually due to a version conflict in the Serenity dependencies. The latest versions (currently) are:
  serenity-core: 1.1.23-rc.3
  serenity-maven-plugin: 1.1.23-rc.3
  serenity-cucumber: 1.1.23

I will close this issue now due to inactivity - if you have the problem again, with these versions, please reopen it.

**Comment by ychaudhari** [comment]
For information to anyone who lands on this page in google search:
I was getting same issue and an exception in serenity (after 10-Apr-2018 when 1.9.6 was released)

**My POM had following versions:**
serenity-core: 1.9.4 (when 1.9.6 was released on 10-Apr-2018)
serenity-maven-plugin: 1.9.4 
serenity-cucumber: 1.9.4 

**Issue was resolved when I updated to latest versions:**
serenity-core: 1.9.6 (released on 10-Apr)
serenity-maven-plugin: 1.9.4 (1.9.6 is not yet released as of 11-Apr. Not sure if it is expected soon)
serenity-cucumber: 1.9.4 (1.9.6 is not yet released as of 11-Apr. Not sure if it is expected soon)


Some more information: 
Exception I got was:
`runner.RunTestsjava.time.DateTimeException: Field DayOfYear cannot be printed as the value 101 exceeds the maximum print
 width of 2
        at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2548)
        at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
        at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
        at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
        at net.thucydides.core.reports.junit.JUnitXMLConverter.lambda$buildTestSuiteElement$0(JUnitXMLConverter.java:197
)
        at java.util.Optional.ifPresent(Optional.java:159)
        at net.thucydides.core.reports.junit.JUnitXMLConverter.buildTestSuiteElement(JUnitXMLConverter.java:196)
        at net.thucydides.core.reports.junit.JUnitXMLConverter.write(JUnitXMLConverter.java:36)
        at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.lambda$generateReportsFor$0(JUnitXMLOutcomeReporter
.java:49)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:41)
        at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:202)
        at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:187)
        at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:135)
        at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:857)
        at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:298)
        at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:117)
        at cucumber.runner.EventBus.send(EventBus.java:28)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO] Running CFE-999)`
