### ISSUE TITLE
Test mechanismjava.lang.NullPointerException: No BaseStepListener has been registered

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#651]
Trying to run test methods in parallel on 2 registered devices through selenium grid with below command

mvn clean verify -Dappium.hub=http://127.0.0.1:4444/wd/hub -Dwebdriver.driver=appium -Dappium.platformName=Android -Dappium.app=Flipkart.3.0.apk -Dappium.deviceName=dummy

Test methods are run only on single device and below error log in seen on terminal

`Test mechanismjava.lang.NullPointerException: No BaseStepListener has been registered
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:108)
	at net.thucydides.core.steps.StepEventBus.exceptionExpected(StepEventBus.java:638)
	at net.thucydides.junit.listeners.JUnitStepListener.updateResultsForExpectedException(JUnitStepListener.java:106)
	at net.thucydides.junit.listeners.JUnitStepListener.updateResultsUsingTestAnnotations(JUnitStepListener.java:101)
	at net.thucydides.junit.listeners.JUnitStepListener.testFinished(JUnitStepListener.java:91)
	at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
	at org.junit.internal.runners.model.EachTestNotifier.fireTestFinished(EachTestNotifier.java:38)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:331)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:433)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:53)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Test mechanismjava.lang.NullPointerException: No BaseStepListener has been registered
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at net.thucydides.core.steps.StepEventBus.getBaseStepListener(StepEventBus.java:108)
	at net.thucydides.core.steps.StepEventBus.exceptionExpected(StepEventBus.java:638)
	at net.thucydides.junit.listeners.JUnitStepListener.updateResultsForExpectedException(JUnitStepListener.java:106)
	at net.thucydides.junit.listeners.JUnitStepListener.updateResultsUsingTestAnnotations(JUnitStepListener.java:101)
	at net.thucydides.junit.listeners.JUnitStepListener.testFinished(JUnitStepListener.java:91)
	at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
	at org.junit.internal.runners.model.EachTestNotifier.fireTestFinished(EachTestNotifier.java:38)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:331)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:433)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:53)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by wakaleo** [comment]
What version are you using?

**Comment by vikramvi** [comment]
1.2.2

**Comment by cliviu** [comment]
Hi @vikrami ! I was not able to reproduce your problem.  Can you please post your pom.xml ?

**Comment by vikramvi** [comment]
@cliviu please find below

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>serenity-appium-mobile-native-app-automation</groupId>
    <artifactId>serenity-appium-mobile-native-app-automation</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Test project with Serenity and Appium to perform UI tests on native mobile app</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.2.2</serenity.version>   
        <serenity.cucumber.version>1.1.13</serenity.cucumber.version>   
    </properties>

    <repositories>
      <repository>
	        <snapshots>
	        	<enabled>false</enabled>
	        </snapshots>
	        <id>central</id>
	        <name>bintray</name>
	        <url>http://jcenter.bintray.com</url>
      </repository>
    </repositories>
    <pluginRepositories>
      <pluginRepository>
	        <snapshots>
	        	<enabled>false</enabled>
	        </snapshots>
	        <id>central</id>
	        <name>bintray-plugins</name>
	        <url>http://jcenter.bintray.com</url>
      </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
        </dependency>			
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
           <groupId>com.github.cukedoctor</groupId>
           <artifactId>Cukedoctor-converter</artifactId>
           <version>1.0.6</version>
        </dependency>
        <dependency>
		    <groupId>com.googlecode.json-simple</groupId>
		    <artifactId>json-simple</artifactId>
		    <version>1.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
        
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
	                    
	                    <skip>true</skip>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                   <includes>
                        <include>FlipkartAppTest.java</include>
                    </includes>
                    
                     <parallel>all</parallel>
                    <threadCount>2</threadCount>
                    <reuseForks>true</reuseForks>

                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            
            
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
	        
	       <plugin>
				    <groupId>com.github.cukedoctor</groupId>
				    <artifactId>cukedoctor-maven-plugin</artifactId>
				    <version>1.0.6</version>
				    <configuration>
				         <featuresDir>target/cucumber_json</featuresDir>
				        <outputFileName>index</outputFileName>
				        <outputDir></outputDir> 
				        
				        <format>all</format>
				        <hideSummarySection>true</hideSummarySection>
				        <hideScenarioKeyword>true</hideScenarioKeyword>
				        <hideStepTime>true</hideStepTime>
				        <hideFeaturesSection>true</hideFeaturesSection>
				        <hideTags>true</hideTags>
				        <sourceHighlighter>coderay</sourceHighlighter>
				        <toc>center</toc>
				        <numbered>true</numbered>
				        
				    </configuration>
				    <executions>
				        <execution>
				            <goals>
				                <goal>execute</goal>
				            </goals>
				            <phase>verify</phase>
				        </execution>
				    </executions>
           </plugin>
        </plugins>
    </build>
</project>

`

**Comment by cliviu** [comment]
Hi @vikrami . I was able to reproduce your issue. The problem occurs when running the test methods in parallel.

**Comment by cliviu** [comment]
Hi @vikrami. Try please in your pom.xml to set `<parallel>classes</parallel>` instead of <parallel>all</parallel>, let me know if the NPE still comes. Thanks !

**Comment by vikramvi** [comment]
@cliviu sorry for late response, with the change your proposed NPE is no more but test cases are not running in parallel on multiple androids connected.

You can have a look at sample project which I'm still working on, it starts & stops appium server, registers all the available devices with selenium hub and kick off automation 

https://github.com/vikramvi/AppiumSerenityPOC/tree/serenity_grid_appium

1. In  public void SetupSeleniumGridAndAppiumNodesTest() , I put debug point till stopAllServers();

2. Afterwards run command from terminal

`mvn clean verify -Dappium.hub=http://127.0.0.1:4444/wd/hub -Dwebdriver.driver=appium -Dappium.platformName=Android -Dappium.app=FULL_PATH/serenityAppiumFlipkart/com.flipkart.android.apk -Dappium.deviceName=dummy`

**Comment by cliviu** [comment]
Hi @vikrami. Sure, I will take a look at your project

**Comment by vikramvi** [comment]
Thanks @cliviu . please let me know in case any further debugging / info needed from my side.

**Comment by vikramvi** [comment]
@cliviu can you please share your pom.xml for running test cases in parallel on multiple mobile devices ? 

I would like to try with latest version of selenium and check if issue still exists.

**Comment by cliviu** [comment]
I'm wondering how is this supposed to work when we specify -Dappium.deviceName=dummy .. How can it possibly run on multiple devices ?

**Comment by vikramvi** [comment]
Yes; it is working properly as I'm running on grid setup where 3 android devices are connected.
I struggled a lot initially and somehow figured I need to just pass some random string for appium.deviceName.

But current issue I'm facing parallel runs on 3 devices are not consistently passing each time. I'm still playing around to configure maven-failsafe-plugin.

If you also have mobile grid setup , can you please share pom.xml ?

**Comment by vikramvi** [comment]
@cliviu I tried parallel run on 3 devices with below configuration

`					<forkCount>10</forkCount>
        			<reuseForks>true</reuseForks>
        			<argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>`

This doesn't run in parallel but in sequence.

Does your setup runs test cases in parallel ?

**Comment by vikramvi** [comment]
@wakaleo can you please clarify how to get parallel methods execution working, I'm struggling to get this working. I could get parallel classes but not parallel methods.

Not sure if this is bug with maven surefire and maven failsafe plugins ?

**Comment by cliviu** [comment]
Hi @vikrami, As I said before,  serenity does support only test class level parallelism.

**Comment by vikramvi** [comment]
@cliviu sorry I didn't understand that point earlier now it's clear.

Can you please clarify below doubt 

1.   I have 5 test classes each having random number of test methods

2.  In case if I set `<parallel>classes</parallel>` , how the parallel execution takes place ?

**Comment by vikramvi** [comment]
@cliviu can you please have a look at https://github.com/vikramvi/AppiumSerenityPOC/commit/8bf126f3152874ee71bea4660715a6bbe92d8854

I've multiple test classes and each one having multiple test methods.

In this case each of the test methods is not running on single device instead sending instructions to multiple devices which is resulting in random failures.

I've 3 android devices connected to selenium grid and want to run test cases in parallel on these

Is this bug in framework or wrong configuration in pom.xml ?

**Comment by vikramvi** [comment]
Closing issue as didn't receive any support here.
