### ISSUE TITLE
serenity-core 1.2.2: Use of "@UseTestDataFrom" results in "IllegalArgumentException"

### ISSUE THREAD

**Issue by mngi-arogers** [serenity-bdd/serenity-core#655]
Starting with Serenity core v1.2.2, when a test uses the `SerenityParameterizedRunner` with the `@UseTestDataFrom` annotation, the test results in the following stacktrace:
```
java.lang.IllegalArgumentException: The display name must not be empty.
	at org.junit.runner.Description.<init>(Description.java:156)
	at org.junit.runner.Description.<init>(Description.java:151)
	at org.junit.runner.Description.createSuiteDescription(Description.java:45)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:349)
	at org.junit.runners.Suite.describeChild(Suite.java:123)
	at org.junit.runners.Suite.describeChild(Suite.java:27)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:352)
	at org.eclipse.jdt.internal.junit4.runner.SubForestFilter.apply(SubForestFilter.java:41)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:37)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createFilteredTest(JUnit4TestLoader.java:77)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:68)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Serenity core 1.1.42 does not have this behavior.

I've checked the instructions here: http://serenity-bdd.info/docs/serenity/#_data_driven_tests but didn't see anything I missed.

I will attach a sample project.

**Comment by mngi-arogers** [comment]
Here's a sample GitHub project complete with instructions to run it:
https://github.com/mngi-arogers/serenity-troubleshooting/tree/655

Let me know if you'd prefer a zip file to be attached to this issue.

Thank you for your time.
