### ISSUE TITLE
Generating report is crashing for large test suite

### ISSUE THREAD

**Issue by RStrizhak** [serenity-bdd/serenity-core#675]
Hi,

we updated to new Serenity versions:
**serenity-core - 1.2.2
serenity-jbehave - 1.21.0**

sometimes during the report generation we get following Exception:
**java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode**
```
mvn -f pom.xml -Dserenity.requirement.types=capabilities, features, sub-features" serenity:aggregate -s settings.xml

11:23:39 [INFO] Scanning for projects...
11:23:41 [INFO]                                                                         
11:23:41 [INFO] ------------------------------------------------------------------------
11:23:41 [INFO] Building Test Framework 1.0-SNAPSHOT
11:23:41 [INFO] ------------------------------------------------------------------------
11:23:42 [INFO] 
11:23:42 [INFO] --- serenity-maven-plugin:1.2.2:aggregate (default-cli) @ test-framework ---
11:23:48 [INFO] webdriver.driver=chrome
11:23:48 [INFO] serenity.timeout=10
11:23:48 [INFO] jira.url=https://jira.qwerty.com
11:23:48 [INFO] serenity.test.root=com.qwerty.qwe
11:23:48 [INFO] serenity.project.name=our project
11:23:48 [INFO] webdriver.wait.for.timeout=30000
11:23:48 [INFO] serenity.maintain.session=true
11:23:48 [INFO] webdriver.timeouts.implicitlywait=5000
11:23:48 [INFO] serenity.take.screenshots=FOR_FAILURES
11:23:48 [INFO] current_project.base.dir: /app/jenkins/workspace/08.3_generate_report
11:23:48 Generating HTML Story Reports from /app/jenkins/workspace/08.3_generate_report/target/site/serenity
11:23:48 Generating HTML Story Reports to /app/jenkins/workspace/08.3_generate_report/target/site/serenity
11:23:48 Generating HTML Outcome Reports: false
11:23:50 [INFO] Generating test results for 3706 tests
11:24:28 [INFO] 595 requirements loaded after 38683 ms
11:24:28 [INFO] 595 related requirements found after 38684 ms
11:24:32 [INFO] Generating test outcome reports: false
11:24:48 [INFO] Starting generating reports: 58723 ms
12:34:33 [ERROR] Report generation failed
12:34:33 java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
12:34:33 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
12:34:33 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
12:34:33 	at net.thucydides.core.reports.html.Reporter.generateReportsFor(Reporter.java:33)
12:34:33 	at net.thucydides.core.reports.html.ReportGenerator.generateReportsFor(ReportGenerator.java:27)
12:34:33 	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:195)
12:34:33 	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
12:34:33 	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:239)
12:34:33 	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:177)
12:34:33 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
12:34:33 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
12:34:33 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
12:34:33 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
12:34:33 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
12:34:33 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
12:34:33 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
12:34:33 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
12:34:33 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
12:34:33 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
12:34:33 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
12:34:33 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
12:34:33 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
12:34:33 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
12:34:33 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:34:33 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:34:33 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:34:33 	at java.lang.reflect.Method.invoke(Method.java:497)
12:34:33 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
12:34:33 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
12:34:33 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
12:34:33 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
12:34:33 Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
12:34:33 	at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1819)
12:34:33 	at java.util.HashMap$TreeNode.treeify(HashMap.java:1936)
12:34:33 	at java.util.HashMap.treeifyBin(HashMap.java:771)
12:34:33 	at java.util.HashMap.putVal(HashMap.java:643)
12:34:33 	at java.util.HashMap.put(HashMap.java:611)
12:34:33 	at net.thucydides.core.requirements.BaseRequirementsService.indexChildRequirements(BaseRequirementsService.java:124)
12:34:33 	at net.thucydides.core.requirements.BaseRequirementsService.indexChildRequirements(BaseRequirementsService.java:125)
12:34:33 	at net.thucydides.core.requirements.BaseRequirementsService.indexRequirements(BaseRequirementsService.java:115)
12:34:33 	at net.thucydides.core.requirements.MultiSourceRequirementsService.getRequirements(MultiSourceRequirementsService.java:49)
12:34:33 	at net.thucydides.core.requirements.BaseRequirementsService.getRequirementTypes(BaseRequirementsService.java:195)
12:34:33 	at net.thucydides.core.reports.html.FreemarkerContext.getBuildContext(FreemarkerContext.java:64)
12:34:33 	at net.thucydides.core.reports.html.ResultReportingTask.generateReports(ResultReportingTask.java:46)
12:34:33 	at net.thucydides.core.reports.html.Reporter$ReportExecutor.call(Reporter.java:52)
12:34:33 	at net.thucydides.core.reports.html.Reporter$ReportExecutor.call(Reporter.java:42)
12:34:33 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:34:33 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
12:34:33 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
12:34:33 	at java.lang.Thread.run(Thread.java:745)
```
successful case with the same test outcome:
```
mvn -f pom.xml "-Dserenity.requirement.types=capabilities, features, sub-features" serenity:aggregate -s settings.xml

13:11:57 [INFO] Scanning for projects...
13:11:57 [INFO]                                                                         
13:11:57 [INFO] ------------------------------------------------------------------------
13:11:57 [INFO] Building FPOS Test Framework 1.0-SNAPSHOT
13:11:57 [INFO] ------------------------------------------------------------------------
13:12:03 [INFO] 
13:12:03 [INFO] --- serenity-maven-plugin:1.2.2:aggregate (default-cli) @ fpos-test-framework ---
13:12:05 [INFO] webdriver.driver=chrome
13:12:05 [INFO] serenity.timeout=10
13:12:05 [INFO] jira.url=https://qwerty.qwety.com
13:12:05 [INFO] serenity.test.root=com.qweert.qwe
13:12:05 [INFO] serenity.project.name=our project
13:12:05 [INFO] webdriver.wait.for.timeout=30000
13:12:05 [INFO] serenity.maintain.session=true
13:12:05 [INFO] webdriver.timeouts.implicitlywait=5000
13:12:05 [INFO] serenity.take.screenshots=FOR_FAILURES
13:12:05 [INFO] current_project.base.dir: /app/jenkins/workspace/08.3_generate_report
13:12:05 Generating HTML Story Reports from /app/jenkins/workspace/08.3_generate_report/target/site/serenity
13:12:05 Generating HTML Story Reports to /app/jenkins/workspace/08.3_generate_report/target/site/serenity
13:12:05 Generating HTML Outcome Reports: false
13:12:07 [INFO] Generating test results for 3706 tests
13:12:41 [INFO] 595 requirements loaded after 33496 ms
13:12:41 [INFO] 595 related requirements found after 33496 ms
13:12:43 [INFO] Generating test outcome reports: false
13:12:58 [INFO] Starting generating reports: 51335 ms
15:30:39 [INFO] Finished generating test results for 3706 tests after 8311818 ms
15:30:39 GENERATE CUSTOM REPORTS
15:30:39 [INFO] ------------------------------------------------------------------------
15:30:39 [INFO] BUILD SUCCESS
15:30:39 [INFO] ------------------------------------------------------------------------
```

Issue in not reproduced using:
**serenity-core - 1.1.42
serenity-jbehave - 1.13.0**

Please check this, thanks!

**Comment by RStrizhak** [comment]
BTW, Reports generation time is greatly increased at the latest Serenity versions :(

**Comment by wakaleo** [comment]
Nothing obvious comes to mind, would you be able to send me a zipped-up version of your target/site/serenity directory?

**Comment by RStrizhak** [comment]
Hi John, sorry for the late answer.

Unfortunately, I cannot provide test results of our project and exactly **this issue with error isn't reproduced again** on our test runners.

**We have other not permanent issues with report generation:**
**1)** GENERATING HTML REPORT file is hanging for defined scenario after test running (but Generating JSON report for scenario was successful):
```
14:08:55 [INFO] GENERATING HTML REPORT FOR 37 story file name:05.01.37.01 - scenario description in 2ea139210554765e99021148468dbebd.html in directory target/site/serenity  
14:38:55 Build timed out (after 30 minutes). Marking the build as aborted.
```
> When we added parameter **report.max.threads=1** to *serenity.properties* file - issue is not reproduced more.

**2)** Generating report is hanging after capabilities.html was created in the end of report generation:
```
23:03:58 [DEBUG] Generated report capabilities.html in 185375 ms
23:03:58 [DEBUG] Requirements report capabilities.html generated in 185377 ms
23:59:02 $ /usr/bin/vncserver -kill :61
23:59:02 Build was aborted
```
> Looks that you fixed it here -> https://github.com/serenity-bdd/serenity-core/commit/f3ba174f7f3561ac61ab1e5d0368966fde30953a#diff-4cc55af13efa59c5fb690db6f1c991e6

**3)** Our regression report with 2400 tests still is generated during the 80 minutes, it's excruciating pain (:
```
05:28:23 [INFO] Generating test results for 2443 tests
......
06:47:47 [INFO] Finished generating test results for 2443 tests after 4763905 ms (~80 minutes)
```
> We could not find a solution how to fix it :(

So we are waiting for new Serenity releases and hope these issues will be fixed.
Thank you :)

**Comment by wakaleo** [comment]
Hi Roman,

Without seeing the actual tests and test reports, it will be very difficult to figure out what is going on just from the log file. Most users are reporting a significant _reduction_ in the time it takes to generate the reports, so there may be some project or environment-specific issue at play in this case. I would be happy to discuss some ad-hoc remote support, so that I could see what your code is doing directly (see http://johnfergusonsmart.com/serenity-bdd-mentoring/) if you need to find a solution quickly.

**Comment by nzvonilov** [comment]
Hi John

I have same problem.

**Comment by wakaleo** [comment]
Hi Nicolay,

Could you get me a sample copy of your test project? The tests themselves can be empty, but I would need to see the package structure and configuration.

**Comment by nzvonilov** [comment]
Ok, 
I will send the project in the coming days

**Comment by nzvonilov** [comment]
Ок, I will send you the project in the near future

**Comment by sacredvor** [comment]
Hi John
I also faced with the same issue.

**Comment by nzvonilov** [comment]
This is target/site [target.zip](https://github.com/serenity-bdd/serenity-core/files/806793/target.zip)

**Comment by downhomeboy20** [comment]
I have an issue with report not genrating also. Does anyone have any ideals

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building 990TAPIAutomation 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://dl.bintray.com/serenity/maven/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
[WARNING] Could not transfer metadata org.seleniumhq.selenium:selenium-java/maven-metadata.xml from/to serenity (http://dl.bintray.com/serenity/maven): connect timed out
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ 990TAutomation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ 990TAutomation ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ 990TAutomation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ 990TAutomation ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ 990TAutomation ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ 990TAutomation ---
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18.1:integration-test (default) @ 990TAutomation ---
[INFO] 
[INFO] --- serenity-maven-plugin:2.0.39:aggregate (serenity-reports) @ 990TAutomation ---
[WARNING] Failure to transfer org.seleniumhq.selenium:selenium-java/maven-metadata.xml from http://dl.bintray.com/serenity/maven was cached in the local repository, resolution will not be reattempted until the update interval of serenity has elapsed or updates are forced. Original error: Could not transfer metadata org.seleniumhq.selenium:selenium-java/maven-metadata.xml from/to serenity (http://dl.bintray.com/serenity/maven): connect timed out
[INFO] current_project.base.dir: C:\Users\a442046\eclipse-workspace\990TAutomation
[INFO] Generating test results for 0 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.FileSystemRequirementsTagProvider@7b4b8199, net.thucydides.core.requirements.PackageRequirementsTagProvider@38a38ed4]
[INFO] 0 requirements loaded after 35 ms
[INFO] 0 related requirements found after 35 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 82 ms
[INFO] Configured report threads: 20
[WARNING] Failed to generate report for Test Summary Report - java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
net.thucydides.core.reports.html.FreemarkerContext.addFormattersToContext(FreemarkerContext.java:167)
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.thucydides.core.reports.html.Reporter.generateReports(Reporter.java:53)
	at net.thucydides.core.reports.html.Reporter.generateReportsFor(Reporter.java:29)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:211)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:243)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:186)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
	at net.thucydides.core.reports.html.FreemarkerContext.addFormattersToContext(FreemarkerContext.java:167)
	at net.thucydides.core.reports.html.FreemarkerContext.getBuildContext(FreemarkerContext.java:95)
	at net.thucydides.core.reports.html.TextSummaryReportTask.generateReports(TextSummaryReportTask.java:31)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:32)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.vladsch.flexmark.util.options.DataHolder
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 9 more
[WARNING] Failed to generate report for net.thucydides.core.reports.html.AggregateReportingTask@11cadb32 - java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
net.thucydides.core.reports.html.FreemarkerContext.addFormattersToContext(FreemarkerContext.java:167)
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.thucydides.core.reports.html.Reporter.generateReports(Reporter.java:53)
	at net.thucydides.core.reports.html.Reporter.generateReportsFor(Reporter.java:29)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:211)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:243)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:186)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
	at net.thucydides.core.reports.html.FreemarkerContext.addFormattersToContext(FreemarkerContext.java:167)
	at net.thucydides.core.reports.html.FreemarkerContext.getBuildContext(FreemarkerContext.java:95)
	at net.thucydides.core.reports.html.AggregateReportingTask.generateReports(AggregateReportingTask.java:40)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:32)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.vladsch.flexmark.util.options.DataHolder
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 9 more
[WARNING] Failed to generate report for Requirements report capabilities.html - java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
net.thucydides.core.reports.html.FreemarkerContext.addFormattersToContext(FreemarkerContext.java:167)
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.thucydides.core.reports.html.Reporter.generateReports(Reporter.java:53)
	at net.thucydides.core.reports.html.Reporter.generateReportsFor(Reporter.java:29)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:211)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:243)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:186)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
	at net.thucydides.core.reports.html.FreemarkerContext.addFormattersToContext(FreemarkerContext.java:167)
	at net.thucydides.core.reports.html.FreemarkerContext.getBuildContext(FreemarkerContext.java:95)
	at net.thucydides.core.reports.html.RequirementsOverviewReportingTask.generateReports(RequirementsOverviewReportingTask.java:89)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:32)
	at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.vladsch.flexmark.util.options.DataHolder
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 9 more
[WARNING] SOME REPORT PAGES COULD NOT BE GENERATED
 * Failed to generate report for Test Summary Report - java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
net.thucydides.core.reports.html.FreemarkerContext.addFormattersToContext(FreemarkerContext.java:167)

 * Failed to generate report for net.thucydides.core.reports.html.AggregateReportingTask@11cadb32 - java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
net.thucydides.core.reports.html.FreemarkerContext.addFormattersToContext(FreemarkerContext.java:167)

 * Failed to generate report for Requirements report capabilities.html - java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/vladsch/flexmark/util/options/DataHolder
net.thucydides.core.reports.html.FreemarkerContext.addFormattersToContext(FreemarkerContext.java:167)


[INFO] Test results for 0 tests generated in 227 ms
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18.1:verify (default) @ 990TAutomation ---
[INFO] Failsafe report directory: C:\Users\a442046\eclipse-workspace\990TAutomation\target\failsafe-reports
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ 990TAutomation ---
[INFO] Installing C:\Users\a442046\eclipse-workspace\990TAutomation\target\990TAutomation-0.0.1-SNAPSHOT.jar to C:\Users\a442046\.m2\repository\990TAutomation\990TAutomation\0.0.1-SNAPSHOT\990TAutomation-0.0.1-SNAPSHOT.jar
[INFO] Installing C:\Users\a442046\eclipse-workspace\990TAutomation\pom.xml to C:\Users\a442046\.m2\repository\990TAutomation\990TAutomation\0.0.1-SNAPSHOT\990TAutomation-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:53 min
[INFO] Finished at: 2020-08-25T15:48:04-04:00
[INFO] Final Memory: 33M/358M
[INFO] ------------------------------------------------------------------------

**Comment by basid09** [comment]
Same issue here
