### ISSUE TITLE
Error generating Serenity report with approved test cases

### ISSUE THREAD

**Issue by knludi** [serenity-bdd/serenity-core#701]
The test case passes, but when generating the report the error is thrown. I already researched a lot and I did not find the solution.

The problem only occurs when using @RunWith (SerenityParameterizedRunner.class)

I'm making my classes, the csv file and the pom.xml available, to try to reproduce the problem:

https://github.com/knludi/training_serenity/blob/master/serenity.zip

Just run the "Login" test.

When I run the test, Serenity tries to generate the html report and crashes.

Here is the exception log that is happening:

![print_211](https://cloud.githubusercontent.com/assets/22732624/23264547/7513d0e0-f9c0-11e6-9880-fedf919a6480.jpg)
24261 [main] INFO net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter - GENERATING JUNIT REPORT SERENITY-JUNIT-822ae03714fc77b79bcd7461759a9603500d36339e17d204e90ef4dd5e14545f.xml
ch.lambdaj.function.argument.InvocationException: Failed invocation of public int net.thucydides.core.model.TestOutcome.countResults(net.thucydides.core.model.TestResult) on object Valida se o sistema efetua o login corretamente ao informar dados validos:Valida se o sistema efetua o login corretamente ao informar dados validos [[1] {CONTRATANTE TESTE=Treinamento, USUARIO TESTE=analistat, SENHA TESTE=1237, URL BASE TESTE=http://sgobh.algartech.com:8080} [Acessar o Link do Sistema, Inserir Dados Válidos, Acionar o botão 'Login', Validar se o sistema exibiu a página inicial]] caused by: null
	at ch.lambdaj.function.argument.Invocation.invokeOn(Invocation.java:70)
	at ch.lambdaj.function.argument.InvocationSequence.invokeOn(InvocationSequence.java:91)
	at ch.lambdaj.function.argument.InvocationSequence.invokeOn(InvocationSequence.java:85)
	at ch.lambdaj.function.argument.Argument.evaluate(Argument.java:35)
	at ch.lambdaj.function.convert.ArgumentConverter.convert(ArgumentConverter.java:36)
	at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
	at ch.lambdaj.Lambda.typedSum(Lambda.java:576)
	at ch.lambdaj.Lambda.sum(Lambda.java:570)
	at net.thucydides.core.model.OutcomeCounter.withResult(OutcomeCounter.java:23)
	at net.thucydides.core.reports.junit.JUnitXMLConverter.buildTestSuiteElement(JUnitXMLConverter.java:137)
	at net.thucydides.core.reports.junit.JUnitXMLConverter.write(JUnitXMLConverter.java:41)
	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:47)
	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:149)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:137)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:97)
	at net.serenitybdd.junit.runners.SerenityParameterizedRunner.generateReportsFor(SerenityParameterizedRunner.java:193)
	at net.serenitybdd.junit.runners.SerenityParameterizedRunner.generateReports(SerenityParameterizedRunner.java:189)
	at net.serenitybdd.junit.runners.SerenityParameterizedRunner.run(SerenityParameterizedRunner.java:184)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at ch.lambdaj.function.argument.Invocation.invokeOn(Invocation.java:68)
	... 23 more
Caused by: java.lang.SecurityException: class "org.hamcrest.Matchers"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.thucydides.core.model.TestOutcome.countDataRowsWithResult(TestOutcome.java:1390)
	at net.thucydides.core.model.TestOutcome.countResults(TestOutcome.java:1363)
	at net.thucydides.core.model.TestOutcome.countResults(TestOutcome.java:1355)
	... 28 more

![image](https://cloud.githubusercontent.com/assets/22732624/23264582/9473d728-f9c0-11e6-9751-cf2029b03eda.png)

**Comment by cliviu** [comment]
maybe this one helps : http://stackoverflow.com/questions/9651784/hamcrest-tests-always-fail

**Comment by cliviu** [comment]
https://code.google.com/archive/p/hamcrest/issues/128

**Comment by knludi** [comment]
Perfect!
I'll never imagine it could be this ... The exception gave no hint that this was the problem.

I followed the steps:

1. Right click on top of the project;
2. Properties;
3. Java Build Path;
4. Click JUnit4;
5. Remove

Thank you!
