### ISSUE TITLE
Serenity Rest Assured won't work with rest-assured 2.4.1

### ISSUE THREAD

**Issue by encius** [serenity-bdd/serenity-core#708]
I keep getting this error when I try to run a test:

```
net.thucydides.core.requirements.CouldNotLoadRequirementsException
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsFromClassesInPackage(PackageRequirementsTagProvider.java:163)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementPathsStartingFrom(PackageRequirementsTagProvider.java:151)
	at net.thucydides.core.requirements.PackageRequirementsTagProvider.getActiveRequirementTypes(PackageRequirementsTagProvider.java:292)
	at net.thucydides.core.model.PackageBasedLeafRequirements.typeFrom(PackageBasedLeafRequirements.java:38)
	at net.thucydides.core.model.PackageBasedLeafRequirements.testCase(PackageBasedLeafRequirements.java:28)
	at net.thucydides.core.model.TestOutcome.storyDefinedIn(TestOutcome.java:383)
	at net.thucydides.core.model.TestOutcome.<init>(TestOutcome.java:373)
	at net.thucydides.core.model.TestOutcome.<init>(TestOutcome.java:353)
	at net.thucydides.core.model.TestOutcome.forTestInStory(TestOutcome.java:611)
	at net.thucydides.core.steps.BaseStepListener.testStarted(BaseStepListener.java:370)
	at net.thucydides.core.steps.StepEventBus.testStarted(StepEventBus.java:115)
	at net.thucydides.core.steps.StepEventBus.testStarted(StepEventBus.java:142)
	at net.thucydides.junit.listeners.JUnitStepListener.testStarted(JUnitStepListener.java:79)
	at org.junit.runner.notification.SynchronizedRunListener.testStarted(SynchronizedRunListener.java:49)
	at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:121)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:118)
	at org.junit.internal.runners.model.EachTestNotifier.fireTestStarted(EachTestNotifier.java:42)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:323)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:433)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:53)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:248)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:49)
	at net.thucydides.core.steps.BaseStepListener.getCurrentTestOutcome(BaseStepListener.java:293)
	at net.thucydides.core.steps.BaseStepListener.exceptionExpected(BaseStepListener.java:133)
	at net.thucydides.core.steps.StepEventBus.exceptionExpected(StepEventBus.java:645)
	at net.thucydides.junit.listeners.JUnitStepListener.updateResultsForExpectedException(JUnitStepListener.java:110)
	at net.thucydides.junit.listeners.JUnitStepListener.updateResultsUsingTestAnnotations(JUnitStepListener.java:105)
	at net.thucydides.junit.listeners.JUnitStepListener.testFinished(JUnitStepListener.java:95)
	at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
	at org.junit.internal.runners.model.EachTestNotifier.fireTestFinished(EachTestNotifier.java:38)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:331)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:433)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:53)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:248)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

If I add my own dependency to rest-assured greater than 2.4.1 it will work fine.
```
<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>2.9.0</version>
		</dependency>
```

**Comment by wakaleo** [comment]
The current version of serenity-rest-assured is compatible with 2.4.1, and should work without you having to provide your own version of RestAssured (see https://github.com/serenity-bdd/serenity-rest-taxi-stands for a demo). Using other versions of RestAssured is not recommended at this stage because of numerous breaking API changes introduced in new versions. 

The stack trace you provided appears to be unrelated to the rest-assured version. If you can provide a sample project reproducing the issue, we might be able to know more.

**Comment by wakaleo** [comment]
The RestAssured support has been rewritten and upgraded to 2.9.x. If you get this problem again, please feel free to reopen the issue.
