### ISSUE TITLE
Failed to run tests on SauceLabs Devices with serenity.driver.capabilities. Base URL can not be navigated

### ISSUE THREAD

**Issue by ibmer921150** [serenity-bdd/serenity-core#709]
Problem:
Failed to run tests on SauceLabs Devices with serenity.driver.capabilities. The job can be initial on sauce labs with OS-Browser combination. But the base URL can not be navigated. Test failed.

Steps:
1. Run test via following command line
mvn verify -Dwebdriver.driver=remote -Dserenity.driver.capabilities="deviceOrientation:portrait;appiumVersion:1.6.3;browserName:Safari;deviceName:iPhone 6s Simulator;platformVersion:9.3;platformName:iOS" -Dsaucelabs.url=http://xxx:xxx@ondemand.saucelabs.com:80/wd/hub -Dsaucelabs.access.key=xxx -Dsaucelabs.user.id=xxx -Dwebdriver.base.url=xxx -Dmaven.test.failure.ignore=true

2. The job can be initial on Saucelabs. But the base URL can not be navigated.
3. Error as following

133100 [main] INFO net.thucydides.core.pages.Pages - Failed to instantiate page of type class nz.net.xxx.qa.pages.xxxHomePage ({})
org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 201 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'xxx', ip: '127.0.1.1', os.name: 'xxx', os.arch: 'amd64', os.version: '3.13.0-110-generic', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{orientation=PORTRAIT, networkConnectionEnabled=false, preventWDAAttachments=true, noReset=true, webdriver.remote.quietExceptions=true, hasMetadata=true, keepKeyChains=true, databaseEnabled=false, deviceName=iPhone 6s, launchTimeout=180000, platform=MAC, backendRetries=4, showIOSLog=true, desired={orientation=PORTRAIT, preventWDAAttachments=true, noReset=true, webdriver.remote.quietExceptions=true, keepKeyChains=true, deviceName=iPhone 6s, launchTimeout=180000, backendRetries=4, showIOSLog=true, newCommandTimeout=0, platformVersion=9.3, browserName=safari, javascriptEnabled=true, platformName=iOS}, webdriver.remote.sessionid=a1d37d3e65b248d9814de2a80ccd8f5f, newCommandTimeout=0, platformVersion=9.3, locationContextEnabled=false, webStorageEnabled=false, takesScreenshot=true, browserName=safari, javascriptEnabled=true, platformName=iOS}]
Session ID: a1d37d3e65b248d9814de2a80ccd8f5f
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:945)
	at nz.net.xxx.qa.pages.xxxHomePage.<init>(xxxHomePage.java:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.thucydides.core.pages.Pages.createFromConstructorWithWebdriver(Pages.java:247)
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:205)
	at net.thucydides.core.pages.Pages.getPage(Pages.java:89)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:54)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:32)
	at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:142)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:132)
	at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:118)
	at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:83)
	at net.thucydides.core.steps.StepFactory.getStepLibraryFor(StepFactory.java:77)
	at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:52)
	at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:41)
	at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:23)
	at net.serenitybdd.core.Serenity.injectScenarioStepsInto(Serenity.java:131)
	at net.serenitybdd.core.Serenity.initializeWithNoStepListener(Serenity.java:97)
	at cucumber.runtime.SerenityObjectFactory.newInstance(SerenityObjectFactory.java:68)
	at cucumber.runtime.SerenityObjectFactory.cacheNewInstance(SerenityObjectFactory.java:51)
	at cucumber.runtime.SerenityObjectFactory.getInstance(SerenityObjectFactory.java:41)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:299)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.ExamplesRunner.run(ExamplesRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.ScenarioOutlineRunner.run(ScenarioOutlineRunner.java:53)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
146436 [main] ERROR net.serenitybdd.core.Serenity

**Comment by wakaleo** [comment]
The problem is in this line:
```
org.openqa.selenium.WebDriverException: Method has not yet been implemented 
```

Which comes from the `maximize()` method. So it could be a driver issue.

**Comment by ibmer921150** [comment]
Thanks wakaleo. 
It appears that the driver can not be maximized on device. Disable the following command and everything is working fine. 

#driver.manage().window().maximize();
