### ISSUE TITLE
Unable to run tests on ie9 

### ISSUE THREAD

**Issue by prathimak** [serenity-bdd/serenity-core#737]
When i try to run tests on ie9 i got the below exception
my serenity.properties

serenity.take.screenshots=true
serenity.verbose.steps=true
thucydides.adaptors.zephyr=net.thucydides.plugins.jira.adaptors.ZephyrAdaptor
thucycides.step.delay=001
story.timeout.in.secs=160000
webdriver.timeouts.implicitlywait=1600
serenity.driver.capabilities=INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS:true;ACCEPT_SSL_CERTS:true
webdriver.driver = iexplorer webdriver.ie.driver=IEDriverServer.exe 

 net.thucydides.core.webdriver.UnsupportedDriverException: Unsupported browser type: iexplorer webdriver.ie.driver=IEDriverServer.exe . Did you mean android?

java.lang.RuntimeException: net.thucydides.core.webdriver.UnsupportedDriverException: Unsupported browser type: iexplorer webdriver.ie.driver=IEDriverServer.exe . Did you mean android?
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:179)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: net.thucydides.core.webdriver.UnsupportedDriverException: Unsupported browser type: iexplorer webdriver.ie.driver=IEDriverServer.exe . Did you mean android?
	at net.thucydides.core.webdriver.SupportedWebDriver.getDriverTypeFor(SupportedWebDriver.java:158)
	at net.thucydides.core.configuration.SystemPropertiesConfiguration.lookupSupportedDriverTypeFor(SystemPropertiesConfiguration.java:238)
	at net.thucydides.core.configuration.SystemPropertiesConfiguration.getDriverType(SystemPropertiesConfiguration.java:100)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.getDefaultDriverType(SerenityWebdriverManager.java:145)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.getWebdriver(SerenityWebdriverManager.java:88)
	at net.thucydides.core.webdriver.ThucydidesWebDriverSupport.getDriver(ThucydidesWebDriverSupport.java:128)
	at net.serenitybdd.jbehave.SerenityReporter.prepareSerenityListeners(SerenityReporter.java:172)
	at net.serenitybdd.jbehave.SerenityReporter.beforeStory(SerenityReporter.java:140)
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStory(DelegatingStoryReporter.java:72)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStory(ConcurrentStoryReporter.java:117)
	at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:431)
	at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:117)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)
	at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:86)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:177)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Unsupported driver type: IEXPLORER WEBDRIVER.IE.DRIVER=IEDRIVERSERVER.EXE 
	at net.thucydides.core.webdriver.SupportedWebDriver.valueOrSynonymOf(SupportedWebDriver.java:117)
	at net.thucydides.core.webdriver.SupportedWebDriver.getDriverTypeFor(SupportedWebDriver.java:154)
	... 22 more

**Comment by wakaleo** [comment]
Your properties file is incorrectly formatted: you need to put the webdriver properties on two lines:

    webdriver.driver = iexplorer  
    webdriver.ie.driver=IEDriverServer.exe

**Comment by prathimak** [comment]
I changed my properties got below exception

java.lang.RuntimeException: net.thucydides.core.webdriver.UnsupportedDriverException: Unsupported browser type: iexplorer  . Did you mean firefox?
at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:179)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: net.thucydides.core.webdriver.UnsupportedDriverException: Unsupported browser type: iexplorer  . Did you mean firefox?
	at net.thucydides.core.webdriver.SupportedWebDriver.getDriverTypeFor(SupportedWebDriver.java:158)
	at net.thucydides.core.configuration.SystemPropertiesConfiguration.lookupSupportedDriverTypeFor(SystemPropertiesConfiguration.java:238)
	at net.thucydides.core.configuration.SystemPropertiesConfiguration.getDriverType(SystemPropertiesConfiguration.java:100)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.getDefaultDriverType(SerenityWebdriverManager.java:145)
	at net.thucydides.core.webdriver.SerenityWebdriverManager.getWebdriver(SerenityWebdriverManager.java:88)
	at net.thucydides.core.webdriver.ThucydidesWebDriverSupport.getDriver(ThucydidesWebDriverSupport.java:128)
	at net.serenitybdd.jbehave.SerenityReporter.prepareSerenityListeners(SerenityReporter.java:172)
	at net.serenitybdd.jbehave.SerenityReporter.beforeStory(SerenityReporter.java:140)
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStory(DelegatingStoryReporter.java:72)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStory(ConcurrentStoryReporter.java:117)
	at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:431)
	at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:117)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)
	at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:86)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)
	at net.serenitybdd.jb

**Comment by wakaleo** [comment]
Make sure there are no training spaces after "iexplorer"

**Comment by prathimak** [comment]
Yep tried got below exception
Started InternetExplorerDriver server (64-bit)
2.39.0.0
Listening on port 2316
2017-03-28 13:46:19 WARN  InternetExplorerServicePool:76 - Remote driver creation failed (Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)), falling back on default driver creation
Started InternetExplorerDriver server (64-bit)
2.39.0.0
Listening on port 13828
2017-03-28 13:46:19 ERROR InternetExplorerDriverProvider:76 - org.openqa.selenium.remote.SessionNotFoundException happened - retrying in 2 seconds
2017-03-28 13:46:21 WARN  InternetExplorerServicePool:76 - Remote driver creation failed (Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)), falling back on default driver creation
Started InternetExplorerDriver server (64-bit)
2.39.0.0
Listening on port 11463
2017-03-28 13:46:22 ERROR InternetExplorerDriverProvider:76 - org.openqa.selenium.remote.SessionNotFoundException happened - retrying in 2 seconds
2017-03-28 13:46:24 WARN  InternetExplorerServicePool:76 - Remote driver creation failed (Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)), falling back on default driver creation
Started InternetExplorerDriver server (64-bit)
2.39.0.0
Listening on port 44578
2017-03-28 13:46:24 ERROR InternetExplorerDriverProvider:76 - org.openqa.selenium.remote.SessionNotFoundException happened - retrying in 2 seconds
2017-03-28 13:46:26 WARN  InternetExplorerServicePool:76 - Remote driver creation failed (Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)), falling back on default driver creation

Do i need to have Protected Mode settings same for all zones?

**Comment by wakaleo** [comment]
Yes, that is a documented problem with the IEDriver.

**Comment by prathimak** [comment]
Thank you for your due to security reason we can't enable for all zones,is there any work around for this

**Comment by wakaleo** [comment]
I don't believe so. It is for reasons like this that many automation specialists avoid testing on IE. See http://jimevansmusic.blogspot.co.uk/2012/08/youre-doing-it-wrong-protected-mode-and.html.

**Comment by prathimak** [comment]
Thank you for the article,but i dont have permission to security tab ,hmm this is bit annoying

**Comment by wakaleo** [comment]
Do you really need to test on IE?

**Comment by prathimak** [comment]
yes thats the business requirement and i tried firefox as well when ever i ran the tests firefox started installing dont know why

**Comment by wakaleo** [comment]
Have you considered running your tests using a service like Saucelabs or BrowserStack? Both make it much easier to test with many different types of browser.

**Comment by prathimak** [comment]
Yes we are looking for browser stack but at the moment budget issues
