### ISSUE TITLE
Aggregate task runs with error

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-core#769]
After upgrading serenity-core to 1.2.5-rc.6 version, aggregate task started failing with the following exception:
`Unable to store test outcome for posterity
java.nio.file.NoSuchFileException: history
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
        at java.nio.file.Files.newDirectoryStream(Files.java:457)
        at net.serenitybdd.core.history.FileSystemTestOutcomeSummaryRecorder.loadSummaries(FileSystemTestOutcomeSummaryRecorder.java:93)
        at net.serenitybdd.core.history.HistoricalFlagProvider.<init>(HistoricalFlagProvider.java:32)
        at net.serenitybdd.core.history.HistoricalFlagProvider$$FastClassByGuice$$4a4d0dce.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
        at net.thucydides.core.model.TestOutcome.<init>(TestOutcome.java:247)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:108)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:206)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at net.thucydides.core.reports.json.gson.GsonJSONConverter.fromJson(GsonJSONConverter.java:58)
        at net.thucydides.core.reports.json.JSONTestOutcomeReporter.loadReportFrom(JSONTestOutcomeReporter.java:106)
        at net.thucydides.core.reports.TestOutcomeLoader$TestOutcomeLoaderCallable.call(TestOutcomeLoader.java:113)
        at net.thucydides.core.reports.TestOutcomeLoader$TestOutcomeLoaderCallable.call(TestOutcomeLoader.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Report generation timed out for Requirements report capabilities.html - java.util.concurrent.TimeoutException
java.util.concurrent.FutureTask.get(FutureTask.java:205)
SOME REPORT PAGES COULD NOT BE GENERATED
 * Report generation timed out for Requirements report capabilities.html - java.util.concurrent.TimeoutException
java.util.concurrent.FutureTask.get(FutureTask.java:205)
`
The index html file is created and the report looks fine. But I'd like to keep a clean logs.
Do I need to set some property to resolve this error ?

**Comment by ilzul** [comment]
Verified on serenity_version = "1.2.5-rc.11"
