### ISSUE TITLE
Changing JIRA workflow status using Serenity

### ISSUE THREAD

**Issue by Jcigniti** [serenity-bdd/serenity-core#778]
Hi,

I am quite new to Jbehave and Serenity. Trying to integrate JIRA with Serenity, Right now I could see the JIRA ticket link is attached in Serenity reports, but I also want to change the workflow status. These JIRA tickets are created for automation purpose and whenever the test case is passed the status to be changed as passed also as failed if the automation test case is failed. Below is the screenshot of my JIRA workflow.

![image](https://cloud.githubusercontent.com/assets/17033782/25658100/bd5600f0-301e-11e7-8837-860ab649068d.png)

I have created workflow file in below path

![image](https://cloud.githubusercontent.com/assets/17033782/25658165/1a497b98-301f-11e7-8821-3ee989941279.png) 

I have set the classpath as 
![image](https://cloud.githubusercontent.com/assets/17033782/25658199/4be52cf6-301f-11e7-919f-2115e539d867.png)

I am running the tests in Saucelabs, and I dont see any JIRA logs created. Could you please help me with this scenario.

Thanks

**Comment by Jcigniti** [comment]
Comment is added to Jira story, but the workflow status is not changed. Could you look at below logs and suggest.

TEST PASSED: User can track a shipment by entering a valid tracking number
----------------------------------------------------------------------------
[pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.public.url, please use the serenity.* format instead.

[pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.public.url, please use the serenity.* format instead.
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraUpdater - Updating JIRA issue: VMLNAFEDEXW-393
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraUpdater - JIRA server: Connection to JIRA instance at https://jira.uhub.biz with user jyothsna.thada@vml.com
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraUpdater - Updating comments for issue VMLNAFEDEXW-393
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraUpdater - WIKI Rendering activated: true
[pool-1-thread-1] WARN net.thucydides.core.ThucydidesSystemProperty - Legacy property format detected for thucydides.public.url, please use the serenity.* format instead.
[pool-1-thread-1] INFO net.thucydides.plugins.jira.JiraListener - Updating JIRA issue: VMLNAFEDEXW-393
[pool-1-thread-1] INFO net.thucydides.plugins.jira.JiraListener - JIRA server: Connection to JIRA instance at https://jira.uhub.biz/rpc/soap/jirasoapservice-v2 with user jyothsna.thada@vml.com
[pool-1-thread-1] INFO net.thucydides.plugins.jira.JiraListener - Updating comments for issue VMLNAFEDEXW-393
[pool-1-thread-1] INFO net.thucydides.plugins.jira.JiraListener - WIKI Rendering activated: true
May 04, 2017 8:34:49 PM com.google.common.util.concurrent.AbstractFuture executeListener
SEVERE: RuntimeException while executing runnable net.thucydides.plugins.jira.JiraListener$2@506f2494 with executor com.google.common.util.concurrent.MoreExecutors$DirectExecutorService@30ca99cd
net.thucydides.plugins.jira.model.IssueTrackerUpdateException: Could not update JIRA using URL (https://jira.uhub.biz/rpc/soap/jirasoapservice-v2)
	at net.thucydides.plugins.jira.service.JiraIssueTracker.processJiraException(JiraIssueTracker.java:78)
	at net.thucydides.plugins.jira.service.JiraIssueTracker.getCommentsFor(JiraIssueTracker.java:102)
	at net.thucydides.plugins.jira.JiraListener.newOrUpdatedCommentFor(JiraListener.java:239)
	at net.thucydides.plugins.jira.JiraListener.updateIssue(JiraListener.java:212)
	at net.thucydides.plugins.jira.JiraListener.access$3(JiraListener.java:209)
	at net.thucydides.plugins.jira.JiraListener$2.run(JiraListener.java:180)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:595)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:96)
	at net.thucydides.plugins.jira.JiraListener.updateIssueStatus(JiraListener.java:176)
	at net.thucydides.plugins.jira.JiraListener.testSuiteFinished(JiraListener.java:160)
	at net.thucydides.core.steps.StepEventBus.testSuiteFinished(StepEventBus.java:507)
	at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:504)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:122)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:792)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:416)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:387)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: (404)Not Found
	at org.apache.axis.transport.http.HTTPSender.readFromSocket(HTTPSender.java:744)
	at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:144)
	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:2443)
	at org.apache.axis.client.Call.invoke(Call.java:2366)
	at org.apache.axis.client.Call.invoke(Call.java:1812)
	at thucydides.plugins.jira.soap.JirasoapserviceV2SoapBindingStub.login(JirasoapserviceV2SoapBindingStub.java:3797)
	at net.thucydides.plugins.jira.client.SOAPSession.usingCredentials(SOAPSession.java:49)
	at net.thucydides.plugins.jira.service.JIRAConnection.getSoapSession(JIRAConnection.java:27)
	at net.thucydides.plugins.jira.service.JIRAConnection.getAuthenticationToken(JIRAConnection.java:52)
	at net.thucydides.plugins.jira.service.JiraIssueTracker.getCommentsFor(JiraIssueTracker.java:97)
	... 23 more

**Comment by wakaleo** [comment]
"Caused by: (404)Not Found" would indicate an error in the URL. It also looks like the library is using the (deprecated) SOAP API; are you using the latest version of the serenity jira library?

**Comment by Jcigniti** [comment]
hi wakaleo,

Actually i have another problem with me this is nagabhushan(naguguna244@gmail.com)
here is my console out output is :

TEST PASSED: User can track a shipment by entering a valid tracking number
----------------------------------------------------------------------------

[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - Updating JIRA issue: VMLNAFEDEXW-393
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - JIRA server: Connection to JIRA instance at https://jira.uhub.biz with user xxxxxx@vml.com
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - Updating comments for issue VMLNAFEDEXW-393
[pool-1-thread-1] INFO net.serenitybdd.plugins.jira.JiraListener - WIKI Rendering activated: true


and i am using :+1: : 
<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jira-requirements-provider</artifactId>
			<version>1.1.2-rc.1</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jira-plugin</artifactId>
			<version>1.1.2-rc.1</version>
		</dependency>

and my groovyfile is:
jira-workflow.groovy(location of my groovy File is:/fedex-tests/src/test/resources/jira-workflow.groovy)

when 'Open', {
    'success' should: 'Resolve Issue'
}

when 'Open', {
    'success' should: 'Resolve'
}

when 'Open', {
    'failure' should: 'Resolve'
}

when 'Reopened', {
    'success' should: 'Passed'
}

when 'Reopened', {
    'failure' should: 'Passed'
}

when 'FAILED', {
    'success' should: 'Reopen Issue'
}

when 'FAILED', {
    'failure' should: 'Reopen Issue'
}

when 'In Progress', {
    'success' should: ['Stop Progress','Resolve Issue']
}

when 'Closed', {

     'success' should: 'Reopen'
}

And my Properties file is:
jira.url=https://jira.uhub.biz

jira.username=xxxxxx
jira.password=xxxxxx

serenity.public.url=file://C:/VML/Amazon-WorkingCopy/target/site/serenity/index.html

serenity.jira.workflow.active=true

serenity.jira.workflow=jira-workflow.groov

While console is showing that issue is updationg like that but it is not affected in jira



Please let me know why jiira status is not updating 

Thanks in advance

**Comment by cliviu** [comment]
Please check this issue, it may help : https://github.com/serenity-bdd/serenity-core/issues/676

**Comment by cliviu** [comment]
use use everywhere version 1.1.3-rc.2 of serenity-jira-plugin/serenity-jira-requirements-provider

**Comment by Jcigniti** [comment]
Thank you so much for your time @cliviu, but this day i can't try version 1.1.3-rc.2 due to sauce labs server down. Once the sauce labs server is up and running, I will change the version to 1.1.3-rc.2 and let you know. Please don't  close this issue.

**Comment by cliviu** [comment]
this pom file works for me. I will attach it 
[pom.zip](https://github.com/serenity-bdd/serenity-core/files/991859/pom.zip).
Please check that you do not have a typo in your properties.file : 

> serenity.jira.workflow=**jira-workflow.groov**

From your IDE, I can read that the name of your property file is **jira_workflow.groovy** . You have configured it in the properties file with dash but your actual file uses underscore. Not to mention the missing "y" from "groov" :-(
