### ISSUE TITLE
Serenity BDD fails with Generics due to CGLIB limitations

### ISSUE THREAD

**Issue by mtedone** [serenity-bdd/serenity-core#80]
I've got the following tests: 

```
@Test
    @Title("Podam should create sorted Maps")
    public void testSortedMapCreation() {
        testMap(TreeMap.class);
    }

    @Test
    @Title("Podam should create Concurrent Maps")
    public void testConcurrentMapCreation() {
        testMap(ConcurrentHashMap.class);
    }

    @Test
    @Title("Podam should create Hash Maps")
    public void testHashMapCreation() {
        testMap(HashMap.class);
    }



    //------------------> Private methods

    private void testMap(Class<? extends Map> mapType) {

        PodamFactory podamFactory = podamFactorySteps.givenAStandardPodamFactory();

        DataProviderStrategy strategy = podamFactory.getStrategy();

        int mapSize = strategy.getNumberOfCollectionElements(PodamTestInterface.class);

        Map<?,?> pojo = podamInvocationSteps.whenIInvokeTheFactoryForGenericTypeWithSpecificType(
                mapType, podamFactory, PodamTestInterface.class);


        podamValidationSteps.theMapShouldContainAtLeastOneNonEmptyElement(pojo);
        podamValidationSteps.theCollectionShouldHaveExactlyTheExpectedNumberOfElements(pojo.keySet(), mapSize);
        podamValidationSteps.theCollectionShouldHaveExactlyTheExpectedNumberOfElements(pojo.values(), mapSize);
    }
```

When running Serenity throws the following exception: 

```
java.lang.ClassCastException: uk.co.jemos.podam.test.unit.steps.PodamInvocationSteps$$EnhancerByCGLIB$$fd76e560 cannot be cast to java.util.Map
	at uk.co.jemos.podam.test.unit.features.collections.CollectionsTest.testMap(CollectionsTest.java:180)
	at uk.co.jemos.podam.test.unit.features.collections.CollectionsTest.testSortedMapCreation(CollectionsTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:435)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:59)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:248)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

However Junit passes with the following tests: 

```
public class MapUnitTest {

	private static final DataProviderStrategy strategy =
			new RandomDataProviderStrategyImpl();

	private static final PodamFactory factory = new PodamFactoryImpl(strategy);

	private void testMap(Class<?> mapType, int mapSize) {
		Map<?,?> pojo = (Map<?,?>)factory.manufacturePojo(mapType,
				String.class, PodamTestInterface.class);
		Assert.assertNotNull("Construction failed", pojo);
		Assert.assertEquals("Wrong size of key set",
				mapSize, pojo.keySet().size());
		Assert.assertEquals("Wrong size of value set",
				mapSize, pojo.values().size());
	}
	
	@Test
	public void testSortedMapCreation() {

		testMap(TreeMap.class,
				strategy.getNumberOfCollectionElements(PodamTestInterface.class));
	}

	@Test
	public void testConcurrentMapCreation() {

		testMap(ConcurrentHashMap.class, 0);
	}

	@Test
	public void testHashMapCreation() {

		testMap(HashMap.class,
				strategy.getNumberOfCollectionElements(PodamTestInterface.class));
	}
}
```

**Comment by wakaleo** [comment]
What does the whenIInvokeTheFactoryForGenericTypeWithSpecificType() method look like?

**Comment by mtedone** [comment]
@Step("When I invoke Podam for a Generic Pojo specifying the concrete types")
public <T> T whenIInvokeTheFactoryForGenericTypeWithSpecificType(
        Class<T> pojoClass,
        PodamFactory podamFactory, Type... genericTypeArgs) {
    return podamFactory.manufacturePojo(pojoClass, genericTypeArgs);
}

**Comment by wakaleo** [comment]
I can't seem to reproduce this, could you create a pull request with a unit test that reproduces the issue?

**Comment by mtedone** [comment]
You mean fork Serenity?

**Comment by wakaleo** [comment]
Yes - then just add a failing test to the
NonWebTestScenarioWithParameterizedSteps.java class

On 21 June 2015 at 08:47, Marco Tedone <notifications@github.com> wrote:

> You mean fork Serenity?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/80#issuecomment-113871394>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by mtedone** [comment]
I've put together something, but it doesn't run (don't know Gradle that much)

```
package net.thucydides.samples;

import net.serenitybdd.junit.runners.SerenityRunner;
import net.thucydides.core.annotations.Steps;
import net.thucydides.samples.testObjects.PodamTestInterface;
import org.junit.Test;
import org.junit.runner.RunWith;
import uk.co.jemos.podam.api.DataProviderStrategy;
import uk.co.jemos.podam.api.PodamFactory;

import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.concurrent.ConcurrentHashMap;

@RunWith(SerenityRunner.class)
public class NonWebTestScenarioWithParameterizedSteps {
    
    @Steps
    public SampleNonWebSteps steps;
        
    @Test
    public void happy_day_scenario() {
        steps.stepWithAParameter("proportionOf");
        steps.stepWithTwoParameters("proportionOf", 2);
        steps.stepThatSucceeds();
        steps.stepThatIsIgnored();
        steps.stepThatIsPending();
        steps.anotherStepThatSucceeds();
    }

    @Test(expected = IllegalArgumentException.class)
    public void should_throw_correct_exception() {
        steps.throw_exception();
    }


    @Test
    public void testSortedMapCreation() {
        testMap(TreeMap.class);
    }

    @Test
    public void testConcurrentMapCreation() {
        testMap(ConcurrentHashMap.class);
    }

    @Test
    public void testHashMapCreation() {
        testMap(HashMap.class);
    }

    //------------------> Private methods

    private void testMap(Class<? extends Map> mapType) {

        PodamFactory podamFactory = steps.givenAStandardPodamFactory();

        DataProviderStrategy strategy = podamFactory.getStrategy();

        int mapSize = strategy.getNumberOfCollectionElements(PodamTestInterface.class);

        Map<?,?> pojo = steps.whenIInvokeTheFactoryForGenericTypeWithSpecificType(
                mapType, podamFactory, PodamTestInterface.class);


        steps.theMapShouldContainAtLeastOneNonEmptyElement(pojo);
        steps.theCollectionShouldHaveExactlyTheExpectedNumberOfElements(pojo.keySet(), mapSize);
        steps.theCollectionShouldHaveExactlyTheExpectedNumberOfElements(pojo.values(), mapSize);
    }

}
```

SampleNonWebSteps

```
package net.thucydides.samples;

import net.thucydides.core.annotations.Pending;
import net.thucydides.core.annotations.Step;
import net.thucydides.junit.runners.ThucydidesRunner;
import org.junit.Assert;
import org.junit.Assume;
import org.junit.Ignore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import uk.co.jemos.podam.api.PodamFactory;
import uk.co.jemos.podam.api.PodamFactoryImpl;

import java.lang.reflect.Type;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import static org.hamcrest.Matchers.is;
import static org.junit.Assert.fail;

@SuppressWarnings("serial")
public class SampleNonWebSteps {

    private static final Logger LOGGER = LoggerFactory.getLogger(ThucydidesRunner.class);

    public SampleNonWebSteps() {
    }

    @Step("A pending step")
    @Pending
    public void stepThatIsPending() {}

    @Step
    @Ignore
    public void stepThatIsIgnored() {}

    @Step
    public void stepThatSucceeds() {
    }

    @Step
    public void anotherStepThatSucceeds() {}

    @Step
    public void stepThatFails() {
        throw new AssertionError("Oh bother!");
    }

    @Step
    public void anotherStepThatFails() {
        stepThatSucceeds();
        throw new AssertionError("Oh crap!");
    }

    @Step
    public void stepWithAParameter(String param) {}

    @Step
    public void stepWithTwoParameters(String param, int i) {}

    public void methodWithError() {
        String s = null;
        s.length();
    }

    @Step
    public void stepWithFailingNonStepMethod() {
        methodWithError();
    }

    public void methodWithMessagelessError() {
        fail();
    }

    @Step
    public void stepWithFailingAssumption() {
        Assume.assumeThat(true, is(false));
    }

    public void throw_exception() {
        throw new IllegalArgumentException("Your argument is invalid");
    }

    @Step("Given a standard Podam Factory")
    public PodamFactory givenAStandardPodamFactory() {
        return new PodamFactoryImpl();
    }

    @Step("When I invoke Podam for a Generic Pojo specifying the concrete types")
    public <T> T whenIInvokeTheFactoryForGenericTypeWithSpecificType(
            Class<T> pojoClass,
            PodamFactory podamFactory, Type... genericTypeArgs) {
        return podamFactory.manufacturePojo(pojoClass, genericTypeArgs);
    }

    @Step("Then the Map<?, ?> {0} should contain at least one non empty element")
    public void theMapShouldContainAtLeastOneNonEmptyElement(Map<?, ?> map) {
        Assert.assertTrue("The map attribute must be of type HashMap",
                map instanceof HashMap);
        Assert.assertNotNull("The map object in the POJO cannot be null", map);
        Set<?> keySet = map.keySet();
        Assert.assertNotNull("The Map must have at least one element", keySet);
        Object o = map.get(keySet
                .iterator().next());

        Assert.assertNotNull("The map element must not be null!",
                o);
    }

    @Step("Then the collection should have exactly {1} elements")
    public void theCollectionShouldHaveExactlyTheExpectedNumberOfElements(Collection<?> collection, int nbrElements) {
        Assert.assertTrue("The collection should have exactly " + nbrElements + " elements",
                collection.size() == nbrElements);
    }
}
```

Added a PodamTestInterface under a new package: samples/testObjects

```
package net.thucydides.samples.testObjects;

public interface PodamTestInterface {

}
```

Added the following dependency to grade.build

```
testCompile 'uk.co.jemos.podam:podam:5.4.1.RELEASE'
```

When running the tests I'm getting the following:

```
Testing started at 09:38 ...
09:38:17: Executing external tasks 'cleanTest test --tests net.thucydides.samples.NonWebTestScenarioWithParameterizedSteps'...
Inferred version: 1.0.58-SNAPSHOT
Publishing serenity-ant-task:net.serenity-bdd:1.0.58-SNAPSHOT
Publishing serenity-core:net.serenity-bdd:1.0.58-SNAPSHOT
Publishing serenity-report-resources:net.serenity-bdd:1.0.58-SNAPSHOT
Publishing serenity-browsermob-plugin:net.serenity-bdd:1.0.58-SNAPSHOT
Publishing serenity-gradle-plugin:net.serenity-bdd:1.0.58-SNAPSHOT
Publishing serenity-junit:net.serenity-bdd:1.0.58-SNAPSHOT
Publishing serenity-rest-assured:net.serenity-bdd:1.0.58-SNAPSHOT
Publishing serenity-sample-alternative-resources:net.serenity-bdd:1.0.58-SNAPSHOT
Publishing serenity-spring:net.serenity-bdd:1.0.58-SNAPSHOT
Publishing serenity-test-utils:net.serenity-bdd:1.0.58-SNAPSHOT
:serenity-junit:cleanTest
:serenity-report-resources:compileJava UP-TO-DATE
:serenity-report-resources:compileGroovy UP-TO-DATE
:serenity-report-resources:processResources UP-TO-DATE
:serenity-report-resources:classes UP-TO-DATE
:serenity-report-resources:jar UP-TO-DATE
:serenity-core:compileJava UP-TO-DATE
:serenity-core:compileGroovy UP-TO-DATE
:serenity-core:processResources UP-TO-DATE
:serenity-core:classes UP-TO-DATE
:serenity-core:jar UP-TO-DATE
:serenity-junit:compileJava UP-TO-DATE
:serenity-junit:compileGroovy UP-TO-DATE
:serenity-junit:processResources UP-TO-DATE
:serenity-junit:classes UP-TO-DATE
:serenity-test-utils:compileJava UP-TO-DATE
:serenity-test-utils:compileGroovy UP-TO-DATE
:serenity-test-utils:processResources UP-TO-DATE
:serenity-test-utils:classes UP-TO-DATE
:serenity-test-utils:jar UP-TO-DATE
:serenity-junit:compileTestJava UP-TO-DATE
:serenity-junit:compileTestGroovy UP-TO-DATE
:serenity-junit:processTestResources UP-TO-DATE
:serenity-junit:testClasses UP-TO-DATE
:serenity-junit:test
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
09:38:32,321 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.groovy] at [file:/Users/tedonema/dev/serenity-core/serenity-junit/build/resources/test/logback.groovy]
09:38:33,191 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@3429dcad - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:38:33,193 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@3429dcad - Naming appender as [STDOUT]
09:38:33,284 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@71a968df - There is no conversion class registered for conversion word [LOGGER]
09:38:33,284 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@71a968df - [LOGGER] is not a valid conversion word

Empty test suite.
Empty test suite.
:serenity-junit:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':serenity-junit:test'.
> No tests found for given includes: [net.thucydides.samples.NonWebTestScenarioWithParameterizedSteps]
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 15.905 secs
No tests found for given includes: [net.thucydides.samples.NonWebTestScenarioWithParameterizedSteps]
```

Is this what you were after?

**Comment by wakaleo** [comment]
I don't think this is Serenity as such. The podamFactory.manufacturePojo(pojoClass, genericTypeArgs) method call fails with:

java.lang.IllegalStateException: java.util.HashMap is missing generic type arguments, expected [K, V] found [interface net.thucydides.samples.PodamTestInterface]
	at uk.co.jemos.podam.api.PodamFactoryImpl.fillTypeArgMap(PodamFactoryImpl.java:307)
	at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoInternal(PodamFactoryImpl.java:1207)
	at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojo(PodamFactoryImpl.java:170)
	at net.thucydides.samples.SampleNonWebSteps.whenIInvokeTheFactoryForGenericTypeWithSpecificType(SampleNonWebSteps.java:105)
	at net.thucydides.samples.SampleNonWebSteps$$EnhancerByCGLIB$$e27d832b.CGLIB$whenIInvokeTheFactoryForGenericTypeWithSpecificType$10(<generated>)
	at net.thucydides.samples.SampleNonWebSteps$$EnhancerByCGLIB$$e27d832b$$FastClassByCGLIB$$880c1541.invoke(<generated>)

Without the @Step annotation (and also without the SerenityRunner), it returns null. With the @Step annotation, Serenity does it's best to avoid the test crashing after the first exception, but can't figure out what object type it should return because of the generics information that gets lost at runtime.

**Comment by mtedone** [comment]
Ok thanks, I'll look into it. I might have made an error while porting from
Junit to Serenity.

Regards,

**Comment by mtedone** [comment]
Apologes, I forgot to pass to the Map the key type. It's working now
