### ISSUE TITLE
Correct way to create step before test starts

### ISSUE THREAD

**Issue by a-en** [serenity-bdd/serenity-core#809]
In some cases, we need to call the steps before test starts (for making preconditions). 
In order to do that, we need to have static field with steps (because method marked with @BeforeClass should be static). 
So now I initialized steps as following:

```
@Steps
private static MySteps mysteps = new StepFactory().instantiateNewStepLibraryFor(MySteps.class);

```	
The issue that I get an exception at attempt to invoke method of steps class

```
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:45)
	at net.thucydides.core.steps.BaseStepListener.getCurrentTestOutcome(BaseStepListener.java:301)
	at net.thucydides.core.steps.BaseStepListener.stepFailed(BaseStepListener.java:634)
	at net.thucydides.core.steps.StepEventBus.stepFailed(StepEventBus.java:356)
	at net.thucydides.core.steps.StepInterceptor.notifyOfStepFailure(StepInterceptor.java:444)
	at net.thucydides.core.steps.StepInterceptor.logStepFailure(StepInterceptor.java:349)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:342)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)

```

It happens, because `latestTestOutcome` method returns Optional.absent(), but `getCurrentTestOutcome()` invokes `get()` without the check if optional is there.

The general question - what is proper way to initialize steps object in order to avoid this issue?

**Comment by wakaleo** [comment]
@Steps-annotated fields only work within the lifecycle of a test. If you need to do something before a test starts, you need to manage the objects yourself and not use the @Step annotation.

**Comment by a-en** [comment]
Thanks @wakaleo for the response, closing this issue.
