### ISSUE TITLE
The error "sun.proxy.$Profyx.how" display when execute test case with JUnit. 

### ISSUE THREAD

**Issue by phuoc-simplypost** [serenity-bdd/serenity-core#829]
Hi, 

Maybe it is already possible but I can't figure out how to do it. 
I run test case with SerenityRunner class as below:
`@WithTags(
        {
                @WithTag(type = "Regression", name = "Validation"),
        }
)
@RunWith(SerenityRunner.class)
public class CreateSingleDomesticOrderFeature {

        @Managed(uniqueSession = true)
        WebDriver userBrowser;

        @Steps
        MerchantSteps merchantSteps;

        Actor testMerchant = Actor.named("Test merchant user");

        @Before
        public void loginToMerchantPortal(){
                merchantSteps.loginWith("test","123",testMerchant);
        }

        @Title("Verify merchant can create order with single item")
        @Test
        public void verifyMerchantCanCreateOrderWithSingleItem(){
                Delivery delivery = new Delivery();
                merchantSteps.goToCreateDomesticOrderPage(testMerchant);
                merchantSteps.shouldSeeTheCreateDomesticOrderPage(testMerchant);
                merchantSteps.inputSingleItemWithCOD(testMerchant,delivery);
                merchantSteps.shouldSeeDatetimePickupDropOffPage(testMerchant);
                merchantSteps.checkNoNeedPickup(testMerchant);
                merchantSteps.checkNeedFollowSLA(testMerchant);
                merchantSteps.shouldSeeTheDropoffPage(testMerchant);
                merchantSteps.inputOneTimeDropoffAddress(testMerchant,delivery.getReceiver());
                merchantSteps.shouldSeeTheConfirmationPage(testMerchant);
                merchantSteps.confirmTheOrder(testMerchant);
                merchantSteps.shouldSeeTheOrderInOrderlist(testMerchant,delivery);
        }

        @After
        public void logOutMerchantPortal(){
                merchantSteps.logout(testMerchant);
        }`

But I faced the issue like this:

> `java.lang.StackOverflowError
	at com.sun.proxy.$Proxy24.how(Unknown Source)
	at net.serenitybdd.core.annotations.locators.SmartAnnotations.assertValidFindBy(SmartAnnotations.java:474)
	at net.serenitybdd.core.annotations.locators.SmartAnnotations.buildByFromFindBy(SmartAnnotations.java:268)
	at net.serenitybdd.core.annotations.locators.SmartAnnotations.buildBy(SmartAnnotations.java:228)
	at net.thucydides.core.annotations.locators.SmartElementLocator.<init>(SmartElementLocator.java:25)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.<init>(SmartAjaxElementLocator.java:60)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.<init>(SmartAjaxElementLocator.java:50)
	at net.thucydides.core.annotations.locators.SmartElementLocatorFactory.createLocator(SmartElementLocatorFactory.java:23)
	at net.thucydides.core.annotations.locators.SmartFieldDecorator.decorate(SmartFieldDecorator.java:48)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:27)
	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:21)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:152)
	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:156)
	at net.thucydides.core.pages.Pages.createFromSimpleConstructor(Pages.java:234)
	at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:203)
	at net.thucydides.core.pages.Pages.getPage(Pages.java:89)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:54)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:32)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:32)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55)`

Could anyone help me in this case?

**Comment by wakaleo** [comment]
The relevant code is in your page object (something odd happening with the @FindBy field), not here. I don't think it will affect your test, but this is not how you use the Actor class (see http://serenity-bdd.info/docs/articles/screenplay-tutorial.html)

**Comment by phuoc-simplypost** [comment]
Thank John, 
I'm going to do refactor my code to screenplay pattern. 
In my page object class, I do like this:
`public class CreateDomesticOrderPage extends MerchantHomePage {

    @FindBy(xpath = "//pm-steps-bar")
    WebElementFacade stepsBar;

    public void isCreateDomesticOrderPage(){
        stepsBar.shouldBePresent();
    }

    /**
        STEP 1
     **/
    public class CreateDomesticOrderStep1 extends CreateDomesticOrderPage {

        @FindBy(xpath = "//pm-delivery-domestic-services//select[@name='serviceType']")
        WebElementFacade serviceTypeDropdown;
        @FindBy(xpath = "//pm-delivery-domestic-services//select[contains(@ng-model,'CodType')]")
        WebElementFacade codTypeDropdown;
        @FindBy(id = "amount")
        WebElementFacade codAmount;
        @FindBy(name = "orderRef")
        WebElementFacade orderRefInput;
        @FindBy(xpath = "//div[@class='table-responsive']/table")
        WebElementFacade itemDetailsTable;
//        @FindBy(xpath = "//pm-delivery-domestic-services//div[contains(@ng-if,'showFees')]/div[2]")
//        WebElementFacade deliveryFeeLabel;
        @FindBy(xpath = "//pm-delivery-domestic-services//button[@class='btn btn-primary']")
        WebElementFacade nextStep1Btn;

        public void selectServiceType(String serviceType){
            selectItemInDropdownByText(serviceTypeDropdown,serviceType);
        }

        public void selectCodType(String codType){
            selectItemInDropdownByText(codTypeDropdown,codType);
        }

        public void inputOrderRef(String orderRef){
            typeInto(orderRefInput,orderRef);
        }

        public void inputCodAmount(String amount){
            typeInto(codAmount,amount);
        }

        public void enterSingleItemDetails(Parcel parcel){

            SPHtmlTable itemHTMLTable = new SPHtmlTable(itemDetailsTable);
            List<String> headings = convert(itemDetailsTable.findElements(By.xpath("thead//th")), SerenityUtil.toTextValues());
            List<Map<String, WebElement>> rows = itemHTMLTable.getWebElementRows(headings);

            for(Map<String, WebElement> row : rows){

                typeInto(row.get("Length (cm)"),parcel.getDeclaredLength());
                typeInto(row.get("Width (cm)"),parcel.getDeclaredWidth());
                typeInto(row.get("Height (cm)"),parcel.getDecalredHeight());
                typeInto(row.get("Weight * "),parcel.getActualWeight().toString());
                selectItemInDropdownByText((WebElementFacade) row.get("Weight Unit *"),parcel.getDeclaredUnit());
                typeInto(row.get("Desciption"),parcel.getDescription());
            }
        }

        public void clickNextButtonStep1(){
            clickOn(nextStep1Btn);
        }

    }`

Do I implement wrong at this step?

**Comment by phuoc-simplypost** [comment]
Hi, 
I know the issue already, in my MerchantHomePage, I declared 1 CreateDomesticOrderPage then it initial loop each other. 
Thanks for your help. I'm reading the screenplay tutorial.
