### ISSUE TITLE
serenity-core 1.4.0/guava 21 and org.openqa.selenium.support.ui.Wait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by foxrafi** [serenity-bdd/serenity-core#830]
Hi,

I'm trying to run old automated test cases that used Selenium 2.x and Serenity 1.1.31 using Selenium 3.4.0 and Serenity core 1.4.0 with guava 21 as mentioned in selenium release notes. The reason: the old tests don't work with the latest Firefox. Unfortunately, I receive the following exception:

Jun 29, 2017 12:05:10 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
JavaScript warning: http://njdimcmap:8080/dim_images/jquery.js, line 19: unreachable code after return statement
JVMLauncher.afterStart(): starting JVM process watcher
Given Dimensions Application is open (FAILED)
(net.serenitybdd.core.exceptions.SerenityManagedException: org.openqa.selenium.support.ui.Wait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;)
When I click Items tab (NOT PERFORMED)
Then Items table should be displayed (NOT PERFORMED)

net.serenitybdd.core.exceptions.SerenityManagedException: org.openqa.selenium.support.ui.Wait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;
	at net.thucydides.core.steps.ErrorConvertor.convertToAssertion(ErrorConvertor.java:22)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:342)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at com.foxrafi.automation.steps.DimensionsSteps$$EnhancerByCGLIB$$52d1e94d.open_application(<generated>)
	at com.foxrafi.automation.DimensionsWellnessCheck.openApplication(DimensionsWellnessCheck.java:14)
	(reflection-invoke)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)

Do you have any idea what is the reason and if there is any solution for it ? 

Thank you,
foxrafi

**Comment by wakaleo** [comment]
Serenity 1.4.x needs Selenium 2.53.1. Selenium 3.4.0 has breaking API changes, so you will need to use Serenity 1.5.0-rc.1

**Comment by foxrafi** [comment]
Thank you Wakaleo. Where could I find jar files for 1.5.0-rc.1 ?

**Comment by wakaleo** [comment]
It is on bintray

**Comment by foxrafi** [comment]
ok, thank you. Do you know if it will be available also in the Central maven repository ? Unfortunately bintray is blocked in my company. Thank you

**Comment by foxrafi** [comment]
Today I found that 1.5.0-rc1 appeared in Maven Central. Thanks :-)
