### ISSUE TITLE
Not close firefox after updating Serenity version

### ISSUE THREAD

**Issue by fbn945** [serenity-bdd/serenity-core#867]
Hi!
After updating:

- Serenity 1.4.0 -> 1.5.3
- Se Server 2.53.1 -> 3.4.0
- ff 46.0.0 -> 53.0.0 + geckoDriver 0.18

firefox instanses not close after test finish. And as sequence all memory of VM leaks.
Chrome works correct.

**Comment by wakaleo** [comment]
Firefox is working correctly on Mac (hard to see on the linux build server) - what environment are you running on?

**Comment by fbn945** [comment]
Ubuntu with grid.
Also I tried to run same configuration locally on Win env (1 thread) and detected a same problem

**Comment by wakaleo** [comment]
Could you post the error message/logs?

**Comment by fbn945** [comment]
Sure, logs parts:

> 1501590308915   geckodriver INFO    geckodriver 0.18.0
1501590308921   geckodriver INFO    Listening on 127.0.0.1:11128
1501590309625   geckodriver::marionette INFO    Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
[GPU 11548] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1501590386824   Marionette  WARN    TLS certificate errors will be ignored for this session
1501590312283   Marionette  INFO    Listening on port 57804
1501590313060   Marionette  WARN    TLS certificate errors will be ignored for this session
org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
 org.openqa.selenium.interactions.Actions moveToElement
INFO: When using the W3C Action commands, offsets are from the center of element
[Time-limited test] INFO net.serenitybdd.core.Serenity - STEP ERROR: net.serenitybdd.core.exceptions.SerenityManagedException: mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
Driver info: driver.version: RemoteWebDriver

---

> org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

> [main] WARN net.thucydides.core.webdriver.WebDriverFacade - Error while quitting the driver (quit
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'

> Capabilities [{moz:profile=C:\Users\user\AppData\Local\Temp\rust_mozprofile.XshbYKCHstfs, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=53.0, platformVersion=10.0, moz:processID=4192.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]

---

> [Time-limited test] INFO net.serenitybdd.core.Serenity - STEP ERROR: net.serenitybdd.core.exceptions.SerenityManagedException: Failed to decode response from marionette
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP', ip: '123.123.11.11', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.remote.RemoteWebDriver

---

> Failure in JUnit mode for class web.tests.mytest.myTest
    at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:107)
    at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
    at org.testng.TestRunner$1.run(TestRunner.java:682)
    at org.testng.TestRunner.runWorkers(TestRunner.java:1005)
    at org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
    at org.testng.TestRunner.run(TestRunner.java:614)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
[Time-limited test] INFO net.serenitybdd.core.Serenity - STARTING STEP Should page: 1
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:212)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[Time-limited test] INFO net.serenitybdd.core.Serenity - IGNORING STEP
Caused by: java.util.ConcurrentModificationException
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at net.thucydides.core.model.TestOutcome.getCurrentTestResults(TestOutcome.java:1276)
    at net.thucydides.core.model.TestOutcome.getResult(TestOutcome.java:1186)
    at net.thucydides.core.model.TestOutcome.isFailure(TestOutcome.java:2036)
    at net.thucydides.core.reports.junit.JUnitXMLConverter.buildTestCaseElement(JUnitXMLConverter.java:63)
    at net.thucydides.core.reports.junit.JUnitXMLConverter.write(JUnitXMLConverter.java:39)
    at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:53)
    at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:182)
    at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:166)
    at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:113)
    at net.serenitybdd.junit.runners.SerenityRunner.generateReportsFor(SerenityRunner.java:410)
    at net.serenitybdd.junit.runners.SerenityRunner.generateReports(SerenityRunner.java:305)
    at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:259)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
    at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)

> [main] WARN net.thucydides.core.webdriver.WebDriverFacade - Error while quitting the driver (quit
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'

**Comment by wakaleo** [comment]
I'll take a look, but this looks like a geckodriver issue

**Comment by fbn945** [comment]
Using ff v55 decided the problem
Look a like GeckoDriver issue https://github.com/mozilla/geckodriver/issues/833

Thank you John
