### ISSUE TITLE
issue with Firefox in Serenity BDD

### ISSUE THREAD

**Issue by push2212** [serenity-bdd/serenity-core#880]
Hello,

I am using Serenity BDD version 1.4, 32 bit Firefox 54.0.1 and geckodriver v18.0 -32 bit, however the Serenity is launching firefox but not entering the URL.

could you please help me resolve the issue.

**Comment by wakaleo** [comment]
Have you placed the geckodriver on the system path?

**Comment by bebef1987** [comment]
Can you share the stack trace please

**Comment by push2212** [comment]
@wakaleo Hi, I have placed the geckodriver in the lib folder of the Serenity framework.
@bebef1987 Hi , PFB 
TEST STARTED: Verify MultiLogin
-------------------------------------------------------------------(stories/Application/Basic/Login.story;Verify MultiLogin)
Scenario: Verify MultiLogin
1502368206059	geckodriver	INFO	geckodriver 0.18.0
1502368206117	geckodriver	INFO	Listening on 127.0.0.1:27645
1502368206814	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1502368209491	Marionette	INFO	Listening on port 54419
15980 [pool-1-thread-1] WARN net.thucydides.core.webdriver.WebDriverFacade - Failed to take screenshot (Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance)
15984 [pool-1-thread-1] WARN net.thucydides.core.webdriver.WebDriverFacade - Failed to get the page source code (com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String)
15988 [pool-1-thread-1] WARN net.thucydides.core.webdriver.WebDriverFacade - Failed to get the page source code (com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String)
Given Login with 'ADMIN' in 'Env' (FAILED)
(java.lang.AssertionError: Login Button is not visible)
When Customise 'RootProduct' with Econfig Item 'DataRoamingBarOff%PlanOn' (NOT PERFORMED)

java.lang.AssertionError: Login Button is not visible
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at pages.LoginPage.Login(LoginPage.java:64)
	at pages.LoginPage$$EnhancerByCGLIB$$cfe6b5eb.CGLIB$Login$1(<generated>)
	at pages.LoginPage$$EnhancerByCGLIB$$cfe6b5eb$$FastClassByCGLIB$$7c9c3f3c.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:372)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:357)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:332)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at pages.LoginPage$$EnhancerByCGLIB$$cfe6b5eb.Login(<generated>)
	at jbehave.steps.Login.LoginToSiebel(Login.java:23)
	(reflection-invoke)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)
...
16184 [pool-1-thread-1] ERROR net.serenitybdd.core.Serenity - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED: Verify MultiLogin
--------------------------------------------------------------------------
16356 [pool-1-thread-1] ERROR net.serenitybdd.core.Serenity - TEST FAILED AT STEP Login: ADMIN, Env
16356 [pool-1-thread-1] ERROR net.serenitybdd.core.Serenity - Login Button is not visible

2 stories excluded by filter: +Log -skip -ignore -wip


(AfterStories)
17086 [pool-2-thread-1] INFO net.thucydides.core.reports.json.JSONTestOutcomeReporter - Generating JSON report for Verify MultiLogin to file C:\OpenUI-SJBPushkar\target\site\serenity\aa5ba493cc3263e4c0a2fa2316bf7d3afa9bc8622804cc3bf10d0c04de46cef2.json (using temp file C:\OpenUI-SJBPushkar\target\site\serenity\aa5ba493cc3263e4c0a2fa2316bf7d3afa9bc8622804cc3bf10d0c04de46cef2.json675ab5f7-4708-407f-8227-f46b1e63346e)
17764 [pool-3-thread-1] INFO net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - GENERATING HTML REPORT FOR Story: Multiple Login:Verify MultiLogin in aa5ba493cc3263e4c0a2fa2316bf7d3afa9bc8622804cc3bf10d0c04de46cef2.html in directory target\site\serenity  

Generating reports view to 'C:\OpenUI-SJBPushkar\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 2 stories (of which 0 pending) containing 1 scenarios (of which 0 pending)
Failures in reports view: 1 scenarios failed
[ERROR] [1;31mTests [0;1mrun: [0;1m7[m, [1;31mFailures: [0;1;31m3[m, [1;31mErrors: [0;1;31m1[m, [1;33mSkipped: [0;1;33m1[m, Time elapsed: 19.683 s[1;31m <<< FAILURE![m - in jbehave.stories.[1mStoryRunnerIT[m
[ERROR] Given Login with 'ADMIN' in 'Env'(jbehave.steps.Login)  Time elapsed: 13.357 s  <<< FAILURE!
java.lang.AssertionError: Login Button is not visible
	at jbehave.steps.Login.LoginToSiebel(Login.java:23)

[ERROR] Scenario: Verify MultiLogin  Time elapsed: 13.381 s  <<< FAILURE!
java.lang.AssertionError: scenario failed!

[ERROR] Login.story  Time elapsed: 13.703 s  <<< FAILURE!
java.lang.AssertionError: story failed!

[ERROR] jbehave.stories.StoryRunnerIT  Time elapsed: 3.008 s  <<< ERROR!
java.lang.RuntimeException: 
org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
org.jbehave.core.embedder.PerformableTree$SomethingHappened@62d40d5: java.lang.AssertionError: Login Button is not visible
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: 
Failures in running stories: 
org.jbehave.core.embedder.PerformableTree$SomethingHappened@62d40d5: java.lang.AssertionError: Login Button is not visible
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] [1;31mFailures: [m
[ERROR] [1;31m  story failed![m
[ERROR] [1;31m  scenario failed![m
[ERROR] [1;31m  Login.LoginToSiebel:23 Login Button is not visible[m
[ERROR] [1;31mErrors: [m
[ERROR] [1;31m  JUnit4Provider.invoke:159->executeTestSet:236->executeWithRerun:272->execute:365 » Runtime[m
[INFO] 
[ERROR] [1;31mTests run: 7, Failures: 3, Errors: 1, Skipped: 1[m
[INFO] 
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- serenity-maven-plugin:1.4.0:aggregate (serenity-reports) @ sjb ---
[INFO] webdriver.chrome.driver=C:\OpenUI-SJBPushkar\lib\geckodriver.exe
[INFO] serenity.project.name=Open UI Serenity JBehave
[INFO] current_project.base.dir: C:\OpenUI-SJBPushkar
[INFO] Generating test results for 1 tests
[INFO] 5 requirements loaded after 124 ms
[INFO] 5 related requirements found after 124 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 275 ms
[INFO] Configured report threads: 20
[INFO] Finished generating test results for 1 tests after 9249 ms
[INFO] 
[INFO] --- maven-failsafe-plugin:2.20:verify (default) @ sjb ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.797 s
[INFO] Finished at: 2017-08-10T13:30:33+01:00
[INFO] Final Memory: 45M/561M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.20:verify (default) on project sjb: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\OpenUI-SJBPushkar\target\failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Exception in thread "Thread-1" java.lang.RuntimeException: Process refused to die after 10 seconds, and couldn't taskkill it: Unable to find executable for: taskkill
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:143)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:247)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$200(UnixProcess.java:201)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:125)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:155)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:196)
	at net.serenitybdd.core.webdriver.servicepools.StopServiceHook.run(StopServiceHook.java:15)
Caused by: java.lang.NullPointerException: Unable to find executable for: taskkill
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:811)
	at org.openqa.selenium.os.UnixProcess.<init>(UnixProcess.java:62)
	at org.openqa.selenium.os.CommandLine.<init>(CommandLine.java:38)
	at org.openqa.selenium.os.WindowsUtils.killPID(WindowsUtils.java:178)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:138)
	... 7 more

**Comment by bebef1987** [comment]
Yes add the gecko drive to the system path.
Here you can find more info about how to do this: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver#Setting_up_the_geckodriver_executable

**Comment by push2212** [comment]
@bebef1987 I have added the gecko to the system path, however it did not resolve the issue.

**Comment by wakaleo** [comment]
If the browser is opening but with no URL, it is a Selenium compatibility issue and not a Serenity one. Make sure you are using the latest version of Serenity (1.5.4-rc.1) which is compatible with Selenium 3.4

**Comment by push2212** [comment]
@wakaleo Thanks , where can I get the latest version of Serenity or can I make some changes in the version 1.4 to update it ? Please suggest

**Comment by bebef1987** [comment]
Update your POM dependency version

**Comment by push2212** [comment]
@bebef1987 Thanks , it worked :)

**Comment by push2212** [comment]
Hi , 

Actually the results are not getting generated after test execution(i.e. the result html page contains no data).Please suggest
