### ISSUE TITLE
Failed to load requirements: URI template of the newly created target must not be null.

### ISSUE THREAD

**Issue by tremkonzah** [serenity-bdd/serenity-core#886]
Using serenity 1.5.3 and getting the following error

`[WARNING] Failed to load requirements: URI template of the newly created target must not be null.
java.lang.NullPointerException: URI template of the newly created target must not be null.
	at jersey.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:289)
	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:76)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.readFieldMetadata(JerseyJiraClient.java:494)
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findOptionsForCascadingSelect(JerseyJiraClient.java:631)
	at net.serenitybdd.plugins.jira.requirements.JIRACustomFieldsRequirementsProvider.getRequirements(JIRACustomFieldsRequirementsProvider.java:116)
	at net.thucydides.core.requirements.RequirementsProvided.by(RequirementsProvided.java:15)
	at net.thucydides.core.requirements.reports.MultipleSourceRequirmentsOutcomeFactory.buildRequirementsOutcomesFrom(MultipleSourceRequirmentsOutcomeFactory.java:53)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:152)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:237)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:183)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)`

**Comment by cliviu** [comment]
Hi @tremkonzah , have you set **jira.url** ?

**Comment by tremkonzah** [comment]
Thanks @cliviu, working now after set jira.url in serenity.properties
