### ISSUE TITLE
executeScript("arguments[0].click() .... fails with error "org.openqa.selenium.ElementNotVisibleException" when WebElement is passed directly 

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-core#914]
SERENITY_VERSION = "1.5.9" + chromedriver latest version + Mac OS

1. User goes to https://www.etsy.com/
2. scrolls to **Shop By Category** section with below command
  ((JavascriptExecutor) getDriver()).executeScript("arguments[0].scrollIntoView(true);", getDriver().findElement(By.xpath("//span[@class='vesta-hp-category-default']")));
3. Then tries to click on one of the icon

//works fine
((JavascriptExecutor) getDriver()).executeScript("arguments[0].click();", getDriver().findElement( By.xpath("//a[@data-url-with-anchor ='https://www.etsy.com/c/toys-and-games?anchor_listing_id=544894349&ref=hp']/div/picture") ));

//Throws error
((JavascriptExecutor) getDriver()).executeScript("arguments[0].click();", shopByCategoryIconToysGames);

@FindBy(xpath="//a[@data-url-with-anchor ='https://www.etsy.com/c/toys-and-games?anchor_listing_id=544894349&ref=hp']/div/picture")
    WebElement shopByCategoryIconToysGames;

```
org.openqa.selenium.ElementNotVisibleException: Timed out after 2 seconds. Element not available
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'Vikrams-MBP.fritz.box', ip: 'fe80:0:0:0:e5:e7ac:2a44:fb4c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: RemoteWebDriver
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.ajaxFindElement(SmartAjaxElementLocator.java:148)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.findElement(SmartAjaxElementLocator.java:103)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy26.getWrappedElement(Unknown Source)
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:51)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:820)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators.addAll(Iterators.java:373)
	at com.google.common.collect.Lists.newArrayList(Lists.java:165)
	at com.google.common.collect.Lists.newArrayList(Lists.java:150)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:575)
	at net.thucydides.core.webdriver.WebDriverFacade.executeScript(WebDriverFacade.java:420)
	at com.db.am.bauhaus.project.pages.MainSearchPage.clickShopByCategoryIcon(MainSearchPage.java:85)
	at com.db.am.bauhaus.project.steplib.SearchUser.search_from_shopByCategory_icon_click(SearchUser.java:36)
	at com.db.am.bauhaus.project.steplib.SearchUser$$EnhancerByCGLIB$$c3c13563.CGLIB$search_from_shopByCategory_icon_click$3(<generated>)
	at com.db.am.bauhaus.project.steplib.SearchUser$$EnhancerByCGLIB$$c3c13563$$FastClassByCGLIB$$a72390a6.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:395)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:380)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:355)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:132)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at com.db.am.bauhaus.project.steplib.SearchUser$$EnhancerByCGLIB$$c3c13563.search_from_shopByCategory_icon_click(<generated>)
	at com.db.am.bauhaus.project.steps.SearchSteps.search_by_clicking_icon_under_shopByCategory(SearchSteps.java:61)

```

**Comment by wakaleo** [comment]
Most likely not a Serenity, or even Selenium, issue, but more to do with the way the page works. Executing Javascript is _not_ the same as invoking a WebDriver command, so results often vary. Looking up elements in real-time seems to be more consistently reliable than using @FindBy.

**Comment by vikramvi** [comment]
But in this case it's static image shown on etsy home page, what do you think is the best way to handle this kind of scenario ? 

sorry, I didn't understand your statement "Looking up elements in real-time seems to be more..." please elaborate

<img width="1365" alt="screen shot 2017-08-31 at 8 48 59 pm" src="https://user-images.githubusercontent.com/308490/29939934-e3fc899a-8e8d-11e7-8a68-d6c414ffe3c8.png">

**Comment by wakaleo** [comment]
Have you tried clicking on the <a> and not the <picture>?

**Comment by vikramvi** [comment]
sorry didn't understand your last comment ? Are you referring to xpath or something else ?

**Comment by wakaleo** [comment]
Sorry, the html elements didn't render properly - try clicking on the anchor element (< A >) as opposed to the picture.

**Comment by vikramvi** [comment]
Thanks for clarification, I will close this as not an issue.

I'm not sure why etsy has added so much complications in web page design.
