### ISSUE TITLE
Maven dependencies error when upgrade serenity core version to latest 1.5.9 - java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V 

### ISSUE THREAD

**Issue by ibmer921150** [serenity-bdd/serenity-core#923]
[maven project ] Update the serenity core version from 1.5.0-rc.1 to latest version 1.5.9

Then it show guava dependence need be upgraded.  

	<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>23.0</version>
		</dependency>

Then upgrade the guava version. And run test cases, it does not show dependence issue, but fail the test case as the following error. 

ERROR!
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V

**Comment by wakaleo** [comment]
Could you check with 1.5.12?

**Comment by tfredett** [comment]
I have the same issue, I am currently attempting to setup Serenity using the current latest version `1.6.0`. It happens when attempting to use chrome. Have the chromedriver `2.32` and chrome `61.0.3163.100`.

I also attempted to bump guava to version 23 as well, and same issue still occurs.

Currently trying to use with Selenium Java `3.5.3` and Java `1.8.144`

`java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V`

**Comment by wakaleo** [comment]
Do you have a full stack trace?

**Comment by tfredett** [comment]
```
 java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
at net.serenitybdd.core.webdriver.servicepools.DriverServiceExecutable.checkForMissingBinaries(DriverServiceExecutable.java:106)
  at net.serenitybdd.core.webdriver.servicepools.DriverServiceExecutable.asAFile(DriverServiceExecutable.java:98)
  at net.serenitybdd.core.webdriver.servicepools.ChromeServicePool.chromeDriverExecutable(ChromeServicePool.java:44)
  at net.serenitybdd.core.webdriver.servicepools.ChromeServicePool.newDriverService(ChromeServicePool.java:25)
  at net.serenitybdd.core.webdriver.servicepools.ChromeServicePool.newDriverService(ChromeServicePool.java:12)
  at net.serenitybdd.core.webdriver.servicepools.DriverServicePool.driverServiceWithName(DriverServicePool.java:54)
  at net.serenitybdd.core.webdriver.servicepools.DriverServicePool.getDriverService(DriverServicePool.java:45)
  at net.serenitybdd.core.webdriver.servicepools.DriverServicePool.start(DriverServicePool.java:60)
  at net.serenitybdd.core.webdriver.servicepools.DriverServicePool.ensureServiceIsRunning(DriverServicePool.java:86)
  at net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider.getDriverServicePool(ChromeDriverProvider.java:29)
  at net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider.newInstance(ChromeDriverProvider.java:48)
  at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:125)
  at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:153)
  at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:144)
  at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:114)
  at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:189)
  at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:184)
  at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:828)
  at net.serenitybdd.core.pages.PageObject.open(PageObject.java:738)
  at net.serenitybdd.core.pages.PageObject.open(PageObject.java:726)
  at step_definitions.designer.codelists.StepDefsDesignerCodelists.iNavigateToTheTestPage(StepDefsTestPage.java:24)
  at ✽.When I navigate to the codelists designer page(/Users/tfredett/Development//cucumber-src/features/functional_tests//TEST_FEATURE.feature:10)
```

**Comment by tfredett** [comment]
Looking at DriverServiceExecutable at a glance. It looks like `com.google.common.base.Preconditions` is not being imported. I would be curious to see what would happen if we added that as an import to the file.

**Comment by tfredett** [comment]
I ended up resolving my issue with this. It turns out I had a jar-hell issue. Specifically I had a web application also using guava, that required version 18 of that. I was unable to bump that up. So I instead went and moved serenity into is own module in intellij, and set it to use the things it needed separate from my web application. Once I did that, it was able to boot Chrome successfully without issue.

**Comment by wakaleo** [comment]
Thanks for the update.

**Comment by sumit-global** [comment]
I am still facing same issue with serenity version 1.9.16, what I observed serenity itself downloads different versions of guava(refer screenshot), I don't have any other dependency which uses guava(checked same with dependecy:tree) still getting above exception while launching browser. 

Please find stack trace for reference.

java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
	at net.serenitybdd.core.webdriver.servicepools.DriverServiceExecutable.checkForMissingBinaries(DriverServiceExecutable.java:122)
	at net.serenitybdd.core.webdriver.servicepools.DriverServiceExecutable.asAFile(DriverServiceExecutable.java:92)
	at net.serenitybdd.core.webdriver.servicepools.InternetExplorerServicePool.driverExecutable(InternetExplorerServicePool.java:44)
	at net.serenitybdd.core.webdriver.servicepools.InternetExplorerServicePool.newDriverService(InternetExplorerServicePool.java:26)
	at net.serenitybdd.core.webdriver.servicepools.InternetExplorerServicePool.newDriverService(InternetExplorerServicePool.java:12)
	at net.serenitybdd.core.webdriver.servicepools.DriverServicePool.driverServiceWithName(DriverServicePool.java:55)
	at net.serenitybdd.core.webdriver.servicepools.DriverServicePool.getDriverService(DriverServicePool.java:46)
	at net.serenitybdd.core.webdriver.servicepools.DriverServicePool.start(DriverServicePool.java:61)
	at net.serenitybdd.core.webdriver.servicepools.DriverServicePool.ensureServiceIsRunning(DriverServicePool.java:87)
	at net.serenitybdd.core.webdriver.driverproviders.InternetExplorerDriverProvider.getDriverServicePool(InternetExplorerDriverProvider.java:36)
	at net.serenitybdd.core.webdriver.driverproviders.InternetExplorerDriverProvider.access$100(InternetExplorerDriverProvider.java:27)
	at net.serenitybdd.core.webdriver.driverproviders.InternetExplorerDriverProvider$TryAtMost.toStartNewDriverWith(InternetExplorerDriverProvider.java:82)
	at net.serenitybdd.core.webdriver.driverproviders.InternetExplorerDriverProvider.retryCreateDriverOnNoSuchSession(InternetExplorerDriverProvider.java:70)
	at net.serenitybdd.core.webdriver.driverproviders.InternetExplorerDriverProvider.newInstance(InternetExplorerDriverProvider.java:62)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:127)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:149)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:140)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:110)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:181)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:860)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:761)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:749)
![guava](https://user-images.githubusercontent.com/24950602/45619608-8b052b80-ba97-11e8-8e88-188bdc714819.PNG)

**Comment by wakaleo** [comment]
@sumit-global You need to do a dependency analysis to find the references to guava in your project. If Serenity downloads more than one version (it shouldn't) you may be using older versions of some of the libraries.

**Comment by sumit-global** [comment]
First of all thanks for your quick response @wakaleo , I did analysis and run mvn dependency:tree -Dverbose to check is there any another lib using guava but I didn't found any only serenity using guava dependency, refer below:

+- net.serenity-bdd:serenity-screenplay:jar:1.9.9:compile
[INFO] |  |  +- (com.google.guava:guava:jar:23.6-jre:compile - omitted for duplicate)
[INFO] |  |  +- (com.google.inject:guice:jar:4.1.0:compile - omitted for duplicate)

I am not sure about this omitted duplicate..

Please suggest what and where I need to do analysis..

Thanks in advance.

**Comment by sumit-global** [comment]
I observed only 23.6-jre guava folder contains executable jar file rest only contains POM, SHA1 and repositories file

**Comment by wakaleo** [comment]
This sounds like a project/environment specific issue. Possibly try deleting your maven repo. If you can't figure it out, we can take a closer look at your project directly as part of one of the commercial support contracts (https://johnfergusonsmart.com/serenity-bdd-mentoring/) (if your company has opted for commercial Serenity support)

**Comment by punkratz312** [comment]
I had the same issue: make sure to use the latest maven version some tutorials are outdated.
