### ISSUE TITLE
Jbehave lifecycle after and gradle error 

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#924]
Hello, 

- serenity-core & serenity-gradle : 1.5.9
- serenity-jbehave : 1.27

Actually, I have a story with this format, delete_a_project.story :
```
Meta:

Lifecycle:
   Before:
      Given...
      When...
      Then...
   After:
   Outcome: ANY
      Given...

Scenario: Should delete a project
   Given...
   Then...
```

When I run it from the IDE, no problem.
But when I run it with gradle (>gradle clean test aggregate), I have this error in the console : 
```
delete_a_project.story.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed

Scenario: Should delete a project.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed
```

And in the gradle report :
```
java.lang.RuntimeException: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
stories/delete_a_project.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: stories/delete_a_project.story
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:169)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
stories/delete_a_project.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: stories/delete_a_project.story
	at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:553)
	at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:238)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:216)
	at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:167)
	... 29 more```
```

**But in the Serenity report, everything is green and fine. And the test has been well executed.**

When I delete the part :
```
   After:
   Outcome: ANY
      Given...
```
 this error disappears. 

I have tested that : https://groups.google.com/forum/#!topic/thucydides-users/E7INo02X3Wk , without success.

Any suggestion ? Thanks !

**Comment by mmanach** [comment]
To give more info, with a maven config and a maven verify, I do not reproduce this issue.

**Comment by wakaleo** [comment]
Can you provide a project that reproduces the issue?

**Comment by mmanach** [comment]
Sure : https://github.com/mmanach/serenity-issue-924

**Comment by mmanach** [comment]
One more thing about this "after" issue, on the serenity report : 
![serenity report after steps](https://user-images.githubusercontent.com/29480659/30476017-fb9b4600-9a08-11e7-8075-53292e7abeeb.png)

The after steps are not displayed like the other steps, with the tree-view expandable.

**Comment by mmanach** [comment]
Hi @wakaleo, did you manage to reproduce with https://github.com/mmanach/serenity-issue-924 ?

**Comment by wakaleo** [comment]
It's in our backlog.

**Comment by mmanach** [comment]
Hi, 

I just update my gradle.settings with latest versions : 

- serenity-core and gradle : 1.5.11
- serenity-jbehave : 1.28

And now, when running tests with gradle, all tests are failing in console : 
```
talend.runner.CancelAProject > cancel_a_project.story.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed

talend.runner.CancelAProject > Scenario: Should cancel a new project.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed

talend.runner.CheckSubscriptionInfo > check_subscription_info.story.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed

talend.runner.CheckSubscriptionInfo > Scenario: Should display licence information.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed

talend.runner.DeleteAProject > delete_a_project.story.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed

talend.runner.DeleteAProject > Scenario: Should delete a project.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed

talend.runner.AddAProject > add_a_project.story.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed

talend.runner.AddAProject > Scenario: Should add a new project.classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed
```

While all tests are green in serenity-report.

**Comment by wakaleo** [comment]
I had a quick look and I can reproduce it, but can't see where it is coming from, other than somewhere in the Gradle code that is being called by JBehave. It could be some kind of JBehave bug or incompatibility. Please feel free to dig in on your side and propose a PR if you find anything.

**Comment by mmanach** [comment]
@wakaleo Hi, with serenity 1.6.5 the gradle error is fixed, but in the report, there is still the problem mentionned in https://github.com/serenity-bdd/serenity-core/issues/924#issuecomment-329731273
