### ISSUE TITLE
Wait is not working properly whwn using `withTimeoutOf`

### ISSUE THREAD

**Issue by bebef1987** [serenity-bdd/serenity-core#928]
If we use `withTimeoutOf` in a wait call the framework tries to find the element.
Because of this if the element is not present we get a default element not present error.

See the test here:
https://github.com/bebef1987/demo-project/tree/wait_Demo

It looks like we try to find the element in the `withTimeoutOf` calls:
```
org.openqa.selenium.NoSuchElementException: Timed out after 10 seconds. Element not found
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'CLU-946PW02', ip: '10.68.163.33', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_101'
Driver info: driver.version: unknown
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.ajaxFindElement(SmartAjaxElementLocator.java:151)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.findElement(SmartAjaxElementLocator.java:103)


#####Here we do a find element call######

	at net.serenitybdd.core.pages.WebElementResolverByElementLocator.resolveForDriver(WebElementResolverByElementLocator.java:27)

####################


	at net.serenitybdd.core.pages.WebElementFacadeImpl.getElement(WebElementFacadeImpl.java:173)
	at net.serenitybdd.core.pages.WebElementFacadeImpl.withTimeoutOf(WebElementFacadeImpl.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.thucydides.core.annotations.locators.AbstractSingleItemHandler.invoke(AbstractSingleItemHandler.java:45)
	at com.sun.proxy.$Proxy23.withTimeoutOf(Unknown Source)
	at com.test.demoProject.pages.FirstPage.waitForElementExtendedWait(FirstPage.java:22)
	at com.test.demoProject.steps.FirstStep.waitForElementExtendedWait(FirstStep.java:25)
	at com.test.demoProject.steps.FirstStep$$EnhancerByCGLIB$$955ca89e.CGLIB$waitForElementExtendedWait$1(<generated>)
	at com.test.demoProject.steps.FirstStep$$EnhancerByCGLIB$$955ca89e$$FastClassByCGLIB$$9a38dfc5.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:395)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:380)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:355)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:132)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at com.test.demoProject.steps.FirstStep$$EnhancerByCGLIB$$955ca89e.waitForElementExtendedWait(<generated>)
	at com.test.demoProject.tests.SearchTest.waitForElementExtendedWait(SearchTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:471)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:446)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:252)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Somehow in the stack trace we do a `findElement`

https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementResolverByElementLocator.java#L27

**Comment by bebef1987** [comment]
This might be a easy fix if we change:

https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/serenitybdd/core/pages/WebElementFacadeImpl.java#L309

to

`return wrapWebElement(driver, bySelector,`

**Comment by wakaleo** [comment]
Thanks, something very similar should do the trick.

**Comment by bebef1987** [comment]
Thanks for the quick fix

**Comment by wakaleo** [comment]
Made much easier because of the sample project and detailed analysis on your part.
