### ISSUE TITLE
I got net.serenitybdd.core.exceptions.SerenityManagedException: Class net.serenitybdd.core.pages.RenderedPageObjectView$2 does not implement the requested interface java.util.function.Function

### ISSUE THREAD

**Issue by aburlutskiy** [serenity-bdd/serenity-core#929]
Hello

I got this exception:

```

net.serenitybdd.core.exceptions.SerenityManagedException: Class net.serenitybdd.core.pages.RenderedPageObjectView$2 does not implement the requested interface java.util.function.Function
	at net.thucydides.core.steps.ErrorConvertor.convertToAssertion(ErrorConvertor.java:22)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:365)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:132)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	(...)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)

```
serenity-core : 1.5.10
serenity-jbehave : 1.27.0

java : 1.8

in method:

```
MyLoginPage loginPage;
@Step
    public void login(String username, String password) {
        loginPage.login(username, password);
    }
```

```
@DefaultUrl("http://192.168.1.1:8080/myapplication/")
public class MyLoginPage extends LoginPage {

    public MyLoginPage(WebDriver driver) {
        super(driver);
        open();
    }
}
```

Any suggestions?

**Comment by wakaleo** [comment]
This is a version conflict, due to your project possibly using an older version of Selenium or Serenity. I can't say any more with the information you have provided - could you check your dependency tree and provide any more stack traces that appear?

**Comment by wakaleo** [comment]
Could you check with serenity-core 1.5.12 and serenity-jbehave 1.28.0?

**Comment by wakaleo** [comment]
Closed for lack of activity.

**Comment by SriramLeela** [comment]
Hi Wakaleo,

While working on API test automation using Serenity BDD & rest assured, encountered below issue and not able to fix it. please help regarding this;

[31mnet.serenitybdd.core.exceptions.SerenityManagedException: Premature end of Content-Length delimited message body (expected: 427; received: 24
      	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
      	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
      	at org.apache.http.conn.EofSensorInputStream$read.call(Unknown Source)
      	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.convertStreamToByteArray(RestAssuredResponseOptionsGroovyImpl.groovy:463)
      	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      	at java.lang.reflect.Method.invoke(Unknown Source)
      	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
      	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
      	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
      	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
      	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)

**Comment by wakaleo** [comment]
The error is being reported by RestAssured, and seems to indicate a problem with the format of the response it is receiving from the serve.

**Comment by adityabhargav** [comment]
> Could you check with serenity-core 1.5.12 and serenity-jbehave 1.28.0?

getting the same issue even though using serenity-core - 2.0.56
