### ISSUE TITLE
serenity 1.5.10 : java.lang.NoClassDefFoundError: ch/lambdaj/function/convert/Converter

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#931]
Hello,

I have just updated serenity-core and gradle-plugin from 1.5.9 to 1.5.10, and now when I run a test or gradle I have got a initializationError : 
```
java.lang.NoClassDefFoundError: ch/lambdaj/function/convert/Converter

	at net.serenitybdd.jbehave.SerenityStories.stepsFactory(SerenityStories.java:85)
	at org.jbehave.core.ConfigurableEmbedder.configuredEmbedder(ConfigurableEmbedder.java:126)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.<init>(SerenityReportingRunner.java:68)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.<init>(SerenityReportingRunner.java:62)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: ch.lambdaj.function.convert.Converter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```

Any idea ? Thanks.

**Comment by mmanach** [comment]
May be linked to https://github.com/serenity-bdd/serenity-core/commit/48b9d98a17edfeb204ac0733f12661ade3d77330

**Comment by navvro** [comment]
@mmanach Yep, it is linked to this. Adding dependency to lambdaj fixes this.

**Comment by wakaleo** [comment]
The correct fix is to update to the latest version of serenity-jbehave (1.1.28).

**Comment by navvro** [comment]
@wakaleo I got the same error with serenity-cucumber (I do not use jBehave). I am using 1.5.11 for core and 1.5.4 for serenity-cucumber.

**Comment by wakaleo** [comment]
Do you have the stack dump?

**Comment by wakaleo** [comment]
Actually, 1.5.4 is quite old. You will need to use 1.5.7.

**Comment by navvro** [comment]
`[INFO] Running CucumberTestRunner
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.092 s <<< FAILURE! - in CucumberTestRunner
[ERROR] initializationError(CucumberTestRunner)  Time elapsed: 0.011 s  <<< ERROR!
java.lang.NoClassDefFoundError: ch/lambdaj/function/convert/Converter
Caused by: java.lang.ClassNotFoundException: ch.lambdaj.function.convert.Converter
`
