### ISSUE TITLE
Unable to Run Serenity tests with phantomjs or htmlunit driver

### ISSUE THREAD

**Issue by prat23k** [serenity-bdd/serenity-core#934]
Hi,
Can anyone help me to run tests using phantomjs or htmlunit driver.

Issue1: When i try to execute tests with phantomjs driver i got below error

phantomjs version: 2.1.1
Serenity:1.5.4-rc.2
[ERROR -xxxxx] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1505903156547

 phantomjs://platform/console++.js:263 in error

Issue2: When i try to execute with htmlunit driver got below error

net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: java.net.MalformedURLException: unknown protocol: about

Thanks

**Comment by vuthelinh** [comment]
If you want to try run in headless mode. You can add this option into **serenity.properties** file
`chrome.switches=headless`

More details here: https://www.linkedin.com/pulse/short-guide-how-configure-chromedriver-serenity-bdd-smart

**Comment by prat23k** [comment]
@vuthelinh thanks for the reply,i would like to run headless tests on chrome,firefox and ie driver.

Is there any other alternative solution.

**Comment by wakaleo** [comment]
Chrome is the only "real" browser that supports headless mode. PhantomJS should generally work, but the error you are reporting looks like an incorrect URL or a phantomjs bug.

**Comment by prat23k** [comment]
@wakaleo  Thanks for the reply,can you help me out to resolve below issue with htmlunit driver

: When i try to execute with htmlunit driver got below error

net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: java.net.MalformedURLException: unknown protocol: about

**Comment by wakaleo** [comment]
You are trying to open a url with the wrong syntax. What does your calling code look like?

**Comment by prat23k** [comment]
I am using below code to open url

PageObject page = new xxxPage(getDriver());
        page.open();
        getDriver().navigate ().to ("javascript:document.getElementById('overridelink').click()");
        page.getDriver().manage().window().maximize();

**Comment by wakaleo** [comment]
Visibly, PhantomJs doesn't like the "javascript:" protocol. Does it work with plain Selenium?

**Comment by prat23k** [comment]
yes it works with plain selenium.

**Comment by wakaleo** [comment]
Hmmm, "java.net.MalformedURLException: unknown protocol: about" is a Selenium error, not a Serenity one. Do you have a more detailed stack trace?

**Comment by prat23k** [comment]
yes below exception thrown with htmlunit driver


et.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: java.net.MalformedURLException: unknown protocol: about
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'L00051294', ip: '192.168.1.104', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: unknown
	at net.serenitybdd.core.exceptions.SerenityManagedException.detachedCopyOf(SerenityManagedException.java:21)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:364)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:132)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at com.vocalink.pbba.thucydides.portal.steps.LoginSteps$$EnhancerByCGLIB$$71abcc38.openOpsPortal(<generated>)
	at com.vocalink.pbba.serenity.portal.testcases.defsteps.LoginDefSteps.givenUserIsOnOpsLoginPage(LoginDefSteps.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1088)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:953)
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1027)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:898)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wakaleo** [comment]
The code you show is just calling WebDriver directly, so I suspect the problem is a library one. What version of Selenium did you try with?

**Comment by prat23k** [comment]
ok i am using serenity 1.5.4-rc2 and selenium -3.4.0 and htmlunit driver -2.26

**Comment by wakaleo** [comment]
Can you share the pure selenium code that works?

**Comment by wakaleo** [comment]
After investigation, the "javascript:" protocol seems to be supported by Firefox and phantoms, but not by chrome or htmldriver. I don't think this is related to Serenity.

**Comment by prat23k** [comment]
Below code was working fine with chrome driver earlier it suddenly stops working after updating serenity to latest and chrome driver.

PageObject page = new xxxPage(getDriver());
page.open();
getDriver().navigate ().to ("javascript:document.getElementById('xxx').click()");
page.getDriver().manage().window().maximize();

Thank you

**Comment by wakaleo** [comment]
That would confirm that this is a chromedriver issue, not a Serenity one. Serenity has no influence on what happens in this code.

**Comment by prat23k** [comment]
yes could be i am tired with phantomjs as well unable to proceed because of below error

phantomjs://platform/console++.js:263 in error
(net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: Timed out after 2 seconds. Element not found
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html

looks like phantomjs issue
