### ISSUE TITLE
Getting java.lang.NullPointerException: at index 1 while reading data from csv file

### ISSUE THREAD

**Issue by muli09** [serenity-bdd/serenity-core#952]
while  reading the data from csv file but only 
 when i update the cdv file with excel @UseTestDataFrom(value="testdata/subscriber/counts.csv",separator='|'),getting Nullpointer exception
Please find the error trace.

java.lang.NullPointerException: at index 1
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:242)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:232)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:281)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:239)
	at net.thucydides.core.model.DataTableRow.<init>(DataTableRow.java:18)
	at net.thucydides.core.model.DataTableRow.<init>(DataTableRow.java:14)
	at net.thucydides.core.model.DataTable$DataTableBuilder$1.convert(DataTable.java:252)
	at net.thucydides.core.model.DataTable$DataTableBuilder$1.convert(DataTable.java:249)
	at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
	at ch.lambdaj.Lambda.convert(Lambda.java:986)
	at net.thucydides.core.model.DataTable$DataTableBuilder.andMappedRows(DataTable.java:245)
	at net.serenitybdd.junit.runners.DataDrivenAnnotations.getParametersTableFromTestDataSource(DataDrivenAnnotations.java:67)
	at net.serenitybdd.junit.runners.SerenityParameterizedRunner.buildTestRunnersFromADataSourceUsing(SerenityParameterizedRunner.java:129)
	at net.serenitybdd.junit.runners.SerenityParameterizedRunner.<init>(SerenityParameterizedRunner.java:65)
	at net.serenitybdd.junit.runners.SerenityParameterizedRunner.<init>(SerenityParameterizedRunner.java:172)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by wakaleo** [comment]
Could you try with the latest version and post the CSV data?

**Comment by muli09** [comment]
I figured it out 
getting this error only when open that file with ".excel" do the modification.
Thanks,

**Comment by muli09** [comment]
Working
