### ISSUE TITLE
Reports not getting created

### ISSUE THREAD

**Issue by jaspreetmanchinda** [serenity-bdd/serenity-core#971]
<serenity.version>1.6.5</serenity.version>
		<serenity.jbehave.version>1.30.0</serenity.jbehave.version>
<serenity-maven-plugin-version>1.6.4</serenity-maven-plugin-version>

 * Failed to generate report for TagReportingTask for TestTag{name='abc/abc', type='story'} - java.util.concurrent.ExecutionException: java.lang.StackOverflowError
java.util.AbstractList$Itr.next(AbstractList.java:358)

Stacktrace:

java.util.concurrent.ExecutionException: java.lang.StackOverflowError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.thucydides.core.reports.html.Reporter.generateReports(Reporter.java:59)
	at net.thucydides.core.reports.html.Reporter.generateReportsFor(Reporter.java:35)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:197)
	at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports(SerenityAggregatorMojo.java:237)
	at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute(SerenityAggregatorMojo.java:183)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.StackOverflowError
	at java.util.AbstractList$Itr.next(AbstractList.java:358)
	at net.thucydides.core.reports.html.Breadcrumbs$BreadcrumbsBuilder$ParentTagFinder.from(Breadcrumbs.java:62)

**Comment by wakaleo** [comment]
Can you provide a sample project to reproduce this?

**Comment by jaspreetmanchinda** [comment]
got this on my org project, didn't try on a sample project. Let me see if i am able to reproduce it

**Comment by wakaleo** [comment]
It might be related to the names of the tags or the directories in the directory structure.

**Comment by jaspreetmanchinda** [comment]
Any quick fix for that I can try ? as earlier it was working in 1.6.3

**Comment by wakaleo** [comment]
If you can isolate the latest version were it works, that would help.

**Comment by wakaleo** [comment]
Fixed in 1.6.6
